### ISSUE TITLE
Support out of the box springboot application 

### ISSUE THREAD

**Issue by apupier** [openshift/odo#1024]
[kind/Feature]

## Which functionality do you think we should add?

Currently, SpringBoot applications are not supported out of the box. This kind of modification is required https://github.com/snowdrop/spring-boot-http-booster/blob/a5b271f3bf1356d5e46b75ef7d463ea7d462c1a9/pom.xml#L194 .

The issue is that by default there are 2 jars generated and copied to the java s2i image. Only the uberjar needs to be started but the java s2i image doesn't know which one.

potential solutions discussed:
- have java s2i image to be "smarter" by scanning all the jars and if there is a single one executable, launch this one
- have odo copying only the uberjar in case of springboot project
- have odo setting an environment variable to specify which jar to launch

## Why is this needed?

- have a far more straightforward use of springboot application with odo
- avoid to modify all examples/quickstarts/boosters

cc @geoand @jorgemoralespou

**Comment by geoand** [comment]
Although I am not an s2i expert, I am strongly in favor of the first proposed solution and would be willing to work on it.

Also cc @kadel to get his perspective as well :)

**Comment by geoand** [comment]
Let's also keep in mind that although this manifests itself OOTB with Spring Boot, it affects any Maven project that produces multiple jars (either by explicit configuration or lack of changing the defaults)

**Comment by geoand** [comment]
We need to make one correction based on a chat that @apupier and I had:

A Spring Boot application created from start.spring.io **will** work with odo, since the default behavior of the spring boot maven plugin is to add the `.original` suffix to the code-only jar.
However there seems to be fairly widespread use of the `classifier` "trick" (see: https://github.com/jboss-fuse/fuse-rest-http-booster/blob/824ceb03269309551509b1b3a0167446e596078d/pom.xml#L170) which indeed breaks odo.
That trick was probably initially added to get around a maven failsafe plugin issue, which is however better handled by what is done in: https://github.com/snowdrop/spring-boot-http-booster/blob/a5b271f3bf1356d5e46b75ef7d463ea7d462c1a9/pom.xml#L194

Nevertheless, it would be great if the OpenJDK builder image has the ability to determine the single executable jar among the potentially many jars that could be present in the `target` directory

**Comment by geoand** [comment]
@jorgemoralespou If I am not mistaken, an executable jar will always have the `Main-Class` entry in it's `META-INF/MANIFEST.MF` file.
So would it not be possible to check the existence of that entry in the jars files, and if there is only one that contains such an entry s2i could use it?

**Comment by geoand** [comment]
In such cases of course such a strategy wouldn't work and the scripts could just fall back to what they do now.

What I am proposing is simply an optimization for the common case, that the build of a project produces both an uberjar and a regular jar.

**Comment by jorgemoralespou** [comment]
IMHO this is a corner case to regular development, so I 👎 to implement this logic in s2i.
From the 3 options laid out by @apupier I would think we need the last 2:
In case of binary build: `have odo copying only the uberjar in case of springboot project`
In case of source build: `have odo setting an environment variable to specify which jar to launch`

**Comment by geoand** [comment]
@jorgemoralespou You have much more context than I do so what you describe sounds good to me :)

The options you describe however mean that `odo` will need some extra logic to understand the project type. Do we have some kind of proposal for adding such functionality?

**Comment by geoand** [comment]
If/when we have all the necessary pieces in place, I would be glad to work on this

**Comment by geoand** [comment]
@jorgemoralespou @kadel Do we have any larger issue/epic in place about providing odo the capability to recognize the type of project it's being used on and perform specific actions according to the project?

**Comment by jorgemoralespou** [comment]
No, we don't, and actually is a good issue to write. OpenShift oc CLI does some recognition. Not sure if it's on the client side though. They were looking into a specific library from GitHub for such recognition. We should probably get their feedback on this.
@geoand do you want to write the issue?

**Comment by geoand** [comment]
@jorgemoralespou Sure thing! I will create the issue and add some java specific cases that could be useful but I will need the teams help in filling out more use cases from other environments
