### ISSUE TITLE
Add regression tests against multiple versions of OpenShift

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1032]
Within our (hopefully new) CI system, we should have:

 - Multiple tests against different versions of OpenShift (3.11, 3.10, 3.9, etc.)
 - Backwards compatibility tests against older versions of Odo. For example, launching a component with 0.0.15 CLI, upgrading to 0.0.16 and then continuing to use Odo.

**Comment by geoand** [comment]
This makes me wonder, what is minimum supported version of Openshift? Do we have that in the docs?

**Comment by kadel** [comment]
> This makes me wonder, what is minimum supported version of Openshift? Do we have that in the docs?

currently it is 3.9 https://github.com/redhat-developer/odo#requirements

**Comment by geoand** [comment]
Thanks!

**Comment by kadel** [comment]
blocked on #952

**Comment by amitkrout** [comment]
This has already been configured on Openshift CI.
Currently CI tests are being run on - 3.11 (Travis), 4.2 and 4.1 (OpenShift CI)
/close
