### ISSUE TITLE
two utils packages

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1033]
Do something with the two packages that has the same name

- `"github.com/redhat-developer/odo/pkg/util"`
- `"github.com/redhat-developer/odo/pkg/odo/util"`

how about renaming `github.com/redhat-developer/odo/pkg/odo/util` to `github.com/redhat-developer/odo/pkg/odo/cmdutils`?

**Comment by metacosm** [comment]
I agree that these two packages need to be examined and possibly merged…
