### ISSUE TITLE
Support hot-reload of SpringBoot based applications

### ISSUE THREAD

**Issue by apupier** [openshift/odo#1035]
[kind/Feature]

currently using the java s2i image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift and odo watch, there is a rebuild of the image, so we have an "automatic redeployment" which can take several seconds/minutes to occur. it would be better if when modifying java classes, the Java class is hot reloaded.

some discussions on the subject https://issues.jboss.org/browse/SB-846?focusedCommentId=13637228&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13637228

## Which functionality do you think we should add?

hot-reload of SpringBoot app

## Why is this needed?

to shorten development cycle of a springboot application targeting deployment on OpenShift.

**Comment by jorgemoralespou** [comment]
This is something we should do in the future as part of optimizing the configuration for the runtimes.
There's a huge dependency, at least, with #803 for this.
