### ISSUE TITLE
self linking of the component should not be there using odo link

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#1052]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: odo v0.0.16 (82968cb0)

## How did you run odo exactly?
Running odo from the binary.

## Actual behavior
If I do `odo link` on the component and pass the same component name in the --component parameter, it works.

e.g.   odo link nodejs --component nodejs

## Expected behavior

We should handle this condition and make sure that self linking of the component is not allowed or a warning is shown.

**Comment by geoand** [comment]
Hi @mohitsuman 

This indeed should not be possible, but I am curious to what led you to executing such a command?
Where you just trying to brake stuff or was something in the command  names or help not clear?

Thanks

**Comment by mohitsuman** [comment]
Hi @geoand ,

We are working on OpenShift extension which uses odo under the hood. Now in the VSCode UI, when the user is given a list of components to link, it can be have the same component in the list and running the `odo link` succeeded into that.

We for now are handling this condition on UI and not showing the same component in the list to select, but it reminded us that `odo link` should also have a check for this.

**Comment by geoand** [comment]
@mohitsuman Thanks for the insight!

**Comment by kadel** [comment]
> I think this is something the CLI should probably not control. In this case, I think this is more a feature for the VSCode plugin and I think it solved the right way, by filtering the component there.
> 
> In any case, there's also the possibility to have the same component name in a different application, so if at any point, this issue is solved in `odo`, all different possibilities should be considered, which means that `--app` is not provided or if that it's provided it's not the same as current.

Shouldn't odo check that user is not doing something stupid on invalid? 
I think that self-linking should be something that odo should catch and error out.

Of course, it has to be smart enough to recognize that you are linking to a different component with the same name and allow that.

**Comment by geoand** [comment]
> > I think this is something the CLI should probably not control. In this case, I think this is more a feature for the VSCode plugin and I think it solved the right way, by filtering the component there.
> > In any case, there's also the possibility to have the same component name in a different application, so if at any point, this issue is solved in `odo`, all different possibilities should be considered, which means that `--app` is not provided or if that it's provided it's not the same as current.
> 
> Shouldn't odo check that user is not doing something stupid on invalid?
> I think that self-linking should be something that odo should catch and error out.
> 
> Of course, it has to be smart enough to recognize that you are linking to a different component with the same name and allow that.

I agree that odo should try and prevent things that don't make sense

**Comment by mohitsuman** [comment]
@dharmit any update for this ?

**Comment by dharmit** [comment]
@mohitsuman I'm adding this to our team discussion. Mainly because this is something we need to discuss for odo v2 as well even though this issue was opened for v1.

**Comment by mohitsuman** [comment]
@dharmit sure thing, let us know the discussion conclusion.

**Comment by dharmit** [comment]
@mohitsuman I'm closing this one since it's being tracked as an acceptance criterion on #3423. 

/close

**Comment by dharmit** [comment]
@mohitsuman this has been fixed by https://github.com/openshift/odo/pull/4777.
