### ISSUE TITLE
Give odo the ability to understand the type of project it is being used for and use that information to provide a more seamless experience

### ISSUE THREAD

**Issue by geoand** [openshift/odo#1085]
[kind/Feature]

## Which functionality do you think we should add?

In it's current form, odo does not have any insights into the type of project it's being used for. All it knows (because the user supplied this information) is the s2i builder image that should be used to deploy the project on Openshift.

## Why is this needed?

Although the current situation ensures that odo can potentially work with any of the runtimes supported by s2i, it means that users might have to jump through some hoops to get the project working, depending on how they have organized their project.
The ideal situation (at least when the user uses any of the popular runtimes/frameworks and doesn't have any exotic project setup) would be for everything to just work without forcing the user to specify for example environment extra variables on the supervisord pod.

## Examples use cases:

* Some of the Red Hat Spring Boot guides use a specific project [setup](https://github.com/jboss-fuse/fuse-rest-http-booster/blob/824ceb03269309551509b1b3a0167446e596078d/pom.xml#L170) that prevents s2i to properly deploy the uber jar unless a [specific](https://github.com/jboss-fuse/fuse-rest-http-booster/blob/824ceb03269309551509b1b3a0167446e596078d/.openshiftio/application.yaml#L23) environment variable is set. (this relates to issue #1024)
Being able to recognize this use case and make odo drive s2i properly (for example by setting this environment variable automatically or even better by copying the proper binary in case of a binary build) would prevent frustration for users that are following (semi-)official Red Hat guides.
* Most Red Hat guides for Java applications contain the code for various microservices in a single git repo for convenience. (this relates to issue #1014)
Another scenario which might be more common is to have a git repo with multiple modules, only one of which however results in the creation of a deployable uberjar.
It might be of interest to create the necessary components when a such a project is recognized and drive s2i properly.
* For NodeJS applications we could ensure that `node_modules` is ignored (relates to #1119 and #647 )

I am sure there are many more use cases for other runtimes / frameworks as well.

Any thoughts @jorgemoralespou @kadel @cmoulliard @metacosm @iocanel @gytis?

**Comment by metacosm** [comment]
How would this materialize at the UI level, though?

**Comment by geoand** [comment]
For what I have in mind, most things would be done behind the scenes (like setting environment variables to drive s2i).

One UI/UX change I can think of is that if odo knows what project it's working with, it can perhaps deduce the appropriate s2i image builder

**Comment by metacosm** [comment]
That's also kind of what I am thinking, however, how would `odo` know the type of project it deals with? Would we have a set of heuristics to detect it?

**Comment by geoand** [comment]
@jorgemoralespou mentioned that the `oc` team might have done something similar.
If nothing ready exists, then yes we would have to develop some heuristics

**Comment by jorgemoralespou** [comment]
@geoand the library they looked at was https://github.com/github/linguist

**Comment by geoand** [comment]
Thanks @jorgemoralespou!

**Comment by jorgemoralespou** [comment]
But the problem is that even if you know a repo has a pom.xml, you won't know what is the most appropriate image to use. What if there are many similar images that knows how to build java (maven) (e.g. java, fabric8-s2i, java-s2i, wildfly, eap,....)?

To the main topic of the issue, I did write some comments here: https://github.com/redhat-developer/odo/issues/600#issuecomment-444097323

**Comment by geoand** [comment]
@jorgemoralespou I was thinking that we could include even deeper support, meaning that we could inspect the pom and make decisions based on that.
The way I see it, it would be great for runtime/framework experts to have the ability to encode their knowledge in odo making the developer experience as smooth as possible for users. In the case of maven, we might encode knowledge of Maven itself (like you have eloquently stated in the linked comment) and perhaps of the some typical plugin configurations (like the Spring Boot Maven plugin)

**Comment by metacosm** [comment]
I don't think that `linguist` will indeed be enough, and we might need to be able to provide `odo` extensions with a documented SPI so that people can indeed add their own framework / runtime detection tool and trigger appropriate actions.

**Comment by geoand** [comment]
@metacosm my thoughts exactly!

**Comment by geoand** [comment]
@metacosm Perhaps this would be interesting also in the context of odo plugins...
