### ISSUE TITLE
Add Odo to Chocolatey

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1095]
I'm just setting up a Windows VM and Chocolatey makes installation *so much easier*. 

We used Chocolatey on another one of our projects. Let's use it with Odo to make the developer experience much better!

https://chocolatey.org

We've had previous issues opened regarding this:
 - https://github.com/redhat-developer/odo/issues/70
 - https://github.com/redhat-developer/odo/issues/145

Both of which Chocolatey was suggested to be nice-to-have but it had not been implemented.

**Comment by geoand** [comment]
I'm learning new things everyday :P

**Comment by cdrage** [comment]
I'm going to close this since we just download the .exe anyways :)
