### ISSUE TITLE
Complete UI review

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1102]
[kind/Enhancement]
## Which functionality do you think we should update/improve?
While the UI has improved, there are still lots of inconsistency between how different commands output results.

## Why is this needed? 
The UI should be consistent.

**Comment by cdrage** [comment]
/lifecycle frozen

I'll do a review of all commands (eventually).

I've assigned this to myself.

**Comment by dharmit** [comment]
/close 

The issue is kinda vague as-is. Sure there are gaps in the command outputs. We hope to get more specific issues through the ongoing docs effort.
