### ISSUE TITLE
Should push not do anything if there aren't any local changes?

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1103]
[kind/Feature]
## Which functionality do you think we should add?
`push` should not do anything and return immediately if there are no local changes.

## Why is this needed?
Not needed but would be nice! :)

**Comment by geoand** [comment]
How would odo know if there are any local changes since the last push?

**Comment by metacosm** [comment]
Timestamp comparison? Not sure that it would indeed be worth the effort…

**Comment by geoand** [comment]
Sounds like a nice to have, but I am worried about that it could create problems for us :)

**Comment by kadel** [comment]
This is already implemented
/close
