### ISSUE TITLE
Suggest a valid input for commands which require such an input

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1104]
[kind/Feature]

## Which functionality do you think we should add?
For commands that require a user input, it would be nice to have a valid input automatically generated on pressing `tab` (i.e. using the completion mechanism) so that users can know what would be generated and have the opportunity to change it (and be lazy as well!). Might be difficult to implement without completely switching to flags instead of positional arguments, though…

## Why is this needed?
Not needed but would be nice.

**Comment by geoand** [comment]
Which types of input do you have in mind @metacosm ?

**Comment by metacosm** [comment]
@geoand service / app / component names for example.

**Comment by geoand** [comment]
@metacosm I see, thanks!
