### ISSUE TITLE
Add odo ssh command

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1105]
[kind/Feature]

## Which functionality do you think we should add?
`odo ssh` command would allow a user to directly log into the currently active (or the appropriate one based on `component`, `application` and `project` flags) pod to be able to examine its state without having to first hunt it down.

## Why is this needed?
Not needed but would be nice for `odo` to help user diagnose issues / check that everything is as expected.

**Comment by jorgemoralespou** [comment]
Agreed. Not sure if ssh would be better than rsh, but feature should exist. This command exists in `oc`

**Comment by cdrage** [comment]
@jorgemoralespou @metacosm 

The command exists in `oc` but let's hope that we can access this through the OpenShift golang library.

**Comment by kadel** [comment]
> The command exists in `oc` but let's hope that we can access this through the OpenShift golang library.

It shouldn't be a problem to implement this. It is just executing `/bin/bash` or other shell and redirecting input and output to local console. It should be pretty similar to what we already do for copying files.

**Comment by cdrage** [comment]
/lifecycle frozen

IMO we should (eventually) implement this into `odo debug` subset of commands.

**Comment by valaparthvi** [comment]
@metacosm I am closing this issue because `odo exec` seems to serve the purpose described in this issue. Feel free to reopen it if I misunderstood the issue and you think otherwise.
