### ISSUE TITLE
Install completion fails on windows terminal like powershell and command prompt

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1109]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10
- Output of `odo version`: 
```
PS C:\Users\cdk\Downloads> .\odo-windows-amd64.exe version
odo v0.0.17 (1d10127b)
the server has asked for the client to provide credentials
```

## How did you run odo exactly?
Steps tp reproduce:
1. Use release version of [ODO-v0.0.17](https://github.com/redhat-developer/odo/releases/download/v0.0.17/odo-windows-amd64.exe) windows bit
2. Open terminal ```Powershell``` or ```command prompt```
3. Run ```odo-windows-amd64.exe --complete```
```
PS C:\Users\cdk\Downloads> .\odo-windows-amd64.exe --complete
Install completion for odo? y
Installing...
Install failed! Did not find any shells to install
```

## Actual behavior
```
PS C:\Users\cdk\Downloads> .\odo-windows-amd64.exe --complete
Install completion for odo? y
Installing...
Install failed! Did not find any shells to install
```

## Expected behavior
Install completion for odo should be successful on windows terminal like ```powershell``` and ```command prompt```.

**Comment by metacosm** [comment]
Completion is currently only supported on `bash`, `zsh` or `fish` shells. No surprise here that it doesn't work on `powershell` or `cmd`.

**Comment by kadel** [comment]
> Completion is currently only supported on `bash`, `zsh` or `fish` shells. No surprise here that it doesn't work on `powershell` or `cmd`.

As mentioned above, the library (`github.com/posener/complete/`) that odo uses for autocompletion supports only bash,zsh, and fish.
It will be a lot of work to rewrite it to use something else. 
There would have to be a big demand for powershell completion to start considering it.
I'm not even sure if autocompletion is possible in `cmd.exe`


/close
/triage unresolved
