### ISSUE TITLE
odo url open

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1128]
open a browser with the url

similar to `odo url create --open`

**Comment by cdrage** [comment]
I'm assuming this will open the default url for that component?

Since `odo url list` is for *all* components.

**Comment by surajnarwade** [comment]
we don't have this feature now, shall we close this ?

cc @kadel  @cdrage

**Comment by cdrage** [comment]
@surajnarwade Oh no. How in the world did my flag get removed? Haha.

What are your thoughts of adding this back in @kadel ?

**Comment by kadel** [comment]
how about adding `odo url open` command.
If the component has only one url it gets automatically opened.
If there are multiple urls, the user has to provide a name `odo url open myurl`

This command should also have optional `--context` similarly as other commands

**Comment by kadel** [comment]
not a priority
/close
