### ISSUE TITLE
Validate provided parameters in service create.

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1130]
[kind/Enhancement]
## Which functionality do you think we should update/improve?
Currently parameters provided as options to the command are not validated. We should validate them before trying to create the service.

## Why is this needed? 
Improved UX.

**Comment by jorgemoralespou** [comment]
How can you know the type the parameters do support?

**Comment by metacosm** [comment]
> How can you know the type the parameters do support?

Using the same mechanism used by the interactive mode.
