### ISSUE TITLE
Write command runner for oc and odo in test package

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1131]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
The current implementation of running command in the [test suite](https://github.com/redhat-developer/odo/blob/master/tests/e2e/e2e.go#L17) looks premature. Moreover this testsuite won’t work in windows environment. So creating a generic command runner for both would be helpful

## Why is this needed? 
To run testsuite on all supported platform

**Comment by girishramnani** [comment]
we should consider after beta

**Comment by amitkrout** [comment]
Pr #1612 has the fix of ```oc``` and ```odo``` command runner.

**Comment by amitkrout** [comment]
So closing it as it has been fix via #1559.
