### ISSUE TITLE
Use tab writer for listing components

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1136]
We should be using tab writer here:
https://github.com/redhat-developer/odo/blob/master/pkg/odo/cli/application/application.go#L293

Similar to how it's implemented above here:
https://github.com/redhat-developer/odo/blob/master/pkg/odo/cli/application/application.go#L199

**Comment by surajnarwade** [comment]
@cdrage, can you please verify this issue and close accordingly if resolved.
lot of refactoring happened after Dec 14, 2018 :smile:

**Comment by girishramnani** [comment]
currently we are using tab writer for listing components and other resources. Hence closing this issue
