### ISSUE TITLE
Use variable through test terminal to run independent test feature 

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1138]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Make a generic  ```PHONY``` statement which can handle any test feature individually just by passing through variable name like ```ODO_TEST_FEATURE```. For example pass the variable in the terminal like 
```
make integration ODO_TEST_FEATURE=odoJavaE2e
```
and in the Makefile only one ```.PHONY``` can handle whatever the argument we passed. 
```
# Run integration test
.PHONY: integration
integration: ODO_TEST_FEATURE = ""
integration:
ifdef TIMEOUT
	go test -v github.com/redhat-developer/odo/tests/e2e --ginkgo.focus=$(ODO_TEST_FEATURE) -ginkgo.succinct -timeout $(TIMEOUT)
else
	go test -v github.com/redhat-developer/odo/tests/e2e --ginkgo.focus=$(ODO_TEST_FEATURE) -ginkgo.succinct -timeout 15m
endif
```

## Why is this needed? 
To remove unnecessary ```.PHONY``` statement for individual test in ```Makefile``` and make it more dynamic for developer to test their feature file just by passing it through a variable.

**Comment by surajnarwade** [comment]
Closing as this is not applicable for now
