### ISSUE TITLE
Support .s2i/environment files

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#1147]
[kind/Enhancement]
## Which functionality do you think we should update/improve?
s2i has the ability to provide along with the source an .s2i/environment file that will be read prior to the build (assemble) and run phase.
We need `odo` to mimic the behavior so that the developer can add that file to their source code and then it will be read.

## Why is this needed? 
So that a user can easily alter the build/run behavior by specifying environment variables. These need to be added or deleted when added or deleted from local file system in `push` and `watch` so that the process can be more easily controlled by the user/developer.

**Comment by kadel** [comment]
This might be also related to https://github.com/redhat-developer/odo/issues/1060

**Comment by girishramnani** [comment]
`odo config set --env` now allows users to set env variables as part of local odo config. Hence the scope of this issue has been implemented. Closing.

**Comment by kadel** [comment]
/open
a lot of s2i projects are using `.s2i/environment` file. Odo wants to support s2i so this is something that should be supported.

**Comment by dudash** [comment]
FYI, the .s2i/environment file is how Quarkus currently works with s2i:
https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started

https://quarkus.io/guides/deploying-to-openshift-s2i#deploying-the-application-as-java-application-in-openshift

**Comment by girishramnani** [comment]
Assuming we are moving to devfile, should we consider this as feature? @kadel

**Comment by kadel** [comment]
this is no longer relevant as odo is moving from using s2i to Devfiles
/close
