### ISSUE TITLE
Support Context Dir Like oc new-app

### ISSUE THREAD

**Issue by sherl0cks** [openshift/odo#1152]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
`oc create --git` needs a` --context-dir` flag like we have in  `oc new-app`

## Why is this needed? 
Allows one to create build configs that build from a subdirectory, so we can use repos like https://github.com/jboss-openshift/openshift-quickstarts

**Comment by girishramnani** [comment]
currently we don't have plans to implement multi-component in a single directory. Closing this issue for now but if someone feels this feature is needed then please re-open this issue.
