### ISSUE TITLE
Refactor Examples Into A Directory

### ISSUE THREAD

**Issue by sherl0cks** [openshift/odo#1155]
[kind/Documentation]

## What did you find missing in the documentation?
Let's refactor (examples.md)[examples.md] into `components.md` and place it under a larger directory of examples. This could include docs for #862

## What is the relevence of it?
Provides structure to grow the docs.

**Comment by girishramnani** [comment]
Our user facing documentation have been moved to https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/understanding-odo.html. So it seems this issue is not relevant anymore. Closing this issue.
