### ISSUE TITLE
Use proper wait logic instead of sleep for a specific time

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1163]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
time.Sleep() in test suite need to be improved. We need to think/implement some kind of retry logic like in a specific interval of time ```(let 1s)``` keep hitting the command for some try ```(let 10 times)```. If it returns ```0 ```or expected ```stdout``` then well and good else report timeout with error as ```command did not executed in time period of 10s```.  

## Why is this needed? 
Reduces actual time taken by test suite with time.Sleep().

**Comment by amitkrout** [comment]
@cdrage's suggestion copying from https://github.com/redhat-developer/odo/issues/1165#issue-393488259

We should create a function to grep / wait for project to appear with oc and then continue, rather than relying on sleep.

**Comment by surajnarwade** [comment]
Closing this as it is implemented
