### ISSUE TITLE
`odo` extension architecture

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1173]
[kind/Feature]

## Which functionality do you think we should add?
Adding an extension mechanism for `odo` would allow interested third-parties to extend the tool to suit their own needs without needing features to be added to `odo` itself. Extensions would work as plugins that would be dynamically loaded when the tool starts and communicate with `odo` via an event system over an event bus to be able to have decoupled extensions implemented as listeners of events produced at different stages of command execution. Commands would thus be able to push events during different stages of their execution (e.g. pre-run, post-complete, post-validate, post-run). The bus will allow interested third parties to register listeners to react to events and possibly interrupt the command processing based on this (by returning a specific error type, which will allow the bus to abort the command processing and notify listeners that might have already performed some process based on the event to revert their work).

## Why is this needed?
Not strictly needed but would be a nice to have feature. This could, in particular, allow runtimes to customize `odo`'s behavior to account for their specificity or make it easier to implement a scaffolding feature to more easily bootstrap projects. Another idea could be to use a listener to play the commands the user triggers on different clusters than the one the user is logged to…

**Comment by metacosm** [comment]
Golang issue regarding Windows support: https://github.com/golang/go/issues/19282

**Comment by johnfriz** [comment]
Hi Folks. Just wondering what the plan in to develop the plugin concept further? Is there any follow up work planned at this time?
