### ISSUE TITLE
Be More Tolerant of Network Timeouts

### ISSUE THREAD

**Issue by ALRubinger** [openshift/odo#1178]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
So I went to use `odo` to connect to an OpenShift cluster on another continent.  Here's what happened:

```
[alr@tubescreamer ~]$ odo login %URL% -u user18 -p %PASSWORD%
Login successful.

You have one project on this server: "user18"

Using project "user18".
```

Cool!  Now let's make an app.

```
[alr@tubescreamer ~]$ odo app create test
 ✗  Unable to connect to OpenShift cluster, is it down?
```

Allright; so we've hit a connection timeout.  But the problem is in the messaging; this could be improved.  I suggest the following fixes to the error message:

1) Change to say "✗  Unable to connect to OpenShift cluster, is it down? Perhaps you're hitting a network timeout?"
2) Add some context to suggest a workaround in case the timeout is not sufficient.  For instance telling the user to run `odo utils config set Timeout XX` where XX is a new timeout value in seconds, say, 20, should do the trick.

Additionally, how about increasing the default timeout?  I believe 1 second is the default?  Surely we can be more permissive, yeah?

**Comment by cdrage** [comment]
More notes / suggestions:

- If the connection is taking more than 3 seconds / too longer to connect to OpenShift, we should use a spinner or at least indicate to the user that the connection is delayed and taking a while...
