### ISSUE TITLE
Move project under OpenShift

### ISSUE THREAD

**Issue by containscafeine** [openshift/odo#118]
It was suggested a couple of times that this project be moved under the github.com/openshift/ GH org, so this issue tracks the status of that!

**Comment by kadel** [comment]
I've already send email about that.

**Comment by kadel** [comment]
This has been postponed. We will move it once the tool is a little bit more mature.

**Comment by kadel** [comment]
more info in https://github.com/redhat-developer/odo/issues/1433

**Comment by cdrage** [comment]
This has been completed!
