### ISSUE TITLE
We should output information with regards to odo service create and how to use it

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1184]
For example:

 1. We run the `odo service create` command.
 2. Afterwards, we should list what ENV variables are available, how to actually link the components as well as any other information that is available for `odo service create`

**Comment by metacosm** [comment]
@cdrage could you provide an example of what that would like?

**Comment by cdrage** [comment]
@metacosm 

So after a bit of testing, I was thinking of outputting the S2I environment variables that are available... however, that is based on each and every S2I image, for example, the mysql and mariadb examples use DB_HOST and DB_PASSWORD.

Ideally, after you deploy for example: 

`odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret`

It should output that:

 - You can link it to another component using `odo link`
 - That: `DB_USER=luke DB_PASSWORD=secret` is accessible in the other component..

**Comment by cdrage** [comment]
After digging through s2i documentation and using my Google-fu, I found that you can get the environment variables (set at runtime) using this: https://docs.openshift.com/enterprise/3.0/dev_guide/environment_variables.html

Do you know by-heart an alternative way to retrieve the environment variables (such as DB_USER and DB_PASSWORD) set by s2i?

**Comment by kadel** [comment]
> @metacosm
> 
> So after a bit of testing, I was thinking of outputting the S2I environment variables that are available... however, that is based on each and every S2I image, for example, the mysql and mariadb examples use DB_HOST and DB_PASSWORD.
> 
> Ideally, after you deploy for example:
> 
> `odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret`
> 
> It should output that:
> 
> * You can link it to another component using `odo link`
> * That: `DB_USER=luke DB_PASSWORD=secret` is accessible in the other component..

I'm confused a little bit :-( Why outputting S2I env variables?
Env variables that describe how to connect to the service are usually in Secret that is created together with Service.
I suspect that what you want is to show what is in that Secret.

It could look like this:
```
$ odo service create mariadb
...
...
MariaDB service was created. You can link your component to the service using `odo link` command.
`odo link mariadb`


$ odo link mariadb
Component "mycomponent" has been linked to "MariaDB" service.
Environment variables provided by the service:
 - DB_NAME
 - DB_USER
 - DB_PASSWORD
 - DB_HOST
```

**Comment by girishramnani** [comment]
we have show the env variables available as part of `odo link` and `odo service create` has interactive mode which provides enough information. Hence I feel the scope of this issue has been implemented.
Closing
cc @kadel
