### ISSUE TITLE
INFO output on how to use odo url create after push

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1186]
For example:

1. When we do `odo create` we output do `odo push` to continue
2. When we do `odo push`, nothing else appears.

We should add:

`To access your pushed project, run 'odo url create'`

**Comment by jorgemoralespou** [comment]
Or even add that output to `odo create` in the form of:

```
odo create nodejs frontend
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating component frontend
 ✓  Component 'frontend' was created and port 8080/TCP was opened
 ✓  Component 'frontend' is now set as active component
To push source code to the component run 'odo push'
TIP: If you want to create the URL at the same time as you create your component do 'odo create ... --create-url'
```

This could be complemented with a list of tips that would randomly show, so we show the user how to use the tool. This could be disabled via a setting.

**Comment by jorgemoralespou** [comment]
I just realized this is not related to the issue, but came to my mind as I read the issue. If you think it's a nice feature, we could add it as an issue of itself (for future).

**Comment by kadel** [comment]
url is shown when url is created
/close
