### ISSUE TITLE
Update logging documentation 

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1187]
https://openshiftdo.org/logging/

The current documentation is incorrect for erroring. We do not use glog for erroring, we should provide examples that functions must provide `err` return as errors are handled more upstream (within `cmd/` files)

**Comment by surajnarwade** [comment]
cc @anmolbabu 

ref link: https://github.com/redhat-developer/odo/pull/1123

**Comment by kadel** [comment]
done
/close
