### ISSUE TITLE
Figure out why interactive mode test does not work

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1206]
See https://github.com/redhat-developer/odo/pull/857#discussion_r248634783

**Comment by amitkrout** [comment]
Cool!!!
@metacosm Thanks, I will be happy to take this in the next sprint plan

**Comment by girishramnani** [comment]
we have a plan to test interactive mode in this issue https://github.com/openshift/odo/issues/2194.
Hence closing current issue.
