### ISSUE TITLE
Add unit tests for the completion handlers that don't have them

### ISSUE THREAD

**Issue by geoand** [openshift/odo#1225]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

We should include unit tests for the completion handlers that currently lack them: like the app completion handler

## Why is this needed? 

Since the new completion architecture allows us to write the completion handlers in go, it makes sense to test this code as we would any other piece of odo

**Comment by mohammedzee1000** [comment]
You are talking about completion handlers as in complete in complete-validate-run pattern right?

**Comment by mohammedzee1000** [comment]
Some of these have UI input which might make them harder to test, as UI does not seem to be mocked, writing tests for those that don't, should have something working soon
