### ISSUE TITLE
Unable to push changes for source code for NodeJS

### ISSUE THREAD

**Issue by mcouliba** [openshift/odo#1231]
[kind/bug]

## What versions of software are you using?
- Operating System: CENTOS
- Output of `odo version`:

odo v0.0.17 (1d10127b)

OpenShift: v3.11.43
Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?

$ odo create nodejs:8 ui --app web --local labs/web-nodejs
$ odo push ui --app web
--- Modify the source code
$ odo push ui --app web

## Actual behavior

Failed to push the changes

## Expected behavior

Pushed the changes

## Any logs, error output, etc?

Pushing changes to component: ui
 ✓   Waiting for pod to start
 ✓   Copying files to pod
⠈⠁   Building component ERR Unable to build files
+ set -eo pipefail
+ '[' -f /tmp/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source ...
mv: inter-device move failed: '/tmp/src/app' to './app'; unable to remove target: Directory not empty
mv: inter-device move failed: '/tmp/src/views' to './views'; unable to remove target: Directory not empty

 ✗   Building component
Failed to push component: ui

**Comment by anmolbabu** [comment]
@mcouliba Can you verify if this issue is relevant to latest odo master?
Bcoz in my opinion this was fixed with various fixes part of https://github.com/redhat-developer/odo/pull/1125 and https://github.com/redhat-developer/odo-supervisord-image/pull/10
It might be relevant to last odo release 0.0.17

**Comment by mcouliba** [comment]
@anmolbabu I still got the same issue using odo release 0.0.19.
`odo watch` or `odo push` give me the same error

**Comment by syamgk** [comment]
I am able to reproduce this 
steps to reproduce:
```
$ git clone https://github.com/openshift/nodejs-ex.git
$ odo create nodejs:8 customsupvisrodui --app web --local /tmp/nodejs-ex/
$ odo push
# till here it works fine
# by making changes to source locally and pushing, it fails
$ odo push
```

its happening from the [assemble-and-restart](https://github.com/redhat-developer/odo-supervisord-image/blob/master/assemble-and-restart#L6)  script in supervisord image

**Comment by girishramnani** [comment]
@syamgk shouldn't this be in review?
