### ISSUE TITLE
End-user telemetry data of odo features

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#1236]
[kind/epic]
[milestone/backlog]

As a developer or product manager on the `odo` team, I would like to get have some telemetry data to better understand how many users are using individual odo features.

This will help the team prioritize their efforts in the highest impact areas and also to figure out what some areas aren't used as much as expected. This will lead to the end-user having a better overall experience with the too. Of course, the end-user should be able to opt-out of this feature.

**Comment by metacosm** [comment]
The work I've been doing on an event system associated with plugins (i.e. telemetry could be implemented as a listener plugin) would help this effort.

**Comment by sspeiche** [comment]
This feature is still valid

/lifecycle frozen

**Comment by girishramnani** [comment]
is this something we would like to consider @sspeiche

**Comment by girishramnani** [comment]
Hello,
I had a quick chat with praveen to understand how they implemented telemetry in crc.

The tools used were
- segment.com
- https://www.woopra.com
- golang library for segmentio

So a gist of it - segmentio is where the telemetry is sent - then woopra has good visualisation built on top of it. We need to ask for access for both of these tools from @gorkem.

Now we need to implement telemetry from our end using golang library from segmentio, basically we are going to capture these things- os related information- commands executed- errors that occurred

This is the link of segment code present in crc - https://github.com/code-ready/crc/tree/master/pkg/crc/segment its quite standard and I can help you out in taking this to fit odo.
And finally this is the segment library doc for go that we have to use https://segment.com/docs/connections/sources/catalog/libraries/server/go/

while we get the access you can use Free version on segment so its not a blocker https://segment.com/pricing.

**Comment by girishramnani** [comment]
Also just so its clear we cannot capture any personally identifiable information which means we probably need to clean up the data we capture before sending

**Comment by sspeiche** [comment]
Here's the policy around what we collect and not https://developers.redhat.com/article/tool-data-collection

**Comment by girishramnani** [comment]
we should have a metric to detect users directly using odo vs people using vscode adapter / che

**Comment by kadel** [comment]
Let's start with just basic metrics we can always add more later.

What information we should send from start:
 - odo version
 - OS information
 -  name of the command that gets executed and if possible its return code
 - error messages
 - when user executes `odo push` we should send an event containing information if the cluster supports `Project` (to detect if it is OpenShift or not)
 

Later we can add more:
 - what type of component is user creating (type of devfile) (java, nodejs, python)


 @elsony Are there any other metrics that you would like to track?

**Comment by kadel** [comment]
/reopen
this is not done yet

**Comment by valaparthvi** [comment]
@kadel Is it alright if we close this issue now? We closed #4462.
From your https://github.com/openshift/odo/issues/1236#issuecomment-784205444, I missed out on _if URL is created is it Route or Ingress_, but I think we require this information, we can track it in a separate issue.

**Comment by kadel** [comment]
yes, we can close this now.
We have all core metrics implemented.
/close
