### ISSUE TITLE
Support for arbitrary runtime/framework images

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#1237]
[kind/Enhancement]

As a Developer I would like to use `odo`'s innerloop flow but I need to supply my own builder images for a variety of reasons.

Mostly it can't be expected the `odo` and the Red Hat teams (or community) provide all the language and runtime support a developer may need. There should be a well-documented way for arbitrary images be provided.

**Comment by cdrage** [comment]
@sspeiche 

Are you possibly talking about using an intuitive / Odo-like way of doing `oc import-image` ?

**Comment by sspeiche** [comment]
This feature is still valid

/lifecycle frozen

**Comment by sspeiche** [comment]
@kadel @girishramnani @cdrage I believe we can mark this as closed and claim it is accomplished by devfile support, do you agree?

**Comment by cdrage** [comment]
I agree 100% @sspeiche
