### ISSUE TITLE
Support cron application types

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#1239]
[kind/Feature]

As a Developer, I have applications that require some features such as running regularly scheduled jobs.

This should use the CronJob feature of Kubernetes and provide a simple interface for working with it.

**Comment by jorgemoralespou** [comment]
How many users use CronJobs? I'm pretty sure that as part of the inner loop a developer would most likely not test the code that will ultimately run as a CronJob in a CronJob fashion.
Also, what would the experience look like for these feature request?

I would be really interested in see if we can fit the experience that would be required into odo or not. We're making decisions before 1.0 GA that will later be difficult to change.

@sspeiche Could you provide details on the experience you think a developer would need/want/use?

**Comment by girishramnani** [comment]
This can be replicated by implementing on component level like having application logic periodically running a task. 
Currently we dont have plans to implement this for next 6 months hence closing this issue. If someone feels its relevant now, please re-open this issue
