### ISSUE TITLE
improve installation script install.sh

### ISSUE THREAD

**Issue by kadel** [openshift/odo#124]
It would be good to add parameters to control what gets installed and how.

- choosing what version to install (master vs latest release) via command line argument 
- choosing installation method, it should be possible to just copy ocdev to /usr/local/bin (no dist detection no packages)

for example something like this:
```
./install.sh [-v (master|latest)] [-t (bin|pkg)]
```

default behaviour without arguments would be what install.sh does right now - installing latest released version via packages for supported systems if a system is not supported fall back to binary copy.

**Comment by girishramnani** [comment]
is this issue still relevant?

**Comment by girishramnani** [comment]
closing this issue as its stale
