### ISSUE TITLE
Support for easily running unit tests in container (inner or outer loop)

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#1240]
[kind/Feature]

As a Developer, I would like to execute unit tests within a given container whether it is based on inner or outer loop deployments.

This could be a simple variation or streamlined flow of something like rsh. It shouldn't be required that the test artifacts have to be pre-packed into the image.

**Comment by jorgemoralespou** [comment]
@sspeiche 
Unit tests in the inner loop are executed in the assemble phase of s2i. To be able to alter the s2i pipeline that happens in the assemble script, and to be able to have odo supporting this, these steps need to be properly defined and enforced in the images.
In the outer loop, unit tests are executed as part of the build process, however that happens. Build in Jenkins or build in OpenShift triggered by Jenkins. Again, the only way to support this is to be opinionated on what type process the outer loop will follow.
