### ISSUE TITLE
Additional interactive commands

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1242]
## Which functionality do you think we should add?
An interactive mode has been implemented for `service create`. Other commands might benefit from similar effort but we need to identify such commands.

## Why is this needed?
This would improve the usability of the tool.

### Sub-tasks
- [ ] `login`
- [x] `component create` #1272
- [ ] `url create`
- [ ] `storage create`
- [ ] `link`
- [ ] `config set`
- [ ] `utils config set`

**Comment by jorgemoralespou** [comment]
Here's some that we should make interactive, if possible:

- odo login (not sure as this comes from oc)
- odo component create
- odo url create
- odo storage create
- odo link
- odo config set (this is not yet there, proposal coming)
- odo utils config set

**Comment by kadel** [comment]
> Here's some that we should make interactive, if possible:
> 
> * odo login (not sure as this comes from oc)
> * odo component create
> * odo url create
> * odo storage create
> * odo link
> * odo config set (this is not yet there, proposal coming)
> * odo utils config set

+1 on the list.
`odo login` already have of interactive mode (inherited from `oc`). It looks slightly different, but I don't think that that is an issue.  If you run `odo login` it will ask for username and password.

`odo component create` should be next candidate for interactive mode, as this is the command that is run most often.

**Comment by geoand** [comment]
I agree about `odo component create`, seems like the most reasonable choice

**Comment by geoand** [comment]
I can probably pick `odo component create` up next week unless @metacosm has already done some work on it

**Comment by metacosm** [comment]
> I can probably pick `odo component create` up next week unless @metacosm has already done some work on it

Nope, I haven't started on it. You can go ahead if you want.

**Comment by geoand** [comment]
> > I can probably pick `odo component create` up next week unless @metacosm has already done some work on it
> 
> Nope, I haven't started on it. You can go ahead if you want.

OK, it will be a good chance to get a second set of hands using the interactive stuff

**Comment by cdrage** [comment]
:+1: for `odo component create`

I believe `odo storage` would be another great candidate, volumes have always been a pain point for Kubernetes / OpenShift...

**Comment by kadel** [comment]
Removing this from the epic in favor of https://github.com/redhat-developer/odo/issues/1242.

This will be continued after the beta release
