### ISSUE TITLE
Integrate odo with Application and/or Component CRD

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#1244]
[kind/Feature]

**Goal** : Integrate odo with the k8s Application and/or Component CRD
**why** : 
- Reduce development/maintenance costs of odo by delegating responsibilities to maintain k8s resources of an application on the platform using CRD and operator
- Propose a common approach for all the DevTools to generate resources on the cloud Platform using `Application/Component` CRD
- Simplify migration of existing application when images + CVE should be patched, when new or additional features should be installed (e.g istio 1.1, Prometheus, EFK, ...)
- Delegate complex logic to be part/handled by k8s operator to manage Application status (update) when related resources are created/updated. That will let us to aggregate the status for the different resources created/application or component
- Support different installation or build strategies : inner, outerloop, knative build/pipelines

**Comment by girishramnani** [comment]
Closing this issue as currently we don't have plans to implement this for next 6 months. Please re-open this if someone feels this is relevant now.
