### ISSUE TITLE
Adding unit test for Functions under pkg/component/component.go

### ISSUE THREAD

**Issue by syamgk** [openshift/odo#1260]
[kind/Enhancement]
## Which functionality do you think we should update/improve?
Unit tests for https://github.com/redhat-developer/odo/blob/master/pkg/component/component.go 
adding tests for functions 

- [ ]  func CreateFromPath
- [ ] func Build
- [ ] func Delete
## Why is this needed? 

For keeping up with unit test standards

**Comment by girishramnani** [comment]
shouldn't we try to cover all functions in UTs e.g. `GetComponentDir`

**Comment by girishramnani** [comment]
this can be considered part of https://github.com/openshift/odo/issues/2256
