### ISSUE TITLE
Unit test for watch.go

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#1267]
Functions in unit tests covered by unit test

- [x] isGlobExpMatch
- [ ] addRecursiveWatch
- [x] WatchAndPush

**Comment by girishramnani** [comment]
do we need unit test for `addRecursiveWatch` function @mik-dass ? if no then please close this issue.

**Comment by mik-dass** [comment]
> do we need unit test for addRecursiveWatch function @mik-dass ? if no then please close this issue.

I guess we can close this as the function using this has been covered by unit tests.
