### ISSUE TITLE
segregate the printing and business logic of structs

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1270]
Currently the `cmd` packages also hold a lot of business logic which is not related to printing, we should consider keeping only the printing logic in the `cmd` packages and move the business logic to the `non-cli` oriented packages.

E.g. - a function like `component.List` should return new structures (in this example ComponentList) etc.. and printing should be the only concern of the `cmd`.

**Comment by cdrage** [comment]
This is another code refactor and wouldn't be affecting any feature / deployment logic, medium priority?

**Comment by kadel** [comment]
> This is another code refactor and wouldn't be affecting any feature / deployment logic, medium priority?

this is something that will be important for #1263, without this everything in that issue will be much messier and complicated
