### ISSUE TITLE
add missing fields and populate some fields with default values in machine readable structs

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1271]
Missing fields
  - [ ] `ComponentSpec` should have port, cpu, memory (min,max)
  - [ ] `ComponentSpec` for git should have a source ref
  - [ ] `StorageSpec.Status` should have a field indicating to which Component the storage is mounted - name suggestion @kadel 
  - [ ]  `Component` should have a field indicating to which application it belongs to
  - [ ] Mounted storage should have a field indicating to which application and component it belongs to
  - [ ] Unmounted storage should have a field indicating to which application it belongs to
  - [ ]  Url should have a field indicating to which application and component it belongs to

Other enhancements 
  - [ ] **tag is not displayed** when components are created with specific builder image version
  - [ ] every object should have `metadata.namespace' filled
  - [x] odo url list shows port, but there are no ports in odo url list -o json

**Comment by cdrage** [comment]
This is more of a refactor / logging. Shouldn't this be kind/medium instead of high priority?

**Comment by girishramnani** [comment]
This actually adds new fields to structs so it's not just refactoring

**Comment by girishramnani** [comment]
@surajnarwade can you check on this tasks that have been resolved so far for tracking

**Comment by kadel** [comment]
@mik-dass please check what has been done and what still needs to be done

**Comment by kadel** [comment]
@mik-dass please check what has been done and what still needs to be done

**Comment by mik-dass** [comment]
@kadel Done, updated
