### ISSUE TITLE
Modify Application to use new structs

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1292]
- [ ] Add missing fields
- [ ] Update all functions that refer to Application struct to new structs (machine readable)

**Comment by mik-dass** [comment]
blocked on #1362

**Comment by kadel** [comment]
> blocked on #1362

it is merged now

**Comment by kadel** [comment]
> blocked on #1362

this has been merged

**Comment by mik-dass** [comment]
Blocked on #1360 as a lot is getting changed in the application.go

**Comment by surajnarwade** [comment]
Closing this since we use new structs now
