### ISSUE TITLE
Slow odo watch and push

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1297]
I will be referring a lot to following directories :
 - **destination dir** - the directory where `assemble` scripts looks for source code (usually `/tmp/src` or the same as working dir `/opt/app-root/src')
 -  **deployment dir** - the directory to which `assemble` script moves compiled artifacts, and `run` script runs it from this directory (usually `/deployments`)
  -  **working dir** - this is where `assemble` script usually builds the source code (usually `/opt/app-root/src`)

This problem has two parts:

## Copying files to backup dirs to work around `assemble` moving files to different dirs
Two main issues that are represented by python and java builder images:

### moving sources from destination to working dir  (python)
Python builder image is a representative example of this behavior.
One of the first steps that python's `assemble` script does is that it **moves** files from destination dir to working dir. This causes problems with `watch`, multiple pushes, and with propagating deleted files
more in issues  https://github.com/redhat-developer/odo/issues/1054 https://github.com/redhat-developer/odo/issues/988 https://github.com/openshift/odo/issues/1354

TODO(kadel): add more info description about this problem

Odo works around this by backing up all files from working dir, to backup dir (`/opt/app-root/src-backup`) and then restoring this backup into destination dir after `assemble` script is finished.

### moving compiled artifacts out of /opt/app-root/src (java)
Java builder images are good representative example fo this behavior.
`assemble` scripts **moves** all compiled artifacts into deployment dir.
The problem is that this deployment dir is not on volume. If the container is restarted, this files is lost because it is not part of the container image.

Odo works around this by backup up deployment dir into `/opt/app-root/deployment-backup` and then restoring this into deployment dir before `run` script is executed.

## No hot reloads
We are not doing hot reloads, all application updates require a restart.
This can be costly especially for java apps, and even for some nodejs apps.

**Comment by anmolbabu** [comment]
I am planning to experiment with hard links

**Comment by kadel** [comment]
The biggest problem is the moving files around. We can make it faster, but it is going to be just more complex workaround.

Even if we make this work, there will be no guarantees that it will be a generic solution for any s2i image. 
S2I is good, but also too flexible for our use case.

We should try to solve this inside the S2I builder images.
We can come up with some rules/restrictions and extensions for S2I image that will make builder images "odo compatible" and work with image maintainers to implement it into the "official" s2i images.
Even if we have to temporary maintain a few forked images, it will be better than constantly finding workarounds and while fixing it for one image, breaking it for the other. 

/cc @sspeiche @jorgemoralespou @GrahamDumpleton @bparees

**Comment by jorgemoralespou** [comment]
> I am planning to experiment with hard links instead of cp will post the metrics once done with experiments

Hard links does not work when across filesystems/PVs. So, we should try to have everything on the same filesystem, in the PV, using subPath https://docs.openshift.com/container-platform/3.11/dev_guide/volumes.html#volumes-specifying-a-subpath, if that means that some of the original /deployments or /tmp/src would need to be linked to a real directory under the PV /opt/app-root in a subPath manner. This change would probably need to happen by the initContainer or the start process of the main container.

**Comment by bparees** [comment]
> We can come up with some rules/restrictions and extensions for S2I image that will make builder images "odo compatible" and work with image maintainers to implement it into the "official" s2i images.

we've had a hard enough time creating an s2i community of images today (most of the ones that exist are created/maintained by us).  I'd really hate to see us further fracture that ecosystem.

Allowing an s2i image to indicate something that lets you optimize the behavior is one thing, but requiring it is, imho, problematic.

This is why I originally said the hot-reload mechanism should allow the user to indicate the command/script to be run on code update.

If a user can:
1) indicate the set of filesystem paths to watch for changes
2) indicate the script to run when those paths change

then I would think you can address both of these problems.

**Comment by jorgemoralespou** [comment]
@bparees having the user indicating the paths on the images goes against zero-configuration (or close to zero) requirement in an opinionated tool, hence the idea of curating the images or asking for extensions to s2i.

Seems that as s2i will not evolve, neither some of the other mechanisms available today are good enough, the only possible option is to modify/update some s2i images to support this use-cases while still being s2i compliant, which means an assemble script that does everything. We've looked at other options, but we would still want to be able to support an OpenShift OOTB outer loop experience leveraging s2i. Things might change with knative builds, or some other vendor providing what we haven't been able to.

**Comment by bparees** [comment]
> @bparees having the user indicating the paths on the images goes against zero-configuration (or close to zero) requirement in an opinionated tool, hence the idea of curating the images or asking for extensions to s2i.

you can have defaults/pick up defaults from image labels.

**Comment by jorgemoralespou** [comment]
@bparees This is what @kadel referred in his comment that we should do, work with image maintainers to add these as labels into the images, and at least, create a curated set of images we know will work in odo. 

If I understand correctly your comment now, what you're against is for `odo` to not properly work if the image has not the labels, and we should allow the user to provide these in such scenarios, preventing from making the labels a hard requisite on the images to work. Right?

If yes, then we agree, although we don't think users would go that route. Most likely, they would do either of:
- Modify the image (if they can control it)
- Provide custom .s2i scripts that would adhere to the requirements set to odo

We could potentially, support the latter with the user providing the name of the script, in .s2i/bin so that original assemble can be kept as it is. The main concern here, would be, how different builds/result would be when in inner and outer loop. But definitely a possibility.

**Comment by bparees** [comment]
> If I understand correctly your comment now, what you're against is for `odo` to not properly work if the image has not the labels, and we should allow the user to provide these in such scenarios, preventing from making the labels a hard requisite on the images to work. Right?

right.

**Comment by girishramnani** [comment]
should we consider this for beta @kadel ? I would prefer it to be consider for GA

**Comment by kadel** [comment]
Document describing odo builder image https://docs.google.com/document/d/1Cj4ZXmsaQ-S9NDvrPaAb90i5I4yQg8gYQ8KQ41gIawc/edit?ts=5c87bdfe

**Comment by kadel** [comment]
Resolved with the introduction of partial uploads #1488 and optimized inner loop scripts for NodeJS and Java #2023 (this also solves problems with moving files outside of the destinations directory (only for Java and NodeJS)
