### ISSUE TITLE
openjdk-1.8 images s2i binart builds fail starting with version 1.6 of the image

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#1305]
The openjdk-1.8 image that got released yesterday is causing issues with binary builds, manifesting in java e2e tests.

**Comment by kadel** [comment]
Was this fixed by https://github.com/redhat-developer/odo/pull/1302?

**Comment by jorgemoralespou** [comment]
If you talk about the e2e, they do work, but the java builds are broken, depending on how the java imagestream is imported.

Upstream issue: https://issues.jboss.org/browse/CLOUD-3095

**Comment by apupier** [comment]
https://issues.jboss.org/browse/CLOUD-3095 is marked as done.

**Comment by amitkrout** [comment]
I am closing this issue as the failure is not observed in none of our CI in recent run after #1302 is fixed.
