### ISSUE TITLE
Documentation for ODO_BOOTSTRAPPER_IMAGE env variable

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1311]
https://github.com/redhat-developer/odo/pull/1310

contrib docs will be good place, as this is something that is handy mostly for testing and debugging

**Comment by kadel** [comment]
This feature is mostly for odo developers for testing purposes.

A normal user shouldn't ever need to use this.
I'm not sure if this needs end-user documentation.

**Comment by boczkowska** [comment]
To be honest I’m struggling to see where it fits in the contrib docs, it’s would not be a part of a normal TDD workflow, would it it? 
Should I maybe start compiling a proper debugging section for developers and it could be part of that?
