### ISSUE TITLE
Finish splitting up e2e test runs between CircleCI and TravisCI

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1314]
The way how it is done in #1308 is not ideal.

- We have to mantain two separate ways for spinning up openshift (one for travis, one for circle-ci :-( ) We should either enable orbs or modify our script to work on both.
-  Missing documentation explaining what is running on TravisCi and what on CircleCi.

_Originally posted by @kadel in https://github.com/redhat-developer/odo/pull/1308#issuecomment-462238450_

**Comment by syamgk** [comment]
Closing since the CI setup has changed, and we are not using Circle CI
