### ISSUE TITLE
Dry run option for odo delete

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#1318]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Deletion of objects should have a dry run capability, that allows user to find out what all will be deleted, if he runs deletion, without actually running it. 
Something like maybe `odo object delete --dry` or ` odo object delete --dry-run` 

## Why is this needed? 
This should allow user to get information about what will be deleted without risk of actual deletion. 
Also, this can possibly be integrated with machine readable output, to allow say adapters to find out what will be removed, inform user, take his ack and then delete with `odo object delete -f`

Relies on https://github.com/redhat-developer/odo/issues/804 Please wait for it to close

**Comment by girishramnani** [comment]
currently as we ask for confirmation `Are you sure you want to delete nodejs-nodejst-lmgk from app? (y/N) ` at most of the `delete` commands. I dont see a need for having a `dry-run` flag anymore.
cc @mohammedzee1000 .
Closing this for now
