### ISSUE TITLE
Add support for caching Maven artifacts

### ISSUE THREAD

**Issue by lordofthejars** [openshift/odo#1320]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Currently, for every Java component you want to release in the cluster, needs to be built and this means to download all Maven dependencies. So for every new component all dependencies (which might be huge) all internet must be downloaded. To avoid this it will be great to create a persistence storage where all these artifacts are downloaded. This is something that can be done in several steps but would be great to make Odo do for you.

https://blog.openshift.com/decrease-maven-build-times-openshift-pipelines-using-persistent-volume-claim/

**Comment by jorgemoralespou** [comment]
This is a hack done with oc-cluster wrapper on how to improve builds on local laptop. We could do similar things in odo locally:
https://github.com/openshift-evangelists/oc-cluster-wrapper#faster-s2i-builds
