### ISSUE TITLE
Set "liveness/readiness" probe for a component

### ISSUE THREAD

**Issue by lordofthejars** [openshift/odo#1323]
[kind/Feature]

## Which functionality do you think we should add?

It would be great to be able to set "liveness/readiness" probes so we can be sure that the application is up and running when it is deployed.

Maybe it can be created in two commands, but it is just an idea:

```
odo push --readiness [http://localhost:8080/]
odo ready
```

So if flag `--readiness` is set but no URL then goes to a default endpoint.

`odo` ready waits until the current component is deployed.

## Why is this needed?

If you want to run automatic tests then this could be a good addition instead of having to manually inspect the log until everything is up and running

**Comment by jorgemoralespou** [comment]
How I imagine this feature in `odo inner loop`:

- Have a liveness probe configured to the supervisor that always return true. Even if the supervisor is restarting, it should return true, so this needs to be a "container execution check" liveness probe independent of the supervisor (https://docs.openshift.com/container-platform/3.11/dev_guide/application_health.html).
- Have a readiness probe configured to a process (ideally the go supervisor, but can be a standalone process) that will test your application runtime or health-check endpoint that the user configures. This will be the way `odo status` can tell if runtime/application is ready. As, kubernetes uses the readiness probe for adding/removing the endpoints on services pointing to a DC, and this might not be the best way for odo to know.
- Have odo configure/provide a way to configure an endpoint on your application to determine when it's ready. Ideally, the process in the previous point, should check the application with this command (Ideally we should implement the same checks as kubernetes to support going to outer loop, but I would mainly consider the HTTP check for now.

This could be a config (healthcheck or readyckech) and we could have a command to get the state of the application, with something like `odo status` or `odo is-ready` or similar.

**Comment by kadel** [comment]
> * Have a liveness probe configured to the supervisor that always return true. Even if the supervisor is restarting, it should return true, so this needs to be a "container execution check" liveness probe independent of the supervisor (https://docs.openshift.com/container-platform/3.11/dev_guide/application_health.html).

If liveness will be configured to something that always returns true, why do we need to configure it at all?

**Comment by jorgemoralespou** [comment]
That's a god question, but basically so that if the pod lifeness is checked. Livenessprobe check could make sure everything is in place (e.g. supervisor up and running, PVC mounted, ...)
