### ISSUE TITLE
Applications created with odo v0.0.18 are not visible after update to v0.0.19

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1328]
[kind/bug]
## What versions of software are you using?
- Operating System: Windows 10 Pro
- Output of `odo version`: 
```
"C:\USERS\DGOLO\BIN\OC.EXE" version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://10.0.0.18:8443
kubernetes v1.11.0+d4cacc0
```

## How did you run odo exactly?
I am running newly downloaded release and want to see applications in my only project. 

## Actual behavior
Previously I used odo v0.0.18 and crated tree apps `app1', 'app2' and `app3`.
Now when I run v0.0.19 it lists no applications at all.

That causes problems for VSCode Extension see [#639](https://github.com/redhat-developer/vscode-openshift-tools/issues/629).

## Expected behavior
I still want to see my apps created with previous version of odo.

## Any logs, error output, etc?
N/A

**Comment by amitkrout** [comment]
@dgolovin Was it working with previous version of odo releases ?

**Comment by dgolovin** [comment]
It was always working, because location for odo configuration was always the same `~/.kube/odo`. Now it is moved to new location `~/.odo/odo-config`. When devs upgrades from any odo to 0.0.18 everything works as expected. But when upgrades to 0.0.19 applications and all that is under is not visible anymore.

**Comment by dgolovin** [comment]
Was probably introduced with this change https://github.com/redhat-developer/odo/commit/2bc274e3bc503ce1aaebb845b276b6a0da600c27. I see configuration location changed, but could not find migration code that would be responsible for migration of old config, if found, to new one.

**Comment by mohammedzee1000** [comment]
This is a breaking change for upgrade path

**Comment by mohammedzee1000** [comment]
Issue Verified on my system

```
$  oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.242:8443
kubernetes v1.11.0+d4cacc0

$  wget -O odo-0018 https://github.com/redhat-developer/odo/releases/download/v0.0.18/odo-linux-amd64 

$  wget -O odo-0019 https://github.com/redhat-developer/odo/releases/download/v0.0.19/odo-linux-amd64

$  chmod +x odo-001*

$ ./odo-0018 version
odo v0.0.18 (3e2a0aeb)

Server: https://192.168.42.242:8443
Kubernetes: v1.11.0+d4cacc0

$ ./odo-0019 version
odo v0.0.19 (61f278a1)

Server: https://192.168.42.242:8443
Kubernetes: v1.11.0+d4cacc0

$ ./odo-0018 project     
The current project is: myproject

$ ./odo-0018 project create testproject
 ✓  New project created and now using project : testproject

$ ./odo-0018 app create createdwith18
 Creating application: createdwith18 in project: myproject
Switched to application: createdwith18 in project: myproject

$ ./odo-0018 app list                
The project 'myproject' has the following applications:
ACTIVE     NAME
*          createdwith18

./odo-0019 project list
ACTIVE     NAME
           myproject
*          testproject

$ ./odo-0019 app list    
There are no applications deployed in the project 'testproject'.

```

**Comment by mohammedzee1000** [comment]
This is a relatively new tool, so do we want to write code to maintain backward compatibly for something as simple as a location change of config file across the versions? Note copying over the file just works in above case  

```
$ cp -avrf ~/.kube/odo ~/.odo/odo-config.yaml
'/home/<redacted>/.kube/odo' -> '/home/<redacted>/.odo/odo-config.yaml'

$  ./odo-0019 app list    
The project 'testproject' has the following applications:
ACTIVE     NAME
*          createdwith18
```

@girishramnani @dgolovin @amitkrout

**Comment by kadel** [comment]
I know that this is not good. But currently, we don't guarantee any backward compatibility. We are in pre v1.0 stage (not even a beta).

Right now we have to do some breaking changes :-(
We will make sure that components created by one version are working with the next one only once we have v1.0 out.

**Comment by kadel** [comment]
We haven't done a good job with communicating that this is a breaking change:-( We need to be better in this next time, and have a clear indication in the release notes that there is a breaking change.

**Comment by kadel** [comment]
I've updated release notes with the explanation https://github.com/redhat-developer/odo/releases/tag/v0.0.19
