### ISSUE TITLE
git import should support private repositories like oc --source-secret

### ISSUE THREAD

**Issue by corinnekrych** [openshift/odo#1333]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
odo shouldsupport component import from github private repo.
```
$ odo component create nodejs --git https://github.com/corinnekrych/nodejs-ex-private
=> create ok
$ odo component list 
=> listed ok
$ docker ps
=> no container create
$ docker images
=> no images
```
Looking at the UI cosnole:
Cloning "https://github.com/corinnekrych/nodejs-ex-private " ...
error: failed to fetch requested repository "https://github.com/corinnekrych/nodejs-ex-private " with provided credentials

## Why is this needed? 
Available in `oc`
https://docs.openshift.com/online/dev_guide/builds/build_inputs.html#source-clone-secrets

**Comment by jorgemoralespou** [comment]
In oc, this is a 2 step process:
- Create the secret with your Git credentials (basic auth, ssh-key,...)
- Link the secret to the service account used (builder in this scenario).

`oc new-app` supports only the later, while the former needs to be done with `oc create secret`. 

We need a way to do the former (as the later is easy), something like `odo credentials create` or similar...

**Comment by ryannix123** [comment]
@jorgemoralespou Did this ever get added to do? I'm looking through the help and I didn't see anything that let's me specify my git credentials.

**Comment by jorgemoralespou** [comment]
@ryannix123 no. @kadel can give your more information on priorities. I'm an external contributor to the project.

**Comment by kadel** [comment]
@ryannix123 no it was not implemented yet. We are currently focusing on bug fixing and improving build and reload process for local components. 
This is something that we will probably look into after 1.0 release
