### ISSUE TITLE
In windows git bash `odo login -u developer` does not hide typed password when requested

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1336]
[kind/bug]
## What versions of software are you using?
- Operating System:  Windows 10 Pro
- Output of `odo version`: 
```
$ ~/.vs-openshift/odo version
odo v0.0.19 (61f278a1)
Server: https://10.0.0.18:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

Using it from git bash on Windows

## Actual behavior

```
$ ~/.vs-openshift/odo login -u developer
Authentication required for https://10.0.0.18:8443 (openshift)
Username: developer
Password: developer
✓  Login successful.
You have one project on this server: "myproject"
Using project "myproject".
```

## Expected behavior
Password is hidden.

**Comment by dgolovin** [comment]
Works fine with cmd and powershell.

**Comment by surajnarwade** [comment]
@dgolovin , can you please check same with `oc` ?

**Comment by dgolovin** [comment]
@surajnarwade The same behavior for `oc` v.3.11.0.

**Comment by kadel** [comment]
If this same as in `oc login`, I'm afraid that we can't do much about it right now :-(

We are importing code from `oc login` for `odo login`.
