### ISSUE TITLE
make get command available for odo config

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1352]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
```odo config get <PARAMETER>``` should return the ```CURRENT_VALUE``` assigned to it

## Why is this needed? 
Better user experience and ofcourse it makes the validation easy for a particular ```PARAMETER``` in the test file.

**Comment by amitkrout** [comment]
ping @girishramnani , Please share your thoughts. 

cc_ @kadel

**Comment by girishramnani** [comment]
@amitkrout as part of the config changes, the `odo utils config` will be moved to `odo config` so maybe there we can consider the `get`

**Comment by girishramnani** [comment]
@tkral should decide if this is needed

**Comment by kadel** [comment]
there is `odo config view` that lists all the configuration values. I think that this is enough for now. 
Let's wait if there is a real need `get` before adding it.

**Comment by girishramnani** [comment]
closing this issue as we haven't seen any request for this feature so far. If someone feels this feature is need then they can re-open this issue
