### ISSUE TITLE
odo push doesn't propagate file deletions

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#1354]
How to test : 

1. Create a component with a local source
2. Push the changes
3. Delete a file from the source
4. Push again

## Actual behaviour
The deleted file remains in the pod after the push

## Expected behaviour
The deleted file should be removed from the pod.

## Notes from @kadel 
For delete propagation and partial update to work in  `odo watch`  we use a small hack.
Inside the builder image we first [backup](https://github.com/openshift/odo-supervisord-image/blob/13b639efe20dba13c208a64fb7d604d270d75fc9/assemble-and-restart#L19) source files before executing assemble script and then [restoring] it.

Note that due to this files has to be deleted in multiple locations - https://github.com/openshift/odo/blob/8a5950720f74ddf6a4c8bbbab449223eb592e48e/pkg/occlient/occlient.go#L3305

**Comment by kadel** [comment]
There is another part to this, that we need to also handle properly.

```
odo component create .. 
touch somefile
odo push
echo "somefile" > .odoignore
odo push
```

Now the question is what we should do in this case.
Should `somefile` be deleted from the container if it is ignored?

Or should it just be ignored. That means that if user wants to delete a file that is already pushed and it is it odoignore, he/she will have to remote it from the odoignore first and then run push, and then add it back to ignore.

**Comment by cdrage** [comment]
So with some testing, `odo watch` works perfectly. The problem is indeed `odo push` that doesn't propagate deletions (we don't even have the code added for it).

```sh
~/nodejs-ex  master ✗                                                                                                                                                                                                          239d ✖ ◒  ⍉
▶ oc rsh nodejs-hjig-app-1-9r6tx ls /tmp/src
README.md  foobar      helm       package.json  tests
foo.txt    foobarrrrr  openshift  server.js

~/nodejs-ex  master ✗                                                                                                                                                                                                           239d ✖ ◒  
▶ rm foobarrrrr 

~/nodejs-ex  master ✗                                                                                                                                                                                                           239d ✖ ◒  
▶ oc rsh nodejs-hjig-app-1-9r6tx ls /tmp/src
README.md  foo.txt  foobar  helm  openshift  package.json  server.js  tests
```

(when using `odo watch` in the background)

I'll take this up and implement the new feature for `odo push`.

**Comment by cdrage** [comment]
Update:

This issue relates to https://github.com/openshift/odo/issues/1788 and further discussion will take place there... We need a solution to detect what files have been changed and what hasn't.

**Comment by girishramnani** [comment]
If we think about this problem, it can be considered as passive file change monitoring. We cannot have a watch on our directory like we did for odo watch. Which means there are two approaches we can consider 
1 - have a state local which helps us detect the change
2 - compare the remote files with local files and sync the differences ( like rsync )

**Comment by kadel** [comment]
This was unblocked by https://github.com/openshift/odo/pull/1849 
/remove-label status/blocked

**Comment by cdrage** [comment]
Hey @mik-dass 

Question, as I'm having a brain fart over here trying to implement this.

As of right now, we have the `odo-file-index.json`. 

In order to see what has been deleted, I was thinking of:

1. Generating another json file
2. Comparing the two and see what has been changed.

The problem is that some projects have thousands of files (think `golang` projects).

How do you suggest we compare the two? Is there an algorithm you may have come across when implementing the walker function?

**Comment by mik-dass** [comment]
@cdrage I have already implemented the file deletion part here https://github.com/openshift/odo/blob/4929e494b3ae97ebe6ffd3f2cb47b35e837fd75d/pkg/odo/cli/component/common_push.go#L186. The list already contains the list of the deleted files filtered according to the glob rules in .gitignore or .odoignore

Even the e2e test was written for deletion https://github.com/openshift/odo/blob/4929e494b3ae97ebe6ffd3f2cb47b35e837fd75d/tests/integration/cmd_push_test.go#L88. You just need to modify it a bit.

**Comment by cdrage** [comment]
@mik-dass Thanks for the guidance, I'm going to implement it with your advice :+1:
