### ISSUE TITLE
Machine output in case of catalog list operation

### ISSUE THREAD

**Issue by lordofthejars** [openshift/odo#1357]
[kind/Feature]

## Which functionality do you think we should add?

`odo catalog list` command should be able to produce the output in machine format too.

## Why is this needed?

Some integrators might need this information to create some guards in case of the catalog does not contain a specific element. For example, we could create a guard that makes a test to not be executed if openjdk s2i is not in the catalog.

**Comment by surajnarwade** [comment]
TODO: 

* `odo catalog list components -o json`
* `odo catalog list services -o json`

**Comment by lordofthejars** [comment]
Ok I am going to work on that

**Comment by cdrage** [comment]
Closed by mistake. Still need #2067 merged in
