### ISSUE TITLE
Active app doesn't switch when switching project

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#1363]
## Which functionality do you think we should update/improve?

`odo project delete`

## Why is this needed? 

When the project is delete and odo sets an existing project as active, one of the apps from the project should be set as active automatically

**Comment by amitkrout** [comment]
@mik-dass Even in normal scenario you can able to reproduce it

odo project create test0
odo app create 1
odo app create 2
```
$ odo app list
The project 'test0' has the following applications:
ACTIVE     NAME
           1
*          2
```
odo project create test1
odo app create 3
odo app create 4
```
$ odo app list
The project 'test1' has the following applications:
ACTIVE     NAME
           3
*          4
```
odo project test0
```
$ odo app list
The project 'test0' has the following applications:
ACTIVE     NAME
           1
           2
```
odo project test1
```
$ odo app list
The project 'test1' has the following applications:
ACTIVE     NAME
           3
           4
```

**Comment by mik-dass** [comment]
@kadel @amitkrout After switching to the other app, should the component be switched too?

**Comment by amitkrout** [comment]
> @kadel @amitkrout After switching to the other app, should the component be switched too?

@mik-dass Hard to get you, Would you please come with an example

**Comment by kadel** [comment]
I would postpone any changes to component switching. 
Component switching will be completely different with new odo workflow. We will not store active component anymore, it won't be needed

**Comment by kadel** [comment]
after new workflow implementation, this is no longer valid. 
/close
