### ISSUE TITLE
slow odo describe

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1375]
`odo describe`  takes a lot of time
```
▶ time odo describe
Component Name: myjava
Type: java
Source: file:///Users/tkral/tmp/odo-examples/fuse-rest-http-booster

Environment variables:
 - foo=bar

Storage:
 - myjava-zakj of size 1G mounted to /data

odo describe  0.20s user 0.05s system 5% cpu 4.542 total
```

20 seconds for simple description of a component is too much

**Comment by metacosm** [comment]
It's not 20 seconds, it's 0.2 seconds… It might still be too slow for you but I find it acceptable…

**Comment by kadel** [comment]
Ah, you are right :flushed: , my bad. But it felt like 20 :grimacing:

**Comment by metacosm** [comment]
I've noticed slowness yesterday on a very bad network where commands would hang despite the result being already returned and displayed… Didn't look into it, though… 😞

**Comment by kadel** [comment]
fixed
/close
