### ISSUE TITLE
machine readable output: -o for delete commands

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1383]
every delete command:

- [x]  - `odo component delete`
- [x]  - `odo project delete`
- [x] - `odo application delete`
- [ ]  - `odo storage delete`
- [ ]  - `odo url delete`

can be run with `-o json` argument. in that case, it doesn't ask for confirmation.
If deletion was successful it doesn't have to return any output, just exit with correct exit code - 0

**Comment by mohammedzee1000** [comment]
https://github.com/redhat-developer/odo/issues/1318
This is maybe what we should consider with delete for machine readable

**Comment by syamgk** [comment]
> #1318
> This is maybe what we should consider with delete for machine readable

Once we enable and implement a minimal `-o json` for all commands we can work on giving more info
