### ISSUE TITLE
new odo workflow: odo storage

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1388]
odo storage should only modify the config file. Storage will be created by `odo push`

- changes to odo storage command
- add storage suppport to `odo push`

`odo storage create`
  - it just updates the `.odo/config.yml` file ( no action on the cluster)
  - `odo push` has to be run to actually create the storage on the cluster

`odo storage delete`
  - it just updates the `.odo/config.yml` file ( no action on the cluster)
  - `odo push` has to be run to actually create the storage on the cluster

`odo storage list`
  - lists all the storage that is in the config file
  - Ideally, it should list all storage associated with the component, both in the cluster and in the config file, and mark what is from the config and what is from the cluster. Let's start with listing just the config, we can add cluster side later. 
  
`odo storage mount`
 - let's skip this command for now - comment it out, we will get back to this later

`odo storage unmount`
 - let's skip this command for now - comment it out, we will get back to this later

**Comment by mik-dass** [comment]
@kadel @jorgemoralespou How should the new `storage list` look like on the CLI?

**Comment by kadel** [comment]
Lets start with just this:
`odo storage list`  - list storage for the component in `./`
`odo storage list --context /my/project` - list storage for the component in `/my/project`

**Comment by cdrage** [comment]
@boczkowska @kadel 

Should we have a more extensive document with regards to how to use / some examples on storage?

**Comment by girishramnani** [comment]
closing this for now, if this issue still seems relevant then please do re-open it.
