### ISSUE TITLE
Missing commit hash in odo version on MacOS

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1393]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`:
```
$ odo version
odo v0.0.20 ()

Server: https://192.168.64.2:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
```
brew tap kadel/odo
brew install kadel/odo/odo
```

## Actual behavior
```
$ odo version
odo v0.0.20 ()

Server: https://192.168.64.2:8443
Kubernetes: v1.11.0+d4cacc0
```

## Expected behavior
```
$ ./odo version
odo v0.0.20 (id)

Server: https://192.168.64.2:8443
Kubernetes: v1.11.0+d4cacc0
```

**Comment by surajnarwade** [comment]
Working on :penguin: linux though 
```
$ ./odo version
odo v0.0.20 (bd3e74a4)

Server: https://192.168.42.160:8443
Kubernetes: v1.11.0+d4cacc0
```

**Comment by kadel** [comment]
The version is correct, just a commit hash from which it was built is missing.

This is a result of the way how odo is built on MacOS. It is using source tarball instead of cloning git repository. Because of that build script doesn't know what commit it is building.

**Comment by kadel** [comment]
starting [v1.0.0-beta1](https://github.com/kadel/homebrew-odo/pull/35) homebrew Formula is cloning git repository instead of downloading tarbar form github. 

This resolves this issue, and also it should fix checksum mismatch that we were facing from time to time.

/close
