### ISSUE TITLE
Mock resolution of absolute pathof user home for OpenShift CI

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#1411]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
We should be able to mock users home directory resolution for user homedir for cases where it is not possible to resolve user correctly

## Why is this needed? 
This is needed to enable testing on OpenShift CI where tests are run as anyuid, and therefore users home directory is not guaranteed to resolve.

**Comment by mohammedzee1000** [comment]
Needed for https://github.com/redhat-developer/odo/issues/1167

**Comment by kadel** [comment]
> This is needed to enable testing on OpenShift CI where tests are run as anyuid, and therefore users home directory is not guaranteed to resolve.

It just might not exist. But `~` that should have nothing to do with `aynuid`

**Comment by mohammedzee1000** [comment]
> > This is needed to enable testing on OpenShift CI where tests are run as anyuid, and therefore users home directory is not guaranteed to resolve.
> 
> It just might not exist. But `~` that should have nothing to do with `aynuid`

Updated title and information accordingly

**Comment by mohammedzee1000** [comment]
Quickfix up, need to figure out a better solution

**Comment by mohammedzee1000** [comment]
Since we have quickfix in, it is not as urgent, but we still need to figure out a less hacky solution

**Comment by kadel** [comment]
@mohammedzee1000 Do we have any idea how would a less hacky solution look like?

**Comment by mohammedzee1000** [comment]
@kadel that might be possible. We should ensure tests dont create anything w.r.t users home dir. As things stand we are almost there with everything except preferences, which is currently still created in users home dir in tests. If its possible to just override that, we should be good

**Comment by kadel** [comment]
There is an issue with odo when executed inside Pod on OpenShift that might be related to this issue.

**Comment by girishramnani** [comment]
we have the tests running on openshift CI so it seems this issue is not valid anymore.
cc @mohammedzee1000 
Hence closing
