### ISSUE TITLE
Add more tests related to odo config and preference

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1414]
Add more e2e tests for `odo config` and `odo preference` for the following scenarios -

Scenario 1 -

Local config view
Local config set
Validate config and the value should be reflected in the pod
Local config unset
Validate config and the value should be reflected in the pod
Scenario 2 -

Global config view
Global config set
Validate config and the value should be reflected in the pod
Global config unset
Validate config and the value should be reflected in the pod
Scenario 3 -

Local config set
Global config set
Validate config and the value which has more precedence over other should be reflected in the pod
Scenario 3 -

Local config set
Global config set
Pass the same config as command line argument parameter
Validate config and the value which has greater precedence over other two should be reflected

**Comment by girishramnani** [comment]
@amitkrout PTAL

**Comment by amitkrout** [comment]
@girishramnani Thanks for creating the issue. Will take it forward
