### ISSUE TITLE
`odo catalog list` should allow to list hidden components and services

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1421]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

`odo catalog list` should have an option `--hidden' or '--all' to disable filtering of hidden objects.

## Why is this needed? 

It would allow to use old image streams that is hidden right now, but still can be used with 'odo create' if you know name:tag.
See issue [#673](https://github.com/redhat-developer/vscode-openshift-tools/issues/673) in VSCode OpenShift Connector extension for additional details.

**Comment by kadel** [comment]
I think that the better name for the flag cloud be `--show-hidden`

Commands that need this flag: 
 - [ ] `odo catalog list component` 
 - [ ] `odo catalog list services`
 - [ ] `odo component create` (for interactive mode)
 - [ ] `odo service create` (for interactive mode)

**Comment by dgolovin** [comment]
Would be also useful in:
* `odo catalog search component'
* `odo catalog search service'
