### ISSUE TITLE
move odo to openshift github org

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1433]
What needs to be done step-by-step to successfully move odo repo from redhat-developer to openshift github org.

odo consist of two GitHub repositories:
 - https://github.com/redhat-developer/odo
 - https://github.com/redhat-developer/odo-supervisord-image

#### Before we transfer repos (prerequisites):
 - [ ] step by step checklist of all requred tasks

#### Move repositories:
 - [x] transfer `redhat-developer/odo` to  `openshift/odo`
 - [x] transfer  `redhat-developer/odo` to `openshift/odo-supervisord-image`

#### After odo repo is transdered.
 - [x] Make sure that all [matainers](https://github.com/redhat-developer/odo/blob/master/OWNERS) have write permissions to the repo., add write permissions to @odo-bot account
 - [ ] update quay.io autobuild [settings](https://quay.io/repository/openshiftdo/supervisord?tab=builds) to point to https://github.com/openshift/odo-supervisord-image
 - [x] update odo pkg imports `github.com/redhat-developer/odo/*` to   `github.com/openshift/odo/*`
   - [ ] rename it localy, and odo project in your local GOPATH to  `$GOPATH/src/github.com/openshift/odo/` 
   - [x] make sure that it can be build
   - [x] open PR with updated import paths
 - [x] update CI jobs
   - [x] update  OpenShift CI jobs in openshift/release  
     - [x] Update the cluster prow [`config.yaml`](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml), moving from `redhat-developer/odo`  as just `odo` under `openshift`
     - [x] Update the cluster prow [`plugins.yaml`]((https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml)) moving from redhat-developer/odo  as just odo under openshift
     - [x] Update ci operator [config](https://github.com/openshift/release/tree/master/ci-operator/config/redhat-developer/odo) and [jobs](https://github.com/openshift/release/tree/master/ci-operator/jobs/redhat-developer/odo), moving respective files from redhat-developer/odo directory to odo directory, under openshift directory
     - [x] Rename files above to from `*redhat-developer-odo*` to `*openshift-odo*`
     - [x] Update [canonical repo](https://github.com/openshift/release/blob/master/ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml#L1) in ci operator config to `github.com/openshift/odo`
   - [x] update paths in CircleCI jobs https://github.com/redhat-developer/odo/blob/master/.circleci/config.yml
   - [x] update path in TravisCI jobs https://github.com/redhat-developer/odo/blob/master/.travis.yml
   - [x] update path in  Appveyor jobs https://github.com/redhat-developer/odo/blob/master/appveyor.yml
   - [x]  update the configuration file for website: https://github.com/redhat-developer/odo/blob/gh-pages/_config.yml#L5
   - [x] updates for [odo-bot](https://github.com/redhat-developer/odo/blob/master/docs/development.md#odo-bot) (**TODO**. Do we still need it? Is it possible to replace it with Prow somehow? ping @cdrage)

**Comment by cdrage** [comment]
Still need `odo-bot` since it's a separate user. Yes, we can integrate the script into Prow. But could we perhaps keep the documentation building on Travis for now? We can even disable notifications / GitHub status..

Another thing to add:
- [ ] Point website to new lGitHub repo link(s).

**Comment by kadel** [comment]
> Another thing to add:
> 
> * [ ]  Point website to new GitHub repo link(s).

what website? Isn't everything bundled from readme?

**Comment by cdrage** [comment]
@kadel This website: http://openshift.org 

We have to update the configuration file when we move: https://github.com/redhat-developer/odo/blob/gh-pages/_config.yml#L5

**Comment by mohammedzee1000** [comment]
@stevekuznetsov from OpenShift CI side, I hope i have not missed anything

**Comment by stevekuznetsov** [comment]
Nope, that looks good to me

**Comment by kadel** [comment]
PR to fix openshift ci - https://github.com/openshift/release/pull/3186

**Comment by cdrage** [comment]
#1506 has been merged in to `gh-pages` branch :+1: so site is completed.

**Comment by kadel** [comment]
There are still a couple of issues what we need to solve:
 - automatic builds for supervisord image on quay.io are  still not working
 - CircleCI is not enabled (someone needs enable CircleCI for openshift org - alredy requested) . All tests that were running on CircleCI were moved back to TravisCI

**Comment by kadel** [comment]
> * CircleCI is not enabled (someone needs enable CircleCI for openshift org - alredy requested) . All tests that were running on CircleCI were moved back to TravisCI

we don't need CircleCI, we will move most of our tests to OpenShift CI
