### ISSUE TITLE
We require a machine readable output example document 

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1464]
[kind/Documentation]

## What did you find missing in the documentation?

No examples on machine readable output.

## What is the relevance of it?

There needs to be a guide that outlines all machine readable output options so that projects such as IDE's / VSCode / other projects using it will have a nice reference to look at / implement their code instead of guessing. 

This document should outline command-line examples and output.

**Comment by kadel** [comment]
How about publishing JSON schema for our outputs?

**Comment by girishramnani** [comment]
we need atleast examples for beta

**Comment by cdrage** [comment]
@kadel

Bit confused with regards to publishing a "JSON Schema" for each output.. I'm assuming similar to this: https://github.com/redhat-developer/odo/pull/1465

But using concepts such as `type: string` as per https://json-schema.org ?

**Comment by kadel** [comment]
> @kadel
> 
> Bit confused with regards to publishing a "JSON Schema" for each output.. I'm assuming similar to this: #1465
> 
> But using concepts such as `type: string` as per https://json-schema.org ?

I've created separate issues for JSON Schema related stuff, let's keep this issue just about examples.

**Comment by cdrage** [comment]
Hey @boczkowska 

So I did originally outline the document here: https://github.com/openshift/odo/pull/1465

Simply running the commands and having the output of *every* json command in a concise document would be a start..

Do you have any experience in "json output" and making it generic / agnostic for the output? That's the only point I'm unfamiliar with.

Otherwise, for the documentation, we could simply use a sample application such as https://github.com/openshift/nodejs-ex and go from there (show initial steps to `git clone` and `odo push` and then start the json documentation as if the user was following a real app)
