### ISSUE TITLE
Machine readable output - global `-o` flag

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1475]
`-o` flag should be global
Every command should have structured (json) output.

Open questions:
 - what should be output for delete commands?
 - how to output error messages?

**Comment by girishramnani** [comment]
- `-o` was made global as part of https://github.com/openshift/odo/pull/1898 PR

- then there was an issue which concluded that `-o` shouldn't be global https://github.com/openshift/odo/issues/2031 which was resolved by https://github.com/openshift/odo/pull/2160

Hence closing this issue
