### ISSUE TITLE
Add `-o json/yaml` option support for `odo service list`

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1480]
[kind/Feature]
## Which functionality do you think we should add?
add option `-o json/yaml` for ```odo service list```

**Comment by mohitsuman** [comment]
@kadel @girishramnani Is there any update on this issue ? Is this fixed by any other issue ?

**Comment by girishramnani** [comment]
This issue has been fixed in https://github.com/openshift/odo/pull/2098
