### ISSUE TITLE
Add ports information into `odo describe <componentName>`

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1481]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
`odo describe <svcName>`  should include ports information for human and machine readable output.
Port infor:
- number
- protocol

## Why is this needed? 
When linking components and creating urls for components port parameter is required in case there are more than one port is exposed.

**Comment by kadel** [comment]
+1

Currently ComponentSpecs looks like this
```go
type ComponentSpec struct {
	Type    string          `json:"type,omitempty"`
	Source  string          `json:"source,omitempty"`
	URL     []string        `json:"url,omitempty"`
	Storage []string        `json:"storage,omitempty"`
	Env     []corev1.EnvVar `json:"env,omitempty"`
}
```


we need to add ports to it

```go
type ComponentSpec struct {
	Type    string          `json:"type,omitempty"`
	Source  string          `json:"source,omitempty"`
	URL     []string        `json:"url,omitempty"`
	Storage []string        `json:"storage,omitempty"`
	Env     []corev1.EnvVar `json:"env,omitempty"`
        // list of ports formated as port_number/protocol (8080/tcp)
	Port     []string `json:"env,omitempty"`

}
```

@dgolovin What do you mean by TLS Information. As far as I know containers are not exporting any information about TLS

**Comment by dgolovin** [comment]
@kadel you are correct, I removed TLS from the issue.

**Comment by surajnarwade** [comment]
we can simply use  list of `urlSpec`in place of []string in URL

```
type UrlSpec struct {
	Host     string `json:"host,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Port     int    `json:"port,omitempty"`
}
```

**Comment by kadel** [comment]
> we can simply use list of `urlSpec`in place of []string in URL
> 
> ```
> type UrlSpec struct {
> 	Host     string `json:"host,omitempty"`
> 	Protocol string `json:"protocol,omitempty"`
> 	Port     int    `json:"port,omitempty"`
> }
> ```
> 
> earlier version of output had this but later on removed

UrlSpec and Protocol in ComponentSpec are two different things.

**Comment by surajnarwade** [comment]
I would like to work on this :tada:
