### ISSUE TITLE
'odo describe <compName>` human and machine readable output are not in sync

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1482]
[kind/Bug]

Data presented in human and machine readable output should be the same. Currently '-o json' option print out json with less information.

For example  human readable output would print
```odo describe nodejs-ex-nodejs-exra --app app1```
```
Component Name: nodejs-ex-nodejs-exra
Type: nodejs
Source: https://github.com/dgolovin/nodejs-ex
Storage:
- s1 of size 1Gi mounted to C:/Program Files/Git/mnt/s1
URLs
- http://nodejs-ex-nodejs-exra-8080-app1-myproject.10.0.0.46.nip.io exposed via 8080
```
When machine readable only
```odo describe nodejs-ex-nodejs-exra --app app1 -o json```
``` json
{
    "kind": "Component",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "nodejs-ex-nodejs-exra",
        "creationTimestamp": null
    },
    "spec": {
        "type": "nodejs",
        "source": "https://github.com/dgolovin/nodejs-ex",
        "url": [
            "nodejs-ex-nodejs-exra-8080"
        ],
        "storage": [
            "s1"
        ]
    },
    "status": {
        "active": false
    }
}
```
Couple differences to note in machine readable output:
1. Only storage name
2. Url has only host prefix not a full form

**Comment by kadel** [comment]
The idea is that you will get just the names of the related objects. 
If you need detail information you need to run `odo url describe <url name>` and similarly for the storage.

Do you need all the info in the output?
We could also output the List of all  related object to given component as a list
Output would look like this:
```
odo describe nodejs-ex-nodejs-exra --app app1

{
    "kind": "List",
    "apiVersion": "odo.openshift.io/v1alpha1",
    items:[

{
    "kind": "Component",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "nodejs-ex-nodejs-exra",
        "creationTimestamp": null
    },
    "spec": {
        "type": "nodejs",
        "source": "https://github.com/dgolovin/nodejs-ex",
        "url": [
            "nodejs-ex-nodejs-exra-8080"
        ],
        "storage": [
            "s1"
        ]
    },
    "status": {
        "active": false
    }
},
{
    "kind": "Storage",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "s1",
        "creationTimestamp": null
    },
    "spec": {
      ....
      ......
},
{
    "kind": "Url",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "nodejs-ex-nodejs-exra-8080",
        "creationTimestamp": null
    },
    "spec": {
      ....
      ......
}
]
}

```

Would that help?

**Comment by dgolovin** [comment]
@kadel I did not realize it is basically just references to related objects. I was just thinking straightforward that both outputs should contains the same info. If it would I would use less odo commands this way. For example I would use it for getting storage and url lists instead of `odo url/storage list` commands.
IMO from user point of view would be better to have the same info for both, but I leave that decision to you.

**Comment by dgolovin** [comment]
Can be replaced with `odo url list -o json`. Closing.
