### ISSUE TITLE
odo app list from non component directory

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1486]
to add to @surajnarwade point 
```
$ odo app list
```
This command returns the applications in my project `myproject` from any folder. I am not sure if that should happen @anmolbabu

_Originally posted by @girishramnani in https://github.com/redhat-developer/odo/pull/1360#issuecomment-474749146_

`odo app list`
 - in a directory with `.odo` - list all application in the project defined in the config file
 - in a director without `.odo` - show error that there is no component configuration 

`odo app list --context /my/project`
  - similar to `odo app list`, but uses the context dir instead of the current directory

`odo app list --project`
 - show all applications in given project - doesn't check for the `.odo` folder
 - this command can be run from any directory regardless of `.odo` presence

**Comment by kadel** [comment]
@mohammedzee1000 I have updated the description

**Comment by mohammedzee1000** [comment]
@kadel  i don't think app list implements `--context` so that might be outside purview of this at the moment
