### ISSUE TITLE
odo create in a  directory that already has component .odo

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1487]
There is one more behavior which we should consider while doing `odo create` is that -
- If the directory already contains a component ( has a .odo/config.yaml ) then when we try to do `odo create` again it should ask for confirmation from the user that `there is already a component in this directory if you want to override it then please enter the name of the component?` 

Currently it allowed me to override the component config without asking.

_Originally posted by @girishramnani in https://github.com/redhat-developer/odo/pull/1360#issuecomment-474779188_

**Comment by girishramnani** [comment]
This seems to be a sub part of https://github.com/openshift/odo/issues/1447 @cdrage

**Comment by girishramnani** [comment]
also we haven't decided that if the `odo component create` in an existing component dir should fail like mentioned in https://github.com/openshift/odo/issues/1447 by @kadel or ask for confirmation like mentioned here

**Comment by kadel** [comment]
> This seems to be a sub part of #1447 @cdrage

@girishramnani 
I think that we can close this issue as, you correctly pointed out that this is covered in https://github.com/openshift/odo/issues/1447
