### ISSUE TITLE
smart odo push

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1488]
@kadel one more improvement to track is that -
multiple `odo push` without changing anything in the code and config should be idempotent in nature ( shouldn't do anything )

the way this could be achieved -
1) for component type `git` - we can track the last commit hash  
2) for component type `binary` and `local` - a sha hash of the local code/artifacts can be tracked

_Originally posted by @girishramnani in https://github.com/redhat-developer/odo/pull/1360#issuecomment-474782801_

**Comment by kadel** [comment]
We should go even further.

This is how it should work ideally:
 - When something was changed in the config file, `odo push` will apply changes, if no change in config file, no changes to the DeploymentConfig.
- When something changed in the source code, `odo push` push changed files (this includes deleting files that in the container that were deleted locally) and trigger  build/reload
- When there was config change and souce change, first apply config changes, and than push files.


But the above will take time to implement, for beta release we could just do the following:
 - `odo push --source` will  just copy files
 - `odo push --config` will just apply config changes
 -  by default `odo push`  will do both (later we will make this smarter as described above)

**Comment by girishramnani** [comment]
The https://github.com/redhat-developer/odo/issues/1489 part which does part of this issue will be considered for beta and rest for GA ( in sprint 165 )

**Comment by anmolbabu** [comment]
For each iteration of push:
- [ ] Compute a hash of the component settings say `cmpSettingsHash`
- [ ] Fetch the hash of the config applied on the component from a label say `app.kubernetes.io/componentSettingsHash`
- [ ] if `cmpSettingsHash` != `app.kubernetes.io/componentSettingsHash` , component settings have changed, update them to the dc

* for local and binary path additionally:
- [ ] Walk the component SourceLocation recursively and find the latest time stamp. Lets call it `lastUpdatedTimeStamp`
- [ ] Fetch the lastUpdatedTimeStamp from the label attached to component dc. Lets call the label `app.kubernetes.io/lastUpdatedTimeStamp`
- [ ] compare the values
   * If `app.kubernetes.io/lastUpdatedTimeStamp` < `lastUpdatedTimeStamp` => New source available that's not pushed to the component, so push the sources over
  * If `app.kubernetes.io/lastUpdatedTimeStamp` == `lastUpdatedTimeStamp` => No source code to push

* For a distributed revision control system like git, a common technique that works immaterial of git or any other is to be found may be some providers kind of approach for each of them... but isn't a priority for the moment

**Comment by jorgemoralespou** [comment]
@anmolbabu `oc apply` should already do what you're referring here related to `cmpSettingsHash`.
If you apply a configuration that is the same, oc/kubernetes will do nothing. If there is a redeployment happening, it's basically because everytime you save/deploy the component's definition on of the fields that can trigger a redeployment is changed.

I would rather look into the logic of how to do this in the standard openshift/kubernetes way. Should you not know how this is done, we can talk to some openshift engineers.

**Comment by kadel** [comment]
I also found this https://github.com/openshift/odo/issues/1633 that is related to this.

**Comment by kadel** [comment]
@mik-dass It would be better to look to https://github.com/openshift/odo/issues/1633 before we jump into this issue. https://github.com/openshift/odo/issues/1633 Might solve a lot of our problems

**Comment by kadel** [comment]
closing in favor of https://github.com/openshift/odo/issues/1788
