### ISSUE TITLE
Publish JSON Schema for machine readable output

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1490]
How about publishing JSON schema for each output?

_Originally posted by @kadel in https://github.com/redhat-developer/odo/issues/1464#issuecomment-473805588_

**Comment by cdrage** [comment]
@kadel 

What kind of "schema" are you referring to?

I'm assuming something like this:

```sh
{
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Product",
   "description": "A product from Acme's catalog",
   "type": "object",
	
   "properties": {
	
      "id": {
         "description": "The unique identifier for a product",
         "type": "integer"
      },
		
      "name": {
         "description": "Name of the product",
         "type": "string"
      },
		
      "price": {
         "type": "number",
         "minimum": 0,
         "exclusiveMinimum": true
      }
   },
	
   "required": ["id", "name", "price"]
}
```

So in theory:

```json
{
  "kind": "url",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {
    "name": "foobar-8080",
    "creationTimestamp": null
  },
  "spec": {
    "host": "foobar-8080-odo-cmac-foobar.e8ca.engint.openshiftapps.com",
    "protocol": "http",
    "port": 8080
  }
}
```

Would be:

```json
{
  "kind": "url",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {
    "name": "name-of-url",
    "creationTimestamp": null
  },
  "spec": {
    "host": "example.domain.org",
    "protocol": "http-or-https-protocol",
    "port": port-number
  }
}
```

?

**Comment by kadel** [comment]
> What kind of "schema" are you referring to?
> 
> I'm assuming something like this:
> 
> ```shell
> {
>    "$schema": "http://json-schema.org/draft-04/schema#",
>    "title": "Product",
>    "description": "A product from Acme's catalog",
>    "type": "object",
> 	
>    "properties": {
> 	
>       "id": {
>          "description": "The unique identifier for a product",
>          "type": "integer"
>       },
> 		
>       "name": {
>          "description": "Name of the product",
>          "type": "string"
>       },
> 		
>       "price": {
>          "type": "number",
>          "minimum": 0,
>          "exclusiveMinimum": true
>       }
>    },
> 	
>    "required": ["id", "name", "price"]
> }
> ```


Yes, something like that. It would be nice if we could generate this automaticaly based on struc tags and have it available somewhere in our repo.
