### ISSUE TITLE
odo new workflow - fixing odo service 

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1491]
after #1360 is merged make sure that odo service commands are working with new workflow

if there are commended out e2e tests, uncomment those, and make sure that it works.

**Comment by kadel** [comment]
Tested the service commands manually and everything seems to work. Service create, list, deletion

**Comment by amitkrout** [comment]
Awesome!!!
Please open pr for the ame

**Comment by kadel** [comment]
Works, but tests needs to be fixed. Decreasing priority

/remove-priority high
/priority medium
