### ISSUE TITLE
new odo workflow - make sure that odo link work

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1492]
after #1360 is merged make sure that odo link command work properly

**Comment by cdrage** [comment]
@syamgk Please make sure that the `odo link` command and `odo unlink` command work correctly.

We also need to make sure that `--context` is also implemented.

**Comment by kadel** [comment]
good point. I forgot about `--context`

**Comment by kadel** [comment]
odo link is working, but link is removed after `odo push`!!
https://github.com/openshift/odo/issues/1596

**Comment by girishramnani** [comment]
This issue's scope is to only verify that odo link works in the new workflow. 
Resolution of the link tests is scoped out to this issue https://github.com/openshift/odo/issues/1616 @syamgk @kadel

**Comment by syamgk** [comment]
ack!
