### ISSUE TITLE
odo project delete fails after first delete

### ISSUE THREAD

**Issue by anmolbabu** [openshift/odo#1503]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 29
- Output of `odo version`: master with #1360 

## How did you run odo exactly?
odo project create odo2-1553171170
odo project create prj4

odo project delete prj4
odo project delete odo2-1553171170

## Actual behavior
[anmolbabu@localhost odo]$ odo project delete prj4
? Are you sure you want to delete project prj4 Yes
 ✓  Deleting project prj4
Deleted project : prj4

[anmolbabu@localhost odo]$ odo project delete odo2-1553171045
 ✗  deploymentconfigs.apps.openshift.io is forbidden: User "developer" cannot list deploymentconfigs.apps.openshift.io in the namespace "prj4": no RBAC policy matched

## Expected behavior

Both deletes should go through

**Comment by girishramnani** [comment]
picking this up @kadel

**Comment by syamgk** [comment]
Note: after the deletion of project it's not switching the active project
and while doing the second project delete it's trying to query the same project instead of the name passed via the cli cmd

**Comment by girishramnani** [comment]
If I remember correctly the switching project part was already removed with
anmol's PR
