### ISSUE TITLE
e2e tests are not cleaning up

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1509]
Each e2e test spec needs to clean up after itself.

When I run e2e tests I can see a lot of components that were left after the test finished.

It is not enough to clean up everything at the end. The test needs to delete everything that was created right after finishes (no matter in what state it ended)

**Comment by amitkrout** [comment]
> When I run e2e tests I can see a lot of components that were left after the test finished.

Right, some test file have implemented the clean up logic just by deleting the self created project at the end of the test. However in other test file cleanup is not properly implemented or missing.

Thanks for the issue.

**Comment by kadel** [comment]
/remove-lifecycle stale

this is still an issue, I just run integrations tests and after everything was done there were 2 projects left on the cluster that ware created by tests.

**Comment by kadel** [comment]
this is still valid

/remove-lifecycle rotten
/lifecycle frozen

**Comment by dharmit** [comment]
@anandrkskd's work on #4467 would fix this.

/close
