### ISSUE TITLE
--json inclusion in the brew info command

### ISSUE THREAD

**Issue by navalsinghIIM** [openshift/odo#1514]
This is more related to my experience while trying out Odo for the first time on my MacBook Pro machine. The `brew info --installed docker-machine-driver-xhyve` command at https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-macos need to have `brew info --installed docker-machine-driver-xhyve --json` . The reference to the page is on this page: https://github.com/minishift/minishift#documentation

**Comment by cdrage** [comment]
Hey @navalsinghIIM 

The best way to update OpenShift documentation would be to ask the people on the OpenShift team at: https://github.com/openshift/openshift-docs

I am however a tad confused with regards to the `--json` inclusion. Why would you require that? I believe the `--json` command it included for machine output / other application to feed in that information.

**Comment by navalsinghIIM** [comment]
`Navals-MacBook-Pro:~ singhn9$ brew info --installed docker-machine-driver-xhyve`
Error: `installed` cannot be passed without `json`

**Comment by cdrage** [comment]
@navalsinghIIM I'd suggest opening up an issue with the OpenShift docs team: https://github.com/openshift/openshift-docs
