### ISSUE TITLE
odo url list -o json should return json with empty list if no url present

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#1515]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`:

```
odo v0.0.20 (bd3e74a4)
Server: https://192.168.64.13:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
`odo url list --component <comp> --app <name> -o json`

## Actual behaviour
Currently it prints the text as mentioned below:
`✗  no URLs found for component front in application demo`

## Expected behaviour
If there are no URLs `odo url list --component <comp> --app <name> -o json` should return an empty list.
`
{
  "kind": "List",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {},
  "items": []
}
`

**Comment by mohitsuman** [comment]
Can we please mark this as priority, as this will help us to fix 2-3 issues together on vscode side. :)

**Comment by kadel** [comment]
/priority medium

@syamgk everything marked with [new workflow](https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+workflow%22) has higher priority than this,

**Comment by syamgk** [comment]
@kadel  ack!
