### ISSUE TITLE
new workflow:  odo component commands

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1520]
Each `odo component` command has optional `--context` argument.
That defines what is the component that the action shoudl be performed on.
By default context is `./` 

####  create 
creates component config (definition) in the context directory

#### delete 
flags : --force --context
deletes component from the cluster (undeploy), configuration in intacted

####  describe 
flags:  --context : Describe the given component
show all information about the current component, including information if it is deployed or not

#### link
flags:  --app --project --wait --context
Link current component to a service or component
do live change, storing in config file will depend on whether service is stored in the config or not

TODO: `--app` and `--project`

#### unlink
flags:  --app --port --project --context
Unlink current component from a service or component
TODO: `--app` and `--project`

#### list
flags:  --app --project --all --context
List all components in the current application  (the same application as the current component is)
`--application` flag can be specified to list components in the different application  (if not specified defaults to the application defined in the context)
`--project` flag can be specified to list components in the different project (if not specified defaults to the project defined in the context)

if we have following config
```
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Application: testing
  Project: myproj
  Name: php
```

`odo component list` - list all components in `testing` app in `myproj`
`odo component list --application  myapp` - list all components in `myapp` app in `myproj`
`odo component list --project  secondproj` - list all components in `testing` app in `secondproj`
`odo component list --application  myapp --project  secondproj`- list all components in `myapp` app in `secondproj`. This command is only `odo component list` that be run outside of the directory  with `.odo` o

All the above commands can be run with `--context` to use config file in different directory than the current one (expect the last one)

#### log|logs 
Retrieve the log for the given component
flags:   --app --follow --project --context

`--project` and `--app`  have the same behavior like in `list` command

#### push 
Push source code to a component
flags:  --show-log --context

show-log implementation in #1082 

#### watch 
Watch for changes, update component on change
flags:  --delay --ignore --show-log --context

#### update 
TODO:

**Comment by mohammedzee1000** [comment]
I personally think context resolution should happen in context.go. With commands not having to worry about it. They should instead complain if they dont have enough information. 

For eg, If user has specified a context with no active component then context does is set but without active component and when user tries to perform any op that needs component while not providing --component flag. Then it complains asking user to set/create a component first

**Comment by kadel** [comment]
> Then it complains asking user to set/create a component first or provide `--component`

there shouldn't be a `--component` flag anymore. This is controlled by `--context`

**Comment by anmolbabu** [comment]
> For eg, If user has specified a context with no active component then context is set but without active component and when user tries to perform any op that needs component while not providing --component flag. Then it complains asking user to set/create a component first or provide `--component`

No there is no active component or app or project now in odo everything that was previously called active is now only the ones in config so if component name or app name is not passed, a default is generated in config and if project is not passed, currently we use active project in component config but not sure if that's a bug though targeted for sometime in future

**Comment by mohammedzee1000** [comment]
> > For eg, If user has specified a context with no active component then context is set but without active component and when user tries to perform any op that needs component while not providing --component flag. Then it complains asking user to set/create a component first or provide `--component`
> 
> No there is no active component or app or project now in odo everything that was previously called active is now only the ones in config so if component name or app name is not passed, a default is generated in config and if project is not passed, currently we use active project in component config but not sure if that's a bug though targeted for sometime in future. Only the contents of the component config is the single source of truth

Brilliant this should simplify stuff a lot :)

**Comment by cdrage** [comment]
Ideally `--context` would be a global flag... but we'll get there eventually.

Should we split up this issue into separate parts so multiple engineers can work on it @mohammedzee1000 ?

**Comment by mohammedzee1000** [comment]
@cdrage yes agreed. https://github.com/openshift/odo/pull/1532 is already heading in that direction. I hope i have not missed any commands here. Basically, I am letting through any command that does not rely on context at all, creates it, or has a possible flag to override missing context file. This should help in that direction. I hope i have not missed anything
Yes i think splitting would help :)

**Comment by mohammedzee1000** [comment]
@cdrage it seems to be like it already is as far as context.go is concerned. What is important is shifting to making use of it

**Comment by mohammedzee1000** [comment]
Create already just sets up the config information while push is the one that actually creates the said object

**Comment by mohammedzee1000** [comment]
Working on this already. I have the base information I needed. Will ask if i need more

**Comment by kadel** [comment]
`odo component list --all` and `odo watch --show-logs` can be addressed in another issue and PR

**Comment by kadel** [comment]
created https://github.com/openshift/odo/issues/1584 and https://github.com/openshift/odo/issues/1589 is there something else that is missing?

**Comment by mohammedzee1000** [comment]
--delay in watch i think

**Comment by girishramnani** [comment]
covered --delay in https://github.com/openshift/odo/issues/1592 for tracking
