### ISSUE TITLE
not allow internal ODO env variables to be overridden and some cleanup

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1530]
[kind/Enhancement]

Currently `odo config set --env` allows someone to set any env variable which means that the internal ODO variables like these https://github.com/openshift/odo/blob/master/pkg/occlient/occlient.go#L107-L154
 can also be changed. we want to enforce that this cannot be done.

Also follow up refactor like - 
- [ ] Change function name `In` to `InStrSlice` https://github.com/openshift/odo/pull/1449#discussion_r269866518

**Comment by girishramnani** [comment]
picking this up as well

**Comment by kadel** [comment]
> picking this up

low priority!

**Comment by girishramnani** [comment]
Well then not picking it up
