### ISSUE TITLE
UC 9: As a developer, I want to list all possible configurations of components I can deploy and their meaning

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#154]
As a developer, I want to be able to list all possible components and their configurations and I want to be able to understand what those configurations entail.

```
$ ocd catalog search [postgres] [--type=database|java|whatever] 
The following items were found:
(postgresql) PostgreSQL
(postgresql-10.0) PostgreSQL-10.0
(crunchydb) CrunchyDB Clustered (PostgreSQL 9.5)

$ ocd catalog describe postgresql-10.0
Possible options are:
(optional) memory=(auto-generated if empty)
(optional) password=(auto-generated if empty)
(required) persistent=(true/false)
(optional) storage-size=

Add with the -p flag to set settings

$ ocd create postgresql-10.0 -p username=dbuser -p password=dbpassword -p persistent=true -p storage-size=10gb
```

Tasks:
- [x] #194 Search all possible components I can deploy
- [x] #195 List all possible configurations of components I can deploy and their meaning

**Comment by slemeur** [comment]
For this use case, we should be relying on the service catalog APIs.

Decompose this epic into sub-issues and add the sub-issues into the milestone-mvp.

@kadel @containscafeine : Could you please create the sub-issues for that particular use case.

**Comment by kadel** [comment]
all done
/close
