### ISSUE TITLE
'odo push' fails on windows

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1543]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`: built from master

## How did you run odo exactly?
>dist\bin\windows-amd64\odo.exe create nodejs nodejs-test --app new --project myproject --context C:\Temp\nodejs-ex\nodejs-ex
> dist\bin\windows-amd64\odo.exe push --context C:\Temp\nodejs-ex\nodejs-ex

## Actual behavior
 X  Component nodejs-test has invalid source path c

## Expected behavior
Successfully pushed

## Any logs, error output, etc?
N/A

**Comment by amitkrout** [comment]
I am able to reproduce this on master

```
amit@WIN10 MINGW64 ~/go/src/github.com/openshift/odo/dist/bin/windows-amd64 (master)
$ ./odo.exe create nodejs nodejs-test --app new --project myproject --context ../../../tests/e2e/examples/source/nodejs/
 V  Checking component
 V  Checking component version
Please use `odo push` command to create the component with source deployed

amit@WIN10 MINGW64 ~/go/src/github.com/openshift/odo/dist/bin/windows-amd64 (master)
$ ./odo.exe push --context ../../../tests/e2e/examples/source/nodejs/
 X  Component nodejs-test has invalid source path c
```

**Comment by amitkrout** [comment]
@kadel @anmolbabu ^ This is a critical issue IMO

**Comment by kadel** [comment]
@cdrage we need to unify path handling in the push and watch.

**Comment by cdrage** [comment]
I'll take this up, the implementation would (most likely) be pushed to this PR: https://github.com/openshift/odo/pull/1446

**Comment by cdrage** [comment]
Hey @dgolovin Fix is available here: https://github.com/openshift/odo/pull/1446

If you can test it out that'd be great :+1:

**Comment by kadel** [comment]
Closing this.
@dgolovin if you still face this issue, feel free to re-open this issue
