### ISSUE TITLE
Autocompletion for `--context` flag

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1546]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Add autocompletion to `--context` flag

## Why is this needed? 

because it helps :smile:

**Comment by surajnarwade** [comment]
Closing since `FileCompletionHandler` is already there

**Comment by kadel** [comment]
@surajnarwade is it working for you?


When I run  `odo create java --context <tab>` I get this:
```
▶ odo create java --concompgen:96: no such file or directory: /Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/odo
compgen:96: no such file or directory: /Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/odo
compgen:96: no such file or directory: /Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/odo
```

**Comment by surajnarwade** [comment]
@kadel , it works for me:

```
$ odo create nodejs --context 
./            .gitignore    .odo/         package.json  server.js     views/        
.git/         helm/         openshift/    README.md     tests/    
```

are you using master build ?

**Comment by kadel** [comment]
Ah, my bad 😇 
I forgot to update my path (`redhat-developer` vs `openshift`), sorry about that.
