### ISSUE TITLE
rewrite e2e test to new test format

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1548]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
spec isolation, parallel run, better test structure, easy to maintain 

## Test file to migrate

- [ ] e2e_test.go

- [ ] component and sub-component test

- [ ] java test

- [ ] json format test

- [ ] link test

- [ ] login test

- [ ] source test

- [ ] watch test

NOTE: Any new test file should follow the test [template](https://github.com/openshift/odo/blob/master/tests/e2e/template_cleantest_test.go) 

## How to write 

Follow the test [template](https://github.com/openshift/odo/blob/master/tests/e2e/template_cleantest_test.go)

**Comment by kadel** [comment]
Don't convert scenarios 1:1, we need to do the reorganization.
It would be nice if we have a separate file for each test scenario.
@cdrage had some nice ideas for this.

**Comment by mohammedzee1000** [comment]
Agreed

**Comment by amitkrout** [comment]
Closed via #1612
