### ISSUE TITLE
Validate config values

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1549]
`odo config set` needs to check if the input value is valid
This can't be allowed:

```
▶ odo config set memory asdf
? memory is already set. Do you want to override it in the config Yes
Local config was successfully updated.

tmp/odo-examples/nodejs-ex  master ✗                                                                                        241d ⚑ ◒
▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: /Users/tkral/tmp/odo-examples/nodejs-ex
  SourceType: local
  Application: nodejs-ex-wzxy
  Project: tkral
  Name: mynode
  MinMemory: asdf
  MaxMemory: asdf

```

Sensible validation needs to be added to each config option.
Some of the validation: 
 - Correct value for memory and cpu (with units check)
    - memory and cpu should be validated using the same rules as Kuberentes uses (for example support both `M` and `Mi` - https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory)
 - length check for name, project, and application
 - ...

**Comment by girishramnani** [comment]
needed before beta @kadel ?

**Comment by kadel** [comment]
> needed before beta @kadel ?

I would say good to have.

**Comment by dharmit** [comment]
```
 ./odo config view
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component
```
which looks similar to #1599

**Comment by girishramnani** [comment]
@dharmit `odo config view` will only work if you have a component in the current folder
which means as the command suggest you need to create a component by doing 
`odo create <type>`  or `odo create nodejs`
