### ISSUE TITLE
Test coverage is not reported on each pr

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1557]
[kind/bug]

## What versions of software are you using?
- Operating System: CI Setup
- Output of `odo version`: master

## How did you find it?
Check coverage report on each pr

## Actual behavior
No coverage report

## Expected behavior
Test coverage should be reported on each pr

**Comment by kanchwala-yusuf** [comment]
@amitkrout , Can you please provide more details as to what is expected here? Can you please elaborate? Thanks

**Comment by amitkrout** [comment]
@kanchwala-yusuf Early days odo repo was being maintained in ```github.com/redhat-developer/odo``` org, later it moved to OpenShift org which we currently working on. During the repo migration it seem certain make target does not work for us. For example, each pr run executes code coverage target [1] but the report does not reflected in pr like it was reflecting before [2]. You can refer [3] for more understanding.

[1] https://github.com/openshift/odo/blob/master/.travis.yml#L26
[2] https://github.com/openshift/odo/pull/818#issuecomment-427797354
[3] https://docs.codecov.io/docs/pull-request-comments

NOTE: you may need write access to make the changes in odo repo setting. @kadel can you please grant write access to @kanchwala-yusuf

**Comment by kanchwala-yusuf** [comment]
> @kanchwala-yusuf Early days odo repo was being maintained in `github.com/redhat-developer/odo` org

Is this is the link you are referring to:

**Comment by amitkrout** [comment]
> > @kanchwala-yusuf Early days odo repo was being maintained in `github.com/redhat-developer/odo` org
> 
> Is this is the link you are referring to:
> https://github.com/redhat-developer/odo-fork

yes

**Comment by kanchwala-yusuf** [comment]
Codecov provides code coverage reports.

Codecov has two types of settings to be done:
1. For all the repositories in the organization.
2. For local repository

1. For all the repositories, codecov requires:
- Either add  "CodeCov Team bot" or "CodeCov Github Integration" to the openshift org. This can be done by the openshift account org administrators.
Refer: https://docs.codecov.io/docs#section-advanced-usage

- Team Yaml to be created. This file is global for all the repositories in an organization. Can be created only by the team owners.
Refer: https://docs.codecov.io/docs/codecov-yaml#section-team-yaml

2. For local repository
- Code coverage file to be available for code coverage analysis. In ODO, this file is present in `scripts/generate-coverage.sh`. This file should be executed as a part of the Travis CI.

- Correct configuration of `.travis.yml` file, which is present. 
Refer: https://github.com/codecov/example-go#travis-ci

- Correct configuration in `.codecov.yml`
Refer: https://docs.codecov.io/docs/codecov-yaml#section-repository-yaml


I observe that the local repository requirements are fulfilled by the `openshift/odo` repository.

We may need some help in setting up requirements for all repositories as specified in section #1.

**Comment by kadel** [comment]
Why all repositories in org? It is not possible to enable it for just one single repo?

**Comment by kanchwala-yusuf** [comment]
> Why all repositories in org? It is not possible to enable it for just one single repo?

So CodeCov has two types of settings:
1. Global (I made up this word) settings which are common to all the repositories. These are configured in a file called "Team Yaml"
2. Local settings which override globally settings. These are configured in ".codecov.yml" which is already present in odo repo.

**Comment by kanchwala-yusuf** [comment]
Thanks to @amitkrout, codecov comments are being posted on PRs after the access to codecov was granted at the openshift org level.

Now that we can see the codecov reports on each PR, closing this issue.

Please reopen if necessary.
