### ISSUE TITLE
GolangCI and codeclimate bot is missing after org migration

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1561]
[kind/bug]

## What versions of software are you using?
- Operating System: CI Setup
- Output of `odo version`: master

## How did you run odo exactly?
Check GolangCI and codeclimate bot on each pr

## Actual behavior
None have access to openshift org, so missing on each pr.

## Expected behavior
Should have access to openshift/odo

**Comment by kadel** [comment]
I would like to start a debate on how useful those tools were. Did someone actually use those?

**Comment by girishramnani** [comment]
We have golangCI bot enabled and I am not sure about the importance of codeclimate bot. 
Closing this issue. If someone feels codeclimate is helping us then please re-open this issue
