### ISSUE TITLE
Documentation conversion from .md -> .adoc 

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1565]
[kind/Documentation]

A few todo's for .md to .adoc conversion:

- [ ] Synchronization script must be updated
- [x] CLI reference script must also be updated to use .adoc instead of markdown.

**Comment by cdrage** [comment]
@Preeticp Could you please add some more todo's / checklist of what needs to be done before the documentation goes live?

**Comment by Preeticp** [comment]
Convert all docs to asciidoc:
- [ ] Installation
- [ ] Getting Started
- [ ] Development
- [ ] Readme
- [ ] CI reference
- [ ] CLI reference
- [ ] Completion Architecture
- [ ] Examples
- [ ] logging
- [ ] tdd-workflow
- [ ] validation architecture

**Comment by Preeticp** [comment]
@cdrage all docs have been converted to asciidoc, You can go ahead with changes in the script.

**Comment by kadel** [comment]
@cdrage we need to change the scripts. We can't mantain docs in both formats

**Comment by cdrage** [comment]
@kadel I'll push the changes today to use .adoc instead.

**Comment by kadel** [comment]
This shouldn't be closed.

https://github.com/openshift/odo/blob/master/cmd/cli-doc/cli-doc.go is still generating markdown and needs to be updated

/cc @girishramnani @cdrage

**Comment by cdrage** [comment]
I have this already in the sprint planning and will be working on this soon. Fixing the generating markdown file as well as auto synchronization.

**Comment by girishramnani** [comment]
please close this issue @cdrage if its resolved

**Comment by cdrage** [comment]
@girishramnani It's not yet, still need to add the auto sync working :+1:

**Comment by cdrage** [comment]
Closing this issue in favour of: #1679
