### ISSUE TITLE
Organize the tests in a proper way

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1581]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Tests 

## Why is this needed? 
The current test is not properly organized and issues are encountered while improving the test scenarios. 

Inspired from - https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html

**Comment by amitkrout** [comment]
Current test tree structure 
```
$ tree -L 2
.
├── OWNERS
└── e2e
    ├── README.md
    ├── cmp_sub_test.go
    ├── cmp_test.go
    ├── component.go
    ├── e2e.go
    ├── e2e_test.go
    ├── examples
    ├── helper
    ├── java_test.go
    ├── json_test.go
    ├── link_test.go
    ├── login_test.go
    ├── service_test.go
    ├── source_test.go
    ├── template_cleantest_test.go
    ├── utils.go
    └── watch_test.go

3 directories, 16 files
```

Proposal 
```
$ tree -L 2
.
├── OWNERS
├── e2e-scenarios
│   └── e2e_test.go
├── helper
│   ├── helper_filesystem.go
│   ├── helper_generic.go
│   ├── helper_oc.go
│   └── helper_run.go
├── integration
│   ├── cmp_sub_test.go
│   ├── cmp_test.go
│   ├── component.go
│   ├── e2e_test.go
│   ├── integration_test.go
│   ├── java_test.go
│   ├── json_test.go
│   ├── link_test.go
│   ├── login_test.go
│   ├── service_test.go
│   ├── source_test.go
│   └── watch_test.go
├── test-src
│   ├── binary
│   └── source
└── test-template
    └── template_cleantest_test.go

7 directories, 19 files
```

**Comment by amitkrout** [comment]
**Integration test -** It covers only the feature test. For example in ```json format``` feature only that feature will be tested like ```odo url create -o json, odo storage create -o json, odo project list -o json ...```
**Purpose:** Just to make sure the feature works fine and doesn't break any existing feature. 

**End to End test -** It covers the mostly the real time user specific scenario. For example as a user i can do
```
1. login
2. Create component from source like local or git
3. Push component with watch
4. link component 
5. mount storage
6. create service
7. Delete project
8. logout
```
**Purpose :** Just to make sure as a single run all the feature works fine 

So don't mix integration test with end to end test.

**Comment by kadel** [comment]
> ├── test-src

what is test-src? Are those the sample application on which we run tests?

**Comment by amitkrout** [comment]
> > ├── test-src
> 
> what is test-src? Are those the sample application on which we run tests?

Yes, Will put those binary and source (Which are currently in [examples](https://github.com/openshift/odo/tree/master/tests/e2e/examples) directory) in this directory.

**Comment by kadel** [comment]
> > > ├── test-src
> > 
> > 
> > what is test-src? Are those the sample application on which we run tests?
> 
> Yes, Will put those binary and source (Which are currently in [examples](https://github.com/openshift/odo/tree/master/tests/e2e/examples) directory) in this directory.

not sure if test-src is a good name for that

**Comment by amitkrout** [comment]
@girishramnani @kadel Doc [1] will be the reference for writing the test from scratch.Tomorrow i will categorize the integration test and update here with more details. 

[1] https://docs.google.com/document/d/1RKva9lvIR6dLmDm2tlqmp8V4nFjlrXdulOQ4FSmLkr8/edit?ts=5c715ffd#heading=h.eqonbgz6nece

**Comment by amitkrout** [comment]
Need some more time to update the new test workflow in a separate google doc then will share with the team for feedback.

**Comment by kadel** [comment]
> Need some more time to update the new test workflow in a separate google doc then will share with the team for feedback.

lets figure out the structure first

**Comment by amitkrout** [comment]
> > Need some more time to update the new test workflow in a separate google doc then will share with the team for feedback.
> 
> Let's figure out the structure first.
> 
> We need to keep writing tests, and we need to know where to put what test

I ma looking structure like this 

```$ tree -L 2
.
├── OWNERS
├── e2e-scenarios
├── helper
├── integration
├── examples
└── test-template
```

Which folder contains what 
e2e-scenarios - End to end scenario
helper - Only contains library 
integration - Component lavel testing
examples - Binary and source for test scenario
test-template - Only a demo test of how to write test

So total no of test suite will be used  - 3
E2E test
Integration Test
Test template
**Why need 3 testsuite -** To solve the propose what they are created for. 
**Where they run -** 
Integration test - Runs only on prs
E2E test + Integration test - Runs only in nightly
Test template - This will only be available for manual run just to see how to write clean test

@girishramnani @mohammedzee1000 @kadel does it make sense ?

**Comment by kadel** [comment]
> **E2E test + Integration test -** Runs only in nightly

I think that we will be able to run e2e on PRs. Because of the nature of our project e2e tests are going to be faster than integration tests. If we run them in a separate job it won't add any time to the total duration of the test.


In general, this looks good. Now the main question. How do we move to this new format?

**Comment by amitkrout** [comment]
> I think that we will be able to run e2e on PRs. Because of the nature of our project e2e tests are going to be faster than integration tests. If we run them in a separate job it won't add any time to the total duration of the test.

No doubt of E2E duration will be less than the whole integration test duration but once integration test start growing bigger then E2E test duration matters a lot because e2e also keeps updated time to time.  That's why i kept it in a separate job to avoid any future rework of split, moreover the nightly job will be like a release bits of master. 

> In general, this looks good. Now the main question. How do we move to this new format?

This should go in a single pr, no followup pr unless there is a hard requirement. moreover i am in the favor of single mindset and one time effort so that it completely replace the old structure. I will draft a pr.
