### ISSUE TITLE
odo component list --all

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1584]
`odo component list --all` - list all component in the current project (as set by KUBECONFIG)
`odo component list --all --project myproject` - list all component in project myproject

Output could look something like this:
```
Component     Application    Type
myjava        myapp          java
mynode        anotherapp     nodejs
```

**Comment by surajnarwade** [comment]
one query, this should work from any location, right ?

**Comment by kadel** [comment]
> one query, this should work from any location, right ?

yes

**Comment by surajnarwade** [comment]
@kadel , as you mentioned `Application` column here, for uniformity, I think it will be good to add this column to `odo list` and `odo list --path` also

**Comment by jorgemoralespou** [comment]
@surajnarwade Hey, Watched the recording from the sprint and one thing I noticed is that when local, the URL for the code location was described as `file://./`. IMHO we should provide as an annotation the path for the component sources so a user can easily find it in his drive. I think this was on an issue, but commenting here as it's the only link I have.

There's a related issues to this that I could find. https://github.com/openshift/odo/issues/1356

cc/ @kadel
