### ISSUE TITLE
'odo list' command should provide option to show not deployed components in local filesystem along with deployed ones

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1587]
[kind/Feature]

## Which functionality do you think we should add?
In odo up to v0.0.20 new component is always deployed to the cluster. That means after successful 'odo create'  command 'odo list' would always list created component. With new workflow that would not work that way anymore, because new component created only in local file-system and not deployed to the cluster.

Would be good to support that in new odo without change, by saving new not deployed component's location in ~/.odo configuration and then inlude them in `odo list` or at least provide search for component in the specified local file system folder(s) with recursion support.

## Why is this needed?
To allow developers and tools see list of all locally created not deployed yet components.

## Workaround 
Devs or tools would have to iterate over local file-system folder and use `odo describe --context folder/path` to test if there component in specified `folder/path`.

**Comment by kadel** [comment]
How about something like `odo component discover `
This command will search given path, and list all components, based on presence of `.odo` dir that it can find in given path


```
odo component discover --path Documents/MyProjects

Name                 Type    Path
myfirstcompnent      java    Documents/MyProjects/MyJavaProject
mysecontcomp         nodejs  Documents/MyProject/MyNodeProject
```

and also with `-o json`

That will be list of all info from the .odo/config.yaml in json format
```json
{
   "kind":"List",
   "apiVersion":"odo.openshift.io/v1alpha1",
   "items":[
      {
         "kind":"LocalConfig",
         "apiversion":"odo.openshift.io/v1alpha1",
         "ComponentSettings":{
            "Type":"java",
            "SourceLocation":"/Users/user/Documents/MyJavaProject",
            "SourceType":"local",
            "Application":"myapp",
            "Project":"myproject",
            "Name":"myfirstcomponent"
         }
      },
      {
         "kind":"LocalConfig",
         "apiversion":"odo.openshift.io/v1alpha1",
         "ComponentSettings":{
            "Type":"nodejs",
            "SourceLocation":"/Users/user/Documents/MyNodeProject",
            "SourceType":"local",
            "Application":"myapp",
            "Project":"myproject",
            "Name":"mysecontcomp"
         }
      }
   ]
}
```

**Comment by kadel** [comment]
Instead of a new command, we could also introduce a new flag to `odo component list`.

That might be better, but it might require to rework how `odo component list` is defined right now. Currently, it is used to list components inside the given application.



Operations that `odo component list` should support:
 - list deployed components in the given application and project
 - list components in given paths (what I described as `discovery` in the previous comment)
 - list deployed components in an application that is defined by `--context` flag (the same application and project as the component inside the context dir)

**Comment by surajnarwade** [comment]
qs: if I mention `--path /home/user/code`, odo should crawl through every directory present and check for `.odo` directory right ?

also that means, `odo component list` should work without `--context` flag ?

cc @kadel

**Comment by surajnarwade** [comment]
I started working on this, I propose following solution, WDYT @kadel @dgolovin 
(ignore wrong values if any)

where `SOURCE` is where source code resides or maybe relative to `path` provided
`STATE` is whether it is deployed or not

```
$ odo list --context odo-example/nodejs-ex --path odo-example
ACTIVE     NAME                      TYPE         SOURCE                     STATE
*          nodejs-dcca               nodejs       file://./                  deployed
           test                      testtype     odo-example/cakephp-ex      not deployed
```

**Comment by girishramnani** [comment]
I would like to propose a `--depth n` flag to limit the recursive searches odo does.

**Comment by kadel** [comment]
> where `SOURCE` is where source code resides or maybe relative to `path` provided
> `STATE` is whether it is deployed or n

It would be great if `SOURCE` is in one common format, having one in uri form and other not looks weird and it will complicate things

**Comment by kadel** [comment]
> I started working on this, I propose following solution, WDYT @kadel @dgolovin
> (ignore wrong values if any)
> 
> where `SOURCE` is where source code resides or maybe relative to `path` provided
> `STATE` is whether it is deployed or not
> 
> ```
> $ odo list --context odo-example/nodejs-ex --path odo-example
> ACTIVE     NAME                      TYPE         SOURCE                     STATE
> *          nodejs-dcca               nodejs       file://./                  deployed
>            test                      testtype     odo-example/cakephp-ex      not deployed
> ```
> 
> using `--context` because as of now, it is mandatory.

Makes sense. But I think that @dgolovin is mainly interested in the JSON output

**Comment by dgolovin** [comment]
> I started working on this, I propose following solution, WDYT @kadel @dgolovin
> (ignore wrong values if any)
> 
> where `SOURCE` is where source code resides or maybe relative to `path` provided
> `STATE` is whether it is deployed or not
> 
> ```
> $ odo list --context odo-example/nodejs-ex --path odo-example
> ACTIVE     NAME                      TYPE         SOURCE                     STATE
> *          nodejs-dcca               nodejs       file://./                  deployed
>            test                      testtype     odo-example/cakephp-ex      not deployed
> ```
> 
> using `--context` because as of now, it is mandatory.

`-o json` support is what we need in vscode.

`SOURCE` column contains component's source like local folder path, local binary path or git URL, doesn't it? Would be also good to have CONTEXT column.

**Comment by surajnarwade** [comment]
@dgolovin @kadel , one more question

when I run `odo component list --path some-path`, so it should look for that path and check for components only in that path, right ? it should not list other deployed component from other directory, correct ?

**Comment by kadel** [comment]
> @dgolovin @kadel , one more question
> 
> when I run `odo component list --path some-path`, so it should look for that path and check for components only in that path, right ? it should not list other deployed component from other directory, correct ?

yes, correct

**Comment by dgolovin** [comment]
@kadel I remember we agreed to support list of folders for --path option, so we can scan all the folders from path and list all the components there. In this case would be good to know what CONTEXT is. 
The same would be good in case there are several components down the directory hierarchy.

In general I would say 'list' means dealing with several components, if you are going to list only component in --path, it would be just duplication of `odo describe --context /path/to/context`, because we can use it to detect component in specific folder.

**Comment by kadel** [comment]
> @kadel I remember we agreed to support list of folders for --path option, so we can scan all the folders from path and list all the components there. In this case would be good to know what CONTEXT is.
> The same would be good in case there are several components down the directory hierarchy.

Yes, context path will be in the output. Even for several components in the hierarchy.


> 
> In general I would say 'list' means dealing with several components, if you are going to list only component in --path, it would be just duplication of `odo describe --context /path/to/context`, because we can use it to detect component in specific folder.


I'm a little bit confused. 
 - `odo component list --context ` displays all components that are deployed in the same application as a given component (the one in context dir)
 - `odo component list --path` displays all component in a given filesystem path (it walks through whole path)

 Let's say that I have the following structure
```
/Code
  |- frontend 
  |  |- component1 
  |  |  |- .odo
  |  |  |- src  
  |  |- component2 
  |     |- .odo
  |     |- src 
  |- backend
     |- component3 
        |- .odo
        |- src  
```

executing `odo component list --path /Code` will dispaly information about all three components. With context pointing to `/Code/frontend/component1`, `/Code/frontend/component2` and `/Code/backend/component3`

executing `odo component list --context /Code` will error out. 
executing `odo component list --context /Code/frontend/component1` will list all components that are **deployed** in the same application as the `component1`. Those components might not even have source files in the local filesystem.

**Comment by kadel** [comment]
@dgolovin I'll look into that next.

> Otherwise we will have to get components with `odo list --path --project --app` option to find out what is in vscode workspace.
> Then run `odo list --project --app` to find out deployed components.
> Then reconcile two sets to present them under application node in tree.

There is one slight complication for you. The deployed component doesn't have to have the source code in the local machine. It could be deleted, or deployed by someone else or from another computer.

**Comment by dgolovin** [comment]
> There is one slight complication for you. The deployed component doesn't have to have the source code in the local machine. It could be deleted, or deployed by someone else or from another computer.

@kadel I understand this and ready to deal with it. 

Would be easier for me if deployed components would have annotation to save context path, so it would be easy to understand if it is present on users local machine or not. Now I have always search for component using project/application/component names.

**Comment by kadel** [comment]
> > There is one slight complication for you. The deployed component doesn't have to have the source code in the local machine. It could be deleted, or deployed by someone else or from another computer.
> 
> @kadel I understand this and ready to deal with it.
> 
> Would be easier for me if deployed components would have annotation to save context path, so it would be easy to understand if it is present on users local machine or not.

We used to save it as an annotation. We don' do that anymore, as it creates another more issues. For example, the user might move the source code to a different location, or it might be pushed from a different machine.
