### ISSUE TITLE
Get odo binaries packaged with OpenShift

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#1594]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
We should get odo binaries published in Openshift as a client tool like oc

## Why is this needed? 
Better visibility and we are an OpenShift client

Internal jira tracker:
https://jira.coreos.com/browse/ART-554

**Comment by mohammedzee1000** [comment]
OpenShift ART (Automatic Release Tooling) are looking to mirror our releases into
https://mirror.openshift.com/pub/

**Comment by mohammedzee1000** [comment]
Had dicsussion on coreos channel https://coreos.slack.com/archives/CB95J6R4N/p1554904866475800
Collab with oc team if they are ok with splitting into clients/oc and clients/odo https://bugzilla.redhat.com/show_bug.cgi?id=1666573

**Comment by mohammedzee1000** [comment]
Binaries from our current releases published on https://mirror.openshift.com/pub/openshift-v4/clients/odo/
Daily job setup to pull our latest in. So once we release our beta, it should likely reflect there

**Comment by mohammedzee1000** [comment]
https://github.com/openshift/aos-cd-jobs/pull/1788

**Comment by mohammedzee1000** [comment]
Contacting oc team to find out additional actions, if any that we might need to take

**Comment by mohammedzee1000** [comment]
We should have odo binaries linked to OpenShift console at soon.  A quick fix is underway.

**Comment by mohammedzee1000** [comment]
Getting odo on OpenShift console 
https://jira.coreos.com/browse/CONSOLE-1380 and https://github.com/openshift/console/pull/1420

**Comment by girishramnani** [comment]
@sspeiche are we bundling `odo` binary with `oc`. Do we need something more like bundling the `odo` binary in the RPM for GA?

**Comment by sspeiche** [comment]
@girishramnani I'd have to research it, though I'd expect it to be aligned with where `oc` is...which is bundled with RPM. I don't know if that has changed or will change.

**Comment by sspeiche** [comment]
I haven't tracked down rpm details but the console links to the mirror site http://mirror.openshift.com/pub/openshift-v4/clients/odo/

**Comment by kadel** [comment]
@mohammedzee1000 how is it going with the checklist?

**Comment by girishramnani** [comment]
After a discussion in an ART integration cabal, we found that openshift release feature release happens every 1 month and minor bug fix releases every week. This schedule aligns with what we wanted.
Doc - https://mojo.redhat.com/docs/DOC-1182562
cc @mohammedzee1000 @sspeiche @kadel

**Comment by girishramnani** [comment]
So we now want to setup odo releases in two ways
- odo binary as part of openshift images 
- odo binary as part of openshift RPM repositories

**Comment by kadel** [comment]
@mohammedzee1000 Do you have any updates on this?

**Comment by mohammedzee1000** [comment]
Alright so here is what we need right now

- [ ] rhel packaging for our supervisord image https://github.com/openshift/odo-supervisord-image

- [ ] odo packages in image as oc is for local delivery https://github.com/openshift/origin/blob/master/images/cli/Dockerfile.rhel

- [ ] odo binary and rpm built and packages via brew

**Comment by mohammedzee1000** [comment]
@openshift/openshift-team-automated-release

**Comment by mohammedzee1000** [comment]
git@github.com:mohammedzee1000/odo-supervisord-image.git

**Comment by mohammedzee1000** [comment]
https://jira.coreos.com/browse/ART-811

**Comment by mohammedzee1000** [comment]
odo should use rhel based supervisord on rhel when it has been built
https://github.com/openshift/odo/issues/1935

**Comment by mohammedzee1000** [comment]
Setting up a call with Jessica Forrester to hash this out
/cc @jwforres

**Comment by mohammedzee1000** [comment]
Getting supervisord image to build without pulling from internet https://github.com/openshift/odo-supervisord-image/pull/26

**Comment by mohammedzee1000** [comment]
Consolidated document https://docs.google.com/document/d/1nBa2RqrxGIaohNVXWctA1PLqs3wiQ9q_ltFyNQDMens/edit#

**Comment by mohammedzee1000** [comment]
- Waiting on IT to add me to `devel` ldap group to have write access to our dist-gits
- Got added to openshift team on comet (check document above, TLDR: internal OSBS UI) Looking at comet, how most of the containers are maintained.
- Above PR needs to go in to be able to properly build the image ^

**Comment by mohammedzee1000** [comment]
Release information will be available in internal git reposiroty

**Comment by amitkrout** [comment]
Done as per reference - https://jira.coreos.com/browse/ART-554

/close
