### ISSUE TITLE
`--now` flag for `odo component create`, `odo url create --now`, `odo config --now`

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1595]
```
odo component create --now
```
will create the local configuration and create all objects on the cluster (the same what `odo push --config` is doing)

```
odo url create --now
```
creates the url in the config and propagates all the changes to the cluster  (`odo push --config`)

```
odo config set --now
```
the same as above

**Comment by mohammedzee1000** [comment]
Currently looking at normal push, figuring out how it can be reused

**Comment by girishramnani** [comment]
adapter team is wating for this issue and so we need this before GA
