### ISSUE TITLE
Can't list components without first creating one

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1599]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: master

## How did you run odo exactly?

```sh
github.com/openshift/odo master ✔                                                                                                                                    7h46m  ⍉
▶ ./odo catalog list components
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component
```

## Actual behavior

Can't list catalog components without having to use `odo create`

## Expected behavior

Listing all components available

**Comment by cdrage** [comment]
ping @girishramnani

**Comment by kadel** [comment]
It is actually possible, but it is not convenient and intuitive.

you have to specify both, `--project` and `--app` flags

```
odo component list --project myproject --app myapp
```

To list applications in the project:
```
odo app list --project myproject
```

**Comment by kadel** [comment]
decreasing priority, as we have a workaround, not much user-friendly one but it exists

/priority medium

**Comment by dharmit** [comment]
I'm confused here. @cdrage is trying:
```bash
$ ./odo catalog list components
```
But the workaround given by @kadel is:
```bash
$ odo component list --project myproject --app myapp
```
If I run the first command with those flags, it fails because those subcommands don't exist:
```bash
$ ./odo catalog list components --project myproject --app app
Error: unknown flag: --project
Usage:
  odo catalog list components [flags]

Examples:
  # Get the supported components
  odo catalog list components

Flags:
  -h, --help   help for components

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default false)
      --skip-connection-check            Skip cluster check
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

 ✗  unknown flag: --project
```

So what exactly need to be fixed?

**Comment by cdrage** [comment]
What needs to be fixed is being able to use `odo catalog list` without having to create a component / service :(

**Comment by dharmit** [comment]
> What needs to be fixed is being able to use odo catalog list without having to create a component / service.

@cdrage you mean, one should be able to execute `odo catalog list` from anywhere on the system and not only from a directory that's got `.odo/config.yaml`, right? I understand why that should be possible because as a user I might want to quickly look at the type of components I can create before I create one for my project.

Tangential question: What commands should work similarly without a user having to create anything first? For example, there's another command that can be used with `list` but doesn't on my Minishift cluster:
```bash
$odo catalog list services
 ✗  unable to list services because Service Catalog is not enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "developer" cannot list clusterserviceclasses.servicecatalog.k8s.io at the cluster scope: no RBAC policy matched
```
I see the Catalog on Minishift console but above command fails. Is it due to permissions issue as mentioned in the end of the error message?

**Comment by girishramnani** [comment]
@dharmit service catalog is not present in minishift, you would need to add it.

**Comment by dharmit** [comment]
> @dharmit service catalog is not present in minishift by default, you would need to add it.

Thanks! I didn't know. I assumed the `<minishift-ip>:8443/console/catalog` to be Service Catalog. :(

Setting up Service Catalog and doing things with it looks like yet another can of worms so I think I'll pass that for now. However, even after bringing up Minishift with it enabled using below command:
```bash
$ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--enable=*,service-catalog"
```
as recommended in the [docs](https://docs.okd.io/latest/minishift/using/experimental-features.html#enabling-experimental-oc-flags), I fail to list the services using `odo` from a directory that doesn't have `.odo/` directory:
```bash
$ odo catalog list services 
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component

$ odo version               
odo v1.0.0-beta1 (c226b008)

Server: https://192.168.42.179:8443
Kubernetes: v1.11.0+d4cacc0
```
Is this normal? I have the same tangential question that I asked in my previous comment:
> Tangential question: What commands should work similarly without a user having to create anything first?
