### ISSUE TITLE
Questions around "Component" and "odo create" based on the README

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1605]
[kind/Documentation]

## What did you find missing in the documentation?
- I found the definition of "Component" to be ambiguous/confusing. 
- Few other things w.r.t. `oc`/`kubectl`

## What is the relevance of it?
Not sure. Maybe it could confuse the user?

## Description
Not sure if it's just me or the definition of "Component" is really a bit confusing. I'm referring Glossary section on main README page. Even before that when I was following the `nodejs-ex` example, it seemed a bit vague/confusing as to what a "Component" means. 

I'm looking at examples mentioned in `oc create -h` and am a bit confused by this example:
```
# A specific image version may also be specified
$ odo create nodejs:latest
```
I have now understood that component name here is `nodejs` and image version is `latest`. But the `nodejs:latest` combination can very well (and probably more commonly, thanks to `docker pull` example) be used to refer to an image and its tag. I was thinking of it in terms of `docker pull nodejs:latest` so to me it seemed like `nodejs:latest` is the image name plus its tag and not `<component>:<image-version>`.

In another  example:
```
# Create a new Node.js component of version 6 from the 'openshift' namespace
$ odo create openshift/nodejs:6 --local /nodejs-ex
```
I think when we refer to a template from another namespace while using `oc`, we use double forward slash like this:
```
$ oc process -p MEMORY_LIMIT=2Gi openshift//jenkins-persistent | oc create -f -
```
But in this case we're using only one `/`. I know it's not a big deal but just pointing it out. Also, going back to earlier point, `openshift/nodejs:6` looks more like an image name that I would `docker pull`.

As a user I was wondering that why `odo url create` and not `odo create url`. Devs in the team are quite likely going to chuckle/laugh at this but isn't that the way `oc`and `kubectl` also do things? It seemed confusing to me when I saw `odo url create`. But I understand that `url` is not a `component`. However, I'm not entirely sure what a Component is in the first place. 

In Glossary we say:

> odo supports multiple component types like nodejs, perl, php, python, and ruby.

But that's ambiguous because I *think* we're referring to programming languages as well as frameworks as "Components". 

**I'm 100% sure that there are reasons for doing what we are doing. But I'm looking at things as a user right now so that I can understand things and contribute to the project. A really n00b user, tbh.**

**Comment by Preeticp** [comment]
Needs docs

**Comment by boczkowska** [comment]
We now have an expanded glossary for the key concepts in odo, and also the overview of the architecture: https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_developer_cli/understanding-odo.html
Does it help in claryfing some of these questions and points?

**Comment by dharmit** [comment]
@boczkowska it helps clarify what a "component" means. But other question in this issue stand as-is. However, it's something for us devs to discuss IMO.

@kadel can you look at the issue description and share your thoughts please?

**Comment by Preeticp** [comment]
@dharmit we have addressed this issue via this PR: https://github.com/openshift/openshift-docs/pull/20106 please let us know if we can close this issue?

**Comment by dharmit** [comment]
@Preeticp thanks for fixing this. Good to close!

/close
