### ISSUE TITLE
odo httpd --local rsync failure

### ISSUE THREAD

**Issue by martin-morales** [openshift/odo#1609]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10, Minishift with VirtualBox driver.
- Output of `odo version`:
odo v0.0.20 (bd3e74a4)                                                                                                                                                                                          Server: https://192.168.99.111:8443                                                                     Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?
`odo app create <appname>`
`git clone https://github.com/martin-morales/httpd-ex`
`cd httpd-ex`
`odo create httpd --local C:\Users\mmoral04\Desktop\httpd-ex\`
`odo push`

## Actual behavior
The odo push fails with an rsync command not found error. The app deploys and when I create a route for 8080, I get the Red Hat Enterprise Linux Test Page and not my html files.

## Expected behavior
The HTTPD app to deploy properly with the local html files that I have. Note: this worked with the --git flag and in fact the local files I'm using is the same repo cloned.

This works:
`odo app create <appname>`
`odo create httpd --git https://github.com/martin-morales/httpd-ex`
`odo push`
`odo url create --port 8080`
I can access the website and I see my own webpage and not the Red Hat page.

## Any logs, error output, etc?
`C:\Users\mmoral04\Desktop\httpd-ex>odo push
[1mPushing changes to component: httpd-ex-httpd-gghu[0m                                                [32m✓[0m  Waiting for component to start                                                              [32m✓[0m  Copying files to component                                                                  [31m✗[0m  Unable to build files
+ set -eo pipefai
+ '[' '!' -z /opt/app-root/src ']' 
+ '[' /tmp '!=' /opt/app-root/src ']' 
+ '[' '' '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/                                                   /var/lib/supervisord/bin/assemble-and-restart: line 19: rsync: command not found                                                                                                                                 [31m✗[0m  Building component
 [31m✗[0m  command terminated with exit code 127

Also note: that at least on Windows 10 the output from most odo commands on a command prompt gives a lot of missing characters: "[32m✓[0m  Checking component "

**Comment by mohammedzee1000** [comment]
/cc @cdrage 
You have worked with windows side more. Maybe you can triage this?

**Comment by yohanswanepoel** [comment]
I have the same issue on on Fedora with OCP 4.1

odo version
odo v1.0.0-beta2 (242f0979)

Server: https://api.crc.testing:6443
Kubernetes: v1.13.4+f2cc675

It looks like it is trying to run rsync in the container but that does not exist in the image.

odo push
 ✓  Checking component
 ✓  Checking component version
 ◒  Applying component settings to component: httpd-ptnm ✓  Checking URL httpd-ptnm
 ✓  Successfully created URL for component: httpd-ptnm
 ✓  http://httpd-ptnm-app-test.apps-crc.testing
 ✓  Applying component settings to component: httpd-ptnm
 ✓  Successfully updated component with name: httpd-ptnm
 ✓  Pushing changes to component: httpd-ptnm of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✗  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
/var/lib/supervisord/bin/assemble-and-restart: line 19: rsync: command not found

**Comment by cdrage** [comment]
So with regards to the Windows output, that's been fixed.

I'll investigate this. It's either something we need to fix upstream in the `httpd` container, or downstream (not use `rsync`).

Either way, I'll take this up :+1:

**Comment by cdrage** [comment]
Opened up an issue upstream, let's see what happens: https://github.com/sclorg/httpd-container/issues/78

**Comment by cdrage** [comment]
So: https://github.com/sclorg/httpd-container/issues/78 just got closed. rsync has been added to the base container.

Not too sure if this happens *immediately* or happens in the next release of OpenShift, but the issue will be resolved soon :+1:

**Comment by amitkrout** [comment]
Just tested on macOS + odo master and it works without the failure mentioned above.
Closing the issue fo now. Feel free to reopen it if you still face the issue
/close
