### ISSUE TITLE
Schedule nightly job on prow

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1613]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Nightly job for running odo tests (Integration + e2e) on prow

## Why is this needed? 
To reduce total time taken for pr testing job.

**Comment by mohammedzee1000** [comment]
I guess it would help in the way you say if we rebalance pr tests accordingly

**Comment by amitkrout** [comment]
Yes, Just waiting for my another pr #1612 to go in first then only we can implement this issue in more efficient and stable way.

**Comment by girishramnani** [comment]
In one of the discussions with @kadel we decided to not run tests as nightly but on each PR.
Hence I think this issue becomes invalid. Closing.
