### ISSUE TITLE
Uncomment and resolve link_tests

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1616]
Currently the link_tests are failing, we should uncomment them and update them so they don't fail.

**Comment by syamgk** [comment]
https://github.com/openshift/odo/pull/1580 there is a pr for link_test wrt to the new workflow

**Comment by girishramnani** [comment]
duplicate of #1700, should close this or that please advice @kadel

**Comment by kadel** [comment]
> duplicate of #1700, should close this or that please advice @kadel

we close the newer issues as a duplicate and keep this one, as it was first

**Comment by girishramnani** [comment]
@amitkrout assigning this to you
