### ISSUE TITLE
test flake on e2e-core test

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1621]
* On PR: https://github.com/openshift/odo/pull/1610

* In this logs, `oc new-project,  myproject` is working fine:

Link: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/1610/pull-ci-openshift-odo-master-e2e-core/530/build-log.txt

* In this log, `oc new-project myproject` is failing:

Link: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/1610/pull-ci-openshift-odo-master-e2e-core/528/build-log.txt

Error is:

```
++ oc new-project myproject
error: You must be logged in to the server (Unauthorized)
```

**Comment by kadel** [comment]
closing in favor of https://github.com/openshift/odo/issues/1638

/close
