### ISSUE TITLE
.gitignore and .odoignore not working correctly under Windows

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1630]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`: master

## How did you run odo exactly?

Using `odo watch` after deploying a component

## Actual behavior

.odoignore and .gitignore isn't working correctly.

## Expected behavior

To ignore files correctly

## Any logs, error output, etc?

See: https://github.com/openshift/odo/pull/1601 after findings implementing the relative path PR, it looks like ignoring files hasn't worked on Windows for a while..

**Comment by girishramnani** [comment]
@kadel is this only confined to `odo watch` or `odo push` too

**Comment by cdrage** [comment]
@girishramnani It's happening in both watch and push I believe. 100% watch as that is what I've been testing.

**Comment by cdrage** [comment]
IMO should we create an additional document instead of having it only in the getting-started guide for .odoignore and .gitignore?

https://github.com/openshift/odo/blob/c27e25e93a6a940b434444e8743f1d9219235aaa/docs/getting-started.adoc

Ping @boczkowska
