### ISSUE TITLE
OpenShift CI : Flaky openshift clusters with login failures

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#1638]
[kind/bug]

## What versions of software are you using?
OpenShift CI

## How did you run odo exactly?
Run tests on OpenShift CI

## Actual behavior
Randomly fails with unauthorized at various points in test run, even after successful login

## Expected behavior
CI Should not be failing on login especially after a successful login

## Any logs, error output, etc?
```
++ sleep 3
++ for i in '{1..40}'
++ oc login -u developer -p developer
++ '[' 0 -eq 0 ']'
++ OC_LOGIN_SUCCESS=true
++ break
++ '[' -z true ']'
++ oc whoami
error: You must be logged in to the server (Unauthorized)
++ oc new-project myproject
Now using project "myproject" on server "https://api.ci-op-t5jndf67-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git
```

Note Logs above representative as they are from one instance, but multiple tests fail with
```
Result: 
 stdout: 
 stderr: ✗  Please log in to the cluster
```
on multiple instances
/kind test-flake
/kind flake
/area testing

**Comment by mohammedzee1000** [comment]
Example : https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_odo/1636/pull-ci-openshift-odo-master-e2e-core/637

**Comment by mohammedzee1000** [comment]
Conversation with auth team https://coreos.slack.com/archives/CEKNRGF25/p1556020997133000
Most likely cause https://bugzilla.redhat.com/show_bug.cgi?id=1694878

**Comment by amitkrout** [comment]
Frequency of hitting the the issue has increased in recent days  - https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_odo/1612/pull-ci-openshift-odo-master-e2e-core/838

**Comment by stevekuznetsov** [comment]
Is there a final determination of what is wrong from auth?

**Comment by mohammedzee1000** [comment]
They were pointing it to the fapping api server and it definetly looks like it. It looks like it is happening more often again

**Comment by stlaz** [comment]
I believe "flapping" is the word we used :smile: 

There were fixes to this in authn operator, not sure about apiserver.
https://github.com/openshift/cluster-authentication-operator/pull/125 (May 4)
https://github.com/openshift/cluster-authentication-operator/pull/120 (Apr 29 - only if you're setting up IdPs in your test cluster)
https://github.com/openshift/cluster-authentication-operator/pull/118 (Apr 27 - quite important, would have caused "Unauthorized" issues as well)

**Comment by stevekuznetsov** [comment]
OK, please keep me up to date on any needs you have from DPTP.

**Comment by kadel** [comment]
It looks like this should be resolved. The Bugzilla issue was closed

**Comment by amitkrout** [comment]
Closing the issue as it has been fixed in https://bugzilla.redhat.com/show_bug.cgi?id=1694878
