### ISSUE TITLE
odo login does not work properly when connection insecure

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#1643]
When logging to a cluster with self signed certificates, the message that asks you to bypass certificate check is not shown.

odo version: odo v1.0.0-beta1

```
$ odo login https://master.mycluster.com
```

Hangs there. If you enter anything, it tells you to:

```
Please enter 'yes' or 'no'.
```

If you enter `yes`, then you're prompted for the username.

If `--insecure-tls-skip-verify`is provided, then everything works fine:

```
$ odo login https://master.mycluster.com --insecure-skip-tls-verify
Authentication required for https://master.mycluster.com:443 (openshift)
Username:
```

This is the correct output when using `oc`:

```
$ oc login https://master.mycluster.com
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://master.mycluster.com:443 (openshift)
Username:
```

**Comment by jorgemoralespou** [comment]
As part of the fix for this one, we should also fix the message being displayed, as it says:

```
You have access to the following projects and can switch between them with 'odo project <project-name>':
```

And it should say:

```
You have access to the following projects and can switch between them with 'odo project set <project-name>':
```

Or even not print anything else after the Login successful, or just print the current project, and a hint in case you want to change project:

```
 ✓  Login successful. You're using project `default`
HINT: You can use another project by doing `odo project set <project-name>`
HINT: You can list existing projects by doing `odo project list`
HINT: You can create a new project by doing `odo project create <project-name>`
HINT: Look at `odo project --help` for other project related commands
```

**Comment by cdrage** [comment]
This has a fix located here: https://github.com/openshift/odo/pull/1652

**Comment by girishramnani** [comment]
closing this issue as this was fixed as mentioned by @cdrage
