### ISSUE TITLE
Running odo commands outside of the component directory

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1646]
Improve commands so they can be executed outside of the component context or they provide more information on how to use them.

**This applies to all commands:**
If the command is run "outside the component" and no `--project` flag is set, use project that is set in `KUBECONFIG`. That means that `--project` flag will be optional even if the command is run outside component context.

#### `odo app list`
right now:
```
▶ odo app list
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to a directory with a component
```

Better would be to use the project from `KUBECONFIG` if there is no component in the current directory and no `--project` flag was specified.

```
▶ odo app list

Applications deployed in "myproject" project:
NAME
firstapp
secondapp

```

#### `odo app describe`
Currently the same as `odo app list`
This would be better

```
▶ odo app describe
 ✗  the current directory does not represent an odo component.
Please specify the application name and project. 
HINT: See 'odo app describe --help' for more information.
```

#### `odo app delete`
```
▶ odo app delete
 ✗  the current directory does not represent an odo component.
Please specify the application name.
HINT: See 'odo app delete --help' for more information.
```

- `odo app delete myapp` is valid and it should try to delete the application from the current project
- `odo app delete myapp --project` is valid and it should try to delete the application from the current project
- `odo app delete` is valid only if it is run in the component context, and it will try to delete the whole application where the component is

#### `odo component list`
instead of this:
```
▶ odo component list
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to a directory with a component
```
something like this would be better
```
▶ odo component list
 ✗  the current directory does not represent an odo component.
Please specify project and application to list components deployed in a given project and application.
HINT: See 'odo component list --help' for more information.
```

 `odo component list --app myapp`  is a valid command even outside of the context. It should list components inside the application in default project as set in `KUBECONFIG`

#### `odo component describe`
Currently, the same situation as with `odo component list`
Instead, do this?
```
▶ odo component describe 
 ✗  the current directory does not represent an odo component.
Please specify the name of the deployed component, application, and project.
HINT: See 'odo component describe --help' for more information.
```
 `odo component describe mycomponent --app myapp`  is a valid command even outside of the context. 

#### `odo component delete`
```
▶ odo component delete
 ✗  the current directory does not represent an odo component.
Please specify the name of the deployed component, application, and project.
HINT: See 'odo component delete --help' for more information.
```

- `odo component delete componnet --app app --project myproject` - valid command
- `odo component delete nodejs-sbqo --app app` - valid command. Project is used form `KUBECONFIG`
- `odo component delete nodejs-sbqo  --project myproject1` - **not** valid. If application flag is required if running outside component context
- `odo component delete` - valid only if running inside component context

**Comment by surajnarwade** [comment]
as I am started exploring #1587 #1584 I found that first command should be `odo app list` which will run even outside the context

**Comment by mik-dass** [comment]
> odo app delete myapp is valid and it should try to delete the application from the current project

Should this behaviour be  for `app describe` too?

**Comment by kadel** [comment]
> @kadel Should this behaviour be for `app describe` too?

yep, the same behavior can be applied

**Comment by mik-dass** [comment]
> ▶ odo app describe
 ✗  the current directory does not represent an odo component.
Please specify the application name and project. 
HINT: See 'odo app describe --help' for more information.

The above message seems to be confusing. The first line indicates that the command should be fired from inside a directory while the second line tells the opposite.

**Comment by kadel** [comment]
> > ▶ odo app describe
> > ✗  the current directory does not represent an odo component.
> > Please specify the application name and project.
> > HINT: See 'odo app describe --help' for more information.
> 
> The above message seems to be confusing. The first line indicates that the command should be fired from inside a directory while the second line tells the opposite.

You are right, it might be a little bit confusing.
Feel free to modify those messages for something better.
Maybe "Please specify context directory or specify application and project name"? I'm not good with this, I bet that whatever you come with will be better than this :-D

**Comment by mik-dass** [comment]
> Maybe "Please specify context directory or specify application and project name"? I'm not good with this, I bet that whatever you come with will be better than this :-D

@kadel I am not good with this too. I am confused as well :D @jorgemoralespou @girishramnani @surajnarwade Please help.

**Comment by mik-dass** [comment]
@kadel How about?

```
Please specify the application name and project.
Or use the command from inside an odo directory.
HINT: See 'odo app describe --help' for more information.
```

**Comment by kadel** [comment]
> @kadel How about?
> 
> ```
> Please specify the application name and project.
> Or use the command from inside an odo directory.
> HINT: See 'odo app describe --help' for more information.
> ```

That looks great and much cleaner. I'm just not sure about `odo directory` it might not be clear what that means.  How about replacing `odo directory`  with `directory with odo component`?

**Comment by mik-dass** [comment]
> How about replacing odo directory with directory with odo component?

Ok cool. That sounds cleaner :+1:
