### ISSUE TITLE
odo app create command missing in windows beta

### ISSUE THREAD

**Issue by gshepherd7** [openshift/odo#1651]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10
- Output of `odo version`: v1.11.0+d4cacc0

## How did you run odo exactly?
odo login -u developer -p developer
odo app create test

## Actual behavior
Error: Use one of available subcommands: delete, describe [application-name], list
Usage:
  odo app [flags]
  odo app [command]
etc...

## Expected behavior
Switched to application: test in project: myproject

## Any logs, error output, etc?
Nothing more than listed in the Actual behavior above.  This occurred with windows beta exe download.

**Comment by jorgemoralespou** [comment]
@gshepherd7 that odo version does not exist. Can you verify again what version of `odo` you're using?

**Comment by jorgemoralespou** [comment]
Also, in latest release `v1.0.0-beta1` application is no longer a command. You don't need to create an application, as odo will create it for you, although if you want your component to be created in a specific application, you can provide a `--app` flag to every component related command

**Comment by gshepherd7** [comment]
Sorry...posted the Kubernetes version.  odo version is 0.0.20 (0f63cc5a)

Was going through some of the openshift tutorials which pointed me to downloading the most recent verison of odo and using the app create command.

**Comment by jorgemoralespou** [comment]
Docs and the tutorials have not yet been updated. Sadly, and they still use version 0.0.19. In 0.0.20 things started to change.
We should be up to date soon(ish)

**Comment by anthcp** [comment]
I have just installed the Mac OSX version of ODO and the "odo app create" option is also missing e.g "odo app create myapp
Error: Use one of available subcommands: delete, describe [application_name], list"

**Comment by jorgemoralespou** [comment]
As I said, tutorials and doc needs to be updated ASAP.

cc/ @cdrage @kadel

**Comment by kadel** [comment]
@jorgemoralespou 
`odo app create` is not mentioned anywhere in the tutorials or docs.

**Comment by kadel** [comment]
@anthcp 

> I have just installed the Mac OSX version of ODO and the "odo app create" option is also missing e.g "odo app create myapp
> Error: Use one of available subcommands: delete, describe [application_name], list"
> I can see above that you don't need to use this command so what is the alternative syntax?


You don't need to create an application before creating component anymore (starting from v1.0.0-beta1). Just use `--app` flag for `odo component create` command, the component will be added to the application, no need to create it beforehand.

**Comment by surajnarwade** [comment]
@anthcp @gshepherd7 can we close this ? since there's no mention of `odo app create` command and @kadel mentioned the right way for this in above command.

**Comment by surajnarwade** [comment]
Closing this issue since @kadel has given resolution
