### ISSUE TITLE
Info message is printed during binary component creation

### ISSUE THREAD

**Issue by jankleinert** [openshift/odo#1653]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: v1.0.0-beta1

## How did you run odo exactly?

clone https://github.com/grahamdumpleton/parksmap-web

```
mvn package
odo create java frontend --binary target/parksmap-web.jar --app parksmap
```

## Actual behavior
```
odo create java frontend --binary target/parksmap-web.jar --app parksmap
I0425 19:11:24.732607    1769 create.go:138] target/parksmap-web.jar
 ✓  Checking component
 ✓  Checking component version
Please use `odo push` command to create the component with source deployed
```

## Expected behavior
I wouldn't expect that info message to be printed:
I0425 19:11:24.732607    1769 create.go:138] target/parksmap-web.jar

https://github.com/openshift/odo/blob/2b98a06e811a60a08c9a6545c9698896d91e8f0b/pkg/odo/cli/component/create.go#L138

**Comment by cdrage** [comment]
Hey all, I've opened up a PR here: #1657
