### ISSUE TITLE
Successful login gives incorrect help to use `odo projects`

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#1662]
[kind/bug]

## What versions of software are you using?
- Operating System: Mac
- Output of `odo version`:

```  odo version
odo v1.0.0-beta1 (c226b008)
$ odo login
Authentication required for https://api.openshift.codeready.cloud:6443 (openshift)
Username: kubeadmin
Password: 
 ✓  Login successful.

You have access to 65 projects, the list has been suppressed. You can list all projects with 'odo projects'

Using project "default".

$ odo projects
Error: Use one of available subcommands: app, catalog [options], component, config, create <component_type> [component_name] [flags], delete <component_name>, describe [component_name], help [command], link <service> --component [component] OR link <component> --component [component], list, log [component_name], login, logout, preference, project [options], push [component name], service, storage, unlink <service> --component [component] OR unlink <component> --component [component], update, url, utils, version, watch [component name]
```

## Correct message should be

```
You have access to 65 projects, the list has been suppressed. You can list all projects with 'odo project list'
```

**Comment by girishramnani** [comment]
this issue with this message is this it comes from `oc`'s code base i.e. 
https://github.com/openshift/odo/blob/c88f02e247710c51c11ac4662ea69086e1bbcaf9/vendor/github.com/openshift/origin/pkg/oc/cli/login/loginoptions.go#L328
which mean we cannot directly update it. And I would suggest to follow `oc` convention that we should have an alias for `odo projects` in the mean time.

**Comment by kadel** [comment]
> which mean we cannot directly update it. And I would suggest to follow `oc` convention that we should have an alias for `odo projects` in the mean time.

We can update it. We already replace `oc new-project` with `odo project create` (https://github.com/openshift/odo/blob/6bd0d73dc67e014e34f7e92a35dab26734163afc/pkg/auth/login.go#L56)

**Comment by mohammedzee1000** [comment]
@dharmit loading you up with easy fixes you may want to pick up

**Comment by cdrage** [comment]
@dharmit if you want to take this up as a first issue feel free to! :+1:

**Comment by girishramnani** [comment]
@cdrage please refer the PR that solves this issue

**Comment by girishramnani** [comment]
closing this issue
