### ISSUE TITLE
Setup project and milestone via prow

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#1663]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
We should redirect milestone and project setup via bot commands

## Why is this needed? 
Makes it closer to OpenShift workflow. Also allows us to remove write aceess from most contributors preventing manual errors

**Comment by mohammedzee1000** [comment]
PR for enabling plugins https://github.com/openshift/release/pull/3624

**Comment by mohammedzee1000** [comment]
Need to setup necessary groups / teams to give permissions to

**Comment by kadel** [comment]
we already have @openshift/odo-maintainers group (`3185642`)

**Comment by mohammedzee1000** [comment]
Yes, i am mainly looking at how it can be configured

**Comment by mohammedzee1000** [comment]
Milestone plugin enabled on `odo maintainers` team. project plugin is underway
https://github.com/openshift/release/pull/3742

**Comment by mohammedzee1000** [comment]
@kadel if you can confirm both plugins are functional, i will close this issue

**Comment by kadel** [comment]
milestone command is working perfectly, but project does not :-(

**Comment by kadel** [comment]
any updates on /project command? It is still not working :-(

**Comment by adambkaplan** [comment]
Issues related to prow should be sent to @openshift/openshift-team-developer-productivity-test-platform

**Comment by stevekuznetsov** [comment]
Looking at the help for it, it's not obvious how to do a project name with more than one word:

https://prow.svc.ci.openshift.org/command-help?repo=openshift%2Fodo#project

/project foo

**Comment by stevekuznetsov** [comment]
So the plugin does seem to be on...

**Comment by mohammedzee1000** [comment]
Hmm,  is something wrong with the config. I set the same team id as for milestone, and that works, so what is up with project. The team it shows does not seem to exist.

**Comment by mohammedzee1000** [comment]
> Issues related to prow should be sent to @openshift/openshift-team-developer-productivity-test-platform

Sorry, that is my bad,  clicked the wrong team

**Comment by stevekuznetsov** [comment]
No, I think it is a bug against the plugin, I do not think it handles multi-word project names. Could you report it to `kubernetes/test-infra`?

**Comment by kadel** [comment]
@mohammedzee1000 It looks like that it can't handle even dashes in a name.
I've created the project `test-project` -  it didn't work. Then I renamed it to `testproject` and it worked

**Comment by mohammedzee1000** [comment]
@kadel @stevekuznetsov ^

**Comment by mohammedzee1000** [comment]
Strange this is also something strange, you are able to add, but im not. I can manipulate milestone though
/milestone 1.0

**Comment by mohammedzee1000** [comment]
Ok the team id is same but team indicated is different o_O

**Comment by mohammedzee1000** [comment]
https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml#L774-L785
How is there so much diff in behavior?

**Comment by stevekuznetsov** [comment]
Neither of those teams exist, I don't know how you configured them -- the team that _does_ exist is `odo-maintainers-1` https://github.com/orgs/openshift/teams/odo-maintainers-1

**Comment by mohammedzee1000** [comment]
I got the ID from github api
https://github.com/openshift/release/pull/3731#issue-277386518

**Comment by mohammedzee1000** [comment]
@stevekuznetsov

**Comment by girishramnani** [comment]
TBH this issue has been open for long and we have been able to live without this feature. Hence closing. If someone feels it is still relevant then they can re-open this issue
