### ISSUE TITLE
Documentation for "odo component create"

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1667]
[kind/Documentation]

## What did you find missing in the documentation?
As a new user of `odo`, I tried doing `odo component create` and was pleasantly surprised by the iterative manner in which `odo` asked me various questions and lets me configure things as per my requirement.
```bash
/tmp/django_simple » odo component create
? Which component type would wish to create python
? Which version of 'python' component type would you wish to create 3.6
? Location of context component, relative to '/tmp/django_simple' /tmp/django_simple
? Which input type would wish to use for the component local
? How would you wish to name the new component python-miib
? Which application do you want the commponent to be associated with new-app
? Which project go you want the component to be created in new-project
? Do you wish to set advanced options Yes
? Enter the ports you wish to set (for example: 8080,8100/tcp,9100/udp). Simply press 'Enter' to avoid setting them 8080
? Enter the environment variables you would like to set (for example: MY_TYPE=backed,PROFILE=dev). Simply press 'Enter' to avoid setting them 
? Do you wish to set resource limits Yes
? Enter the maximum memory (for example 100Mi) 1Gi
? Enter the minimum memory (for example 100Mi) 1Gi
? Enter the maximum CPU (for example 100m or 2) 2
? Enter the minimum CPU (for example 100m or 2) 0.5
 ✓  Checking component
 ✓  Checking component version
Please use `odo push` command to create the component with source deployed
/tmp/django_simple » odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              python:3.6
Application       new-app
Project           myproject
SourceType        local
Ref               
SourceLocation    /tmp/django_simple
Ports             8080
Name              python-miib
MinMemory         1Gi
MaxMemory         1Gi
Ignore            
MinCPU            0.5
MaxCPU            2
```
Does it make sense to have this documented in the repo?

I was not able to understand why the opening line in README read:
> OpenShift Do (odo) is a fast, iterative, and straightforward CLI tool for developers who write, build, and deploy applications on OpenShift.

I always wondered what was "iterative" about `odo` till I saw what `odo component create` does.
## What is the relevance of it?
This could be helpful to the new users who are just getting started with `odo`.

**Comment by jorgemoralespou** [comment]
Iterative in the context of odo's README is not meant for this behavior but rather than for allowing developers to develop applications in a fast and iterative manner. This means code, test, code, test, but not going through GIT at all. in odo, this would be:
- code, push, test, code, push ,test 
or
- watch, code, test, code, test.

**Comment by dharmit** [comment]
@jorgemoralespou thanks for that explanation. It makes sense.

In fact, a few hours back (before looking at your response) I felt like I was wrong in my expectations as far nitpicking the word 'iterative' is concerned.

Anyhow, I feel that an asciinema of `odo component create` would be helpful to a new user to help understand that they can set the config parameters as a first step, should they wish to. Would like to know what the team thinks.
