### ISSUE TITLE
Re-enable watch tests

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1669]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

We need to re-enable watch tests.

## Why is this needed? 

In order to test the stability of `odo`, `odo watch` tests should be re-enabled: https://github.com/openshift/odo/blob/master/tests/e2e/watch_test.go

**Comment by girishramnani** [comment]
watch tests have been re-enabled  as it can be observed here https://github.com/openshift/odo/blob/master/tests/integration/cmd_watch_test.go
