### ISSUE TITLE
Installation document should be similar to the README doc

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1670]
[kind/Documentation]

## What did you find missing in the documentation?

https://github.com/openshift/odo/blob/master/docs/installation.adoc and https://github.com/openshift/odo/blob/master/README.adoc should be similar / almost indistinguishable. The only difference between the two should be that the installation doc contains all the "alternative" ways of installation such as by OS (CentOS / Ubuntu, etc.).

## What is the relevance of it?

Both docs should be similar, right now, they're too different.

**Comment by dharmit** [comment]
@cdrage @Preeticp can you guys please provide your feedback on https://github.com/openshift/odo/pull/1735 ?
