### ISSUE TITLE
What's the difference between 'odo create' and 'odo component create' ?

### ISSUE THREAD

**Issue by rhuss** [openshift/odo#1673]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

I'm just making an experiment to work with odo without any documentation. I still remember parts of it (cool stuff), and I knew there was an answer for the following question, I just can't remember it. But:

What's the difference between 'odo component create/delete/describe' and 'odo create/delete/describe' ?

The help message is confusing here:

```
Component Commands:
  component   Components of an application (create, delete, describe, get, link, list, log, push, unlink, update, watch)
  create      Create a new component
  delete      Delete an existing component
  describe    Describe the given component
```

The difference is not clearly understandable here.

## Why is this needed? 

To not confuse noob users like me.

**Comment by jorgemoralespou** [comment]
`odo create` is an alias to `odo component create` for those that don't like typing. All the actions, if no resource is specified should apply to component.

This should be clearly stated in the documentation. Some time ago we agreed to not show the shorter version as commands, but rather as information on the help.

Something along the lines of:

```
odo -h
Odo (OpenShift Do) is a CLI tool for running OpenShift applications in a fast and automated matter. Odo reduces the complexity of deployment by adding iterative developme
nt without the worry of deploying your source code.

Find more information at https://github.com/openshift/odo

Usage:
  odo [flags]
  odo [command]

Examples:
  # Creating and deploying a Node.js project
  git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
  odo component create nodejs
  odo push

  # Accessing your Node.js component
  odo url create

odo Commands:
Component Commands:
  component   Components of an application (create, delete, describe, get, link, list, log, push, unlink, update, watch). This can be skipped if a subcommand (verb) is directly used.
  app         Perform application operations (delete, describe, list)
  catalog     Catalog related operations (describe, list, search)
  preference  Modifies preference settings (set, unset, view)
  project     Perform project operations (create, delete, get, list, set)
  service     Perform service catalog operations (create, delete, list)
  storage     Perform storage operations (create, delete, list, mount, unmount)
  url         Expose component to the outside world (create, delete, list)
```

**Comment by rhuss** [comment]
I see, thanks for the explanations.

Having it only in the examples section but not listed below in the 'reference' section is confusing typo (one would always think about a typo). A comment could help here, too, but maybe a section "Shortcuts" in the help message would make the intention more clear? 

E.g.

```
Shortcuts:

    odo create     == odo component create
    odo delete     == odo component delete
    odo describe == odo component describe

```

**Comment by rhuss** [comment]
Also, I would really try to avoid tautologies in the usage description overall

I.e. instead of 

```
  create      Create a new component
  delete      Delete an existing component
  describe    Describe the given component
```

just

```
  create      Create a component
  delete      Delete a component
  describe    Describe a component
```
("component" is here the important information)

**Comment by rhuss** [comment]
Sorry to be picky (and playing the German here ;), but remember, the usage page will be the first contact to odo for the impatient user. I suggest to handover "odo" without any explanation to someone and let him try to find how it works **without any documentation**. (that's the execercise I'm just trying to perform). If this works for the basic stuff, then I think it passes the litmus test.

The description should be consistent, too. i.e.:

```
odo Commands:
  component   Performs component operations (create, delete, describe, get, link, list, log, push, unlink, update, watch). Default operations will be done on a component if the the command name is skipped.
  app         Perform application operations (delete, describe, list)
  catalog     Catalog related operations (describe, list, search)
....
  service     Perform service catalog operations (create, delete, list)
```

It should be either `Perform catalog related operations` or move everything to nominal style. Also the difference between "catalog related operations" (command: "catalog") and "service catalog operations" (coman: "service") is not clear.

**Comment by jorgemoralespou** [comment]
@rhuss German is good. German is squared ;-)

I agree with all your comments.

**Comment by cdrage** [comment]
@rhuss 

I can take this up since I'm pretty in-tune with the help output.


The only problem is this:

```sh
Shortcuts:
  create      Create component
  delete      Delete a component
  describe    Describe a component

Component Commands:
  component   Components of an application (create, delete, describe, get, link, list, log, push, unlink, update, watch)
  config      Modifies configuration settings (set, unset, view)
  link        Link component to a service or component
  list        List all components in the current application
  log         Retrieve the log for the given component
  push        Push source code to a component
  unlink      Unlink component to a service or component
  update      Update the source code path of a component
  watch       Watch for changes, update component on change
```

You suggest we add "create, delete, describe" as shortcuts..

If you think about it, push, unlink, update, watch, etc. are all shortcuts as well. They are all aliased versions of `odo component link` or `odo component unlink` or `odo component update`, etc.

So what do you suggestion that we do?

At this point, I'm debating about removing `odo component` completely...

**Comment by kadel** [comment]
> At this point, I'm debating about removing `odo component` completely...

The main point is to have `odo component` as the primary command. And clearly highlit that what are shortcuts or aliases.


@cdrage could we do something like this?

```
Commands:
  component   Components of an application (create, delete, describe, get, link, list, log, push, unlink, update, watch)
  app         Perform application operations (delete, describe, list)
  catalog     Catalog related operations (describe, list, search)
  preference  Modifies preference settings (set, unset, view)
  project     Perform project operations (create, delete, get, list, set)
  service     Perform service catalog operations (create, delete, list)
  storage     Perform storage operations (create, delete, list)
  url         Expose component to the outside world (create, delete, list)


Shortcuts:
  create = component create 
  config = component config
  delete = component delete
  describe = component describe
  link = component link
  list = component list
  log = component log
  push = component push
  unlink = component unlink
  watch  = component watch
```

**Comment by cdrage** [comment]
@kadel 

That's my point though... we already have something like this:

```sh
Component Commands:
  component   Components of an application (create, delete, describe, get, link, list, log, push, unlink, update, watch)
  config      Modifies configuration settings (set, unset, view)
  create      Create a new component
  delete      Delete an existing component
  describe    Describe the given component
  link        Link component to a service or component
  list        List all components in the current application
  log         Retrieve the log for the given component
  push        Push source code to a component
  unlink      Unlink component to a service or component
  update      Update the source code path of a component
  watch       Watch for changes, update component on change

Other Commands:
  app         Perform application operations (delete, describe, list)
  catalog     Catalog related operations (describe, list, search)
  preference  Modifies preference settings (set, unset, view)
  project     Perform project operations (create, delete, get, list, set)
  service     Perform service catalog operations (create, delete, list)
  storage     Perform storage operations (create, delete, list, mount, unmount)
  url         Expose component to the outside world (create, delete, list)

```

It's as easy as moving `component` to "other commands" and renaming "Component Commands" to "Shortcuts".

Is that something we want?

**Comment by kadel** [comment]
> Is that something we want?

yes, but for shortcuts instead of description, I would point to the full command

**Comment by cdrage** [comment]
I don't think that modifying the description to use:

```sh
create = component create
```

Would help much for new users. I do like the way we have it right now,.

What about something like this?

```sh
Shortcuts:
  config      Modify local configuration (component config)
  create      Create a new component (component create)
  delete      Delete an existing component (component delete)
  ...
```

or

```sh
Shortcuts:
  config [component config]     Modify local configuration
  create [component create]    Create a new component
  delete [component delete]     Delete an existing component 
  ...
```

**Comment by rhuss** [comment]
All proposals sound good to me as they make it clear that component commands can be used directly.

What about having a 

```
Commands:
    component           ....
    app                         ....
    ....

The following component specific actions can be used directly:
    config                    ..... (shortcut for "component config")
    create                    .... (shortcut for "component create")
    ....
```

(i.e. using a short sentence as an introduction for the command specific actions)

**Comment by cdrage** [comment]
PR here! https://github.com/openshift/odo/pull/1763
