### ISSUE TITLE
Proposal document for rewriting the occlient package

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1678]
[kind/Enhancement]

The current occlient related code which is responsible for communicating with openshift cluster is scattered in different places and needs well designed interfaces and abstractions. So a rewrite of the `occlient` package with these goals should be considered - 

- having an interface which then can be used to provide support for kubernetes and Knative.
- ~~easy to understand, more maintainable and can be consumed by other projects.~~
-  Reduce/Avoid race conditions.
- Good to have : parallel/concurrent API calls embedded in the core package making odo faster.
/cc @jorgemoralespou @kadel

**Comment by kadel** [comment]
> * easy to understand, more maintainable and can be consumed by other projects.

We don't have to consider other projects. It can be tailored just for our use case

**Comment by kadel** [comment]
proposal: https://docs.google.com/document/u/1/d/1LDtJEuyfh7QLZPtgpojHTLOK2qXVdjZPgzt1vOHvWqg/edit

**Comment by dharmit** [comment]
- Support for Kubernetes makes sense as OpenShift is a distro of Kubernetes. But why do we need to support Knative?
- Are there any examples (GH issues, maybe?) of the race conditions we face at the moment?

**Comment by girishramnani** [comment]
we already have some work being done on `kclient` package in this PR https://github.com/openshift/odo/pull/2458
Hence closing
