### ISSUE TITLE
UC 23: As a developer, I want ocd to remember the application I was last working on on a per OpenShift project basis

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#168]
When I switch to a different OpenShift project, ocd should automatically put me in the context of the last known application I was working on for that project.  

If the application no longer exists in the project follow this algorithm:

```
If app does not exist then
  If there are no applications then
    Create application “app” and default to it
  else
    If application “app” exists then
        Use application “app”
     else
        Choose one application randomly
    end
  end
end
```

the ocd tool should display an error similar to the following:

The last known application <name-old> for this project does not exist.  Known applications are:
<name-1> (*)
<name-2> 
You have been switched to the <name-1> application. To use a different application, use the ocd app command to select the application.

Or

The last known application <name-old> for this project does not exist.
Default application “app” was created and you were switched to it.

```
$ ocd project create myproj1
$ ocd project create myproj2

$ ocd project myproj1 // app=app
$ ocd create httpd myhttps // app=app in myproj1
$ ocd project myproj2  //should load my last working app 
  -- you are current working on the default application //if none has created
 -- you are currently working the app application in the myproj2 project
```

**Comment by kadel** [comment]
decompose.  foundations are already in, and those will be part of MVP. But in general this is not MVP requirement

**Comment by jorgemoralespou** [comment]
@kadel not to disagree yet once again, but while #600 covers the active component, we still need a way to track what is the current application, or at least think what will be the experience when we create a component from scratch as there will not be a way to set/link it to an existing application unless you explicitly set it. 
Now with "automatic detection of the context" we need to make sure that some information related to a component is stored in the local odo config that is gitignored, and at the same time that we have in the odo global config what's the application we're working on. Food for thought.

**Comment by kadel** [comment]
odo now works in the context of the current directory

/close
