### ISSUE TITLE
list all url in application

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1680]
It would be great to have a command that can list all URLs in an application.

**Comment by girishramnani** [comment]
we can consider an `--app` flag for url list command e.g. `odo url list --app <app>`  to show all the urls in a specific app

**Comment by kadel** [comment]
> we can consider an `--app` flag for url list command e.g. `odo url list --app <app>` to show all the urls in a specific app

that flag already exists it allows you to list urls for a component in a different application

```
odo url list --app myapp --component mycomponent
```



We need to think about what will be the most intuitive way. 
For example, one option could be that if `--app` is specified but no `--component` than list urls for all components in the app. Problem with this that we need to have the same behavior for all the commands, otherwise it will be confusing.

**Comment by girishramnani** [comment]
remove-lifecycle stale.
