### ISSUE TITLE
README Has Broken Links Due to Referencing .md Instead of .adoc

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1692]
[kind/Documentation]

## What did you find missing in the documentation?

Links under the `Additional documentation` section in the main `README.adoc` for the project have broken links due to the `.md` to `.adoc` conversion for documentation. 

## What is the relevance of it?

The `Additional documentation` links in the main `README.md` come back as 404s due to incorrect references.

**Comment by amitkrout** [comment]
/priority high
/assign @Preeticp 

@Preeticp Please check the doc links associated with https://github.com/openshift/odo/blob/master/README.adoc#additional-documentation
