### ISSUE TITLE
UC 25: As a developer, I want to be able to manage storage for a component in an easy way

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#170]
As a developer, I want to be able to add storage to a component in an easy way, only requiring the common minimal information (type, size and path) 

Storage scenarios:
- Create storage
- Update storage
- Delete storage
- Mount/Unmount storage

```
$ cd myapp
$ ocd create mongodb
$ ocd storage create [name] [--size=1GB] [--access=single/multi] [--path=/opt/data/mongodb] [--component=<name>]
-------------
$ ocd storage update [name] [--size=1GB] [--access=single/multi] [--path=/opt/data/mongodb] [--component]
-------------
$ ocd storage delete [name]
Do you really want to delete storage for component <name> (y/n)?
-------------
$ ocd storage mount [name] [--path=] [--component]
$ ocd storage umount [name] [--component]
```

__*NOTE:*__ At least for Red Hat provided components the --path argument has to be optional.
Access defaults to “single”. Options single container access or multiple container access (a.k.a concurrent)

$ ocd storage create will create a PVC and mount it on the component
$ ocd storage umount will just unlink the pvc from the component but does not delete the volume or claim
$ ocd storage mount will link a pvc to a component at the specified path
$ ocd storage update while providing a new size should add additional GB to the current PVC.

Tasks (add issues if tasks are deferred):
- [x] #226 Create storage
- [ ] #227 Update storage
- [x] #228 Delete storage
- [ ] #229 Mount storage
- [x] #230 Unmount storage

**Comment by kadel** [comment]
we need to decompose this to smaller tasks

**Comment by cdrage** [comment]
Again, see: https://github.com/redhat-developer/ocdev/issues/226 can we close this @kadel ?

(sorry for the copy paste, haha)

**Comment by kadel** [comment]
mount, unmount implemented
/close
