### ISSUE TITLE
Cannot list odo resources until component is created and used as a context

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1712]
[kind/bug]
## What versions of software are you using?
- Operating System:
Windows 10 Pro
- Output of `odo version`:
```
~/.vs-openshift/odo.exe version
odo v1.0.0-beta1 (1af22f3b)
Server: https://10.0.0.46:8443
Kubernetes: v1.11.0+d4cacc0
```
built from master branch

## How did you run odo exactly?
1. ```odo catalog list components```
2. ```odo catalog list services```
3. ```odo list --project project1 --app app1```
4. ```odo.exe component list --app app1```
5. ```odo.exe storage list --app app1 --component node4```
6. ```odo.exe url list --app app1 --component node4```
## Actual behavior
```
X  the current directory does not represent an odo component.                                                                                                                                                                               Maybe use 'odo create' to create component here or switch to directory with a component
```
This is happening even for commands that does not have --context option.

## Expected behavior
List requested objects.

## Any logs, error output, etc?
N/A

**Comment by dgolovin** [comment]
As workaround for now home directory can be used as current working directory for all commands and that fixes the issue, because home directory has ```.odo``` configuration present.

**Comment by kadel** [comment]
@dgolovin  #1646 should solve this problem once implemented

**Comment by surajnarwade** [comment]
Among all commands mentioned, all except following are resolved:

```
odo storage list --app app1 --component node4
odo url list --app app1 --component node4
```

**Comment by girishramnani** [comment]
@dgolovin is this issue still relevant?

**Comment by dgolovin** [comment]
@girishramnani @kadel Not really relevant anymore, because context folder is required for component's commands to work.

**Comment by girishramnani** [comment]
closing as this seems to not be relevant anymore.
