### ISSUE TITLE
Autocompletion is not working for `--context` in `odo push`

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1718]
[kind/bug]

## What versions of software are you using?
- Operating System: Linux
- Output of `odo version`:
odo v1.0.0-beta1

## How did you run odo exactly?

Hi tab `odo push --con`

Tab completion is failing with similar error for following commands as well:

- `odo component {delete, describe, link, log, push, unlink, update, watch}`
- `odo {delete, describe, link, log, push, unlink, update, watch}`
- `odo service {create, delete}`
- `odo storage delete`
- `odo url delete`

## Actual behavior

```
$ odo push --con ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component
```

## Expected behavior

auto completion should work for all flags for `odo push` command.

**Comment by surajnarwade** [comment]
autocompletion for `odo push` works only if we are running it from same directory

**Comment by mohammedzee1000** [comment]
On a connected note, we are apparently checking for active cluster during auto completion
```
$ odo push --co ✗  Please log in to the cluster
 ✗  Please log in to the cluster
 ✗  Please log in to the cluster

```
Reproduced
```
odo push --co ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component

```

**Comment by mohammedzee1000** [comment]
It seems connection check and context creation happens even with autocompletion

**Comment by kadel** [comment]
blocked on #1588

**Comment by kadel** [comment]
no need to block this anymore

**Comment by dharmit** [comment]
Moving this to ready since it was reproduced in https://github.com/openshift/odo/issues/1718#issuecomment-494264709

/state ready

**Comment by dharmit** [comment]
Auto-completion fails in a similar fashion for numerous other combinations. I tried hitting tab after typing following commands on the CLI:

- `odo app {delete, describe}`
- `odo component {create, delete, describe, link, log, push, unlink, update, watch}`
- `odo {create, delete, describe, link, log, push, unlink, update, watch}`
- `odo service {create, delete}`
- `odo storage delete`
- `odo url delete`

Could these all be result of same/similar bug?

**Comment by dharmit** [comment]
IIUC, above commands which are failing to auto-complete as expected, do require a valid component/context to operate under normal cirumstances. If we were to execute these commands outside a directory containing a component, they are bound to fail with same erro message, no? Then why do we expect their auto-complete to work without any issues outside a directory containing a valid component? Isn't the error indicating the user that (s)he's working from a directory that contains no component?

If that's not the way it should be then what should we print instead to tell the user to `cd` into a directory with a compnent?

Trying to understand what I'm missing here.

cc @kadel @girishramnani @surajnarwade

**Comment by kadel** [comment]
@dharmit there is no reason why `odo push --con <tab>` should fail. It is supposed to complete the `--context` flag name, there is no information that is required from the cluster in this case.

But there are some commands that fetch information from the cluster like `odo component delete <tab>` or `odo component create <tab>`, first one is supposed to suggest the component name, and the second one the component type.  In this case, odo shouldn't show any errors. If it can't fetch the information it should simply not show anything (fail silently).

**Comment by dharmit** [comment]
Hi @mik-dass @surajnarwade @kadel 

I'm hitting a wall here. Can you please help me answer a few questions and point me in the right direction?

I read the "Completion Architecture" doc (https://github.com/openshift/odo/blob/master/docs/completion-architecture.adoc) and tried to make sense from it.

I commented the line https://github.com/openshift/odo/blob/34e362dc9d7b5f1a4e713e69548d0126f7f73f99/pkg/odo/cli/component/push.go#L128 and built the binary and found that auto-completion works for `odo push --context` but when I press `<Tab>` after that, it complains that same thing.
```bash
$ odo push --con <Tab>
--config   --context

$ odo push --context <Tab>
✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

Then I uncommented the line mentioned above https://github.com/openshift/odo/blob/34e362dc9d7b5f1a4e713e69548d0126f7f73f99/pkg/odo/cli/component/push.go#L128 commented the line after that https://github.com/openshift/odo/blob/34e362dc9d7b5f1a4e713e69548d0126f7f73f99/pkg/odo/cli/component/push.go#L129 and built the binary again.

This time the behaviour changes:
```bash
$ odo push --cont <Tab>
 -- no matches found --

$ odo push --context <Tab>
 -- file --
go-build167356221/
minishift.INFO@
...
...
```
Now, I don't think I understand things completely but what doesn't make sense to me is that:
- shouldn't commenting 
  ```
  completion.RegisterCommandHandler(pushCmd, completion.ComponentNameCompletionHandler)
  ``` 
  have prevented `odo push --con <tab>` from working fine? It worked OK but the file completion didn't work.
- shouldn't commenting
   ```
   completion.RegisterCommandFlagHandler(pushCmd, "context", completion.FileCompletionHandler)
   ```
   have prevented file completion from working? But, in fact, it failed to show options when I did `odo push <tab>` and showed me list of files instead just like it did after `odo push --context <tab>`.

Questions:
- Am I looking at this correctly or am I missing the point?
- What do you recommend I do next to make progress on this issue to be able to fix it? For example, I tried to play with auto-completion for `odo create` and it worked just fine as we expect it to work for `odo push --con <tab>`. If you look at https://github.com/openshift/odo/issues/1718#issuecomment-508722252, I think, there's a scope to fix the issue reported here for other auto-completions as well.

**Comment by dharmit** [comment]
I'm hitting a wall again after making some progress on skipping the OpenShift cluster connection check as per https://github.com/dharmit/odo/commit/e362486b64ef4761c3460a2609d275280cf12ee7

Now `odo` complains following:
```bash
$ odo push --con... ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

This error is thrown by the code at: https://github.com/openshift/odo/blob/bbee9156eb5ebddea3814cdce97cdb3d1a2bffdb/pkg/odo/genericclioptions/context.go#L170-L173

Which actually makes sense in this case because we're working from a non-component directory, i.e., there's no `.odo/config.yaml`. So the moment we try `odo push <tab>` aforementioned error starts throwing up.

The reason auto-completion requires a valid context (and I could be wrong here) seems to be because of: https://github.com/openshift/odo/blob/bbee9156eb5ebddea3814cdce97cdb3d1a2bffdb/pkg/odo/util/completion/completionhandlers.go#L390


I can't imagine what condition I am supposed to check/add here that would prevent this message from showing up and make auto-completion fail silently.

Can someone lend a hand please? @kadel @girishramnani @surajnarwade @mik-dass

**Comment by mik-dass** [comment]
> Which actually makes sense in this case because we're working from a non-component directory, i.e., there's no .odo/config.yaml. So the moment we try odo push <tab> aforementioned error starts throwing up.

The problem here is the completion architecture. Analyzing the issue logs, I can see that the auto complete was trying to find a component name instead of auto completing the flag `context`. 

Also if we really want to remove the error message completely, we need to stop any print message deep in the architecture (it messes up auto completion).

**Comment by cdrage** [comment]
Found where it was introduced after much trial-and-error: 

https://github.com/openshift/odo/commit/b800ebc370ee0ed893b3522d323327d36c188847

Going to go from there into fixing it.. Looks like the code within completionhandlers is totally fine, it's related to context.
