### ISSUE TITLE
removal of odo project create, get and set, and add odo project describe

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1720]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
The idea behind this issue is to have consistency among commands and also to make sure that inconsistencies like these https://github.com/openshift/odo/issues/1715#issuecomment-491713801 dont occur.
The proposal here is to remove the `odo project create`, `odo project set` and `odo project get`.
As well as add `odo project describe`.

All the future project operations should occur using `odo config`.

There are different workflows which users follow, some of them are described bellow with the above mentioned changes incorporated - 

- user wants to use an existing project -
`odo create --project <project_name>` 

- user wants to change the project while developing - 
`odo config set Project <project_name>`  <- benefit here is that the user gets a nice message to do `odo push --config` to push this change

- user wants to delete a project
`odo project delete`

- user wants to see the current project
`odo config view`

**Comment by girishramnani** [comment]
@dgolovin are you using any of the commands we are planning to remove in this issue?

**Comment by dgolovin** [comment]
@girishramnani We are using all of it except last one. See all command we use [here](https://github.com/redhat-developer/vscode-openshift-tools/blob/de457dd41039229765db2d612268619199e684c5/src/odo.ts#L57).

**Comment by girishramnani** [comment]
@dgolovin so I can see that you are using `odo project create` and `odo project set` but once the plugin uses new odo workflow then I think these commands won’t be needed by the plugin, is my assumption correct?
cc @kadel

**Comment by dgolovin** [comment]
@girishramnani how would we create project when 'odo project create' is removed? I have no concerns about removing 'project set', than was used as workaround for possible issues.

**Comment by kadel** [comment]
> @girishramnani how would we create project when 'odo project create' is removed? I have no concerns about removing 'project set', than was used as workaround for possible issues.

@dgolovin 
It would work similarly to applications. The project will be created with the component. 


@girishramnani 
We need to think about all the consequences and of this.
What if the user needs to first create service and then component?
I think that currently `odo service create` requires an existing project.

cc @jorgemoralespou

**Comment by jorgemoralespou** [comment]
I'm curious to why a project needs to be part of the component configuration. IMHO a project is tangential to the applications and components the same way as a cluster is. What if in clusterA a user has projectA but in clusterB the user has projectB? Both of this concepts are (and should not be) bound to the component's configruation.

We need to have:
- project create
- project delete
- project set (or use or select or any other term that works)
- project get (or list or ...)

I know that a service or a component will need a project, but when you log into a cluster you will always have/be in the context of a project. 

Whether you make the actions in the correct project should be out of the scope of `odo`, and the only actions that should potentially create a "project" should be `odo component create` and `odo service create`, although the second could be "declarative" or "imperative". For the former, it would require to create the service in the context of a "component" and fail if there is no component in the current context. For the latter, it should create the component independently of whether a component exists, or not, to allow for service pre-creation.

For this matter, I would consider that `odo service create` would be declarative, and `odo service create --force` (or --now or similar) should be the imperative form.

**Comment by kadel** [comment]
> I'm curious to why a project needs to be part of the component configuration. IMHO a project is tangential to the applications and components the same way as a cluster is. What if in clusterA a user has projectA but in clusterB the user has projectB? Both of this concepts are (and should not be) bound to the component's configruation.

If we don't store the project in a component configuration than how is it going to work if user switches between two component each of them in a different project?
Example:
I have component1 that I want to be in a project1
I have component2 that I want to be in project2

Currently, it works like this.
```
cd component1
odo component create --project project
odo push

cd component2
odo component create --project2
odo push

#I want to work on a component2 
cd component2
odo push
# no need to worry about project
``` 

If we don't store project information in a local configuration.

```
odo project set project1
cd component1
odo component create 
odo push

odo project set project2
cd component2
odo component create
odo push

#I want to work on a component2 
cd component2
odo project set project2
odo push
# I have to remember where to which project my component belongs to
``` 



> 
> We need to have:
> 
> * project create
> * project delete
> * project set (or use or select or any other term that works)
> * project get (or list or ...)
> 
> I know that a service or a component will need a project, but when you log into a cluster you will always have/be in the context of a project.
> 
> Whether you make the actions in the correct project should be out of the scope of `odo`, and the only actions that should potentially create a "project" should be `odo component create` and `odo service create`, although the second could be "declarative" or "imperative". For the former, it would require to create the service in the context of a "component" and fail if there is no component in the current context. For the latter, it should create the component independently of whether a component exists, or not, to allow for service pre-creation.

I'm lost :-( Are you saying that `odo service create` shouldn't be possible without already existing component?

> 
> For this matter, I would consider that `odo service create` would be declarative, and `odo service create --force` (or --now or similar) should be the imperative form.

**Comment by jorgemoralespou** [comment]
@kadel, I see the problem. I think at some point we discussed having an additional configuration file (something like config.local) where this information should be stored, but that the file should be prevented to be stored in git, and hence shared.
I'm guessing that we lost this local configuration at some point in time. In the odo-workflow original document I see some config values marked as `EPHEMERAL` for this reason. I think this is needed mostly to support what you describe and also to guarantee that not "environment specific" configruation is saved in odo-config file in git.

> I'm lost :-( Are you saying that odo service create shouldn't be possible without already existing component?

I'm saying that we can define how it works. If we want to be able to create a service without a project, we can:
- always be imperative, and have `odo service create` act directly on the cluster without adding anything to any context or component's config. This could pose some problems for application composition as a link in a component would not trigger the creation of the "required" service.
- always be declarative, and if a service is created need to be in the context of a component, and hence, information about the service will be saved in the component's config. But to allow to create a service when there's no component, we should add a flag (--force or similar) that would override this behavior and force the service creation to be imperative.

I hope this explain better my previous comment.

**Comment by amitkrout** [comment]
#2236
