### ISSUE TITLE
odo watch Still Runs Despite Stopping odo watch

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1725]
[kind/bug]

`odo watch` still runs despite running a `ctrl-c` to stop the watch. My original thought was this was a supported behavior, so I opened issues around [how to stop an odo watch](https://github.com/openshift/odo/issues/1722) and another on [odo watch hanging](https://github.com/openshift/odo/issues/1723). However, after discussing the issue in #1723, it was discovered that this is potentially a bug with `odo watch`.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0-beta1`

## How did you run odo exactly?
This was all done using an OpenShift cluster on `Minishift`.

  `odo create nodejs frontend`
  `odo push`
  `odo link backend --component frontend`
  `odo link backend --component frontend --port 8080`
  `odo url create frontend --port 8080`
  `odo push`
  `odo watch &`
  `ctrl+c`
  Edited a file associated with the nodejs application.

## Actual behavior
The change I made to the nodejs app was pushed to `Minishift`.

## Expected behavior
The `odo watch` should be killed and the changes made locally should not be pushed up.

## Any logs, error output, etc?
No errors. Just successful deployment output:

```
Pushing files...
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
```

**Comment by jorgemoralespou** [comment]
@danielhelfand If you run `odo watch &` the process is taken into the background. To be able to exit that watch, you need to first put it in the foreground before with `fg`.

`odo watch` is a blocking command, so when run without the ampersand, control+c should stop the command. If that feature is not working then, it's a bug, but as long as you're running the watch in the background, `control+c` should have no effect.

Is this what you're seeing?

**Comment by danielhelfand** [comment]
Yeah, my apologies. I think the `&` through me off. I think this is not actually a bug. It might be helpful for us to include a note on this in the katacoda and developing with odo tutorials to avoid confusion on this.
