### ISSUE TITLE
Measuring odo speed

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1726]
We need some kind of test that will help us measure speed.
By speed I mean time how long it takes to see changes made in the source code in the running application.

Something like this
```
odo component create
odo url create
odo push
# edit file
# start timer
odo push
# verify changes 
# stop timer
```

This will help us track progress and see track any regressions

**Comment by jorgemoralespou** [comment]
I think that it should also be worth to meassure the actions that happen inside the container when you push, as on initial push some things happen, on subsequent pushes additional things (backups/restores) happen, and etc....

It would be worth to convert what happens in the container to a more proper "script/binary" where these things can be measured if started with an e.g. ODO_DEBUG flag enabled.

**Comment by kadel** [comment]
> I think that it should also be worth to meassure the actions that happen inside the container when you push, as on initial push some things happen, on subsequent pushes additional things (backups/restores) happen, and etc....
> 
> It would be worth to convert what happens in the container to a more proper "script/binary" where these things can be measured if started with an e.g. ODO_DEBUG flag enabled.

👍

**Comment by jorgemoralespou** [comment]
@cdrage I think @kadel mentioned that this PR didn't close this issue. Was it closed by accident?

**Comment by kadel** [comment]
> @cdrage I think @kadel mentioned that this PR didn't close this issue. Was it closed by accident?

This shouldn't be closed.

**Comment by kadel** [comment]
I will start with measuring the time between:
 -  first push and running application
 - push after the file was modified and seeing the change in the application

The values should be recorded somewhere so we can track it in time.

**Comment by girishramnani** [comment]
next step would be to add a stage to run the benchmark tests on CI

**Comment by kadel** [comment]
> next step would be to add a stage to run the benchmark tests on CI

https://github.com/openshift/release/pull/4396

**Comment by kadel** [comment]
openshift/release#4396

 was merged
/close
