### ISSUE TITLE
`odo application list` does not list applications that contains only services

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1730]
[kind/bug]
## What versions of software are you using?
- Operating System:
Windows 10 Pro
- Output of `odo version`:
```
odo v1.0.0-beta1 (0237ea2a)

Server: https://10.0.0.46:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
```
C:\Users\dgolo>odo application list
There are no applications deployed in the project 'myproject1'.

C:\Users\dgolo>odo service create mysql-persistent --app app2
 V  Creating service
 V  Service 'mysql-persistent' was created
Progress of the provisioning will not be reported and might take a long time.
You can see the current status by executing 'odo service list'

C:\Users\dgolo>odo application list --project myproject1
There are no applications deployed in the project 'myproject1'.
```

## Actual behavior
odo application list command does not print any applications

## Expected behavior
odo application list command prints app2

## Any logs, error output, etc?
N/A

**Comment by kadel** [comment]
/kind bug
/priority medium
/milestone 1.0

`odo app list` currently looks for app labels in  DeploymentConfigs to find what applications are deployed, but it should also look for ServiceInstances
