### ISSUE TITLE
Uninstall Script

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1733]
[kind/Feature]

As far as I can tell, there is no uninstall script available for `odo` at this time. It would be helpful to have an OS-independent script similar to the install script. 

## Which functionality do you think we should add?
Uninstall `odo` in an OS-independent manner.

## Why is this needed?
Give users the ability to uninstall `odo`. My use case is that I would like to remove an old version from an environment I am working in.

**Comment by dharmit** [comment]
For the use case of removing an old version, should we rather have something like `odo update` on the lines of `minishift update` which replaces the old binary with the latest binary?

**Comment by kadel** [comment]
@dharmit 

> For the use case of removing an old version, should we rather have something like `odo update` on the lines of `minishift update` which replaces the old binary with the latest binary?


I would prefer to guide users to update using the package managers.


We have OS independent install method via [install.sh](https://github.com/openshift/odo/blob/master/scripts/install.sh) that is smart enough to use package managers. We can add `uninstall` argument to that script that handles the removing odo from the system.

**Comment by danielhelfand** [comment]
So I went ahead and put together a completely separate `uninstall.sh` script below. I have tested on all the supported distributions and the default case. Is the idea here to update `install.sh` to have both installation and uninstallation capabilities and maybe update the name to `installer.sh`, or should there be two separate scripts? I could see pros and cons with both approaches. 

```bash
#!/bin/bash
set -e

INSTALLATION_PATH="/usr/local/bin/"
PRIVILEGED_EXECUTION="sh -c"

SUPPORTED_PLATFORMS="
darwin-amd64
linux-amd64
linux-arm
"

echo_stderr ()
{
    echo "$@" >&2
}

command_exists() {

  distribution=$(get_distribution)

  case "$distribution" in

    ubuntu|debian)
        # Use which to verify uninstall on ubuntu and debian distributions
        which "$@" > /dev/null 2>&1
        ;;
    *)
        command -v "$@" > /dev/null 2>&1
        ;;
  esac
}

check_platform() {
    kernel="$(uname -s)"
    if [ "$(uname -m)" = "x86_64" ]; then
        arch="amd64"
    fi

    platform_type=$(echo "${kernel}-${arch}" | tr '[:upper:]' '[:lower:]')

    if ! echo "# $SUPPORTED_PLATFORMS" | grep "$platform_type" > /dev/null; then
        echo_stderr "
# The uninstall script has detected your platform to be $platform_type, which is
# currently not supported by this uninstall script."
        exit 1
    fi
    echo "$platform_type"
}

get_distribution() {
	lsb_dist=""
	if [ -r /etc/os-release ]; then
		lsb_dist="$(. /etc/os-release && echo "$ID")"
	fi
	echo "$lsb_dist"
}

set_privileged_execution() {
	if [ "$(id -u)" != "0" ]; then
        if command_exists sudo; then
            echo "# Uninstall will run privileged commands with sudo"
            PRIVILEGED_EXECUTION='sudo -E sh -c'
        elif command_exists su ; then
            echo "# Uninstall will run privileged commands with \"su -c\""
            PRIVILEGED_EXECUTION='su -c'
        else
    	    echo_stderr "#
Uninstall needs to run as root. The current user is not root, and we could not find "sudo" or "su" installed on the system. Please run again with root privileges, or install "sudo" or "su" packages.
"
        fi
    else
        echo "# Uninstall is being run as root"
	fi
}

uninstall_odo() {
    echo "# Starting odo uninstall..."
    echo "# Detecting distribution..."

    platform="$(check_platform)"
    echo "# Detected platform: $platform"

    # check if odo command already does not exist, meaning it's not installed
    if ! command_exists odo; then
        echo_stderr "# odo is not installed. Ending execution of uninstall script."
        exit 1
    fi

    # macOS uninstall steps using brew package manager
    if [ "$platform" = "darwin-amd64" ]; then
        if ! command_exists brew; then
            echo_stderr "# brew command does not exist. Please install brew and run the uninstall again."
        fi

        echo "# Uninstalling odo on macOS"
        brew uninstall odo

        return 0
    fi

    set_privileged_execution

    #uninstall steps for linux distributions and default case of non linux
    distribution=$(get_distribution)
  	echo "# Uninstalling odo on $distribution"

    case "$distribution" in

    ubuntu|debian)

        $PRIVILEGED_EXECUTION "apt-get remove -y odo"
        ;;

    centos|fedora)
        package_manager=""
        case "$distribution" in
        fedora)
            package_manager="dnf"
            ;;
        centos)
            package_manager="yum"
            ;;
        esac

        $PRIVILEGED_EXECUTION "$package_manager remove -y odo"
        ;;
    *)
        echo "# Proceeding with removing binary..."
        rm -r $INSTALLATION_PATH/odo
        ;;
    esac
}

verify_uninstall() {
    if ! command_exists odo; then
        echo "
# Verification complete!
# odo has been uninstalled"
    else
        echo_stderr "
# Something went wrong with odo uninstall. Please run the uninstall script again. If the issue persists, please create an issue at https://github.com/openshift/odo/issues."
        exit 1
    fi
}

uninstall_odo
verify_uninstall
```

**Comment by surajnarwade** [comment]
@danielhelfand , can you please send PR for the same ? (since you already worked on script)

**Comment by kadel** [comment]
> Is the idea here to update `install.sh` to have both installation and uninstallation capabilities and maybe update the name to `installer.sh`, or should there be two separate scripts? I could see pros and cons with both approaches.

Simple question, but thought to answer :-D 
Slightly leaning towards one `installer.sh` script that will by default (without any arguments)  perform the installation. To uninstall one would have to run `installer.sh --uninstall`.
Install and uninstall process has some common logic and this will make it easy to share the code.

**Comment by danielhelfand** [comment]
@surajnarwade @kadel Sure thing, I'll submit a pr after I re-work the `install.sh` script and add the logic I have in the script above. Thanks!

**Comment by cdrage** [comment]
So... We have no documentation in https://github.com/openshift/odo/blob/master/docs/installation.adoc with regards to uninstall.

Ping @boczkowska

/label need-docs

**Comment by danielhelfand** [comment]
Something to note here: The script won't work quite like `curl -L https://github.com/openshift/odo/raw/master/scripts/installer.sh -- uninstall | bash`

The correct way to call it would be as follows:
`curl -L https://github.com/openshift/odo/raw/master/scripts/installer.sh | bash -s -- --uninstall`

The weird syntax is related to how curl interpreting `--uninstall` as an unknown curl flag when used like in the example above. If someone has the script locally, he or she can run `installer.sh` and pass the `--uninstall` flag like so `sh installer.sh --uninstall`
