### ISSUE TITLE
"odo config view" doesn't work when OpenShift cluster is not reachable

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1745]
[kind/bug]

## What versions of software are you using?
- Operating System: CentOS 7.6, Fedora 30
- Output of `odo version`:
```
$ odo version
odo v1.0.0-beta1 (3ff77cb)
```

## How did you run odo exactly?
```bash
$ odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              python
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             
Name              python-ccqz
MinMemory         
MaxMemory         
Ignore            
MinCPU            
MaxCPU            

$ minishift stop
Stopping the OpenShift cluster...
Cluster stopped.

$ odo config view
 ✗  Unable to connect to OpenShift cluster, is it down?
```

## Actual behavior
`odo config view` fails when OpenShift cluster is not reachable.

## Expected behavior
Shouldn't viewing the config be possible in spite of cluster being down since the config values are already present in `.odo/config.yaml`?

**Comment by kadel** [comment]
> Shouldn't viewing the config be possible in spite of cluster being down since the config values are already present in `.odo/config.yaml`?

yes it should. As part of this PR we should also check for the commands where it doesn't make sense to require cluster connection

**Comment by amitkrout** [comment]
> > Shouldn't viewing the config be possible in spite of cluster being down since the config values are already present in `.odo/config.yaml`?
> 
> yes it should. As part of this PR we should also check for the commands where it doesn't make sense to require cluster connection

Right, i think flag ```--skip-connection-check``` should work as a workaround for now.

for example ```odo config view --skip-connection-check```

**Comment by cdrage** [comment]
I don't believe we actually have many docs with regards to interactive mode. Perhaps we could have a quick look?

Ping @boczkowska

/label need-docs
