### ISSUE TITLE
UC 30: As a developer, I want to connect to my application

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#175]
TBD

**Comment by cdrage** [comment]
We've implemented URL. Do you mean using `oc exec` or just accessing your application in general @jorgemoralespou ?

**Comment by jorgemoralespou** [comment]
I mean something similar to `oc rsh` so I can get into the pod, and potentially `oc port-forward` so that I can connect to my pod from local without a URL. 

This task needs R&D.
