### ISSUE TITLE
Clarify message about running odo push for components in the odo component list command

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1750]
- update `odo list` so it shows the message only if there is a difference between cluster and local config. If local config has url that is not deployed, and also if the cluster has url that has been removed from the local config.

/priority medium

more in  https://github.com/openshift/odo/issues/1650#issuecomment-486986788_

**Comment by mik-dass** [comment]
> If local config has url that is not deployed, and also if the cluster has url that has been removed from the local config.

@kadel So `odo list` should show the list of URLs on and not on the cluster?

**Comment by mik-dass** [comment]
> If local config has url that is not deployed, and also if the cluster has url that has been removed from the local config.

I guess this command should be possible to be triggered from a non odo directory. If yes, then the problem will be detecting the source paths as we don't store the complete absolute path of the component. I guess this functionality may be added to the odo list command with the `path` flag enabled. That way we can detect the odo component directories and perform operations accordingly. @kadel WDYT?

**Comment by dharmit** [comment]
If I understand the issue correctly, this seems to be fixed. `odo list` doesn't say anything about the URLs. And `odo url list` doesn't talk about local changes if `odo push` was executed. 

Should we close this @kadel @mik-dass ?

**Comment by mik-dass** [comment]
I think we can close this. WDUT?

**Comment by dharmit** [comment]
I'm gonna go ahead and close this as it's not looking relevant anymore. We can re-open it if required.

/close
