### ISSUE TITLE
Create test file for odo catalog command

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1752]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Integration test of odo catalog command 

## Why is this needed? 
No proper integration test file for odo catalog command is added yet

**Comment by girishramnani** [comment]
It seems now we have integration tests for catalog command here https://github.com/openshift/odo/blob/b14cd3a0e1f09b274cb43153a518107f130eff2f/tests/integration/servicecatalog/cmd_service_test.go#L58

**Comment by girishramnani** [comment]
closing this issue
