### ISSUE TITLE
odo component create interactive mode: default value and prompt are confusing for source location

### ISSUE THREAD

**Issue by jankleinert** [openshift/odo#1756]
[kind/bug]

This tripped up quite a few people at the Summit lab, as they were blindly accepting the defaults in interactive mode, despite the instructions saying to enter '/' for the source location in interactive mode to try to avoid this issue.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: v1.0.0-beta2 (also present in beta1)

## How did you run odo exactly?
```
git clone https://github.com/openshift-labs/beercan-shooter-game.git bc2
cd bc2
odo component create
```

choose nodejs for component type, 10 for version, and then look at the next step where it asks for location.

## Actual behavior
Location of context component, relative to '/opt/app-root/src/bc2' (/opt/app-root/src/bc2)

If you accept this default, it appends the current path to the current path, resulting in:

```
/opt/app-root-src-bc2/opt/app-root/src/bc2
```

However, that is not clear from odo config view:

```
odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs:10
Application       app
Project           developing-with-odo-odobeta2-6bh0t
SourceType        local
Ref
SourceLocation    /opt/app-root/src/bc2
Ports
Name              nodejs-yyzt
MinMemory
MaxMemory
Ignore
MinCPU
MaxCPU
```

But when you run odo push, you'll see that it's looking in /opt/app-root/src/bc2/opt/app-root/src/bc2:

```
 master  ?  $  odo push
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating nodejs:10 component with name nodejs-yyzt
 ✓  Initializing 'nodejs-yyzt' component
 ✓  Creating component nodejs-yyzt
 ✓  Successfully created component nodejs-yyzt
 ✓  Applying component settings to component: nodejs-yyzt
 ✓  Successfully updated component with name: nodejs-yyzt
 ✓  Pushing changes to component: nodejs-yyzt of type local
 ✗  open /opt/app-root/src/bc2/opt/app-root/src/bc2: no such file or directory
```

To get it to actually work, I have to enter '/' as the source location. Note that entering '.' does not work, which was my first inclination.

## Expected behavior
If the value entered for source location is in fact supposed to be relative to the current directory, then change the default value, so that if the user accepts the default, the source location is the current directory.

For example:
Location of context component, relative to '/opt/app-root/src/bc2' (/) 

or 

Location of context component, relative to '/opt/app-root/src/bc2' (.)

**Comment by mik-dass** [comment]
@jankleinert https://github.com/openshift/odo/pull/1764 is in. Can you please confirm that the issue is resolved? Thanks.

**Comment by kadel** [comment]
> @jankleinert #1764 is in. Can you please confirm that the issue is resolved? Thanks.

@mik-dass if you verified that PR fixed this issue then you can close it. No need to wait for confirmation. If Jen or someone else finds that it was not fixed correctly we can always reopen the issue.

**Comment by girishramnani** [comment]
this issue was resolved and locally verified
