### ISSUE TITLE
openshiftdo.org website not in sync with docs on the repo

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1760]
[kind/Documentation]

## What did you find missing in the documentation?
For example:
- Installation steps at https://openshiftdo.org/installation/ don't match that from the master branch.
- GitHub link at the bottom of the page points to https://github.com/redhat-developer/odo instead of https://github.com/openshift/odo. Other links at the bottom are also incorrect.

## What is the relevance of it?
The synchronization is important to avoid confusing the users.

**Comment by dharmit** [comment]
@cdrage I just saw https://github.com/openshift/odo/deployments. It says you deployed it last. Can you PTAL?

**Comment by cdrage** [comment]
Hey @dharmit I already have an issue open for this: https://github.com/openshift/odo/issues/1679

Yeah, it's not automatically syncing. I'll do a manual sync right now however.
