### ISSUE TITLE
cannot create component in home directory

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1766]
As there is a preference file present in the home directory with the name path as the local config file `.odo/config.yaml`, people cannot create components in their home directory ( which could be something someone does )

**Comment by girishramnani** [comment]
we can consider changing the name of the preference file to `.odo/preference.yaml` instead to make sure people can create components in home directories

**Comment by cdrage** [comment]
:+1: on this, this would be related to the previous issue I had: https://github.com/openshift/odo/issues/1729

:+1: on renaming it to `preference.yaml`

**Comment by amitkrout** [comment]
@girishramnani Can you please assign label to it

**Comment by girishramnani** [comment]
@jorgemoralespou could you please provide you suggestion on these two questions -
1 - renaming the global preference to `preference.yaml` or `preferences.yaml`
2 - do we provide automatic migration for users i.e. rename the `~/.odo/config.yaml` to the new file?

**Comment by jorgemoralespou** [comment]
@girishramnani I would go ahead, although bc I honestly hope no one does that, but makes sense.
For question #2 I would just add it to the release notes as I also don't think many people is yet using the preferences.
