### ISSUE TITLE
Use of make test-e2e in test suite

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1769]
[kind/Documentation]

## What did you find missing in the documentation?
Are we really care about the running of ```make test-e2e``` [1], i mean running the whole test suite through ```make test-e2e``` or may be ```make integration```  ?

[1] https://github.com/openshift/odo/blob/master/Makefile#L156

I am in the favor of removing [1] because it is available from the start of odo i guess but not in use.

## What is the relevance of it?
Test cleanup

**Comment by cdrage** [comment]
Yes. We need it. I use it constantly and it beats waiting for the CI to finish.

Plus you need it to test locally against your own cluster.

I'm good for renaming it though, but we 100% need to keep this.

**Comment by kadel** [comment]
👍 for keeping this.
Running all test with a single command is really useful, especially once we can run multiple tests in parallel.

**Comment by cdrage** [comment]
Sorry @amitkrout I think that we have a consensus. I'm going to close this for now, we 100% need to keep `make test-e2e`.
