### ISSUE TITLE
Create documentation around GLOBALODOCONFIG env variable

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1773]
[kind/Documentation]

## What did you find missing in the documentation?
No doc found around ```GLOBALODOCONFIG```

## What is the relevance of it?
Increase odo user experience

**Comment by surajnarwade** [comment]
cc @boczkowska

**Comment by mohammedzee1000** [comment]
@boczkowska do you have any updates or do you need any help
`GLOBALODOCONFIG ` allows you to change the location of where odo preferences are stored
