### ISSUE TITLE
Cleanup test naming - e2e vs integration

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1780]
There is still a lot of places (like Makefile, or names of Describe blocks) where integration tests are named as e2e or have e2e in the name.
This should be cleaned to make it clear that those are two different tests approaches.

/kind bug
/area testing
/priority medium
/project Sprint 168

**Comment by dharmit** [comment]
Issue description is really clear in this case! For example: https://github.com/openshift/odo/blob/009f9d7e775caef0dc63d2a361f2eeb423398a05/Makefile#L106-L109

has the name `test-cmp-e2e` but lives under `tests/integration` directory. There are many such tests with `e2e` in their name but living under `test/integration` dir.

**Comment by dharmit** [comment]
The bot's on a PTO, maybe? :thinking:

**Comment by kadel** [comment]
This should be also updated in  https://github.com/openshift/release

**Comment by amitkrout** [comment]
> This should be also updated in https://github.com/openshift/release

Right, I will fix all those reference of e2e related to test.

**Comment by amitkrout** [comment]
Pr sent https://github.com/openshift/release/pull/4268 for OpenShift CI job and config changes

**Comment by kadel** [comment]
Is there a PR for this on odo side?

**Comment by girishramnani** [comment]
PR for this issue https://github.com/openshift/odo/pull/1878

**Comment by kadel** [comment]
/close
#1878
