### ISSUE TITLE
Improved guidance/feedback when the user encounters errors

### ISSUE THREAD

**Issue by triceam** [openshift/odo#1781]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Improved guidance/feedback when the user encounters errors.

## Why is this needed? 
When the user encounters an error, it is not always apparent what caused the error, or how to resolve the error.  

For example, this is what I see when I see when I follow the quickstart instructions from https://github.com/openshift/odo on a brand new managed cluster:

![image](https://user-images.githubusercontent.com/974294/58677008-5a64d980-8328-11e9-8e55-71d44d9b92f5.png)

In order to resolve the issue the end user has to explore the OpenShift dashboard or `oc` cli and track down the root cause of the failure.  This seems to go against the mission statement: 

> `odo` abstracts away complex Kubernetes and OpenShift concepts, thus allowing developers to focus on what is most important to them: code.

A deeper understanding of Kubernetes/OpenShift is required to resolve the problem when the user strays from the golden path.

In a separate, but similar case I got this error, which again, is not easily understood for the end user:

![image](https://user-images.githubusercontent.com/974294/58677436-e7f4f900-8329-11e9-8f2b-6e8de9759ce6.png)

@kadel @sspeiche this is the issue that I mentioned on WebEx with IBM earlier today.

**Comment by kadel** [comment]
@triceam Good point. We definitely need to figure some better way to report errors.



> In order to resolve the issue the end user has to explore the OpenShift dashboard or `oc` cli and track down the root cause of the failure. This seems to go against the mission statement:
> 
> > `odo` abstracts away complex Kubernetes and OpenShift concepts, thus allowing developers to focus on what is most important to them: code.
> 
> A deeper understanding of Kubernetes/OpenShift is required to resolve the problem when the user strays from the golden path.

I'm afraid that there will always be some unexpected situation where `odo` don't know how to handle it. In that situation, `odo` should provide as much information as it can so someone with a deeper understanding of Kubernetes can resolve the issue.

**Comment by triceam** [comment]
@kadel, yeah, understood that there will always be some unexpected situations.

**Comment by girishramnani** [comment]
it seems we cannot do anything for unexpected situations. Hence closing this for now.
