### ISSUE TITLE
Don't rebuild if only changing URL / detect change in source code.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1788]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

We should implement a way to make changes to the component without rebuilding. 

For example, when we create a url and then run `odo push`, we shouldn't have to rebuild the component. 

## Why is this needed? 

Saves development time as well as not requiring the component to be rebuilt again.

**Comment by kadel** [comment]
> For example, when we create a url and then run `odo push`, we shouldn't have to rebuild the component.

How are we going to detect if the rebuild is needed or not?

**Comment by jorgemoralespou** [comment]
There should be a checksum on local files to see if there has been a change, like Git does.

**Comment by kadel** [comment]
I don't know how exactly git does it. 

The first simple solution that I can think of would be:

1) compute the checksum for each file in the component directory (skip ignored files)
2) store checksums somewhere in the cluster when the component is pushed
3) do 1) before each push, and compare it with the checksums store on the cluster.

Don't know how fast hash functions like SHA-1 are but I'm afraid that this is going to be slow :-(


We could also just simply check the time of the newest file, and store that instead of all checksums. 
But need to investigate how to save this is going to be.

**Comment by kadel** [comment]
Did quick benchmark with sha-1
It took about 2s to compute the checksum for every file in odo codebase (27327 files).

**Comment by jorgemoralespou** [comment]
Yeah, I would think that how git does things is a good way, and AFAIK they don't compute the whole SHA or whatever. Also, maybe they do that behind the scenes, when a file timestamp is changed only.
In any case, I would not store that on the cluster but only locally.

Maybe there's libraries that help, like:
- https://github.com/spf13/afero
Or use git's techniques:
- https://stackoverflow.com/a/4092156
- http://www-cs-students.stanford.edu/~blynn/gitmagic/ch08.html

**Comment by kadel** [comment]
OK, let's look into this deeper. This is probably something that we would want for 1.0

/milestone 1.0

/kind Enhancement
/priority medium


There already is a similar issue https://github.com/openshift/odo/issues/1488. I'll close #1488 in favor of this one.

**Comment by mik-dass** [comment]
I was looking into git indexing. Here's what I found
https://github.com/git/git/blob/master/Documentation/technical/index-format.txt
https://stackoverflow.com/questions/4084921/what-does-the-git-index-contain-exactly

**Comment by jorgemoralespou** [comment]
Another tools/libraries to consider for this task:
- https://github.com/syncthing/syncthing
- https://github.com/src-d/go-git

**Comment by mik-dass** [comment]
One of the possible ways we can start is to 
- keep the modified date of all the files in a local file (like git index)
- during every push, match the modified date of a file to the one stored in the local file
- If the don't match, trigger the build. 
- We also update the modified dates in the local file after every push.

We can later improve on the solution and add additional data like computed hashes for every file etc.

@kadel @jorgemoralespou @girishramnani WDYT?

**Comment by jorgemoralespou** [comment]
Is it easier to parse compare dates or hashes? Is it possible to get the modified date as floating number rather than as string to be able to compare easier?

What I don't get is the last part of "we also update the modified dates in the local file after every push". You mean reindex the mdate if files have been pushed, else, not modify the index?

We need to think if by introducing incremental changes for the solution we can cause breaking compatibility. We will probably need to "fix/reindex" the index for a repository with every version, so a version key, might be needed in the index as well. This adds some more complexity, but can provide room for a incremental solution.

**Comment by mik-dass** [comment]
> What I don't get is the last part of "we also update the modified dates in the local file after every push". You mean reindex the mdate if files have been pushed, else, not modify the index?

I mean if the user updates the content of a file, the modified date of the file will also change. So we record the modified date in the index file against the filepath.

**Comment by kadel** [comment]
### This is a solution of time-based that Anmol proposed a while back:

First push:
1) Walk through the source code and find a file with the latest modification time
2) Store the latest modification time in a component annotation (or somewhere local on the client side) (it is just one value)
3) upload the source code

Next push:
1) Walk through the source code and find a file with the latest modification time
2) Retrieve the  latest modification time from the annotation (or somewhere local on the client side)
3) Compare two times. If the one retrieved from the 1) step is newer than there was a change in source code and we need to push the source code. Store new modification time.

It is nice and simple. But has one huge downside.
It will require to push the whole component source each time there is a change.
Also, it relies on the modification time. I'm not sure how reliable this is on different systems.


### Hash (CRC) based approach
First push:
1) Walk through the source code and compute the checksum for each file.
2) Store list of all files with their checksums in `.odo/files.yaml` (we should probably use a format that is going to be faster to parse than YAML, as there might be a lot of records in it)
3) upload the source code

Next push:
1) Walk through the source code and compute the checksum for each file.
2) Compare checksums with what is stored in `.odo/files.yaml`. Upload each file that has a different checksum. Update `.odo/files.yaml`

I would actually prefer to store the list of checksums somewhere on the cluster side (maybe even somewhere inside the container?). It is state information and I would like to keep all state on inside the cluster with the component.

With this approach, we can upload just files that were changed. It is a little bit more complicated and in some cases slower. But not always, for a huge codebase, and for a slower network it might be actually faster as we don't transfer everything over again.
Another benefit will be that we can keep track of files that were locally deleted.

**Comment by jorgemoralespou** [comment]
I think again that this is why the supervisor should be intelligent and not just a supervisor, as this is the type of information the supervisor could compute / deal with, through it's API.

**Comment by cdrage** [comment]
I'm roping in issue: https://github.com/openshift/odo/issues/1354 in here as well..

I am looking at implementing the checksum approach as it would be needed to detect the differences in issue: https://github.com/openshift/odo/issues/1354 for what files have been deleted (or modified) and what files have not...

There is a trade in this..

Initially, the first `odo push` would take longer as it would compute the checksum for **every** file. 

However, upon each new `odo push`, we would only have to transfer files that have been modified (we either check to see if the checksum has changed, **or** if it's missing in whatever file we use to store sha256, etc.)

Any other thoughts @jorgemoralespou / @kadel ?

**Comment by jorgemoralespou** [comment]
Why not compute the checksums before doing a push, e.g. when doing an `odo component create`, or as a background task that is initiated on some commands, so that when doing the push, the first checksums are already there?

git does it when you do `git init` AFAIK.

**Comment by girishramnani** [comment]
Yeah checksum of the directory could work but we have to consider cases like ignoring the .git folder and similar such directories which affects the checksum even if the files dont change.
And I don't think we should store this checksum in config.yaml, maybe a state file which isn't meant to be checked in like `odo.state` in the .odo dir.

**Comment by girishramnani** [comment]
There is an issue https://github.com/openshift/odo/issues/1354 i.e. file deletion propagation for odo push which needs to be considered while we try to solve this problem

**Comment by girishramnani** [comment]
While the checksum will help to detect that deletion happened or not, it wont give us the files that were delete or changed. Hence we need to
- take this checksum as a circuit breaker to decide that `was there ever a change`
- if yes then have a solution to find the changed state of the directory ( which essentially solves https://github.com/openshift/odo/issues/1354 )

But it's also possible that generating the checksum can be as expensive as the method to check state change and in that case we would be paying that cost twice.

**Comment by kadel** [comment]
@jorgemoralespou 

> I think again that this is why the supervisor should be intelligent and not just a supervisor, as this is the type of information the supervisor could compute / deal with, through it's API.

If we implement tracking changes in supervisor it will require to do full push each time. Each time `odo push` is run we will have to upload all source code. And on top of that, there still will be an issue with deleting files. We will have to still somehow compare container and local directory.

### This is probably the first thing that we need to agree on.

**`odo push` uploading everything each time** vs **`odo push` uploading only modified files** 
 


> Why not compute the checksums before doing a push, e.g. when doing an `odo component create`, or as a background task that is initiated on some commands, so that when doing the push, the first checksums are already there?
> 
> git does it when you do `git init` AFAIK.

I don't think that this will speed up anything. If we want to track changes on the client side, we will have to validate/recompute all checksums right before `odo push`. 


---

@girishramnani 



> While the checksum will help to detect that deletion happened or not, it wont give us the files that were delete or changed. Hence we need to

Don't understand :-( 
If we have a list of all files with their checksums from the previous `odo push` run then we can easily tell which files were deleted, added or changed in the current run.  
Or am I missing something?


> But it's also possible that generating the checksum can be as expensive as the method to check state change and in that case we would be paying that cost twice.

Check my previous comment in this issue - https://github.com/openshift/odo/issues/1788#issuecomment-499504696

And  checksum functions (crc-32) instead of cryptographic hash (sha-1), will make this even faster.

**Comment by girishramnani** [comment]
> If we have a list of all files with their checksums from the previous `odo push` run then we can easily tell which files were deleted, added or changed in the current run.
> Or am I missing something?

We would be storing alot of metadata if we store the checksums of all the files

**Comment by girishramnani** [comment]
but if we think about this as a git repo which only stores the one previous commit then it might not be that much data.

**Comment by kadel** [comment]
> > If we have a list of all files with their checksums from the previous `odo push` run then we can easily tell which files were deleted, added or changed in the current run.
> > Or am I missing something?
> 
> We would be storing alot of metadata if we store the checksums of all the files

Is there another way how we can do achieve this?

> but if we think about this as a git repo which only stores the one previous commit then it might not be that much data.

What is the source code is not a git repo? 
Even if we say that source code has to be a git repo, then it is not going to help us. Users still want to see changes before they are committed. This is the whole point of the inner loop. There is no way to track changes that that are not staged or committed using git.

**Comment by mik-dass** [comment]
@girishramnani @kadel @jorgemoralespou How about we start by storing only the modified date of the files retrieved by golang implementation of the `stat` command? We also will keep in mind #1354 while building the solution. We can validate the process and then later add other details like check sums and others to the local storage file. WDYT?

**Comment by jorgemoralespou** [comment]
@kadel If you think about how Git works, I think this should/could be pretty similar, with some caveats/differences.

We can treat the component filesystem as a Git repository, and when a user does "odo push" we would stage all the files/changes to the .odo/.local-storage and push that to the container, acting as a remote. 
One benefit of using Git type filesystem/libraries is that we only push diffs, so even deletes are propagated. The amount of files transferred are minimal, as it won't need to push everything again on every push, just the initial one.

Not sure how easy/difficult this could be, but I think Git provides what we want, hence using a Git library to do some of these functions for us could be an option. For this, I think go-git(https://github.com/src-d/go-git) provides most of what we would need. We would need to have a server side component (meaning in the containers), and to this point point, is where I think a smart go supervisor is the way to go.

I know this is way too complex, but to me seems to be the best option longer term.

**Comment by girishramnani** [comment]
> but if we think about this as a git repo which only stores the one previous commit then it might not be that much data.

its about thinking from that perspective, a git repo with just a single commit has enough state to provide a difference so we can follow a similar approach, its just a git repo generates alot of metadata distributed among multiple files which we dont want.

**Comment by jorgemoralespou** [comment]
@girishramnani If that's transparently managed by a well tested library, why would it be a problem?

**Comment by girishramnani** [comment]
currently the team is leaning towards following approach that is being followed by `oc rsync` with use of https://github.com/Redundancy/go-sync instead of rsync binary but @surajnarwade and @mik-dass are researching the approach

**Comment by mik-dass** [comment]
rsync implementation in origin
https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/rsync.go#L154

Requirements of rsync : https://docs.openshift.com/container-platform/3.9/dev_guide/copy_files_to_container.html#copying-requirements

It states
```
If rsync is not found locally or in the remote container, then a tar archive will be created locally and sent to the container where tar will be used to extract the files. If tar is not available in the remote container, then the copy will fail.

The tar copy method does not provide the same functionality as rsync. For example, rsync creates the destination directory if it does not exist and will only send files that are different between the source and the destination.
```

**Comment by kadel** [comment]
> rsync implementation in origin
> https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/rsync.go#L154
> 
> Requirements of rsync : https://docs.openshift.com/container-platform/3.9/dev_guide/copy_files_to_container.html#copying-requirements
> 
> It states
> 
> ```
> If rsync is not found locally or in the remote container, then a tar archive will be created locally and sent to the container where tar will be used to extract the files. If tar is not available in the remote container, then the copy will fail.
> 
> The tar copy method does not provide the same functionality as rsync. For example, rsync creates the destination directory if it does not exist and will only send files that are different between the source and the destination.
> ```

Could we use Go rsync library like https://github.com/Redundancy/go-sync to avoid local rsync requirement?

How is `oc` managing communication between local and remote rsync? Any port forwarding involved?

**Comment by surajnarwade** [comment]
let's break problem into 2 parts:

1. propagate deleted files

(`oc rsync` has `--delete` flag which also works with tar strategy which we are also using)

2. copying only changed files

(as @mik-dass  mentioned)

**Comment by mik-dass** [comment]
> How is oc managing communication between local and remote rsync? Any port forwarding involved?

There are 4 strategies used for copy: `rsync, tar, default, rsync-daemon`

https://github.com/openshift/origin/blob/master/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsyncd.go

It seems port forwarding is done is the `rsync-daemon` copy strategy. Here's the start, end and check scripts for the daemon. 

https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsyncd.go#L27

The `startRemoteDaemon()` function gets a free port on the remote machine and executes the start daemon script on the remote machine.

https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsyncd.go#L156

**Comment by mik-dass** [comment]
> Could we use Go rsync library like https://github.com/Redundancy/go-sync to avoid local rsync requirement?

The library seems in a non maintained state (stated in the description too) and the latest commit is approx 3 years old.

**Comment by jorgemoralespou** [comment]
[Okteto](https://github.com/okteto/okteto) uses [Syncthing](https://github.com/syncthing/syncthing) library, which seems very smart and well maintained.

**Comment by kadel** [comment]
> [Okteto](https://github.com/okteto/okteto) uses [Syncthing](https://github.com/syncthing/syncthing) library, which seems very smart and well maintained.

@mik-dass can you check also this as an option. It might be an interesting option.


> The `startRemoteDaemon()` function gets a free port on the remote machine and executes the start daemon script on the remote machine.

How is port accessed in this case? Some are there some port forward mechanism or via Kubernetes Service somehow?

**Comment by cdrage** [comment]
Notes from a call: 
 - We could also copy over syncthing (binary) to the image using supervisord. 
 - We literally need to *only* find out what files have been changed, some form of a Go function that would find what file needs to be copied over / have been copied over.

**Comment by alanconway** [comment]
What is the objection to using rsync? It is available on every linux platform and on windows, and it is built into oc. It solves the "what do I need to sync problem" and the file transfer problem efficiently, it has decades of optimization. Its delta-transfer algorithm is faster (after the first sync) than anything we are going to write. Why reinvent the wheel?

**Comment by kadel** [comment]
> What is the objection to using rsync? It is available on every linux platform and on windows, and it is built into oc. It solves the "what do I need to sync problem" and the file transfer problem efficiently, it has decades of optimization. Its delta-transfer algorithm is faster (after the first sync) than anything we are going to write. We can run it over rsh or ssh just as we currently run the tar/untar pipe, we don't need an rsync server on either side.
> 
> Why reinvent the wheel?

Problem is not availability but usability.
Most of the Windows users won't have rsync installed and if you want to install it on windows you have to use Cygwin (as far as I know). More than 50% of our targeted are on Windows. This is a big barrier, odo shouldn't force users to install additional tools. Enterprise middleware developer is mostly using windows and won't have `rsync` installed, and in some cases, he/she won't be able to do even install it. 

`oc` requires rsync to be installed on the client side otherwise it will fallback to the tar/untar pipe.
`oc` is a different story, the target audience is more towards Ops and DevOps rather than Developers.  We would have to do the same thing, but in our cases, most of the users would be using fallback, that for me defeats the purpose of the optimization.

I'm not against using rsync, quite the opposite, I would like to use it as it will make our life much easier. But we have to find a way that will work for 80% of users without forcing them to install another tool. From the user's point of view, it needs to be seamless.

**Comment by jorgemoralespou** [comment]
I would say the solution needs to work for 100% of the users

**Comment by mik-dass** [comment]
> @mik-dass can you check also this as an option. It might be an interesting option.

@kadel @jorgemoralespou Syncthing is not a library that we can easily plug into our codebase. To run this we will need the binary on both sides. Even Okteto runs it by downloading the binary first and then performs the operations. This might be expensive for the users.

**Comment by cdrage** [comment]
@mik-dass I'm currently implementing a CRC check / doing checksums on each file. As of right now, for 27,000 files, it took about 3 seconds for do checks / see what the differences are.

**Comment by alanconway** [comment]
On Thu, Jun 20, 2019 at 3:36 AM Tomas Kral <notifications@github.com> wrote:

> What is the objection to using rsync?
>
> [snip[

> Most of the Windows users won't have rsync installed and if you want to
> install it on windows you have to use Cygwin (as far as I know).
>
Understood, packaging or requiring dependencies on windows is a pain. So
the requirement is a fully self-contained client that can run anywhere that
a Go executable can run.

**Comment by alanconway** [comment]
> > How is oc managing communication between local and remote rsync? Any port forwarding involved?
> 
> @kadel There are 4 strategies used for copy: `rsync, tar, default, rsync-daemon`
> 
> https://github.com/openshift/origin/blob/master/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsyncd.go
> 
> It seems port forwarding is done is the `rsync-daemon` copy strategy. Here's the start, end and check scripts for the daemon.
> 
> https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsyncd.go#L27
> 
> The `startRemoteDaemon()` function gets a free port on the remote machine and executes the start daemon script on the remote machine.
> 
> https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsyncd.go#L156
> 
> In the `normal rsync` strategy, the pod's existence is checked and then the rsync command is executed with the source and destination.
> 
> https://github.com/openshift/origin/blob/c1b9e450edc8b427cddd33bd0d9fce22cf658541/staging/src/github.com/openshift/oc/pkg/cli/rsync/copy_rsync.go#L71

Note that rsync has a remote-shell mode, and can create a temporary daemon using any remote shell transport (rsh, ssh etc.) without opening any extra ports or connections. However based on https://github.com/openshift/odo/issues/1788#issuecomment-503913647 it seems that the odo client must be self-contained without dependencies so using an external rsync client is probably not an option.

**Comment by mik-dass** [comment]
> @mik-dass I'm currently implementing a CRC check / doing checksums on each file. As of right now, for 27,000 files, it took about 3 seconds for do checks / see what the differences are.

I will try to implement one based on just `lastModified` date. I will benchmark and post the results here.

**Comment by alanconway** [comment]
> @mik-dass I'm currently implementing a CRC check / doing checksums on each file. As of right now, for 27,000 files, it took about 3 seconds for do checks / see what the differences are.

I don't think checksums are the way to go. Rsync uses size+timestamp by default, checksums are intended for the special case where the network is vastly slower than the extra disk and CPU access required to checksum every file. Here are some numbers from rsync (generated by attached shell script)

= Flags:  none
full copy: real 4.31
no copy:   real 1.69
= Flags: --checksum
full copy: real 4.42
no copy:   real 3.19

Checksum makes the best case (nothing to do) take over 75% of the time of the worst case (copy everything). I get the same numbers over loopback or a real ethernet interface.

**Comment by alanconway** [comment]
We don't have to solve the general file-sync problem. Our issue is detecting quickly whether anything has changed on the odo side since the last successful push. I think it would be fast and sufficient for odo to cache file-size+timestamp locally on each push, and do the check locally before the next push. The size+timestamp check isn't perfect but it is very widely  used (e.g. rsync, make), it is usually good enough, and developers generally understand that  meddling with timestamps is likely to mess things up without a complete rebuild.

We would want to add a "push --full"  option to force a full push if things somehow do get messed up. If we really want rsync-style reliability we could exchange timestamp+size in both directions, but if nothing else can meddle with files on the container then we may not need the extra complexity.

**Comment by alanconway** [comment]
> > @mik-dass I'm currently implementing a CRC check / doing checksums on each file. As of right now, for 27,000 files, it took about 3 seconds for do checks / see what the differences are.
> 
> I will try to implement one based on just `lastModified` date. I will benchmark and post the results here.

We crossed in the mail: +1 :)

I'd suggest using date + file size - its an extra consistency check that  it doesn't cost anything extra in terms of disk access.

**Comment by mik-dass** [comment]
> I'd suggest using date + file size - its an extra consistency check that it doesn't cost anything extra in terms of disk access.

:+1: I will add file size as an extra parameter for consistency.

> We would want to add a "push --full" option to force a full push

This might help the user if something goes wrong. We can trigger a full re index with this option. @kadel @jorgemoralespou ?

**Comment by mik-dass** [comment]
> I will try to implement one based on just lastModified date. I will benchmark and post the results here.

@kadel @cdrage @jorgemoralespou @alanconway I tried with the lastModifiedDate for the entire `odo` directory containing 29k+ files and it took `146ms` to get the path and modifiedDate of each file, put it in a map, convert it into a json and dump that in a file.

**Comment by kadel** [comment]
> We would want to add a "push --full" option to force a full push if things somehow do get messed up. If we really want rsync-style reliability we could exchange timestamp+size in both directions, but if nothing else can meddle with files on the container then we may not need the extra complexity.

+1 

> @kadel @cdrage @jorgemoralespou @alanconway I tried with the lastModifiedDate for the entire `odo` directory containing 29k+ files and it took `146ms` to get the path and modifiedDate of each file, put it in a map, convert it into a json and dump that in a file (there was no checking involved though).

this looks pretty good

**Comment by jorgemoralespou** [comment]
Agree.
And since the "push --full" command could trigger a full re-index, this can be helpful to whenever we decide to upgrade the strategy of how we do this. I think we should add a version to the index or metadata files/directory, so in case there's a version change we can do a reindex automagically or ask the user to do it explicitly.

**Comment by mik-dass** [comment]
@kadel @cdrage @jorgemoralespou For testing the performance here's a demo PR for benchmarking: https://github.com/openshift/odo/pull/1849/files (with only lastModifiedDate). 

NOTE: There is no filtering and other complex computations in the PR. This is just to test the performance of detecting changes.

**Comment by alanconway** [comment]
On Fri, Jun 21, 2019 at 7:02 AM Jorge Morales Pou <notifications@github.com>
wrote:

> Agree.
> And since the "push --full" command could trigger a full re-index, this
> can be helpful to whenever we decide to upgrade the strategy of how we do
> this. I think we should add a version to the index or metadata
> files/directory, so in case there's a version change we can do a reindex
> automagically or ask the user to do it explicitly.
>

Ideally we should detect any condition that needs a full sync and do this
automatically. We want the user to trust odo to get it right - that trust
is quickly lost if we get it wrong in anything but a very exceptional
situation.

**Comment by kadel** [comment]
Probably stupid question:
Why are we can't just list all files inside the directory in a container and compare it with the list of the files in the local directory? We could use modification time and size in comparison to detect changes. And we don't have to store anything.

**Comment by mik-dass** [comment]
> Why are we can't just list all files inside the directory in a container and compare it with the list of the files in the local directory? We could use modification time and size in comparison to detect changes. And we don't have to store anything.

The once concern I can think of currently is that the clock timing might be different or incorrect in the container and might be running some days behind. Is there any guarantee that it will always be the correct time?

**Comment by jorgemoralespou** [comment]
Also, how would you collect that information in the container and provide it to the client side. With scripts that are execed in the container? I know I'm recurrent on the topic, but wouldn't a smart procces in the container be better?

**Comment by kadel** [comment]
> Also, how would you collect that information in the container and provide it to the client side. With scripts that are execed in the container? I know I'm recurrent on the topic, but wouldn't a smart procces in the container be better?

Smart process in the container is not going to help us figure out what files we need to push into the container. We will have to push everything each time `odo push` is executed. 
I think that we discussed that this needs to be also optimized.

I know that this issue is not about this, but we need also solve the delete problem https://github.com/openshift/odo/issues/1354.


I think that all this has one common solution.
 - rebuilding only when there is a code change
 - pushing only changed files
 - delete files inside the container that were deleted locally

But maybe I'm taking this too far, and each problem can be solved with its own independent solution.

**Comment by jorgemoralespou** [comment]
My main concern is that all this logic is difficult to implement in bash scripts and coordinate with the generic supervisord, which can only start/stop a process. That's the main reason I'm constantly advocating for this solution, cause a smart app on the container side could just alleviate much of the logic, since there's currently some things that happen on the client side and some others on the container side. Minimizing what happens in one side and maximizing what happens in the other gives a lot of room for goodness. In this case, on the container side should there be all the logic, and on the client side should just provide the changeset. In this way, you can also not require the image to be s2i or even have all these new scripts, as the supervisor could take all the logic. It's easier to provide a new version of the supervisor than it is of the s2i images or the odo client itself.

**Comment by kadel** [comment]
Completely agree with you. No argument there.
"rebuilding only when there is a code change" problem can be solved on the container side. This is what hot reload will do.

But we still have problems with "deleting files" (we don't know what has been deleted between two `odo push` invocations). And we want to stop pushing the whole codebase all the time. This can't be solved inside the container.

**Comment by jorgemoralespou** [comment]
As I said in my response, agree. The changeset needs to come from the client. The container just needs ñ to apply it, ñ to both the ñ backup location and the current code location.

**Comment by alanconway** [comment]
> Probably stupid question:
> Why are we can't just list all files inside the directory in a container and compare it with the list of the files in the local directory? We could use modification time and size in comparison to detect changes. And we don't have to store anything.

Not stupid - that's exactly what rsync does. Basically we need to decide how far we want to go in implementing our own rsync-like solution, vs.  just adopting an existing rsync library.

Clock-skew is a good point to raise, but not problem here:  'rsync -a'  sets the timestamps on the remote copy to be the same as the local timestamp, and completely ignores the remote clock. Our existing tar-based copy does the same thing. Things can get weird if the clocks are badly out of sync (files created in the future) but most build tools won't care as long as the older/newer relations between files are sane.
