### ISSUE TITLE
Export context folder from deployed odo component created with previous release

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1790]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
There should be command to create context folder based on deployed component.

## Why is this needed?
For binary and git components created with previous odo releases there would be no context folder. That means there would be no straightforward way to work with those components.

**Comment by kadel** [comment]
You should be able to just do `odo component create java component-name --project project --app application` in the directory with the source code and use component-name project and application of the already existing component. If I recall correctly `odo` is not validating names during the component creation so this should work.

**Comment by jorgemoralespou** [comment]
We should not support backwards compatibility for this, as the context folder was introduced before beta. As @kadel mentions, if a component was created by a previous version of odo, you could still create the context folder that way.

**Comment by dgolovin** [comment]
@jorgemoralespou I am not asking backward compatibility, I am asking for the way out for developers, if any, who is using git and binary components. If we would just release odo-1.0.0 with vscode now all those component would not be usable without context folder. What @kadel suggested is basically 'do it again' for all git/binary components deployed. Would be much easier with 'odo import' to reconstruct context folder using deployed component.

**Comment by dgolovin** [comment]
@kadel
> You should be able to just do `odo component create java component-name --project project --app application` in the directory with the source code and use component-name project and application of the already existing component. If I recall correctly `odo` is not validating names during the component creation so this should work.
What would happen for components with URLs, storage and links if after I use just `odo create` and then push it?

**Comment by girishramnani** [comment]
@dgolovin is this issue still relevant?
