### ISSUE TITLE
odo config set should work without an active connection with the OpenShift cluster

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1791]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
This is a spin-off from https://github.com/openshift/odo/pull/1758#discussion_r290252753.

Like `odo config view`, `odo config set` should be doable without an active connection with the OpenShift cluster. Config values should be changed in `.odo/config.yml` and a connection to the cluster should be required only when doing `odo push --config`

## Why is this needed? 
At the moment, doing `odo config set`, which only affects the configuration values in the developer's system, requires an active connection to OpenShift cluster. This is not required unless one is pushing the changes.

**Comment by kadel** [comment]
/close 
in favor of systematic fix https://github.com/openshift/odo/issues/1588
