### ISSUE TITLE
Inconsistency in odo command exit code

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1803]
[kind/bug]

## What versions of software are you using?
- Operating System: All supported platform
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo app describe test
 ✗  Application test has no components or services deployed.
Amits-MacBook-Pro:odo amit$ echo $?
0
Amits-MacBook-Pro:odo amit$ odo app delete test -f
 ✗  test app does not exists
Amits-MacBook-Pro:odo amit$ echo $?
1
```

## Actual behavior
Inconsistent exit code

## Expected behavior
Exit code should be consistent through out the odo command/sub-command execution. For example:

On a fresh cluster ```odo app describe test``` returns 0 (graceful exit) where as ```odo app delete test -f``` returns ```1```.

In both the case either it should be 0 (graceful exit) or non-zero otherwise.

**Comment by amitkrout** [comment]
ping @kadel

**Comment by kadel** [comment]
If commands results in error, return code needs to be non-zero.

**Comment by amitkrout** [comment]
@girishramnani Found some weird behaviour observed which i believe is not acceptable for a cli tool. Due to the issue #1899 unfortunately it was not reported. When i am fixing the issue via #1902 this is what i am hitting

```
$ odo app describe test --project myproject
 ✗  Application test has no components or services deployed.

$ echo $?
0

$ odo app describe test --project myproject > out 2>error

$ cat out 

$ cat error 
 ✗  Application test has no components or services deployed.
```

**Analysis** 

Actual - For a graceful exit, message is redirected to stderr chanel
Expected - For a graceful exit, message should be redirected to stdout chanel

Due to this inconsistency in behaviour pr #1902 is failing. I am increasing the priority to bring more attention to this issue. For now i am commenting the assertion statment to make CI pass.
