### ISSUE TITLE
service create shouldn't require existing component

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1810]
```
▶ odo service create mysql --project myproject --app myapp
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component
```

It should be possible to create a service without the odo component.

 - `odo service create mysql` outside component  directory should error out and inform user that `--project` and `--app` flags are required. `--project` is not necessary if set in `KUBECONFIG`
 - `odo service create` is missing `--context` flag
 - `odo service create mysql --app myapp` - is valid command outside of the component directory

**Comment by jorgemoralespou** [comment]
See my comments here: https://github.com/openshift/odo/issues/1720#issuecomment-501298613

**Comment by dharmit** [comment]
@kadel I looked at the discussion on the other issue and, I believe, most of the points being discussed between you & @jorgemoralespou are covered in the https://github.com/openshift/odo/issues/1872#issuecomment-514185476. But correct me if I'm wrong.
