### ISSUE TITLE
Wrong values reported in time intervals

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#1811]
https://travis-ci.com/openshift/odo/jobs/207361276#L1442

The value reported is `2562047h47m16.854775807s` which is equivalent to `292.4711187` years

**Comment by kadel** [comment]
@cdrage can please you look into it?

/kind bug
/priority medium

**Comment by cdrage** [comment]
@mik-dass LOL. That shouldn't happen. I'll take this up :+1:

**Comment by cdrage** [comment]
@mik-dass I have a feeling it has to do with:

https://github.com/openshift/odo/blob/master/pkg/log/fidget/spinner.go#L125

and the Travis CI environment not reporting the time correctly...

Hopefully it's just a fluke and won't happen again, but I'll do some quick debugging and see how in the world they managed to get such a high value.

**Comment by kadel** [comment]
> @mik-dass I have a feeling it has to do with:
> 
> https://github.com/openshift/odo/blob/master/pkg/log/fidget/spinner.go#L125
> 
> and the Travis CI environment not reporting the time correctly...
> 
> Hopefully it's just a fluke and won't happen again, but I'll do some quick debugging and see how in the world they managed to get such a high value.

@cdrage It is not related to TravisCI, I can see it in integrations tests if running on my local machine.
Interestingly if I run `odo` command manually from the terminal, it is ok, but in tests outputs, it is still wrong.

**Comment by mik-dass** [comment]
@cdrage interestingly this weird time interval happens when we enable the `-v` flag. @kadel Since we run the integration tests with the `v` flag enabled, it shows the weird interval in the integration tests. Without the flag it seems to work fine.

**Comment by cdrage** [comment]
@mik-dass Managed to fix it. The code logic wasn't adding a value to the `time` variable in the struct. Hence the value overflow and it saying it was taking wayyyyy longer than normal haha. Fixed in the PR! https://github.com/openshift/odo/pull/1824
