### ISSUE TITLE
"odo url create" should work without an active connection with the OpenShift cluster

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1813]
> Tangential question: shouln't `odo url create` work without having an active connection with the OpenShift cluster? 🤔

Yes, it should, there is nothing that we need from the cluster.

_Originally posted by @kadel in https://github.com/openshift/odo/issues/1213#issuecomment-501231074_

**Comment by kadel** [comment]
/close

this is already covered in https://github.com/openshift/odo/issues/1588#issuecomment-501206443
