### ISSUE TITLE
Improve odo watch integration test

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1819]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Only one watch test scenario https://github.com/openshift/odo/blob/master/tests/integration/watch_test.go#L54 has been running since a long period of time. So more scenario can be added using the combination of flags.
```
$ odo watch -h
Watch for changes, update component on change.

Usage:
  odo watch [component name] [flags]

Examples:
  # Watch for changes in directory for current component
  odo watch
  
  # Watch for changes in directory for component called frontend
  odo watch frontend

Flags:
      --app string           Application, defaults to active application
      --context string       Use given context directory as a source for component settings
      --delay int            Time in seconds between a detection of code change and push.delay=0 means changes will be pushed as soon as they are detected which can cause performance issues (default 1)
  -h, --help                 Help for watch
      --ignore stringSlice   Files or folders to be ignored via glob expressions.
      --project string       Project, defaults to active project
      --show-log             If enabled, logs will be shown when built

Global Flags:
      --skip-connection-check   Skip cluster check
  -v, --v Level                 Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec      Comma-separated list of pattern=N settings for file-filtered logging
```

## Why is this needed? 

To add more integration test coverage

**Comment by kadel** [comment]
Please describe the scenarios in the issue before implementing it. 

My take on this is that it is far more important to test the watch with different images than go overboard with testing every single flag that command has.

**Comment by kadel** [comment]
Let's start with having at least one test for each flag, no need to start with permutations.

**Comment by girishramnani** [comment]
We have good watch tests already and there are issues related to improving intg tests which covers this if need be
