### ISSUE TITLE
Warning Message to Update Version to v1.0.0-beta3 Not Suppressed 

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1835]
[kind/bug]

When using `odo v1.0.0-beta2 (242f0979)`, the following message appears to warn of a version update:

```
A newer version of odo (version: v1.0.0-beta3) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/openshift/odo/master/scripts/install.sh | sh
to update manually, or visit https://github.com/openshift/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo config set UpdateNotification false'
```

Running `odo config set UpdateNotification false` does not suppress the error message moving forward.

This makes me wonder if the warning message about new versions should be the default. Maybe it would make sense to have the user opt in to receiving warning messages about version updates. 

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0-beta2 (242f0979)`

## How did you run odo exactly?
`odo login -u user -p password`
`odo config set UpdateNotification false`

## Actual behavior
Warning message above still displays after running `odo config set UpdateNotification false` and returns the following:

```
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component
```

## Expected behavior
Warning message about version does not display after running `odo config set UpdateNotification false`.

**Comment by amitkrout** [comment]
@danielhelfand There is a typo in UX you are seeing. Instead of ```odo config set UpdateNotification false``` it should be ```odo preference set UpdateNotification false```

I have already created an issue #1822 to fix the UX. 

So closing the issue as it is being tracked in #1822

**Comment by danielhelfand** [comment]
@amitkrout Thanks for the clarification!
