### ISSUE TITLE
odo logout fails with error of the current directory does not represent an odo component

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1836]
[kind/bug]

## What versions of software are you using?
- Operating System: I tested it on macOS. 
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo login -u developer -p developer https://192.168.64.3:8443
Connecting to the OpenShift cluster

Login successful.

You have one project on this server: "myproject"

Using project "myproject".


$ odo logout 
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component
```
## Actual behavior
Fails

## Expected behavior
Should successfully logout

**Comment by amitkrout** [comment]
ping @cdrage

**Comment by amitkrout** [comment]
@kadel If the fix is less complex then can you add this to the current sprint

**Comment by kpiwko** [comment]
Thanks for reporting this @amitkrout , I've just hit the same problem :-)

**Comment by cdrage** [comment]
Ping @girishramnani as I believe he's implemented this "check"
