### ISSUE TITLE
service list does not work outside of component dir

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1838]
[kind/bug]

## What versions of software are you using?
- Operating System: All supported platform
- Output of `odo version`: master

## How did you run odo exactly?
```
$ oc --request-timeout 5m import-image java --namespace=myproject --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --confirm

$ oc annotate istag/java:latest --namespace=myproject tags=builder --overwrite

$ odo create java sb-app

$ odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret -p postgresql_database=my_data -p postgresql_version=9.6

$ cd .. && odo service list
```
## Actual behavior
```
$ cd .. && odo service list
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component

$ odo service list --project myproject
 ✗  the current directory does not represent an odo component.
```

## Expected behavior
```
$ odo service list
NAME                  TYPE                  STATUS
dh-postgresql-apb     dh-postgresql-apb     ProvisionedAndBound
```

**Comment by amitkrout** [comment]
#1872

**Comment by dharmit** [comment]
This one is reproducible. When working with minishift, I had to do `minishift openshift component add template-service-broker` twice to be able to see the service mentioned in the description. 

This one doesn't seem directly related to #1872 or #1810 (both are about `odo service create`) to me and can be fixed separately. 

WDYT @cdrage @amitkrout @girishramnani ?

**Comment by amitkrout** [comment]
> This one is reproducible. When working with minishift, I had to do `minishift openshift component add template-service-broker` twice to be able to see the service mentioned in the description.
> 
> This one doesn't seem directly related to #1872 or #1810 (both are about `odo service create`) to me and can be fixed separately.
> 
> WDYT @cdrage @amitkrout @girishramnani ?

ping @kadel

**Comment by dharmit** [comment]
Looking at https://github.com/openshift/odo/blob/bab62c4d7c00d851cbb60d8d1ca22ee7806399e6/pkg/odo/cli/service/list.go#L49 I think that `odo service list` is not going to work without a context as it needs application name. So executing `odo service list` from a directory that doesn't have a component is going to fail unless we somehow use a default app+project combination when the command is executed.

The way `oc` command handles this from `~/.kube/config` file can be worth a look?

Say, for example, within a directory my `.odo/config.yaml` file looks like this:
```bash
$ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: nodejs-olzr
```
so if I execute `odo service` commands from this directory, I should be working on the `myproject` project and `app` application.

But if I'm working from a non-component directory, the default values of application and project could be fetched from a central file that's stored somewhere under `~/.odo` and has a mapping for which app+project to use for given user.

I'm just thinking out loud here and could be totally wrong. Happy to be corrected. :smile:

**Comment by kadel** [comment]
`odo service list` should work in a similar way to `odo component list`

if run inside the context directory or with `--context` flag it will take project and application name from the component config.
If run outside of the context directory or without `--context` flag it should error out at tell the user that `--project` and `--application`  or `--context` is required. I believe that we are doing the same for `odo component list`
