### ISSUE TITLE
Improve test specs

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1845]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
To cover more test cases of different scenarios of all odo command/sub-command

Test scenario

## Why is this needed? 
Recently some issue are hit which are not covered in test spec. Seems we are still rely on spec  which are not enough to capture negative, corner cases even few positive scenario issues. 

Better to revisit the spec, update or add new spec to avoid such issues

**Comment by amitkrout** [comment]
in the current test it seems some flags are missing or not properly tested in the corresponding command test file. For example flag ```--port``` is nowhere validated in the component test file.

Also in some cases the command itself is missing in the test file. For example get and set command.
```
$ odo project -h
[...]
Available Commands:
  [...]
  get         Get the active project
  set         Set the current active project
  [...]
```

I guess you can find some more such scenario where these flags and commands are not validated yet.  Now it will be easy to add those missing commands and flags in the respective command files. To find out those missing parts just run ```-h``` against that command or subcommands. 

Test command/file under consideration:

Command test:
- [ ] cmd_app_test

- [ ] cmd_catalog_test

- [ ] component

- [ ] cmd_perf_config_test

- [ ] cmd_project_test

- [ ] cmd_service_test

- [ ] cmd_storage_test

- [ ] cmd_url_test

Special case:

- [ ] cmd_push_test

NOTE: If you think some commands or flags are difficult to validate in their respective command test file then add those tests in generic test file.

**Comment by amitkrout** [comment]
#2176

**Comment by kadel** [comment]
@amitkrout Can you please break down to smaller issues that describe what scenarios are missing and that can be addressed in one sprint?

**Comment by amitkrout** [comment]
This requires a revisit
