### ISSUE TITLE
odo component commands are confusing before first push

### ISSUE THREAD

**Issue by alanconway** [openshift/odo#1847]
[kind/bug]

## What versions of software are you using?
- Operating System: 
Linux grommit 5.1.11-300.fc30.x86_64 #1 SMP Mon Jun 17 19:33:15 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Output of `odo version`:
odo v1.0.0-beta3 (HEAD)

Server: https://192.168.42.249:8443
Kubernetes: v1.11.0+d4cacc0

## Actual behavior

I've put the "expected" comments in-line with the actual odo commands and output:

```
[aconway@grommit nodejs-ex (master *%=)]$ odo create nodejs
 ✓  Validating component [118ms]
Please use `odo push` command to create the component with source deployed
[aconway@grommit nodejs-ex (master *%=)]$ odo component describe
 ✗  component nodejs-kedz does not exist
```
I just created the component so it makes no sense to say it does not exist. I suggest:
```
Component Name: nodejs-kedz
Status: not deployed, use `odo push`
```
Also: `create` should tell me the name of the component it created "nodejs-kedz" as I have no way of knowing that and it is important if there are ever multiple components that I know what I just created.

```
[aconway@grommit nodejs-ex (master *%=)]$ odo component list
 ✗  There are no components deployed.
```
The command is "component list" not "component list-deployed" - it should list the component that I just created because...
```
[aconway@grommit nodejs-ex (master *%=)]$ odo component create
 ✗  this directory already contains a component
```
"list" just told me there are no components, but now I'm told I can't create one because there already is one. Clearly the component *does* exist, it is just in an un-deployed state. `list` should not hide it from me.

**Comment by kadel** [comment]
/bug
/priority medium
/milestone 1.0


### Fixes:

#### `odo component describe`
Needs to work for nondeployed components.
The output needs to contain the information that the component is not pushed, and how to push it.


#### `odo component list`
I agree with you @alanconway it is a little bit confusing. But this one is a little bit trickier, we can't really list all non-deployed components as the only place how to find them would be going through the whole user's filesystem.
But we can at least include a component in the current directory (pushed or not) in the list.

cc @jorgemoralespou

**Comment by jorgemoralespou** [comment]
`odo component list` definition is: List components in the current application, so I would understand the behavior to be:

- Give details about the current component (if no args provided or if -app is provided and matches the app for the current component). Also details whether this component is deployed or not (as status).
- Query the server, current namespace (as namespace should not be in .odo-config.yaml) for components with the same app as current component. Also give some details of these components so the developer can identify where to look for them or how to interact with them (e.g. Binary, local or git)

**Comment by alanconway** [comment]
> #### `odo component list`
> I agree with you @alanconway it is a little bit confusing. But this one is a little bit trickier, we can't really list all non-deployed components as the only place how to find them would be going through the whole user's filesystem.
> But we can at least include a component in the current directory (pushed or not) in the list.

+1 - the real problem is when list returns nothing but create returns an error saying there is something. Just listing the current directory would resolve that.

**Comment by cdrage** [comment]
For `odo component describe`:

```sh
[aconway@grommit nodejs-ex (master *%=)]$ odo component describe
 ✗  component nodejs-kedz does not exist
```

We could at least have some form of output that says, `Create a component with odo create` or something similar.

Each error should at least give the user some way / form to fix it..

**Comment by alanconway** [comment]
On Mon, Jun 24, 2019 at 3:59 PM Charlie Drage <notifications@github.com>
wrote:

> For odo component describe:
>
> [aconway@grommit nodejs-ex (master *%=)]$ odo component describe
>
>  ✗  component nodejs-kedz does not exist
>
> We could at least have some form of output that says, Create a component
> with odo create or something similar.
>
The problem here is that the component *does* exist locally but has not yet
been deployed - odo uses "exists" in a confusing way.
IMO this shouldn't be an error but a description of the local component
with a note that says it hasn't been deployed yet.

**Comment by jorgemoralespou** [comment]
I do agree with @alanconway 
Is important to use correct terminology and language so user easily understand and learns odo

**Comment by cdrage** [comment]
@jorgemoralespou @alanconway 

Would it be better to instead say `Foobar component not found in the cluster` rather than "exist" ? Would be more beneficial and implies that it's not "deployed yet"

**Comment by jorgemoralespou** [comment]
Why not "Component not pushed yet to the cluster. Use `odo push` to push
your Component when ready."?

**Comment by cdrage** [comment]
@jorgemoralespou Can't use multiple sentences for error messages, but I've updated the PR: https://github.com/openshift/odo/pull/1861
