### ISSUE TITLE
odo project delete: Confusing message about ServiceCatalog

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1848]
When deleting project there is a confusing message about ServiceCatalog not being available.

```
▶ odo project create asdf
 ✓  New project created and now using project : asdf

▶ odo project delete asdf
 ⚠  Unable to access Service Catalog instances, may not be enabled on cluster
? Are you sure you want to delete project asdf Yes
 ✓  Deleting project asdf [6s]
Deleted project : asdf
```

There should be no such message

**Comment by cdrage** [comment]
This was implemented here: https://github.com/openshift/odo/pull/1809

What should we do with regards to the error message? When we perform `application.List` we now also check ServiceInstances.

**Comment by kadel** [comment]
> We could drop this into verbose / hidden output.

Yes, both are ok, up to you. 

The message is pretty confusing especially for the user that doesn't have service catalog enabled on their cluster and never used or deployed any Service, no suddenly they see some message complaining about Service Catalog when deleting a project.
