### ISSUE TITLE
Jenkins support with odo commands

### ISSUE THREAD

**Issue by chandrapersi** [openshift/odo#1852]
oc command supports Jenkins creation and creation of build pipeline.
But it seems same support is lacking with odo commands. 
For ex. following command works
oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/pipeline/nodejs-sample-pipeline.yaml

But same command with odo doesn't. 

Is there any documentation which demonstrate odo commands instruction to setup Jenkins and Pipeline.

**Comment by kadel** [comment]
Hi @chaitanyaenr,

Odo is targeting developers, and we want to make developers life easier. One of the ideas behind odo is that developers shouldn't need to write any yaml definitions, You won't be able to directly apply yaml file using `odo` as you can do with `oc`. This is not even on `odo` roadmap.

But we have Pipelines support on our roadmap - https://github.com/openshift/odo/issues/1238. 
I don't have any details right now. I don't know when we get to it, but some future `odo` version will definitely have support for Pipelines in some form.


If you have any suggestions or ideas feel free to continue the discussion on Pipelines epic 
 issue https://github.com/openshift/odo/issues/1238



/close
