### ISSUE TITLE
No option for setting policy on service account with odo commands

### ISSUE THREAD

**Issue by chandrapersi** [openshift/odo#1859]
oc policy add-role-to-user view system:serviceaccount:top-secret:robot

Setting policy is only available with oc command but not with odo.

**Comment by kadel** [comment]
`odo` is not a replacement for `oc`.
`odo` focuses only on developers, and developer flow. Managing roles is a little bit more advanced case, and `oc` does a good job managing users and roles.

**Comment by surajnarwade** [comment]
@chandrapersi , since odo is developer CLI not ops one, this is out of scope for odo :)

**Comment by surajnarwade** [comment]
HI @chandrapersi , Closing this issue as of now. feel free to reopen if needed :smile:
