### ISSUE TITLE
Optimize "Validating component" step.

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1863]
```
Validation
 ✓  Validating component [6s]
 ✓  Checking component [916ms]

Configuration changes
 ✓  Applying configuration [937ms]

Pushing to component mynode of type local
 ✓  Waiting for component to start [113ms]
 ✓  Copying files to component [6s]
 ✓  Building component [846ms]
 ✓  Changes successfully pushed to component
```

I can't take 6s to perform basic validation.

There are multiple checks that are happening there.

I can see options on how to speed up checks if builder image exists, and if the version exists, those functions is using List calls, there are better ways to check (using just Get).
I'm sure that there will be more to speed this up. 
We should get this under 1s

**Comment by mik-dass** [comment]
@kadel I see two exist calls during validation

https://github.com/openshift/odo/blob/ca5e619292a302855a7357dd8fa9905715ffc6e5/pkg/odo/cli/component/push.go#L133
and 
https://github.com/openshift/odo/blob/ca5e619292a302855a7357dd8fa9905715ffc6e5/pkg/component/component.go#L513

I also two calls to the catalog list functions

https://github.com/openshift/odo/blob/ca5e619292a302855a7357dd8fa9905715ffc6e5/pkg/catalog/catalog.go#L78
and 
https://github.com/openshift/odo/blob/ca5e619292a302855a7357dd8fa9905715ffc6e5/pkg/catalog/catalog.go#L58

Removing these can also speed up things.

**Comment by surajnarwade** [comment]
`component.Exists` is being resolved here: https://github.com/openshift/odo/pull/1905
