### ISSUE TITLE
odo nginx

### ISSUE THREAD

**Issue by rashmi-sakhalkar** [openshift/odo#1868]
[kind/Documentation]
Can you pls guide how I can customize the nginx.conf and then create the nginx service.
Quick reply would be very helpful.

**Comment by amitkrout** [comment]
@rashmi-sakhalkar Can you please describe the complete usecase

**Comment by rashmi-sakhalkar** [comment]
Using odo I created a nodejs application. I then want to setup nginx reverse proxy to access the nodejsapp.
How can i achieve this with odo?

**Comment by rashmi-sakhalkar** [comment]
Using oc I could setup the reverse proxy following the steps given in below link.
http://keyangxiang.com/2018/06/01/Openshift/how-to-run-nginx-as-reverse-proxy/

But I want to achieve this with odo.

**Comment by rashmi-sakhalkar** [comment]
closing this as duplicate
