### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by rashmi-sakhalkar** [openshift/odo#1869]
[kind/bug]
How to configure nginx for a nodejs application. Is there a way to edit the nginx.conf.

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

odo v1.0.0-beta3

## How did you run odo exactly?
using cli

## Actual behavior
Using odo I have created a NodeJS application. Exposed the route.
I want to now configure a Nginx reverse proxy to access the NodeJs application pages.

## Expected behavior
How can I configure Nginx reverse proxy for above scenario

## Any logs, error output, etc?
none

**Comment by amitkrout** [comment]
Its hard to understand the usecase with the details provided above. So can you fill the issue template. And make the issue title bit descriptive

**Comment by amitkrout** [comment]
@rashmi-sakhalkar I believe you are asking similar question in #1868 too. If yes, then can you close #1868 and lets track your question here

**Comment by rashmi-sakhalkar** [comment]
Using odo I created a nodejs application. I then want to setup nginx reverse proxy to access the nodejsapp.
How can i achieve this with odo?

Using oc I could setup the reverse proxy following the steps given in below link.
http://keyangxiang.com/2018/06/01/Openshift/how-to-run-nginx-as-reverse-proxy/

**Comment by surajnarwade** [comment]
@rashmi-sakhalkar , can you please provide us exact steps to reproduce the issue ?

**Comment by rashmi-sakhalkar** [comment]
I am looking out for help on odo commands for the below scenario.

Step 1. Create a nodejs app and expose the url. (eg. http://<Host url of Node Js app>)
Step 2. Create a nginx application with a preconfigured nginx-proxy.conf file.

How can I configure the nginx.conf file and then create the service using odo.

Using Openshift oc I follow the below steps:
1. oc new-app registry.access.redhat.com/rhscl/nginx-112-rhel7~$HOME/webfolder --name=nginxbase
2. oc start-build nginxbase --from-dir=$HOME/webfolder
3. 
oc delete bc/nginxbase
oc delete dc/nginxbase
oc delete svc/nginxbase
4. Create Dockerfile with below contents
FROM nginxbase:latest
ADD nginx-proxy.conf /opt/app-root/etc/nginx.default.d/nginx-proxy.conf

5. Create nginx-proxy.conf with below contents
location /test {
  proxy_pass http://<Host_Of_NodeJS_route>;
}
6. Create nginx app using Dockerfile and nginx-proxy.conf file.
oc new-app --strategy=docker nginxbase~. --name=myreverseproxy
7. oc start-build myreverseproxy --from-dir=.
8. oc expose svc/myReverseProxy
9. When i access the http://<ngixurl_host_url>/test it redirects to the nodejs application url.

**Comment by rashmi-sakhalkar** [comment]
I want to know how I can configure nginx reverseproxy using odo cli.

**Comment by surajnarwade** [comment]
I can help with this use case,

> Step 1. Create a nodejs app and expose the url. (eg. http://)

```
cd nodejs-ex/
odo create nodejs
odo url create --port 8080
odo push
```

I am not sure about nginx stuff, but just to give context, `odo` is developer focussed CLI, so I am not sure how odo is useful in your use case.

**Comment by rashmi-sakhalkar** [comment]
I have successfully created the nodejs component using odo.
I want odo commands to create nginx component with customized config. Can you please connect with your team and share the steps.

**Comment by amitkrout** [comment]
> I have successfully created the nodejs component using odo.
> I want odo commands to create nginx component with customized config. Can you please connect with your team and share the steps.

You can track your concern in Issue #1874. Both issue looks similar.
