### ISSUE TITLE
How to create nginx component in odo

### ISSUE THREAD

**Issue by rashmi-sakhalkar** [openshift/odo#1874]
[kind/Documentation]
The odo catalog consist of nginx component.
How can i create a nginx service using odo cli. 
Please share the commands.

**Comment by rashmi-sakhalkar** [comment]
**Commands executed:-**
# git clone https://github.com/sclorg/nginx-ex.git
# cd nginx-ex/
# odo create nginx my-sample-nginx1
# odo push

**ERROR::**

Validation
 â  Validating component [4s]
 â  Checking component [6s]

Configuration changes
 â  Initializing component
 â  Creating component [249ms]
 â  Applying configuration [0s]

Pushing to component my-sample-nginx1 of type local
 â  Waiting for component to start [11s]
 â  Copying files to component [2s]
 â  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
/var/lib/supervisord/bin/assemble-and-restart: line 19: rsync: command not found

 â  Building component [140ms]
 â  command terminated with exit code 127

**Comment by surajnarwade** [comment]
```
 $ odo create nginx 
 ✓  Validating component [90ms]
Please use `odo push` command to create the component with source deployed
```

```
18:07 $ odo push
Validation
 ✓  Validating component [129ms]
 ✓  Checking component [3ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [535ms]
 ✓  Applying configuration [17963ns]

Pushing to component nginx-oopm of type local
 ✓  Waiting for component to start [30s]
 ✓  Copying files to component [3s]
 ✗  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
/var/lib/supervisord/bin/assemble-and-restart: line 19: rsync: command not found

 ✗  Building component [153ms]
 ✗  command terminated with exit code 127
```

I am facing the same issue, looks like `nginx` builder image don't have `rsync` installed & odo supervisord scripts are not checking whether `rsync` is installed or not

**Comment by surajnarwade** [comment]
@rashmi-sakhalkar , I have raised the issue here: https://github.com/openshift/odo-supervisord-image/issues/22

**Comment by rashmi-sakhalkar** [comment]
By when can I expect a resolution for this issue

**Comment by amitkrout** [comment]
@surajnarwade https://github.com/openshift/odo/issues/1869#issuecomment-506665052 cc_ @rashmi-sakhalkar
