### ISSUE TITLE
Use of client side caching when interacting with openshift

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1882]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Through out the lifecycle of an odo run, we fetch information which at times do not change and hence client side caching is possible.
Libraries like https://godoc.org/k8s.io/client-go/tools/cache can be considered here.

## Why is this needed? 
For optimization purposes

> original proposal and research done by @alanconway :tada:

**Comment by kadel** [comment]
https://github.com/openshift/odo/pull/1891 already improved the speed of validation a lot.

Not sure how big impact his will have.
If this is something that we can easily enable and it will be just one day work, let's do it. But I don't think that we need to spend more time on this right now.

/priority low

**Comment by girishramnani** [comment]
got it

**Comment by girishramnani** [comment]
The benefit we would get from this feature would outweigh the effort in my opinion so closing this for now
