### ISSUE TITLE
Implement `--wait` flag for `odo project delete`

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1884]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Add `--wait` flag in `odo project delete` similar to `odo project create`

## Why is this needed? 

Reference: `waitForProjectToBeGone` from https://github.com/openshift/odo/issues/1739

as of now, vscode plugin relies on,

```
oc wait project/${project} --for delete
```

**Comment by surajnarwade** [comment]
cc @kadel @cdrage @dgolovin

**Comment by cdrage** [comment]
ping @girishramnani

**Comment by cdrage** [comment]
Se my current implementation: #2397 

I'm having major troubles mitigating ONE niche case and that's essentially when you run `odo project create` IMMEDIATELY after `odo project delete` with the same project name.

Here's essentially the TLDR;

- `--wait` works. And works well
- if you do project create with the same name as the project you just deleted, it *may* fail as your cluster is still propagating changes..

The project is deleted asynchronously by OpenShift. We cannot control this. OpenShift will delete all the pods + project + etc when it wants. No amount of code can fix this. My implementation #2397 even waits for **all** pods to be deleted, but to no avail. You must wait until the project is *completely* closed by OpenShift.

This is actually a "feature" of OpenShift and no amount of code would fix it. For example, if you were to create a watch for Project or even Pods (from the deleted project) it'd fail. OpenShift says it's deleted.. `oc get projects` also shows blank... but when you do `oc create project foobar`, it'll error out!

Here's an explanation of what happens by Will Gordon @ Red Hat from https://stackoverflow.com/questions/48208001/deleted-openshift-online-pro-project-has-left-a-trace-so-cannot-create-project-o

```
Projects are deleted asynchronously after you send the delete command. So it's possible that the deletion just hasn't been reconciled yet. It should happen within a minute or so, so try again.

Also, please be aware that in a multitenant environment, like OpenShift Online, you are prevented from creating a project with the same name as any other project in the cluster, even if it's not your own. So if you can't create the project, it's possible that someone has already created a project with the same name.
```

So for the niche case of:

```sh
odo project delete foobar --wait
# create a few components here
odo project create foobar
```

We cannot support it. You will have to literally wait for your cluster to automatically delete the project. In the case of `minishift` or `crc` or something local, this is done almost instantly. But when you are dealing with multi-tenant environments such as OpenShift Online or our internal test cluster, you'll just have to wait for OpenShift to finish. 

Ping @girishramnani @amitkrout @kadel
