### ISSUE TITLE
Demonstration Video Uses Out of Date odo Version

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#1888]
[kind/Documentation]

The [video](https://asciinema.org/a/225717) in the `README.md` is no longer representative of the current `odo` workflow of deploying a Node.js application. 

In the video, the Node.js sample app is created with a url as follows:

```
odo create nodejs
odo push
odo url create
```

Currently, the workflow is as follows:

```
odo create nodejs
odo push
odo url create --port 8080
odo push
```

I believe there is work going on to not require the `--port` flag for `odo url create`, so it may again change. Would the next release of `odo` (i.e., `odo v1.0.0-beta4`) be a good chance to update the demonstration video?

## What did you find missing in the documentation?

The video demonstration used is out of date with the current workflow of `odo`.

## What is the relevance of it?

The video may confuse users getting started with `odo`.

**Comment by pmacko1** [comment]
@dharmit do you know what is the action item on this one, please?

**Comment by danielhelfand** [comment]
Looking at the video currently in the main README, I think this has been addressed. This was from July when I think the video was using a much older version than what had been released at the time. I think this can be closed but obviously makes sense to keep updating over time.

**Comment by dharmit** [comment]
At the moment, this issue is pretty much addressed as @danielhelfand pointed out. We have bunch of videos based on 1.0 from around September-October timeframe. We'll be creating new ones very soon as we add some important features in this sprint and the next one.

Closing this issue.
