### ISSUE TITLE
Config set creates local config file

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1895]
[kind/bug]

## What versions of software are you using?
- Operating System: Supported platform
- Output of `odo version`: master

## How did you run odo exactly?
```
$ mkdir -p /Users/amit/Context
$ odo config set memory 2Gi --context /Users/amit/Context/
```

## Actual behavior
```
$ odo config set memory 2Gi --context /Users/amit/Context/
Local config was successfully updated.
Run `odo push --config` command to apply changes to the cluster.

$ cat /Users/amit/Context/.odo/config.yaml 
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  MinMemory: 2Gi
  MaxMemory: 2Gi
Amits-MacBook-Pro:odo amit$

```
## Expected behavior
Should report error

**Comment by amitkrout** [comment]
ping @kadel @girishramnani

**Comment by kadel** [comment]
@amitkrout yes, this is a bug. If local config file doesn't exist `odo config set` should fail, not create it.


I'm a decresing priority a little bit. This is not preventing the use of odo, it is just inconvenience that might confuse people.

/priority Medium
/remove-priority High

**Comment by amitkrout** [comment]
> I'm a decreasing priority a little bit. 

@kadel This is a clear case of regression of spec [1] and [2]. In the mentioned spec i am continuously hitting the issue locally. But surprisingly in CI only spec [2] is hit with the issue - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/1843/pull-ci-openshift-odo-master-e2e-scenarios/1046.  

There is something very weird happening. So i would say lets not decrease the priority as it breaks the existing feature and lets propose a fix in the current sprint. Till then i can comment out those affected test spec.

[1] https://github.com/openshift/odo/blob/master/tests/e2escenarios/core_beta_flow.go#L111
[2] https://github.com/openshift/odo/blob/master/tests/e2escenarios/core_beta_flow.go#L128

> This is not preventing the use of odo, it is just inconvenience that might confuse people.

Right, but i am concern about the existing test cases those are broken.

**Comment by girishramnani** [comment]
I remember implementing this, a recent change might have removed the `erroring out`

**Comment by amitkrout** [comment]
> There is something very weird happening. So i would say lets not decrease the priority as it breaks the existing feature and lets propose a fix in the current sprint. Till then i can comment out those affected test spec.

pr #1897 sent
