### ISSUE TITLE
ODO_S2I_DEPLOYMENT_BACKUP_DIR cleanup from occlient

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1908]
once https://github.com/openshift/odo/pull/1840 is merged, `ODO_S2I_DEPLOYMENT_BACKUP_DIR` wouldn't be needed and hence we should remove that from occlient

**Comment by kadel** [comment]
/assign @girishramnani 
/priority high

This needs to be done rather sooner than later!

**Comment by kadel** [comment]
I would actually prefer to do this as part of https://github.com/openshift/odo/pull/1840

**Comment by kadel** [comment]
fixed in #1840 
/close
