### ISSUE TITLE
ODO linking

### ISSUE THREAD

**Issue by janepelladinesh** [openshift/odo#1913]
I have  Kafka Pod, and producer and consumer-python code ,It was executing in my VM,I want to create another pods for producer code and consumer code, and it should be communicate with my kafka pod using odo ,please resolve it

**Comment by surajnarwade** [comment]
@janepelladinesh can you please provide steps to reproduce the issue

**Comment by janepelladinesh** [comment]
i had created a python flask application as a odo component ,the code consists of  kafka producer code, error is it is not connecting to my kafka pod , i want to know how to connect to external ip in openshift do ,please help

**Comment by surajnarwade** [comment]
@janepelladinesh please provide proper steps and sample code to reproduce

**Comment by janepelladinesh** [comment]
import threading, logging, time
import multiprocessing

from kafka import  KafkaProducer


class Producer(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
        self.stop_event = threading.Event()
        
    def stop(self):
        self.stop_event.set()

    def run(self):
        producer = KafkaProducer(bootstrap_servers='10.128.0.202:9092')
        producer.send('test', b"big boss season 3 contraversy started")
        time.sleep(1)

        producer.close()

        
        
def main():
    tasks = [
        Producer()
    ]

    for t in tasks:
        t.start()

    time.sleep(10)
    
    for task in tasks:
        task.stop()

    for task in tasks:
        task.join()
        
        
if __name__ == "__main__":
    logging.basicConfig(
        format='%(asctime)s.%(msecs)s:%(name)s:%(thread)d:%(levelname)s:%(process)d:%(message)s',
        level=logging.INFO
        )
    main()

**Comment by janepelladinesh** [comment]
This is the code , in the bootstrap_servers i mentioned ip address ,but it was not connected during odo push
