### ISSUE TITLE
switching directory between odo create and odo push fails

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1922]
As the sourceLocation is stored relative to the directory `odo create` is run it, when the directory is switched to run `odo push` it fails.
```
[gramnani@girish integration]$ odo create java sb-jar-test --project jxxjiebvvn --binary ../examples/binary/java/openjdk/sb.jar --context /tmp/294104207
 ✓  Validating component [4s]
Please use `odo push` command to create the component with source deployed

[gramnani@girish integration]$ cat /tmp/294104207/.odo/config.yaml 
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: ../examples/binary/java/openjdk/sb.jar
  SourceType: binary
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: app
  Project: jxxjiebvvn
  Name: sb-jar-test
--> [gramnani@girish integration]$ cd ..
[gramnani@girish tests]$ odo push --context /tmp/294104207
 ✓  Creating project jxxjiebvvn
 ✓  Successfully created project jxxjiebvvn
Validation
 ✓  Validating component [5s]
 ✓  Checking component [312ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [3s]
 ✓  Applying configuration [41320ns]

Pushing to component sb-jar-test of type binary
 ✗  open /tmp/examples/binary/java/openjdk: no such file or directory
 ```

**Comment by girishramnani** [comment]
This is happening because we store the `SourceLocation` relative to the currentDirectory where is running. This is working currently because the tests run the `odo create` and `odo push` from the same directory making currentDirectory same in both cases but in the real world that wouldn't be the case.
Hence we should make sure that `SourceLocation` is set relative to the `context` dir and hence it wont be dependent on where the user runs `odo` from.
This certainly has a down side that l`SourceLocation` of the component is case of `--local` and `--binary` will always need to be relative to `componentContext` due to this, commands like
```
odo create java sb-jar-test --project jxxjiebvvn --binary ../examples/binary/java/openjdk/sb.jar --context /tmp/294104207
```
will fail. i.e. creations in which binary location is not a child or relative to context dir will fail.
cc @kadel @jorgemoralespou @cdrage

**Comment by jorgemoralespou** [comment]
the source location has to always be sub directory of the context if binary or source. That has to be a requirement, otherwise too many problems can arise.

**Comment by girishramnani** [comment]
We have tests that doesn't follow the requirements. We need to update that
