### ISSUE TITLE
golangci-lint reports dead code, missing error checks and other issues.

### ISSUE THREAD

**Issue by alanconway** [openshift/odo#1927]
golangci-lint is a meta-linter that runs a bunch of other linting tools (lint, vet etc.) very quickly.
With default settings it catches a lot of real problems and very few false ones.
I recommend we included it in the odo build vaildation.

## Actual behavior

In root of odo repo:
```
go get github.com/golangci/golangci-lint/cmd/golangci-lint
golangci-lint run ./...
```
Prints a lot of  issues

## Expected behavior

No issues.

## Any logs, error output, etc?

[lint.txt](https://github.com/openshift/odo/files/3412381/lint.txt)

**Comment by kadel** [comment]
It might be worth to integrate golangci-lint into our CI
