### ISSUE TITLE
odo create generates relatives path making it difficult for IDE integration

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#1930]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta3 (c2b402e3)

Server: https://172.17.24.86:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

```
odo create java:8 sbcomp --project sbproject --app sbapp --context `pwd`/subdir
```
## Actual behavior

`cd subdir;odo list` 

reports `source` as `file:///./`

## Expected behavior

Source as absolute path

**Comment by girishramnani** [comment]
the source even though is relative is still correct so this should be a feature
