### ISSUE TITLE
Issue template still mentions https://chat.openshift.io/developers/channels/odo

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#1931]
[kind/Documentation]

## What did you find missing in the documentation?

The https://chat.openshift.io/developers/channels/odo mention is not valid anymore

## What is the relevance of it?

When creating an entry

**Comment by girishramnani** [comment]
Currently we haven't finalized the public channel for odo and as the coreos slack is not publicly accessible (if I am not wrong) so we cannot add that in the templates either.
cc @kadel @jorgemoralespou

**Comment by jeffmaury** [comment]
Agree but we should remove the mention to a non existing channel even if we don't have the next one

**Comment by girishramnani** [comment]
Sure, makes sense

**Comment by girishramnani** [comment]
we currently have a google group for questions https://groups.google.com/a/redhat.com/forum/#!forum/devtools-odo, I will add that instead
