### ISSUE TITLE
Debug support proposal

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#1934]
[kind/Feature]

## Which functionality do you think we should add?

One very important feature is the debug support.

## Why is this needed?

Because we always debug !!!!

## Proposal

As requested by @veillard, I'm starting the discussion based on the JBoss Tools experience.
Comments are welcomed.

In order to be able to debug, the underlying container must be started in a specific way so that the debug port is activated and that third party tools (IDE,...) could connect.
So I thing we could have two commands:

- `odo debug start`
- `odo debug stop`

### odo debug start

This will restart the container in debug mode if not already in this mode. The debug port must be returned and an `oc forward` will be started so that third party tools can connect to the port on `localhost`
Please not that JBoss Tools uses two environment variables to do that, and the name and values are extracted from the labels of the builder images

### odo debug stop

If the component is in debug mode, restart it in normal mode and stop the running `oc forward`

@kadel @veillard @dgolovin @mohitsuman @adietish feel free to comment

**Comment by sspeiche** [comment]
Think this is a dup of https://github.com/openshift/odo/issues/822

**Comment by girishramnani** [comment]
This issue outlines a proposal to implement #822. We can keep that as a separate issue or directly on #822.

**Comment by kadel** [comment]
@jeffmaury I've just tried to describe how this could work in a proposal document. Can you please check and review it in https://github.com/openshift/odo/pull/1995?

**Comment by kadel** [comment]
I'm closing this one in favor of #822 so we don't split the discussion.

/close
