### ISSUE TITLE
 Implement `--wait` flag for `odo storage delete`

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1942]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Add `--wait` flag in `odo storage delete` similar to `odo project create`

## Why is this needed? 

Reference: `waitForStorageToBeGone` from https://github.com/openshift/odo/issues/1739

as of now, vscode plugin relies on,

```
oc wait pvc/${storage}-${app}-pvc --for=delete --namespace ${project}
```

**Comment by girishramnani** [comment]
@kadel cannot assign this issue to @drichtarik

**Comment by girishramnani** [comment]
as part of new workflow `odo storage delete` now requires `odo push` after it which means having `--wait` flag for it `odo storage delete` isn't required. Hence closing this issue.
