### ISSUE TITLE
Check closed issues in 1.0 milestone and add need-docs label

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1944]
https://github.com/openshift/odo/milestone/8?closed=1

Go through closed issues and mark the ones which needs the docs?
For example, if there is a new flag that needs documentation than the issue should have `need-docs` label etc...

This will help docs team to plan their work.

**Comment by cdrage** [comment]
I've gone through all the issues and re-opened the ones I find necessary. Just cases of missing documentation!
