### ISSUE TITLE
Adding machine readable structs for `service list`

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1945]
* Add machine readable struct for `service` 
* add machine readable output for `odo service list`

**Comment by surajnarwade** [comment]
sub-issue for #1739

**Comment by surajnarwade** [comment]
PR is [here](https://github.com/openshift/odo/pull/1938)

**Comment by cdrage** [comment]
The issue for `service create` and `service delete` is located here: https://github.com/openshift/odo/issues/2076

**Comment by cdrage** [comment]
https://github.com/openshift/odo/pull/2098 has been merged. Closing
