### ISSUE TITLE
How to properly build odo-supervisord-image without binary blobs.

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1950]
[odo-supervisord-image](https://github.com/openshift/odo-supervisord-image) is a container image that odo uses to inject [SupervisorD](https://github.com/ochinchina/supervisord/), [dumb-init](https://github.com/Yelp/dumb-init) and few our bash scripts into the builder image.

Both [SupervisorD](https://github.com/ochinchina/supervisord/) and [dumb-init](https://github.com/Yelp/dumb-init) are added to the image as binaries downloaded from GitHub. ([Dockerfile line 10](https://github.com/openshift/odo-supervisord-image/blob/fad79ae18dc56776aed2be0480b48e3d43178cdf/Dockerfile#L10), [Dockerfile line 19](https://github.com/openshift/odo-supervisord-image/blob/fad79ae18dc56776aed2be0480b48e3d43178cdf/Dockerfile#L19))

We probably need some clean and safe way to do this that doesn't involve downloading random binaries from the internet.

cc: @amitkrout @mohammedzee1000 @sspeiche @oskutka 

/milestone 1.0
/priority high

**Comment by mohammedzee1000** [comment]
We should have ubi once https://github.com/openshift/odo-supervisord-image/pull/25 goes in but yes, binaries will be an issue.

The safest bet is to try to get someone to package the bits we need(the version that we need) for centos and rhel. But that will involve a fair amount of work outside of odo itself but should mean no change in the image other than installing as rpm. 

We already have rpm packages for both so maybe contact maintainers to see if they can help?

Any other way will entail the maintenance of a separate rhel dockerfile -> separate container built internally thereby requiring odo to refer appropriate supervisor image.

Another thing we can do is to have an `internal repository`, for example, may be an ftp server, which has the bits we need to be updated from the internet only after some sort of validation and then of course as mentioned above, maintain them as separate containers, unless we can get to a method other than rpms, where we dont have to update any references.

**Comment by mohammedzee1000** [comment]
Looking at building this image from this single repo somehow

**Comment by girishramnani** [comment]
I think this is the PR https://github.com/openshift/odo-supervisord-image/pull/26

**Comment by kadel** [comment]
/close
done in https://github.com/openshift/odo-init-image/pull/26
