### ISSUE TITLE
odo fails to login to 3.11 cluster on psi whereas oc login works as expected

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1953]
[kind/bug]

## What versions of software are you using?
- Operating System: Tested on macOS
- Output of `odo version`: master

## How did you run odo exactly?

1. Connected to redhat vpn
2. Configured Dns to send request to `*.ocp311.odo`
3. odo login ...
```
$ odo login --insecure-skip-tls-verify -u <username> -p <password> https://<part of url>.odo:8443
Connecting to the OpenShift cluster

 ✗  dial tcp: lookup <part of url>.odo: no such host - verify you have provided the correct host and port and that the server is currently running.
```
```
$ oc login --insecure-skip-tls-verify -u <username> -p <password> https://<part of url>.odo:8443
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
```

## Actual behavior
See the issue title

## Expected behavior
Should login to the cluster. It seems odo login does not work the way oc does.

## Any logs, error output, etc?

Some more observation
```
$ oc login --insecure-skip-tls-verify -u <username> -p <password> https://<part of url>.odo:8443
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

$ odo project list
 ✗  Unable to connect to OpenShift cluster, is it down?
```

**Comment by amitkrout** [comment]
ping @kadel @mohammedzee1000

**Comment by amitkrout** [comment]
Login does not work even after setting the preference ```Timeout``` to 40
```
$ odo preference set Timeout 40
? Timeout is already set. Do you want to override it in the config Yes
Global preference was successfully updated.
$ odo project list
 ✗  Unable to connect to OpenShift cluster, is it down?
```

**Comment by kadel** [comment]
This looks like something that is specific to our cluster setup. mainly to the way how DNS is configured.



/remove-priority critical
/priority high

**Comment by amitkrout** [comment]
This issue blocks odo on psi platform

**Comment by girishramnani** [comment]
I feel the way `oc` resolves DNS is different then ours. maybe `odo` is not considering the system wide dns configurations?

**Comment by amitkrout** [comment]
@mik-dass Plese follow the steps as suggested through 1-1 slak chat

**Comment by mik-dass** [comment]
@amitkrout I did but I still can't login

**Comment by mik-dass** [comment]
@amitkrout @kadel This seems to be a network issue according to me. I wasn't able to reproduce it on the office VPN with the latest `odo` binary but on the WiFi, I was constantly hitting the issue and wasn't able to connect to the cluster at all.

**Comment by amitkrout** [comment]
> @amitkrout @kadel This seems to be a network issue according to me. I wasn't able to reproduce it on the office VPN with the latest odo binary

@mik-dass On fedora i can run odo and oc login successfully over a wifi network. I think there is something that ```oc login``` handles smartly with respect to network configuration where as odo doesn't. @kadel and team, If you have a macOS host then can you please try it   

> but on the WiFi, I was constantly hitting the issue and wasn't able to connect to the cluster at all even with the oc binary.

This could be a network issue i guess. Can you please paste the exact error message that are displayed in the terminal.

**Comment by mik-dass** [comment]
> This could be a network issue i guess. Can you please paste the exact error message that are displayed in the terminal.

Here are the logs
```
[mrinaldas@localhost ~]$ oc login --insecure-skip-tls-verify -u mzee1000 -p password@123 https://console.ocp311.odo:8443
error: dial tcp: lookup console.ocp311.odo on 10.208.0.246:53: no such host - verify you have provided the correct host and port and that the server is currently running.
```

**Comment by amitkrout** [comment]
> > This could be a network issue i guess. Can you please paste the exact error message that are displayed in the terminal.
> 
> Here are the logs
> 
> ```
> [mrinaldas@localhost ~]$ oc login --insecure-skip-tls-verify -u mzee1000 -p password@123 https://console.ocp311.odo:8443
> error: dial tcp: lookup console.ocp311.odo on 10.208.0.246:53: no such host - verify you have provided the correct host and port and that the server is currently running.
> ```

@mik-dass Ideally it should search on 10.0.*.* for console.ocp311.odo. Can you add the suggested nameserver just below the ```search ocp311.odo``` and give a try.

**Comment by kadel** [comment]
@amitkrout can you post verbose log to see where it fails?

**Comment by amitkrout** [comment]
@kadel @mik-dass 
```
$ odo login --insecure-skip-tls-verify -u arout -p password@123 https://console.ocp311.odo:8443 -v4
Connecting to the OpenShift cluster

I0813 17:56:44.665642   39553 cmdutils.go:26] Error:
dial tcp: lookup console.ocp311.odo: no such host - verify you have provided the correct host and port and that the server is currently running.
 ✗  dial tcp: lookup console.ocp311.odo: no such host - verify you have provided the correct host and port and that the server is currently running.
```

**Comment by mik-dass** [comment]
@amitkrout 
```
oc login --insecure-skip-tls-verify -u <username> -p <password> https://console.ocp311.odo:8443
error: dial tcp: lookup console.ocp311.odo on 10.0.78.147:53: read udp 10.215.98.38:43809->10.0.78.147:53: i/o timeout - verify you have provided the correct host and port and that the server is currently running.
```
even after adding the suggested parameters in the resolv.conf

Are you using the VPN on your home WiFi? What's the result when you turn off the VPN?

**Comment by amitkrout** [comment]
> @amitkrout
> 
> ```
> oc login --insecure-skip-tls-verify -u <username> -p <password> https://console.ocp311.odo:8443
> error: dial tcp: lookup console.ocp311.odo on 10.0.78.147:53: read udp 10.215.98.38:43809->10.0.78.147:53: i/o timeout - verify you have provided the correct host and port and that the server is currently running.
> ```
> 
> even after adding the suggested parameters in the resolv.conf
> 
> Are you using the VPN on your home WiFi? What's the result when you turn off the VPN?

@mik-dass Make sure that you are connected to the vpn while using wifi

**Comment by mik-dass** [comment]
> @mik-dass Make sure that you are connected to the vpn while using redhat guest wifi network

So I guess this doesn't work outside red hat networks?

**Comment by kadel** [comment]
/unassign @mik-dass 
/triage not-reproducible
/close

This is something that is just specific to the DNS setup for our testing cluster.
We can reopen it if we verify that the weird dns setup is not to blame here.
