### ISSUE TITLE
Add server version for OpenShift 4.x clusters

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#1957]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

`odo version` should point out server version for cluster in OpenShift 4.x.

## Why is this needed? 
 Currently for OpenShift 3.x, `odo version` prompts the server version correctly. But in case of OpenShift 4.x, the server version is missing. This might be as `oc` also does not points the server version for OpenShift 4.x

**Comment by surajnarwade** [comment]
```
$ odo version
odo v1.0.0-beta3 (HEAD)

Server: https://api.ci-ln-hbtnvhk-d5d6b.origin-ci-int-aws.dev.rhcloud.com:6443
Kubernetes: v1.14.0+4d9f17e
```

works for me though

```
$ oc version
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.ci-ln-hbtnvhk-d5d6b.origin-ci-int-aws.dev.rhcloud.com:6443
kubernetes v1.14.0+4d9f17e
```

**Comment by sudhirverma** [comment]
`odo version` does't give the output for cluster Url and cluster version for 4.x cluster.

```
Sudhirs-MacBook-Pro:~ sudhirverma$ .vs-openshift/odo version
odo v1.0.0 (4e3175e6f)

Server: https://api.crc.testing:6443
Kubernetes: v1.14.6+2e5ed54
```
