### ISSUE TITLE
Binary wildfly component does not deployed correctly

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1967]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10 Pro
- Output of `odo version`: locally built from master `odo v1.0.0-beta3 (dd181e65)`

## How did you run odo exactly?
```
"C:\Users\dgolo\.vs-openshift\odo.exe" create wildfly:latest hello1 --binary c:\p\quickstart\helloworld\target\helloworld.war --app app1 --project myproject
V  Validating component [91ms]
Please use `odo push` command to create the component with source deployed
"C:\Users\dgolo\.vs-openshift\odo.exe" push
Validation
 V  Checking component [16ms]

Configuration changes
 V  Applying configuration [46ms]

Applying URL changes
 V  URL url2: http://url2-app1-myproject.192.168.94.220.nip.io created

Pushing to component hello1 of type binary
 V  Checking file changes for pushing [0ns]
 V  No file changes detected, skipping build. Use the '-f' flag to force the build.
```

## Actual behavior
Opening url2 shows default Wildfly page
![image](https://user-images.githubusercontent.com/620330/62194382-9cad9580-b32e-11e9-85f7-afdaa3b2ed01.png)

## Expected behavior
Opening url2 shows webapp deployed form war file

## Any logs, error output, etc?
N/A

**Comment by mik-dass** [comment]
@dgolovin Can please point to location of the war file you are using?

**Comment by dgolovin** [comment]
@mik-dass It is built from https://github.com/wildfly/quickstart/tree/master/helloworld.

**Comment by dgolovin** [comment]
@mik-dass it works with latest build from master, the problem is I have to add /helloworld to url to see deployed app. Closing.
