### ISSUE TITLE
--binary flag doesn't work without --context flag while creating component

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1969]
[kind/bug]

## What versions of software are you using?
- Operating System: Supported
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo component create wildfly:latest wildfly --binary /Users/amit/go/src/github.com/openshift/odo/tests/examples/binary/java/wildfly/ROOT.war --app app1 --project myproject
 ✗  Rel: can't make /Users/amit/go/src/github.com/openshift/odo/tests/examples/binary/java/wildfly/ROOT.war relative to
```

## Actual behavior
See how to run section

## Expected behavior
--binary flag should not depend on --context flag

**EDIT:** --binary flag should not always depend on --context flag. For example creating a binary component in the working dir should not explicitly look for context flag. cc_ @kadel @girishramnani

**Comment by amitkrout** [comment]
ping @girishramnani cc_ @kadel

**Comment by dgolovin** [comment]
It does not work with `--context .` and shows similar error message, except it says `......relative to .`.
Workaround is simply copying binary file into context folder and use relative name `./ROOT.war`.

**Comment by amitkrout** [comment]
> It does not work with `--context .` and shows similar error message, except it says `......relative to .`.
> Workaround is simply copying binary file into context folder and use relative name `./ROOT.war`.

+1, @dgolovin Also as a workaround you can use the absolute path in flag ```--context``` along with the ```--binary``` flag. For example
```
odo component create wildfly:latest wildfly --binary /Users/amit/go/src/github.com/openshift/odo/tests/examples/binary/java/wildfly/ROOT.war --app app --project myproject --context /Users/amit/go/src/github.com/openshift/odo/tests/examples/binary/java/wildfly/
```

**Comment by kadel** [comment]
> --binary flag should not depend on --context flag

This is not how it supposed to work.

Each component has the base folder (context directory) even binary one.

Let's say that I have my component in `/home/tomas/AwesomeProject` and binary artifact is in `/home/tomas/AwesomeProject/target/AwesomeProject.jar`

I should run `odo component create java --context /home/tomas/AwesomeProject --binary target/AwesomeProject.jar` or just `odo component create  --binary target/AwesomeProject.jar` if my current directory is `/home/tomas/AwesomeProject`

**Comment by amitkrout** [comment]
> Let's say that I have my component in ```/home/tomas/AwesomeProject``` and binary artifact is in ```/home/tomas/AwesomeProject/target/AwesomeProject.jar```
I should run ```odo component create java --context /home/tomas/AwesomeProject --binary target/AwesomeProject.jar```

Agree, this is true

> ... or odo component create --binary target/AwesomeProject.jar if my current directory is /home/tomas/AwesomeProject

@kadel But this is throwing error for example
```
✗  Rel: can't make /Users/amit/go/src/github.com/openshift/odo/tests/examples/binary/java/wildfly/ROOT.war 
relative to
```

**Comment by girishramnani** [comment]
the binary must be relative to context
