### ISSUE TITLE
Creating odo project prompts / output from logging in the wrong section.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1970]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

See screenshot. The creating odo component should be under "validation".

![Screenshot from 2019-07-31 12-29-20](https://user-images.githubusercontent.com/6422176/62230052-fd6cba80-b38e-11e9-841d-38a976ac0310.png)

## Why is this needed? 

Better UX / UI

**Comment by kadel** [comment]
Not sure about this.

How is component creation related to validation?

**Comment by girishramnani** [comment]
+1 to @kadel . Component creation shouldn't be part of validation. 
Closing this issue for now :slightly_smiling_face: .
