### ISSUE TITLE
context and component name seems confusing

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#1976]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta3 (c2b402e3)

Server: https://192.168.237.226:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

First created a component from a folder.

Then went one level up in the folder hierarchy: `cd ..`

Tried to create a storage:

```
$ odo storage create st1 --path /mnt2 --size 1Gi --context comp4 --component comp4 --project demoproj --app demoapp
 X  Component comp4 does not exist in application demoapp
```

Tried the same but removing the component name:

```
$ odo storage create st1 --path /mnt2 --size 1Gi --context comp4 --project demoproj --app demoapp
 V  Added storage st1 to comp4
```

## Actual behavior

Error is component name is provided

## Expected behavior

Should accept it

**Comment by amitkrout** [comment]
@jeffmaury This is expect because in your case no component is deployed in the cluster. You can first push the component then only you can create the storage with the specified component.

**Comment by amitkrout** [comment]
Feel free to re open the issue if you are not convinced with my https://github.com/openshift/odo/issues/1976#issuecomment-517579491

@mik-dass ^
