### ISSUE TITLE
Reminder for release notes: No backwards compatibility with new labels.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#1977]
[kind/Documentation]

## What did you find missing in the documentation?

This is a reminder that when https://github.com/openshift/odo/pull/1959 is merged that we should release some notes regards the removal of backwards compatibility with old labels.

## What is the relevance of it?

No backwards compatibility going forward.

**Comment by kadel** [comment]
this was mentioned in release notes for beta4 -https://github.com/openshift/odo/releases/tag/v1.0.0-beta4
/close
