### ISSUE TITLE
Provide a way to figure out the OpenShift server version, whether 3.x or 4.x

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#1979]
[kind/Feature]

## Which functionality do you think we should add?
I am finding it tricky to figure out the OpenShift server version whether it is `3.x` or `4.x`. 

Right now the only thing we get is the server url from `odo version`/ `oc version`.

## Why is this needed?

This will help for adapters to understand the server version and based on that decide the OpenShift web console URL.

For 3.x server, the web console URL does not use route and can be figured out using:
`{server_Url}/console`.
But for 4.x server, the web console URL goes through routes using operators and can be determined using the following:
`oc get routes -n openshift-console -ojson | jq '.items[0].spec.host'`

**Comment by girishramnani** [comment]
If I remember correctly this was resolved on vs code plugin side already? @mohitsuman .
Closing for now, please re-open this issue if it's not yet resolved :slightly_smiling_face:
