### ISSUE TITLE
odo log dumps for supportability

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1980]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
pass/fail log dumps

## Why is this needed? 
To collect all related log that causes failure even from container/api level and archive all those logs to make it portable.

**Comment by amitkrout** [comment]
ping @kadel 
Please feel free to share your thoughts.

**Comment by girishramnani** [comment]
can you elaborate more on this @amitkrout , as we planning to index these logs in a something like ELK or store it somewhere for analysis?

**Comment by girishramnani** [comment]
In my opinion, I dont feel we will be doing anything related to telemetry for next 6 months? hence closing this issue for now.
