### ISSUE TITLE
[Flake] Failed to update config to git component deployed

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1981]
[kind/bug]

## What versions of software are you using?
- Operating System: OpenShift CI
- Output of `odo version`: pr run

## How did you run odo exactly?
Run pr (on two test node) in OpenShift CI. I have seen this even on single test node.  

## Actual behavior
Flakey

## Expected behavior
Should not be flakey 

## Any logs, error output, etc?

Reference  - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/1920/pull-ci-openshift-odo-master-integration/1126

**Comment by amitkrout** [comment]
Same error i can reproduce it on my local setup on the cluster of 3.x that i have been using since 2 days, however on a fresh cluster the chance of hitting the issue is very less (1 out of 10).

Same observation i can find on 4.* cluster on aws too.

**Comment by amitkrout** [comment]
Some more same failure in CI - https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/2001/pull-ci-openshift-odo-master-integration/1241/build-log.txt

**Comment by amitkrout** [comment]
Reproduced in CI - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/1954/pull-ci-openshift-odo-master-integration/1061
```
odoURLIntegration Listing urls 
  should list appropriate URLs and push message
  /go/src/github.com/openshift/odo/tests/integration/url_test.go:41
 Created dir: /tmp/475069174
Creating a new project: qllqkgdnzd
Running odo with args: [project create qllqkgdnzd -w -v4] 
[odo] I0730 05:19:17.632597   31253 preference.go:116] The configFile is /tmp/475069174/config.yaml
[odo] I0730 05:19:17.632680   31253 occlient.go:486] Trying to connect to server api.ci-op-mvjt0q5q-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443
[odo] I0730 05:19:17.651839   31253 occlient.go:493] Server https://api.ci-op-mvjt0q5q-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443 is up
[odo] I0730 05:19:17.754536   31253 occlient.go:416] isLoggedIn err:  <nil> 
[odo]  output: "developer"
[odo] I0730 05:19:17.754579   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: context
[odo] I0730 05:19:17.754591   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: context
[odo] I0730 05:19:17.754648   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: app
[odo] I0730 05:19:17.754663   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: project
[odo] I0730 05:19:17.789847   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: app
[odo] I0730 05:19:17.789873   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: output
[odo] I0730 05:19:17.789878   31253 context.go:367] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
[odo]  •  Waiting for project to come up  ...
[odo]  ✓  Waiting for project to come up [492ms]
[odo]  ✓  Project 'qllqkgdnzd' is ready for use
[odo]  ✓  New project created and now using project : qllqkgdnzd
[odo] I0730 05:19:18.291503   31253 odo.go:70] Could not get the latest release information in time. Never mind, exiting gracefully :)
Running odo with args: [create nodejs --context /tmp/475069174 --project qllqkgdnzd zthnim --ref master --git https://github.com/openshift/nodejs-ex --port 8080,8000] 
[odo]  •  Validating component  ...
[odo]  ✓  Validating component [61ms]
[odo] Please use `odo push` command to create the component with source deployed
[odo] 
Running odo with args: [push --context /tmp/475069174] 
[odo] Validation
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [100ms]
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [34ms]
[odo] 
[odo] Configuration changes
[odo]  •  Creating component  ...
[odo]  ✓  Initializing component
[odo]  •  Triggering build from git  ...
[odo]  ✓  Triggering build from git [121ms]
[odo]  •  Waiting for build to finish  ...
[odo]  ✓  Waiting for build to finish [2m]
[odo]  •  Deploying component zthnim  ...
[odo]  ✓  Deploying component zthnim [18s]
[odo]  ✓  Creating component [2m]
[odo]  •  Applying configuration  ...
[odo]  ✓  Applying configuration [12215ns]
[odo] 
[odo] Pushing to component zthnim of type git
[odo]  ✓  Changes successfully pushed to component
Running odo with args: [url list --context /tmp/475069174] 
[odo]  ✗  no URLs found for component zthnim in application app
Running odo with args: [url create laulo --port 8080 --context /tmp/475069174] 
[odo]  ✓  URL laulo created for component: zthnim
[odo] 
[odo] To create URL on the OpenShift Cluster, please use `odo push` 
Running odo with args: [url list --context /tmp/475069174] 
[odo] Found the following URLs for component zthnim in application app:
[odo] NAME      IN CONFIG     URL                          PORT
[odo] laulo     Present       <not created on cluster>     8080
[odo] To create URLs on the OpenShift Cluster, please use `odo push` 
Running odo with args: [push --context /tmp/475069174] 
[odo] Validation
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [199ms]
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [27ms]
[odo] 
[odo] Configuration changes
[odo]  •  Applying configuration  ...
[odo]  •  Triggering build from git  ...
[odo]  ✓  Triggering build from git [327ms]
[odo]  •  Waiting for build to finish  ...
[odo]  ✓  Waiting for build to finish [1m]
[odo]  ✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [1m]
Deleting project: qllqkgdnzd
Running odo with args: [project delete qllqkgdnzd -f] 
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named zthnim
[odo] No services / could not get services
[odo]  •  Deleting project qllqkgdnzd  ...
[odo]  ✓  Deleting project qllqkgdnzd [6s]
[odo] Deleted project : qllqkgdnzd
Deleting dir: /tmp/475069174
 • Failure [206.767 seconds]
odoURLIntegration
/go/src/github.com/openshift/odo/tests/integration/url_test.go:13
  Listing urls
  /go/src/github.com/openshift/odo/tests/integration/url_test.go:40
    should list appropriate URLs and push message [It]
    /go/src/github.com/openshift/odo/tests/integration/url_test.go:41
     No future change is possible.  Bailing out early after 87.915s.
      
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
     /go/src/github.com/openshift/odo/tests/helper/helper_run.go:29
```

**Comment by mik-dass** [comment]
@amitkrout This might be the underlying cause

```
✗  Waiting for build to finish [30s]
 ✗  Applying configuration [33s]
I0814 13:00:16.602706   13009 cmdutils.go:26] Error:
unable to build the component nodejs-nodejs-ex-ayat: unable to follow logs for nodejs-nodejs-ex-ayat-app-1: unable get build log nodejs-nodejs-ex-ayat-app-1: unable to wait for build nodejs-nodejs-ex-ayat-app-1 to run: timed out waiting for the condition
 ✗  Failed To Update Config To Component Deployed
```

**Comment by kadel** [comment]
Are we getting any closer to resolving this? 

I found another instance of this in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2053/pull-ci-openshift-odo-master-integration/1440  (https://github.com/openshift/odo/pull/2053)

**Comment by amitkrout** [comment]
> @amitkrout This might be the underlying cause
> 
> ```
> ✗  Waiting for build to finish [30s]
>  ✗  Applying configuration [33s]
> I0814 13:00:16.602706   13009 cmdutils.go:26] Error:
> unable to build the component nodejs-nodejs-ex-ayat: unable to follow logs for nodejs-nodejs-ex-ayat-app-1: unable get build log nodejs-nodejs-ex-ayat-app-1: unable to wait for build nodejs-nodejs-ex-ayat-app-1 to run: timed out waiting for the condition
>  ✗  Failed To Update Config To Component Deployed
> ```

Not always, even after successful build the same error appears 
```
[odo]  ✓  Waiting for build to finish [50s]
[odo]  ✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [50s]
```

**Comment by amitkrout** [comment]
@mik-dass I am seeing this issue consistently on latest 4.2 OpenShift nightly build. IMO this is no more a flake as on 4.2 nightly build the failure rate is 100%. 

Can you please take this issue on high priority basis

**Comment by mik-dass** [comment]
@amitkrout https://github.com/openshift/odo/pull/2016#issuecomment-532100708 not sure if this is the same issue as this but this is what I have discovered till now. I am constantly hitting this issue on a 4.2 cluster. Please share the logs of the failures.

**Comment by amitkrout** [comment]
> @amitkrout [#2016 (comment)](https://github.com/openshift/odo/pull/2016#issuecomment-532100708) not sure if it is the same issue as this but this is what I have discovered till now. I am constantly hitting this issue on a 4.2 cluster. Please share the logs of the failures.

It is the same error https://github.com/openshift/odo/pull/2016#issuecomment-532100708. However running the push again successfully pushes the changes to the component.

**Comment by mik-dass** [comment]
> However running the push again successfully pushes the changes to the component.

Yes I am seen this same behavior too

**Comment by amitkrout** [comment]
@mik-dass The issue is still persist. It seems you need some more luck in triage this ;), pr #2167 doesn't help atm.

**Comment by mik-dass** [comment]
> @mik-dass The issue is still persist. It seems you need some more luck in triage this ;), pr #2167 doesn't help atm.

Please point me to the logs

**Comment by amitkrout** [comment]
> > @mik-dass The issue is still persist. It seems you need some more luck in triage this ;), pr #2167 doesn't help atm.
> 
> Please point me to the logs

@mik-dass You can find the logs from the above references. Or you can go to the pr history and there you need to find out such failure logs

**Comment by kadel** [comment]
@amitkrout what reference? you just pointed to #2167  where all the test passed

**Comment by mik-dass** [comment]
https://github.com/openshift/odo/pull/2271#issuecomment-540949830

Looking at the logs, it seems to time out after 5 min
```
[odo]  ✗  Applying configuration [5m]
[odo]  ✗  Failed To Update Config To Component Deployed
```
That is the timeout time for the WaitAndGetDC() function https://github.com/openshift/odo/blob/599683da41194b64b3ec98e187300bef7701b23a/pkg/occlient/occlient.go#L91. So I believe it is a timeout issue while waiting for the DC.

**Comment by mik-dass** [comment]
https://travis-ci.com/openshift/odo/jobs/258102894#L932

Here the problem occurred in the function FollowBuildLog() while setting up the RestClient
