### ISSUE TITLE
Mark supported and unsupported images builder images

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1984]
Not every s2i image will be fully supported by odo.
Two main problems that currently don't have a generic solution:
- Debug #822 - this won't work for every s2i builder image
- File deletions - https://github.com/openshift/odo/issues/1354. assemble scripts in some images are moving or copying files.

Odo should inform the user about what images are fully supported and which are not

Images that fully support odo "out of the box":
- "redhat-openjdk-18/openjdk18-openshift"
- "openjdk/openjdk-11-rhel8"
- "openjdk/openjdk-11-rhel7"

Images that fully support odo after https://github.com/openshift/odo-supervisord-image/pull/27 is merged
- "rhscl/nodejs-8-rhel7"
- "rhoar-nodejs/nodejs-8"
- "rhoar-nodejs/nodejs-10"

```
▶ odo catalog list components
Component types fully supported in odo (including debugging capabilities):
NAME              PROJECT       TAGS
nodejs            openshift     10,8,8-RHOAR,latest
java              openshift     11,8,latest


Component types without full odo support:
NAME              PROJECT       TAGS
dotnet            openshift     2.1,2.2,latest
golang            openshift     1.11.5,latest
httpd             openshift     2.4,latest
modern-webapp     openshift     10.x,latest
nginx             openshift     1.10,1.12,latest
perl              openshift     5.24,5.26,latest
php               openshift     7.0,7.1,7.2,latest
python            openshift     2.7,3.6,latest
ruby              openshift     2.4,2.5,latest
```

```
 $ odo create java 
 ✓  Validating component [90ms]
 ✓  java is fully supported by odo
Please use `odo push` command to create the component with source deployed
```

```
 $ odo create nginx 
 ✓  Validating component [90ms]
 Warning:  nginx is not fully supported by odo, and it is not guaranteed to work.
           Advanced commands like `odo debug` are not going to work.
 Please use `odo push` command to create the component with source deployed
```

**Comment by girishramnani** [comment]
One of the ways I feel this could be done is to add `HasDebug` flag in the `CatalogImage`  struct https://github.com/openshift/odo/blob/9276486fc6f9671900a69c1ce6729180b0130827/pkg/catalog/catalog.go#L13 
and then just augment the output to list them separately.

**Comment by girishramnani** [comment]
consider using the flag called `FullSupport`

**Comment by girishramnani** [comment]
if the image `rhoar-nodejs/nodejs-10` is fully supported by odo then does that mean all of its tags are supported?

or we wanna specify even the tags that are supported?

**Comment by girishramnani** [comment]
the catalog images returns only the name of the component not the image url
 https://github.com/openshift/odo/blob/64f9db2e17df9c7b04ec5e8d9d27147c280f628d/vendor/github.com/openshift/api/image/v1/types.go#L235
shows the reference for the image

**Comment by girishramnani** [comment]
but it can be of multiple types and so I wanted to know is there a better way to get the image names

**Comment by kadel** [comment]
Each image has a label called `name`. The list of the names in issue description comes to form this label.

**Comment by girishramnani** [comment]
so after digging around a lot - this is the information for `nodejs` image 
```
nodejs
         &ObjectReference{Kind:DockerImage,Namespace:,Name:registry.redhat.io/openshift3/nodejs-010-rhel7:latest,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
         &ObjectReference{Kind:DockerImage,Namespace:,Name:registry.redhat.io/rhoar-nodejs/nodejs-10,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
         &ObjectReference{Kind:DockerImage,Namespace:,Name:registry.redhat.io/rhscl/nodejs-4-rhel7:latest,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
         &ObjectReference{Kind:DockerImage,Namespace:,Name:registry.redhat.io/rhscl/nodejs-6-rhel7:latest,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
         &ObjectReference{Kind:DockerImage,Namespace:,Name:registry.redhat.io/rhscl/nodejs-8-rhel7:latest,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
         &ObjectReference{Kind:DockerImage,Namespace:,Name:registry.redhat.io/rhoar-nodejs/nodejs-8,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
    &ObjectReference{Kind:ImageStreamTag,Namespace:,Name:10,UID:,APIVersion:,ResourceVersion:,FieldPath:,} 
Non Hidden Tags:  [10 6 8 8-RHOAR latest]
```
Now it can be observed that each tag has a different image associated with it. which means that if only the image `hoar-nodejs/nodejs-8` is fully supported then the output of the command should be

```
▶ odo catalog list components
Component types fully supported in odo (including debugging capabilities):
NAME              PROJECT       TAGS
nodejs            openshift     8-RHOAR
java              openshift     11,8,latest


Component types without full odo support:
NAME              PROJECT       TAGS
nodejs            openshift     <other tags>
dotnet            openshift     2.1,2.2,latest
golang            openshift     1.11.5,latest
httpd             openshift     2.4,latest
modern-webapp     openshift     10.x,latest
nginx             openshift     1.10,1.12,latest
perl              openshift     5.24,5.26,latest
php               openshift     7.0,7.1,7.2,latest
python            openshift     2.7,3.6,latest
ruby              openshift     2.4,2.5,latest
```

**Comment by kadel** [comment]
You are not looking at the right Name.
Check `occlient.GetS2IMetaInfoFromBuilderImg` function. This function is already extracting some informatino from container image labels.

**Comment by girishramnani** [comment]
closing this as part this left in this issue has been recorded and tracked in this issue https://github.com/openshift/odo/issues/2156
