### ISSUE TITLE
"odo service create" should fail without logging anything else when a service with same name already exists in the cluster

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1989]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora (but I doubt all)
- Output of `odo version`: `master`

## How did you run odo exactly?
- Created a service with `odo service create dh-prometheus-apb --plan ephemeral` and deleted it before it got provisioned using `odo service delete`.
- Faced and reported #1988 
- Tried to create service with same command as earlier: `$ odo service create dh-prometheus-apb --plan ephemeral`

## Actual behavior
- When trying to create the service again, `odo` initially shows the messages that:
  - Creating service
  - Service was created
- But then it thinks that the service with same name already exists in the environment so it fails with:
  ```sh
  $ odo service create dh-prometheus-apb --plan ephemeral --app myapp
   ✓  Creating service [6ms]
   ✓  Service 'dh-prometheus-apb' was created
  Progress of the provisioning will not be reported and might take a long time.
  You can see the current status by executing 'odo service list'
   ✗  object is being deleted: serviceinstances.servicecatalog.k8s.io "dh-prometheus-apb" already exists
  ```

## Expected behavior
`odo` should fail immediately with the error message without printing earlier messages:
```sh
$ odo service create dh-prometheus-apb --plan ephemeral --app myapp
✗  object is being deleted: serviceinstances.servicecatalog.k8s.io "dh-prometheus-apb" already exists
```

**Comment by girishramnani** [comment]
a consideration for `odo service delete --wait` here could also be done which waits till the service is deprovisioned?
