### ISSUE TITLE
Change release format from gzip to tar gz.

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/odo#1994]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

release format change from gzip to tar.gz

## Why is this needed? 

Currrently we are using the ansible module unarchive to process the needed binaries downloaded from mirror.openshift.com. The other binaries are released as tar.gz archives and the Ansible module handles this wel, but gzip is not something that is support. Could you make the release archive more uniform with the other binaries like openshift-client tools and openshift-install.

**Comment by kadel** [comment]
We  use `.gz` extension as tar is not used, it is just a single file that is compressed.
I guess that openshift-client and openshift-install have more than one file in their archive, so tar is used there.

**Comment by Rikbruggink** [comment]
openshift-install is also a one binary file. i understand the choice for ```gz```, but it is more uniform seeing the rest of the openshift binaries to use ```tar.gz``` even it is only a single file

**Comment by kadel** [comment]
ok, we will change it
