### ISSUE TITLE
add odo debug info command

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2015]
parent #822
debug proposal in #1995

#### `odo debug info`
Informs the user if the debug mode is enabled for the component and if the port-forward process is running or not, and information about ports used.

**Comment by sbouchet** [comment]
@kadel , i'm currently implementing https://github.com/redhat-developer/intellij-openshift-connector/issues/72 and i would like to use this command to interact with odo to know if the current component is already running in debug mode. this would help a lot to have such info.

**Comment by kadel** [comment]
@sbouchet Is ti something that you will be working on this current sprint?
It might be problematic and hacky for you to implement redhat-developer/intellij-openshift-connector#72 without odo first adding `odo debug info` command.

**Comment by jeffmaury** [comment]
We plan to release next version with debug features, same for VSCode OpenShift Connector (@dgolovin). When do you think this will be added to odo otherwise we will implement external odo debug info based on the presence or not of the local port.

**Comment by sbouchet** [comment]
@kadel actual implementation/testing is not using odo debug info for now, only workarounds.

**Comment by kadel** [comment]
I'm would be careful with workarounds. `odo debug` is still an experimental feature, and a lot can change there.

**Comment by jeffmaury** [comment]
The workaround will be use will be independant of odo implementation. Before we start `odo debug port-forward`, we will check if the local port (that we allocate ourselves) is available or not (we can connect to it or not) and if not we will start `odo debug port-forward`

**Comment by mik-dass** [comment]
@kadel @girishramnani @cdrage How about we add a `odo-debug.lock` file in the odo directory when a debugging session starts and delete the file when the session ends? The file will contain the local port number of the debug and the PID. 

I also looked into the RPC/http server concept but the problem was finding the port number of the serving program itself.

**Comment by mik-dass** [comment]
@kadel @girishramnani @cdrage The idea proposed above

- When a debug session starts, create temporary file `odo-debug-info.json`, put the process id, local and the remote port of the current debug session into the file.
- When `odo debug info` is run during an active debug session, we check for the above file. If the file is not present, we inform the user that no debug session is active. If the file is present, we read the port number and try to check if a debug session is actually running on the port.
- When the debug session is closed, we remove the temporary info file described above.

(Note: This approach will fail if the user deletes the temporary file during an active debug session.)

**Comment by mik-dass** [comment]
@kadel @girishramnani What should be the location of the debug file?

**Comment by girishramnani** [comment]
In my opinion, if the information is something that we dont wanna check into the repo then we should keep it in the temporary directory. we should namespace the filename i.e. `<project>-<app>-<component>-debug-info.json` so multiple debug sessions can run at the same time

**Comment by mik-dass** [comment]
> we should namespace the filename i.e. <project>-<app>-<component>-debug-info.json if we finally decide to use the /tmp dir so multiple debug sessions can run at the same time

I think this will also be within the filename limits of windows and linux both. @kadel WDYT?
