### ISSUE TITLE
UpdateNotification is not a parameter in the odo config

### ISSUE THREAD

**Issue by sbose78** [openshift/odo#2024]
[kind/bug]

## What versions of software are you using?
- Operating System: MacOS
- Output of `odo version`: 0.0.20

## How did you run odo exactly?
OpenShift Connector

## Actual behavior

In my terminal I see:
```
If you wish to disable the update notifications, you can disable it by running
'odo utils config set UpdateNotification false'

bash-3.2$ odo utils config set UpdateNotification false
 ✗  'UpdateNotification' is not a parameter in the odo config
```

## Expected behavior
I would expect the `UpdateNotification` command to work

**Comment by girishramnani** [comment]
Can you try the latest odo version @sbose78 ?

**Comment by amitkrout** [comment]
Try ```odo preference set UpdateNotification false``` on latest odo release.

**Comment by kadel** [comment]
I think that we should consider turning this feature comply off for the GA release

**Comment by girishramnani** [comment]
we should remove global preferences or just the `UpdateNotification` flag?
