### ISSUE TITLE
Remove -o, --o string from global flag

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2031]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

## How did you run odo exactly?
```
$ odo -h
[...]
Utility Commands:
  login       Login to cluster
  logout      Log out of the current OpenShift session
  utils       Utilities for terminal commands and modifying odo configurations (terminal)
  version     Print the client version information

Flags:
      --complete                Install completion for odo command
  -o, --o string                Specify output format, supported format: json (default "json")
[...]
```

## Actual behavior
Flag ```-o``` is a global flag

## Expected behavior
Should not be a global flag because it does not work with all the command and subcommand of odo till date. See issue for details - https://github.com/openshift/odo/issues/1739

**Comment by amitkrout** [comment]
ping @cdrage cc_ @kadel

**Comment by kadel** [comment]
> * There are some commands that do not use -o... The solution is to use the annotations system (that we use for the help commands) to  indicate what is using json and what is not, and then "hiding" the `-o` option in the help / usage menu. (reference: https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L592)

I don't think that hiding will be enough :-( If it is just hidden it will not error out when someone tries to use it for command where it is not implemented.
