### ISSUE TITLE
"odo component list --path" shows incorrect "STATE" when components belong to different projects

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2032]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora
- Output of `odo version`: master

## How did you run odo exactly?
- Create two components belonging to different projects/namespaces
- Push the components using `odo push`
- Execute `odo list --path ../` in the context directory of both components and observe the "STATE" column of the output
- If the components belong to the same project, the output shows up as expected.

## Actual behavior
- Components belong to different projects
  ```sh
  $ pwd
  /home/dshah/src/nodejs-ex-2

  $ odo list --path ../
  APP     NAME                        TYPE       SOURCE     STATE          CONTEXT
  app     nodejs-nodejs-ex-kyvs       nodejs     ./         Not Pushed     /home/dshah/src/nodejs-ex
  app     nodejs-nodejs-ex-2-msky     nodejs     ./         Pushed         /home/dshah/src/nodejs-ex-2

  $ pwd
  /home/dshah/src/nodejs-ex

  $ odo list --path ../
  APP     NAME                        TYPE       SOURCE     STATE          CONTEXT
  app     nodejs-nodejs-ex-kyvs       nodejs     ./         Pushed         /home/dshah/src/nodejs-ex
  app     nodejs-nodejs-ex-2-msky     nodejs     ./         Not Pushed     /home/dshah/src/nodejs-ex-2
  ```
- Components belong to same project
  ```sh
  $ odo list --path ../
  APP     NAME                        TYPE       SOURCE     STATE          CONTEXT
  app     nodejs-nodejs-ex-kyvs       nodejs     ./         Pushed         /home/dshah/src/nodejs-ex
  app     nodejs-nodejs-ex-2-msky     nodejs     ./         Pushed         /home/dshah/src/nodejs-ex-2

  ```

## Expected behavior
Executing `odo list --path ../` should present same output which should show the "STATE" as "Pushed".
```sh
$ odo list --path ../
APP     NAME                        TYPE       SOURCE     STATE          CONTEXT
app     nodejs-nodejs-ex-kyvs       nodejs     ./         Pushed         /home/dshah/src/nodejs-ex
app     nodejs-nodejs-ex-2-msky     nodejs     ./         Pushed      /home/dshah/src/nodejs-ex-2
```

**Comment by mik-dass** [comment]
weirdly I am facing this issue while running `odo list`
```
[mrinaldas@localhost nodejs-ex]$ odo list --path /home/mrinaldas
 ✗  namespacing: component name cannot be blank
```

**Comment by kadel** [comment]
> I am facing this issue while running `odo list --path <path>`
> 
> ```
> [mrinaldas@localhost nodejs-ex]$ odo list --path /home/mrinaldas
>  ✗  namespacing: component name cannot be blank
> ```

confirmed, this is a bug. `odo list` with `--path` needs to work outside the context directory.
