### ISSUE TITLE
odo tab completion doesn't work

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2048]
[kind/bug]

## What versions of software are you using?
- Operating System: OSX and Linux (Fedora 30)
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo --complete
Install completion for odo? y
Installing...
Done!
```
```
$ odo comp(press tab twice quickly)
or
$ odo (press tab twice quickly) 
```

## Actual behavior
Completion does not work

## Expected behavior
Completion should work

**Comment by amitkrout** [comment]
Workaround:
On OSX:
```
$ odo --complete
Install completion for odo? y
Installing...
Done!
$ source $HOME/.bash_profile
```
On fedora:
```
$ odo --complete
Install completion for odo? y
Installing...
Done!
$ source $HOME/.bashrc
```
Then try tab completion

**Comment by amitkrout** [comment]
#1801

**Comment by amitkrout** [comment]
#1718

**Comment by dharmit** [comment]
I think this is expected behaviour and that you need to `source ~/.bashrc` or `source ~/.zshrc` to get this working because all `odo --complete` does is add data to these files. Without sourcing them, you won't be able to see the auto-completion work.

**Comment by girishramnani** [comment]
maybe we can add that as part of the output?
```
Installing...
Done!
Run "source $HOME/.bashrc"
```
or something?
