### ISSUE TITLE
open JDK binary source URL does not come up

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2049]
[kind/bug]

## What versions of software are you using?
- Operating System: OpenShifi CI (4.2 cluster)
- Output of `odo version`: master

## How did you run odo exactly?
Run test on OpenShift CI (4.2 cluster)

## Actual behavior
Route URL is not coming up

## Expected behavior
Route URL should come up

**Comment by amitkrout** [comment]
@kadel @girishramnani @cdrage @mik-dass @dharmit @mohammedzee1000 ping

**Comment by mik-dass** [comment]
@amitkrout You mean the URL doesn't become ready?

**Comment by amitkrout** [comment]
> @amitkrout You mean the URL doesn't become ready?

@mik-dass yes

**Comment by mik-dass** [comment]
@amitkrout https://github.com/openshift/odo/pull/2045#issuecomment-525610268

**Comment by amitkrout** [comment]
> @amitkrout [#2045 (comment)](https://github.com/openshift/odo/pull/2045#issuecomment-525610268)
If you were not able to reproduce this issue on your AWS cluster, how many average retries were required for the URL to be available. Also did increasing the timeout help?

@mik-dass The number of retries was mostly less than 30.  Increasing timeout could not help in OpenShift CI

**Comment by mik-dass** [comment]
> @mik-dass The number of retries was mostly less than 30 on my aws cluster. Increasing timeout could not help in OpenShift CI

Locally it worked too under 15 secs

**Comment by kadel** [comment]
We should probably revert https://github.com/openshift/release/pull/4741 before we figure out what is happening there.

**Comment by kadel** [comment]
@amitkrout have you tried to debug this to see what the reason for this failure?

**Comment by kadel** [comment]
Another point is that we shouldn't test just against 4.2, we need to test both 4.1 and 4.2

**Comment by kadel** [comment]
I probably found the reason for java test failing. 
The application jar doesn't support Java 11

The 4.1 java:latest points to java:8
The 4.2 java:latest points to java:11

This makes me wonder how it could ever pass on 4.2! Maybe it got changed only in recent 4.2 builds?

**Comment by amitkrout** [comment]
> I probably found the reason for java test failing.
> The application jar doesn't support Java 11
> 
> The 4.1 java:latest points to java:8
> The 4.2 java:latest points to java:11
> 
> This makes me wonder how it could ever pass on 4.2. Maybe it got changed only in recent 4.2 builds?

@kadel Yup, you are right.
I did the cross verification and hit the issue on my OpenShift 4.2 aws cluster but on 4.1 cluster it went fine.

It's correct that the jar is not supported on java:11. So by passing version with component type should fix the issue then. For example 
```
helper.CmdShouldPass("odo", "create", "java:8", "sb-jar-test", "--project", project ... )
```

Please share if you have any better idea atm

**Comment by kadel** [comment]
@amitkrout already opened PR to use `java:8` everywhere -  #2059
