### ISSUE TITLE
Enable tests against 4.2 cluster

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2052]
We should start testing odo against 4.2 clusters.

We need to test against both 4.1 and 4.2. The same jobs should run against each openshfit version.

We might have to temporary mark 4.2 jobs as optional until we resolve all issues like #2049

**Comment by amitkrout** [comment]
https://coreos.slack.com/archives/CBN38N3MW/p1566990527013700

**Comment by amitkrout** [comment]
Done via #4883
/close
