### ISSUE TITLE
Shortcut for linking a component?

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2058]
[kind/Feature]

## Which functionality do you think we should add?

So within VSCode the use the following functionality to link a component as well as open a port..

```sh
odo project set ${project} && odo application set ${app} && odo component set ${component} && odo link ${componentToLink} --wait${port ? ' --port ' + port : ''}
```

Do we really need to implement this for json output, or is there a better way for VSCode to use the above functionality?

@kadel @dgolovin

**Comment by kadel** [comment]
I think that this is command is for older (pre beta) odo versions. 
I expect that with a new workflow just `odo link`  will be enought

**Comment by girishramnani** [comment]
closing this as it seems new odo versions provide a simpler way of `linking` components
