### ISSUE TITLE
odo push fails with long running s2i builds

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/odo#2063]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: 
```
$ odo version
odo v1.0.0-beta4 (d11517f1)

Server: https://api.ocp4.home.ocpcloud.com:6443
Kubernetes: v1.13.4+4b86cc5
```

## How did you run odo exactly?
```
$ odo create jboss-eap64-openshift demo --git=https://github.com/VeerMuchandi/kitchensink-example -p 8080
 ✓  Validating component [19ms]
Please use `odo push` command to create the component with source deployed```

$ odo push
Validation
 ✓  Checking component [28ms]

Configuration changes
 ✓  Initializing component
 ✓  Triggering build from git [139ms]
 ✗  Waiting for build to finish [2m]
 ✗  Failed to create component with name demo. Please use `odo config view` to view settings used to create component. Error: unexpected EOF
error streaming logs for demo-app-1
github.com/openshift/odo/pkg/occlient.(*Client).FollowBuildLog
	/home/travis/gopath/src/github.com/openshift/odo/pkg/occlient/occlient.go:1955
..
...
...
```

## Actual behavior
`odo push` fails as it doesn't wait for the build to complete. The application actually gets built and deploys too. `odo` doesnt wait long enough

## Expected behavior
If `odo push` times out, there should be some other command like `odo push retry` that picks up from where it left off.

**Comment by EnriqueL8** [comment]
I am having this same issue. It seems to happen when the BuildConfig using a Dockerfile hits a `COPY` step. 
OCP version 4.3, building odo from master.
