### ISSUE TITLE
catalog list components doesn't list out component of a specified namespace

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2065]
[kind/bug]

## What versions of software are you using?
- Operating System: Supported platform
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo project create test
$ oc apply -n test -f https://raw.githubusercontent.com/openshift/library/master/arch/x86_64/community/wildfly/imagestreams/wildfly-centos7.json
$ odo catalog list components --project test
Error: unknown flag: --project
Usage:
  odo catalog list components [flags]
[...]
```
## Actual behavior
```--project``` flag is not supported.

## Expected behavior
Should list out wildfly component

**Comment by girishramnani** [comment]
is this a bug or a feature request? because I cannot see that `odo catalog list components` having supported `--project` flag.
cc @kadel
