### ISSUE TITLE
`odo service create` doesn't work from a new location

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/odo#2068]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

```
$ odo version
odo v1.0.0-beta4 (d11517f1)
```

## How did you run odo exactly?
```
$ odo service create mysql-ephemeral mysql -p DATABASE_SERVICE_NAME=mysql -p MYSQL_USER=user -p MYSQL_PASSWORD=password -p MYSQL_DATABASE=my_data -p MYSQL_ROOT_PASSWORD=password
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```
## Actual behavior
See above. It doesnt create a service unless a component is created from that directory in the past.

## Expected behavior

Should create the service.

**Comment by girishramnani** [comment]
You can either provide `--app` and `--project` flag to run this or create a component in the directory using `odo create`.

**Comment by dgolovin** [comment]
@girishramnani Even with --app and --project it does not work.

```
Failed to create Service with error 'Error: Command failed: "C:\Users\dgolo\.vs-openshift\odo.exe" service create mysql-persistent --plan default ms --app app --project myproject -w
 X  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

**Comment by dharmit** [comment]
@VeerMuchandi @dgolovin can you please try using the [beta5 release](https://github.com/openshift/odo/releases/tag/v1.0.0-beta5)? #2001 was added as a part of beta5 release.

**Comment by dgolovin** [comment]
@dharmit works for me with beta5.
