### ISSUE TITLE
Add wait command for deleting service

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2077]
[kind/Feature]

## Which functionality do you think we should add?

Currently we use:

```sh
oc wait ServiceInstance/${service} --for delete --namespace ${project}
```

Within VSCode.

We should also have a `--wait` command for deleting a service within odo.

## Why is this needed?

Needed so that the CLI will correctly "hang" until it's completely deleted.

**Comment by girishramnani** [comment]
seems like this is a duplicate of https://github.com/openshift/odo/issues/2077, closing this as its newer
