### ISSUE TITLE
Missing SHA256_SUM for odo-beta-5 release 

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#2079]
[kind/bug]

The assets section is missing the `SHA256_SUM` file from the release build.
https://github.com/openshift/odo/releases/tag/v1.0.0-beta5

**Comment by kadel** [comment]
@cdrage also https://github.com/openshift/odo/blob/master/build/VERSION has not been updated

**Comment by cdrage** [comment]
This has been fixed :+1:
