### ISSUE TITLE
Installation process and Update notification after GA

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2089]
Currently, we have an update-notifier, each time someone executes odo command, it checks with github if there is a new version available and if there is it shows the following message that suggests that users can use our install.sh script to install or update odo.

![](https://user-images.githubusercontent.com/6422176/64281054-51376a00-cf20-11e9-866c-d932a77cef6c.png)

- Are we going to use this script even after GA
- The script is using binary packages (hacky packages that no official repo will ever accept) and our deb and rpm repositories hosted on bintray.  I don't think that we should keep using it.
- Shouldn't we just guide users to install it by copying odo binary to appropriate directory? we can use the install.sh script to automate it.
- Windows installation process?

OCP documentation is just telling users to download binary and place it to `PATH` https://docs.openshift.com/container-platform/4.1/cli_reference/getting-started-cli.html

**Comment by cdrage** [comment]
IMO, I always found the notification annoying and I have it permanently disabled.

Does `oc` even use it?

Also, past GA, I don't think we should use it as (theoretically) odo is stable and backwards compatible, so any new updates are new features + bug fixes.

**Comment by dharmit** [comment]
I don't have a strong opinion with either keeping or removing this, but how do we intend to notify the user of a new update being available for `odo` if we remove this feature? There's a possibility that we will see BZ/issues opened for things that are already fixed by a newer version.

**Comment by kadel** [comment]
Resolution from cabal call:
- we are keeping the update notifier, just updating the message, not using install.sh script as it is not portable (not going to work on Windows)
- PR already opened for updating the message - https://github.com/openshift/odo/pull/2110
- update notification message should point to the docs.openshift.com odo installation section (it can be via github releases). Message from update notified pointing to github releases, which points to docs.openshift.com
