### ISSUE TITLE
odo url list returns invalid error when used with context

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#2092]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta5 (4d1d5071)

Server: https://192.168.30.54:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

First create a component from current directory but did not push it
Second create an URL

Then `odo url list -o json` reports:
`
{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"url","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"url1","creationTimestamp":null},"spec":{"port":8080},"status":{"state":"Not Pushed"}}]}`

Go up one level and run:

`odo url list --project sbproj --app sbapp --component sbcomp1 --context theComponentDir -o json`

Empty output is report.
If the json flag is omitted:

```
odo url list --project sbproj --app sbapp --context C:\work\src\tmp\demo170\comp1 --component sbcomp1
 X  Component sbcomp1 does not exist in application sbapp
```

## Actual behavior

See above

## Expected behavior

Report the same information as when run from component folder

**Comment by kadel** [comment]
@jeffmaury Sopecifing `--context` wiht `--app` and `--project` and `--component` is not what you usually want to do. 

Try using just `--context` -  `odo url list --context C:\work\src\tmp\demo170\comp1`


The context directory already have all necessary configuration that is required (app, project, component name)

If you use both context and one or more of app, project or component flags, than the flags overwrite what is specified in the context directory.

Example:
```
cd componentDir
odo component create java mycomponent --app myapp --project myproject
cd ..

odo url list --context componentDir
# odo lists urls for mycomponent in myapp in myproject.

odo url list --context --app otherapp
# odo lists urls for mycomponent in otherapp in myproject

````

**Comment by jeffmaury** [comment]
Then I ran:

```
$ odo url list --context comp1 --component sbcomp1
 X  Component sbcomp1 does not exist in application sbapp
```

**Comment by kadel** [comment]
You don't have to specify the `--component` flag if you want to list url for the component that is specified in `comp1` directory.

But you are right. This is a bug in `odo`.


given the folowing config in a `nodejs-rest-http`
```
▶ cat nodejs-rest-http/.odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - "8080"
  - "8088"
  Application: app
  Project: tkmyproject
  Name: nodejs-nodejs-rest-kagx
  Url:
  - Name: nodejs-nodejs-rest-kagx-8080
    Port: 8080
```


Listing with just `--context` works as expected.
```
▶ odo url list --context nodejs-rest-http
Found the following URLs for component nodejs-nodejs-rest-kagx in application app:
NAME                             STATE          URL     PORT
nodejs-nodejs-rest-kagx-8080     Not Pushed     ://     8080

There are local changes. Please run 'odo push'.
```

But if the `--component` flag is specified ( with the same value as the name of the component in the context directory) it fails.
```
▶ odo url list --context nodejs-rest-http --component nodejs-nodejs-rest-kagx
 ✗  Component nodejs-nodejs-rest-kagx does not exist in application app
```


Both commands should be equal

/bug
/remove-kind discussion

**Comment by dharmit** [comment]
Now, `odo` rightly reports that `--component` flag is not valid when you do `odo url list`. 

@jeffmaury I'm closing this issue since odo rightly mentions that the flag is not usable with the command. Please feel free to re-open if it's still a problem.
