### ISSUE TITLE
Compatibility table for hot reloading support / image support

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2093]
[kind/Documentation]

## What did you find missing in the documentation?

We should have a "matrix" table that lists what images are compability, whether they support hot reloading or not.

As well as:
 - What images support binaries (Java)
 - What images to use when using certain frameworks (Django, Ruby on Rails, etc.)
 - Compatibility support for Python 2.7 or 3.0 modules and what images support what.

## What is the relevance of it?

More openness as to what's available and compatible.

**Comment by kadel** [comment]
The only images that we officially support are Java and NodeJS, and only those that are based on the images specified [here](https://github.com/openshift/odo-init-image/blob/master/language-scripts/image-mappings.json). Everything else is just as-is, we don't provide any guarantees there.

**Comment by girishramnani** [comment]
The PR was merged and hence we can close this issue.
