### ISSUE TITLE
Refactor machine output to use machineoutput/types.go

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2105]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

The below code:
```sh
    storageListResultMachineReadable := storage.GetMachineReadableFormatForList(storageListMachineReadable)
  
    if log.IsJSON() {
      out, err := json.Marshal(storageListResultMachineReadable)
      if err != nil {
        return err 
      }   
      fmt.Println(string(out))
```

Is used throughout odo (https://github.com/openshift/odo/search?q=json.Marshal&unscoped_q=json.Marshal). 

This should instead use what we have within: https://github.com/openshift/odo/blob/master/pkg/machineoutput/types.go

## Why is this needed? 

Clean up / stability

**Comment by kadel** [comment]
This is not a good design. We already have structs representing most of the stuff that will be returned in machine-readable outputs. like `components/types.go` and `url/types.go`.

Odo should internally work with structures defined there, and the same structs should also be outputted as jsons.
The only exception should be if we need to return something that is not representations of odo object, like when the operation fails or deletion is successful.
If the operation is listing, or getting info about odo object (project, app, component..) it should always use structs in types.go inside the packages representing a given object.

**Comment by cdrage** [comment]
Bit confused @kadel 

What I mean is removing the json.Marshal statements for:

https://github.com/openshift/odo/blob/master/pkg/machineoutput/types.go#L34

Which is simply a wrapper around `json.Marshal` instead of having to copy/paste `json.Marshal` code everwhere :)

**Comment by kadel** [comment]
OH, right. So you mean replacing every occurrence `json.Marshal` that is outside of `machineoutput.OutputSuccess` with `machineoutput.OutputSuccess`, right? That makes sense.

**Comment by cdrage** [comment]
I've refactored this as much as I could :+1: I think we can close this for now.
