### ISSUE TITLE
odo delete --all delete odo config file when run from $HOME

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#2109]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta5 (4d1d5071)       
                                  
Server: https://172.18.10.148:8443
Kubernetes: v1.11.0+d4cacc0       
```

## How did you run odo exactly?

1. Go to $HOME
2. Create a component (not pushed)
3. Run `odo delete --all`

## Actual behavior

Whole `$HOME/.odo` folder is deleted

## Expected behavior

Only `$HOME/.odo/config.yaml` deleted

**Comment by girishramnani** [comment]
one possible solution could be to have case where if the current directory is the same as the `preference.yaml`'s parent directory then only the config file is removed because we have a `preference.yaml` also present.

**Comment by girishramnani** [comment]
other solution could be to just remove the `config.yaml` file. but this would keep the folder unclean and the `odo delete --all` is supposed to remove all traces of odo from the directory which wont happen as a blank directory `.odo` would be left behind ( we would have to remove the **odo-file-index.json** as well )

**Comment by girishramnani** [comment]
a solution suggested by @kadel 

- remove the `config.yaml` and `odo-file-index.json` 
- if the `.odo` directory is empty then remove it else dont
