### ISSUE TITLE
odo catalog describe service requires .odo/config.yaml

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#2111]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

odo v1.0.0-beta5 (4d1d5071)       
                                  
Server: https://172.18.10.148:8443
Kubernetes: v1.11.0+d4cacc0     

## How did you run odo exactly?

`odo catalog describe service mysql-persistent`

## Actual behavior
` X  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component`

## Expected behavior

`mysql-persistent` template details

**Comment by kadel** [comment]
# User Story
- As a user, I want to list items from `odo catalog` without creating component first.

## Acceptance Criteria
- `odo catalog` should not require component (localConfig) to list, describe or search services and  component types
- if any of `odo catalog *`  commands need project, the current project from `KUBECONFIG` should be used.

**Comment by kadel** [comment]
/remove-kind user-story

This be addressed in user story https://github.com/openshift/odo/issues/2605

**Comment by dgolovin** [comment]
@kadel  This issues seems to be fixed in v1.1.0, because #2605 is fixed.

**Comment by kadel** [comment]
> @kadel This issues seems to be fixed in v1.1.1, because #2605 is fixed.

/close
