### ISSUE TITLE
`odo app delete` removes application components but not services

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2113]
[kind/bug]
## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`: 
```
> odo version
odo v1.0.0-beta5 (4d1d5071)
```

## How did you run odo exactly?
```
> odo.exe create nodejs:latest nodejs1 --git https://github.com/dgolovin/nodejs-ex --ref HEAD --app app --project myproject

> odo.exe push

> odo.exe service create postgresql-persistent --plan default psql --app app --project myproject -w

> odo list
APP     NAME        TYPE       SOURCE                                    STATE
app     nodejs1     nodejs     https://github.com/dgolovin/nodejs-ex     Pushed

> odo service list
NAME     TYPE                      STATUS
psql     postgresql-persistent     ProvisionedAndBound

> odo app delete app -f
This application has following components that will be deleted
component named nodejs1
This application has following service that will be deleted
service named psql of type postgresql-persistent
Deleted application: app from project: myproject

> odo list
 X  There are no components deployed.

> odo service list
NAME     TYPE                      STATUS
psql     postgresql-persistent     ProvisionedAndBound
```
## Actual behavior
Services have not been deprovisioned

## Expected behavior
Services have been deprovisioned

## Any logs, error output, etc?
N/A

**Comment by kadel** [comment]
This should get resolved once https://github.com/openshift/odo/issues/1793 is implemented.

**Comment by dharmit** [comment]
> This should get resolved once #1793 is implemented.

I don't think so. The PR #2125 opened to address #1793 makes DC the owner of Service, Replication Controller, PVC and Secret. But this is not the service (or Provisioned Service as shown on web console) created from Service Catalog using `odo service create` command. It's the Service started by the DC that we bring up as part of deploying component.

Besides, we had a series of PRs opened to make sure that Provisioned Services don't get bound to a context (`.odo/config.yaml`). We are now at a stage where `odo service {create,delete,list}` happens without requirng the command to be executed from a valid component directory.

Do we now want to attach a Provisioned Service to the life-cycle of an `app`? I understand that the context/component directory and `app` are different things.

If we delete the service(s) when the `app` is deleted it causes the future components being created for that app to not be able to attach to the service. User needs to bring up the service again if they want to attach a component to it.
- PROs:
  - if it's a database service, for example, the component won't have to work with old schema and/or data from the leftover service.
- CONs:
  - Time it takes to bring up the service afresh.

Does that fit in with the opinionated approach of the tool?

@kadel @dgolovin @girishramnani

**Comment by girishramnani** [comment]
consider `--all` as an extra flag to remove all the services as well

**Comment by kadel** [comment]
I think that the important question here is whatever the service is part of the application or not.
If odo is working with the model where services are part of the application, then it should be deleted with it.  

If we say that service is not part of the app but stand above it, then we shouldn't label it with application labels and do other changes in odo to reflect this.

Odo currently assumes that service is part of the application and requires that every service is associated with an app.
To make odo behave consistently the `odo application delete`  shouldn't also remove the services that are in the application. The message even warns the user that services will be deleted.

**Comment by dharmit** [comment]
@kadel TBH, I missed that the `odo app delete` explicitly warns the user that the service will be removed. Besides that, I agree with your point that at the moment services are tightly bound with the application in that, a service can't be created without `project` and `app` flags.

In this scenario, it makes sense to me to delete the service when application is deleted. I guess we could trying setting the `app`/`application` as `referenceOwner` for the service so that kubernetes/OpenShift automatically takes care of this.

**Comment by kadel** [comment]
> In this scenario, it makes sense to me to delete the service when application is deleted. I guess we could trying setting the `app`/`application` as `referenceOwner` for the service so that kubernetes/OpenShift automatically takes care of this.

+1

**Comment by dharmit** [comment]
The changes I've made to fix this issue of deleting a service deployed from Service Catalog when user deletes the app (`odo app delete app -f`) can be found at https://github.com/openshift/odo/compare/master...dharmit:fix-2113. However, something's off with the permissions and it doesn't let me delete the service binding and service instance. I'm not able to figure out what's wrong. PTAL at the output below.

```sh
~ $ odo service create dh-postgresql-apb psql --plan dev -p postgresql_database=mydb -p postgresql_password=password -p postgresql_user=luke -p postgresql_version=10
Deploying service psql of type: dh-postgresql-apb
 ✓  Deploying service [705ms]
 ✓  Service 'psql' was created

Progress of the provisioning will not be reported and might take a long time
You can see the current status by executing 'odo service list'
Optionally, link dh-postgresql-apb to your component by running: 'odo link <component-name>'

~ $ odo service list --app app
NAME     TYPE                  PLAN     STATUS
psql     dh-postgresql-apb     dev      Provisioning
~ $ odo app list
The project 'myproject' has the following applications:
NAME
app

~ $ odo app delete app -f
This application has following service(s) that will be deleted
service named psql of type dh-postgresql-apb
servicebindings.servicecatalog.k8s.io is forbidden: User "developer" cannot deletecollection servicebindings.servicecatalog.k8s.io in the namespace "myproject": no RBAC policy matched
serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot deletecollection serviceinstances.servicecatalog.k8s.io in the namespace "myproject": no RBAC policy matched
 ✗  unable to delete servicebinding,unable to delete serviceinstancervice(s) that will be deleted
service named psql of type dh-postgresql-apb
servicebindings.servicecatalog.k8s.io is forbidden: User "developer" cannot deletecollection servicebindings.servicecatalog.k8s.io in the namespace "myproject": no RBAC policy matched
serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot deletecollection serviceinstances.servicecatalog.k8s.io in the namespace "myproject": no RBAC policy matched
 ✗  unable to delete servicebinding,unable to delete serviceinstance
```

As far as the changes I've made, it's mainly the `occlient.go` file that contains the changes that matter. I've mainly done two things:
1. Added labels to the `ServiceBinding` that's created as a part of `odo service create` code
2. Tried to delete the `ServiceBinding` and then the `ServiceInstance` in the same function `func (c *Client) Delete(labels map[string]string) error` that deletes other resources belonging to the app when we do `odo app delete app -f`.

Can someone take a look please @kadel @girishramnani @mik-dass @kanchwala-yusuf

**Comment by girishramnani** [comment]
Can you try to delete the service using web console or using oc? If that happens successfully something is wrong with our code. We can then further investigate

**Comment by dharmit** [comment]
Yes it works through `oc` cli and web console. Errors only when using `odo.`

**Comment by dharmit** [comment]
@girishramnani I figured out the issue. Opened a PR. :man_dancing:
