### ISSUE TITLE
Should we mention "Supported" / "Unsupported" in components list output for community images?

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2148]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: `master`

## Actual behavior
`odo catalog list components` doesn't list "Supported" / "Unsupported" images on minishift.

## Expected behavior
Decide what the expected behaviour should be!

## Any logs, error output, etc?
Refer this dicussion for more context https://github.com/openshift/odo/pull/2133#discussion_r325623682

**Comment by kadel** [comment]
for reference:
On cluster with no supported components:
```
▶ odo catalog list components
OpenShift Components:
NAME        PROJECT       TAGS
dotnet      openshift     2.0,latest
httpd       openshift     2.4,latest
nginx       openshift     1.10,1.12,1.8,latest
perl        openshift     5.24,5.26,latest
php         openshift     7.0,7.1,latest
python      openshift     2.7,3.5,3.6,latest
ruby        openshift     2.3,2.4,2.5,latest
wildfly     openshift     10.0,10.1,11.0,12.0,13.0,8.1,9.0,latest
```

cluster with supported and unsupported components
```
▶ odo catalog list components
Odo Supported OpenShift Components:
NAME       PROJECT       TAGS
java       openshift     11,8,latest
nodejs     openshift     10,8,8-RHOAR,latest

OpenShift Components:
NAME              PROJECT       TAGS
dotnet            openshift     2.1,2.2,latest
golang            openshift     1.11.5,latest
httpd             openshift     2.4,latest
modern-webapp     openshift     10.x,latest
nginx             openshift     1.10,1.12,latest
perl              openshift     5.24,5.26,latest
php               openshift     7.0,7.1,7.2,latest
python            openshift     2.7,3.6,latest
ruby              openshift     2.4,2.5,latest
```


The issue is is that the list of components that are not fully supported doesn't say that. So if there are no supported components on the cluster, the user doesn't have a clue that we have two different support levels for component types.

**Comment by kadel** [comment]
Let's change the wording to explicitly say "Odo Unsupported OpenShift Component"
