### ISSUE TITLE
"odo list" showing component of an application from context directory of a different application

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2154]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: master

## How did you run odo exactly?
```sh
$ odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs
Application       app    <-------- note the application name
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             8080/TCP
Name              nodejs-nodejs-ex-mrsg
MinMemory         
MaxMemory         
Ignore            
MinCPU            
MaxCPU            

# Should this run when specifying the "path" as pwd?
$ odo list --path ./ --app myapp
APP     NAME                      TYPE       SOURCE     STATE      CONTEXT
app     nodejs-nodejs-ex-mrsg     nodejs     ./         Pushed     /home/dshah/src/nodejs-ex

# This is OK as it's not bound by pwd or any other directory
$ odo list --app myapp
APP       NAME                         TYPE       SOURCE        STATE
myapp     nodejs-myapp-nodejs-opdk     nodejs     file://./     Pushed
```
## Actual behavior
`odo list` shows component of an application that is not represented by the component directory from where the command is exexuted.

## Expected behavior
`odo list` should not list such component(s)

**Comment by girishramnani** [comment]
I think this is occurring because of conflicting `--path` and `--app` flags. `--path` will try to list all components present in the path irrespective of the app and so `--app` flag is ignored.

We can either 
- make `--app` and `--path` flag mutually exclusive
- use `--app` as a filtering criteria and list all the components present in the `--path` which are part of the `--app`.

**Comment by dharmit** [comment]
I think second option makes more sense. We should use `--app` as a filtering mechanism.

**Comment by dharmit** [comment]
This was opened from s2i perspective. Closing this since lot has changed since it was opened.

/close
