### ISSUE TITLE
Changing component's project and pushing it doesn't delete the component from the project it belonged to earlier

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2165]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: `master`

## How did you run odo exactly?
1. `odo create nodejs` (component belongs to `myproject`)
2. `odo push` (component pushed to `myproject`)
3. `odo config set project newproject`
4. `odo push` (component gets pushed to `newproject` but doesn't get deleted from `myproject`)

## Actual behavior
Component exists in two projects.

## Expected behavior
Should it be removed from the old project?

**Comment by girishramnani** [comment]
In my opinion, it shouldn't remove the other component.

**Comment by girishramnani** [comment]
Think about a scenario where someone from the same team clones an component repo that you are working on. They change the project name and as the project, app, cluster and the component name would be same your component would get deleted from the cluster. In my opinion, I don't think that would be the desired behaviour someone would be expecting.

**Comment by dharmit** [comment]
I don't think I entirely understand the scenario you're describing here.

**Comment by girishramnani** [comment]
after a discussion on https://github.com/openshift/odo/issues/2172. we decided to show a warning and it seems that the PR https://github.com/openshift/odo/pull/2454 shows warning when someone changes the project as well.
Hence closing this issue
