### ISSUE TITLE
`odo push` fails for local nodejs component with nodejs:10 and nodejs:latest

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2171]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`: odo 1.0.0-beta5

## How did you run odo exactly?
1. `git clone https://github.com/dgolovin/nodejs-ex`
2. `cd nodejs-ex`
3. `odo create nodejs:latest` or `odo create nodejs:10`
4. `odo push`

## Actual behavior
```
PS C:\Temp\nodejs-ex> odo push
Validation
 V  Checking component [18ms]

Configuration changes        
 V  Initializing component   
 V  Creating component [98ms]   
 V  Applying configuration [0ns]

Pushing to component nodejs-ex of type local
 V  Checking files for pushing [11ms]
 V  Waiting for component to start [5s]
 V  Syncing files to the component [2s]
 X  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
 p</  Busricopt/app-root/src-backu
+ rsylndci n-rlg Oc /tmp/sompornenct/. /opt/app-root/src-backup/src/
+ b_IFS='
'
+ b_OFS=
+ OIFS='
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.dummy
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.gitignore
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.odo
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/README.md
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/helm
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/openshift
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/package.json
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/server.js
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/tests
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/views
+ OIFS=
+ IFS='
'
+ '[' -n bucharestgold/centos7-s2i-nodejs ']'
+ '[' bucharestgold/centos7-s2i-nodejs == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
  '^[ ' B -uilnd /iungs r/cliompboenxeenct/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source
cp: preserving times for './.': Operation not permitted

 X  Building component [446ms]
 X  command terminated with exit code 1
PS C:\Temp\nodejs-ex> 
```

## Expected behavior

Build started and push command finished sucessfully. The same way it works with `nodejs:8`,
```
PS C:\Temp\nodejs-ex> odo push
Validation
 V  Checking component [22ms]

Configuration changes
 V  Initializing component
 V  Creating component [72ms]
 V  Applying configuration [0ns]

Pushing to component nodejs-ex of type local
 V  Checking files for pushing [13ms]
 V  Waiting for component to start [6s]
 V  Syncing files to the component [2s]
 V  Building component [12s]
 V  Changes successfully pushed to component
PS C:\Temp\nodejs-ex>
```

## Any logs, error output, etc?
N/A

**Comment by mohammedzee1000** [comment]
/kind bug
/priority High
Thanks @dgolovin

**Comment by amitkrout** [comment]
@dgolovin I am able to reproduce it on ```odo beta5 + 4.2 Openshift Cluster + win10```, However on odo master binary no such issue found. 

This week we will have a new odo upstream release. You can check it on that binary.

**Comment by kadel** [comment]
Tested with the same result as @amitkrout. I was able to reproduce this on Windows with beta5. But not on the latest master.

**Comment by RickJWagner** [comment]
This problem is similar to an issue reported by another user.
In this case, the user is using a nodejs application (perhaps from [1]), the push fails and a timeout message appears.
The user notes that OpenShift artifacts are being manipulated on the cluster (even as the timeout message appears).
I have durable artifacts (video recording) to show the symptoms, contact me if you wish to see them.


[1] https://developers.redhat.com/blog/2019/05/03/announcing-odo-developer-focused-cli-for-red-hat-openshift/

**Comment by kadel** [comment]
I've done some investigation and I believe that what is @RickJWagner is mentioning and what @dgolovin are reporting are two different issues. 

In @dgolovin's issue, the Sync phase was sucessfull and it failed  during Build phase.

In the other reported issue that @RickJWagner is mentioning, `odo push` failed during the Sync phase.
See screen shot.

<img width="423" alt="Screen Shot 2019-09-25 at 16 18 04" src="https://user-images.githubusercontent.com/57206/65609438-11f4ba00-dfb0-11e9-9b90-3d981ba9fe0a.png">

**Comment by kadel** [comment]
/close

This shouldn't be a problem anymore.
More info about this error in https://github.com/openshift/odo/pull/2265#issuecomment-540488848
