### ISSUE TITLE
odo create binary error with absolute path

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#2173]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta5 (4d1d5071)

Server: https://172.18.84.5:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

While in `C:\work\src\tmp\demo170\comp2`:

`odo create java:8 bincomp --binary C:\work\src\tmp\demo170\comp2\target\springboot-rest2-1.0.0-SNAPSHOT.jar --project bin --app binapp`

## Actual behavior

` X  Rel: can't make C:\work\src\tmp\demo170\comp2\target\springboot-rest2-1.0.0-SNAPSHOT.jar relative to`

## Expected behavior

Should relativize  `C:\work\src\tmp\demo170\comp2\target\springboot-rest2-1.0.0-SNAPSHOT.jar` to `target\springboot-rest2-1.0.0-SNAPSHOT.jar`

**Comment by kadel** [comment]
/kind bug
/priority high

Might be related to https://github.com/openshift/odo/issues/1969 ?

**Comment by kadel** [comment]
fixed in https://github.com/openshift/odo/pull/2209
/close
