### ISSUE TITLE
Evaluate possible test scenerios which have been missed

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2176]
List out the possible failure scenarios which have been missed by the integration tests. Breaking this list per command to make it easy to distribute the work load.

**Comment by dharmit** [comment]
Some issues I found while recording videos: #2139 #2138 #2154 #2155 #2158 #2165 #2172 #2174

**Comment by kadel** [comment]
@girishramnani How is this different from https://github.com/openshift/odo/issues/1845 ?

**Comment by girishramnani** [comment]
> @girishramnani How is this different from #1845 ?

+1, looks like a duplicate. Closing this issue as #1845 has more information.
