### ISSUE TITLE
Incorrect information about supported languages in readme

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2178]
Readme says "Supports multiple languages and frameworks such as Node.js, Java, Ruby, Perl, PHP, and Python." But odo officially supports only Java and NodeJs, the other languages are without any guarantees. 

Not sure what the right wording should be.

**Comment by kadel** [comment]
ping @boczkowska

**Comment by girishramnani** [comment]
the PR is merged. we can close this issue
