### ISSUE TITLE
Update the bump-version.sh script to function correctly

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2181]
@mohammedzee1000 mentioned that the script in question is not up-to-date and should be avoided to bump the version.

**Comment by girishramnani** [comment]
is this be relevant anymore? we use a different release mechanism post GA. We could consider removing all release related scripts also?

**Comment by dharmit** [comment]
> is this be relevant anymore? we use a different release mechanism post GA. We could consider removing all release related scripts also?

:+1:
