### ISSUE TITLE
Should we allow/prevent user to set DebugPort as environment variable?

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2183]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: master

## How did you run odo exactly?
I set the DebugPort using environment variable approach (`odo config set --env`) but tried to unset it using normal approach (`odo config unset DebugPort`) and was left confused why it's not getting unset.

1. `odo config set -e DebugPort 9090`
2. `odo config unset DebugPort`

## Actual behavior
Not really a bug but as a user I was wondering if this is a bug.

## Expected behavior
TBD

## Any logs, error output, etc?
In this case, it was my mistake to set DebugPort as env var and then unset it using `odo config unset`. Should we have a check or documentation or anything to prevent user from doing this or should this be just passed as user error? 

It seems more like user error to me than anything that tool should be worried about.

**Comment by boczkowska** [comment]
We have a separate module on setting / unsetting variables now which users can refer to: https://github.com/openshift/openshift-docs/pull/18478

**Comment by Preeticp** [comment]
@dharmit a separate module on setting / unsetting variables is documented by Yana here: https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/managing-environment-variables-in-odo.html 
Do you think we can close this issue?

**Comment by dharmit** [comment]
> @dharmit a separate module on setting / unsetting variables is documented by Yana here: https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/managing-environment-variables-in-odo.html
> Do you think we can close this issue?

In it's current state, the link you mentioned talks about environment variables in general. We're discussing about a particular environment variable (`DebugPort`) which, IMO, could cause confusion if we don't document it.

**Comment by Preeticp** [comment]
@dharmit documentation on the debug feature was covered through this PR: https://github.com/openshift/openshift-docs/pull/19750 can you confirm if we can close this issue, please?

**Comment by dharmit** [comment]
Looks good to me. Thanks for addressing this @boczkowska & @Preeticp !
