### ISSUE TITLE
`odo list --path <path>` fails when not in component directory

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2186]
> I am facing this issue while running `odo list --path <path>`
> 
> ```
> [mrinaldas@localhost nodejs-ex]$ odo list --path /home/mrinaldas
>  ✗  namespacing: component name cannot be blank
> ```

confirmed, this is a bug. `odo list` with `--path` needs to work outside the context directory.

UPDATE:
It looks like that this has to do something with the `--path` flag and where it points to. It doesn't matter from what directory the command is executed.

_Originally posted by @kadel in https://github.com/openshift/odo/issues/2032#issuecomment-535415637_

**Comment by dharmit** [comment]
I think this issue pops up when there's no odo component directory among the immediate child directories. For example, I face this issue when I do `odo list --path ~` but not when I do `odo list --path ~/src/`. There are numerous component directories under `~/src` in my case.
