### ISSUE TITLE
Documentation doesn't talk much about Java based components

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2196]
[kind/Documentation]

## What did you find missing in the documentation?
Nodejs and Java based components are going to be the supported ones for 1.0. We need to talk more about Java components in the documentation. For example in Getting Started guide.

## What is the relevance of it?
Relevant for 1.0 release.

**Comment by boczkowska** [comment]
We do have the docs for Java - "Creating a multicomponent application with odo" example includes instruction for creating a back-end Java comonent - https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.html

**Comment by kadel** [comment]
> We do have the docs for Java - "Creating a multicomponent application with odo" example includes instruction for creating a back-end Java comonent - https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.html

@dharmit  is this enough?

**Comment by dharmit** [comment]
Closing this in favour of #839. Also opening a topic for Cabal call to discuss if we need more examples in general.
