### ISSUE TITLE
Cannot update component's exposed ports with 'odo'

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2201]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- Output of `odo version`: 1.0.0-beta5

## How did you run odo exactly?
Created component using `odo create` without `--ports` option.

## Actual behavior
There is no way to update ports component config got by default. `config` and `update` commands does not support `ports`.

## Expected behavior
`odo` can update any property in config.

## Any logs, error output, etc?
N/A

**Comment by amitkrout** [comment]
@dgolovin Can you please provide the detail steps, On which component you try it out ? Or did you try the interactive mode ?

**Comment by dharmit** [comment]
You should be able to update the ports by doing:
```sh
$ odo config set ports 8080/TCP
```

**Comment by dgolovin** [comment]
@dharmit this didn't work for me in beta5, but it works in beta6. Thanks!

**Comment by dharmit** [comment]
@dgolovin glad it does! Closing this issue. :smile:
