### ISSUE TITLE
"odo storage create" with "--app" and "--project" flags is broken

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2203]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: master

## How did you run odo exactly?
Created storage with `--app` and `--project` flags where the values of these flags were different from the values in component directory. Also, these values were invalid because the `app` and `project` with those names don't exist.

```sh
$ odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             8080/TCP
Name              nodejs-nodejs-ex-vaiv
MinMemory         
MaxMemory         
DebugPort         
Ignore            
MinCPU            
MaxCPU

# we now create storage that doesn't belong to the app/project in above config
$ odo storage create invalidstorage \
> --path=/opt/newstorage \
> --size=1Gi \
> --app newapp \
> --project newproject
 ✓  Added storage invalidstorage to nodejs-nodejs-ex-vaiv
Please use `odo push` command to make the storage accessible to the component

$ odo push # works just fine.

$ odo storage list
The component 'nodejs-nodejs-ex-vaiv' has the following storage attached:
NAME               SIZE     PATH
invalidstorage     1Gi      /opt/newstorage

# inside the remote pod
sh-4.2$ ls /opt
app-root  newstorage  odo  rh

```

## Actual behavior
1. `odo storage create` command reports no error
2. `odo push` creates a storage for the component

## Expected behavior
`odo  storage create` should report some error indicating that the `app`/`project` are invalid. Creating the `app`/`project` upon `odo push` after `odo storage create` doesn't make sense because a storage is created for a component.

**Comment by dharmit** [comment]
IMO, `odo storage create` is closely tied with the component. We could even remove the `--app` and `--project` flags from it so that it can be created from a component directory or with a `--context` flag.

@kadel unless I'm mistaken, `odo storage create` with these extra flags looks miserably broken to me. (hoping to be wrong.)

**Comment by kadel** [comment]
You are right. The `--app`, `--project` and also `--component` doesn't make much sense. 
Original idea was that you could create storage and then attach it to multiple components. But with context directory and `LocalComponet` this is easily possible. 

It would be a good idea to remove those flags, and just leave the `--context`. 
I suspect that `url create` is in the same situation.

**Comment by dharmit** [comment]
@kadel You're right about the `odo url create` remark.
```sh
$ odo url create myurl --app nosuchapp --project nosuchproject
 ✓  URL myurl created for component: nodejs-nodejs-ex-vaiv

To create URL on the OpenShift Cluster, please use `odo push`

$ odo url list
Found the following URLs for component nodejs-nodejs-ex-vaiv in application app:
NAME      STATE          URL     PORT
myurl     Not Pushed     ://     8080

There are local changes. Please run 'odo push'.
$ odo push 
# push was successful and url got created for the component in pwd
```
