### ISSUE TITLE
"odo debug port-foward" should fail if the application is not running in the pod

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2207]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: master

## How did you run odo exactly?
1. `odo push`'d the nodejs-ex example
2. Did `odo debug port-forward` unbeknownst of the fact that nodejs application had stopped running on the remote pod. Found this when URL for the component lead to "Application is not running" page.

## Actual behavior
`odo debug port-forward` starts showing error when I tried to connect to port 5858 through VS Code debugger

## Expected behavior
`odo debug port-forward` should throw an error when setting up port-forward to an application that's stopped working.

## Any logs, error output, etc?
The errors below start showing only when we try to connect the debugger. The only output printed when doing `odo debug port-forward` is `Started port forwarding at ports - 5858:5858`.
```sh
$ odo debug port-forward
Started port forwarding at ports - 5858:5858
E0930 17:16:32.847229   24903 portforward.go:331] an error occurred forwarding 5858 -> 5858: error forwarding port 5858 to pod fa2cdd229a134361f305334cb6e6341926f2f26263e35552a504862c6c55e90d, uid : exit status 1: 2019/09/30 11:46:32 socat[22697] E connect(6, AF=2 127.0.0.1:5858, 16): Connection refused
E0930 17:16:35.114477   24903 portforward.go:331] an error occurred forwarding 5858 -> 5858: error forwarding port 5858 to pod fa2cdd229a134361f305334cb6e6341926f2f26263e35552a504862c6c55e90d, uid : exit status 1: 2019/09/30 11:46:35 socat[22705] E connect(6, AF=2 127.0.0.1:5858, 16): Connection refused
E0930 17:16:35.115332   24903 portforward.go:331] an error occurred forwarding 5858 -> 5858: error forwarding port 5858 to pod fa2cdd229a134361f305334cb6e6341926f2f26263e35552a504862c6c55e90d, uid : exit status 1: 2019/09/30 11:46:35 socat[22704] E connect(6, AF=2 127.0.0.1:5858, 16): Connection refused
E0930 17:16:35.124438   24903 portforward.go:331] an error occurred forwarding 5858 -> 5858: error forwarding port 5858 to pod fa2cdd229a134361f305334cb6e6341926f2f26263e35552a504862c6c55e90d, uid : exit status 1: 2019/09/30 11:46:35 socat[22706] E connect(6, AF=2 127.0.0.1:5858, 16): Connection refused
E0930 17:16:35.357695   24903 portforward.go:331] an error occurred forwarding 5858 -> 5858: error forwarding port 5858 to pod fa2cdd229a134361f305334cb6e6341926f2f26263e35552a504862c6c55e90d, uid : exit status 1: 2019/09/30 11:46:35 socat[22707] E connect(6, AF=2 127.0.0.1:5858, 16): Connection refused
```

**Comment by girishramnani** [comment]
Actually if port-forward fails when component is not running then that would make the user experience not so great between `odo push`s. Because the user would have to again and again run `port-forward` between pushes as there is a moment when the component is not running. 
This would also increase the complexity for the vs-code plugin because they would have to rerun the `port-forward` sub-process everytime a push happens.

**Comment by dharmit** [comment]
I think I'm trying to have a check to ensure that the component is running when `odo debug port-forward` is run for the first time. Once it has started, there could be a situation like the one you have mentioned where component would be off for a brief time. If that is something that needs to be addressed is a secondary thing IMO. 

For this issue, I think, the goal is that when `odo debug port-forward` is triggered from the CLI or by VS Code for the first time, there should be a mechanism to tell the user that the remote component is not running.

Does that make sense or is that not a valid thing to aim for?

**Comment by kadel** [comment]
> For this issue, I think, the goal is that when `odo debug port-forward` is triggered from the CLI or by VS Code for the first time, there should be a mechanism to tell the user that the remote component is not running.
> 
> Does that make sense or is that not a valid thing to aim for?

That makes sense. But I'm not sure if this is what we want. 
Is it really so confusing when port-forward command executes without and error, and then it starts throwing errors when something wants to communicate? 
I can see situations where setting up port-forward beforehand can be useful,and it might be limiting to condition port-forward with the requirement that the application has to be running.  


Maybe we could just show a warning when `port-forward` is executed before component is running?

/kind feature
/area debug
/priority low

**Comment by dharmit** [comment]
> Maybe we could just show a warning when port-forward is executed before component is running?

A warning would be good enough but the debug session thus started is still useless, IIUC. User would have to start the component and then start the debug session for the debug session to be of any use. 

>  Is it really so confusing when port-forward command executes without and error, and then it starts throwing errors when something wants to communicate?

More than the confusion, I think it's about usability. A debug session started for a component that's not running is of no practical use, no?

**Comment by dharmit** [comment]
@mik-dass Can you share your thoughts on this from devfile v2 point of view?

**Comment by mik-dass** [comment]
> @mik-dass Can you share your thoughts on this from devfile v2 point of view?

I think this issue is valid from the point of view of devfile v2 too.
