### ISSUE TITLE
odo catalog list components -o json is missing the supported flag

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#2208]
[kind/bug]

## What versions of software are you using?
- Operating System: Win10 Pro
- Output of `odo version`:

```
odo v1.0.0-beta6 (0cdcc908)      
                                 
Server: https://172.18.84.8:8443 
Kubernetes: v1.11.0+d4cacc0
```      

## How did you run odo exactly?

`odo catalog list components -o json`

## Actual behavior

JSON output list stacks but the supported flag is missing

## Expected behavior

Add a new property to each stack that exposes the supported nature

**Comment by girishramnani** [comment]
@jeffmaury I can introduce a new list called `supportedTags` which will list all the supported tags ( subset of `nonHiddenTags` )
