### ISSUE TITLE
odo debug requires force push when DebugPort value is changed

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2215]
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: master

## How did you run odo exactly?
1. Change the value of `DebugPort` by `odo config set DebugPort <port>`.
2. Did `odo push --config` as recommended
    ```sh
    $ odo config set DebugPort 9090
    Local config was successfully updated.
    Run `odo push --config` command to apply changes to the cluster.
    ```
3. Started debug mode `odo debug port-forward`. It started throwing errors similar to #2207 after trying to connect VS Code with local port.
4. Stopped `odo debug port-forward`, did `odo push -f` and started `odo debug port-forward` again. It worked just fine with the new port, i.e., 9090.

## Actual behavior
Like #2207, errors start appearing after trying to attach the VS Code debugger with remote application:
```sh
$ odo debug port-forward
Started port forwarding at ports - 5858:9090
# Below errors start appearing after I try to connect through VS Code
E1001 13:28:45.643806   11585 portforward.go:331] an error occurred forwarding 5858 -> 9090: error forwarding port 9090 to pod deea8adfed4fae61c141c11e39ff6a7ad29dc28981b7cb2d81369c43ff845d18, uid : exit status 1: 2019/10/01 07:58:45 socat[5933] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
E1001 13:28:47.954022   11585 portforward.go:331] an error occurred forwarding 5858 -> 9090: error forwarding port 9090 to pod deea8adfed4fae61c141c11e39ff6a7ad29dc28981b7cb2d81369c43ff845d18, uid : exit status 1: 2019/10/01 07:58:47 socat[5936] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
E1001 13:28:47.955981   11585 portforward.go:331] an error occurred forwarding 5858 -> 9090: error forwarding port 9090 to pod deea8adfed4fae61c141c11e39ff6a7ad29dc28981b7cb2d81369c43ff845d18, uid : exit status 1: 2019/10/01 07:58:47 socat[5937] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
```
## Expected behavior
`odo config set DebugPort <port>` should mention that force rebuild of remote application is required so `odo push -f` has to be executed. Or, `odo push --config` has to be smart enough to trigger force rebuild if the `DebugPort` value is changed.

**Comment by girishramnani** [comment]
I would prefer to change the documentation to say "Run `odo push -f` to apply the changes to the cluster"

**Comment by kadel** [comment]
> I would prefer to change the documentation to say "Run `odo push -f` to apply the changes to the cluster" @dharmit @kadel

@girishramnani documentation is not enough. `odo push` needs to be smart enough to do it what is needed and `odo config set DebugPort` needs to have a different message that will say that user needs to run `odo push` as pushing explicitly just a config with  `odo push --config` is not enough

**Comment by girishramnani** [comment]
this looks duplicate or subset of https://github.com/openshift/odo/issues/2337

**Comment by girishramnani** [comment]
Added a special mention for `DebugPort` in the #2337 issue, so we verify it specifically along with other parameters.
Closing this issue
