### ISSUE TITLE
add odo-file-index.json entry into .gitignore

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2223]
When a component is created `odo component create` the command should automatically add `./.odo/odo-file-index.json` to the `.gitignore` file.

If `.gitignore` doesn't exist it should be created even if the current directory is not a git repo as the user might be creating git repo later after the component is created.

**Comment by girishramnani** [comment]
This would mean everyone who clones the repo. For them the first push will always be a full push, is that ok?

**Comment by kadel** [comment]
yes, most likely they will push it to their own component instance (different cluster, different project etc...)

**Comment by girishramnani** [comment]
> If `.gitignore` doesn't exist it should be created even if the current directory is not a git repo as the user might be creating git repo later after the component is created.

This assumption is not that universal, I feel we should create a `.odoignore` instead. 
e.g. what if the user is using perforce?

**Comment by kadel** [comment]
> This assumption is not that universal, I feel we should create a `.odoignore` instead @kadel .

We want to prevent users commiting `odo-file-index.json` to git repo. Why `.odoignore`?

> e.g. what if the user is using perforce?
Don't know what you mean.

**Comment by girishramnani** [comment]
Yeah, I misunderstood. We should add the file to gitignore

**Comment by girishramnani** [comment]
the flow -
- check if `.gitignore` is present or not
   - not present then: create it and add the entry file with keeping in mind the `//` and `\` i.e. `filepath.Join(".odo","odo-file-index.json")`
   - if present then: add the entry if its **not present already**.

**Comment by kadel** [comment]
> * if not present then: create it and add the entry file with keeping in mind the `//` and `\` i.e. `filepath.Join(".odo","odo-file-index.json")`

It should be only `/`, .gitignore uses `/` as directory separator on all platforms

**Comment by girishramnani** [comment]
got it
