### ISSUE TITLE
Misleading Error Message for odo create

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#2225]
[kind/bug]

When trying to create a url via `odo`, I accidentally ran `odo create url` instead of `odo url create`. I received the following error message:

```
odo create url frontend
 ✗  this directory already contains a component
```

It would be helpful if `odo` could suggest a different command to run. The simpler solution would be to say that `url` or any invalid option is not a valid language option.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0-beta6 (0cdcc908)`

## How did you run odo exactly?

`odo create url frontend`

## Actual behavior

```
odo create url frontend
 ✗  this directory already contains a component
```

## Expected behavior

```
odo create url frontend
 ✗  url is an invalid language option. Run odo catalog list components to view language options.
```

or 

```
odo create url frontend
 ✗  Invalid command: Did you mean odo url create?
```

**Comment by kadel** [comment]
Currently, odo does the "cheapest" checks first. And one of the most simple checks is to simply verify that there is no component in the directory.


It should be pretty easy to just reorder checks and validate the component type first.
