### ISSUE TITLE
Document usage of  `odo debug` with a sample application

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2227]
[kind/Documentation]

## What did you find missing in the documentation?

When typing in `odo debug port-forward --help` there is no example on how to use it with an application..

For someone whose first using the command, how would one use `odo debug`? Is it for temporarily opening a port? 

## What is the relevance of it?

More documentation needed / an actual example of an application with a debug interface.

**Comment by cdrage** [comment]
Ping @girishramnani @kadel

**Comment by Preeticp** [comment]
Needs docs

**Comment by girishramnani** [comment]
This could be collaboration between @pmacko1 and a dev possibly in the next sprint if he would have bandwidth

**Comment by girishramnani** [comment]
we had some documentation which got lost in transition https://github.com/girishramnani/odo/blob/56e2e2c04f2197f7243564af660c256cea4a8f91/docs/getting-started.adoc#using-debug-mode-to-interactively-debug-tech-preview

**Comment by boczkowska** [comment]
Some basic documentation has been added here: https://github.com/openshift/openshift-docs/pull/19750

**Comment by Preeticp** [comment]
@cdrage can we close this issue? Docs for this have been added through the PR linked by Yana above.

**Comment by girishramnani** [comment]
@Preeticp as per the issue description, it would be nice to have an actual example of using debug via the cli or vscode (screenshot/gif). Like a process of going through the debug mode using an actual application? 
I cannot see that in the PR above, so can we please add that?
