### ISSUE TITLE
Format json output by default or add an option for that

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2235]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Output produced by `-o json` should be formatted 

## Why is this needed? 
Because it has more info about odo objects than table output and it is hard to get that information from output like this
![image](https://user-images.githubusercontent.com/620330/66100460-e64d7300-e55f-11e9-8ae6-416b28f6ab80.png)

**Comment by girishramnani** [comment]
If the -o json is used by machine, formatting it would make no difference. If it's tough for developers  then wouldn't just using `jq` work?

**Comment by dgolovin** [comment]
`oc get -o json` and `kubectl get -o json` do return formatted json, why we should fall out of the line?  '-o json' is a good source of additional, information if default table view output is not enough.

**Comment by girishramnani** [comment]
Resolved by #2267
