### ISSUE TITLE
Deleted namespace is being listed in odo project get command

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2236]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS (supposed to be found on all platform)
- Output of `odo version`: master

## How did you run odo exactly?
I used OSD 4.2 cluster

Steps:
1. Login to the cluster
```
odo login --token=xxxxxxxxxxx https://api.crw-osd4.t7n7.p1.openshiftapps.com:6443
```
2. Create project
```
odo project create project1
```
3. Delete project
```
odo project delete project1
```
4. Get the project
```
$ odo project get
The current project is: project1
```

## Actual behavior
Deleted project is being listed even after deleting it.

## Expected behavior
odo project get should list out the current active project ```default``` instead of the deleted one.

**Comment by prietyc123** [comment]
/kind bug
@kadel not sure if it is important for GA

**Comment by girishramnani** [comment]
If I remember correctly this is kind of expected behavior, but the question here would be that if its confusing enough, we could change it

**Comment by amitkrout** [comment]
> If I remember correctly this is kind of expected behavior, but the question here would be that if its confusing enough, we could change it

@girishramnani It really looks weird if ```get``` command is listing the deleted project as active project. There is an old open issue #1720 where you can see such discussion. Probably you can take that issue and send a fix as per the final discussion.

**Comment by girishramnani** [comment]
I would suggest that a warning being shown that the current project doesn't exist remotely. Because the current behavior is how it works in oc.
Rational - the current project is like a pointer and at times a pointer can point to non existent constructs as well. So we should provide a warning to the user incase they are using a non existent project.

**Comment by kadel** [comment]
> I would suggest that a warning being shown that the current project doesn't exist remotely. Because the current behavior is how it works in oc.
> Rational - the current project is like a pointer and at times a pointer can point to non existent constructs as well. So we should provide a warning to the user incase they are using a non existent project.
> They can then chose to switch the project.

+1

It could look something like this?

```
$ odo project get
The current project is: project1

$ odo project delete project1

$ odo project get
The current project is: project1
Warning: The current project doesn't exist on the cluster.
```

**Comment by girishramnani** [comment]
> $ odo project get
> The current project is: project1
> Warning: The current project doesn't exist on the cluster.

works

**Comment by dharmit** [comment]
Assuming this is still relevant.
