### ISSUE TITLE
Removing --app, --project, --component from subcommands that depends on component dir

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2243]
Copied from our last cabal discussion 

- we should remove --project, --app, --component flags from url and storage

- we need to check with vscode adapter that they are not using it

- lets check if there are more commands where we need to remove those flags

**Comment by amitkrout** [comment]
- [ ] Storage command - #2238 

- [ ] Url command -

**Comment by amitkrout** [comment]
ping @kadel @dgolovin

**Comment by girishramnani** [comment]
Intrested in doing the url one, if someone hasn't started 
cc @mik-dass

**Comment by mik-dass** [comment]
> Intrested in doing the url one, if someone hasn't started
cc @mik-dass

@girishramnani There is already a PR open for it https://github.com/openshift/odo/pull/2247

**Comment by girishramnani** [comment]
I opened it :smile:

**Comment by mik-dass** [comment]
> I opened it smile

Yeah I know, thanks for that :D

**Comment by kadel** [comment]
We need a list of the commands from which the flags should be removed!

**Comment by kadel** [comment]
> * we need to check with vscode adapter that they are not using it
> *

did someone check this?

**Comment by girishramnani** [comment]
The only commands that have the above flags is link, unlink and service stuff

**Comment by girishramnani** [comment]
ping @dgolovin 

> * we need to check with vscode adapter that they are not using it

**Comment by kadel** [comment]
There is `odo.ts` file inside the vscode plug source that contains all the odo commands execute by plugin in place.

You can look there.

I just did a quick check. `url` commands look clean. But there is a `odo storage` command using all 3 of them  https://github.com/redhat-developer/vscode-openshift-tools/blob/8388b83e750c686b773fed91e6275da425675576/src/odo.ts#L139

**Comment by girishramnani** [comment]
and the `odo storage` PR already got merged in, which means if we do a release the vscode plugin would break? @kadel

**Comment by kadel** [comment]
> and the `odo storage` PR #2238 already got merged in, which means if we do a release the vscode plugin would break? @kadel

yes!

**Comment by girishramnani** [comment]
then we should probably tell them :sweat_smile:

**Comment by mohitsuman** [comment]
We will update the `odo storage` command to use `--context`. This goes for beta-7 release, right ?

**Comment by girishramnani** [comment]
yes

**Comment by girishramnani** [comment]
@amitkrout I went through the code and it seems these are the only places from where we need to remove --project, --app and --component commands.
Closing this issue as we have already 
- [X] removed the flags from the url and storage
- [X] notified the adapters team about the removal of flag - they opened an issue to handle the change on their end https://github.com/redhat-developer/vscode-openshift-tools/issues/1226
- [X] checked and confirmed if the flags are to be removed from somewhere else or not
