### ISSUE TITLE
Deleted files are not remove from Java component

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2248]
Java assemble script copies the source files somewhere where outside the destination directory `/tmp/src`, where it does the build.

```
odo create java
odo push
# delete a file that is important and that should break the build
rm something-important
odo push

#everything is ok, but it shouldn't be
```

**Comment by amitkrout** [comment]
@kadel Hard to understand the scenario in the description area you mentioned. Can you please elaborate it

**Comment by kadel** [comment]
Did you mean this part?

```
odo create java
odo push
# delete a file that is important and that should break the build
rm something-important
odo push

#everything is ok, but it shouldn't be
```

**Comment by amitkrout** [comment]
> Did you mean this part?
> 
> ```
> odo create java
> odo push
> # delete a file that is important and that should break the build
> rm something-important
> odo push
> 
> #everything is ok, but it shouldn't be
> ```

Got it
Then it should be same case with nodejs component i guess

**Comment by amitkrout** [comment]
> > Did you mean this part?
> > ```
> > odo create java
> > odo push
> > # delete a file that is important and that should break the build
> > rm something-important
> > odo push
> > 
> > #everything is ok, but it shouldn't be
> > ```
> 
> Got it
> Then it should be same case with nodejs component i guess

@kadel Tested with url creation for nodejs component and it seems to work fine
Nodejs source - https://github.com/openshift/odo/tree/master/tests/examples/source/nodejs

**Comment by amitkrout** [comment]
> > > Did you mean this part?
> > > ```
> > > odo create java
> > > odo push
> > > # delete a file that is important and that should break the build
> > > rm something-important
> > > odo push
> > > 
> > > #everything is ok, but it shouldn't be
> > > ```
> > 
> > 
> > Got it
> > Then it should be same case with nodejs component i guess
> 
> @kadel Tested with url creation for nodejs component and it seems to work fine
> Nodejs source - https://github.com/openshift/odo/tree/master/tests/examples/source/nodejs

Tested on java source and I can confirm this breaks for java component

**Comment by kadel** [comment]
> > Did you mean this part?
> > ```
> > odo create java
> > odo push
> > # delete a file that is important and that should break the build
> > rm something-important
> > odo push
> > 
> > #everything is ok, but it shouldn't be
> > ```
> 
> Got it
> Then it should be same case with nodejs component i guess

nodejs should be fine (it will broke as it should), it is not copying source code to another directory, everything is happening inside the `/tmp/src`

**Comment by girishramnani** [comment]
So I checked the deployment and files are copied correctly and renames are working as expected as well. 
The only issue here is when I break something and then push, the odo push is successful. This is expected because the `.jar` file is built successfully. But when I tried to run the jar file it shows error.

Logs - 
```
[jboss@java-javatest-gasc-app-2-q5fwz deployments]$ ls /tmp/src/src/main/java/
Application.java  R2D2.java
[jboss@java-javatest-gasc-app-2-q5fwz deployments]$ ls /tmp/src/src/main/java/
Application.java  RX.java
[jboss@java-javatest-gasc-app-2-q5fwz ~]$ ls /tmp/src/src/main/java/
Application.java
```

manually running the java jar from the container shows error
```
+ echo exec java -cp . -jar /deployments/javalin-hello-world-0.1-SNAPSHOT.jar
exec java -cp . -jar /deployments/javalin-hello-world-0.1-SNAPSHOT.jar
++ get_exec_args
++ EXEC_ARGS=
++ '[' x '!=' x ']'
++ get_java_options
+++ get_script_dir
++++ dirname ./run-java.sh
+++ local dir=.
++++ cd .
++++ pwd
+++ local full_dir=/deployments
+++ echo /deployments
++ local dir=/deployments
++ local java_opts
++ local debug_opts
++ '[' -f /deployments/java-default-options ']'
++ '[' -f /deployments/debug-options ']'
++ '[' -f /deployments/proxy-options ']'
++ awk '$1=$1'
+++ run_java_options
+++ '[' -f /opt/run-java-options ']'
+++ which run-java-options
++ echo '     '
++ get_classpath
++ local cp_path=.
++ '[' x/deployments '!=' x/deployments ']'
++ '[' -z '' ']'
++ '[' x '!=' x ']'
++ '[' x '!=' x ']'
++ echo .
+ exec java -cp . -jar /deployments/javalin-hello-world-0.1-SNAPSHOT.jar
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	RX cannot be resolved

	at Application.main(Application.java:8)
```
But the jar was built successfully

I think there should be a way to show `unresolved compilation problem` while building the jar file
@kadel

**Comment by girishramnani** [comment]
ok so was able to make `mvn` show the expected error when the compilation shouldn't be successful. 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project javalin-hello-world: Compilation failure
[ERROR] /tmp/src/src/main/java/Application.java:[8,35] error: cannot find symbol
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project javalin-hello-world: Compilation failure
/tmp/src/src/main/java/Application.java:[8,35] error: cannot find symbol

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
/tmp/src/src/main/java/Application.java:[8,35] error: cannot find symbol

	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
I was able to do this by
- initially doing a clean odo push
- removed the `/tmp/src/target` folder from the container
- removed an important file locally without which compilation wouldn't be successful
- `odo push`

This produced the above error which the user expects to see.

so one of the solution might be to have a `mvn clean` somewhere in the s2i scripts or manually remove the `target` folder using `ExecCmdinContainer` helper
@kadel @cdrage any suggestions

**Comment by kadel** [comment]
> * removed the `/tmp/src/target` folder from the container

why touching files inside the container?

**Comment by girishramnani** [comment]
> > * removed the `/tmp/src/target` folder from the container
> 
> why touching files inside the container?
to find the reason behind why the files are not getting compiled.

**Comment by kadel** [comment]
The Java framework used might have to play some role here. I've tried to do similar test as @girishramnani with SprintBoot example it once the java file was deleted it failed. 

If we can verify that we are correctly deleting files form the container, from all the appropriate paths I think we should be ok. We can't deal with the specifics of different Java frameworks or application setups.

**Comment by girishramnani** [comment]
@kadel this https://github.com/openshift/odo/issues/2248#issuecomment-540068332 in my opinion provides the necessary proof that the files are actually deleted and hence in reality the only behaviour which is confusing is the `odo push` passing even when the files are not present.
But in the end when the application runs, it fails.

**Comment by kadel** [comment]
Do we have tests validating that the files are deleted?

**Comment by girishramnani** [comment]
Understood, will add tests

**Comment by kadel** [comment]
/assign @amitkrout 
@amitkrout  will try to verify if the issue is still there or not. If it is fixed, we just need to write test. If issue is still present, we need to fix it together with writing a proper test for it.

**Comment by amitkrout** [comment]
> @kadel this #2248 (comment) in my opinion provides the necessary proof that the files are actually deleted and hence in reality the only behaviour which is confusing is the odo push passing even when the files are not present.
But in the end when the application runs, it fails.

With odo master bits +  OpenShift 4.3 cluster i have verified the same behaviour what @girishramnani observed. 

> Do we have tests validating that the files are deleted?
We need tests for both, nodejs and java that will check that files are deleted from the directory that is used to build the component.

Test will be added as @girishramnani mentioned above. However the behaviour of second push when no files are present need to be addressed properly.

cc_ @kadel @girishramnani

**Comment by kadel** [comment]
Why was this closed?
This issue was scheduled for the current sprint and assigned to @girishramnani to write tests for this.
https://github.com/openshift/odo/issues/2248#issuecomment-547244047
