### ISSUE TITLE
Scenarios that are not tested!

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2249]
The following scenarios are currently broken and they are not tested!

Pushing Java component after changing the config
```
odo component create java
odo push
odo config set --env foo=bar
odo push
# edit java source code
odo push

#changes are not reflected on the application
```

Linking NodeJs component to something else
```
odo component create java backend --context backend
odo component create nodejs frontend --context frontend
odo push --context frontend
odo push --context backend
odo link --context frontend backend

# frontend nodejs component is broken (source code is lost from container)

```

Onether scenario that should be covered is one described at https://github.com/openshift/odo/issues/2248

**Comment by amitkrout** [comment]
@kadel Thanks for finding it out. Also you can find some good amount of valid missing scenario per command. I have already created an issue #1845 to track and fix those missing scenario. 

> Linking NodeJs component to something else
odo component create java backend --context backend
odo component create nodejs frontend --context frontend
odo push --context frontend
odo push --context backend
odo link --context frontend backend
# frontend nodejs component is broken (source code is lost from container)

This scenario is being tested in https://github.com/openshift/odo/blob/master/tests/integration/servicecatalog/cmd_link_unlink_test.go but not with java component, instead of ```java``` component type ```python``` is being used. However, there is no such steps for validating the component/application status.

> Pushing Java component after changing the config
odo component create java
odo push
odo config set --env foo=bar
odo push
# edit java source code
odo push
#changes are not reflected on the application

This is a clear miss. However i can see many scenario in ```cmd_push_test.go``` file but no push scenario after a config change.

I would suggest fix both the issue and add these test along with the pr.

**Comment by kadel** [comment]
> @kadel Thanks for finding it out. Also you can find some good amount of valid missing scenario per command. I have already created an issue #1845 to track and fix those missing scenario.

as we discussed many times.  #1845 needs to be broken into smaller issues. Those smaller issues should describe what is missing and even better include the missing scenarios.

> 
> > Linking NodeJs component to something else
> > odo component create java backend --context backend
> > odo component create nodejs frontend --context frontend
> > odo push --context frontend
> > odo push --context backend
> > odo link --context frontend backend
> > frontend nodejs component is broken (source code is lost from container)
> 
> This scenario is being tested in https://github.com/openshift/odo/blob/master/tests/integration/servicecatalog/cmd_link_unlink_test.go but not with java component, instead of `java` component type `python` is being used. However, there is no such steps for validating the component/application status after linking.

Different component types, missing validation  - This is a different scenario.

> 
> > Pushing Java component after changing the config
> > odo component create java
> > odo push
> > odo config set --env foo=bar
> > odo push
> > edit java source code
> > odo push
> > changes are not reflected on the application
> 
> This is a clear miss. However i can see many scenario in `cmd_push_test.go` file but no push scenario after a config change.
> 
> I would suggest fix both the issue and add these test along with the pr.

What PR?

**Comment by amitkrout** [comment]
> > @kadel Thanks for finding it out. Also you can find some good amount of valid missing scenario per command. I have already created an issue #1845 to track and fix those missing scenario.
> 
> as we discussed many times. #1845 needs to be broken into smaller issues. Those smaller issues should describe what is missing and even better include the missing scenarios.

#1845 is an umbrella issue and it's already been broken into smaller issues like in the comment https://github.com/openshift/odo/issues/1845#issuecomment-527865106. Only things to be done is pick any command, improve the scenario and send the pr as part of #1845 fix. Fo example, we have already done in - https://github.com/openshift/odo/issues/1473

Or as you mentioned separate issue can be created for each command where more analysis to the missing scenario can be added.

> 
> > > Linking NodeJs component to something else
> > > odo component create java backend --context backend
> > > odo component create nodejs frontend --context frontend
> > > odo push --context frontend
> > > odo push --context backend
> > > odo link --context frontend backend
> > > frontend nodejs component is broken (source code is lost from container)
> > 
> > 
> > This scenario is being tested in https://github.com/openshift/odo/blob/master/tests/integration/servicecatalog/cmd_link_unlink_test.go but not with java component, instead of `java` component type `python` is being used. However, there is no such steps for validating the component/application status after linking.
> 
> Different component types, missing validation - This is a different scenario.
> 
> > > Pushing Java component after changing the config
> > > odo component create java
> > > odo push
> > > odo config set --env foo=bar
> > > odo push
> > > edit java source code
> > > odo push
> > > changes are not reflected on the application
> > 
> > 
> > This is a clear miss. However i can see many scenario in `cmd_push_test.go` file but no push scenario after a config change.
> > I would suggest fix both the issue and add these test along with the pr.
> 
> What PR?

Just a question to clarify - The two scenarios above you mentioned are not broken ? or these tow scenarios are only missing in test file ?

**Comment by kadel** [comment]
> Just a question to clarify - The two scenarios above you mentioned are not broken ? or these tow scenarios are missing in test file/spec ?

They are completely missing. And because they are missing we haven't noticed that it is not working as it should.

**Comment by amitkrout** [comment]
> Pushing Java component after changing the config
odo component create java
odo push
odo config set --env foo=bar
odo push
# edit java source code
odo push
#changes are not reflected on the application

Test pr sent - #2338

**Comment by amitkrout** [comment]
> Linking NodeJs component to something else
odo component create java backend --context backend
odo component create nodejs frontend --context frontend
odo push --context frontend
odo push --context backend
odo link --context frontend backend
#frontend nodejs component is broken (source code is lost from container)

@kadel This has been fixed via #2265. Test step available here - https://github.com/openshift/odo/blob/master/tests/integration/servicecatalog/cmd_link_unlink_test.go#L86

**Comment by amitkrout** [comment]
Scenario 1 as per the issue description

> Pushing Java component after changing the config
odo component create java
odo push
odo config set --env foo=bar
odo push
# edit java source code
odo push
#changes are not reflected on the application

@kadel It fails locally and in CI too (#2338). However if you set the config at the beginning i mean set it through component create command or through config set just after component create then scenario works. For example
```
odo component create java
odo config set --env foo=bar
odo push
#create route
odo push
#Access the route URL     <------------- Works
#edit java source code
odo push 
#Access the app URL     <------------- Works
```
But after first push if you set config ```--env ...```, then accessing the route works after second push. Accessing the same route breaks after updating the source and followed by a push. For example
```
odo component create java
odo push
odo config set --env foo=bar
#create route
odo push
#Access the route URL     <------------- Works
#edit java source code
odo push 
#Access the app URL     <------------- Breaks
```

**Comment by amitkrout** [comment]
> Scenario 1 as per the issue description
> 
> > Pushing Java component after changing the config
> > odo component create java
> > odo push
> > odo config set --env foo=bar
> > odo push
> > #edit java source code
> > odo push
> > #changes are not reflected on the application
> 
> @kadel It fails locally and in CI too (#2338). However if you set the config at the beginning i mean set it through component create command or through config set just after component create then scenario works. For example
> 
> ```
> odo component create java
> odo config set --env foo=bar
> odo push
> #create route
> odo push
> #Access the route URL     <------------- Works
> #edit java source code
> odo push 
> #Access the app URL     <------------- Works
> ```
> 
> But after first push if you set config `--env ...`, then accessing the route works after second push. Accessing the same route breaks after updating the source and followed by a push. For example
> 
> ```
> odo component create java
> odo push
> odo config set --env foo=bar
> #create route
> odo push
> #Access the route URL     <------------- Works
> #edit java source code
> odo push 
> #Access the app URL     <------------- Breaks
> ```

@kadel As discussed, created an separate issue - #2371

**Comment by kadel** [comment]
separate issue https://github.com/openshift/odo/issues/2371 created to address last issue
/close
