### ISSUE TITLE
Improve component test spec

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2256]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
Test spec for component test

## Why is this needed? 
To add more test coverage

**Comment by kadel** [comment]
Improve how?
This needs a better definition of what needs to be done.

**Comment by amitkrout** [comment]
> Improve how?
> This needs a better definition of what needs to be done.

Will update as per our last discussion

**Comment by amitkrout** [comment]
> Improve how?

It depends what impact the code brings to the local system and the cluster aswell. For example 

component creates involve 
1. Create local config (Local config data need to be verified because it is created by odo)

Need to push the changes what is created in local config to confirm that it should work or not
1. For successful push, local config should reflect in the cluster in dc level (Same dc data need to be verified)

Expected end result
1. App end point should work (need to be verified)

These steps in each scenario should be verified to confirm pass and failure status. Other than this there are many flag to test along with component command. 

> This needs a better definition of what needs to be done.

Updated the above points from our last 1-1 discussion.

**Comment by kadel** [comment]
@amitkrout Can you please break this down into smaller tasks that can be addressed in a sprint? 
Or modify the description with more information what exactly is required

**Comment by amitkrout** [comment]
> @amitkrout Can you please break this down into smaller tasks that can be addressed in a sprint?
> Or modify the description with more information what exactly is required

- [ ] Test should run for component and component shortcut commands

- [ ] verify the local config after component creation

- [ ] If flags are used other than default then verify the local config along with the changes done in dc

- [ ] Verify the component create UTs and fix those missing cases if any so that we can minimize the integration test coverage with respect to UTs.

- [ ] Add negative cases for user facing cases

- [ ]  App route should work after each component create followed by a push

**Comment by amitkrout** [comment]
https://github.com/openshift/odo/issues/2256#issuecomment-558949843

@prietyc123 I can see the pending task here. So reopen it.
