### ISSUE TITLE
Collect info for 1.0 release notes

### ISSUE THREAD

**Issue by boczkowska** [openshift/odo#2258]
[kind/Documentation]

## What did you find missing in the documentation?
We don't have RNs and KIs yet.

We have 2 options:
1. RNs and KIs are integrated in the collective OCP Release Notes, a small paragraph about odo and a list of issues: https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html
2. Detailed RNs and KIs are a separate module within our docs, example: https://docs.openshift.com/container-platform/4.1/service_mesh/servicemesh-release-notes.html

If we go route 1, I need your input regarding KIs: https://docs.google.com/document/d/1QSv75n-LCafWalxEHjxLefdxUuOfs9VOowTZDLHsXKE/edit?usp=sharing

If we go route 2, I need your input regarding KIs and *features you want to be listed in the RNs*.

Please let me know as soon as possible your thoughts on this. Tnx!

## What is the relevance of it?
The docs need to be finalized. :)

**Comment by amitkrout** [comment]
@boczkowska I have added it to our today's cabal discussion.

**Comment by boczkowska** [comment]
The docs are created and integrated within OCP docs. Thanks everybody for the help. :)
