### ISSUE TITLE
Link tests are never executed!!

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2262]
Form travis-ci logs:
```
$ make test-cmd-link-unlink
ginkgo -v -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=2 -focus="odo link and unlink command tests" tests/integration/
Running Suite: Integration Suite
================================
Random Seed: 1570456653 - Will randomize all specs
Will run 106 specs
Running in parallel across 2 nodes
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 0 of 106 Specs in 0.064 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 106 Skipped

```

It looks like that all tests are skipped!

/area testing
/priority critical

**Comment by kadel** [comment]
There is far more than this. Like Service tests
 
```
ginkgo -v -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=2 -focus="odo service command tests" tests/integration/
Running Suite: Integration Suite
================================
Random Seed: 1570456638 - Will randomize all specs
Will run 106 specs
Running in parallel across 2 nodes
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 0 of 106 Specs in 0.056 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 106 Skipped
```

**Comment by amitkrout** [comment]
I can see it from the Makefile, even service command is also excluded. Will send the pr ASAP.

In the mean time let me check from where it was misplaced. AFAIK in the beginning it was there.

**Comment by kadel** [comment]
problem is in Makefile
https://github.com/openshift/odo/blob/9318bc163fd0f5c80b32e8c32c43c539c0985a24/Makefile#L138

it should be `tests/integration/servicecatalog`

which is a little bit odd as linking is not a service catalog, but that is a different story

**Comment by amitkrout** [comment]
> I can see it from the Makefile, even service command is also excluded. Will send the pr ASAP.
> 
> In the mean time let me check from where it was misplaced. AFAIK in the beginning it was there.

@kadel After beta5 release it was misplaced.
