### ISSUE TITLE
--binary with relative fails

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2266]
I'm seeing an issue that I didn't see in a previous version.

git clone https://github.com/openshift-evangelists/Wild-West-Backend
cd Wild-West-Backend
mvn clean package
odo login <server>
odo project create ododemo
odo create java backend --binary target/wildwest-1.0.jar

gives this error:

 ✗  Rel: can't make target/wildwest-1.0.jar relative to /Users/jkleiner/Downloads/Wild-West-Backend

I did not get that error in odo v1.0.0-beta6 (0cdcc908)

_Originally posted by @jankleinert in https://github.com/openshift/odo/pull/2265#issuecomment-540116066_

**Comment by girishramnani** [comment]
I can take a look at this

**Comment by amitkrout** [comment]
@prietyc123 Is it the same issue you are facing while validating the command in doc steps ?

**Comment by prietyc123** [comment]
@amitkrout Yes I am facing the same issue while validating the docs.
```
$ odo create java test3 --binary target/*.jar
 ✗  Rel: can't make target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar relative to /Users/pkumari/spring-petclinic
```
