### ISSUE TITLE
Component create fails with flag —context when —binary is located in temp folder

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2282]
[kind/bug]

## What versions of software are you using?
- Operating System: **macOS**
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo component create wildfly --project test123 --binary /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/ROOT.war --context /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/ 
 ✗  Validating component [1s]
 ✗  ../../../../../../private/var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/ROOT.war binary needs to be inside of the context directory (/var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/)
```

## Actual behavior
Component creation fails on **macOS**. 
```
$ ls /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test
ROOT.war
$ ls /private/var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/
ROOT.war
```
odo confuses between which ```$TMPDIR``` to use in --context when binary is already located in temp folder.

This causing the test script failure in java test on macOS -  https://github.com/openshift/odo/blob/master/tests/e2escenarios/e2e_java_test.go#L60

On WIndows and linux system same test script it works 

## Expected behavior
Should work

**Comment by amitkrout** [comment]
Work around: Go to the temp folder where the binary resides. from there create the component using binary flag

NOTE: For this case do not use ```--context``` flag along with ```--binary``` flag even you are in temp folder in macOS

**Comment by girishramnani** [comment]
@amitkrout would this error occur on any other non-home directory like `/opt/src/<>`?

**Comment by kadel** [comment]
this is related to symlinking. It will only occur if the component is created inside the symlinked directory.
