### ISSUE TITLE
Add more information to "Releasing a new version" step

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2287]
[kind/Documentation]

## What did you find missing in the documentation?
Doc path - https://github.com/openshift/odo/blob/master/docs/dev/development.adoc#releasing-a-new-version

- Verification steps are not very clear
- Steps are not well formatted
- Missing info like what option to uncheck before publishing

**Comment by kadel** [comment]
Can you add more details?

> * Verification steps are not very clear

What exactly is missing there?

> * Missing info like what option to uncheck before publishing

Not sure what you mean.


Could you maybe open PR to fix some of those? You are the last person who did a release, and you have everything in your fresh memory.
