### ISSUE TITLE
Gather ideas to improve odo PRs and test coverage

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2303]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
During the run-up to GA, we faced quite a bit of frustration with the tests and many points were discussed during various calls. Something that has been repeated during these calls is the lack of enough tests and, at times, rush to fix things which, in turn, becomes a reason for not adding enough tests in the PRs.

This issue is meant to gather ideas that the team members have. Ideas that can fix this situation we have with test coverage and make things less painful. Once we agree upon the points, we can make sure that the PRs follow a certain standard or satisfy certain requirements.

To start the discussion, here are the two points (not entirely mine) that I think can help us address the situation:

1. **PR template should be modified to include a section for tests** which has to be filled up by the PR owner when (s)he opens a PR without tests. There could be valid reasons like docs PR or adding more comments to the code that don't necessarily need tests. However, if it's not a valid reason (QE could be the judge of a valid reason), the PR must have the tests.
2. **Develop a habit of imagining failure scenarios** for the feature being added or bug being fixed (which quite likely happened because we couldn't imagine a failure scenario when adding a feature). Only having successful tests in the code is not enough. We must imagine scenarios that could break the code we're adding before the end-user imagines one. This could eventually lead to more lines of code for tests than for code itself but, IMO, it would strengthen our project by an order of magnitude.

## Why is this needed? 
To be less stressed when next major version of odo is to be shipped! :wink:

**Comment by amitkrout** [comment]
Will discuss it in cabal

**Comment by dharmit** [comment]
@amitkrout 

> Will discuss it in cabal

Sure, that's a great idea and we should do that. However, we must copy the points being discussed on the call to this issue. :wink:

**Comment by amitkrout** [comment]
> @amitkrout
> 
> > Will discuss it in cabal
> 
> Sure, that's a great idea and we should do that. However, we must copy the points being discussed on the call to this issue. 😉

@dharmit and All May be you will get many articles on test matrix, however i found [1] is more appropriate of what we are looking for. I would say go through the article so that we all will be in same page.

[1] https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html

**Comment by dharmit** [comment]
- We have a lot of integration tests. We can benefit from adding more unit tests.
- There are scenarios where we surely need integration tests. Writing more unit tests wouldn't suffice here.
- Neither of us is an expert at writing any kind of tests. Learn by reading how other projects are doing it, by reading blogs.
- Smaller integration tests to make it take lesser time.
- We have a bunch of overlapping scenarios being tested. But that's OK because machines are cheap.
- Add regression testing
- All the scenarios in the videos should be covered by integration test and e2e tests
- Very difficult to debug cause of integration/e2e test failures. Unit tests are handy in this regards. Easy to figure exactly where unit tests failed.
- Write integration tests where unit tests are not good enough. So just write unit tests till some scenario doesn't make sense to be tested with it. Write integration/e2e tests in this case.
- Make a list of areas that are painful and need improvement. Come up with a solution.
- We have to make it easier to write unit tests. Make it easier to work with fake client.
- Look into how OpenShift is doing this for themselves.
- Change in mindset of devs. Writing tests shouldn't be secondary to writing code. Spending more time on writing tests than in writing actual code is OK.
- PR reviewer also responsible for the merged code. So try to find bugs when reviewing code.
- Mention in the PR that x, y and z scenarios have been tested. This helps reviewer suggest some possible scenarios.

**Comment by dharmit** [comment]
- Performance tests. Not sure about its current priority but could be worth adding more. Possibly compare with `oc` for equivalent `odo` commands. At the moment we just record timings. We don't compare.

**Comment by girishramnani** [comment]
@dharmit should we close this issue?

**Comment by dharmit** [comment]
I don't think so. Not before discussing whether the points mentioned here are addressed or put in practice. These points were noted during a cabal call and hence are inputs from entire team. We still discuss points related to test in our cabal calls. So, I'd request we talk about these in a cabal after the holidays.

**Comment by dharmit** [comment]
IMO, we're still facing the problems that lead to opening this issue in the first place. But it's obviously not of value to most. Closing.

/close
