### ISSUE TITLE
No message is generated for component create command with -o json flag

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2309]
[kind/bug]

## What versions of software are you using?
- Operating System: All
- Output of `odo version`: Master

## How did you run odo exactly?
```
$ odo component create python -o json
$ 
// i am expecting json format output or an error message if it is not supported
```
```
$ odo component create python -o json
{
    "kind": "Error",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "creationTimestamp": null
    },
    "message": "this directory already contains a component"
}
// looks good
```
## Actual behavior
No display of output message

## Expected behavior
Json format output or an error message if it is not supported

**Comment by girishramnani** [comment]
successfully reproduced. 
would a message like be shown the user?
```
{
    "kind": "Success",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "creationTimestamp": null
    },
    "message": "Please use `odo push` command to create the component with source deployed"
}
```
i.e. the final message produced by the cli when `-o json` is not provided?

**Comment by kadel** [comment]
> successfully reproduced.
> would a message like be shown the user?
> 
> ```
> {
>     "kind": "Success",
>     "apiVersion": "odo.openshift.io/v1alpha1",
>     "metadata": {
>         "creationTimestamp": null
>     },
>     "message": "Please use `odo push` command to create the component with source deployed"
> }
> ```
> 
> i.e. the final message produced by the cli when `-o json` is not provided?

Nope. If the operation is successful it should return what was created. So, in this case, the output should be the same as `odo component describe -o json`

**Comment by cdrage** [comment]
@kadel 

For `odo component describe -o json` to work, you actually have to push the component.

See below:
```sh
▶ odo component describe -o json
{
    "kind": "Error",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "creationTimestamp": null
    },
    "message": "component nodejs-nodejs-ex-geah not pushed to the OpenShift cluster, use `odo push` to deploy the component"
}
```

So in theory, we're unable to actually output everything to the user after using `odo create -o json` since `odo describe` uses this function:

https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/describe.go#L72

Which requires ports to be available to get it.. 

Which I was hoping to simply drop into the `create.go` file.

This opens up another issue, we can't actually use `odo describe` without the component being pushed, should we remove the GetPorts() all-together? 

https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/describe.go#L72

**Comment by kadel** [comment]
> For `odo component describe -o json` to work, you actually have to push the component.

Not anymore. This PR https://github.com/openshift/odo/pull/2399 implemented `odo describe` even for not pushed components.

/kind feature
/remove-kind bug
/priority high

This is not a bug, but something that was not yet implemented.

**Comment by mohammedzee1000** [comment]
```
❯ odo push -o json
{
    "kind": "Component",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "nodejs-nodejs-ex-2-qehq",
        "namespace": "myproject",
        "creationTimestamp": null
    },
    "spec": {
        "app": "app",
        "type": "nodejs",
        "source": "file://./",
        "env": [
            {
                "name": "DEBUG_PORT",
                "value": "5858"
            }
        ]
    },
    "status": {
        "state": "Pushed"
    }
}


```

**Comment by mohammedzee1000** [comment]
Ok corrected:

```
❯ odo create -o json nodejs
{
    "kind": "Component",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "nodejs-nodejs-ex-2-quxc",
        "namespace": "myproject",
        "creationTimestamp": null
    },
    "spec": {
        "app": "app",
        "type": "nodejs",
        "source": "file://./",
        "ports": [
            "8080/TCP"
        ]
    },
    "status": {
        "state": "Not Pushed"
    }
}

❯ odo create python --now -o json
{
    "kind": "Component",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "python-python-bveb",
        "namespace": "myproject",
        "creationTimestamp": null
    },
    "spec": {
        "app": "app",
        "type": "python",
        "source": "file://./",
        "env": [
            {
                "name": "DEBUG_PORT",
                "value": "5858"
            }
        ]
    },
    "status": {
        "state": "Pushed"
    }
}


```

**Comment by mohammedzee1000** [comment]
https://github.com/openshift/odo/pull/2532
