### ISSUE TITLE
Write UTs for client.CreateNewProject

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2319]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
UTs for client.CreateNewProject

## Why is this needed? 
It was missing

**Comment by mik-dass** [comment]
@amitkrout @prietyc123 There is already a unit test for client.CreateNewProject() https://github.com/openshift/odo/blob/116728936e3ed26f25b51ae51218d4d0e11bb6ee/pkg/occlient/occlient_test.go#L2258

**Comment by amitkrout** [comment]
> @amitkrout @prietyc123 There is already a unit test for client.CreateNewProject()
> 
> https://github.com/openshift/odo/blob/116728936e3ed26f25b51ae51218d4d0e11bb6ee/pkg/occlient/occlient_test.go#L2258

Cool!!!
/close
