### ISSUE TITLE
Create a glossary for odo terminology

### ISSUE THREAD

**Issue by boczkowska** [openshift/odo#2320]
[kind/Documentation]

## What did you find missing in the documentation?
Since we have feedback on odo being confusing sometimes, how about adding a glossary in "Understanding odo" which would elaborate on the important terms and explain the relationship/hierarchy between them as well as examples: 

- project
- application
- component 
- something else? 

Maybe a visual representation - a diagram of some sorts could help?

Cc @kadel @cdrage @dharmit 

## What is the relevance of it?

Make docs better!

**Comment by kadel** [comment]
diagram https://drive.google.com/file/d/1iNSZjEfNY5mdOcfBMGUR-mYaFdDZL85l/view?usp=sharing

**Comment by girishramnani** [comment]
@boczkowska @pmacko1 could you please add an update on this issue?

**Comment by pmacko1** [comment]
I was not working on this issue, @boczkowska could you provide an update, please?

**Comment by boczkowska** [comment]
Done here: https://github.com/openshift/openshift-docs/pull/18477

**Comment by girishramnani** [comment]
As the PR was merged, we can close this issues
