### ISSUE TITLE
Suggestion: documentation on env variable in odo

### ISSUE THREAD

**Issue by boczkowska** [openshift/odo#2321]
[kind/Documentation]

## What did you find missing in the documentation?
When users work with odo, they can do a lot with env variables.

Should we have a separate piece of docs that would cover:
- overview of default/preset/automatically added env variables (if there are any)
- setting, unsetting, listing (so the user won't have to dig through the CLI ref)
- cover issues such as https://github.com/openshift/odo/issues/2183
- examples of what can be done via using env vars
- something else?

Example of the existing docs: https://docs.openshift.com/online/dev_guide/environment_variables.html

We used to have it in the upstream docs but the piece got lost in the great restructure for the downstream. (https://github.com/openshift/odo/pull/2026/files)

Would docs like that be useful?

## What is the relevance of it?
Improve docs.

**Comment by kadel** [comment]
we need to come up with the scenarios where user will set env variables

**Comment by kadel** [comment]
https://github.com/openshift/openshift-docs/pull/18478

**Comment by girishramnani** [comment]
@boczkowska is this issue in review or need some more work?

**Comment by boczkowska** [comment]
Done here: https://github.com/openshift/openshift-docs/pull/18478

**Comment by girishramnani** [comment]
as the PR has been merged, we can close this issue
