### ISSUE TITLE
Add json formatted output for `odo version` command

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#2323]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
The `odo version` command should have json formatted output 

## Why is this needed? 
To enable application users, such as adapters to process the output more easily

**Comment by mohammedzee1000** [comment]
Got something, how does this look
❯ ./odo version
odo v1.0.2 (HEAD)
❯ ./odo version -o json
{
    "Version": "v1.0.2",
    "GitCommit": "HEAD",
    "ServerInfo": null,
    "KubernetesEnv": {}
}
```
With server:

❯ odo version
odo v1.0.2 (HEAD)

Server: https://192.168.42.64:8443
Kubernetes: v1.11.0+d4cacc0

❯ ./odo version -o json
{
    "Version": "v1.0.2",
    "GitCommit": "HEAD",
    "ServerInfo": {
        "Address": "https://192.168.42.64:8443",
        "OpenShiftVersion": "",
        "KubernetesVersion": "v1.11.0+d4cacc0"
    },
    "KubernetesEnv": {}
}
```

**Comment by kadel** [comment]
/close
in favor of https://github.com/openshift/odo/issues/2614
