### ISSUE TITLE
Python inner loop support

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#2327]
[kind/Feature]

## Which functionality do you think we should add?

Leveraging an official image from community and Red Hat to be able to do inner loop development using Python.

## Why is this needed?

Python is growing in popularity due to its usage in AI/ML based applications and robotics/automation.

## Scope

- [ ] Use the v1 python devfile and convert it into v2 https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python/devfile.yaml
- [ ] Store the v2 python devfile on the devfile registry

**Comment by Preeticp** [comment]
"...documenting better what inner loop is and what images we actually test/support with it?
https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/understanding-odo.html#key-features
I find what we have to be a bit vague
For example "Official full support of Node.js and Java components." I assume that isn't any possible Java image, like tomcat or eap or quarkus."

**Comment by sspeiche** [comment]
> "...documenting better what inner loop is and what images we actually test/support with it?
> https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/understanding-odo.html#key-features
> I find what we have to be a bit vague
> For example "Official full support of Node.js and Java components." I assume that isn't any possible Java image, like tomcat or eap or quarkus."

@Preeticp I believe this was a slack auto-add of a comment or what did you have in mind with this comment as it relates to Python support?

**Comment by Preeticp** [comment]
I was trying to capture the feedback so that we could improve the docs. But you are right, I will create another docs issue for the above suggestion.

**Comment by kadel** [comment]
Before we start adding full support for more languages and runtimes we should solve the problem with s2i or figure out an alternative approach for the inner loop builds

The current approach where we try to hack s2i to play nice with inner loop and odo is not a good way forward.

**Comment by sspeiche** [comment]
This should be based on devfile support

**Comment by girishramnani** [comment]
> Leveraging an official image from community and Red Hat to be able to do inner loop development using Python.
@sspeiche as mentioned we would have two images - one set of dev files created by odo team and other productised version created by language team. Am I assuming this correctly?

**Comment by sspeiche** [comment]
I'd assume you just use/update what is being used with community Che https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/python and downstream with CodeReady Workspaces (I don't know the link off hand)

**Comment by girishramnani** [comment]
As per a recent discussion - this issue was deemed as `good-to-have` for devfile v2

**Comment by gorkem** [comment]
https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python-django/devfile.yaml is probably a better starting point as it does also cover debug.

**Comment by girishramnani** [comment]
we can create a python devfile based on what gorkem has mentioned and add that to the registry to make this easy to use

**Comment by kadel** [comment]
added in https://github.com/odo-devfiles/registry/pull/36

**Comment by kadel** [comment]
done in https://github.com/odo-devfiles/registry/pull/36
/close
