### ISSUE TITLE
FYI, labels "use case" and "code refactoring" have been changed

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2343]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

OpenShift bot doesn't recognizes spaces, thus we have to add a dash to the kind / label..

So I'm changing `code refactoring` to `code-refactoring` as well as `use case` to `use-case`

## Why is this needed? 

For `/kind code-refactoring` to work.

I've gone ahead and re-labelled use case to `use-case` and `code refactoring` to `code-refactoring`

**Comment by kadel** [comment]
Is there anything that is needed to do? Can we close this?

**Comment by cdrage** [comment]
Nope! Was just opening this issue for reference. Closing.
