### ISSUE TITLE
`odo storage create` does not show when using `odo push`

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2347]
/kind enhancement

## Which functionality do you think we should update/improve?

When doing `odo storage create`, the storage is created immediately in the config and does not show up when doing "push" using `odo push`. 

Similar to when we use `odo storage delete`, we should notify the user that you must use `odo push` to propage the changes, and we should also show in the `odo push` output that the storage was actually created..

## Why is this needed? 

Make it similar to `odo storage delete`, `odo create`, etc.

**Comment by girishramnani** [comment]
currently when I add a storage and then push I can see the log that `Added storage <name> to <component>`
```
$ odo push
Validation
 ✓  Checking component [924ms]

Configuration changes
 ✓  Added storage nodejs-nodejst-uivl-xzuc to nodejs-nodejst-uivl
 ✓  Initializing component
 ✓  Creating component [2s]

Pushing to component nodejs-nodejst-uivl of type local
 ✓  Checking files for pushing [2ms]
 ✓  Waiting for component to start [28s]
 ✓  Syncing files to the component [3s]
 ✓  Building component [8s]
 ✓  Changes successfully pushed to component
```

**Comment by girishramnani** [comment]
and also 
```
$ odo storage create --path=/home/blah --size=1Gi
 ✓  Added storage nodejs-nodejst-uivl-xzuc to nodejs-nodejst-uivl

Please use `odo push` command to make the storage accessible to the component
```
odo tells me to do `odo push` as well when I create the storage.

**Comment by girishramnani** [comment]
Hence it seems that this issue has been implemented already and hence closing.
