### ISSUE TITLE
Document how to enable service catalog on OpenShift so it can be used with 'odo service'

### ISSUE THREAD

**Issue by tmds** [openshift/odo#2353]
[kind/Documentation]

I'm trying out `odo` with OpenShift [crc](https://github.com/code-ready/crc). I'm trying to create a service and it's not clear what I should do to make it work.

```
$ odo catalog list services
 ✗  unable to list services because Service Catalog is not enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: the server could not find the requested resource (get clusterserviceclasses.servicecatalog.k8s.io)
$ odo service create postgresql
 ✗  unable to search classes by name (the server could not find the requested resource (get clusterserviceclasses.servicecatalog.k8s.io))

```

**Comment by girishramnani** [comment]
CRC uses openshift 4.0+ which doesn't have service catalog installed by default

**Comment by tmds** [comment]
I understood that from the message. I don't know how to install it.

**Comment by kadel** [comment]
We should like to guide on how to enable ServiceCatalog on crc if we are suggesting users to use crc and service catalog.
For example at  [Creating an application with a database
](https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-an-application-with-a-database.html) the   "Service Catalog is enabled." prerequisite should be a link to crc docs explaining how to enable service catalog.

Not sure if there is a CRC specific way to enable service catalog, but for OCP 4.2 there is this https://docs.openshift.com/container-platform/4.2/applications/service_brokers/installing-service-catalog.html 

We should verify that this is working on CRC first

cc @boczkowska

**Comment by tmds** [comment]
@kadel after following the OpenShift documentation steps, I get this:

> $ odo catalog list services
 ✗  no deployable services found

**Comment by tmds** [comment]
note: the top of the OpenShift documentation says:

> The service catalog is deprecated in OpenShift Container Platform 4. Equivalent and better functionality is present in the Operator Framework and Operator Lifecycle Manager (OLM).

**Comment by kadel** [comment]
> note: the top of the OpenShift documentation says:
> 
> > The service catalog is deprecated in OpenShift Container Platform 4. Equivalent and better functionality is present in the Operator Framework and Operator Lifecycle Manager (OLM).

We are looking into it, but the problem is that right now it is not equivalent. Some of the apis to allow what was possible with ServicaCatalog are still missing in operators :-(

**Comment by tmds** [comment]
@kadel do you know how I can populate the service catalog after enabling it? I get:

> $ odo catalog list services
✗ no deployable services found

**Comment by tmds** [comment]
fyi, this is what happens with my OpenShift Online account:

>  odo catalog list services
 X  unable to list services because Service Catalog is not enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "tdeseyn" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope

**Comment by tmds** [comment]
> We are looking into it

Ref https://github.com/openshift/odo/issues/2161

**Comment by kadel** [comment]
> fyi, this is what happens with my OpenShift Online account:
> 
> > odo catalog list services
> > X  unable to list services because Service Catalog is not enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "tdeseyn" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope

that looks like SeviceCatalog was not deployed or something went wrong with it

**Comment by tmds** [comment]
Sorry for the confusion.

This is the message on **OpenShift Online**:

> odo catalog list services
X unable to list services because Service Catalog is not enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "tdeseyn" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope

This is what I get on **crc**:

> $ odo catalog list services
✗ no deployable services found

**Comment by tmds** [comment]
After also following the instructions at https://docs.openshift.com/container-platform/4.2/applications/service_brokers/installing-template-service-broker.html, `odo catalog list services` is no longer empty. 🎉

**Comment by mohammedzee1000** [comment]
We might want to document this as a workaround for 4.x clusters?

**Comment by praveenkumar** [comment]
@tmds did you follow those doc on the latest `crc` and it worked or you used openshift online?

**Comment by gbraad** [comment]
>  CRC specific way to enable service catalog, 

There are no CRC specific ways. All interaction with the cluster we deploy is done as if it is a regular OpenShift 4.x cluster

**Comment by tmds** [comment]
> @tmds did you follow those doc on the latest crc and it worked or you used openshift online?

There is no `odo`/`crc` documentation for this. `odo`/`crc` is also not pointing at the OpenShift documentation, which makes it hard for a user to figure out how to make this work.

I have not tried these steps with OpenShift Online. I guess it won't work because the user is not the admin?

These are the steps:
- https://docs.openshift.com/container-platform/4.2/applications/service_brokers/installing-service-catalog.html
- https://docs.openshift.com/container-platform/4.2/applications/service_brokers/installing-template-service-broker.htm

**Comment by gbraad** [comment]
> Document how to enable service catalog on OpenShift so it can be used with 'odo service' 

Document how to enable service catalog on OpenShift 4.x so it can be used with 'odo service'

**Comment by gbraad** [comment]
> OpenShift Online

AFAIR OpenShift Online is 3.x, right?

**Comment by kadel** [comment]
> AFAIR OpenShift Online is 3.x, right?

It depends on which one. 
OpenShift Online Starter  is 4.x (various versions)
OpenShift Online Pro is still 3.11

**Comment by Preeticp** [comment]
Needs docs

**Comment by dudash** [comment]
+1

**Comment by Preeticp** [comment]
@kadel we have added a link to the Installing service catalog section through this PR: https://github.com/openshift/openshift-docs/pull/20106, is that enough for this issue? Can we close it?

**Comment by faysou** [comment]
I think this issue is still up to date, if I run "odo catalog list services", no service like a database is available when using CRC, which is what is used when learning. Instead I have to install operators, which is much harder than the intended use of odo which is to simplify development experience (especially for a beginner).

**Comment by kadel** [comment]
You are right, this is still valid at it should not been closed. 

/reopen 
/remove-lifecycle rotten
/remove-lifecycle rotten
/priority high

**Comment by dharmit** [comment]
> Also the steps above from @tmds don't seem to work anymore on the latest version of CRC.

I'm assuming that you're talking about steps in https://github.com/openshift/odo/issues/2353#issuecomment-550964471. Latest version of CRC is based on OpenShift 4.6. Whereas, as we can see in the [official OpenShift documentation](https://docs.openshift.com/container-platform/4.4/applications/service_brokers/installing-service-catalog.html), Service Catalog is not supported beyond OpenShift 4.4.

I'm not sure how we could address installation of Service Catalog on CRC in this situation.

**Comment by dharmit** [comment]
@kadel any suggestions?

**Comment by kadel** [comment]
/close

odo supports only supported versions of OpenShift. Service catalog is not supported in any of those
