### ISSUE TITLE
Short Cut Flag to Add Url to Component Configuration for odo create

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#2354]
[kind/Feature]

It would be nice to add a shortcut to `odo create` that would allow a user to create a url without having to run `odo url create`.

Something like the following would result in a configuration being created that specifies a node app is to be created that also has a url:

```
odo create nodejs frontend --url-create
```

## Why is this needed?

It would provide an easy way to also create a url without having to run another command.

**Comment by kadel** [comment]
/kind feature
/priority medium


This is a good idea.
The question is what this flag should do when component has multiple ports (defined in s2i builder image). 
 - We could create a  url for each port. Probably not a good idea.
 - Have an optional argument for the flag specifying for what port the url should be created. For example `odo create nodejs frontend --url 8080` or `odo create nodejs frontend --url 8080,8443`

The name for url can be autogenerated as we do with `odo url create` if user needs to define url name they will have to use the full commands (first create component than url).
