### ISSUE TITLE
odo delete Fails to Delete Linked Component When Secret Not Found

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#2355]
[kind/bug]

After linking two components, if you delete the component that shared its information with the other component as part of the linking, `odo` won't let you delete the remaining component.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0 (4e3175e6)`

## How did you run odo exactly?
Create Java component
```
odo create java:8 backend --binary target/jarfile
odo push
```

Create Node.js component
```
odo create nodejs frontend
odo url create frontend
odo push
```

Link components
(In directory of node app)
`odo link backend`

Delete Java component
`odo delete backend`

Delete Node Component
`odo delete fronted`

## Actual behavior
```
✗  secrets "backend-app-8080" not found
```

## Expected behavior
Able to delete Node.js component

**Comment by dharmit** [comment]
Can reproduce this on latest master. It's failing in the function `GetComponent` in `pkg/component/component.go` file.

**Comment by dharmit** [comment]
@kadel Using https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/component/component.go#L867
we can get a list of components in the cluster. This gives a list of components that are in `Pushed` state. Using this info on the component requested for deletion, we can figure if the component is linked to some other pushed component in the cluster.

IMO, using this info, we can prevent deletion of the component irrespective of the `--force` flag being provided with `odo delete` command. This should go in `Validate()` function for `odo delete`. WDYT?

**Comment by kadel** [comment]
> IMO, using this info, we can prevent deletion of the component irrespective of the `--force` flag being provided with `odo delete` command. This should go in `Validate()` function for `odo delete`. WDYT?

Why would you want to prevent deleting? The deletion should happen.
When  `odo delete backend` is executed and the backend component is linked to the frontend component it should first "unlink" the components (remove envFrom from frontend DC), delete the secret and then delete the component.
