### ISSUE TITLE
Nodejs images are not showing as supported on 4.3 cluster

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2359]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: odo master

## How did you run odo exactly?
odo create nodejs

## Actual behavior
warning shows up

## Expected behavior
No warning

## Any logs, error output, etc?
```
[odo] Warning: nodejs is not fully supported by odo, and it is not guaranteed to work.
```

**Comment by kadel** [comment]
/priority high

We need to figure out what changed, how the new images differ from the old one.

**Comment by amitkrout** [comment]
@kadel @girishramnani There is no latest tag for nodejs component 
```
$ odo catalog list components
Odo Supported OpenShift Components:
NAME       PROJECT       TAGS
java       openshift     11,8,latest
nodejs     openshift     8,8-RHOAR
```

**Comment by girishramnani** [comment]
yes, this image is `rhscl/nodejs-10-rhel7` latest, we need to add `rhscl/nodejs-10-rhel7` in the supported list

**Comment by girishramnani** [comment]
Debug mode seems to be broken on the nodejs latest version on openshift 4.3

**Comment by girishramnani** [comment]
so we need to resolve it

**Comment by cdrage** [comment]
@girishramnani Is there any output / logging as to why debug mode isn't working for OpenShift 4.3 or an issue created against the S2I images?

**Comment by girishramnani** [comment]
This failure has to be handled on our side @cdrage . I can open another issue scoping the failing debug mode if we want to not include that in this issue's scope.

**Comment by kadel** [comment]
Should be fixed as part of https://github.com/openshift/odo-init-image/pull/43/files

**Comment by kanchwala-yusuf** [comment]
This issue has been fixed by the PR https://github.com/openshift/odo/pull/2427

**Testing results:**
**CRC version:**
```zsh
➜  ~ crc version
crc version: 1.3.0-dev+b0d660e
OpenShift version: 4.3.0-0.nightly-2019-11-25-153929 (embedded in binary)
```

**odo-init-image:** "registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.0.1"

**assemble-and-restart script correctly identifying the language:**
```zsh
++ /opt/odo/bin/getlanguage
+ IMAGE_LANG=nodejs
+ '[' -f /tmp/.s2i/bin/run ']'
+ '[' '!' -z nodejs ']'
```

**node.js application starting correctly with debugger:**
```
+ echo 'Launching via nodemon...'
+ exec npx nodemon --inspect=5858
[33m[nodemon] master: <none>[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `node --inspect=5858 server.js`[39m
Debugger listening on ws://127.0.0.1:5858/35541d56-eb98-486c-9ad8-c09ad0505796      <------ Debugger started
For help, see: https://nodejs.org/en/docs/inspector
Server running on http://0.0.0.0:8080
time="2019-12-05T07:15:31Z" level=debug msg="wait program exit" program=run
```

**odo catalog list:**
```zsh
➜  ~ odo catalog list components
Odo Supported OpenShift Components:
NAME       PROJECT       TAGS
java       openshift     11,8,latest
nodejs     openshift     10-SCL,8,8-RHOAR,latest
```
