### ISSUE TITLE
Optimize number of test clusters created for each PR

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2360]
Right now we are creating 3 clusters of each 4.x version.
It might be better to group all tests into just one job and run all 3 tests against one cluster.

Instead of this:
- ci/prow/v4.1-benchmark
- ci/prow/v4.1-e2e-scenarios
- ci/prow/v4.1-integration 
- ci/prow/v4.2-benchmark 
- ci/prow/v4.2-e2e-scenarios
- ci/prow/v4.2-integration
- ci/prow/v4.3-benchmark 
- ci/prow/v4.3-e2e-scenarios
- ci/prow/v4.3-integration 

We would have just:
- ci/prow/v4.1
- ci/prow/v4.2
- ci/prow/v4.3

and 
- ci/prow/v4.1-unit 

BTW: why is unit test prefixed with v4.1 if it is just a unit test that doesn't create any cluster?

**Comment by amitkrout** [comment]
> BTW: why is unit test prefixed with v4.1 if it is just a unit test that doesn't create any cluster?

It was a copy paste issue from the previous config file. It should be removed

**Comment by amitkrout** [comment]
> We would have just:
    ci/prow/v4.1
    ci/prow/v4.2
    ci/prow/v4.3

@kadel It will increase the total time of test around 1hr i guess

**Comment by kadel** [comment]
> @kadel It will increase the total time of test by 1hr i guess

can we test it and measure it?

**Comment by amitkrout** [comment]
> > @kadel It will increase the total time of test by 1hr i guess
> 
> can we test it and measure it?

Sure, will figure it out. However i can see some painful points, For example

In case a test flake is hit in benchmark test then retest time cost a lot because integration and e2e test will run again along with benchmark

**Comment by kadel** [comment]
> In case a test flake is hit in benchmark test then retest time cost a lot because integration and e2e test will run again along with benchmark

One more incentive to write better tests that are not flaky 😄 
Now serious: It will depend on how much this will increase the test run time.
On the other hand, if we create fewer clusters, we should get fewer terraform and aws errors. 

Another problem is that we can't continue like this, and just keep adding more and more versions that will multiply test clusters by 3.

**Comment by amitkrout** [comment]
> > In case a test flake is hit in benchmark test then retest time cost a lot because integration and e2e test will run again along with benchmark
> 
> One more incentive to write better tests that are not flaky 😄
> Now serious: It will depend on how much this will increase the test run time.
> On the other hand, if we create fewer clusters, we should get fewer terraform and aws errors.
> 
> Another problem is that we can't continue like this, and just keep adding more and more versions that will multiply test clusters by 3.

@kadel Created a pr https://github.com/openshift/release/pull/5909. PTAL
