### ISSUE TITLE
odo link, specify prefix for envvars

### ISSUE THREAD

**Issue by tmds** [openshift/odo#2369]
[kind/bug]

## Which functionality do you think we should update/improve?

When linking to a service, it should be possible to specify a prefix for the environment variables that were added.

## Why is this needed? 

An application may be linked to multiple services which may causes name collisions.

**Comment by amitkrout** [comment]
I guess #2377 is related to what @tmds is looking for.

**Comment by amitkrout** [comment]
```
$ oc exec frontend-app-2-bfqsk -n test123 -- env
[...]
TERM=xterm
HOSTNAME=frontend-app-2-bfqsk
DEBUG_PORT=5858
ODO_S2I_SRC_BIN_PATH=/tmp
[...]
COMPONENT_BACKEND_HOST=backend-app
COMPONENT_BACKEND_PORT=8080
[...]
```
Yup, env var name should be taken care to avoid name collision.

**Comment by tmds** [comment]
For example, when linking with a PostgreSQL db, these envvars are made available:
```
 - database_name
 - password
 - root_password
 - uri
 - username
```
The request is to be able to add a prefix, for example with prefix `userdb_`, these would be:
```
 - userdb_database_name
 - userdb_password
 - userdb_root_password
 - userdb_uri
 - userdb_username
```

This is similar to `oc set env` `--prefix` argument:

> --prefix=""
Prefix to append to variable names

**Comment by kadel** [comment]
Why is this marked as bug? Is there something that is broken?

It is more like an improvement or a new feature, or am I missing something?


> For example, when linking with a PostgreSQL db, these envvars are made available:
> 
> ```
>  - database_name
>  - password
>  - root_password
>  - uri
>  - username
> ```
> 
> The request is to be able to add a prefix, for example with prefix `userdb_`, these would be:
> 
> ```
>  - userdb_database_name
>  - userdb_password
>  - userdb_root_password
>  - userdb_uri
>  - userdb_username
> ```
> 
> This is

`odo` uses a Secret that was created by ServiceCatalog ServiceBinding.

The Secret is added to the component's DeploymentConfig using `envFrom`.

```
     envFrom:
      - secretRef:
          name: posgresqlSecret
```

There is a `prefix` field in `envFrom` that is supposed to do what we want.
But the documentation is mentioning just ConfigMap.
"An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER."
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#envfromsource-v1-core

We should test it if it works also with Secrets. If yes that it will be easy to implement something like `odo link --prefix userdb` Which will do the following:
```
     envFrom:
      - secretRef:
          prefix: userdb
          name: posgresqlSecret
```

**Comment by tmds** [comment]
> It is more like an improvement or a new feature, or am I missing something?

Yes, this is a feature request.

**Comment by amitkrout** [comment]
> Why is this marked as bug? Is there something that is broken?

I was thinking in a different way, So thought it could be broken when multiple component are  involved. Ran some use case hopping it will be broken at some point but it did not happen. So yes it's a feature request then.

**Comment by girishramnani** [comment]
Two points to discuss here -

We can either derive the prefix from the component name by default or not have any if the user doesn't set it. 

We can set the prefix in the local odo config and allow the user to set it using `odo config set EnvPrefix <prefix>`.

**Comment by kadel** [comment]
>We can either derive the prefix from the component name by default or not have any if the user doesn't set it.

No prefix by default would be better.

> We can set the prefix in the local odo config and allow the user to set it using `odo config set EnvPrefix <prefix>`.

The component can have multiple links, and each link can have a different prefix.
The prefix needs to be parameters of a link. 
It should probably be something like this `odo link mysql --env-prefix=DATABASE`

**Comment by girishramnani** [comment]
> It should probably be something like this `odo link mysql --env-prefix=DATABASE`

then we need to think about the case where a developer forgets the `env-prefix`? should we store it locally?
also we would need a command to show this prefix to the user or show all the env variables exposes by the service with this prefix?

**Comment by girishramnani** [comment]
if we plan to store the prefix in local config and that prefix if can be different for each link then we have to consider this issue https://github.com/openshift/odo/issues/2400 first.

**Comment by girishramnani** [comment]
This issue is blocked on https://github.com/openshift/odo/issues/2400

**Comment by girishramnani** [comment]
we have another feature request which is related to this and we might have to decide how to either make these work together or implement one of them.
The related issue is https://github.com/openshift/odo/issues/2691
