### ISSUE TITLE
odo link, add envvar for service type

### ISSUE THREAD

**Issue by tmds** [openshift/odo#2370]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

When linking to a service, an envvar should be added that identifies the service type.

## Why is this needed? 

An application may support multiple types of database backends. Having a variable that identifies the service type (e.g. postgresql, mariadb, ...) makes it possible for the application to know what backend is used and use the corresponding envvars.

**Comment by tmds** [comment]
I just noticed the `uri` envvar for the PostgreSQL service is `postgres://xxxx`.
Do other services also expose a `uri` that includes their type?

**Comment by kadel** [comment]
> I just noticed the `uri` envvar for the PostgreSQL service is `postgres://xxxx`.
> Do other services also expose a `uri` that includes their type?

As far as I know, this depends on the Service Broker implementation.

**Comment by girishramnani** [comment]
@tmds could you provide a use case where this could be useful?

**Comment by tmds** [comment]
@girishramnani I put the use-case under 'Why is this needed?': an app can support multiple db backends (postgresql, mariadb, ...). This enabled figuring out which is provided. Without, the user must do additional envars to pass the type himself.
