### ISSUE TITLE
 If env var is set after first component push then route URL doesn't work after editing the source

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2371]
[kind/bug]

## What versions of software are you using?
- Operating System: Supported
- Output of `odo version`: master

## How did you run odo exactly?
```
odo component create java
odo push
odo config set --env foo=bar
#create route
odo push
#Access the route URL     <------------- Works
#edit java source code
odo push 
#Access the app URL     <------------- Breaks
```
Check https://github.com/openshift/odo/issues/2249#issuecomment-548416923 for more details.

## Actual behavior
Route is broken

## Expected behavior
route should work

**Comment by cdrage** [comment]
I'm unable to replicate this...

```sh
git clone https://github.com/openshift/nodejs-ex
odo create nodejs
odo push 
odo config set --env foo=bar
odo url create
odo push
# Can access
vim views/index.html
odo push # it's rebuilt
# Can still access
```

**Comment by amitkrout** [comment]
> I'm unable to replicate this...
> 
> ```shell
> git clone https://github.com/openshift/nodejs-ex
> odo create nodejs
> odo push 
> odo config set --env foo=bar
> odo url create
> odo push
> # Can access
> vim views/index.html
> odo push # it's rebuilt
> # Can still access
> ```

@cdrage Can you please check with java component.

**Comment by kadel** [comment]
> @cdrage Can you please check with java component.

I tried this with java, and it was working ok, component is running, it just takes a moment for application to start.


But I encountered another issue while testing this https://github.com/openshift/odo/issues/2476

@amitkrout If you can reproduce this issue (If env var is set after first component push then route URL doesn't work after editing the source) feel free to re-open this.


/close
