### ISSUE TITLE
[switch to CRD] saving local config leads to inconsistency

### ISSUE THREAD

**Issue by containscafeine** [openshift/odo#238]
So I work using ocdev using minishift on day 1, I make the changes, bring the cluster down and go home.
The next day bring up a fresh OpenShift cluster using minishift, and run `ocdev application list`, this will still show me older applications from the previous day which do not exist on the cluster anymore.

I think that the solution to this "out of sync" problem is that we don't store any information locally, but instead store on the server in a CRD and query that every time.

ping @kadel

**Comment by containscafeine** [comment]
I think we should prioritize this sooner than later, the sooner we switch to CRDs, the better it will be later on

**Comment by kadel** [comment]
We can't currently use CRDs. A regular user can't create CRDs.

**Comment by jorgemoralespou** [comment]
I agree that a CRD would help on the use case, but it's also a bad option for other use cases. We would need to define what possible scenarios could happen to know how to best implement the CRD or if implement it at all.
As you know, there's upstream discussions on creating an application CRD that might also change how this work. As everything is still very much in flux, I agree with @kadel that would defer that post MVP, as for the MVP current behavior is enough.

**Comment by kadel** [comment]
I don't actually need CRD to solve our problem with applications and storing current component. We could store this information in `Project` annotations.

**Comment by kadel** [comment]
We won't be able to use CRDs for this in foreseeable future.
CRDs are currently cluster-wide resource, thus cluster admin privilege is required. CRDs can't be created in the namespace by a regular user.

But there might be another option. As we only need to store simple data (key:value at most) we could use ConfigMaps. 
We could create odo ConfigMap that would store stuff that ODO needs (like empty applications or current components)

**Comment by jorgemoralespou** [comment]
AFAIK, CRD definition is cluster wide, the objects defined/created don't
need to be.
That means that installing the CRD would need to be done by an admin, but
once installed/registered, any use can leverage them.

I agree that it's not an optional solution as of now, but maybe the
OpenShift team can think of providing native support on OpenShift clusters
for odo and hence making the CRD installed by default. This is part of the
discussion that needs to happen with the OpenShift team to know what
leverages they'll provide.

**Comment by kadel** [comment]
Yes,  admin privileges are needed only to create `CustomResourceDefinition` (new resource can be defined with `scope: Namespaced`) +  appropriate RBAC `Role` and `RoleBinding` to allow normal users to interact with the new resource needs to be created. 

After this initial setup normal user will be able to create/modify new resource.

**Comment by girishramnani** [comment]
closing this issue as its stale
