### ISSUE TITLE
Link to download v1.0.1 does not work

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2385]
/kind docs
## What mistake did you find / what is missing in the documentation?

![image](https://user-images.githubusercontent.com/620330/68522846-3b6a5c00-0265-11ea-8dab-3d89c9d9eb08.png)

![image](https://user-images.githubusercontent.com/620330/68522826-dca4e280-0264-11ea-9c74-a790766deb36.png)

**Comment by mohammedzee1000** [comment]
There was a slight delay due to the unavailability of ART team. Content has been synced now

https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.0.1/
/close
