### ISSUE TITLE
.odo file gets pushed into component pod

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2390]
/kind bug

## What versions of software are you using?

**Operating System: Supported platform

**Output of `odo version`: master

## How did you run odo exactly?

```
$ git clone https://github.com/openshift/nodejs-ex
$ cd nodejs-ex && odo component create nodejs nodejs --project test
$ odo push
// go inside the component pod and get the env variable ODO_S2I_DEPLOYMENT_DIR
$ oc exec podName --namespace test -- ls -a <value of ODO_S2I_DEPLOYMENT_DIR>
```

## Actual behavior

Listing out the .odo component directory

## Expected behavior

It should ignore .odo directory to push inside the pod

**Comment by kadel** [comment]
This is not going to cause any issues. In some cases, this might be even useful.
If it is not causing any problems I wouldn't worry about changing this behavior for now.

/unassign @mik-dass 
/close
