### ISSUE TITLE
Add .NET images as supported images.

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2395]
It looks like that .Net images should work with odo without any problems.
We need to verify that, and if everything works (push, watch, debug) ... We should .net to our supported component types.

There already is a nice example of how to use .net with odo - https://github.com/redhat-developer/s2i-dotnetcore-persistent-ex

odo should also properly support --binary with .net components

cc @tmds

/priority high
/kind feature

**Comment by tmds** [comment]
debugging won't work.

For debugging you need a debug application that runs besides the .NET Core app.
Microsoft has `vsdbg` which we may not use due to license restrictions.
Samsung has https://github.com/Samsung/netcoredbg. This is used by Eclipse Che. Eclipse Che downloads a release from https://github.com/Samsung/netcoredbg/releases at runtime. netcoredbg supports VS Code debug adapter protocol.

How does `odo debug` integrate with an IDE?

**Comment by kadel** [comment]
> How does odo debug integrate with an IDE?

Currently, it does not. `odo debug` just tries to prepare the component, and set up the local port where you can connect your debugger to.

By default we set env variable `DEBUG_MODE=true` for all images. There are scripts that run the application in a debug mode when the `DEBUG_MODE` is set. 
For java the JVM is executed with `-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n` arguments and for NodeJS it is `nodemon --inspect=${DEBUG_PORT}`.

`odo debug` than just setups the port forwarding of container port`${DEBUG_PORT}` to the local port
Then it is up  to the user to setup IDE or another remote debugger to connect to the localhost and given port.

**Comment by tmds** [comment]
> Then it is up to the user to setup IDE or another remote debugger to connect to the localhost and given port.

Is there documentation for java/nodejs on how the user can do this?

Do we need debug for .NET Core to consider it supported by odo?

**Comment by girishramnani** [comment]
@tmds you can refer this for java/nodejs https://github.com/girishramnani/odo/blob/56e2e2c04f2197f7243564af660c256cea4a8f91/docs/getting-started.adoc#using-debug-mode-to-interactively-debug-tech-preview

**Comment by tmds** [comment]
@kadel we don't have plans to include a debugger in the .NET Core images. If that is a requirement, .NET Core can't be a 'supported image' in the near future. I'm fine if this issue is closed. If the situation changes, I'll look into adding `odo` support for the debugger.

**Comment by girishramnani** [comment]
closing this issue

**Comment by kadel** [comment]
> closing this issue

why? This is something that we will want to do.
/reopen

**Comment by girishramnani** [comment]
> If that is a requirement, .NET Core can't be a 'supported image' in the near future

As mentioned by @tmds hence we cannot resolve this issue.

**Comment by kadel** [comment]
Let's close this issue for now.
/close
Currently, odo requires supported images to have debug support. 
Not sure if this restriction is good or not, we might want to revisit it in the future.

**Comment by dmvolod** [comment]
@kadel , I thought also about support debug for dotnet core apps in odo. What do you think about adding function which will use an API to invoke kubectl/oc rsync/exec analogs for delivering and embedding vsdbg inside runtime pod.
