### ISSUE TITLE
odo link Doesn't Require odo push

### ISSUE THREAD

**Issue by danielhelfand** [openshift/odo#2400]
/kind enhancement

Unlike other commands that have the ability to alter what's deployed in a project, `odo link` simply performs linking as soon as you run the command. 

It seems a bit odd to have this behavior that is not consistent with other `odo` commands. I am wondering if it makes sense to add the need to run `odo push` as part of linking or if there's reasoning behind excluding it from `odo link`?

## Which functionality do you think we should update/improve?

Require `odo push` after an `odo link`.

## Why is this needed? 

To keep the experience of using `odo` commands the same as with other commands that alter the state of a project. Users might be caught off guard that `odo link` runs instantly as opposed to a `create` command.

**Comment by mohammedzee1000** [comment]
/kind feature
we need to update the template to say above :/

**Comment by tmds** [comment]
Adding to this:

It would be nice if linking is allowed when the application has not yet been pushed. This is currently not possible.

For example, if your application uses a database, currently you need to deploy the application, and after that link it to the database.

**Comment by girishramnani** [comment]
We have to create a list of `Links` in the odo local config. The essential information needed here are the 1st component and other component/service info ( component, app and project name ).
The current component present in the local config can be assumed as the 1st component so we need to only store the other component/service's info

**Comment by kadel** [comment]
Scenario:
- I clone a repository, for example, wildwest-frontend that  that uses odo (has .odo/config.yaml) and there is a Link in the config that points to `wildwest-backend`
- now I run `odo push` in  wildwest-frontend directory, but `wildwest-backend` is not deployed yet.

What should happen?

**Comment by girishramnani** [comment]
we show a warning that the linked component isn't running so we are ignoring the link. and when the user creates the `wildwest-backend`. and then rerun the `odo push` to create the link.

we need the links to be present in the local config. The purpose of local config is to allow someone to recreate the same component environment with least amount of information.

This could be useful when we consider storing service information in local config and then to re-create a database backed component a developer just needs to do `odo push`.

**Comment by mik-dass** [comment]
> we show a warning that the linked component isn't running so we are ignoring the link. and when the user creates the wildwest-backend. and then rerun the odo push to create the link.

I think a simple error/warning message would be enough.

**Comment by girishramnani** [comment]
we can store the links in config as a list of structs containing this info
```
LinksWith:
- name: <component/service name>
  app: <application name>
  env-prefix: <env prefix> # as described in https://github.com/openshift/odo/issues/2369
  port: <port to link with>
...
```

**Comment by kadel** [comment]
We also need to store information about "type" of the link, if it is a link to service or another component.

**Comment by girishramnani** [comment]
> We also need to store information about "type" of the link, if it is a link to service or another component.
I was thinking about that and when we do `odo link` that we don't ask user for that information so would we need to store it?
we can detect if its a service name or a component name?

**Comment by girishramnani** [comment]
There is alot of change in this issue and hence its taking time for me to get a WIP PR. should have something in this week.

**Comment by girishramnani** [comment]
Created a user story https://github.com/openshift/odo/issues/2534 for this issue. Please track the progress on that issue.
closing this issue.
