### ISSUE TITLE
Notarize odo in order to run on macOS Catalina 

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2408]
Every user running odo on macOS Catalina will have to add an exception to bypass new security measures in macOS Catalina in order to run odo.

Odo needs to be notarized by Apple in order to run on macOS Catalina.
This process should be ideally automatized and part of our release pipeline.

https://developer.apple.com/news/?id=09032019a

**Comment by mohammedzee1000** [comment]
coreos jira issue https://jira.coreos.com/browse/ODO-12 liable to change after migration to issues.jboss.org

**Comment by mohammedzee1000** [comment]
https://github.com/golang/go/issues/34986 this seems to be a larger-scale problem as even go is looking to do this
