### ISSUE TITLE
odo debug:  use env DEV_MODE instead of DEBUG_MODE

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2409]
Current odo debug implementation uses `DEBUG_MODE` that is set to true by default if the component is created from a supported image.

To be more aligned with s2i images we should start using `DEV_MODE` instead. This will allow users to use `odo debug` even with images that are not officially supported by odo, but support `DEV_MODE`

**Comment by girishramnani** [comment]
The only thing left on this issue is to release a new `odo-init-image` version and update the reference in odo
