### ISSUE TITLE
envForm record not found in dc when linking component using --wait flag

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2414]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported platform
**Output of `odo version`:**
master
## How did you run odo exactly?

https://github.com/openshift/odo/pull/2398/files#diff-93c99b01e2a566d8d27400ffb6e2ee51R112-R135

## Actual behavior
envForm record not found 

<img width="457" alt="Screen Shot 2019-11-26 at 2 35 58 PM" src="https://user-images.githubusercontent.com/19851115/69614969-1abe4680-105a-11ea-8ef3-9a92e90e8c10.png">

## Expected behavior
envForm record should be added in dc

<img width="435" alt="Screen Shot 2019-11-26 at 2 37 35 PM" src="https://user-images.githubusercontent.com/19851115/69615092-535e2000-105a-11ea-9cc7-bdbea9e371f6.png">

**Comment by kadel** [comment]
> https://github.com/openshift/odo/pull/2398/files#diff-93c99b01e2a566d8d27400ffb6e2ee51R112-R135

This is not a valid bug. The problem is in the test. It is trying to link backend component to the backend component. see  https://github.com/openshift/odo/pull/2398/files#r350663133

**Comment by amitkrout** [comment]
> > https://github.com/openshift/odo/pull/2398/files#diff-93c99b01e2a566d8d27400ffb6e2ee51R112-R135
> 
> This is not a valid bug. The problem is in the test. It is trying to link backend component to the backend component. see https://github.com/openshift/odo/pull/2398/files#r350663133

/close
