### ISSUE TITLE
Avoid triggering CI job for only typo, comment and doc fix

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2417]
/kind enhancement

## Which functionality do you think we should update/improve?
Prow job triggering mechanism

## Why is this needed? 
To avoid unnecessary use of aws resources for fixes which are not part of any code change.

**Comment by kadel** [comment]
If it is any change in source code it needs to pass all the tests, even if it is just fixing typo.

Documentation shouldn't be a problem, as most of it is in a separate repo.
We have just a few *.md files in this repo that are not changed that often. I wouldn't worry about triggering tests for it. They are usually modified less than once per month.

Implementing checks to when trigger CI and when not to won't give us much benefit especially when comparing it to how much work this will need to make detection safe.

/close
