### ISSUE TITLE
Emphasize that odo is used for development not production

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2428]
/kind docs

## What mistake did you find / what is missing in the documentation?

Current we have:

```
OpenShift Do (odo) is a fast, iterative, and straightforward CLI tool for developers who write, build, and deploy applications on OpenShift.

Existing tools such as oc are more operations-focused and require a deep-understanding of Kubernetes and OpenShift concepts. odo abstracts away complex Kubernetes and OpenShift concepts for the developer, thus allowing developers to focus on what is most important to them: code.
```

We should elaborate on this and explain to the user that odo is meant for development and not production. We don't actually "deploy" applications to OpenShift, but rather write and build them. 

Two action items:

- An emphasis that it's meant for development use ONLY and we (potentially) have plans to deploy to production (whether that's knative, or something else, who knows). 
- Documentation on how to go from development (using odo) to using oc / deploying to production.

## What is the relevance of it?

Elaborating on the basic functionality of odo and being more clear.

**Comment by pmacko1** [comment]
this should be higher up :)
odo -> a tool for devs to have standardised container test environment. 

My naive question is -> what next? After the app is built, tested in containers, is it green to go to production off containers?

**Comment by Preeticp** [comment]
Needs docs

**Comment by cdrage** [comment]
@pmacko1 Yeah, there is no "next step" solution after odo since we focus on just the "inner loop" process at the moment. We need to emphasize that odo is currently for development only and that current outer-loop solutions are in development.
