### ISSUE TITLE
Update description for `--all` flag in `odo list`

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2452]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `master`

## How did you run odo exactly?
```sh
$ odo list
APP     NAME     PROJECT        TYPE       SOURCE        STATE
app     node     newproject     nodejs     file://./     Pushed

$ odo list --all
APP     NAME     PROJECT        TYPE       SOURCE        STATE
app     node     newproject     nodejs     file://./     Pushed

$ odo list --path ~/src
APP     NAME         PROJECT        TYPE       SOURCE                      STATE      CONTEXT
app     backend      myproject      java       target/wildwest-1.0.jar     Pushed     /home/dshah/src/Wild-West-Backend
app     frontend     myproject      nodejs     ./                          Pushed     /home/dshah/src/Wild-West-Frontend
app     node         newproject     nodejs     ./                          Pushed     /home/dshah/src/nodejs-ex

$ odo list --path ~/src --all
APP     NAME         PROJECT        TYPE       SOURCE                      STATE      CONTEXT
app     backend      myproject      java       target/wildwest-1.0.jar     Pushed     /home/dshah/src/Wild-West-Backend
app     frontend     myproject      nodejs     ./                          Pushed     /home/dshah/src/Wild-West-Frontend
app     node         newproject     nodejs     ./                          Pushed     /home/dshah/src/nodejs-ex

$ odo delete -f
This component has following urls that will be deleted with component
URL named url with host url-app-newproject.apps-crc.testing having protocol http at port 8080
 ✓  Deleting component node [23ms]
 ✓  Component node from application app has been deleted

$ odo list --path ~/src --all
APP     NAME         PROJECT        TYPE       SOURCE                      STATE          CONTEXT
app     backend      myproject      java       target/wildwest-1.0.jar     Pushed         /home/dshah/src/Wild-West-Backend
app     frontend     myproject      nodejs     ./                          Pushed         /home/dshah/src/Wild-West-Frontend
app     node         newproject     nodejs     ./                          Not Pushed     /home/dshah/src/nodejs-ex

$ odo list --path ~/src
APP     NAME         PROJECT        TYPE       SOURCE                      STATE          CONTEXT
app     backend      myproject      java       target/wildwest-1.0.jar     Pushed         /home/dshah/src/Wild-West-Backend
app     frontend     myproject      nodejs     ./                          Pushed         /home/dshah/src/Wild-West-Frontend
app     node         newproject     nodejs     ./                          Not Pushed     /home/dshah/src/nodejs-ex
```

## Actual behavior
I tried by setting different projects for the components and also tried by deleting the component from the cluster. However, I don't see any difference in the output of `odo list` command with `--all` flag.

## Expected behavior
There should be some difference in the output based on an extra flag. Or maybe I'm missing something naive!

**Comment by kadel** [comment]
/kind question

Ugh, we have a horrible description for this flag :-(

But if you want to find out what it is doing, you can just check the source code ;-)
https://github.com/openshift/odo/blob/54d35558f1835af6e1cd4b278166bea0e2fb7654/pkg/odo/cli/component/list.go#L84

Based on the code it looks like it is supposed to list components from all applications.

**Comment by kadel** [comment]
/retitle Update description for `--all` flag in `odo list`

Right now the description is just `Lists all components`.
It should be something like this: `List all components in all applications in a current project`

**Comment by dharmit** [comment]
> But if you want to find out what it is doing, you can just check the source code ;-)

My bad. I forget to wear the "developer" hat when I'm opening issues with "user" hat on. :smile:

**Comment by dharmit** [comment]
@mohitsuman @dgolovin any comments?

**Comment by mohitsuman** [comment]
@dharmit We currently only use `odo list --app ${app} --project ${project} -o json` to list the components.

**Comment by dharmit** [comment]
> @dharmit We currently only use `odo list --app ${app} --project ${project} -o json` to list the components. 

@kadel Since Adapters don't rely on it, I *think* we can remove `--all`
flag. `odo list` in itself is quite helpful already. WDYT?

**Comment by dharmit** [comment]
@mohitsuman @dgolovin We had a discussion about this issue on one of the team calls. It was mentioned that the `--all` flag was added based on request from the Adapters team. So, just being doubly sure here before we move ahead with removing the `--all` flag here. :wink:

**Comment by adisky** [comment]
@mohitsuman @dgolovin can we move ahead with removal of --all flag?

**Comment by adisky** [comment]
> @mohitsuman @dgolovin do the Adapters use this command (`odo list --all` which is shorthand for `odo component list --all`)? We're just trying to gather more info to take a decision that doesn't end up breaking anything.
> 
> UPDATE: To add more context, we're seeing that `odo list` and `odo list --all` generate exactly similar output. So, we could either remove the `--all` flag or change its behaviour to something that might be helpful.

@dharmit @kadel I ran  `odo list --all` command on my local setup, there is difference in the output, `odo list` lists component of current application, `odo list --all` lists all components of current project.
```
[adisky@localhost frontend]$ odo list
APP     NAME                     PROJECT     TYPE       SOURCE        STATE
app     nodejs-fend-lcbf         march       nodejs     file://./     Pushed
app     nodejs-frontend-uqwr     march       nodejs     file://./     Pushed
app     nodejs-mycomp3-ewks      march       nodejs     file://./     Pushed

[adisky@localhost frontend]$ odo list --all
APP      NAME                     PROJECT     TYPE       SOURCE        STATE
app2     nodejs-mycomp4-aqml      march       nodejs     file://./     Pushed
app      nodejs-fend-lcbf         march       nodejs     file://./     Pushed
app      nodejs-frontend-uqwr     march       nodejs     file://./     Pushed
app      nodejs-mycomp3-ewks      march       nodejs     file://./     Pushed
```
When run out of component folder, `odo list` lists nothing and `odo list --all`, lists components for current set project.
```
[adisky@localhost ~]$ odo list
 ✗  Please specify the application name and project name
Or use the command from inside a directory containing an odo component.
[adisky@localhost ~]$ odo list --all
APP      NAME                     PROJECT     TYPE       SOURCE        STATE
app      nodejs-fend-lcbf         march       nodejs     file://./     Pushed
app      nodejs-frontend-uqwr     march       nodejs     file://./     Pushed
app      nodejs-mycomp3-ewks      march       nodejs     file://./     Pushed
app2     nodejs-mycomp4-aqml      march       nodejs     file://./     Pushed
```

Do we still want to remove `--all` flag?

**Comment by dharmit** [comment]
It does seem to have a distinct functionality. And it's not bothering us in any way. I'd say we keep it.

**Comment by adisky** [comment]
I also suggest to to keep it, as `odo list --project` gives an error to specify `app` also, so there is no other way to list all components in a project.

**Comment by adisky** [comment]
As discussed with @kadel we are going to rename `--all` flag to `--all-apps`, and update the description `List all components in all applications in a current project`
