### ISSUE TITLE
Change the default PVC size of 1Gi to 10Gi

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2455]
/kind enhancement

## Which functionality do you think we should update/improve?

It's 2019, even my phone comes with 32Gb already included ;)

I tried running: https://github.com/gothinkster/vue-realworld-example-app

and found that I encountered an error of running out of space within the Node.js application. I checked PVC and found that we only use `1Gi`!

https://github.com/openshift/odo/blob/master/pkg/occlient/occlient.go#L1194

I suggest we:
- Change the default to 10Gi
- Allow the ability to set the default PVC similar to how we can set the minimum CPU and memory size.
- Remove the hardcoded variables of `1Gi`!

## Why is this needed? 

Because 1Gi isn't enough *at all*

**Comment by kadel** [comment]
@cdrage do you have a suggestion on how the configuration should look like?

**Comment by kadel** [comment]
not sure about changing the default - see https://github.com/openshift/odo/issues/755

**Comment by girishramnani** [comment]
we can make this PVC Size configurable? maybe a preference? suggestion on param name `ComponentVolumeSize`

**Comment by cdrage** [comment]
@kadel Yup. See initial description, I suggest we: `Allow the ability to set the default PVC similar to how we can set the minimum CPU and memory size.`

**Comment by girishramnani** [comment]
Then I would suggest to keep the PVC size to 1Gi and allow it to change. 10Gi is too big.

**Comment by kadel** [comment]
/close
in favor of https://github.com/openshift/odo/issues/2616
