### ISSUE TITLE
Add support for yarn / Node.js

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2456]
See upstream issue: https://github.com/openshift/odo-init-image/issues/47 we should be implementing support for `yarn`.

Cross-opening this issue here for further referencing.

**Comment by pyrobit** [comment]
This issue still needs a handy solution. I am struggling a lot to deploy with yarn. Did not find anysample config.yaml to properly set the yarn as main package manager and build steps for the app to properly work.
Nowadays developing with typescript it becomes really challenging to set up a deploy in openshift.
