### ISSUE TITLE
Autoselect local port for debug port forwarding

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2459]
/kind bug

## What versions of software are you using?

**Operating System:** Windows 10 Pro

**Output of `odo version`:** 1.0.1

## How did you run odo exactly?
Run `odo debug port-forward` for one component, 
```
C:\Temp\nodejs-ex>c:\Users\dgolo\.vs-openshift\odo debug port-forward
Started port forwarding at ports - 5858:5858
```

then cd to different context folder and run `odo debug port-forward` again

## Actual behavior

```
C:\Temp\nodejs-ex1>c:\Users\dgolo\.vs-openshift\odo debug port-forward
Started port forwarding at ports - 5858:5858
 X  Unable to listen on any of the requested ports: [{5858 5858}]
```

## Expected behavior

Two port forwarding works at the same time

**Comment by girishramnani** [comment]
the issue here is that local port `5858` is already in use hence this error is showing.
you can use a different port by providing `--local-port` argument like this
```
odo debug port-forward --local-port 5000
```

**Comment by kadel** [comment]
debug is still in tech-preview this is actually intentional design. 
As @girishramnani mentioned you have to specify local port manually if you want to debug multiple components at the same time.


/remove-kind bug
/kind feature
/retitle Autoselect local port for debug port forwarding
/priority medium

**Comment by kadel** [comment]
It should work like this:
- when `odo debug port-forward` is executed it first should test if the `DefaultDebugPort` is available. If it is, then use that as a local port. This will make sure that in most cases the port number is predictable.
- if `DefaultDebugPort` is already taken than odo can pick any available port (for example binding to port 0 does that)

**Comment by kadel** [comment]
## User Story
- As a user, I want to be able to simultaneously debug two components at the same time without manually selecting local ports.

## Acceptance criteria
- odo should use fixed default port as a default local port
- if the default port is not available it should automatically select available port

**Comment by kadel** [comment]
User story created in https://github.com/openshift/odo/issues/2606

**Comment by mik-dass** [comment]
@kadel I think we can close because of https://github.com/openshift/odo/pull/2648
