### ISSUE TITLE
Validation of cluster's capabilities to run operators and listing services

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2461]
[kind/Feature]

## Which functionality do you think we should add?
Checking the cluster version and validating the capabilities for running operators.
Checking if cluster has 
- some minimum `OperatorSource`s present to be useful
- has the service binding operator installed
- check the version of openshift

Listing all the possible operators and services that a user can create is also part of the this issue

## Why is this needed?
We want the operator backed services and service catalog backed services to co-exists. which means a user could run both a service-catalog service and operator using odo.
To allow this initially we need to check 
- possibility to run service-catalog services ( this becomes a necessary check for openshift 4+ )
- possibility to run operator-backed services

**Comment by kadel** [comment]
> has the service binding operator installed

Is ServiceBinging operator going to be a hard requirement?

> check the version of openshift

It should not depend on OpenShift version.  The important part is the presence of the OperatorHub.



I haven't seen mentioned listing of available operators in any other issues, so I assume that it should be part of this one.

 - When the cluster has both, ServiceCatalog and OperatorHub the listing should contain services that can be created by either of the methods (provisioner)
```
▶ odo catalog list services
NAME                                                  PROVISIONER
mariadb-ephemeral                                     ServiceCatalog
mongodb-ephemeral                                     ServiceCatalog
mysql-ephemeral                                       ServiceCatalog
mongodb-enterprise.v1.2.4                             OperatorHub
mariadb-operator-0.1.3-6                              OperatorHub
```

- When the cluster has just OperatorHub enabled the `odo catalog list services` should list all available services that can be deployed using operators, ServiceCatalog is silently ignored.
```
▶ odo catalog list services
NAME                                                  PROVISIONER
mongodb-enterprise.v1.2.4                             OperatorHub
mariadb-operator-0.1.3-6                              OperatorHub
```
- When the cluster has just ServiceCatalog enabled the `odo catalog list services` should list all available services that can be deployed using ServiceCatalog, OperatorHub is silently ignored.
```
▶ odo catalog list services
NAME                                                  PROVISIONER
mariadb-ephemeral                                     ServiceCatalog
mongodb-ephemeral                                     ServiceCatalog
mysql-ephemeral                                       ServiceCatalog
```

**Comment by girishramnani** [comment]
> Is ServiceBinging operator going to be a hard requirement?

I mean if you just want to start the operators and dont wanna link it with components then its not required

**Comment by girishramnani** [comment]
- we can move the check for service binding operator check to https://github.com/openshift/odo/issues/2463 issue
- as mentioned in the issue description 
> We want the operator backed services and service catalog backed services to co-exists

hence we will have a `Provisioner` or `Provider` column which provides the source of the service in the `odo catalog list services`

**Comment by girishramnani** [comment]
so some of the points have become invalid like checking the openshift version and checking if the service binding operator ( can be done lazily )

and hence currently the scope and AC of the issue about checking if service catalog is present, operator csvs are present, and then list them when odo catalog list service is executed

**Comment by dharmit** [comment]
We are working on a proposal document and hence moved the issue to "In Analysis" state. Goal is to come up with a proposal like we did for odo debug.

**Comment by dharmit** [comment]
At the moment, I'm working on making use of APIs provided by `github.com/operator-framework/operator-lifecycle-manager` to list the `ClusterServiceVersions` (equivalent to doing `oc get csvs` on CLI) available in the cluster.

As a part of this, I'm adding `OperatorsClient` to the definition of `Client` struct in `kclient` package. 

A few things that I'm still trying to figure out:

1. How do I create a `OperatorsClient` like we're doing `serviceCatalogClient, err := servicecatalogclienset.NewForConfig(config)` in `occlient` package?
2. How do I make sure that existing code in `occlient` package to list services provided by Service Catalog and the code I'm adding as a part of this issue work in tandem? Most likely, I'll add code for this issue in `kclient` and other odo specific packages. That should smooth things out.

I'll keep digging to figure the answers to these questions

**Comment by dharmit** [comment]
I guess I'm facing an issue with dependency management. I've pushed this commit https://github.com/dharmit/odo/commit/d6cf298f13b726c6b09b1a4b3eb1e6e297863725 to be able to list the clusterserviceversions. For that, I added the dependency on OLM [here](https://github.com/dharmit/odo/commit/bd6c1c30e7a137d541f7a9b550eba64eceb0dace#diff-395f41b2a27b70ce44399c91c82158c2). However, `make` is failing with below error:

```sh
$ make
go build -ldflags="-w -X github.com/openshift/odo/pkg/version.GITCOMMIT=d6cf298f1" cmd/odo/odo.go
# github.com/openshift/odo/vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:40:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:45:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:50:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:55:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:60:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:65:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:70:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go:75:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
# github.com/openshift/odo/vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:42:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:47:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:52:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:57:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:62:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:67:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:72:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:77:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:82:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:87:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGeneratedConversionFunc)
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go:87:13: too many errors
make: *** [Makefile:45: bin] Error 2
```

I tried to use a couple of older versions of OLM but that didn't help. What should I do?

PS: I'm not seeking code review. I know it looks like trash. I'm seeking to get past the dependency management problem.

**Comment by girishramnani** [comment]
If u use glide to `get` the dependency it will try all possible versions to make the code work.

**Comment by girishramnani** [comment]
https://github.com/Masterminds/glide#how-it-works
