### ISSUE TITLE
Instantiating operators using CRDs

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2462]
[kind/Feature]

## Which functionality do you think we should add?
Once we have validated a cluster, odo should have the functionality to instantiate an operator backed service using the CRD provided by it. 

## Why is this needed?
To allow openshift/kubernetes users to use operators.

**Comment by girishramnani** [comment]
The initial implementation will possibly be using the `alm-examples` array present in the `ClusterServiceVersion` of an operator.
An example array from keyclock operator looks like this -
```
[
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "Keycloak",
          "metadata": {
            "name": "example-keycloak",
            "labels": {
              "app": "sso"
            }
          },
          "spec": {
            "instances": 1,
            "extensions": [
              "https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar"
            ],
            "externalAccess": {
              "enabled": true
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakRealm",
          "metadata": {
            "name": "example-keycloakrealm"
          },
          "spec": {
            "realm": {
              "id": "basic",
              "realm": "basic",
              "enabled": true,
              "displayName": "Basic Realm"
            },
            "instanceSelector": {
              "matchLabels": {
                "app": "sso"
              }
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakBackup",
          "metadata": {
            "name": "example-keycloakbackup"
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakClient",
          "metadata": {
            "name": "client-secret",
            "labels": {
              "app": "sso"
            }
          },
          "spec": {
            "realmSelector": {
              "matchLabels": {
                "app": "sso"
              }
            },
            "client": {
              "clientId": "client-secret",
              "secret": "client-secret",
              "clientAuthenticatorType": "client-secret",
              "protocol": "openid-connect"
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakUser",
          "metadata": {
            "name": "example-realm-user",
            "labels": {
              "app": "sso"
            }
          },
          "spec": {
            "user": {
              "username": "realm_user",
              "firstName": "John",
              "lastName": "Doe",
              "email": "user@example.com",
              "enabled": true,
              "emailVerified": false
            },
            "realmSelector": {
              "matchLabels": {
                "app": "sso"
              }
            }
          }
        }
      ]
```

Issues with the above approach are
- `alm-examples` is an optional piece of metadata and hence developer of the operator might keep it blank
- Multiple examples are present in the array so we cannot determine the best one to use

**Comment by girishramnani** [comment]
we can also consider using the `validation.openAPIV3Schema` which is part of the CRD definition. But as far as I could tell this field is also not mandatory for the developer of the CRD to provide.

Someone has already tried to do this using a web-app
https://blog.openshift.com/openshift-4-2-declarative-dynamic-ui-for-your-operator

**Comment by dharmit** [comment]
Thinking out loud here.

I think what we need here is `InstallPlan` (check its definition in the table on [OLM arch page](https://github.com/operator-framework/operator-lifecycle-manager/blob/2feb5fc/doc/design/architecture.md#architecture)) for the operators that are installed in the cluster:
```sh
$ oc explain installplan
KIND:     InstallPlan
VERSION:  operators.coreos.com/v1alpha1

DESCRIPTION:
     Represents a plan to install and resolve dependencies for Cluster Services.

FIELDS:
   apiVersion   <string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#resources

   kind <string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds

   metadata     <Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata

   spec <Object>
     Spec for an InstallPlan
```

For example, I have two Operators installed in my cluster:
```sh
$ oc get csvs
NAME                        DISPLAY               VERSION   REPLACES                    PHASE
eap-operator.v1.0.0         JBoss EAP             1.0.0                                 Succeeded
prometheusoperator.0.32.0   Prometheus Operator   0.32.0    prometheusoperator.0.27.0   Succeeded
```

But I have `InstallPlan` only for the `prometheusoperator.0.32.0`:
```sh
$ oc get ip
NAME            CSV                         APPROVAL    APPROVED
install-nfbct   prometheusoperator.0.32.0   Automatic   true
```

With `InstallPlan` available in the cluster, we can offload the task of creating the service to OLM Operator (I don't know how to do this through CLI, but Web Console uses this IP when we create ) since it's the one responsible for creating applications defined by CSVs (ref. [OLM Operator](https://github.com/operator-framework/operator-lifecycle-manager/blob/2feb5fc/doc/design/architecture.md#olm-operator)).

The other Operator in my cluster `eap-operator.v1.0.0` doesn't have a corresponding IP and so when I want to create an application out of it (WildFly Server in this case), I need to provide the details manually. We can think of this as (mandatorily) using interactive mode to create an application/service out of this Operator.

I think we should use OLM operator (its APIs in our code) to create application/service in the cluster instead of trying to do it ourselves. Trying to deploy application/service by ourselves probably sounds like reinventing the wheel.

As I said, I'm thinking out loud here. :smile:

**Comment by girishramnani** [comment]
we need to also consider that an operator can have multiple CRs which can be created. like the Prometheus Operator has `Prometheus`, `ServiceMonitor`, `PodMonitor` etc. so we need detect these and allow users to do something like this
`odo service create ServiceMonitor` 

- for this to work we need to detect from the CR definition that `ServiceMonitor` requires `Prometheus` and we should show that as an error and suggest to create `Prometheus`

**Comment by dharmit** [comment]
> I think what we need here is InstallPlan

Upon further reading, I figured that `InstallPlan`s are for the life-cycle of the Operator itself. They don't seem to have much to do with spinning up the CRs.

**Comment by kadel** [comment]
Closing in favor of the https://github.com/openshift/odo/issues/2613 user story
