### ISSUE TITLE
Issue triage

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2465]
- make sure that all issues have proper labels
  - kind
  - area
- close outdated and invalid
- merge duplicates

/assign @girishramnani

**Comment by girishramnani** [comment]
reached #2095 ( going newest to oldest )

**Comment by dharmit** [comment]
I'll pick up from oldest in that case.

**Comment by dharmit** [comment]
Currently triaging issue 830.

**Comment by kadel** [comment]
Issues without kind: https://github.com/openshift/odo/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3Akind%2Fflake+-label%3Akind%2Fcleanup+-label%3Akind%2Fepic+-label%3Akind%2Fcode-refactoring+-label%3Akind%2Ftest+-label%3Akind%2Fdocumentation+-label%3Akind%2Fdiscussion+-label%3Akind%2Ffeature++-label%3Akind%2Fbug+

**Comment by girishramnani** [comment]
All issues mentioned @kadel now have kind and area. Hence closing this issue.
