### ISSUE TITLE
Support raw kubernetes in addition to openshift resource types

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#2468]
As a Developer, I'd like to use the same basic model of `odo` to create my application and components but for Kubernetes base distributions without the need for specific OpenShift capabilities such as Builds, ImageStreams, DeploymentConfigs, Routes and so on.

Additional consideration as part of this Epic would be to determine:

1.  Should the Kubernetes and OpenShift use cases be satisfied with 1 cli? The goal is a strong yes, 1 cli.
1. Should we rename the project to be something more neutral (most think of `odo` as "OpenShift Do") perhaps `udo` (thought of as "you do" or "unified do")? Recommended to pivot to a more neutral name such as `udo`.

**Comment by kadel** [comment]
The devfile support (https://github.com/openshift/odo/issues/2467) is going to be done using just vanilla Kubernetes resources. One exception might be a Route. Odo should be smart enough to autodetect OpenShift and use Route instead of Ingress.

**Comment by sspeiche** [comment]
This will be supported with devfile support for Kubernetes Deployments and Ingress. Need to add support for OpenShift Routes and DeploymentConfig.

**Comment by prietyc123** [comment]
There is no point in keeping this issue in milestone 1.2, hence deffering it to milestone 1.3

**Comment by kadel** [comment]
This is done. All devfile related operations are kubernetes "compatible".
Everything that we are doing from now on is taking Kubernetes into consideration.
