### ISSUE TITLE
Devfile components sync support

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2473]
Related to https://github.com/openshift/odo/issues/2470

- [ ] Implement source syncing to containers within a fat pod.
- [ ] Ignore files in .gitignore
- [ ] Sync delta changes instead of entire source

**Comment by johnmcollier** [comment]
As discussed on the odo dev meeting today:
- We'll keep the existing watch and sync technology, it works fine as-is, and should work well with Devfile projects
- Current sync function can only sync to one container
- As Devfile projects may deploy fat / multi-container pods, we may need to sync the source code to multiple containers, so need to modify the sync function to support that
    - However, we don't want to sync to **every** container
- We'll use the `mountsources` field in the devfile to determine which containers need access to the source code, and have a single shared volume with the source that those containers would mount
    - Means we only need to sync once

**Comment by johnmcollier** [comment]
Updating the plan for Devfile syncing:
- When creating the deployment for devfiles, create an emptyDir volume and mount it under `/projects`
    - `/projects` is the default mount path for projects in Che with devfiles
- If a component has `mountSources: true` set in it, we'll mount the emptyDir volume to it
- When syncing, we'll sync the source code to the first container we found that had set `mountSources: true`.
    - No need to sync across the other containers since they will be sharing the same volume.
