### ISSUE TITLE
status command for operators

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2479]
[kind/Feature]

## Which functionality do you think we should add?
Once a user has instantiated the operator, they can check the status of the operator using `odo service status`. This command was not present in the service catalog services.
`odo service status` becomes important for operators because there can be multiple CRs created and the user needs a way to know their status.

**Comment by kadel** [comment]
Service status is already displayed in `odo service list` for ServiceCatalog based services.
Do we really need an extra command for this? Couldn't it be included in the listing as with ServiceCatalog Services? If we decide to implement `odo service status` we need to implement it also for ServiceCatalog services.

**Comment by dharmit** [comment]
+1 we should just use `odo service list` for this unless there's a real need for `status` command.

**Comment by girishramnani** [comment]
got it, closing this issue then
