### ISSUE TITLE
odo service describe and odo catalog describe service for operators + services

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2480]
[kind/Feature]

## Which functionality do you think we should add?
A describe command in the form of `odo catalog describe service` can be added which explains the CRs present in the specific operator.

We need to also address the fact that an operator can have multiple CRs (e.g. `KeyCloak` and `KeyCloakUser` provided by `keycloak-operator` ) and hence the `describe` command should show all the CRs and some help.

There is already a `service catalog describe` command, we would need to make operators also work with it.

**Comment by kadel** [comment]
> We need to also address the fact that an operator can have multiple CRs (e.g. `KeyCloak` and `KeyCloakUser` provided by `keycloak-operator` ) and hence the `describe` command should show all the CRs and some help.

Isn't `KeyCloakUser` just a configuration for KeyCloack in form of CRD?

**Comment by kadel** [comment]
> A describe command in the form of `odo service describe` can be added which explains the CRs present in the specific operator. If the user provides a service name then we will use the output similar to `odo catalog describe service`.

I think that you are meshing two things together.
- `odo service describe` describes already provisioned service
- `odo catalog describes service` is a command that describes service from **odo** catalog of services. Those are services that can be deployed using odo.


Both commands (`odo service describe`  and  `odo catalog describes service`) need to work also with operator backed services.


> There is already a service catalog describe command `odo catalog describe service`, we would deprecate this command because operators are not necessarily part of a catalog.

catalog in `odo catalog` term was meant as a generic term as an odo catalog, not as something that is related to ServiceCatalog.
Even component types are part of the odo catalog.  `odo catalog list components`.



Example:
```
# I want to deploy mongodb, so I check if there is something in odo service catalog
odo catalog search service mongodb

# I saw that there is a service called mongodb so I want to know more details about it
odo catalog describes service mongodb

# I've decided to provision mongodb instance
odo service create mongodb

#I want to know details about my **running** mongodb instance
odo service describe mongodb

```

**Comment by girishramnani** [comment]
understood, changed the description and title of the issue

**Comment by dharmit** [comment]
@kadel there's no `odo service describe` command right now. The closest we have to describing (not listing) service right now is:
```sh
odo app describe app
Application Name: app has 1 component(s) and 1 service(s):
--------------------------------------
Component Name: node
Type: nodejs
Source: file://./
Environment Variables:
 · DEBUG_PORT=5858
--------------------------------------
Service Name: psql-1
Type: dh-postgresql-apb
Status: Provisioning
--------------------------------------
```
But one could argue that it's just `odo service list` output in a non-tabular fashion.
```sh
$ odo service list --app app
NAME       TYPE                  PLAN     STATUS
psql-1     dh-postgresql-apb     dev      ProvisionedSuccessfully
```

**Comment by kadel** [comment]
/close 
in favor of https://github.com/openshift/odo/issues/2615
