### ISSUE TITLE
enhance the odo service delete command to allow deletion of operators

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2481]
[kind/Feature]

## Which functionality do you think we should add?
Currently the `odo service delete` command only supports deleting services. We need to allow users to delete operators with the same command.

**Comment by dharmit** [comment]
> We need to allow users to delete operators with the same command.

Nitpicking here but I assume you mean that we need to augment the command be able to delete services/operands created from Operators and not the Operators themselves. :wink:

**Comment by dharmit** [comment]
We've got a user story covering this on #2792
