### ISSUE TITLE
 If flags are used other than default then verify the local config along with the changes done in dc

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2483]
- verify that the flags specified in `odo create` command are reflected in DC
-  example `odo create --memory 2G --cpu 2` than the DeploymentConfig should have the corresponding resource limits

the following flags should be validated:
-       --cpu string          Amount of cpu to be allocated to the component. ex. 100m or 0.1 (sets min-cpu and max-cpu to this value)
-      --env stringSlice     Environmental variables for the component. For example --env VariableName=Value
-      --max-cpu string      Limit maximum amount of cpu to be allocated to the component. ex. 1
-      --max-memory string   Limit maximum amount of memory to be allocated to the component. ex. 100Mi
-      --memory string       Amount of memory to be allocated to the component. ex. 100Mi (sets min-memory and max-memory to this value)
-      --min-cpu string      Limit minimum amount of cpu to be allocated to the component. ex. 100m
-      --min-memory string   Limit minimum amount of memory to be allocated to the component. ex. 100Mi
-  -p, --port stringSlice    Ports to be used when the component is created (ex. 8080,8100/tcp,9100/udp)

**Comment by prietyc123** [comment]
PR for this issue is almost related to https://github.com/openshift/odo/pull/2457 PR. So I am just waiting for the PR to get merged.

**Comment by prietyc123** [comment]
AFAIU all the flags are already verified in https://github.com/openshift/odo/blob/master/tests/helper/helper_oc.go except --port which I have covered in #2499 PR
