### ISSUE TITLE
we are still using odo.openshift.io/v1alpha1 as apiVersion for json output ( post GA )

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2490]
[kind/Feature]

## Which functionality do you think we should add?
We are still using `odo.openshift.io/v1alpha1` as the ApiVersion for 
machine readable output mostly everywhere in odo.
Post GA we should change it `odo.openshift.io/v1`?
https://github.com/openshift/odo/blob/d1d002d3b04ca02ec2c3593866e34c449d460946/pkg/machineoutput/types.go#L16

**Comment by kadel** [comment]
This is more of a question than a feature.
/kind discussion
/remove-kind json-output

**Comment by cdrage** [comment]
IMO yes. We should change it to `/v1`, however, we'll have to implement some form of backwards compatibility if there are any breaking changes.
