### ISSUE TITLE
Have checks for "bindingName" and "namespace" to avoid empty values in "CreateServiceBinding"

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2493]
/kind discussion

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
The unit tests for `CreateServiceBinding` function have empty value for `bindingName`. Yet the tests pass.

https://github.com/openshift/odo/blob/8df0edaacef0c4b74f8a7e28037c8cd4a8638953/pkg/occlient/occlient_test.go#L1396-L1408

However, when we pass an empty binding name to the OpenShift APIs, it fails to create the ServiceBinding. 

I changed the values of `bindingName` and `namespace` to `""` before the call to create a ServiceBinding. And it failed with below errors:
```sh
# when namespace is ""
odo service create dh-postgresql-apb psql-1 --plan dev -p postgresql_database=mydb -p postgresql_password=password -p postgresql_user=luke -p postgresql_version=10
Deploying service psql-1 of type: dh-postgresql-apb
 ✗  Deploying service [369ms]
 ✗  an empty namespace may not be set during creation

# when bindingNs is ""
$ odo service create dh-postgresql-apb psql-1 --plan dev -p postgresql_database=mydb -p postgresql_password=password -p postgresql_user=luke -p postgresql_version=10
Deploying service psql-1 of type: dh-postgresql-apb
 ✗  Deploying service [564ms]
 ✗  ServiceBinding.servicecatalog.k8s.io "" is invalid: [metadata.name: Required value: name or generateName is required, spec.instanceRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '
-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.secretName: Invalid value: "": a DNS-1123 subdomai
n must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```
## Actual behavior
Providing empty value for `bindingName` in unit tests work while it doesn't work when we use `odo service create` from the CLI

## Expected behavior
An explanation for the behaviour.

**Comment by dharmit** [comment]
For more context, refer the discussion on this comment https://github.com/openshift/odo/pull/2491#discussion_r362746030.

**Comment by kadel** [comment]
This is due to the fact that fakeClient doesn't send anything to the api server (which is the whole purpose of the fakeClient) and validations like this are the responsibility of the Kubernetes api server.

Is it correct that we don't have client-side validations for this and leave this up to the api server to return error? 
I would probably say that it is ok. The code will error out with a descriptive message when someone manages to do this from odo command line.
`CreateServiceBinding` is essentially just a wrapper for `ServiceBindings().Create()` and all the validations are handled on api server.

We could add validation to `CreateServiceBinding` but that is just duplicating what is already there in apiserver.


I think that this is a nice case to show unit test boundaries. 
A unit test should validate using fakeClient that the correct function is called.

Than integration or e2e test should be responsible for making sure that odo errors out correctly when someone tries to do this.

**Comment by dharmit** [comment]
Thanks for that explanation @kadel. 

> The code will error out with a descriptive message when someone manages to do this from odo command line.

And so it does when I set an empty value by hard coding it in the function.

>  CreateServiceBinding is essentially just a wrapper for ServiceBindings().Create() and all the validations are handled on api server.
We could add validation to CreateServiceBinding but that is just duplicating what is already there in apiserver.
I think that this is a nice case to show unit test boundaries.
A unit test should validate using fakeClient that the correct function is called.
Than integration or e2e test should be responsible for making sure that odo errors out correctly when someone tries to do this.

+1. I think this issue and #598 were the reason behind discussing setting unit test limits in the retro call this time. Checking for empty values in the function or in the tests is what underlying APIs do for us, IMO.

I'm inclined to close this one. But I'd like to know what @prietyc123 thinks since she's concerned about this. Also @mik-dass since he pointed this one in the first place.

**Comment by mik-dass** [comment]
> I'm inclined to close this one. But I'd like to know what @prietyc123 thinks since she's concerned about this. Also @mik-dass since he pointed this one in the first place.

I would still like empty validations done in our unit test itself as it's a bit faster than running the integration tests on the CI. On a slow network/cluster, the user sending the empty the values will have to wait a bit longer to know that the command has failed. If we handle it in our code itself, we can save a little bit of his/her time :D

**Comment by kadel** [comment]
> I would still like empty validations done in our unit test itself as it's a bit faster than running the integration tests on the CI. On a slow network/cluster, the user sending the empty the values will have to wait a bit longer to know that the command has failed. If we handle it in our code itself, we can save a little bit of his/her time :D

You are right, but what about code duplication? We are adding the same check that is already there later in the processing.

**Comment by mik-dass** [comment]
> You are right, but what about code duplication? We are adding the same check that is already there later in the processing.

Then I guess then we need to choose between the two.

**Comment by dharmit** [comment]
I'm going to close this because adding checks for something that's already handled by OpenShift doesn't make sense to me. If anyone feels otherwise and would like to have checks anyway, please feel free to reopen this.
