### ISSUE TITLE
suggestion for the the pull request template

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2495]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Currently the template has this quoted string. I would suggest that it could be a comment instead?
 
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring

**Comment by kadel** [comment]
Is there a line comment syntax for markdown?
 As far as I know, only HTML style block comments work (`<!-- !>`)

**Comment by girishramnani** [comment]
[//]: # (This may be the most platform independent comment)

**Comment by girishramnani** [comment]
I guess the current one is not bothering anyone so we should use what we have
