### ISSUE TITLE
Document using odo in disconnected environments

### ISSUE THREAD

**Issue by pmacko1** [openshift/odo#2513]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Documentation for using odo in disconnected environments:
(machine with `odo` is connected to the internet, cluster is disconnected, cluster's host is connected to the internet(?))

- [ ] Cluster configuration
- [ ] Linux
- [ ] MacOS
- [ ] Windows

## What is the relevance of it?

Relevant github issues:
https://github.com/openshift/odo/issues/2189
https://github.com/openshift/odo/issues/2478
https://github.com/openshift/odo/issues/2514
https://github.com/openshift/odo/issues/2286

**Comment by girishramnani** [comment]
The docs PR link https://github.com/openshift/openshift-docs/pull/20227

**Comment by boczkowska** [comment]
The docs PR has been approved and merged - https://github.com/openshift/openshift-docs/pull/20227

**Comment by amitkrout** [comment]
/close
Doc merged in upstream - https://github.com/openshift/openshift-docs/pull/20227
