### ISSUE TITLE
Validating java component on disconnected cluster

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2514]
/kind documentation

What to validate 

```
odo component create java
odo push
odo url create
odo push
# edit sourcode
odo push
```

**Comment by amitkrout** [comment]
@pmacko1 Steps for ```Deploying java app using odo in a restricted environment``` cc_ @kadel

There are two major steps to deploy a java component using odo in a restricted environment.

1. Mirror and export the odo-init-image
2. Create and push the component
    a. git component
    b. local source
    c. local binary

**How to upload the init image and exporting it through env ODO_BOOTSTRAPPER_IMAGE in a disconnected environment having a mirror registry :**

**Step 1:** Use base64 -w0 to encode your mirror registry's root CA content
```
$ echo <ContentOf_additional_ca> | base64 -d > disconnect-ca.crt
```

**Step 2:** Trust root CA certificate in your client platform and login to OpenShift mirror registry
```
$ sudo cp ./disconnect-ca.crt /etc/pki/ca-trust/source/anchors/<mirror-registry>.crt
$ sudo update-ca-trust enable
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
$ docker login <mirror-registry>:<port> -u <mirror_registry_username> -p <mirror_registry_password>
```
NOTE: CA certificate path varies platform wise. Here Fedora is being used as client platform.

**Step 4:** Mirror the odo init image
```
$ oc image mirror registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:latest <mirror-registry>:<port>/openshiftdo/odo-init-image-rhel7:latest
```

**Step 5:** Overwrite init image using environment variale ODO_BOOTSTRAPPER_IMAGE
```
$ export ODO_BOOTSTRAPPER_IMAGE=<mirror-registry>:<port>/openshiftdo/odo-init-image-rhel7:latest
```

**How to create and push a java component:**

**Step 1:** Check java image stream in OpenShift namespace
```
$ oc describe is java -n openshift
Name:                   java
[...]
11 (latest)
  tagged from <mirror-registry>:<port>/openjdk/openjdk-11-rhel7:latest
    prefer registry pullthrough when referencing this tag

  Build and run Java applications using Maven and OpenJDK 11.
  Tags: builder, java, openjdk
  Supports: java:11, java
  Example Repo: https://github.com/jboss-openshift/openshift-quickstarts

  ! error: Import failed (NotFound): dockerimage.image.openshift.io "<mirror-registry>:<port>/openjdk/openjdk-11-rhel7:latest" not found
      46 hours ago

[...]
```

**Step 2:** Import java builder image to the tag specified (latest)
```
$ oc image mirror registry.access.redhat.com/openjdk/openjdk-11-rhel7:latest <mirror-registry>:<port>/openjdk/openjdk-11-rhel7:latest
```

**Step 3:** Update the image stream
```
$ oc tag <mirror-registry>:<port>/openjdk/openjdk-11-rhel7:latest openjdk-11-rhel7:latest --scheduled
```

**Step 4:** Check the image is imported to openshift namespace
```
$ oc describe is java -n openshift
Name:                   java
[...]

11 (latest)
  tagged from <mirror-registry>:<port>/openjdk/openjdk-11-rhel7:latest
    prefer registry pullthrough when referencing this tag

  Build and run Java applications using Maven and OpenJDK 11.
  Tags: builder, java, openjdk
  Supports: java:11, java
  Example Repo: https://github.com/jboss-openshift/openshift-quickstarts

  * <mirror-registry>:<port>/openjdk/openjdk-11-rhel7@sha256:4453c8ab3c428d81b69258500908386c006f7dbacad02024b032cb56fa836f75
      19 hours ago
[...]
```

**Step 5:** Create a java component
**git component**
```
$ odo component create java --project java --git <your_git_source>
 ✓  Validating component [697ms]

Please use `odo push` command to create the component with source deployed
```
**Source component**
```
$ odo component create java --project java --context <your_local_source>
 ✓  Validating component [697ms]

Please use `odo push` command to create the component with source deployed
```
**Binary component**
```
$ odo component create java --project java --context <your_bin_source>
 ✓  Validating component [697ms]

Please use `odo push` command to create the component with source deployed
```

NOTE: A mirror maven registry should be created and configure with the cluster, so that maven packages will be downloaded form the mirror registry. To overwrite the mirror registry you can use ```odo config set --env MAVEN_MIRROR_URL=<mvn_mirror_registry>``` or ```odo component create nodejs --env MAVEN_MIRROR_URL=<mvn_mirror_registry>```.

Step 6: Push the java component
```
$ odo push
Validation
 ✓  Checking component [920ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [4s]
 ✓  Triggering build from git [342ms]
 ✓  Waiting for build to finish [1m]
 ✓  Deploying component java-tjfl [21s]

Pushing to component java-tjfl of type git
 ✓  Changes successfully pushed to component
```

NOTE: For local source or binary, push the component along with ```--context <your local source or binary>``` flag if source is not present in the working directory.

**Step 7:** Create the route
```
$ odo url create --port 8080
 ✓  URL java-tjfl-8080 created for component: java-tjfl

To create URL on the OpenShift Cluster, please use `odo push`
```

NOTE: Use ```--context <your local source or binary>``` flag if source is not present in the working directory.

**Step 8:** Push to apply the route
```
$ odo push
Validation
 ✓  Checking component [924ms]

Configuration changes
 ✓  Retrieving component data [2s]
 ✓  Triggering build from git [342ms]
 ✓  Waiting for build to finish [1m]
 ✓  Applying configuration [29s]

Applying URL changes
 ✓  URL java-tjfl-8080: http://<route> created

Pushing to component java-tjfl of type git
 ✓  Changes successfully pushed to component
```

NOTE: Use --context <your local source or binary> flag if source is not present in the working directory.

**Step 9:** Access the route
```
$ curl -I http://<route>
HTTP/1.1 200 OK
Date: Thu, 16 Jan 2020 04:02:12 GMT
Server: Javalin
Content-Type: text/plain
Content-Length: 0
Set-Cookie: 4a9b3b647e5e9e233eba98f2787d2097=954da7db821af3f383e552014a822644; path=/; HttpOnly
Cache-control: private
```

**Comment by kadel** [comment]
@amitkrout What is status on this?

**Comment by girishramnani** [comment]
This issue https://github.com/openshift/odo/issues/2513 was the outcome.
