### ISSUE TITLE
source type component push does not work in a proxy+disconnected cluster environment

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2516]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported type

**Output of `odo version`:**
master

## How did you run odo exactly?
1. Get a disconnected cluster with a proxy configured with it
2. odo create component --context ruby-ex/ --------- // For now i am using ruby component because the cluster i have is configured with ruby images only in the disconnected cluster
```
$ odo component create ruby --project rubylocal --context ruby-ex/
Warning: ruby is not fully supported by odo, and it is not guaranteed to work
 ✓  Validating component [493ms]

Please use `odo push` command to create the component with source deployed
```
3. odo push --context ruby-ex/
```
$ odo push --context ruby-ex/ -v 9
[...]
✓  Waiting for component to start [41s]
I0116 17:49:44.686426   15111 occlient.go:1784] Pod ruby-ruby-ex-hxfk-app-1-z2hwt is Running
 •  Syncing files to the component  ...
I0116 17:49:44.686520   15111 component.go:701] Copying files  to pod
I0116 17:49:44.686535   15111 occlient.go:2640] CopyFile arguments: localPath /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex, dest /tmp/src/ruby-ex, copyFiles [], globalExps [/home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex/.git /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex/.odo/odo-file-index.json]
I0116 17:49:44.686674   15111 occlient.go:2688] makeTar arguments: srcPath: /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex, destPath: /tmp/src/ruby-ex, files: []
I0116 17:49:44.686711   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex, destBase: /tmp/src, destFile: ruby-ex
I0116 17:49:44.686722   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex
I0116 17:49:44.686898   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/.git, destBase: /tmp/src, destFile: ruby-ex/.git
I0116 17:49:44.686910   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/.git
I0116 17:49:44.686933   15111 util.go:569] ignoring path /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex/.git because of glob rule /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex/.git
I0116 17:49:44.686944   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/.gitignore, destBase: /tmp/src, destFile: ruby-ex/.gitignore
I0116 17:49:44.686944   15111 round_trippers.go:386] curl -k -v -XPOST  -H "X-Stream-Protocol-Version: v4.channel.k8s.io" -H "X-Stream-Protocol-Version: v3.channel.k8s.io" -H "X-Stream-Protocol-Version: v2.channel.k8s.io" -H "X-Stream-Protocol-Version: channel.k8s.io" -H "Authorization: Bearer G8rCFirhCT2lTN5CljYz9kqnTu7B7TLjbxt4CVaHyik" 'https://api.airgap46-amit.qe.devcluster.openshift.com:6443/api/v1/namespaces/rubylocal/pods/ruby-ruby-ex-hxfk-app-1-z2hwt/exec?command=tar&command=xf&command=-&command=-C&command=%2Ftmp%2Fsrc&command=--strip&command=1&stderr=true&stdin=true&stdout=true'
I0116 17:49:44.686953   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/.gitignore
I0116 17:49:45.730600   15111 round_trippers.go:405] POST https://api.airgap46-amit.qe.devcluster.openshift.com:6443/api/v1/namespaces/rubylocal/pods/ruby-ruby-ex-hxfk-app-1-z2hwt/exec?command=tar&command=xf&command=-&command=-C&command=%2Ftmp%2Fsrc&command=--strip&command=1&stderr=true&stdin=true&stdout=true 101 Switching Protocols in 1043 milliseconds
I0116 17:49:45.730632   15111 round_trippers.go:411] Response Headers:
I0116 17:49:45.730642   15111 round_trippers.go:414]     Upgrade: SPDY/3.1
I0116 17:49:45.730649   15111 round_trippers.go:414]     X-Stream-Protocol-Version: v4.channel.k8s.io
I0116 17:49:45.730655   15111 round_trippers.go:414]     Date: Thu, 16 Jan 2020 12:19:44 GMT
I0116 17:49:45.730668   15111 round_trippers.go:414]     Connection: Upgrade
I0116 17:49:46.746978   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/.odo, destBase: /tmp/src, destFile: ruby-ex/.odo
I0116 17:49:46.747029   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/.odo
I0116 17:49:46.747317   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/.odo/config.yaml, destBase: /tmp/src, destFile: ruby-ex/.odo/config.yaml
I0116 17:49:46.747345   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/.odo/config.yaml
I0116 17:49:46.747788   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/.odo/odo-file-index.json, destBase: /tmp/src, destFile: ruby-ex/.odo/odo-file-index.json
I0116 17:49:46.747838   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/.odo/odo-file-index.json
I0116 17:49:46.747953   15111 util.go:569] ignoring path /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex/.odo/odo-file-index.json because of glob rule /home/amit/go/src/github.com/openshift/odo/test/ruby/ruby-ex/.odo/odo-file-index.json
I0116 17:49:46.747981   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/Gemfile, destBase: /tmp/src, destFile: ruby-ex/Gemfile
I0116 17:49:46.748001   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/Gemfile
I0116 17:49:46.751315   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/Gemfile.lock, destBase: /tmp/src, destFile: ruby-ex/Gemfile.lock
I0116 17:49:46.751359   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/Gemfile.lock
I0116 17:49:46.751756   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/README.md, destBase: /tmp/src, destFile: ruby-ex/README.md
I0116 17:49:46.751775   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/README.md
I0116 17:49:46.752109   15111 occlient.go:2731] recursiveTar arguments: srcBase: /home/amit/go/src/github.com/openshift/odo/test/ruby, srcFile: ruby-ex/config.ru, destBase: /tmp/src, destFile: ruby-ex/config.ru
I0116 17:49:46.752126   15111 occlient.go:2737] Corrected destinations: base: /tmp/src file: ruby-ex/config.ru
 ✓  Syncing files to the component [12s]
 •  Building component  ...
I0116 17:49:56.518978   15111 round_trippers.go:386] curl -k -v -XPOST  -H "X-Stream-Protocol-Version: v4.channel.k8s.io" -H "X-Stream-Protocol-Version: v3.channel.k8s.io" -H "X-Stream-Protocol-Version: v2.channel.k8s.io" -H "X-Stream-Protocol-Version: channel.k8s.io" -H "Authorization: Bearer G8rCFirhCT2lTN5CljYz9kqnTu7B7TLjbxt4CVaHyik" 'https://api.airgap46-amit.qe.devcluster.openshift.com:6443/api/v1/namespaces/rubylocal/pods/ruby-ruby-ex-hxfk-app-1-z2hwt/exec?command=%2Fopt%2Fodo%2Fbin%2Fassemble-and-restart&stderr=true&stdout=true'
I0116 17:49:57.616370   15111 round_trippers.go:405] POST https://api.airgap46-amit.qe.devcluster.openshift.com:6443/api/v1/namespaces/rubylocal/pods/ruby-ruby-ex-hxfk-app-1-z2hwt/exec?command=%2Fopt%2Fodo%2Fbin%2Fassemble-and-restart&stderr=true&stdout=true 101 Switching Protocols in 1097 milliseconds
I0116 17:49:57.616402   15111 round_trippers.go:411] Response Headers:
I0116 17:49:57.616412   15111 round_trippers.go:414]     X-Stream-Protocol-Version: v4.channel.k8s.io
I0116 17:49:57.616418   15111 round_trippers.go:414]     Date: Thu, 16 Jan 2020 12:19:56 GMT
I0116 17:49:57.616426   15111 round_trippers.go:414]     Connection: Upgrade
I0116 17:49:57.616432   15111 round_trippers.go:414]     Upgrade: SPDY/3.1
+ set -eo pipefail
+ export ODO_UTILS_DIR=/opt/odo
+ ODO_UTILS_DIR=/opt/odo
+ export ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
+ ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
++ /opt/odo/bin/getlanguage
+ IMAGE_LANG=
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS=' 
'
+ b_OFS=
+ OIFS=' 
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.dummy
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.gitignore
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.odo
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/Gemfile
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/Gemfile.lock
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/README.md
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/config.ru
+ OIFS=
+ IFS=' 
'
+ '[' -n rhscl/ruby-25-rhel7 ']'
+ '[' rhscl/ruby-25-rhel7 == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n '' ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --retry 2 --deployment --without development:test' ...
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
 ✗  Unable to build files
+ set -eo pipefail
+ export ODO_UTILS_DIR=/opt/odo
+ ODO_UTILS_DIR=/opt/odo
+ export ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
+ ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
++ /opt/odo/bin/getlanguage
+ IMAGE_LANG=
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS=' 
'
+ b_OFS=
+ OIFS=' 
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.dummy
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.gitignore
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.odo
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/Gemfile
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/Gemfile.lock
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/README.md
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/config.ru
+ OIFS=
+ IFS=' 
'
+ '[' -n rhscl/ruby-25-rhel7 ']'
+ '[' rhscl/ruby-25-rhel7 == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n '' ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --retry 2 --deployment --without development:test' ...
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/

 ✗  Building component [3m]
I0116 17:53:18.894697   15111 cmdutils.go:48] Error:
Failed to push component: ruby-ruby-ex-hxfk: unable to execute assemble script: error while streaming command: command terminated with exit code 17
 ✗  command terminated with exit code 17
```

## Actual behavior
It works only for git component for example ```odo component create --project ruby && odo push```. AFAIU things are going wrong when init image comes to run certain steps and may be init image involvement overwriting some original configuration in the deploy container. 

```
Retrying fetcher due to error (2/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
```

**NOTE:** Similar issue can be hit with nodejs and java component too.

## Expected behavior
ruby packages should be accessible, i mean odo push should be successful.

**Comment by amitkrout** [comment]
ping @mohammedzee1000 @girishramnani Let me figure out if i can hit the same error in proxy env cluster only. 

Will include @kadel only if we need his help to debug this.

**Comment by girishramnani** [comment]
As you can see there is a request to https://rubygems.org.
Gems in ruby are similar to npm packages in nodejs. So this would require us to setup an internal gems registry which contains all the gems that ur sample application is using.

**Comment by amitkrout** [comment]
> As you can see there is a request to https://rubygems.org.
> Gems in ruby are similar to npm packages in nodejs. So this would require us to setup an internal gems registry which contains all the gems that ur sample application is using.

@girishramnani Same can be hit even after setting an internal registry for nodejs too. It only fails when odo init image is involved in the component push steps. Whereas component push with ```--git``` works without any issue.

**Comment by amitkrout** [comment]
@girishramnani i am pasting the logs of git component push in the same cluster where it passes.

$ odo component create --project rubygit --git https://github.com/sclorg/ruby-ex.git
$ odo push 
[...]
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image image-registry.openshift-image-registry.svc:5000/openshift/ruby@sha256:aaccffc2334332e7a75a4c9a70a4f9de61e52d33e3aa2ecbca4a743e23162ea8
STEP 1: FROM image-registry.openshift-image-registry.svc:5000/openshift/ruby@sha256:aaccffc2334332e7a75a4c9a70a4f9de61e52d33e3aa2ecbca4a743e23162ea8
STEP 2: LABEL "io.openshift.build.commit.id"="c00ecd7c762590f1d52c316c7d00141a745ede18" "io.openshift.build.commit.ref"="master" "io.openshift.build.commit.message"="Merge pull request #25 from pvalena/master" "io.openshift.build.source-location"="https://github.com/sclorg/ruby-ex.git" "io.openshift.build.image"="image-registry.openshift-image-registry.svc:5000/openshift/ruby@sha256:aaccffc2334332e7a75a4c9a70a4f9de61e52d33e3aa2ecbca4a743e23162ea8" "io.openshift.build.commit.author"="Honza Horak <hhorak@redhat.com>" "io.openshift.build.commit.date"="Thu Dec 13 15:35:54 2018 +0100"
STEP 3: ENV OPENSHIFT_BUILD_NAME="ruby-tpef-app-1" OPENSHIFT_BUILD_NAMESPACE="rubygit" OPENSHIFT_BUILD_SOURCE="https://github.com/sclorg/ruby-ex.git" OPENSHIFT_BUILD_COMMIT="c00ecd7c762590f1d52c316c7d00141a745ede18" DEBUG_PORT="5858"
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 1001:0 /tmp/src
STEP 7: USER 1001
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --retry 2 --deployment --without development:test' ...
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/...............
Using bundler 1.16.1
Fetching puma 3.12.0
Installing puma 3.12.0 with native extensions
Fetching rack 2.0.6
Installing rack 2.0.6
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./bundle`
---> Cleaning up unused ruby gems ...
Running `bundle clean --verbose` with bundler 1.16.1
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Frozen, using resolution from the lockfile
STEP 9: CMD /usr/libexec/s2i/run
STEP 10: COMMIT temp.builder.openshift.io/rubygit/ruby-tpef-app-1:0c860183
Getting image source signatures
Copying blob sha256:5a92562cd21a35fc8c0ee33c58d88c5b6c1417cde40a2a83e630232435c4c1d5
Copying blob sha256:18ea39fd2965157d2f9011362919a340e134b5a053ebeca62a118f90983cbd58
Copying blob sha256:ac49297ec1c627dbf5c8cd6c447675489ec3550e7651534344bb9f27c4dae6db
Copying blob sha256:6953a567dfff60c737bdf8e0d614b2474d472a62ef7263e9bd704570116bbc7b
Copying blob sha256:ec67f98d005e8140e582fe2fa5ceb69be20eaeb169f97eeebccdfe8082b6c6ca
Copying blob sha256:7ffb6f18066fc526001a2b913860cbc1d65c0585b077230e2294c019ea236ebd
Copying config sha256:ccb518e4c380337a316549f7117c86abbbb4fc8d0a9d246de2e70e04e3d386f9
Writing manifest to image destination
Storing signatures
[...]

**Comment by amitkrout** [comment]
@mohammedzee1000 @girishramnani It seems #2478 and #2514 may also hit the same issue for binary and source type component push

**Comment by amitkrout** [comment]
@girishramnani @mohammedzee1000 I verifies the same scenario on a cluster that runs behind the proxy and there it works fine i mean source type component push goes well. May be this problem resides in a particular usecase like disconnected + proxy.

**Comment by kadel** [comment]
Git component is working because the build Pod is configured to use a proxy via `HTTPS_PROXY` and `HTTP_PROXY` env variables.

You can verify it by creating s2i build using `oc new-app` and checking env variables set in build pod
```
oc new-app https://github.com/sclorg/ruby-ex.git
oc exec -it ruby-ex-1-build env
```
in the output of the `env` command, you can see that proxy related env variables like `HTTP_PROXY` `HTTPS_PROXY`  and `NO_PROXY`  are set

I'm not sure what is injecting those variables there. **I'll leave this for you to investigate.**


Quick workaround and the way to validate that proxy is being used is to set  `HTTP_PROXY` `HTTPS_PROXY` for odo component.
```
odo component create ruby --env HTTPS_PROXY=<proxy url> --env HTTP_PROXY=<proxy url>
```

`<proxy url>` will depend on a cluster. You can obtain it from either cluster config or from the `env` in a build pod as shown above

**Comment by amitkrout** [comment]
> Git component is working because the build Pod is configured to use a proxy via HTTPS_PROXY and HTTP_PROXY env variables.
You can verify it by creating s2i build using oc new-app and checking env variables set in build pod
oc new-app https://github.com/sclorg/ruby-ex.git
oc exec -it ruby-ex-1-build env
in the output of the env command, you can see that proxy related env variables like HTTP_PROXY HTTPS_PROXY and NO_PROXY are set
I'm not sure what is injecting those variables there. I'll leave this for you to investigate.

Will check for sure. Thanks

> Quick workaround and the way to validate that proxy is being used is to set HTTP_PROXY HTTPS_PROXY for odo component.
odo component create ruby --env HTTPS_PROXY=<proxy url> --env HTTP_PROXY=<proxy url>
<proxy url> will depend on a cluster. You can obtain it from either cluster config or from the env in a build pod as shown above

I got the proxy details from flexy job console and i created the component as you suggested. It worked properly.

> But we need to investigate how it is injected into build pod and try to do the same for odo components. So the user doesn't have have to worry about configuring HTTP_PROXY manually.
Another option would be to detect programmatically that odo is running against disconnected cluster and make odo set HTTP_PROXY, that would also require autodetecting correct proxy url

+1, ping @girishramnani @mohammedzee1000
