### ISSUE TITLE
Test script requires authentication from registry.redhat.io

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2537]
[kind/Feature]

## Which functionality do you think we should add?

Actually our test script runs inside a container (https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-master__v4.1.yaml#L10). So for this container, may be I need to get the secret and apply/use that to the running cluster on aws.

To pull the supported image available only in `registry.redhat.io` we need account service credentials to be configured in the main CI and should be mounted to the test container.

## Why is this needed?

To fix the issue where account service credentials are required. eg: Pulling supported builder images from `registry.redhat.io`

**Comment by girishramnani** [comment]
any update on this @prietyc123 ?

**Comment by prietyc123** [comment]
> any update on this @prietyc123 ?

As per the discussion in [comment](https://github.com/openshift/odo/pull/2668#pullrequestreview-378918703) It was blocked

**Comment by prietyc123** [comment]
Unfortunately the secret mount is not supported for `template-based tests` that we are using. The bad news is even platform team has no plan for adding the support specially for template-based tests. This is the slack message i got from @petr-muller 
``` 
The test that you linked is a template-based test, so the feature does not work there (and we do not plan to backport it to template-based tests).
```
I am clueless atm to run this test. @amitkrout  @mohammedzee1000  feel free to post your suggestion.

**Comment by petr-muller** [comment]
@prietyc123 @amitkrout @mohammedzee1000 I was looking into this a bit more, and one option (not even involving that much effort) you have is to port your e2e test from templates to the new multi-stage feature. That test does not use any arcane template nor some minor cloud platform, and porting it to multi-stage should be fairly easy and everything your test needs should be supported (provided we are talking about [these](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml#L15-L21) tests). After that you should be able to use the custom credential features for multi-stage tests. 

You can find the documentation on multi-stage [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml#L15-L21). You would use the `ipi-aws` [workflow ](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/workflow/ipi-aws) (that's a multi-stage "version" of the `openshift_installer_src` template you are using now, and you would supply a custom step that runs your tests in your ci-operator config file. That step can then use the [custom credentials](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/help#credentials) feature.

**Comment by petr-muller** [comment]
Since my last comment we also added an example to the documentation that shows how a section from a workflow can be supplemented with literal (not shared) steps, which is the equivalent of the `openshift_installer_src` functionality. See the third example in [this section](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/help#config).

**Comment by amitkrout** [comment]
The list of supported images which falls under this category are ```registry.redhat.io/openjdk/openjdk-11-rhel8``` and ```registry.redhat.io/rhscl/nodejs-12-rhel7```. 

Supported container images mapping file - https://github.com/openshift/odo-init-image/blob/master/language-scripts/image-mappings.json
