### ISSUE TITLE
Run unit test on windows and macOS

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2539]
kind/Feature

## Which functionality do you think we should add?

We can borrow macOS host on travis and windows from appveyor then only we can start our unit test on these hosts.

## Why is this needed?

This is not yet implemented in our test CI.

**Comment by kadel** [comment]
## User Story
- As an odo developer
- I want to be sure that the code that I have produced runs on all 3 platforms (mac, windows, linux)


## Acceptance Criteria
- odo unit tests should be executed on all 3 platforms for every open PR

/kind user-story

**Comment by amitkrout** [comment]
- [ ] Run unit test on OSX

- [ ] Run unit test windows

**Comment by amitkrout** [comment]
@prietyc123 Found a nice blog of windows support on travis - https://blog.travis-ci.com/2018-10-11-windows-early-release. Can you please try this out
