### ISSUE TITLE
Image stream nodejs with tag 8 is not available on OpenShift 4.4 cluster

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2542]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master
## How did you run odo exactly?
make test-integration against OpenShift 4.4 cluster

## Actual behavior
Nodejs with tag 8 is not available on OpenShift 4.4 cluster, so test that uses nadejs:8 for component creation are failing

## Expected behavior
Should pass, however we need to check if the source we are using for nodejs:8 builder image is working on latest or not. May be its time to make our source example image version independent.

**Comment by kadel** [comment]
It looks like we might have to start using different image versions for each OpenShift version.
At some point (and we might already be there) there will be no overlap between images available in  OpenShift 4 and OpenShift 3.

**Comment by amitkrout** [comment]
> It looks like we might have to start using different image versions for each OpenShift version.
> At some point (and we might already be there) there will be no overlap between images available in OpenShift 4 and OpenShift 3.

Right, However as an alternate solution we can also consider ```latest``` tag Instead of passing the different image version for each OpenShift version. Then in this case we just need to make sure that the source example we are using should be compatible with latest image tag.

**Comment by kadel** [comment]
> Right, However as an alternate solution we can also consider `latest` tag Instead of passing the different image version for each OpenShift version. Then in this case we just need to make sure that the source example we are using should be compatible with latest image tag.

That is also an option
