### ISSUE TITLE
Error when executing service create with a -p key=value where the value contains one or more commas

### ISSUE THREAD

**Issue by LiveByTheCode** [openshift/odo#2547]
/kind bug

## What versions of software are you using?

**Operating System:** 

macOS 10.15.2

**Output of `odo version`:** 

v1.1.0

## How did you run odo exactly?

odo service create amq-broker-72-gluster -p AMQ_PROTOCOL=amqp -p AMQ_QUEUES=queue1,queue2,queue3,queue4 -p AMQ_USER=test_user -p AMQ_PASSWORD=some_password

## Actual behavior

parameters not provided in key=value format

## Expected behavior

Deploying service amq-broker-72-gluster of type: amq-broker-72-gluster

## Any logs, error output, etc?

parameters not provided in key=value format

**Comment by kadel** [comment]
@LiveByTheCode, thank you for  report this issue and even more on submitting the PR 👍

**Comment by kadel** [comment]
fixed in #2548 
/close
