### ISSUE TITLE
Go Version in travis CI

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2551]
kind/Feature

## Which functionality do you think we should add?

Specific go version in travis CI

## Why is this needed? 

We are having the below issue with go version 1.11.2 in travis CI while executing unit test on macOS. It seems specific go version does not work properly during unit test execution. But surprisingly with the same go version unit test works fine on Linux system in travis CI. May be the go version 1.11.2 doesn't handle temp path properly on macOS.

However unit test works fine with go version 1.13.1 on macOS.

Team, Can you please share your thoughts about the appropriate go version on travis CI?

```
E0131 05:08:03.195040    5465 watch.go:183] Failed getting details of the changed file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis372271615/tests216276105/test_read_licenses.py563585660. Ignoring the change

E0131 05:08:03.197046    5465 watch.go:189] Ignoring event for file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis372271615/tests216276105/test_read_licenses.py563585660 as details about the file couldn't be fetched

--- FAIL: TestWatchAndPush (9.48s)
[...]
```

**Comment by kadel** [comment]
> Team, Can you please share your thoughts about the appropriate go version on travis CI?

just use latest go stable release
/close

**Comment by kadel** [comment]
sorry, reopened by a mistake

**Comment by amitkrout** [comment]
> sorry, reopened by a mistake

/close
