### ISSUE TITLE
Clean up json output making it simpler

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#2573]
[kind/Feature]

## Which functionality do you think we should add?
There is a lot of scatter in json output code with things that should not need to repeat, being repeated increases chances of having non-uniform json output

## Why is this needed?
Cleanup will help make it easier to code

**Comment by amitkrout** [comment]
@mohammedzee1000 This not a feature request. So can you please apply the correct label for example ```/kind cleanup``` of ```/kind code-refactor```

**Comment by kadel** [comment]
> There is a lot of scatter in json output code with things that should not need to repeat, being repeated increases chances of having non-uniform json output

@mohammedzee1000 can you please list things that need to be fixed?

/kind cleanup
/area json-output

**Comment by mohammedzee1000** [comment]
Will do
