### ISSUE TITLE
codecov.io reports fishy behavior

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2575]
/kind bug

## What versions of software are you using?

**Operating System:**
CI
**Output of `odo version`:**
master
## How did you run odo exactly?
Send a pr

## Actual behavior
Most of the time watch.go is reported as a culprit though the file is not touched in the pr. For example - https://github.com/openshift/odo/pull/2572

<img width="835" alt="Screen Shot 2020-02-07 at 3 57 45 PM" src="https://user-images.githubusercontent.com/19851115/74022038-bbb66f80-49c2-11ea-8860-3d027a356b3f.png">

## Expected behavior
Coverage should only be calculated on those file which are part of ```go list  ./... | grep -v github.com/openshift/odo/vendor | grep -v github.com/openshift/odo/tests``` and if the pr doesn't touch the file within the list then coverage report should not report any decrease or increase in coverage for the same pr.

**Comment by johnmcollier** [comment]
Similarly, I also noticed this with @kadel's PR to update the OWNERS file: https://github.com/openshift/odo/pull/2556#issuecomment-582055553

Codecov reported a 0.49% increase in code coverage for the OWNERS file update, which doesn't make sense haha.
