### ISSUE TITLE
Odo push should deploy local Docker containers when pushtarget is set to Docker

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2579]
## User Story
As a user, I want to be able to create components in odo (using `odo create component`), and be able to deploy the same set of devfiles locally, as I would on Kube. This also means `odo create component` should also be identical, [regardless of the context that's being targeted](https://github.com/openshift/odo/issues/2577).

## Acceptance Criteria 
- [x] Devfiles that work on Kube with Odo, should also work locally with odo.
    - The `odo create component` command should function the same as it would on Kube
- [x] `odo push` should deploy containers on the users system via Docker
    - Each container in the devfile corresponds to a container on Docker
- [x] Unit and integration tests
    - Integration tests to only run on Travis CI

## Links 
- Parent epic: https://github.com/openshift/odo/issues/2576

/kind user-story

**Comment by kadel** [comment]
I don't think all this was implemented in #2806
/reopen

**Comment by johnmcollier** [comment]
@kadel Initially this story covered sync and exec as well, but @elsony and I made the decision to split that functionality off into https://github.com/openshift/odo/issues/2717, so my PR that was merged covered everything that was in scope for this issue (deploying containers when pushtarget is set, and integration test platform for odo-docker). Can this issue be closed?
