### ISSUE TITLE
Use 'odo delete` to delete a component that's running locally with odo

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2581]
## User Story
As a user, I will need to be able to delete the applications I've deployed and developed with locally (on Docker), just as I can on Kube right now. `odo delete <component>` should remove all of the running containers for that application, alongside any volumes or other resources that were created.

## Acceptance Criteria 
- [ ] It should clean up all of the resources deployed for that component + the component's config
- [ ] It should use the same command as on Kube
- [ ] When delete, only remove the container and leave the images around

## Links 
- Parent epic: https://github.com/openshift/odo/issues/2576

/kind user-story

**Comment by jgwest** [comment]
First PR has merged. Since the first PR does not include support for deleting non-source volumes (the non-source volumes PR has not been merged at time of first PR) I will be posting a second PR shortly to complete this user story.

This issue should remain open until second PR has merged.

**Comment by elsony** [comment]
Code merged, feature done
