### ISSUE TITLE
Add ability to create application resource/template from stack

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2582]
## User Story
As a user, I want to be able to use odo to point to a devfile/stack that has its own application template associated with it, and have the template generated on my disk. This will be similar to the `appsody init` command that we're trying to replicate in odo.

## Acceptance Criteria 
- [ ] It should clone/download project/application resources on my disk from a template associated with a stack/devfile
     - If `sparseCheckoutDir` is set, need to pull down the specified folder from the git repo, rather than the entire repo
- [ ] resource creation will only be triggered when:

1. experimental flag has been enabled

1. the component is a devfile component

1. there is a project defined in the devfile of the given component

1. `odo component create` command called with a `--downloadSource` flag

- [ ] if a devfile contains a command called `devInit`, the devInit command will be executed at the end of the `odo component create` to do any init setup that the stack needs
- [ ] the `devInit` command should function similarly (if not equivalently) to the `appsody init` command

## Links 
- Parent epic: https://github.com/openshift/odo/issues/2576

CC @neeraj-laad

/kind user-story
/area devfile

**Comment by elsony** [comment]
Added more details on the requirement on the description

**Comment by elsony** [comment]
Based on the Sprint plan discussion, we need to figure out a better name than `--createResource` to clarify that the creation/cloning of resource is on the local file system instead of creating Kube resources.

**Comment by EnriqueL8** [comment]
@upLukeWeston and I added some notes on this issue [here](https://docs.google.com/document/d/1vTWDRV4sfJPn_O3DNDZPd7O4ZXCRjVeXKjsYZuziPkE/edit?usp=sharing)
FYI: @johnmcollier @elsony

**Comment by GeekArthur** [comment]
FYI, this issue https://github.com/openshift/odo/issues/2850 description includes the rough design for template support, we can discuss and finalize the design later then just use one issue for tracking purpose.

**Comment by elsony** [comment]
This item is done with the remaining issues have separate items open
