### ISSUE TITLE
Package github.com/Netflix/go-expect affecting some unit tests on Windows

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2586]
/kind bug

## What versions of software are you using?

**Operating System:** windows 10

**Output of `odo version`:** master

## How did you run odo exactly?

```make test``` on windows

## Actual behavior

Some unit tests are failing.

## Expected behavior

```make test``` should pass successfully

## Any logs, error output, etc?

Ref : https://travis-ci.com/openshift/odo/jobs/284808147

**Comment by amitkrout** [comment]
@prietyc123 https://github.com/openshift/odo/pull/2562#issuecomment-586195763

**Comment by prietyc123** [comment]
https://github.com/openshift/odo/issues/2630#issuecomment-600982744

/close
