### ISSUE TITLE
devfile support for odo delete

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2591]
Related to #2470

## User Story
As a user, I want to be able delete the devfile components that I have created before so that it will do all the necessary cleanup.

## Acceptance Criteria 
- [ ] odo delete command should delete the devfile component that has been created before.
- [ ] it should behave similar to the existing odo delete command
- [ ] delete will do all the necessary clean up as needed, e.g. containers, etc.
- [ ] this code path will only be triggered when EXPERIMENTAL flag has been enabled

/kind user-story
/area devfile

**Comment by mik-dass** [comment]
@elsony @kadel @girishramnani Should this command delete the env folder and the devfile itself?

**Comment by girishramnani** [comment]
I would suggest we follow the same process of delete the cluster side resources on `odo delete` and `odo delete --all` should delete local resources like `devfile` and the env folder

**Comment by kadel** [comment]
> I would suggest we follow the same process of delete the cluster side resources on `odo delete` and `odo delete --all` should delete local resources like `devfile` and the env folder

yes for env folder, that should be deleted with `odo delete --all`.
 Not so sure about devfile :-( devfile.yaml could be created by something else than odo, and in that case, user won't expect that it will get deleted by odo command.

**Comment by girishramnani** [comment]
well then lets keep devfile in its place and if someone requests for it be removed we can add a follow up PR

**Comment by elsony** [comment]
+1 on keeping the devfile. I'd consider the devfile to be part of the user resource after it has been created.  Therefore, we'll never delete that even on a `odo delete all`.

**Comment by elsony** [comment]
@mik-dass This items has been marked for review but the corresponding PR #2763 is still marked as WIP.  Do you think this story will be able to make Sprint 181?

**Comment by mik-dass** [comment]
> @mik-dass This items has been marked for review but the corresponding PR #2763 is still marked as WIP. Do you think this story will be able to make Sprint 181?

Yes it's ready for review. Once the CI is green, I will remove the WIP status.
