### ISSUE TITLE
Issues with localConfigInfo in common_push.go

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2602]
/kind bug

## How did you run odo exactly?

So... for some reason, `LocalConfigInfo` is imported twice into `component/create.go` here:

https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L48

Which then imports it twice in `common_push.go`...

https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/common_push.go#L31

```go
type CommonPushOptions struct {
	ignores []string
	show    bool

	sourceType       config.SrcType
	sourcePath       string
	componentContext string
	LocalConfigInfo  *config.LocalConfigInfo

	pushConfig         bool
	pushSource         bool
	forceBuild         bool
	doesComponentExist bool

	*genericclioptions.Context
}
```

Because in `*genericclioptions.Context` we also import LocalConfigInfo...

https://github.com/openshift/odo/blob/master/pkg/odo/genericclioptions/context.go#L314

Causing a conflict when implementing: https://github.com/openshift/odo/pull/2532

Because LocalConfigInfo ends up being blank..

This needs to be fixed in order to no longer have any conflicting LocalConfigInfo's / null pointers.

## Actual behavior

Incorrect LocalConfigInfo being returned

## Expected behavior

Correct LocalConfigInfo being returned.

We should also refactor the code that's being used in common_push.go as it conflicts with code that's also in `component/describe.go` which uses a different way to retrieve the local context / LocalConfigInfo.

## Any logs, error output, etc?

Running https://github.com/openshift/odo/pull/2532 pulls in incorrect LocalConfgInfo.

**Comment by cdrage** [comment]
Ping @mik-dass  and @girishramnani I believe you two are the best suited for the task. I tried some simple debugging but found I would fix one bug, cause 99 others haha

**Comment by cdrage** [comment]
Setting priority as high as this is affecting us adding new features (`odo create -o json`) and this has already as well as can cause more issues in the future.

**Comment by cdrage** [comment]
ping @mik-dass @girishramnani

**Comment by girishramnani** [comment]
and it seems this is happening at multiple places -

- Describe uses ComponentOptions which has context ( which has localconfiginfo ) https://github.com/openshift/odo/blob/de1aa2bcb44e8f1106d49454952c718b814e9fe4/pkg/odo/cli/component/describe.go#L31
- similarly watchOptions https://github.com/openshift/odo/blob/de1aa2bcb44e8f1106d49454952c718b814e9fe4/pkg/odo/cli/component/watch.go#L45
- PortforwardOptions 
https://github.com/openshift/odo/blob/df2a46a67cfbcce11c2be29340a6bde961d187b2/pkg/odo/cli/debug/portforward.go#L33
- StorageDeleteOptions https://github.com/openshift/odo/blob/de1aa2bcb44e8f1106d49454952c718b814e9fe4/pkg/odo/cli/storage/delete.go#L30
- StorageListOptions https://github.com/openshift/odo/blob/949bcb3c01d40a3dfaf4b379b8a49f894d7e11df/pkg/odo/cli/storage/list.go#L34
- URLListOptions
https://github.com/openshift/odo/blob/de1aa2bcb44e8f1106d49454952c718b814e9fe4/pkg/odo/cli/url/list.go#L32

**Comment by dharmit** [comment]
@cdrage 

> So... for some reason, `LocalConfigInfo` is imported twice into `component/create.go` here:
> 
> https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L48
> 
> Which then imports it twice in `common_push.go`...
> 
> https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/common_push.go#L31

It's more helpful to refer the commit pointed to by `master` at the time of opening an issue instead of referring to the `master` branch since `master` keeps getting updated throughout the day. :wink:
