### ISSUE TITLE
update nodejs images in the supported component catalog

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2603]
## User Story
As a developer I would like to use nodejs 12 images with all the features odo provides which includes experimental features like `odo debug`.

## Acceptance Criteria 
- [ ] Basic features of odo should work correctly with new nodejs images (centos/nodejs-12-centos7`, `rhscl/nodejs-12-rhel7` and `nodeshift/centos7-s2i-nodejs`)
- [ ] experimental features like odo debug should work correctly with new nodejs images
- [ ] tests should all run against these new images and pass
- [ ] It should show new `nodejs` images which are `centos/nodejs-12-centos7`, `rhscl/nodejs-12-rhel7` and `nodeshift/centos7-s2i-nodejs` as supported images when ran `odo catalog list components`, But this should happen only when 3 ACs above are fulfilled.

## Links 
- Feature Request: NA
- Related issue: https://github.com/openshift/openshift-docs/pull/19597

/kind user-story

**Comment by girishramnani** [comment]
I would need to verify that all of these images work in a sample nodejs application and using debug mode as well.
After that I would open a PR on odo-init-image to add the images in the supported list then a similar PR on this Repo.

**Comment by kadel** [comment]
```
▶ oc get is nodejs -n openshift
NAME     IMAGE REPOSITORY                                                    TAGS                         UPDATED
nodejs   image-registry.openshift-image-registry.svc:5000/openshift/nodejs   10,10-SCL,8,8-RHOAR,latest   About an hour ago
```

**Comment by kadel** [comment]
```
▶ oc get is nodejs -n openshift
NAME     IMAGE REPOSITORY                                                    TAGS           UPDATED
nodejs   image-registry.openshift-image-registry.svc:5000/openshift/nodejs   10,12,latest   55 minutes ago

▶ oc version
Client Version: 4.4.0-0.ci-2020-02-18-230529
Server Version: 4.4.0-0.ci-2020-02-18-230529
Kubernetes Version: v1.17.1
```

**Comment by lholmquist** [comment]
The nodeshift images mentioned above are no longer supported since we've migrated to using the images from rhscl

For our community examples, we've also moved from centos to ubi

**Comment by kadel** [comment]
> The nodeshift images mentioned above are no longer supported since we've migrated to using the images from rhscl
> 
> For our community examples, we've also moved from centos to ubi

How about existing 3.11 clusters? Are those somehow updated to deprecate those images?

**Comment by girishramnani** [comment]
The older images are not removed/deprecated. I check it but also verified by this comment https://github.com/openshift/openshift-docs/pull/19597#issuecomment-586220599

**Comment by lholmquist** [comment]
Also see this comment: https://github.com/openshift/openshift-docs/pull/19597#issuecomment-586220599

>nodejs-8-rhel7 as well as both versions of rhoar-nodejs are no longer supported. While OpenShift does not update imagestreams in stable branches, that does not mean we should encourage further use of unsupported versions.

**Comment by girishramnani** [comment]
we need to resolve these issues https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3Anext-oc-version before we could add nodejs:12 as supported image

**Comment by kadel** [comment]
> we need to resolve these issues https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3Anext-oc-version before we could add nodejs:12 as supported image

no, we need to resolve this first! Some of the issues will go away when nodejs images are marked as resolved.

We need to add nodejs images into supported images and test what issues will be fixed!
