### ISSUE TITLE
odo catalog commands without existing component

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2605]
# User Story
- As a user, I want to list items from `odo catalog` without creating a component first.

## Acceptance Criteria
- `odo catalog *` commands should not require component (localConfig) to list, describe or search services and component types
- if any of `odo catalog *`  commands need project, the current project from `KUBECONFIG` should be used.

/kind user-story

Feature request: https://github.com/openshift/odo/issues/2111

**Comment by kadel** [comment]
from #2111 
/label points/2
/label state/Ready
/area catalog
/kind user-story

**Comment by adisky** [comment]
I am able to run `odo catalog *` commands without odo component dir
```
[adisky@localhost ~]$ odo catalog describe service mysql-persistent
  Name                           | mysql-persistent                                                                                             
  Bindable                       | true  
```   
I had run other commands as well, `odo catalog list services`, `odo catalog search component golang` , am I missing something here?  I only found there is no command for describing catalog components `odo catalog describe component`, is this intentional ?

**Comment by girishramnani** [comment]
@kanchwala-yusuf please verify if this cannot be reproduced

**Comment by kadel** [comment]
`odo catalog list services` works for me, but  `odo catalog describe service` fails for me the same way as described in #2111

**Comment by adisky** [comment]
> `odo catalog list services` works for me, but `odo catalog describe service` fails for me the same way as described in #2111

yes, sorry!! I am also able to reproduce it, I mistakenly created a component in my home dir, so it was running.
