### ISSUE TITLE
Allow linking to any arbitrary service in the cluster.

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2607]
## User Story
As a user, I want to be able to link my component to a database or any other service that was not necessarily created by odo (I might manually deploy it from OpenShift template or using Helm.)

## Acceptance Criteria 
- [ ] It should be possible to link components using the `odo link` command to any `Service` resource.

/kind user-story
/area linking

**Comment by mik-dass** [comment]
As per discussion with @kadel , here services doesn't mean anything related to service catalog. It means kubernetes services https://kubernetes.io/docs/concepts/services-networking/service/. But our service command list services from the service catalog, do we need to create a new command or should we display such services in the same table?
