### ISSUE TITLE
[question] multi-arch support of odo

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo#2612]
[kind/Feature]

## Which functionality do you think we should add?
multi arch build support e.g build IBM s390x or ppc arch exec files
looks like there is release files https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.1.0/
but is the build process included in this repo or somewhere downstream? thanks

**Comment by kadel** [comment]
It is built on downstream infra, but most of the scripts are here in the repo.
Binaries as simply build by executing  `make cross`. This Make targets just executes the https://github.com/openshift/odo/blob/master/scripts/cross-compile.sh script.

**Comment by jichenjc** [comment]
thanks a lot for the info, will dig more about the code provided ~

**Comment by jichenjc** [comment]
ok, I find the odo-init-image is not multi arch supported.. maybe something to work on .
