### ISSUE TITLE
Allowing to change size of PVC that is used to store source code

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2616]
## User Story
As a user, I want to be able to specify the size of PVC that odo uses to store source code So that I can run the application that are bigger than 1Gb

## Acceptance Criteria 
- [ ] It should be possible to specify size of PVC that odo uses to store application source code using `odo config` command. This information will be stored in the component configuration (`.odo/config.yaml`)

## Links 
- Feature Request: https://github.com/openshift/odo/issues/2455

/kind user-story
/area component

**Comment by girishramnani** [comment]
assuming `config.yaml` here means the `env.yaml` in the devfile workflow.

As I remember `env.yaml` will not be checked into a repository by the user, which means a change in size of PVC will not be persisted between users and would be considered environment specific attribute.

**Comment by kadel** [comment]
> assuming `config.yaml` here means the `env.yaml` in the devfile workflow.
> 
> As I remember `env.yaml` will not be checked into a repository by the user, which means a change in size of PVC will not be persisted between users and would be considered environment specific attribute.
> Are we ok with that?

+1

**Comment by girishramnani** [comment]
I can already see envInfo struct here https://github.com/openshift/odo/blob/ad6c2cd700ff35ca03b0fe8665ce14e07034b0f9/pkg/envinfo/envinfo.go
so the idea here would be add a `componentPVCSize` or something here.

**Comment by girishramnani** [comment]
we already have an issue which allows `odo config` to change/configure values in the `env.yaml`
