### ISSUE TITLE
Enable existing app for GitOps workflow

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#2617]
## Description
As a developer, I want to have a simple command to "GitOps-enable" my existing application so I 
can easily have CI enabled.

This command could look something like: `odo gitops-enable --stak=springboot .`
which could read some information from the associated stak or auto-detect.

## Acceptance Criteria
* User is able to execute command and have supporting files generated for an existing application 
* User is able to specify that files are to be added to existing app directory structure or staged in a new repo
* User should be able to easily apply these files to validate the desired behavior of their app with gitops flow.

## Note
* There is a related epic to "pipeline enable" https://github.com/openshift/odo/issues/1238

**Comment by sbose78** [comment]
I'll update this to have the details of  'gitops day 2 Add Application' .

**Comment by girishramnani** [comment]
@sbose78  If you could share maybe just a break down whats done and whats left so I can plan for this issue/milestone.

**Comment by fgiloux** [comment]
+1. This would be very useful.

**Comment by girishramnani** [comment]
seems like the kam project took over the enablement of GitOps Pipeline
link - https://github.com/redhat-developer/kam

**Comment by girishramnani** [comment]
so should we close this epic @sspeiche @serenamarie125 ?
