### ISSUE TITLE
JSON output for operators available in the cluster

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2619]
## User Story
As a consumer of odo (for example: Adapters), I want to get `json` output for list of OperatorHub services that would help us present the information to end-users (for example: those using IDE plugins)

## Acceptance Criteria 
- [ ] `odo catalog list services -o json` should list operators from OperatorHub along with the services that it currently lists from Service Catalog 

## Links 
- Feature Request: #2461 
- Related issue: 

/kind user-story

**Comment by girishramnani** [comment]
we have all the methods to output operators as part of work done in this PR https://github.com/openshift/odo/pull/2593/files#diff-5e27f5585eee6d00b3adcddf59b96261R67-R75

so in terms of implementation I have to -
- [ ] build the json output of the csvs
- [ ] handle `EXPERIMENTAL_MODE` in json output

So the struct of `ClusterServiceVersionList` looks like this
```
type ClusterServiceVersionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []ClusterServiceVersion `json:"items"`
}
```

Where each Item has a `Spec`
```
type ClusterServiceVersionSpec struct {
	InstallStrategy           NamedInstallStrategy      `json:"install"`
	Version                   version.OperatorVersion   `json:"version,omitempty"`
	Maturity                  string                    `json:"maturity,omitempty"`
	CustomResourceDefinitions CustomResourceDefinitions `json:"customresourcedefinitions,omitempty"`
	APIServiceDefinitions     APIServiceDefinitions     `json:"apiservicedefinitions,omitempty"`
	NativeAPIs                []metav1.GroupVersionKind `json:"nativeAPIs,omitempty"`
	MinKubeVersion            string                    `json:"minKubeVersion,omitempty"`
	DisplayName               string                    `json:"displayName"`
	Description               string                    `json:"description,omitempty"`
	Keywords                  []string                  `json:"keywords,omitempty"`
	Maintainers               []Maintainer              `json:"maintainers,omitempty"`
	Provider                  AppLink                   `json:"provider,omitempty"`
	Links                     []AppLink                 `json:"links,omitempty"`
	Icon                      []Icon                    `json:"icon,omitempty"`

	// InstallModes specify supported installation types
	// +optional
	InstallModes []InstallMode `json:"installModes,omitempty"`

	// The name of a CSV this one replaces. Should match the `metadata.Name` field of the old CSV.
	// +optional
	Replaces string `json:"replaces,omitempty"`

	// Map of string keys and values that can be used to organize and categorize
	// (scope and select) objects.
	// +optional
	Labels map[string]string `json:"labels,omitempty" protobuf:"bytes,11,rep,name=labels"`

	// Annotations is an unstructured key value map stored with a resource that may be
	// set by external tools to store and retrieve arbitrary metadata.
	// +optional
	Annotations map[string]string `json:"annotations,omitempty" protobuf:"bytes,12,rep,name=annotations"`

	// Label selector for related resources.
	// +optional
	Selector *metav1.LabelSelector `json:"selector,omitempty" protobuf:"bytes,2,opt,name=selector"`
}
```

But as part of the standard output we only display the `Name` and a list of `CRDs` under it.

So I am proposing to have two top level attributes in the json output -

- services
- operators

### Services
Holds the original output of the `odo catalog list services -o json`

### Operators
Holds the list of CSVS with two attributes ( `name, `CRDs` ) consistent with the current `odo catalog list services`

**Comment by girishramnani** [comment]
@dgolovin can you please confirm the json output you require for operators? currently its going to be a list of `name` of the operator and `CRDS` ( this being a list of CRD )

**Comment by dgolovin** [comment]
@girishramnani I would love to confirm it, if you have something to try it out. I assume that creating services from operators is similar to creating services form svcat, is it not?

**Comment by girishramnani** [comment]
So I went with a different approach then initially decided, now the `operators` actually hold all the information provided by the server. This was done because the services also hold everything. So this keeps everything uniform.
