### ISSUE TITLE
Deleting a project says there is a default but it can't be used

### ISSUE THREAD

**Issue by jdob** [openshift/odo#2620]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 31

**Output of `odo version`:**
odo v1.1.0 (86c7e2c9)

Server: https://api.cluster-jdob-dd8d.jdob-dd8d.example.opentlc.com:6443
Kubernetes: v1.16.2

## How did you run odo exactly?
```
$ odo delete --project
Error: flag needs an argument: --project
Usage:
  odo delete <component_name> [flags]

Examples:
  # Delete component named 'frontend'.
  odo delete frontend
  odo delete frontend --all

Flags:
  -a, --all              Delete component and local config
      --app string       Application, defaults to active application
      --context string   Use given context directory as a source for component settings
  -f, --force            Delete component without prompting
  -h, --help             Help for delete
      --project string   Project, defaults to active project

Additional Flags:
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

 ✗  flag needs an argument: --project
```

## Actual behavior
Using `--project` requires a project name to be specified.

## Expected behavior
The help docs say that it "defaults to active project", which sounds like the project name can be omitted. There is no way to do that, so there isn't a way to delete the active project without specifying its name.

This could be as simple as fixing the help text to remove the comment about defaulting to the active project.

## Any logs, error output, etc?
Nope

**Comment by girishramnani** [comment]
if you provide the `--project` flag then you need to provide the value for that flag too. If you don't provide the `--project` flag and just do `odo project delete` then it will **default to the active project**

**Comment by girishramnani** [comment]
please confirm if `odo project delete` deletes the active project or not. If so then please close the issue as well.

**Comment by jdob** [comment]
It doesn't:

```
odo project delete                                                                1 ↵
Error: accepts 1 arg(s), received 0
Usage:
  odo project delete [flags]

Examples:
  # Delete a project
  odo project delete myproject

Flags:
  -f, --force   Delete project without prompting
  -h, --help    Help for delete

Additional Flags:
  -o, --o string             Specify output format, supported format: json (default "json")
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

 ✗  accepts 1 arg(s), received 0
```

**Comment by jdob** [comment]
Though as I write that, I'm seeing where my confusion was. I thought that `odo delete --project` would delete the current project, which is why I thought it didn't make sense that the project name needed to be specified. Now that I see `odo project delete`, I realize I was misunderstanding the purpose of `odo delete`.

I'm fine with closing this out. I'll leave it as your decision; feel free to keep this open to track a problem with `odo project delete` not deleting the active project.

**Comment by girishramnani** [comment]
Sorry I mistook `odo delete` For `odo project delete`.

**Comment by girishramnani** [comment]
> I thought that `odo delete --project`

It will delete the component

**Comment by jdob** [comment]
"Sorry I mistook odo delete For odo project delete."

Basically, so did I :) I'm going to close this out and chalk it up to me still getting acquainted with odo's syntax.

Thanks :)
