### ISSUE TITLE
Implement `odo storage describe` and `odo url describe` command

### ISSUE THREAD

**Issue by adisky** [openshift/odo#2638]
## User Story
As a user I want to get the details of a particular storage/url for a component.

## Acceptance Criteria 
- [ ] It should implement command `odo storage describe <storage-name> `
- [ ] It should `odo url describe <url-name>`

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by adisky** [comment]
as per the discussions with @tomas, `odo component describe -o json` does not contain complete storage information it only contains storage names, to get the complete information user needs to run `odo storage describe <storage-name> -o json `, this commands is missing in odo currently.

**Comment by mohitsuman** [comment]
@adisky Any update on this issue? It would be good if we have this for next odo release from IDE perspective.

**Comment by adisky** [comment]
@mohitsuman We would keep that in mind, and add it in next sprint.

**Comment by mohitsuman** [comment]
@girishramnani @adisky Are you folks taking this issue for the current sprint ?

**Comment by girishramnani** [comment]
@mohitsuman no we haven’t, we are still making devfile v2 core workflow ready and working. Only then this feature could be implemented.

**Comment by girishramnani** [comment]
we need to decide if we need to remove `odo url describe` or implement both

**Comment by girishramnani** [comment]
as per discussion with @mohitsuman - the `list` commands for url and storage are enough. we need to remove the `odo url describe` to remove any confusion

**Comment by jc-berger** [comment]
@boczkowska, I searched for the command, `odo url describe` in both the repo on GitHub and through Atom's `Find All` feature. Currently, there are no references and inclusions of the command, `odo url describe`. 

So I believe this issue can be closed.

**Comment by jc-berger** [comment]
Confirmed that `odo url describe` is not used anywhere in the openshift/openshift-docs` repo.
