### ISSUE TITLE
Flaky tests for --now flag

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2642]
```
c] 'Running odo with args [odo config unset --now --env hello --context /tmp/363231666]
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [66ms]
[odo]  ✓  Environment variables were successfully updated
[odo] 
[odo] Configuration changes
[odo]  •  Retrieving component data  ...
[odo]  ✓  Retrieving component data [88ms]
[odo]  •  Applying configuration  ...
[odo]  ✗  Applying configuration [86ms]
[odo]  ✗  Failed To Update Config To Component Deployed.
[odo] Error: unable to update DeploymentConfig for nodejs component: unable to update the current DeploymentConfig nodejs-app: unable to update DeploymentConfig nodejs-app: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "nodejs-app": the object has been modified; please apply your changes to the latest version and try again
Deleting dir: /tmp/363231666
Deleting project: usaszqseld
Running odo with args [odo project delete usaszqseld -f]
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named nodejs
[odo] No services / could not get services
[odo]  •  Deleting project usaszqseld  ...
[odo]  ✓  Deleting project usaszqseld [6s]
[odo]  ✓  Deleted project : usaszqseld
• Failure [9.242 seconds]
odo preference and config command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_pref_config_test.go:20
  when using --now with config command
  /go/src/github.com/openshift/odo/tests/integration/cmd_pref_config_test.go:310
    should successfully set and unset variables [It]
    /go/src/github.com/openshift/odo/tests/integration/cmd_pref_config_test.go:322
    No future change is possible.  Bailing out early after 0.427s.
```

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2637/pull-ci-openshift-odo-master-v4.3-integration-e2e-benchmark/728#1:build-log.txt%3A395

/priority high
/kind flake
/assign @mohammedzee1000 
/area  testing

**Comment by amitkrout** [comment]
```
[odo]  ✗  Applying configuration [86ms]
[odo]  ✗  Failed To Update Config To Component Deployed.
[odo] Error: unable to update DeploymentConfig for nodejs component: unable to update the current DeploymentConfig nodejs-app: unable to update DeploymentConfig nodejs-app: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "nodejs-app": the object has been modified; please apply your changes to the latest version and try again
```

This is where the issue is hit. I think @mik-dass  is looking into very similar issue.

**Comment by mik-dass** [comment]
> This is where the issue is hit. I think @mik-dass is looking into very similar issue.

I was looking into a similar but different issue earlier: https://github.com/openshift/odo/issues/1981. This issue is arlready closed.

**Comment by kadel** [comment]
another occurence https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2656/pull-ci-openshift-odo-master-v4.1-integration-e2e-benchmark/777

**Comment by amitkrout** [comment]
same failure can be seen against 4.4 cluster aswell - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6892/rehearse-6892-pull-ci-openshift-odo-master-v4.4-integration-e2e-benchmark/3#1:build-log.txt%3A1186

**Comment by johnmcollier** [comment]
Seen again on 4.1: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2656/pull-ci-openshift-odo-master-v4.1-integration-e2e-benchmark/816

**Comment by kadel** [comment]
this is getting more serious, bumping priority again
/remove-priority high
/priority critical

**Comment by mohammedzee1000** [comment]
This seems to b very common with nodejs apps, I could move to test all now flag with python apps but that will only mitigate the problem, not fix it

**Comment by mohammedzee1000** [comment]
@kadel ^

**Comment by girishramnani** [comment]
any updates on this @mohammedzee1000 ?

**Comment by amitkrout** [comment]
Another occurrence - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2739/pull-ci-openshift-odo-master-v4.3-integration-e2e-benchmark/1289#1:build-log.txt%3A375

@mohammedzee1000 Can you please take this as high priority as CI pain is increasing day by day for such flakes.

**Comment by dharmit** [comment]
Faced this couple of times on #2739 :cry:

**Comment by dharmit** [comment]
Hit this again today on same PR 2739: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2739/pull-ci-openshift-odo-master-v4.2-integration-e2e-benchmark/1294. But on 4.2 instead of 4.3 earlier.

**Comment by dharmit** [comment]
@mohammedzee1000 https://github.com/openshift/odo/pull/2841#issuecomment-611351264
