### ISSUE TITLE
Projects field in devfiles isn't optional for odo

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2655]
/kind bug

## What versions of software are you using?
odo built from master branch

## How did you run odo exactly?
1. Ran `odo preference set experimental true`
2. Downloaded this [sample devfile](https://raw.githubusercontent.com/johnmcollier/devfiles/master/odo/liberty/devfile.yaml)
3. Ran `odo push` and was presented with the following error:
```
johns-mbp-3:liberty-ex johncollier$ odo push
 ✗  no projects present in devfile
```

Since the devfile spec allows the `projects` field to be optional (and since odo needs to support projects locally on disk), odo should support devfiles that don't have any projects under `projects` in a devfile.

## Actual behavior
Odo push fails:
```
johns-mbp-3:liberty-ex johncollier$ odo push
 ✗  no projects present in devfile
```

## Expected behavior
Odo push succeeds without a project:
```
johns-mbp-3:nodejs-ex johncollier$ odo push 
 •  Push devfile component nodejs-ex  
...
```

## Any logs, error output, etc?
johns-mbp-3:nodejs-ex johncollier$ odo push
 ✗  no projects present in devfile

If I add a sample project to the devfile, everything runs fine.

**Comment by kadel** [comment]
This should get fixed in https://github.com/openshift/odo/pull/2629

Right @kanchwala-yusuf ?

**Comment by kanchwala-yusuf** [comment]
> This should get fixed in #2629
> 
> Right @kanchwala-yusuf ?

That is correct!

**Comment by kanchwala-yusuf** [comment]
@johnmcollier , You can check out the PR for this https://github.com/openshift/odo/pull/2629. Also, you can try out the code in this PR and see if this really solves your problem.

Lastly, it would be great if you can review it :)

**Comment by johnmcollier** [comment]
@kanchwala-yusuf Thanks! I'll go take a look at that PR and try it out
