### ISSUE TITLE
Devfile push fails on non-OpenShift clusters with oAuth enabled

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2658]
/kind bug

## What versions of software are you using?

**Operating System:**
All OS's
**Output of `odo version`:**
master branch
## How did you run odo exactly?
I've got access to clusters running on IKS (IBM Kubernetes Service) and GKE (Google Kubernetes Engine) and since odo's devfile support doesn't require OpenShift, I thought I'd try running odo push (with a devfile and experimental mode enabled) on them, however I hit the following issues:

**IKS**
```
johns-mbp-3:nodejs-ex johncollier$ odo push
 ✗  No Auth Provider found for name "oidc"
```

**GKE**
```
johns-mbp-3:nodejs-ex johncollier$ odo push
 ✗  No Auth Provider found for name "gcp"
```

Now, the solution for this is actually pretty straightforward, we just need to pull in the `auth` plugin package from client-go, into the package that's initializing the kubernetes client. In this case, we would just add the following to `kclient.go`:
```
import _ "k8s.io/client-go/plugin/pkg/client/auth" // Required for Kube clusters which use auth plugins
```

However, this would require having glide pull in the dependencies for the `auth` plugin into the vendor folder. I was not able to get glide to pull the dependencies without breaking a bunch of other things in odo. So this may be something to look at fixing once go.mod support is added in https://github.com/openshift/odo/issues/2585 .

## Actual behavior
`odo push` fails on non-OpenShift clusters with oauth enabled

## Expected behavior
`odo push` works on non-OpenShift clusters with oauth enabled.

**Comment by kadel** [comment]
> However, this would require having glide pull in the dependencies for the `auth` plugin into the vendor folder. I was not able to get glide to pull the dependencies without breaking a bunch of other things in odo. So this may be something to look at fixing once go.mod support is added in #2585 .

just run add `import _ "k8s.io/client-go/plugin/pkg/client/auth"` to the code and run `glide up -v`.
`k8s.io/client-go/` is already in `glide.yaml` so you just need to run `glide up -v` nothing else ;-)

fixed in https://github.com/openshift/odo/pull/2665
