### ISSUE TITLE
odo push doesn't wait for running pod

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2661]
/kind bug
/area devfile
/priority medium

`odo push` should wait for the Pod to be in running state before exits.
Currently, it does that only for first invocation (when resources are created). But any additional `odo push` doesn't wait.

```
export ODO_EXPERIMENTAL=true

▶ odo push ; kubectl get pods
 •  Push devfile component odo-examples  ...
 ✓  Waiting for component to start [9s]
 ✓  Push devfile component odo-examples [10s]
NAME                           READY   STATUS    RESTARTS   AGE
odo-examples-8cb546c7b-sbmxd   1/1     Running   0          11s

# modify devfile.yaml

▶ odo push ; kubectl get pods
 •  Push devfile component odo-examples  ...
 ✓  Waiting for component to start [174ms]
 ✓  Push devfile component odo-examples [1s]
NAME                           READY   STATUS        RESTARTS   AGE
odo-examples-8cb546c7b-sbmxd   1/1     Terminating   0          71s
```

Also if edits to devfile.yaml caused Pod to get into CrashLoop state users doesn't know about it

**Comment by rajivnathan** [comment]
Spoke to John about this, he mentioned his sync PR may resolve this so I'll try to reproduce this once https://github.com/openshift/odo/pull/2681 is in to see if it's still an issue.

**Comment by rajivnathan** [comment]
@kadel has found a nice solution to this problem. He has a PR incoming so I'll unassign myself.
