### ISSUE TITLE
Consider moving the Devfile Parser to the top level and update the Parse function also validate

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2669]
## Which functionality do you think we should add?

We can consider moving pkg/devfile/parser and pkg/devfile/versions to a top-level folder since it seems like it could be moved to a separate repo altogether and so should be more decoupled from the odo code. Maybe pkg/parser or pkg/devfile-parser so it will make it easier to separate it out later?

https://github.com/openshift/odo/pull/2629 removed some validation code. Maybe we can add it back to a new package like pkg/devfile/validation that lives within the odo code. I'm thinking for odo we'd want the pkg/devfile/Parse function to still validate but just call the validation from an odo package.

This is based on a previous comment: https://github.com/openshift/odo/pull/2629#discussion_r385865159

/kind user-story
/area devfile
/remove kind user-story

**Comment by kadel** [comment]
I think that whole `pkg/devfile`  should be mostly generic

**Comment by rajivnathan** [comment]
@kadel Do you mean odo code should not be in `pkg/devfile`? The devfile adapter code which is only for odo is currently under `pkg/devfile/adapters`, are you suggesting we move that somewhere else?

**Comment by kadel** [comment]
> @kadel Do you mean odo code should not be in `pkg/devfile`? The devfile adapter code which is only for odo is currently under `pkg/devfile/adapters`, are you suggesting we move that somewhere else?

I would probably put `adapters` to `pkg/adapters`.

**Comment by kanchwala-yusuf** [comment]
@kadel, @rajivnathan : 
Currently, the devfile parser related stuff is spread across multiple packages (_viz._ `parser`, `versions`). I was wondering if it would make sense to move all the devfile parser related packages into a single package `pkg/devfile/parser`.

And I would suggest to keep all the devfile related packages within `pkg/devfile` to keep the devfile related functionality at one place under one package. So, we can have adapters under `pkg/devfile/adapters` itself. To address this issue, we can have another package for validation `pkg/devfile/validations`.

Do you guys concur with the above opinion?
