### ISSUE TITLE
Document what frameworks work with Java / Node.JS  / etc.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2683]
/kind documentation

## What mistake did you find / what is missing in the documentation?

In terms of what frameworks are *actually* supported, we have no documentation that actually showcases what works and what does not.

For example, with Node.js, only NPM works, not Yarn.

Same with Java, PHP, Ruby, etc. We need to indicate what frameworks actually work and what does not.

## What is the relevance of it?

More documentation on frameworks.

**Comment by boczkowska** [comment]
Thanks, @cdrage!

We can call it, for example, `Compatible frameworks and tools` and have a breakdown according to the language. 
Do we have a list of popular tools/frameworks/etc that are proved to work, to start with?

**Comment by cdrage** [comment]
@boczkowska I've opened up a PR here! https://github.com/openshift/odo/pull/2687
