### ISSUE TITLE
Documentation on how to modify `..s2i/bin/assemble`

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2686]
/kind documentation

## What mistake did you find / what is missing in the documentation?

When I was deploying a Ruby application, I came across some errors with the current service catalog. I happened upon an issue where you can actually modify the assembly script..

We should have simple documentation on how to modify the assembly script within S2I.

For example, I had to modify: https://github.com/sclorg/s2i-ruby-container/blob/master/2.6/s2i/bin/assemble

In order to add: `npm install -g yarn`

So I could compile yarn.

## What is the relevance of it?

Those who need to customize their s2i / application assembly scripts in case there is no

**Comment by girishramnani** [comment]
This is very image specific work, do you think we should be the one to document such things?
