### ISSUE TITLE
odo config support for settings in devfile.yaml

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2688]
## User Story
As a developer, I want to configure my configuration settings of devfile style components in the devfile.yaml so that I can change the settings after the initial creation.

## Background
The storing of the configuration settings for the devfile style components is currently stored in the `devfile.yaml` that follows the devfile specification. However, the user currently cannot edit the settings in using the command line after the devfile in the project has been created as part of other commands. 

### for "LocalConfig" components (s2i)
- [x] `odo config` should work  as currently does

#### odo config
`odo config` is doing all operations on `devfile.yaml`, should not touch any other file.
Devfile can have multiple containers defined.  `odo config` should by default apply the configuration to all containers in devfile.

- [x] `odo config set Name` - set `metadata.name` field i in devfile.yaml
- [x] `odo config set --env FOO=bar` - add `FOO` env variable with `bar` value to all containers defined in devfile
- [x] `odo config set Ports 8080/TCP` - add new endpoint to each container in devfile
- [x] `odo config set Memory` - set `memoryLimit` for all containers in devfile.yaml
- [x] `odo config unset/view` should  work with new and updated fields 
- [x] config options in `odo confg` should have new updated description to match its meaning in devfile spec
- [x] `odo config set DebugPort` - we can **remove this option** it in favor of `odo config set --env DEBUG_PORT=12345`
- [x] `odo config set MaxCPU` - **remove this command** - devfile v2 currently doesn't have cpu limits
- [x] `odo config set MaxMemory` - **remove this command** - devfile v2 currently have only memory limit
- [x] `odo config set CPU` - **remove this command** - devfile v2 currently doesn't have cpu limits
- [x] `odo config set MinCPU` - **remove this command** - devfile v2 currently doesn't have cpu limits
- [x] `odo config set MinMemory` - **remove this command** - devfile v2 currently have only memory limit
- [x] `odo config set Ref ` - **remove this command**  - not valid for devfile
- [x] `odo config set SourceType ` - **remove this command**   - not valid for devfile
- [x] `odo config set Type ` - **remove this command**   - not valid for devfile
- [x] `odo config set SourceLocation ` - **remove this command**   - not valid for devfile

The [devfile reference](https://devfile.github.io/devfile/_attachments/api-reference.html)

## Links 
- Related issue: #2592, #3401

/kind user-story
/area devfile

**Comment by cdrage** [comment]
Sorry if I do not understand this, but at the moment, we already store environment variable information in the `.odo/config.yaml` file in the projects folder.

Are you proposing that we should have a separate file outside of `.odo/config.yaml` with the environment information?

Ex:

```sh

~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                                         42d ⚑ ◒  
▶ odo config set --env RAILS_ENV=development         
 ✓  Environment variables were successfully updated

Run `odo push --config` command to apply changes to the cluster

~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                                         42d ⚑ ◒  
▶ cat .odo/config.yaml 
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: testing
  Name: nodejs-nodejs-ex-oguc
  Envs:
  - Name: RAILS_ENV
    Value: development
```

**Comment by kadel** [comment]
> Sorry if I do not understand this, but at the moment, we already store environment variable information in the `.odo/config.yaml` file in the projects folder.
> 

Yes, and this stays as it is.

> Are you proposing that we should have a separate file outside of `.odo/config.yaml` with the environment information?

Nope ;-)

What Elson is proposing is just for when the devfile is used (ODO_EXPERIMETNAL=true).
For `LocalConfig` (s2i builder image-based components ) odo will still use `.odo/config.yaml`

**Comment by kadel** [comment]
> Sorry if I do not understand this, but at the moment, we already store environment variable information in the `.odo/config.yaml` file in the projects folder.
> 
> Are you proposing that we should have a separate file outside of `.odo/config.yaml` with the environment information?

Yes, but only for devfile components. This is what Elson is proposing.

I've added 4 more acceptance criteria that should make this clearer. 

But I'm not convinced that this is a good approach.

@elsony Do you think that it makes sense to store env variables in the environment-specific config file? Shouldn't be all env variables captured in devfile.yaml?

The way I see it `odo config set --env key=value` should modify the env variables in devfile.yaml. We will probably have to add something like `--devfile-component` flag fully define where the env variables should be.

**Comment by elsony** [comment]
I don't think we should store any true environment specific config in the devfile.yaml. It will make the devfile not portable and users can't check that into team repository.  Having said that, there are some env setting that fits into the devfile, e.g. a devfile writer can have some containers rely on some env variable to change the behaviour of the build. Strictly speaking, that's part of the stack design and they are not really environment specific so those can be checked into the team repo and put as part of the devfile. However, for the real env specific that we currently put under the env.yaml, e.g. ingress domain, target namespace for odo push, etc., those are not portable to other system and we don't expect people to check it into the team repo. Therefore, the main difference between devfile.yaml and env.yaml are whether those config are environment neutral that can be reused in other systems.

Regarding to the concerns on  `odo config set --env key=value` making changes on env.yaml vs devfile.yaml, I think the bigger question is whether we want odo to be the tool to edit the devfile.  devfile is more than just for odo usage (also used by Che and Appsody, etc.) and it much more complex than the existing config.yaml.  I think if we want a fully featured tools to help users out on editing the devfile, it should be a separate tool for doing that, e.g. a stack creator tool or something like that.  odo will focus on things that we create/inject.  Having said that, if we do find a few settings that a typically odo user will likely to edit, it will be fine if we allow user to do some selected `odo config` setting to edit things from the devfile for convenience.

**Comment by kadel** [comment]
> I don't think we should store any true environment specific config in the devfile.yaml. It will make the devfile not portable and users can't check that into team repository. Having said that, there are some env setting that fits into the devfile, e.g. a devfile writer can have some containers rely on some env variable to change the behaviour of the build. Strictly speaking, that's part of the stack design and they are not really environment specific so those can be checked into the team repo and put as part of the devfile. However, for the real env specific that we currently put under the env.yaml, e.g. ingress domain, target namespace for odo push, etc., those are not portable to other system and we don't expect people to check it into the team repo. Therefore, the main difference between devfile.yaml and env.yaml are whether those config are environment neutral that can be reused in other systems.


Agreed, ingress domain, namespace are good examples of environment-specific configs. But environment variables are not environment-specific. Env variables are highly specific to a given application, they should be part of the application configuration, and as such, it should be captured in devfile.yaml, most of the application depend on the right env variables being set.


> Regarding to the concerns on `odo config set --env key=value` making changes on env.yaml vs devfile.yaml, I think the bigger question is whether we want odo to be the tool to edit the devfile. devfile is more than just for odo usage (also used by Che and Appsody, etc.) and it much more complex than the existing config.yaml. I think if we want a fully featured tools to help users out on editing the devfile, it should be a separate tool for doing that, e.g. a stack creator tool or something like that. odo will focus on things that we create/inject. Having said that, if we do find a few settings that a typically odo user will likely to edit, it will be fine if we allow user to do some selected `odo config` setting to edit things from the devfile for convenience.


Agreed, devfile is much more complex and powerful than `config.yaml`, it doesn't make sense to provide odo commands to modify every devfile aspect, but I think that there should be commands to do most common operations like modifying env variables, cpu/memory limits ....

Originally odo was designed in a way that users shouldn't need to edit any yaml files. And allow users to slowly build their application in an interactive way. This made it appealing to a lot of people.  `config.yaml` was meant to be just implementation detail, which is more or less hidden to normal uses. Devfiles are a different story, they should be exposed to users, but at the same time, we shouldn't force users to edit devfile.yaml for small incremental tasks, if they don't fee like it.

**Comment by cdrage** [comment]
Hi @elsony I've assigned this to you. I think you've already implemented some of the user stories / criteria for this? Could you go through and see what could be checkmarked off?

**Comment by cdrage** [comment]
Alright, I've started work on this, here's my TODO list (for my own reference too):

**When experimental mode is enabled, the following must happen against `env.yaml`:
- [ ] `odo config set --env key=value`
- [ ] `odo config set --env key=value` but override if key already exists
- [ ] `odo config unset --env key`
- [ ] `odo config view`

**Other scenarios:**
- [ ] If `.odo/env.yaml` does not exist, tbut .odo/config.yaml is present, the previous above commands should work against LocalConfig
- [ ] If there is no `devfile.yaml` or `.odo/config.yaml` show error about non-existing component
- [ ] 

- [ ] 'odo config set --env key=value' will add the environment setting on `env.yaml` file if the key does not already exist
- [ ] 'odo config set --env key=value' will update the value of the environment setting on `env.yaml` file if the key already exists
- [ ] 'odo config unset --env key' to remove the environment settings on `env.yaml` file with the given key
- [ ] the above scenarios will only be activated on the devfile style of application when `Experimental` flag is set to `true`
- [ ] if `Experimental=true` and the `devfile.yaml` is present in  the current directory `odo config` `set/get/view`  operates on `env.yaml`.
- [ ] if `Experimental=true` and there is no `devfile.yaml` but `.odo/config.yaml` is present, `odo config` `set/get/view` operates on`LocalConfig `.odo/config.yaml`.
- [ ] if `Experimental=true` and there is   is no `devfile.yaml`  and no `.odo/config.yaml`, show error about non-existing component
- [ ] if `Experimental=false` everything stays is it is right now (`odo config` operatos on `LocalConfig` or fails if there is no component

**Comment by girishramnani** [comment]
so is any of the AC actually completed @cdrage?

**Comment by kadel** [comment]
I think that `odo config` will need much bigger overhaul :-( 

Currently, odo supports the following parameters 

- Application - Application is the name of application the component needs to be part of
- CPU - The minimum and maximum CPU a component can consume
- DebugPort - The port on which the debugger will listen on the component
- Ignore - Consider the .odoignore file for push and watch
- MaxCPU - The maximum CPU a component can consume
- MaxMemory - The maximum memory a component can consume
- Memory - The minimum and maximum memory a component can consume
- MinCPU - The minimum CPU a component can consume
- MinMemory - The minimum memory a component is provided
- Name - The name of the component
- Ports - Ports to be opened in the component
- Project - Project is the name of the project the component is part of
- Ref - Git ref to use for creating component from git source
- SourceLocation - The path indicates the location of binary file or git source
- SourceType - Type of component source - git/binary/local
- Storage - Storage of the component
- Type - The type of component
- URL - URL to access the component
- Env - environment variables


With the old-style components (s2i) we have only one place to store configuration (`config.yaml`)

But with devfile components, we actually have two places where the config values can be stored `env.yaml` and `devfile.yaml`.
As I tried described in https://github.com/openshift/odo/issues/2688#issuecomment-598811878 the configuration that is related to application configuration (for example resource limits or env variables as I see them) should be stored in `devfile.yaml`. `devfile.yaml` is supposed to describe how to set up the environment and how to run the source code and is meant to be shared.
For example, there might be env variable that needs to be set in order to application work properly, so this should be recorded in `devfile.yaml`, or if the application required at least of 1GB RAM, it should be specified in the `devfile.yaml`, otherwise, every user will have to set this in their `env.yaml`

I'm not so sure that just storing env variables set by `odo config set --env key=value` in `env.yaml` is a good solution.
And even if we go this route we need to clearly define how it will work, as devfile can define multiple containers, so does it mean that env variables from `env.yaml` will be set for all containers or just some?

**Comment by maysunfaisal** [comment]
The config support should also take into consideration about saving devfile non custom commands. Probably something like
`odo config set build-command mydevfilebuildcommand`
and then `odo push` can execute `mydevfilebuildcommand` instead of `devbuild`

**Comment by elsony** [comment]
One proposal that has been discussed before is to differentiate between config settings in devfile.yaml vs config settings in env.yaml.  We'll use:
- `odo config set` for setting configuration in the devfile.yaml - devfile.yaml is so big so we'll just pick and choose most common settings in devfile.yaml that odo user will likely to use. These are the settings that will persists as part of the application (we expect user to check the devfile.yaml in the team repo).
- `odo environment set` for setting configuration in the env.yaml - these are transient settings that we don't expect user to check that into team repo.
Having that separation will make it clear on which file we are modifying when specifying changes on a given config that exists on both devfile.yaml and env.yaml.

**Comment by kadel** [comment]
# WORK IN PROGRESS


## "LocalConfig" components (s2i)
- `odo config` should work  as currently does
- `odo environment` will error out with information that the command is not available for s2i builder images based components.


## devfile components
Devfile can have multiple containers defined.  `odo config` should by default apply the configuration to all containers in devfile.
- [ ] `odo config set DebugPort` - adds
- [ ] `odo config set MaxCPU` - The maximum CPU a component can consume
- [ ] `odo config set MaxMemory` - The maximum memory a component can consume
- [ ] `odo config set Memory` - The minimum and maximum memory a component can consume
- [ ] `odo config set CPU` - The minimum and maximum CPU a component can consume
- [ ] `odo config set MinCPU` - The minimum CPU a component can consume
- [ ] `odo config set MinMemory` - The minimum memory a component is provided
- [ ] `odo config set Name` - The name of the component
- [ ] `odo config set --env FOO=bar` - environment variables
- [ ] `odo config set Ports` - Ports to be opened in the component

**Comment by girishramnani** [comment]
should we consider jsonpath like configs? like `odo config set components[0].exec.commandLine "blah"`?

**Comment by girishramnani** [comment]
I would like to research on this issue

**Comment by girishramnani** [comment]
I have one more issue related to `odo project` which I would be able to complete before the sprint part 2 meeting - if that changes then I wil find someone else to work on this issue

**Comment by kadel** [comment]
> should we consider jsonpath field parsing for config values? like `odo config set components[0].exec.commandLine "blah"`?

I wouldn't complicate this for now. We can consider this later if there is a need for something like this

**Comment by elsony** [comment]
After discussing with @kadel , we have decided to split this issue into two since they can be worked independently:
-  This issue will cover the `odo config` for modifying settings in the devfile.yaml 
- An new issue #3401 has been opened to cover `odo environment` for modifying the environment settings in the env.yaml

I'm modifying this issue (title and description) to reflect that.

**Comment by elsony** [comment]
As part of the devfile 2.0 spec (https://github.com/devfile/kubernetes-api/issues/61), we are going to support `.devfile.yaml` in the project and handle it in the same way as the `devfile.yaml`. I think `odo config` should support both `devfile.yaml` and `.devfile.yaml`.

**Comment by gorkem** [comment]
@kadel What is the expectation for `odo debug port-forward` command when determining the remote port? If `odo config set DebugPort` is retired in favor of setting the environment variable `DEBUG_PORT`. Does port-forward look only to the values on `env.yaml` ?

**Comment by kadel** [comment]
> @kadel What is the expectation for `odo debug port-forward` command when determining the remote port? If `odo config set DebugPort` is retired in favor of setting the environment variable `DEBUG_PORT`. Does port-forward look only to the values on `env.yaml` ?


The remote port should be still determined by `DEBUG_PORT` environment variable.
Odo should check `DEBUG_PORT` env variable in the container and use its value as a remote port.

The idea is that the environment variable will make it easy to configure port in debug command. 
```yaml
schemaVersion: 2.0.0
metadata:
  name: nodejs
components:
  - container:
      name: nodejs
      image: nodejs
      mountSources: true
      env:
        -  name: DEBUG_PORT
           value: 1234
commands:
  - exec:
      id: debug
      component: runtime
      commandLine: nodemon --inspect 127.0.0.1:${DEBUG_PORT}
      group:
        kind: debug
        isDefault: true
```

**Comment by mik-dass** [comment]
> The remote port should be still determined by DEBUG_PORT environment variable.
. Odo should check DEBUG_PORT env variable in the container and use its value as a remote port.

This needs to be well documented somewhere for users making the transition from s2i components.

**Comment by gorkem** [comment]
OK, so `debug port-forward` is only meant to work with DEBUG_PORT. It appears that I was doing a hackish thing to forward different ports. See also https://github.com/openshift/odo/issues/3495

**Comment by kadel** [comment]
@girishramnani This issue is still labeled as "needs-information". Is there something that is still needed?

**Comment by girishramnani** [comment]
I would have a PR for review in a day. Quite close to getting it done. 1 small thing that I have already done but just wanted to confirm - can someone have a devfile which isn't called `devfile.yaml`?

**Comment by girishramnani** [comment]
Also `--now` flag for config might be a follow up PR
