### ISSUE TITLE
describe command failed to find component in list output

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo#2689]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**
master compiled version 
## How did you run odo exactly?
```
[root@xyimgr77 backend]# ../odo component list
APP     NAME                  PROJECT       TYPE        SOURCE        STATE
app     ubi-frontend-bdjz     openshift     ubi         file://./     Pushed
app     ubi-backend-qmuj      openshift     ubi:1.0     file://./     Not Pushed
[root@xyimgr77 backend]# ../odo component describe
Component Name: ubi-backend-qmuj
Type: ubi:1.0
Source: file://./
[root@xyimgr77 backend]# ../odo component describe ubi-frontend-bdjz
Component Name: ubi-frontend-bdjz
Type: ubi
Source: file://./
Environment Variables:
 · DEBUG_PORT=5858
[root@xyimgr77 backend]# ../odo component describe ubi-backend-qmuj
 ✗  Component ubi-backend-qmuj does not exist in application app
```

**Comment by jichenjc** [comment]
if you think this is a potential bug, I can try to fix it

**Comment by adisky** [comment]
@jichenjc AFAIK `odo component describe` is intended to be run from inside component folder, which could describe component from localConfig if `Not Pushed`. 
`odo component describe <component-name>` is intended to be run from anywhere which lists component from cluster, so in your case the component is not pushed to cluster, hence it is returning `Not Exist`

**Comment by jichenjc** [comment]
@adisky good to see you here :)

about the quesiton, then why I can see following??

```
[root@xyimgr77 backend]# ../odo component describe
Component Name: ubi-backend-qmuj
Type: ubi:1.0
Source: file://./
```

**Comment by adisky** [comment]
> Component Name: ubi-backend-qmuj

@jichenjc same here :)
yes, same as i mentioned above `odo component describe` is intended to run from component folder it is listing information from .odo/config.yaml.

**Comment by jichenjc** [comment]
I am running in the folder... (../odo is because I put odo execute file there...)

```
[root@xyimgr77 backend]# cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: ubi:1.0
  SourceLocation: ./
  SourceType: local
  Ports:
  - "80"
  Application: app
  Project: openshift
  Name: ubi-backend-qmuj
(reverse-i-search)`ls': ^C .odo
[root@xyimgr77 backend]# ../odo component list
APP     NAME                  PROJECT       TYPE        SOURCE        STATE
app     ubi-frontend-bdjz     openshift     ubi         file://./     Pushed
app     ubi-backend-qmuj      openshift     ubi:1.0     file://./     Not Pushed
[root@xyimgr77 backend]# ../odo component describe ubi-backend-qmuj
 ✗  Component ubi-backend-qmuj does not exist in application app
```

**Comment by girishramnani** [comment]
as you can observe that the `state` of the `ubi-backend-qmuj` component is `Not Pushed` which means it wouldn't be created on the cluster yet. And hence the ` ✗  Component ubi-backend-qmuj does not exist in application app`

- if you do `odo push` and then do `odo component describe ubi-backend-qmuj` then it should show the component info.

**Comment by jichenjc** [comment]
I am ok actually if it works like you mentioned @girishramnani , thanks a lot 
however, why it shows below is another question:

```
[root@xyimgr77 backend]# ../odo component describe
Component Name: ubi-backend-qmuj
Type: ubi:1.0
Source: file://./
```

**Comment by girishramnani** [comment]
got it, I was able to reproduce this locally.
```
$ odo component describe 
Component Name: nodejs-r2t-zage
Type: nodejs
Source: file://./
(base) [gramnani@girishpc r2t]
$ odo component describe nodejs-r2t-zage -v5
I0309 14:12:56.531173    7432 occlient.go:2604] Getting DeploymentConfig: nodejs-r2t-zage-app
 ✗  Component nodejs-r2t-zage does not exist in application app
```

**Comment by girishramnani** [comment]
Added this for the upcoming sprint

**Comment by girishramnani** [comment]
I would like to research on this issue for this sprint

**Comment by adisky** [comment]
It is failing here https://github.com/openshift/odo/blob/master/pkg/odo/genericclioptions/context.go#L363, if `component name` is specified and not present in cluster it throws error. Error is thrown here considering component name specified here does not exist in current project/application, but there could be a case component is `not pushed`,  we can list this from local config, provided  specified `component name` and  local config `component name` matches.
