### ISSUE TITLE
--app information not included in generated non-interactive command

### ISSUE THREAD

**Issue by jdob** [openshift/odo#2696]
/kind bug

## What versions of software are you using?
Fedora 31
odo v1.1.0 (86c7e2c9)
Server: https://api.crc.testing:6443
Kubernetes: v1.14.6+17b1cc6

## How did you run odo exactly?

$ odo service create --app concessions
? Which kind of service do you wish to create database
? Which database service class should we use mongodb-ephemeral
? Enter a value for string property DATABASE_SERVICE_NAME (Database Service Name): mongodb
? Enter a value for string property MEMORY_LIMIT (Memory Limit): 512Mi
? Enter a value for string property MONGODB_DATABASE (MongoDB Database Name): sampledb
? Enter a value for string property MONGODB_VERSION (Version of MongoDB Image): 3.6
? Provide values for non-required properties No
? How should we name your service  database
? Output the non-interactive version of the selected options Yes
? Wait for the service to be ready Yes
Deploying service database of type: mongodb-ephemeral
 ✓  Deploying service [27ms]
 ✓  Waiting for service to come up [1m]
 ✓  Service 'database' is ready for use
Optionally, link mongodb-ephemeral to your component by running: 'odo link <component-name>'
Equivalent command:
odo service create mongodb-ephemeral database --plan default -p DATABASE_SERVICE_NAME=mongodb -p MEMORY_LIMIT=512Mi -p MONGODB_DATABASE=sampledb -p MONGODB_VERSION=3.6

## Actual behavior
Outputted odo service command does not include the --app flag and won't recreate the service completely.

## Expected behavior
The --app flag should be included in the equivalent command:

odo service create mongodb-ephemeral database --plan default -p DATABASE_SERVICE_NAME=mongodb -p MEMORY_LIMIT=512Mi -p MONGODB_DATABASE=sampledb -p MONGODB_VERSION=3.6 --app concessions

## Any logs, error output, etc?
Nope

**Comment by girishramnani** [comment]
it seems the `--project` is also not shown in the equivalent command when provided
