### ISSUE TITLE
Debug using devfile v2

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2701]
## User Story
As a developer I want to debug my component so that I can resolve bugs and use it for other cases.

## Acceptance Criteria 
- [ ] It should have a command to start the component in debug mode
- [ ] It should port-forward the given port or auto select a default one
- [ ] It should have a command to turn off debug mode for the component

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by mik-dass** [comment]
I managed to get debug working with a devfile for a nodejs component.

Using https://github.com/openshift/odo/pull/2735, I changed the devrun command to what we are using in the `odo-init` image https://github.com/openshift/odo-init-image/blob/d64042928158c8d975b690ac9df28731c2ddd28b/language-scripts/nodejs/dev-run#L71. Then I triggered port forwarding using `oc` and used the normal vscode steps to achive it. 

So we would require a devdebug step in the devfile which would kill the current running application and start it in debug mode. Then the `odo port-forward` would be used and would replace the `oc port-forward` step used above.

A command like `odo debug start` can be used to trigger the devdebug step and a similar stop command would kill it and trigger normal devrun.

But I don't expect all devfiles to have a devdebug step. What should we do in such a scenario? @kadel @girishramnani

**Comment by girishramnani** [comment]
in my opinion, this would work similar to current components where certain images support debug and other dont, we can decide on a name of the step like you mentioned `devdebug` here and then check which of the devfiles from the registry have this step defined. Based on this we show the `Supported` and `Unsupported` devfiles.

**Comment by mik-dass** [comment]
> in my opinion, this would work similar to current components where certain images support debug and other dont, we can decide on a name of the step like you mentioned devdebug here and then check which of the devfiles from the registry have this step defined. Based on this we show the Supported and Unsupported devfiles.

OK. Maybe we can inform the user that he can add a devdebug step manually in the devfile. Also we can ask the user he wants to manually add a devdebug step. If he says yes, we can just add a devdebug basic template in devfile.

**Comment by mik-dass** [comment]
After some discussion with @kadel , we have decided to name the step `debug` or `debugrun` in the devfile. And instead of having a dedicated command, we will start the debug mode when the user executes `odo push --debug`.

 The user can also declare a env variable in the devfile to trigger debug mode.

@girishramnani @elsony WDYT?

**Comment by cdrage** [comment]
> After some discussion with @kadel , we have decided to name the step `debug` or `debugrun` in the devfile. And instead of having a dedicated command, we will start the debug mode when the user executes `odo push --debug`. This will execute the `debugrun` step in the devfile.
> 
> The user can also declare a env variable in the devfile to trigger debug mode.
> 
> @girishramnani @elsony WDYT?

After today's cabal, this LGTM and makes sense. If a user wants their application to initially run in debug mode, it makes sense to pass in `--debug` to `odo push`.

**Comment by elsony** [comment]
> After some discussion with @kadel , we have decided to name the step `debug` or `debugrun` in the devfile. And instead of having a dedicated command, we will start the debug mode when the user executes `odo push --debug`. This will execute the `debugrun` step in the devfile.
> 
> The user can also declare a env variable in the devfile to trigger debug mode.
> 
> @girishramnani @elsony WDYT?

Yes, sounds good to me.

**Comment by mik-dass** [comment]
@girishramnani @kadel How will we detect the remote port of the debugrun step?

**Comment by girishramnani** [comment]
- we need to allow the user to set the remote debug port if needed which means the debugrun command should support env interpolation i.e.  a sample devrun command `node —inspect $DEV_PORT main.js` the DEV_PORT can be env variable expose on the s2i script ( for now as we still plan to use it ). This can be a possible solution. 

We should default to something but the user shouldn’t need to provide it from the get go as they can rely on conventions.

**Comment by girishramnani** [comment]
- remote port should only be in the local env if it’s set specifically by the user.
