### ISSUE TITLE
Disable CI run only for doc changes pr

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2704]
## User Story
As a contributor i can send odo dev doc pr. I would expect CI should not run for doc as we are not building doc as part of CI run. 

## Acceptance Criteria 
Doc pr should merge without involving the test run

- [x] Travis CI - https://github.com/openshift/odo/pull/2757 (partially solving the purpose - It just documented the steps, it does not enforce it)

- [ ] Prow 

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by mohammedzee1000** [comment]
For Travis https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build maybe?

**Comment by amitkrout** [comment]
Skipping the test on OpenShift CI is still pending.

**Comment by amitkrout** [comment]
Steps for skipping only doc changes pr on OpenShift CI. Copy pasting the steps provided by @mohammedzee1000 in our slack 1-1 discussion that we agree upon. 
```
step 1 : check branch
step 2: get commit messages from master step 
step 3 : grep for skip ci step 
Step 4: if grep failed then run tests
```

**Comment by mohammedzee1000** [comment]
Alternative solution : https://github.com/openshift/release/blob/master/ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.14-presubmits.yaml#L17

**Comment by amitkrout** [comment]
> Alternative solution : https://github.com/openshift/release/blob/master/ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.14-presubmits.yaml#L17

Solution looks much better. 
I have observed travis CI does not work properly eve after the pr https://github.com/openshift/odo/pull/2757 went in. @mohammedzee1000 can you please revisit the fix done for travis CI.

**Comment by girishramnani** [comment]
@amitkrout please check the PRs where the docs change did trigger CI

**Comment by amitkrout** [comment]
> @amitkrout please check the PRs where the docs change did trigger CI

https://github.com/openshift/odo/pull/3218 and https://github.com/openshift/odo/pull/3233 these are the two pr we recently hit the deviation. 

ATM i am going to create a pr just for testing purpose to verify travis CI skip for doc changes only.

**Comment by amitkrout** [comment]
> > @amitkrout please check the PRs where the docs change did trigger CI
> 
> #3218 and #3233 these are the two pr we recently hit the deviation.
> 
> ATM i am going to create a pr just for testing purpose to verify travis CI skip for doc changes only.

Now i found the issue why it was not working i mean CI skip in these above two examples because the [skip ci] message was added through the pr template not through the git commit message. Actually this looks counter intuitive as the user comes to know at the time of pr creation from the pr template. We should enforce it if pr has only doc changes in travis CI run.

**Comment by mohammedzee1000** [comment]
I will be raising PR for using git commit shortly, to maintain uniform behavior

**Comment by anandrkskd** [comment]
We can use run_if_changed, info about   run_if_changed provided in [doc](https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs).  

For Prow we need use regex similar to provied [here](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml#L595).
