### ISSUE TITLE
Determine how odo should handle multiple projects in a devfile

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2705]
## User Story

As a user, I want to be able to use a devfile that has multiple projects defined because devfiles allow this. Need to determine how odo should handle multiple projects in a devfile.

This follows from the discussion here: https://github.com/openshift/odo/pull/2681#issuecomment-597783079

## Acceptance Criteria
- [ ] When a single project is defined the source should be synced to `/projects/<project name>`
- [ ] *TBD for multiple projects*

/kind user-story
/area devfile

**Comment by johnmcollier** [comment]
@rajivnathan Maybe we want this to be a user story?

**Comment by elsony** [comment]
This item is done as part of https://github.com/openshift/odo/issues/2582
/close
