### ISSUE TITLE
'odo catalog list components -o json' does not have `imageStreamRef` in json output after update from v1.0.x to v1.1.0

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2707]
/kind bug
## How did you run odo exactly?
`odo catalog list components -o json`
imageStreamRef

## Actual behavior
`odo catalog list components -o json` for v1.0.x prints json with `imageStreamRef` attribute for every component. It is, I guess, copy of imageStream resource manifest.
`odo catalog list components -o json` for v1.1.0 does not have ``imageStreamRef` anymore. That is backward compatibility issue. VSCode OpenShift Connector extension is using that node metadata to detect component type to identify what debugger Java or Node.js to start. After upgrading odo from 1.0.0 to 1.1.0 it stopped working.

## Expected behavior
-o json output can have additional information included into json output for new releases, but should preserve json structures from previous releases.

## Any logs, error output, etc?
N/A

**Comment by jichenjc** [comment]
v1.0.2 from https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.0.2/
```
   "items": [
        {
            "kind": "ComponentType",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "busybox",
                "namespace": "openshift",
                "creationTimestamp": null
            },
            "spec": {
                "allTags": [
                    "10"
                ],
                "nonHiddenTags": [
                    "10"
                ],
                "imageStreamRef": {
                    "metadata": {
                        "name": "busybox",
                        "namespace": "openshift",
                        "selfLink": "/apis/image.openshift.io/v1/namespaces/openshift/imagestreams/busybox",
                        "uid": "1b3048d1-578b-11ea-8e45-0a580a810020",
                        "resourceVersion": "3054651",
                        "generation": 2,
                        "creationTimestamp": "2020-02-25T04:55:55Z",
                        "labels": {
                            "samples.operator.openshift.io/managed": "true"
                        },
                        "annotations": {
                            "openshift.io/display-name": "Node.js",
                            "openshift.io/image.dockerRepositoryCheck": "2020-02-25T04:55:57Z",
                            "samples.operator.openshift.io/version": "4.2.10"
                        }
                    },
                    "spec": {
                        "lookupPolicy": {
                            "local": false
                        },
                        "tags": [
                            {
                                "name": "10",
                                "annotations": {
                                    "description": "Build and run Node.js 10 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/nodeshift/centos7-s2i-nodejs.",
                                    "iconClass": "icon-nodejs",
                                    "openshift.io/display-name": "OpenShift Application Runtimes Node.js 10",
                                    "openshift.io/provider-display-name": "Red Hat, Inc.",
                                    "sampleRepo": "https://github.com/sclorg/nodejs-ex.git",
                                    "tags": "builder,nodejs",
                                    "version": "10"
                                },
                                "from": {
                                    "kind": "DockerImage",
                                    "name": "registry.access.redhat.com/ubi7"
                                },
                                "generation": 2,
                                "importPolicy": {},
                                "referencePolicy": {
                                    "type": "Local"
                                }
                            }
                        ]
                    },
                    "status": {
                        "dockerImageRepository": "image-registry.openshift-image-registry.svc:5000/openshift/busybox",
                        "tags": [
                            {
                                "tag": "10",
                                "items": [
                                    {
                                        "created": "2020-02-25T04:55:57Z",
                                        "dockerImageReference": "registry.access.redhat.com/ubi7@sha256:7ec9e173ee3e24473e0746e5aca1c5431fdbf81b511c806d66d64acc682f1c22",
                                        "image": "sha256:7ec9e173ee3e24473e0746e5aca1c5431fdbf81b511c806d66d64acc682f1c22",
                                        "generation": 2
                                    }
                                ]
                            }
                        ]
                    }
                }
            }
        },

```

latest code , compiled version
```
   "items": [
        {
            "kind": "ComponentType",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "busybox",
                "namespace": "openshift",
                "creationTimestamp": null
            },
            "spec": {
                "allTags": [
                    "10"
                ],
                "nonHiddenTags": [
                    "10"
                ],
                "supportedTags": []
            }
        },

```

**Comment by jichenjc** [comment]
https://github.com/openshift/odo/pull/2133 is the one might do the change..

**Comment by jichenjc** [comment]
commit 234c8608f5917df41fcfbd04974561f766b59b0b
Author: Girish Ramnani <girishramnani95@gmail.com>
Date:   Fri Dec 13 14:15:12 2019 +0530

    remove ImageStreamRef from machine readable output (#2451)

this is the PR... 

let me know I can help to do the change as it's pretty simple
@dgolovin

**Comment by girishramnani** [comment]
I removed this imageStreamRef for a reason, it wasn't ever supposed to show up in machine readable output. Lets directly provide the information needed here instead of the whole `imageStreamRef`

**Comment by girishramnani** [comment]
I would suggest to discuss with @dgolovin to understand how they were using the `imageStreamRef` and only provide the fields that were necessary for detecting the debugger.

**Comment by jichenjc** [comment]
@dgolovin could you please help to provide some additional info based on the request above? thanks a lot

**Comment by kadel** [comment]
> I removed this imageStreamRef for a reason, it wasn't ever supposed to show up in machine readable output. Lets directly provide the information needed here instead of the whole `imageStreamRef`

what is the harm in including it in the output?

**Comment by girishramnani** [comment]
It has too much information which is not needed and is making the output unnecessarily large. I would suggest to find out what is actually needed and only show that

**Comment by girishramnani** [comment]
I assume the json output is our API, shouldn’t api be clean and not bloated with information which is not necessary.

**Comment by dgolovin** [comment]
@jichenjc on IDE side we need an info to decide what programming language is used for the component development. When we know the language we can for example connect language specific debugger to the component deployed in a cluster. Image name does not give us that information, because it could be anything. Instead IDE analyses image builder tags and try to detect the language for specific component. To do that we pull "imageStreamRef.spec.tags.annotations.tags" and search for "java" or "nodejs" tags to distinguish supported components.

If odo can just provide `language: string` attribute for ComponentType that would work perfectly. This attribute would normally contain only language name like 'java', 'nodejs', 'python' and etc.

**Comment by jichenjc** [comment]
@girishramnani  some info above for the reason, I think it's more related to `tags` or `language` things..thanks

**Comment by girishramnani** [comment]
> To do that we pull "imageStreamRef.spec.tags.annotations.tags" and search for "java" or "nodejs" tags to distinguish supported components.
> 
> If odo can just provide `language: string` attribute for ComponentType that would work perfectly. This attribute would normally contain only language name like 'java', 'nodejs', 'python' and etc.

@dev-gaur This is the solution we need to implement instead of exposing the whole imageStreamRef

**Comment by dev-gaur** [comment]
> > To do that we pull "imageStreamRef.spec.tags.annotations.tags" and search for "java" or "nodejs" tags to distinguish supported components.
> > If odo can just provide `language: string` attribute for ComponentType that would work perfectly. This attribute would normally contain only language name like 'java', 'nodejs', 'python' and etc.
> 
> @dev-gaur This is the solution we need to implement instead of exposing the whole imageStreamRef

ack
