### ISSUE TITLE
Devfile sync and exec support for local docker containers

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2717]
## User Story
As a user, I want to be able to sync my code changes to a Docker container running locally on my laptop. Once my code changes are synced, odo should build the source and run the application. Subsequent `odo push`'s should only sync the changed files (and remove the deleted files), then proceed to rebuild and re-run the application.

(As discussed with @elsony and team, we're breaking up https://github.com/openshift/odo/issues/2579 into two issues)

## Acceptance Criteria 
- [x] It should re-use the `sync` package in odo, and make `lclient` / `dockerclient` implement the `SyncClient` interface
- [x] It should only sync the changed files (and remove any deleted files)
- [x] Container exec for build/run should follow the same model as described in https://github.com/openshift/odo/issues/2654
- [x] Unit and tests and integration tests need to be written
   - Integration tests to only run on Travis CI

## Links 
- Parent epic: https://github.com/openshift/odo/issues/2576

/kind user-story
/area devfile
/area local

**Comment by kadel** [comment]
What about volumes created based on the `volumes` definition in devfile.yaml component?
I can see that with #2922 they are not deleted.

```
▶ odo push
 •  Push devfile component backend  ...
 ✓  Pulling image quay.io/eclipse/che-java11-maven:nightly [5s]
 ✓  Starting container for quay.io/eclipse/che-java11-maven:nightly [382ms]
 ✓  Pulling image busybox [3s]
 ✓  Starting container for busybox [496ms]
 ✓  Push devfile component backend [9s]
 ✓  Changes successfully pushed to component

tmp/odo-examples/demo-backend  master ✗                                                                                                                                          14d ⚑ ◒
▶ docker volume ls
DRIVER              VOLUME NAME
local               m2-backend-nwpm
local               odo-project-source-backend-bqfz

tmp/odo-examples/demo-backend  master ✗                                                                                                                                          14d ⚑ ◒
▶ odo delete
? Are you sure you want to delete the devfile component: backend? Yes
 ✓  Deleting devfile component backend [398ms]
 ✓  Successfully deleted component

tmp/odo-examples/demo-backend  master ✗                                                                                                                                          14d ⚑ ◒
▶ docker volume ls
DRIVER              VOLUME NAME
local               m2-backend-nwpm
```

**Comment by elsony** [comment]
Feature done
