### ISSUE TITLE
ClusterHost is an incorrect parameter / term for url creation 

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2721]
/kind feature

## Which functionality do you think we should add?

`--clusterHost` should be `--host` for `odo url create`.

## Why is this needed?

ClusterHost parameter for url creation is an incorrect parameter term.

The term **Cluster Host** in kubectl and oc is confusing because Cluster Host actually means Kubernetes / OpenShift "host".

It is confusing because we are specifying a domain name for url creation.. ex: `odo url create --clusterHost example.domain.com`

We should be using the correct term which would actually be `host`, which is exactly what OpenShift uses in the yaml creation for Route.

For example, the current code that is implemented looks like this:

```go
				Host: ingressParam.IngressDomain,
```

**Comment by cdrage** [comment]
Ping @yangcao77 @kadel @GeekArthur

**Comment by yangcao77** [comment]
The host we want user to specify is the cluster host, not the entire domain. 
If the domain we want is `example.domain.com`, then the command should be 
`odo url create example --clusterHost domain.com`

**Comment by cdrage** [comment]
"Cluster Host" is a different definition as "host" or ingress. "Cluster Host" is also not used at all within Kubernetes / OpenShift YAML. 

If you want to define an ingress domain, it should just be `host` similar to Kubernetes / OpenShift YAML definitions. 

I agree to switching it to just `--host`.
