### ISSUE TITLE
How do I login to remote openshift like in oc

### ISSUE THREAD

**Issue by raguks** [openshift/odo#2722]
How do I login to remote openshift like in oc? May be this is assumed but took me a while to figure out.

This did not seem to be documented anywhere.
```
$ odo login https://api.somecluster.os.fyre.ibm.com:6443
Connecting to the OpenShift cluster

Authentication required for https://api.somecluster.os.fyre.ibm.com:6443 (openshift)
Username: kubeadmin
Password:
Login successful.

You have access to 64 projects, the list has been suppressed. You can list all projects with 'odo projects'

Using project "default".
```
Doc here:
https://docs.openshift.com/dedicated/4/cli_reference/openshift_developer_cli/understanding-odo.html

**Comment by kadel** [comment]
/kind docs

It is mentioned in all our examples - https://docs.openshift.com/dedicated/4/cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.html

Or in CLI reference page https://docs.openshift.com/dedicated/4/cli_reference/openshift_developer_cli/odo-cli-reference.html#login


Do you suggest that we create some special page to describe login?

**Comment by raguks** [comment]
odo documentation does not state how to specify which openshift cluster to login to. I guessed I could specify the url (odo login url). Once I specified the url of the openshift server odo login by default connects to that sever (I cant repro what happened when I tried odo login because of this default server thing). What is the format of the openshift url ? Shouldnt we document these? 

Specifying a remote openshift cluster url is NOT documented in the first instance. I could not find the examples (discovery issue). The documentation is very confusing.

**Comment by girishramnani** [comment]
@cdrage something that u could take a look at?

**Comment by cdrage** [comment]
> odo documentation does not state how to specify which openshift cluster to login to. I guessed I could specify the url (odo login url). Once I specified the url of the openshift server odo login by default connects to that sever (I cant repro what happened when I tried odo login because of this default server thing). What is the format of the openshift url ? Shouldnt we document these?
> 
> Specifying a remote openshift cluster url is NOT documented in the first instance. I could not find the examples (discovery issue). The documentation is very confusing.

Hi Raguks, it is documented in `odo login --help`.

See below:

```sh
github.com/openshift/odo  remove-tech-preview ✔                                                                                                                                                                                                                                                                                                                      3h48m  
▶ odo login --help
Login to cluster

Usage:
  odo login [flags]

Examples:
  # Log in interactively
  odo login
  
  # Log in to the given server with the given certificate authority file
  odo login localhost:8443 --certificate-authority=/path/to/cert.crt
  
  # Log in to the given server with the given credentials (basic auth)
  odo login localhost:8443 --username=myuser --password=mypass
  
  # Log in to the given server with the given credentials (token)
  odo login localhost:8443 --token=xxxxxxxxxxxxxxxxxxxxxxx

Flags:
      --certificate-authority string   Path to a cert file for the certificate authority
  -h, --help                           Help for login
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
  -p, --password string                Password, will prompt if not provided
  -t, --token string                   Token, will prompt if not provided
  -u, --username string                Username, will prompt if not provided

Additional Flags:
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
```

If you have used `oc`, `odo login` is a direct copy-and-paste from `oc login`. We actually simply wrap around the `oc` command using their library.

I am closing this as I believe we have amply documentation detailing this.
