### ISSUE TITLE
index file should be created/updated after the files are synced with the pod

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#2728]
/kind bug

## What versions of software are you using?

**Operating System:** fedora 30

**Output of `odo version`:** `master`

## How did you run odo exactly?
- `odo create nodejs hello`
- `npm init --yes`
- `odo push` which I terminated using `Ctrl + C` in between when odo was waiting for component to start.

```
$ odo push
Validation
 ✓  Checking component [925ms]

Configuration changes
 ✓  Retrieving component data [1s]
 ✓  Applying configuration [1s]

Pushing to component t2r of type local
 ✓  Checking file changes for pushing [1ms]
 ✓  Waiting for component to start [319ms] 
^C # stopped here
```
Now the issue here is that the `odo-index-file.json` gets created at the `Checking file changes for pushing [1ms]` stage but no files were actually synced with the pod which means on the next `odo push` the files wont be synced even though there are no files present on the pod.

We should create/update the `odo-index-file.json` after the files get synced. This would allow us to be resilient to above inconsistent states.

**Comment by jichenjc** [comment]
I can take a look :)

**Comment by girishramnani** [comment]
@jichenjc you can ping me on public odo slack and I will assign you the issues you like. Only then please start working on them.

**Comment by jichenjc** [comment]
sorry, I didn't notice this rule
I will follow this next time, for this issue, if you have other ways already, let me know then I will drop my one, thanks a lot and sorry for inconvenience @girishramnani
