### ISSUE TITLE
Add componentType in odo list output

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#2730]
/kind feature

## Which functionality do you think we should add?
`odo list -o json` should mention the specific componentType associated with that component.
e.g. `'type': 'git'`

## Why is this needed?

With the change mentioned with this PR https://github.com/openshift/odo/pull/2674 , it removes `Source` tag from the output.
The adapters workflow was using this tag to figure out the component Type as in git, binary, local.
Hence this change will help in keeping the view consistent in OpenShift connector view.

**Comment by jichenjc** [comment]
I have the following , looks like the type is kept? or misunderstand the question above? Thanks
```
 "spec": {
                "app": "app",
                "type": "ubi",
                "source": "file://./",
                "env": [
                    {
                        "name": "DEBUG_PORT",
                        "value": "5858"
                    }
                ]
            },

```

**Comment by girishramnani** [comment]
@jichenjc are you planning to work on this?

**Comment by girishramnani** [comment]
If not, I would like to work on this.

**Comment by jichenjc** [comment]
yes, please, I didn't plan to work on this , above are just questions to make sure understand this
thanks for asking this @girishramnani

**Comment by girishramnani** [comment]
@mohitsuman currently the json output looks like this

( for a single component present in an application )
```
{
            "kind": "Component",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "nodejs-tesrr-hqtz",
                "namespace": "testproject",
                "creationTimestamp": null
            },
            "spec": {
                "app": "app",
                "type": "nodejs",
                "source": "file://./",
                "ports": [
                    "8080/TCP"
                ]
            },
            "status": {
                "state": "Not Pushed"
            }
        }
``` 
now the issue is that we already have a `type` which corresponds to the component type i.e. `nodejs`, `java` etc.

To introduce the `git`,`local` or `binary` information in the json output we can consider

- `source_type`
- `source`

**Comment by girishramnani** [comment]
In terms of implementation we already have `sourceType` present as an annotation here https://github.com/openshift/odo/blob/2a56a67dc45e9ca5559a6cc243fda0e294b48e79/pkg/component/component.go#L1015.
Its just matter of exposing it for `--all` and current application scenerio.

I would also consider changing the standard output ( non-json one ) to have the sourceType information for consistency.
