### ISSUE TITLE
Projects are not synced to the devfile clonePath

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2741]
/kind bug
/area devfile

## What versions of software are you using?
Using odo experimental support for devfiles by building from source

## Description of the problem
Devfile sync doesn't currently handle the `clonePath` field that's used by some devfiles. eg. https://github.com/eclipse/che-devfile-registry/blob/5a41b4b0c85893a6ee99059fcceab35b8a71780c/devfiles/go/devfile.yaml#L11

## Actual behavior
The source is synced to `/projects`

## Expected behavior
The source should be synced to `/projects/src/github.com/golang/example/` which is what Che does.

## Any logs, error output, etc?
No errors for the sync, but errors result when trying to use commands because they're expecting the source to be under the clonePath directory.

**Comment by johnmcollier** [comment]
/assign

This should be an easy one to fix, we'll adapt how we handle syncing when a project is defined in the devfile:
- If `clonePath` is set, we'll sync to `/projects/<clonePath>`
- If `clonePath` is not set, we'll sync to `/projects/<projectName>`, as before.

**Comment by rajivnathan** [comment]
There also seems to be a `sparseCheckoutDir` property. See https://github.com/eclipse/che-devfile-registry/blob/5a41b4b0c85893a6ee99059fcceab35b8a71780c/devfiles/quarkus/devfile.yaml#L11

There are more properties for `source`, see https://github.com/redhat-developer/devfile/blob/master/docs/devfile.md#projects

**Comment by johnmcollier** [comment]
As discussed on Slack, we won't need `sparseCheckoutDir` for file syncing, as it just determines _which_ folder in the Git repo to pull down.

We will need it however for template/resource creation, so I've added it as an item in https://github.com/openshift/odo/issues/2582

**Comment by kadel** [comment]
> This should be an easy one to fix, we'll adapt how we handle syncing when a project is defined in the devfile:
> 
> * If `clonePath` is set, we'll sync to `/projects/<clonePath>`
> * If `clonePath` is not set, we'll sync to `/projects/<projectName>`, as before.

It looks a bit weird, but I don't think that we can't do much better than this as we currently don't support multiple projects in devfile anyway


so +1

**Comment by kadel** [comment]
> * If `clonePath` is set, we'll sync to `/projects/<clonePath>`

This actually doesn't look right. I think that if the `clonePath` is set you should use it as it is.
It should be `/<clonePath>`  not `/projects/<clonePath>`
