### ISSUE TITLE
PR merge shows wrong CI status in odo github dashboard

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2742]
/kind bug

## What versions of software are you using?

**Operating System:** 
NA
**Output of `odo version`:**
NA
## How did you run odo exactly?
NA

## Actual behavior
Attaching screenshoot for easy understanding.

<img width="1115" alt="Screen Shot 2020-03-22 at 10 09 24 AM" src="https://user-images.githubusercontent.com/19851115/77242672-d23d2100-6c26-11ea-817e-907c133a58f8.png">

Dashboard showing wrong info after merging because ```openshift-merge-robot``` sometime merges the pr without checking the CI status properly.

image for reference 
<img width="805" alt="Screen Shot 2020-03-22 at 10 30 51 AM" src="https://user-images.githubusercontent.com/19851115/77242830-d66a3e00-6c28-11ea-9487-8d97aaab603d.png">
 
Pr that encountered the issue - https://github.com/openshift/odo/pull/2694

## Expected behavior
status should be a green tik mark

**Comment by kadel** [comment]
This looks like a duplicate.

see https://github.com/openshift/odo/issues/2019

**Comment by girishramnani** [comment]
closing
