### ISSUE TITLE
odo push for devfile fails with container is not created

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2743]
/kind bug

## How did you run odo exactly?

- normal `odo push` with a devfile
- oc delete deployments nodejs-ex && odo push

## Actual behavior

[mrinaldas@localhost nodejs-ex]$ odo push
 •  Push devfile component nodejs-ex  ...
 ✓  Checking files for pushing [37ms]
 ✓  Waiting for component to start [584ms]
 ✗  Syncing files to the component [17s]
 ✗  Failed to start component with name nodejs-ex.
Error: Failed to create the component: Failed to sync to component with name nodejs-ex: error while streaming command: Internal error occurred: error executing command in container: container is not created or running

## Expected behavior

Successful push

**Comment by johnmcollier** [comment]
This looks to be the same error that @adisky reported on Slack, @mik-dass if you pull down Tomas' branch from https://github.com/openshift/odo/pull/2731 are you able to reproduce?

I'm wondering too, if you run `kubectl get deployments`, does a deployment exist? And what's the status of any pods that get created too?

**Comment by mik-dass** [comment]
>  if you pull down Tomas' branch from #2731 are you able to reproduce?

#2731 seems to have resolved the issue. Thanks.

/close
