### ISSUE TITLE
context support for odo push

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2744]
/kind feature

### User Story

As a user, I want to trigger ODO commands from outside the source code directory using the context flag.
 
### Acceptance criteria

- [ ] ODO push for devfiles should support context and should work outside of the component directory e.g `odo push --devfile test/devfile.yaml --context source-dir/`

## Why is this needed?

The user won't have to switch directories to push components.

**Comment by kadel** [comment]
This needs to be converted into user story

**Comment by yangcao77** [comment]
When working on context support, this issue should be take into consideration: https://github.com/openshift/odo/issues/2959
