### ISSUE TITLE
Execute devfile commands other than build and run

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2754]
/kind user-story

## User Story
As a user I want to execute commands present in the devfile.

With odo push you can specify `--build-command` and `--run-command` but in some cases another command may be required. For example https://github.com/eclipse/che-devfile-registry/blob/b473b5309c57cc2e7ae098691a6b18e23de7b6fc/devfiles/java-mysql/devfile.yaml#L84

One way we can accomplish this is to create something like an `odo exec --command=<command name>` command that accepts commands. The commands can be run as foreground processes much like how the build commands work for `odo push`. We can consider whether long running background processes are wanted.

## Acceptance Criteria 
- [ ] Ability to execute any command that is linked to a component supported by odo (eg. `dockerimage`
- [ ] I should be able to see the output of the command

## Links 
- Related issue: https://github.com/openshift/odo/issues/2654

/kind user-story
/area devfile

**Comment by maysunfaisal** [comment]
I think this can be closed with the concept of init command @elsony @kadel?

**Comment by adisky** [comment]
I think it is implemented by https://github.com/openshift/odo/pull/3083

**Comment by elsony** [comment]
> I think this can be closed with the concept of init command @elsony @kadel?

@maysunfaisal  No, I don't think this is the same as the init command. This one is meant to execute commands that are defined in a devfile. It does not necessary to be something run at the start of the container.

> I think it is implemented with `odo exec` feature #3083

@adisky Feature #3083 is different from this item. #3083 provide a convenient way for someone to execute command on the running runtime container without exec into the container itself. Those commands that get passed in are shell command and not something defined in the devfile. This feature allows someone to exec a command that is already defined in the devfile. The user only need to refer to the command name defined in the devfile to execute that command, e.g. `odo exec <command name in devfile>` to execute the given command in devfile.  Having said that, given that #3083 already added the `odo exec` command, when we implement this one, we need to make sure the syntax of the command is clear that the user is executing a shell command vs command with a devfile, e.g. do something like `odo exec --devfile-command=<command name>`.

**Comment by adisky** [comment]
still valid issue
/remove-lifecycle rotten
