### ISSUE TITLE
Devfile odo push should use --project instead of --namespace

### ISSUE THREAD

**Issue by rajivnathan** [openshift/odo#2769]
/kind bug
/area devfile

## Description

`odo create` uses the `--project` option to specify a project/namespace but `odo push` uses `--namespace`. Push should be updated to use `--project` as previously agreed upon.

**Comment by kadel** [comment]
We need to be a little bit careful about this. 
It will be a big breaking change!
It needs to be coordinated with https://github.com/redhat-developer/intellij-openshift-connector and https://github.com/redhat-developer/vscode-openshift-tools (cc: @dgolovin and @jeffmaury )

Some kind of slow depreciation might be good here.

For example, in the first stage, we could just hide `--project` from help output but it would still work.

Or I would maybe even consider keeping both flags as for OpenShift users the `--project` might make more sense and `--namespace` might be just confusing.

**Comment by rajivnathan** [comment]
@kadel IIRC what was previously discussed was to just support `--project` and add support for `--namespace` later which is what this issue's description was saying. Although, I may not have worded it that well. :) Supporting both is also fine but just wanted to clarify I was not suggesting we switch to use --namespace.

**Comment by kadel** [comment]
> @kadel IIRC what was previously discussed was to just support `--project` and add support for `--namespace` later which is what this issue's description was saying. Although, I may not have worded it that well. :) Supporting both is also fine but just wanted to clarify I was not suggesting we switch to use --namespace.


Oh sorry, I didn't read the description carefully and assumed that this is about switching from `--project` to `--namespace`


Yes, for now, let's just use `--project` everywhere to be consistent.

We can figure out later what to do with namespace
