### ISSUE TITLE
Restructure the documentation in odo repository

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2780]
/kind documentation

## What mistake did you find / what is missing in the documentation?
As we add more documentation to help users get comfortable with using odo for both OpenShift & Kubernetes clusters, we need to restructure the documentation that we have right now under `docs/` directory.

## What is the relevance of it?
This is to make specific user documentation easier to find and consume.

**Comment by cdrage** [comment]
Hey @dharmit do you mind outlining what specifically needs to be organized?

Do you mean, having user-facing docs within the GitHub repo as well as the site (essentially, a central repository for all docs, rather than hunting through https://github.com/openshift/docs)

**Comment by dharmit** [comment]
@cdrage for now this issue doesn't look much relevant to me since we've already been working on adding docs. Closing this. Will open a new one if required.

/close
