### ISSUE TITLE
Warning message gets printed multiple times

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2782]
/kind bug

## How did you run odo exactly?

`odo push`

## Actual behavior

```
[mrinaldas@localhost nodejs-ex]$ odo push
Validation
 ✓  Checking component [1s]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [5s]

Pushing to component nodejs-nodejs-ex-nyyg of type local
 ✓  Checking files for pushing [715424ns]
 ◐  Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ◓  Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ◑  Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ◒  Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ◐  Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ◓  
^C
```
`Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ◓  ` gets printed again and again.

## Expected behavior

`Waiting for component to start [⚠ WARNING x5: BackOff, use `-v` for more inf ` to be printed once

**Comment by cdrage** [comment]
@mik-dass Is your terminal really small? This is what may be causing the issue.. I may have to shorten the info / output)

**Comment by mik-dass** [comment]
> @mik-dass Is your terminal display really small? This is what may be causing the issue.. I may have to shorten the info / output). Can you re-run it with your terminal display wider?

yes on a wider terminal, the duplication seems to be gone.

**Comment by cdrage** [comment]
@mik-dass Yup. That's normal. It's the terminal doing it's thing with regards to the spinner. 

I do realize that the warning message is actually quite long, I'm going to push a PR to reduce the size to hopefully we don't have this occur again on smaller terminals.

**Comment by mik-dass** [comment]
> I do realize that the warning message is actually quite long, I'm going to push a PR to reduce the size to hopefully we don't have this occur again on smaller terminals.

OK :+1:
