### ISSUE TITLE
Instantiate operator backed service and output JSON data

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2784]
/kind user-story

## User Story
As a user (Adapters) I want to instantiate an operator backed service and get the feedback/output from odo in JSON format so that it can be presented to end-user in a simple form

## Acceptance Criteria 
- [ ] `odo service create <operator/CR> -o json` should provide the output/feedback in JSON format.
- [ ] `odo service describe <service-name>` to describe service in human-readable form (without `spec`)
- [ ] `odo service describe <newly created service> -o json` should provide similar output as `odo service create <operator/CR> -o json` plus `age`.

## Links 
- Feature Request: #4591

/kind user-story

**Comment by girishramnani** [comment]
the old service catalog also doesn't have json output

**Comment by dharmit** [comment]
Closing this for now since we've not had support for this since v1 and there's not much in terms of request to add this for v2. Please reopen this if you would like us to consider this.

/close

**Comment by dharmit** [comment]
/reopen

Reopening based on conversation with @kadel. We want to have this feature for operator backed services. This would make all the `create` commands of odo more consistent.

**Comment by dharmit** [comment]
> odo service create <operator/CR> -o json should provide the output/feedback in JSON format.

This output should contain the Kubernetes Inlined component YAML but converted into JSON. And it should be in the spec. We need to decorate it with `apiVersion: odo.dev/v1`, `kind: Service`, etc. which is odo specific API output.

> odo service describe <newly created service> -o json should provide same output as above.

This should have similar output as above.

**Comment by valaparthvi** [comment]
`odo service create service-binding-operator.v0.7.1/ServiceBinding  -o json` and  `odo service describe ServiceBinding/example-servicebinding -o json` decorated with `apiVersion: odo.dev/v1` and `kind: Service` would look something like this - 

```
{
            "kind": "Service",
            "apiVersion": "odo.dev/v1",
            "metadata": {
                "name": "example-servicebinding",
                "namespace": "pvala-crt-dev",
            },
            "spec": {
                "application": {
                    "group": "apps",
                    "name": "nodejs-rest-http-crud"
                    "resource": "deployments"
                    "version": "v1"
                },
                "services": [
                    {
                     group: postgresql.example.dev
                     "kind": "Database"
                     "name": "pg-instance"
                     "version": "v1alpha1"
                    },
                ]
            }
        }
```

Along with the above, we should also consider changing `odo service list -o json` to be inline with odo's API output. Which can look something like this - 
```
{
    "kind": "ServiceList",
    "apiVersion": "odo.dev/v1alpha1",
    "metadata": "",
    "services":[
        {
            "kind": "Service",
            "apiVersion": "odo.dev/v1",
            "metadata": {
                "name": "example-servicebinding",
                "namespace": "pvala-crt-dev",
            },
            "spec": {
                "application": {
                    "group": "apps",
                    "name": "nodejs-rest-http-crud"
                    "resource": "deployments"
                    "version": "v1"
                },
                "services": [
                    {
                     group: postgresql.example.dev
                     "kind": "Database"
                     "name": "pg-instance"
                     "version": "v1alpha1"
                    },
                ]
            }
        },
    ]
}
```

We already have `odo service <operator/crd> --dry-run` for operator-backed services that prints the inlined Kubernetes manifest, so what we will need is converting that to odo specific output.

**Comment by girishramnani** [comment]
@valaparthvi if you dont have bandwidth to work on this issue in this sprint, do you mind if I pick this up?

**Comment by valaparthvi** [comment]
@girishramnani Sure, I don't have a problem with that.

**Comment by girishramnani** [comment]
Just so I am not blocked I might open a cascading PR based on this branch https://github.com/openshift/odo/pull/4704 (in worst case)

**Comment by girishramnani** [comment]
We dont like unpushed services yet here @kadel?

**Comment by kadel** [comment]
> We dont show unpushed services yet here on `odo service list` @kadel?

This was supposed to be implemented in https://github.com/openshift/odo/issues/4160

**Comment by girishramnani** [comment]
The scope of this issue was json output for `odo service describe` and `odo service create`, going over the discussion got me confused that do wanna consider `odo service list` as part of this issue as well?
cc @dharmit

**Comment by dharmit** [comment]
> The scope of this issue was json output for `odo service describe` and `odo service create`, going over the discussion got me confused that do wanna consider `odo service list` as part of this issue as well?

That would be a cherry on the cake if we do it with this one. But I don't mind a separate issue either. Do whatever seems best to you @girishramnani.

**Comment by girishramnani** [comment]
I went through the code and feel that when we list services we should show common fields of each service ( as each service could have a different spec ). so `odo service list --json` would look like below.
```
{
    "kind": "ServiceList",
    "apiVersion": "odo.dev/v1alpha1",
    "metadata": "",
    "services":[
        {
            "kind": "Service",
            "apiVersion": "odo.dev/v1",
            "metadata": {
                "name": "example-servicebinding",
                "namespace": "pvala-crt-dev",
            },
            "spec": {
                "services": [
                    {
                     group: postgresql.example.dev
                     "kind": "Database"
                     "name": "pg-instance"
                     "version": "v1alpha1"
                     "status": "Pushed"
                     "age": "<timestamp>"
                    },
                ]
            }
        },
    ]
}
```
Observe I have removed the `application section` as that might not be as helpful.

---------

**`odo service describe` <- doesn't even exist**
```
do service describe
Error: Subcommand not found, use one of the available commands: create, delete, list
Usage:
  odo service [flags]
  odo service [command]

Examples:
  # Create new postgresql service from service catalog using dev plan and name my-postgresql-db.
  odo service create dh-postgresql-apb my-postgresql-db --plan dev -p postgresql_user=luke -p postgresql_password=secret

  # Create new EtcdCluster service from etcdoperator.v0.9.4 operator.
  odo service create etcdoperator.v0.9.4/EtcdCluster

  # Delete the service named 'mysql-persistent'
  odo service delete mysql-persistent

  # List all services in the application
  odo service list

Available Commands:
  create      Create a new service from Operator Hub or Service Catalog and deploy it on OpenShift.
  delete      Delete an existing service
  list        List all services in the current application

Flags:
  -h, --help   Help for service

Additional Flags:
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

Use "odo service [command] --help" for more information about a command.

 ✗  Subcommand not found, use one of the available commands: create, delete, list
```

So should I implement that as well with json output. I think we remove it because it wasn't giving more information then `odo service list`.

------

`odo service create -o json`
```
{
            "kind": "Service",
            "apiVersion": "odo.dev/v1",
            "metadata": {
                "name": "example-servicebinding",
                "namespace": "pvala-crt-dev",
            },
            "spec": {
                "services": [
                    {
                     group: postgresql.example.dev
                     "kind": "Database"
                     "name": "pg-instance"
                     "version": "v1alpha1"
                     "status": "Not Pushed"
                    },
                ]
            }
        }
```

Observe I have removed `age` from create output as that doesn't make sense for a new service.
Also should I add the `spec` information of the service for `create -o json` as this information is specific to just one service we could include unstructured information?
cc @kadel

**Comment by girishramnani** [comment]
spec information would be something like `size` for etcCluster or `databaseUser` for Postgres CR. whatever is returned by in the unstructured response

**Comment by dharmit** [comment]
As @feloy mentioned on the planning call, we want to work further on this after getting #4948 in.
