### ISSUE TITLE
Add url state in describe and list for odo2 devfile support

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#2787]
/kind feature

## Which functionality do you think we should add?
Currently devfile URL(ingress) `describe` and `list`  are missing the state
```
NAME            URL                                        PORT
springtest1     https://springtest1.9.42.26.107.nip.io     8080
```

Url state should be added and displayed as what odo url (routes) does.

**Comment by yangcao77** [comment]
Related issue: https://github.com/openshift/odo/issues/2778

**Comment by mohammedzee1000** [comment]
@yangcao77 the pr was merged. We should now be able to make further changes as needed to handle description for devfile
