### ISSUE TITLE
odo create support existing devfile.yaml

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#2789]
/kind user-story
/area devfile

## User Story
As a user I want to use my own devfile.yaml instead of using the devfile.yaml from devfile registry, so we come up with a new design for supporting existing devfile.yaml

odo create always creates env.yaml

If devfile.yaml is not present
Case 1: `odo create <component type>` -> Download devfile from devfile egistry ✅ 
Case 2: `odo create` -> ~Throw errors and tell user to specify component type with running odo create <component type>~
UPDATE: I check the current code, the interactive mode already covered this case ✅ 

If devfile.yaml is present
Case 1: `odo create <component type>` -> Throw errors and tell user to delete the existing devfile.yaml then run odo create <component type> again 🚧 
Case 2: `odo create` -> Use the existing devfile.yaml 🚧  This case should be implemented by @yangcao77 's PR or I can implement this in my PR, either way works for me

**Comment by adisky** [comment]
> Case 2: devfile.yaml present
- `odo create <component>` -> Throw errors and tell user to delete the existing devfile.yaml then run `odo create <component>` again
- `odo create` -> Use the existing devfile.yaml

Little confused for `case2` if `devfile.yaml` is present shouldn't it straightforwardly create the component or have explicit warning/interactive mode? 

IIUC you are using the existing devfile in second run of `odo create`, would you record it somewhere? or 
I think i am not able to understand it correctly :)

**Comment by GeekArthur** [comment]
@adisky 

Yes, that's right, we should directly use `devfile.yaml` if `devfile.yaml` is present in user's workspace directory, and we don't need second run of `odo create`, all `odo create` operation should be finished in one run. I think I should format the cases more readable for better understanding 😄. I already updated the issue description. 

Generally speaking, if user's workspace directory doesn't have `devfile.yaml` and `env.yaml`, `odo create <component type>` is responsible for downloading `devfile.yaml` from devfile registry according to the `<component type>` that user specifies and generating `env.yaml` file.

However, for case 2, if `devfile.yaml` is present, user may input two kinds of `odo create` commands:

If user input `odo create <component type>`, we should throw errors and tell user to delete the existing devfile.yaml then run `odo create <component tyep>` again as we already have `devfile.yaml` in user's workspace directory and we can't use `<component type>` that user specifies to download the `devfile.yaml` (one `devfile.yaml` per user's workspace)

If user input `odo create`, we directly use the `devfile.yaml` in user's workspace directory

**Comment by adisky** [comment]
@GeekArthur Thanls understood now!!
