### ISSUE TITLE
odo push deletes project files after making a change to devfile

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#2807]
/kind bug

## What versions of software are you using?

**Operating System:** 

**Output of `odo version`:** master

## How did you run odo exactly?

I noticed this when writing integration tests for devfile exec and confirmed this on the master branch without any of the exec code. Also seeing this with the integration test suite on the master branch.

- `odo set experimental true`
- `odo push`
- change devfile like ENV for a container
- `odo push`

## Actual behavior
All the project files disappear from the container after the second push 😢 

## Expected behavior
Project files should be there! 😄 

##### after first push
```
Maysuns-MacBook-Pro:T maysun$ oc exec -it spring-devfile-66ffc6549-skn2d bash -c tools
root@spring-devfile-66ffc6549-skn2d:/# cd /projects/springbootproject/
root@spring-devfile-66ffc6549-skn2d:/projects/springbootproject# ls -la
total 55372
drwxr-xr-x. 5 root root       231 Apr  2 22:40 .
drwxrwxrwx. 3 root root        31 Apr  2 22:40 ..
-rw-r--r--. 1  501 staff      213 Oct 21 19:00 .cw-settings
-rw-r--r--. 1  501 staff       74 Mar 13 16:23 .gitignore
drwxr-xr-x. 2 root root        25 Apr  2 22:40 .vscode
-rw-r--r--. 1  501 staff      237 Oct 21 19:00 Dockerfile
-rw-r--r--. 1  501 staff     2409 Oct 21 19:00 Dockerfile-build
-rw-r--r--. 1  501 staff      325 Oct 21 19:00 Dockerfile-tools
-rw-r--r--. 1  501 staff       97 Oct 21 19:00 Jenkinsfile
-rw-r--r--. 1  501 staff     1814 Oct 21 19:00 README.md
drwxr-xr-x. 3 root root        32 Apr  2 22:40 chart
-rw-r--r--. 1  501 staff     1770 Apr  2 22:34 devfile.yaml
-rwxr-xr-x. 1  501 staff 56662652 Mar 31 19:56 odo
-rw-r--r--. 1  501 staff     3011 Oct 21 19:00 pom.xml
drwxr-xr-x. 4 root root        30 Apr  2 22:40 src
```

##### after second push
```
Maysuns-MacBook-Pro:T maysun$ oc exec -it spring-devfile-57484d9b8f-8kq2x bash -c tools
root@spring-devfile-57484d9b8f-8kq2x:/# cd /projects/springbootproject/
root@spring-devfile-57484d9b8f-8kq2x:/projects/springbootproject# ls -la
total 4
drwxr-xr-x. 2 root root    26 Apr  2 22:43 .
drwxrwxrwx. 3 root root    31 Apr  2 22:43 ..
-rw-r--r--. 1  501 staff 1766 Apr  2 22:42 devfile.yaml
```

/area devfile

**Comment by johnmcollier** [comment]
This is because we're using an emptyDir volume to store the project source and the pod that it's mounted to is going down, thus taking down the emptyDir volume to.

Solution is to probably compare the resource versions of the component's pod before and after we attempt updates to it, if they're different it means the pod was recreated and we need to do a full sync. We could even just look at the pod name before and after to determine.

I'll take a look at this tomorrow /assign
