### ISSUE TITLE
Examples are missing for devfile UX when experimental is enabled

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2812]
/kind feature

## Which functionality do you think we should add?
Talkative examples for experimental feature for example devfile UX when experimental is enabled.

## Why is this needed?
Because it is missing in UX and ofcourse for better user experience.

What is missing : devfile command example is missing in the example section when experimental is enabled.

1.
```
$ ODO_EXPERIMENTAL=true odo push devfile --help
Push source code to a component.

Usage:
  odo push [component name] [flags]

Examples:
  # Push source code to the current component
  odo push
  
  # Push data to the current component from the original source.
  odo push
  
  # Push source code in ~/mycode to component called my-component
  odo push my-component --context ~/mycode

Flags:
      [...]
      --devfile string       Path to a devfile.yaml (default "./devfile.yaml")
      [...]
      --namespace string     Namespace to push the component to
      [...]

```
2.
```
$ ODO_EXPERIMENTAL=true odo create --help
Create a configuration describing a component.

 [...]

Usage:
  odo create <component_type> [component_name] [flags]

Examples:
  # Create new Node.js component with the source in current directory.
  odo create nodejs
  
  # Create new Node.js component named 'frontend' with the source in './frontend' directory
  odo create nodejs frontend --context ./frontend
  
  # Create new Java component with binary named sample.jar in './target' directory
  odo create java:8  --binary target/sample.jar
  
  # Create new Node.js component with source from remote git repository
  odo create nodejs --git https://github.com/openshift/nodejs-ex.git
  
  # Create new Node.js component with custom ports, additional environment variables and memory and cpu limits
  odo create nodejs --port 8080,8100/tcp,9100/udp --env key=value,key1=value1 --memory 4Gi --cpu 2

Flags:
      [...]
  -n, --namespace string    Create devfile component under specific namespace
      [...]
```

**Comment by GeekArthur** [comment]
Expected implementations
- [ ] Add `odo create` examples for devfile component to the help page
- [ ] Remove `--namespace` flag usage when experimental mode is disabled

**Comment by dev-gaur** [comment]
@amitkrout there are already devfile specific examples included in UX for `odo create -h` and `odo push -h` .

for create :
https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L127

for push :
https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/push.go#L37

**Comment by amitkrout** [comment]
Right, then why is not being reflect the in the UX. Will check it again, may me it has been updated through some pr.

**Comment by girishramnani** [comment]
any update on this @amitkrout

**Comment by amitkrout** [comment]
> any update on this @amitkrout

checking

**Comment by amitkrout** [comment]
On master, i can see the missing devfile examples. It has been fix through some other pr i guess.
