### ISSUE TITLE
Add devfile command flags to odo watch

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#2819]
/kind user-story

[EDITED] (Check Edit history for previous User Story Acceptance Criteria)

## User Story
We discussed when working on the PR https://github.com/openshift/odo/pull/3075, that saving commands for push flags, was not the way to go.

So, we've introduced flags `build-command`, `run-command` for odo watch

## Acceptance Criteria 
- [ ] odo watch should be able to execute with `build-command`
- [ ] odo watch should be able to execute with `run-command`

## Links 
- Feature Request: 
- Related issue: https://github.com/openshift/odo/issues/2654

/kind user-story
/area devfile

**Comment by kadel** [comment]
I don't think that this is good design. It will be an anti-pattern in odo. `odo push` flags should not get persisted in env.yaml.


As a user, I wouldn't expect that. Flags are there to make one-time change not to persist it.

The original intention for --build-command and --run-command flags in odo push command was to allow users to execute the alternative build or run command just one-time.

If we want to safe non-default commands it should be using `odo config` command. Or I could also see this in `odo create`. But for `odo push` it doesn't really make much sense.
