### ISSUE TITLE
"--context" support for odo create

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#2824]
/kind user-story

## User Story
As a user, I want to create devfile component from outside the source code directory using the context flag.

## Acceptance Criteria 
- [ ] `odo create` for devfiles should support context and should work outside of the component directory (eg `odo create nodejs --context source-dir/`)

## Links 
- Related issue: https://github.com/openshift/odo/issues/2813

/kind user-story
/area devfile

**Comment by dharmit** [comment]
> (eg `odo create nodejs --devfile test/devfile.yaml --context source-dir/`)

I don't see `--devfile` flag for `odo craete` in current `master` branch. Are we proposing to add both `devfile` and `context` flags in this story?

**Comment by GeekArthur** [comment]
@dharmit I just update the description to remove `--devfile` to avoid confusion. Currently `odo create` doesn't support both `--devifle` and `--context`, we will use separate issue to cover `--devfile` support.
