### ISSUE TITLE
Add proper doc for devfile and s2i config matrix

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2831]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Missing config file matrix doc for devfile and s2i component - https://github.com/openshift/odo/pull/2598#issuecomment-585680436
Also comment link https://github.com/openshift/odo/issues/2813#issuecomment-609901433 would be helpful as it explains the above link.

## What is the relevance of it?
Helpful to understand which config file (devfile or s2i) has to be picked up during component create, push

**Comment by girishramnani** [comment]
any updates on this @boczkowska

**Comment by cdrage** [comment]
Hey @amitkrout can you describe the issue a bit more? Confused what you mean by matrix doc. We already have the table on: https://odo.dev/docs/understanding-odo/ and I am updating the README here: #3877

**Comment by boczkowska** [comment]
I've added some general docs on the Experimental mode here, including the table: https://github.com/openshift/openshift-docs/pull/25098
Is it still relevant?

**Comment by boczkowska** [comment]
@amitkrout @kadel is the https://github.com/openshift/odo/pull/2598#issuecomment-585680436 still relevant with the release of 2.0?
