### ISSUE TITLE
Test ingress URL in devfile test suite

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2833]
/kind bug

Currently the URL test scenarios in https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_url_test.go don't test the created ingress URL. We should test that the URL is working just like our s2i tests.

**Comment by maysunfaisal** [comment]
Just as an FYI, to whoever picks this issue up, we would need to figure out the ingress domain/host for working on this issue i.e.; if the test is run on CI what is the ingress domain, if the test is run outside CI what is the ingress domain

odo non-experimental url create just required a port for route but odo experimental requires a port and a host(valid if you want to test endpoint) for ingress.
