### ISSUE TITLE
Code seems to do something different than what's commented

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2847]
/kind bug

Code comment at: https://github.com/openshift/odo/blob/00262d842955b1d5d9d1f6461b8e5ef41393b7e1/pkg/component/component.go#L891-L900
talks about extracting labels but it doesn't look like the block following it is actually extracting them.

**Comment by dharmit** [comment]
Also found repetition of code: https://github.com/openshift/odo/blob/585fd6dc5cd96f536960f0de6664cb66e09cefa5/pkg/component/component.go#L888-L918.

Still relevant and good first issue to get hands dirty with odo code base, IMO.

/remove-lifecycle stale

**Comment by niconosenzo** [comment]
@dharmit I would like to have some fun working on it :).

**Comment by mik-dass** [comment]
> @dharmit I would like to have some fun working on it :).

Done 👍
