### ISSUE TITLE
odo exec command

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2857]
/kind user-story

## User Story
As a developer I want to execute commands in the pod so that I can debug my application and do other stuff.

## Acceptance Criteria 
- [ ] It should have a `exec` command to execute a command inside the pod

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by mik-dass** [comment]
The exec function is already written here https://github.com/openshift/odo/blob/cf1d69743f6242f5fab1858ad3dadd42bd6ca7a3/pkg/exec/exec.go#L19
I think we can use this for the exec command too.

**Comment by mik-dass** [comment]
For multiple container components, I think we can execute the command in the container with which devrun is used. @kadel @girishramnani WDYT?

**Comment by kadel** [comment]
We don't need this for odo 2.0
