### ISSUE TITLE
unable to create URL on GKE

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2866]
When trying to create URL (`odo url create`) on GKE (Google Kubernetes Engine) in the default configuration. Ingress doesn't get created due to the following error:

`error while evaluating the ingress spec: service "default/backend" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

It looks like we might need to add support for specifying different Service types than just `ClusterIP`.

Or find and document some workaround for GKE.
Another option is to use nginx-controller for Ingress (https://cloud.google.com/community/tutorials/nginx-ingress-gke)
But that creates another problem. In order for Ingress Resource to use nginx-controller on GKE it needs to have annotation `kubernetes.io/ingress.class: nginx` odo doesn't allow to specify annotations :-/

/kind bug
/area devfile
/area kubernetes

**Comment by johnmcollier** [comment]
+1 How do we want to handle this? Add support for specifying type of service that's created by odo? And / or allow annotations to be specified during `odo create url`?

@kadel FWIW, I haven't had any issues on GKE with the nginx ingress controller and odo (I used https://hub.helm.sh/charts/nginx/nginx-ingress). That being said, I haven't tried any of the HTTPS support with ingresses and I suspect that would require nginx specific annotations on the ingress.
