### ISSUE TITLE
CICD support for IBM Z

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#2876]
/kind feature
## Which functionality do you think we should add?
In order to setup CI for 4.* cluster of s390x arch, The imagestreams for s390x arch need to be imported firstly. There is 'Setting up pipeline imagestream for the test' job in CI for 4.* cluster of x86 [arch.](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/2759/pull-ci-openshift-odo-master-v4.2-integration-e2e-benchmark/1364/build-log.txt) Are those imagestreams releated to odo e2e testcases or not? If so, Is there any way to get the imagestream list needed by e2e and integration tests?
## Why is this needed?
I found there is CI for 4.* cluster of x86 arch. The e2e and integration tests are based on x86 arch mostly. To enable ODO cli on OCP/Z, The CI is necessary.

**Comment by kadel** [comment]
> There is 'Setting up pipeline imagestream for the test' job in CI for 4.* cluster of x86 [arch.](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/2759/pull-ci-openshift-odo-master-v4.2-integration-e2e-benchmark/1364/build-log.txt) Are those imagestreams releated to odo e2e testcases or not?

I don't think that those are related to odo. 


> If so, Is there any way to get the imagestream list needed by e2e and integration tests?

The only ImageStreams that are required for odo e2e integration tests are s2i builders for [sample apps](https://github.com/openshift/odo/tree/master/tests/examples/source) used in e2e tests.

And those are only required for "old" s2i based components, which I hope we will be able to depreciate soon.

Everything around Devfiles is not going to require any ImageStreams.

**Comment by jichenjc** [comment]
> > There is 'Setting up pipeline imagestream for the test' job in CI for 4.* cluster of x86 [arch.](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/2759/pull-ci-openshift-odo-master-v4.2-integration-e2e-benchmark/1364/build-log.txt) Are those imagestreams releated to odo e2e testcases or not?
> 
> I don't think that those are related to odo.
> 
> > If so, Is there any way to get the imagestream list needed by e2e and integration tests?
> 
> The only ImageStreams that are required for odo e2e integration tests are s2i builders for [sample apps](https://github.com/openshift/odo/tree/master/tests/examples/source) used in e2e tests.
> 
> And those are only required for "old" s2i based components, which I hope we will be able to depreciate soon.
> 
> Everything around Devfiles is not going to require any ImageStreams.

thanks for the confirm, @zhengxiaomei123 will have further comments 
just to confirm, is devfile ready then s2i method (current way ) will be deprecated or both will sit there for some time? Thanks

**Comment by kadel** [comment]
> just to confirm, is devfile ready then s2i method (current way ) will be deprecated or both will sit there for some time? Thanks

When devfile is ready, we will switch odo to use devfiles by default. s2i method will be still there, but it will be marked for dedication. We want to give current users some time to transition existing projects to a new format (devfile).

**Comment by jichenjc** [comment]
ok, got it , thanks a lot for the info

**Comment by zhengxiaomei123** [comment]
> The only ImageStreams that are required for odo e2e integration tests are s2i builders for [sample apps](https://github.com/openshift/odo/tree/master/tests/examples/source) used in e2e tests.

@kadel Thanks for your reply. I think the question is that those s2i builders are not all available on s390x arch. Is there any guide or way to build those s2i builder images or only can be built by RedHat team? 
Besides, When devfile is ready, will the e2e and integration tests switch to ues devfiles by default? If so, I think there will be much changes on e2e integration tests codes.
