### ISSUE TITLE
watch command doesn't honor the project or component

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo#2883]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**
master
## How did you run odo exactly?

no dummy exist for both component or app , but still able to run this command
we should report error

[root@xyimgr77 ftq]# ./odo watch dummy
Waiting for something to change in /root/ftq
^C
[root@xyimgr77 ftq]# ./odo watch --app dummy
Waiting for something to change in /root/ftq

**Comment by jichenjc** [comment]
I can work on this if agree this is a bug

**Comment by girishramnani** [comment]
@amitkrout can you please verify if this is a bug, I am having second thoughts.
