### ISSUE TITLE
Invalid devfile component create fails for devfile feature on kubernetes cluster

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2888]
/kind bug
/area devfile

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?
```odo create fakeComponentName```

## Actual behavior

```
Running odo with args [odo create fake-component]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo] Validation
[odo]  •  Checking Devfile compatibility  ...
[odo]  ✗  Checking Devfile compatibility [13703ns]
[odo] 
[odo] Please run 'odo catalog list components' for a list of supported devfile component types
[odo]  ✗  the server could not find the requested resource (get imagestreams.image.openshift.io fake-component)
Deleting project: hywllfifwd
Running kubectl with args [kubectl delete namespaces hywllfifwd]
[kubectl] namespace "hywllfifwd" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/392710421
• Failure [3.229 seconds]
odo devfile create command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:13
  When executing odo create with an invalid devfile component
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:96
    should fail with please run 'odo catalog list components' [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:97
    Expected
        <string>:  ✗  the server could not find the requested resource (get imagestreams.image.openshift.io fake-component)
        
    to contain substring
        <string>: "fake-component" not found
```

## Expected behavior

It should reflect ```"fake-component" not found```

## Any logs, error output, etc?

Logs can be found in more detail : https://travis-ci.com/github/openshift/odo/jobs/319523643#L566

**Comment by prietyc123** [comment]
I am not sure why ```get imagestreams.image.openshift.io fake-component``` is getting invoked here, as out of 8 specs 7 got passed on kubernetes cluster. If you will see in the logs :  https://travis-ci.com/github/openshift/odo/jobs/319523643.
It's getting crashed on line no : https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_create_test.go#L120

Ping @kadel @girishramnani @johnmcollier @GeekArthur

**Comment by adisky** [comment]
@prietyc123 if component name is not found in supported devfiles, it searches for the given component in S2I based supported components, AFAIK we are not supporting S2I based components on kubernetes, so we should add a check in code if the cluster is kubernetes then odo should not search for S2I based components.

**Comment by prietyc123** [comment]
> @prietyc123 if component name is not found in supported devfiles, it searches for the given component in S2I based supported components, AFAIK we are not supporting S2I based components on kubernetes, so we should add a check in code if the cluster is kubernetes then odo should not search for S2I based components.

@adisky Thanks it make sense 👍. I will try to do that and update the outcome.

**Comment by prietyc123** [comment]
> supported

@adisky I am not confident to fix the backend code atm. Can you please have a look and get a quick fix if possible?

**Comment by prietyc123** [comment]
> > @prietyc123 if component name is not found in supported devfiles, it searches for the given component in S2I based supported components, AFAIK we are not supporting S2I based components on kubernetes, so we should add a check in code if the cluster is kubernetes then odo should not search for S2I based components.
> 
> @adisky Thanks it makes sense 👍. I will try to do that and update the outcome.

@adisky I am not confident to fix the backend code atm. Can you please have a look and get a quick fix if possible?

**Comment by adisky** [comment]
The error is generating from here
https://github.com/openshift/odo/blob/6740e5177ae11db734f7d3d303c4f689015e3b91/pkg/odo/cli/component/create.go#L601
I think we need some way to not execute S2I related codes on kubernetes cluster, We need to detect the cluster type first and we should not initialize the openshift client if it is k8s cluster, and add a check at each s2I related code.
https://github.com/openshift/odo/blob/6740e5177ae11db734f7d3d303c4f689015e3b91/pkg/odo/genericclioptions/context.go#L414
