### ISSUE TITLE
Flakey test observed in devfile list url after push

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2891]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported
**Output of `odo version`:**
master
## How did you run odo exactly?
https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_url_test.go#L48

**Comment by kadel** [comment]
@amitkrout what is the failure? Can you please provide failure logs or links to failed runs? 

This is not enough information.
/triage needs-information

**Comment by amitkrout** [comment]
> @amitkrout what is the failure? Can you please provide failure logs or links to failed runs?
> 
> This is not enough information.
> /triage needs-information

This issue is based on the report https://gist.github.com/kadel/2570427b9113ea0bb546f45723b7a643. Even i was not sure about reason, so i tried it locally couple of times and none of the time i could reproduce it. For now the best way to get the failure log is to wait for CI failure in the same spec.

**Comment by kadel** [comment]
> For now the best way to get the failure log is to wait for CI failure in the same spec.

No need to wait to get the failure log!!
You can easily search logs history for this failure
https://search.svc.ci.openshift.org/?search=should+list+url+after+push&maxAge=336h&context=1&type=build-log&name=pull-ci-openshift-odo-master-&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by elsony** [comment]
This issue has been fixed in this PR: #2762
