### ISSUE TITLE
Flakey test observed in devfile list url in machine readable json format

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2892]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported
**Output of `odo version`:**
master
## How did you run odo exactly?
https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_url_test.go#L85

**Comment by kadel** [comment]
@amitkrout what is the failure? Can you please provide failure logs or links to failed runs? 

This is not enough information.
/triage needs-information

**Comment by amitkrout** [comment]
> @amitkrout what is the failure? Can you please provide failure logs or links to failed runs?
> 
> This is not enough information.
> /triage needs-information

@kadel This issue is based on the report https://gist.github.com/kadel/2570427b9113ea0bb546f45723b7a643. Even i was not sure about reason, so i tried it locally 2 times and none of the time i could reproduce it. For now the best way to get the failure log is to wait for CI failure in the same spec.

**Comment by elsony** [comment]
This issue has been fixed in this PR: #2762

**Comment by kadel** [comment]
> This issue has been fixed in this PR: #2762

/close
