### ISSUE TITLE
migrate odo docs from openshift/docs repo to ./docs

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2898]
- Copy OpenShift documentation from https://github.com/openshift/openshift-docs/tree/master/cli_reference/openshift_developer_cli to https://github.com/openshift/odo/tree/master/docs

- clean it up so it can be used to generate documentation that we can place to odo.dev site (#2897)
- create a script that will sync documentation from our repo to  https://github.com/openshift/openshift-docs/tree/master/cli_reference/openshift_developer_cli. This script ideally open PR on `openshift/openshift-docs` repo with changes

**Comment by cdrage** [comment]
@kadel 

I have included instructions on how to "sync" between the openshift repository as well as our current documentation here: https://github.com/openshift/odo/tree/gh-pages

Do you think this is sufficient enough for our documentation?

**Comment by kadel** [comment]
> @kadel
> 
> I have included instructions on how to "sync" between the openshift repository as well as our current documentation here: https://github.com/openshift/odo/tree/gh-pages
> 
> Do you think this is sufficient enough for our documentation?

+1

Great!
@cdrage can you please share the information on how to update the website and docs with everyone  on odo-dev@googlegroups.com ?

**Comment by cdrage** [comment]
@kadel 

Done! As all tasks have been completed. I'm going to close this issue :)
