### ISSUE TITLE
odo project on Kubernetes

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2899]
/kind user-story

## User Story
As an odo user, I want to be able to use `odo project *` commands regardless of what type of the cluster I'm using (Kubernetes or OpenShift`

## Acceptance Criteria 
- [x] `odo project create` should create Namespace if odo is connected to Kubernetes cluster, and Project if connected to OpenShift
- [x] `odo project delete` should delete Namespace if odo is connected to Kubernetes cluster, and Project if connected to OpenShift
- [x] `odo project get`should get the currently active Namespace from `KUBECONFIG` 
- [x] `odo project list` should list all user's Namespaces if odo is connected to Kubernetes cluster, and all users's Projects if connected to OpenShift
- [x] `odo project set` should set the currently active Namespace from `KUBECONFIG` 

## Links 
- https://github.com/openshift/odo/issues/2846#issuecomment-611064771
- https://github.com/openshift/odo/issues/2769

## Notes
odo should always use the project as an abstraction on top of Kubernetes Namespace and OpenShift Project. From the odo user's point of view, it should not matter what cluster they are using, the commands should remain the same.

/kind user-story
/area project
/area kubernetes
/area openshift
/priority high

**Comment by girishramnani** [comment]
Some of the commands above should have wait flag which we would need to implement, assuming the same way - by watching for events.

**Comment by girishramnani** [comment]
I can confirm that deleting a project is async in nature but not sure if creation is too.

**Comment by girishramnani** [comment]
- as the primary resource here is `namespace` and `project`, I would use checking of their existance as the way to detect if we are dealing with kube or openshift.
- creating namespace is going to straight forward - maybe just one caviat that its creation could be async ( my research so far shows othervise )
- `odo project get` should also be straightforward, as I remember we even now use KUBECONFIG to get namespace if its empty on localconfig https://github.com/openshift/odo/blob/c281978f9c467d3baf3632520058ee5ff0762cef/pkg/odo/genericclioptions/context.go#L166
- project listing would use the api to get namespace, the question here would be to decide on having a `cluster type` in the output table? and does that information help the user?
- setting the project would work similar to getting the project. 
- In some places there are some functionality that are overlapping and for that I would have to refactor the occlient and kclient a bit.
- and also in case of kubernetes the local config info would not exist and hence that has to be bypassed.
- the above point would require us to refactor how we resolve the project/namespace in the context and definitely would require some tests to be written.

**Comment by dharmit** [comment]
@girishramnani I created the JSON output user story so that it doesn't slip from our mind. Obviously it will need more inputs from you. :smile:
