### ISSUE TITLE
Update failure 

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#2914]
/kind bug

I have tried to update my odo version using the recommended `curl` command on `odo version` command and it failed with the below messages.

**Output of `odo version`:**
```
﻿﻿❯ ❯ odo version
odo v1.0.0-beta5 (4d1d5071)

Server: https://api.rh-us-east-1.openshift.com:443
OpenShift: v3.11.154
Kubernetes: v1.11.0+d4cacc0
---
A newer version of odo (version: v1.1.2) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/openshift/odo/master/scripts/installer.sh | sh
to update manually, or visit https://github.com/openshift/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo preference set UpdateNotification false'

❯ curl https://raw.githubusercontent.com/openshift/odo/master/scripts/installer.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9213  100  9213    0     0  33501      0 --:--:-- --:--:-- --:--:-- 33501
# Detecting distribution...
# Detected platform: darwin-amd64
echo_stderr #
odo version "odo v1.0.0-beta5 (4d1d5071)" is already installed on your system. Running this installer script might cause issues with your current installation. If you want to install odo using this script, please remove the current installation of odo from you system.
Aborting now!
```

**Comment by mohammedzee1000** [comment]
The installer script needs an overall. I think we are already looking at breaking off into a sort of upstream/downstream so the install scripts are going to need an overhaul. cc @kadel 

For now, i think the goal should be the script should detect if os is windows/mac/os (if memory serves bash is available on all of these os's) and the automatically curl download appropriate binary.

Long term though, assuming we break off, we should install from rpm for rpm based os's and do a curl download for rest. For downstream os'es we should instead ask use to subscribe to appropriate channels

If script fails, it will give link to binary

wdyt @girishramnani

**Comment by girishramnani** [comment]
For release engineering, always go with long term solutions.

**Comment by girishramnani** [comment]
Please plan for long term, what ever the solution might be

**Comment by mohammedzee1000** [comment]
Long term will need decision on if we want to breakout upstream/downstream. Of course we will  still build internally, it the upload to github/internal delivery mechanisms and signing that will change. This is to avoid divergence as much as possible

**Comment by mohammedzee1000** [comment]
One option we also have is dropping the script altogether and let our documentation handle it

**Comment by kadel** [comment]
> One option we also have is dropping the script altogether and let our documentation handle it

I would be fine with that.

**Comment by mohammedzee1000** [comment]
@gorkem considering its a simple matter of downloading binary and placing it in your path, it does not make sense to keep this script anymore. You can refer https://github.com/openshift/odo/releases and https://odo.dev/docs/installing-odo/.

**Comment by gorkem** [comment]
That is fine as long as you are not printing a message that references a non-working script

**Comment by mohammedzee1000** [comment]
That is happening in older version of odo. The newer versions do not point to the script
