### ISSUE TITLE
Flakey test found in odo devfile push whiling using pushtarget as docker

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2923]
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
https://github.com/openshift/odo/blob/master/tests/integration/devfile/docker/cmd_docker_devfile_push_test.go#L45

**Comment by amitkrout** [comment]
This issue is based on the report https://gist.github.com/kadel/2570427b9113ea0bb546f45723b7a643. Even i was not sure about reason, so i tried it locally and unable to reproduce it. For now the best way to get the failure log is to wait for CI failure in the same spec.

**Comment by johnmcollier** [comment]
The docker tests don’t run on the OpenShift CI (where that report generates the list of flakes), have we seen any failures on Travis?

**Comment by kadel** [comment]
> The docker tests don’t run on the OpenShift CI (where that report generates the list of flakes), have we seen any failures on Travis?

Yep, this doesn't make sense /close

I'll check my script it might show up in the list due to some infra errors.
