### ISSUE TITLE
devfile odo push failed to start component on kubernetes cluster

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2928]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Steps to reproduce:

1. Create single node kubernetes cluster using **minikube [0.25.2](https://github.com/kubernetes/minikube/releases/tag/v0.25.2)**
2. Enable experimental mode
3. git clone https://github.com/che-samples/web-nodejs-sample.git && cd che-samples
4. odo create nodejs --project zxobygmpyf
5. odo push --devfile devfile.yaml --namespace zxobygmpyf

## Actual behavior

Its throwing error while ```odo push``` in starting the component on kuberenetes cluster.

**NOTE:** minikube version 0.25.2 is being used for testing

## Expected behavior

The component should get pushed in the deployment directory.

## Any logs, error output, etc?

```
Running git with args [git clone https://github.com/che-samples/web-nodejs-sample.git /tmp/394302036/projectDir]
[git] Cloning into '/tmp/394302036/projectDir'...
Setting current dir to: /tmp/394302036/projectDir
Running odo with args [odo create nodejs --project zxobygmpyf umffvx]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo] Validation
[odo]  •  Checking devfile compatibility  ...
 ✓  Checking devfile compatibility [33281ns]
[odo]  •  Validating devfile component  ...
 ✓  Validating devfile component [64477ns]
[odo] 
[odo] Please use `odo push` command to create the component with source deployed
Running odo with args [odo push --devfile devfile.yaml --namespace zxobygmpyf]
[odo]  •  Push devfile component umffvx  ...
[odo]  ✗  Failed to start component with name umffvx.
[odo] Error: Failed to create the component: unable to create or update component: unable to create Deployment umffvx: the server could not find the requested resource
Deleting project: zxobygmpyf
Running kubectl with args [kubectl delete namespaces zxobygmpyf]
[kubectl] namespace "zxobygmpyf" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/394302036
```
Detailed logs : https://travis-ci.com/github/openshift/odo/jobs/321025144#L617

**Comment by prietyc123** [comment]
ping @girishramnani @GeekArthur

**Comment by girishramnani** [comment]
assigning this to @elsony, please feel free to assign this to your team.

**Comment by kadel** [comment]
@prietyc123 I don't understand this at all :-(
Is this bug in odo or failing test?

The commands that you have in `How did you run odo exactly?` don't make much sense :-( For example `odo create` is using different `namespace` than `odo push`

**Comment by adisky** [comment]
@prietyc123 I recently tried nodejs devfile on kubernetes cluster, it is working well. Not Sure what is breaking here.

**Comment by prietyc123** [comment]
> @prietyc123 I don't understand this at all :-(
> Is this bug in odo or failing test?

I think this is bug in odo with respect to kubernetes cluster.

**Comment by GeekArthur** [comment]
Given @adisky can't reproduce this issue, @prietyc123 can you manually try the scenario on your k8s cluster with V styling logging enabled then check what exactly the errors are from the logs?

Also FWIW, we will remove `--namespace` flag and always use `--project` for both s2i component and devfile component once this PR https://github.com/openshift/odo/pull/2909 merges in.

**Comment by prietyc123** [comment]
> Given @adisky can't reproduce this issue, @prietyc123 can you manually try the scenario on your k8s cluster with V styling logging enabled then check what exactly the errors are from the logs?
> 
> Also FWIW, we will remove `--namespace` flag and always use `--project` for both s2i component and devfile component once this PR #2909 merges in.

Yes, I tried manually and it is working fine. I think it is the cluster version issue running on travis CI. I think I know the exact solution and I can send pr on this.

**Comment by amitkrout** [comment]
> > Given @adisky can't reproduce this issue, @prietyc123 can you manually try the scenario on your k8s cluster with V styling logging enabled then check what exactly the errors are from the logs?
> > Also FWIW, we will remove `--namespace` flag and always use `--project` for both s2i component and devfile component once this PR #2909 merges in.
> 
> Yes, I tried manually and it is working fine. I think it is the kubernetes cluster version issue which is running on travis CI. I think I know the exact solution and I can send pr on this.

@adisky @kadel From the travis log i found that the the issue is being reported on minikube version [0.25.2](https://github.com/kubernetes/minikube/releases/tag/v0.25.2) which was released 2 years back. Actually we are using the same version on travis CI.

I am sure you guys are using latest minikube to verify it manually. If you use the latest minikube version then you won't be able to reproduce it. 

Currently travis CI with trusty distro has ubuntu version 14.04. To get the latest latest minikube version, distro should have systemd which was added in ubuntu 16.04, therefore we need to bump the ubuntu version to 16.04+ using xenial distro of travis CI.
