### ISSUE TITLE
Manually try multiple openshift and devfile scenarios those are missing in the test script

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#2930]
/kind user-story

## User Story

Try different and complex scenarios of odo locally and gather wherever odo fails. 
E.g.
- add a port, add storage, remove existing storage and then push. ( both using openshift and devfile )
- Create operator service and catalog service together and confirm working and UX. 

## Acceptance Criteria 
- [ ] Each tested scenario needs to be documented, even the passing one, and all the results need to be recorded. 
- [ ] It should cover complex scenario for both regular and experimental feature
- [ ] Scenario test should be passed, otherwise, issues will re-reported 

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by prietyc123** [comment]
This is a basic draft of the issue. I will keep formatting and updating it till the planning part two

**Comment by prietyc123** [comment]
I have created a basic spreadsheet to capture the record. Anyway I will try to figure it out and test it manually.

**Comment by prietyc123** [comment]
Test Scenario | Test Type (Regular/Experimental) | Status | Comment
-------------  | --------------------------------- | ------  | ----------
Adding odo storage in e2e_image_test | Regular | Pass | Checked for the list of storage and it exist

**Comment by girishramnani** [comment]
consider setting config values using `odo config set` in between `odo push`s to see how odo handles does

**Comment by dharmit** [comment]
Focus areas:
- devfile v2
- url related commands
- registry

We can try to break above pieces in odo in any possible and open issues wr.t. those.

All tests for devfile v1 can be run on devfile v2 except the `init` command. `devInit` command has been deprecated from devfile v2.

**Comment by girishramnani** [comment]
consider scenerios - 

- odo create --downloadSource then break the progress from the middle and then do the same command again.
- create two components - 1 frontend and 1 backend then do `odo watch` on both places and compare the UX ( dont worry about linking just create two components )
- add a new devfile v2 registry and do note down if you find lack of documentation. also check the `odo catalog list components` output after adding the new registry. note down the performance as well.

**Comment by amitkrout** [comment]
Thanks for the suggestion. we will focus those areas for sure and ofcourse few more that we find from UX.

**Comment by anandrkskd** [comment]
|Test Scenario    |  Test Type (Regular/Experimental) | Status   | Comment  |  Issue |
|---|---|---|---|---|
|  Changing resource in config values using editor in between odo push |  Experimental | Pass  |  odo push does not build the changes in the particular push but subsequent odo push successfully make the changes. | N/A  |

**Comment by girishramnani** [comment]
> Thanks for the suggestion. we will focus those areas for sure and ofcourse few more that we find from UX, we will make sure that none of the UX command reference left behind.

thank you

**Comment by girishramnani** [comment]
@anandrkskd please add a new column called `Steps to reproduce` to a gist which contains a script that reproduces the scenerio. 
And I want that for each scenerio tried so far @prietyc123

**Comment by dharmit** [comment]
There's a bunch of things we discussed on this one but I'm not sure if we had any outcome. Also wondering if anyone's going to work on this ever. :thinking: 

Maybe we could come back to this when we are done with:
* a few iterations of refactoring the code wherein we add more unit tests and remove some integration tests
* work on improving the overall UX 

Still, IMO, nothing's blocking us from taking things for a manual spin.
