### ISSUE TITLE
QECI best practices

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2932]
/kind user-story

## User Story
// Copy paste

The QE dept has a number of systems and tooling that were developed in a silo, meaning that they were developed by/for a specific QE team or set of teams without considering the needs of the other teams that have similar requirements. This caused a large duplication of effort as multiple teams are developing very similar feature sets without knowing it. As part of this effort we are trying to centralize development effort and converge on a single tool per requirement set.

A number of teams did not have their CI workflow documented. When a workflow isn’t documented, it isn’t actually a workflow, rather it is a number of steps that can’t be analyzed. As [part of this effort, we are working with all teams to ensure that their workflows are documented

One of the initiatives of the QE dept is to enable a roaming tech team to join projects that need extra resources for a specific project or period of time. This process is difficult enough when the resource needs to learn the product and testing environment. Any aspect that can be standardized will ease the onboarding process.

We would like to encourage community, and teams helping one another. This becomes much easier the more similar teams workflows, tooling and methodologies are. It becomes easier to share examples and answer questions asked on a mailing list.

Teams don’t always know about all the capabilities available to them. There are a number of best practices that help out teams as soon as they learn of them. In this initiative, when a team wants to start using something new, we will see how other teams are doing the same thing, and if nobody is doing it yet, we can open a discussion and see if this will help anyone else as well.

## Acceptance Criteria 
- [ ] Implement authentication & credentials
- [ ] Implement data retention
- [ ] Implement job types
- [ ] implement Provisioning Best Practice
- [ ] Implement SCM
- [ ] Implement job generation best practice
- [ ] Document Manual Interventions
- [ ] Implement job triggers
- [ ] Develop plan for automating manual tasks

## Links 
- Feature Request: 
- Related issue: https://issues.redhat.com/projects/ODO/issues

/kind user-story

**Comment by kadel** [comment]
/triage needs-information

Why we need this?
How it will help odo?

**Comment by dharmit** [comment]
QECI? Did you mean QWERTY best practices?

**Comment by kadel** [comment]
So the output of this will be documented describing odo QE workflow?

**Comment by amitkrout** [comment]
> So the output of this will be documented describing odo QE workflow?

Follow the internal mail thread ```QECI best practices onboarding``` for more details

**Comment by girishramnani** [comment]
these practices dont apply to odo because 
- we dont have a large enough team
- we dont run on production clusters and similar such scenarios dont apply to us.
