### ISSUE TITLE
URL list and describe for devfile local support

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#2934]
/area devfile

`odo url list` and `odo url describe` for local docker containers should works the same as kube cases.

```
NAME            URL                                        PORT       STATE
```
The port should display the internal port. 
The name is defined as `local-<componentName>-<portNumber>`
URL should be `https://127.0.0.1:<exposedPort>`. 
State should indicated if the url config has been pushed or not(is only in local env.yaml file, need to push to get reflected)

**Comment by elsony** [comment]
This items should also cover the json output format for the command
