### ISSUE TITLE
Specify the source mapping path for component containers

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2935]
/kind user-story

## User Story
As a stack creator, I want to customize the source mapping path on the containers defined in the devfile. 

## Acceptance Criteria 
- [ ] It should support consuming source mapping path defined in the corresponding devfile 2.0 item: https://github.com/che-incubator/devworkspace-api/issues/17

## Links 
- Related issue: https://github.com/che-incubator/devworkspace-api/issues/17

/kind user-story
/area devfile

**Comment by kadel** [comment]
/status blocked
#2918 we need devfile v2 parser first
