### ISSUE TITLE
Support group in devfile commands (application lifecycle)

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2938]
/kind user-story

## User Story
As a stack creator, I want to define the group that a given command in a devfile belongs to so that odo know what default command to when it build, run, test and debug.

## Acceptance Criteria 
- [ ] It should follow the corresponding settings specified in the devfile 2.0 specification: https://github.com/che-incubator/devworkspace-api/issues/27
- [ ] It should support setting default for each group (see spec above)
- [ ] It should replace the existing `devBuild` and `devRun` commands on the push logic
- [ ] It should modify the existing `odo catalog list components` logic acceptance criteria to use the group info instead of the odo specific `devBuild` and `devRun` commands

## Links 
- Related issue: https://github.com/che-incubator/devworkspace-api/issues/27

/kind user-story
/area devfile

**Comment by kadel** [comment]
this is blocked on  https://github.com/openshift/odo/issues/2918

/stats blocked

**Comment by kadel** [comment]
> * [ ]  It should replace the existing `devBuild` and `devRun` commands on the push logic

@elsony What about devfile v1 support. Are we not going to support it anymore?

**Comment by maysunfaisal** [comment]
Some observations for this work to be completed:
- If there are multiple group commands without a default, it should err out
- there needs to be one run group command defined, otherwise it should err out
- build group command optional like devfile v1

**Comment by elsony** [comment]
> Some observations for this work to be completed:
> 
>     * If there are multiple group commands without a default, it should err out
> 
>     * there needs to be one run group command defined, otherwise it should err out
> 
>     * build group command optional like devfile v1

I would suggest to modify slightly to clarify:
1. If there are multiple group commands without a default, it should err out. This check is only done for the groups that odo consumes and the check is done when doing the corresponding execution, e.g. check on `debug` group only if running `odo push` with `--debug`
2. there needs to be at least one run group command defined, otherwise it should err out during `odo push`. Rule for multiple run command in point #1 still applies.
3. build group command optional like devfile v1

**Comment by maysunfaisal** [comment]
@elsony what do you think about this issue here regarding command groups https://github.com/openshift/odo/pull/3216#discussion_r433471771

**Comment by kadel** [comment]
> * [ ]  It should modify the existing `odo catalog list components` logic acceptance criteria to use the group info instead of the odo specific `devBuild` and `devRun` commands

I think that we should list all devfiles in the registry regardless of what command groups are there. 
Users can still use `--run-command` and `--build-command` to select the right commands if they are not specified in the devfile.

**Comment by maysunfaisal** [comment]
@kadel that is true. But `odo push` would fail if there are no `build` and `run` groups at this point. Is it a good UX to enable this by default registry? 🤔

**Comment by adisky** [comment]
> @elsony what do you think about this issue here regarding command groups [#3216 (comment)](https://github.com/openshift/odo/pull/3216#discussion_r433471771)

I had already removed validation for `groups` after the discussion

**Comment by adisky** [comment]
> > Some observations for this work to be completed:
> > ```
> > * If there are multiple group commands without a default, it should err out
> > 
> > * there needs to be one run group command defined, otherwise it should err out
> > 
> > * build group command optional like devfile v1
> > ```
> 
> I would suggest to modify slightly to clarify:
> 
> 1. If there are multiple group commands without a default, it should err out. This check is only done for the groups that odo consumes and the check is done when doing the corresponding execution, e.g. check on `debug` group only if running `odo push` with `--debug`
> 2. there needs to be at least one run group command defined, otherwise it should err out during `odo push`. Rule for multiple run command in point #1 still applies.
> 3. build group command optional like devfile v1

We are already validating for point 2 and point 3.

**Comment by kadel** [comment]
> @kadel that is true. But `odo push` would fail if there are no `build` and `run` groups at this point. Is it a good UX to enable this by default registry? 🤔

The default registry is under our control, so we can make sure that all devfiles in the default registry have proper groups.
