### ISSUE TITLE
Support container component type in devfile 2.0

### ISSUE THREAD

**Issue by elsony** [openshift/odo#2939]
/kind user-story

## User Story
As a stack creator, I want to use the new container component type in a devfile 2.0 to define the image used by a given component so that my command can execute is the given container.

## Acceptance Criteria 
- [ ] It should follow the specification as defined in https://github.com/che-incubator/devworkspace-api/issues/8 to define the container component in devfile 2.0.

## Links 
- Related issue: https://github.com/che-incubator/devworkspace-api/issues/8

/kind user-story
/area devfile

**Comment by GeekArthur** [comment]
`dockerimage` component type depreciates, will check whether devfile 2.0 parser https://github.com/openshift/odo/pull/3188 handles `container` component type properly.

**Comment by GeekArthur** [comment]
From quick glance, PR #3188 already supports `container` component type in both product https://github.com/openshift/odo/pull/3188/files#diff-8e874d12aadb58a96431fbf88d9fd3a2R122 and tests https://github.com/openshift/odo/pull/3188/files#diff-d16cd992949b0e25e1b445933b9f7ac1R9, I think this issue is done but let's wait for the devfile v2 is fully support so that we can do more testing then close the issue.

**Comment by GeekArthur** [comment]
We need to do more testing, we may need to do some changes for `odo create` and `odo catalog` to fully support `container` component type.

**Comment by kadel** [comment]
> From quick glance, PR #3188 already supports `container` component type in both product https://github.com/openshift/odo/pull/3188/files#diff-8e874d12aadb58a96431fbf88d9fd3a2R122 and tests https://github.com/openshift/odo/pull/3188/files#diff-d16cd992949b0e25e1b445933b9f7ac1R9, I think this issue is done but let's wait for the devfile v2 is fully support so that we can do more testing then close the issue.

I'm assigning this to @adisky, to track this correctly,  as she is working on initial implementations in parser-v2 branch.
if there is something left after initial implementation we can create new issues, or resign this.
/assign @adisky

**Comment by adisky** [comment]
@elsony @kadel `container` component type is implemented with devfile V2 PR,
I can see some fields are not supported by odo, one is `sourceMapping` and other is `endpoints configuration`, support for them has to be done in this issue or we need a new issue?
https://github.com/openshift/odo/blob/master/pkg/devfile/parser/data/2.0.0/types.go#L232
```
type Container struct {
	Endpoints []*Endpoint `json:"endpoints,omitempty"`
	Env          []*Env `json:"env,omitempty"`
	Image        string `json:"image"`
	MemoryLimit  string `json:"memoryLimit,omitempty"`
	MountSources bool   `json:"mountSources,omitempty"`
	Name         string `json:"name"`
	SourceMapping string `json:"sourceMapping,omitempty"`
	VolumeMounts []*VolumeMount `json:"volumeMounts,omitempty"`
}

// Endpoint
type Endpoint struct {
	Attributes    map[string]string `json:"attributes,omitempty"`
	Configuration *Configuration    `json:"configuration"`
	Name          string            `json:"name"`
	TargetPort    int32             `json:"targetPort"`
}


// Configuration
type Configuration struct {
	CookiesAuthEnabled bool   `json:"cookiesAuthEnabled,omitempty"`
	Discoverable       bool   `json:"discoverable,omitempty"`
	Path               string `json:"path,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Public   bool   `json:"public,omitempty"`
	Scheme string `json:"scheme,omitempty"`
	Secure bool   `json:"secure,omitempty"`
	Type   string `json:"type,omitempty"`
}
```

**Comment by girishramnani** [comment]
we need to implement source mapping, endpoints for this.

**Comment by girishramnani** [comment]
as per discussion source mapping is advanced feature and not needed

**Comment by GeekArthur** [comment]
`container` component type support for devfile 2.0 for `odo create` and `odo catalog` should be handled by https://github.com/openshift/odo/issues/3249 and https://github.com/openshift/odo/issues/2938, @maysunfaisal will implement those features. So my concern is resolved and my part is done for this issue. Red hat folks can feel free to close this issue if nothing else left for this issue.

**Comment by dharmit** [comment]
@adisky to research this if we need more info on this orif it's good to be `triage/ready`.

**Comment by adisky** [comment]
not yet researched it, only implementation of endpoint configuration is remaining as part of this issue? 
Do we need to do this in this sprint?

**Comment by adisky** [comment]
As per the latest schema from here https://github.com/devfile/kubernetes-api/blob/master/pkg/apis/workspaces/v1alpha1/containerComponent.go

only `endpoint` and `dedicatedPod` not implemented for odo.

issue for endpoint implementation: https://github.com/openshift/odo/issues/3515

**Comment by girishramnani** [comment]
most of the work on this is done and whatever is left is not relavent for v2.
