### ISSUE TITLE
Supported container images should be based on UBI

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/odo#2952]
/kind feature

## Which functionality do you think we should add?

The supported default images for ODO should be UBI-based, and not CentOS or RHEL/RHSCL.

## Why is this needed?

The images based on RHEL/RHSCL are protected by Red Hat's term of use and cannot be used without subscriptions. Images based on UBI would simplify the QA and allow reuse of ODO with broader community.

**Comment by davivcgarcia** [comment]
Do we have any feedback on this?

**Comment by kadel** [comment]
> The supported default images for ODO should be UBI-based, and not CentOS or RHEL/RHSCL.

We don't control or maintain builder images that are used with odo. The user will see whatever images they have on the cluster.

There is a list of images that odo shows as supported, because we have tests for those images, to ensure that they work.

**Comment by davivcgarcia** [comment]
> > The supported default images for ODO should be UBI-based, and not CentOS or RHEL/RHSCL.
> 
> We don't control or maintain builder images that are used with odo. The user will see whatever images they have on the cluster.
> 
> There is a list of images that odo shows as supported, because we have tests for those images, to ensure that they work.

Got it! Thanks.
