### ISSUE TITLE
Travis failures in "watch, storage, app, project, push, devfile catalog, devfile create, devfile push, devfile delete command integration" tests

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2956]
I'm seeing Travis failures in **watch, storage, app, project, push, devfile catalog, devfile create, devfile push, devfile delete command integration tests**:

```
[odo] Global preference was successfully updated
Running odo with args [odo create openLiberty oxysmosxqkoyaglcwkfkqolnnpyhmkppzjeuceeyqxhrbbhekhpzrytafmhgawcq]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo]  ✗  Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/springBoot/devfile.yaml: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Deleting project: whzaqeynse
Running odo with args [odo project delete whzaqeynse -f]
[odo]  •  Deleting project whzaqeynse  ...
 ✓  Deleting project whzaqeynse [6s]
[odo]  ✓  Deleted project : whzaqeynse
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/553883428
• Failure [19.069 seconds]
odo devfile create command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:13
  When executing odo create with devfile component name that contains more than 63 characters
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:101
    should failed with devfile component name is not valid and prompt container name contains at most 63 characters [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:102
    Expected
        <string>:  ✗  Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/springBoot/devfile.yaml: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
        
    to contain substring
        <string>: Contain at most 63 characters
```
/kind flake
_Originally posted by @dharmit in https://github.com/openshift/odo/pull/2901#issuecomment-617681139_

**Comment by mik-dass** [comment]
I have seen this error locally too.

**Comment by dharmit** [comment]
@mik-dass I'm wondering if this is a flake or an error in tests.

**Comment by amitkrout** [comment]
@mik-dass Its a git request failure, right - ```✗  Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/springBoot/devfile.yaml: net/http: request canceled (Client.Timeout exceeded while awaiting headers)```

When you started seeing this ? i mean after the test node increased to 4 ?

**Comment by johnmcollier** [comment]
Github had a lot of issues yesterday, where this error was common, has this been seen since then?

**Comment by dharmit** [comment]
@johnmcollier I saw bunch of these errors since this morning (India time) on #2901 & #2944

**Comment by mik-dass** [comment]
> @mik-dass I'm wondering if this is a flake or an error in tests.

It is a flake according to me

> @mik-dass Its a git request failure, right - ✗ Get https://raw.githubusercontent.com/elsony/devfile-registry/master/devfiles/springBoot/devfile.yaml: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
When you started seeing this ? i mean after the test node increased to 4 ?

Yes seems to be a network issue. I have seen this failure locally even when the test nodes are set to the default 2 nodes.

**Comment by amitkrout** [comment]
Closing this as it was a network glitch. Thanks
