### ISSUE TITLE
Should use context to get appropriate envinfo instead of using os.Getwd()

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#2959]
/kind bug

Since context is currently not supported in experimental mode, we use `os.Getwd()` to get the env.yaml
https://github.com/openshift/odo/blob/5a26a56426b5d4e214c0817c2820350d9b862e0a/pkg/odo/cli/component/devfile.go#L116-L117
https://github.com/openshift/odo/blob/5a26a56426b5d4e214c0817c2820350d9b862e0a/pkg/odo/cli/component/devfile.go#L130-L131
https://github.com/openshift/odo/blob/10826cc3f43c74ebadd917c3c53e9b40d6853aa6/pkg/devfile/adapters/docker/component/utils.go#L292

However, after context is supported, the project might be under a different directory; we need to switch to use context instead of using the current directory.

This issue is now blocked by experimental mode context support.

**Comment by girishramnani** [comment]
this PR resolves the above issue https://github.com/openshift/odo/pull/3134

**Comment by mohammedzee1000** [comment]
It looks to me like this problem was fixed already in all the places.
`os.getcwd()` is now only used when context="", but that should probably be handled while reading context, value. Will sent pr for that shortly

**Comment by girishramnani** [comment]
`getComponentName` we need to remove this function

**Comment by mohammedzee1000** [comment]
I figured this out while working on the now flag issue. Created local branch and have started looking at it
