### ISSUE TITLE
Travis failure for "make goget-tools" 

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2963]
Spun off a new issue based on https://github.com/openshift/odo/pull/2944#issuecomment-617746856

Saw this couple of times on Travis. 
```
$ make goget-tools
go get -u github.com/Masterminds/glide
go get -u github.com/frapposelli/wwhrd
go get -u github.com/onsi/ginkgo/ginkgo
go get -u github.com/securego/gosec/cmd/gosec
# It is not recomended to go get golangci-lint https://github.com/golangci/golangci-lint#go
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /home/travis/gopath/bin v1.23.6
golangci/golangci-lint info checking GitHub for tag 'v1.23.6'
golangci/golangci-lint info found version: 1.23.6 for v1.23.6/linux/amd64
make: *** [goget-tools] Error 7
The command "make goget-tools" failed and exited with 2 during .
```

/kind flake

_Originally posted by @dharmit in https://github.com/openshift/odo/issues/2954#issuecomment-617747370_

**Comment by prietyc123** [comment]
One more hit in https://travis-ci.com/github/openshift/odo/jobs/322505153#L235

**Comment by johnmcollier** [comment]
Are we maybe getting rate limited by Github? Error 7 from Curl means permission denied

**Comment by girishramnani** [comment]
I haven't observed this error recently hence closing.
Also we have caching in place for odo so less interactions happens then before https://github.com/openshift/odo/pull/3681.
