### ISSUE TITLE
Optimize odo create 

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2967]
/kind bug

The catalog list call in https://github.com/openshift/odo/blob/a45fa0e18b769df75e877e199976cb93f4c4719d/pkg/odo/cli/component/create.go#L319 takes a very long time. We should optimize this call using concurrency. Also we don't need those additional calls in the list call.

**Comment by amitkrout** [comment]
@mik-dass Thanks for the issue. 

I have observed it after some devfile pr was merged. This fix will decrease the test time a lot in CI too.
