### ISSUE TITLE
odo component commands for docker PushTarget

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2968]
Each component command needs to work properly with docker pushTarget

- [ ]  create      
- [ ]  delete     https://github.com/openshift/odo/issues/2581
- [ ]  describe   
- [ ]  link       
- [ ]  list        
- [ ]  log         
- [ ]  push  https://github.com/openshift/odo/issues/2576
- [ ]  unlink     
- [ ] update      
- [ ]  watch       

/kind epic
/area local

**Comment by girishramnani** [comment]
we are not going to add new features to docker/local workflow and hence closing this issue
