### ISSUE TITLE
odo debug   for docker pushTarget

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2972]
all `odo debug *` needs to work properly with docker pushTarget

- [ ] info
- [ ] port-forward

/area local
/kind epic

**Comment by mik-dass** [comment]
@kadel @girishramnani I did managed to attach the debugger inside the docker container by exposing the debug port and executing the required commands e.g for nodejs `nodemon --inspect=0.00.0.:5858`. I had to include `0.0.0.0` to allow external traffic to it otherwise it won't work.

**Comment by girishramnani** [comment]
we need to decide on docker support

**Comment by kadel** [comment]
/close
not relevant anymore
