### ISSUE TITLE
odo create interactive mode asks for namespace when the push target is set to docker

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#2978]
/kind bug
/area devfile

## What versions of software are you using?

**Operating System:**
macos
**Output of `odo version`:**
master branch
## How did you run odo exactly?
enable docker mode by setting the pushtarget
run `odo create`

## Actual behavior
```
$ odo preference set pushtarget docker -f
Global preference was successfully updated
$ odo create
Experimental mode is enabled, use at your own risk
? Which devfile component type do you wish to create openLiberty
? What do you wish to name the new devfile component openLiberty
? What namespace do you want the devfile component to be created in 
```

## Expected behavior
Should not ask for namespace since namespace is only applicable for kube

**Comment by girishramnani** [comment]
@johnmcollier are you still working on this?
