### ISSUE TITLE
Reduce the number of calls to pushtarget.IsPushTargetDocker()

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2979]
/kind cleanup
/area devfile
/area local

A lot of the code that is going in for the Docker pushtarget support in odo is making a number of calls to the `pushtarget.IsPushTargetDocker()` function. Each call of that function involves needing to read the `preference.yaml` from disk and retrieving the pushtarget value from it

We should try and reduce the number of unnecessary calls to that function and reduce how many times we need to access the filesystem. Rather than calling that function each time we need to check the pushtarget, maybe it makes sense to call the function once (maybe when we initialize the context for a command), and store the value in the `genericclioptions`.

A similar approach was done for storing and accessing the Kube namespace when deploying components on Kube

**Comment by GeekArthur** [comment]
Regarding this optimization, one thing I can think of is we need to ensure getting the updated pushTarget value via fs call as I believe preference.yaml is the only place that stores user’s updated pushTarget value, but we can reduce the number of fs calls for the successive functions/operations within the command
