### ISSUE TITLE
odo doesn't list unpushed URLs in experimental mode

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2983]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
```
$ odo create nodejs
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [118686ns]
 ✓  Validating devfile component [293987ns]

Please use `odo push` command to create the component with source deployed

$ odo url create
 ✗  host must be provided in order to create ingress

$ odo url create --host apps-crc.testing                          
 ✓  URL created for component: nodejs, cluster host: apps-crc.testing

To create the URL on the cluster, please use `odo push`

$ odo url list
 ✗  no URLs found for component nodejs
```

## Actual behavior
`odo url list` can't list URL if it's not pushed. In this case, even the component itself wasn't pushed to the cluster.

## Expected behavior
`odo url list` should be able to list the URLs not pushed to the cluster.

**Comment by girishramnani** [comment]
this is expected as we haven't implement this. so I think this is more of a feature

**Comment by girishramnani** [comment]
We need to wait on all devfile JSON output until we finalise on https://github.com/openshift/odo/issues/3137

**Comment by dharmit** [comment]
On minishift, I'm facing an issue wherein pushed url is neither listed in `odo url list` nor the application is accessible on it. I'm trying for https://github.com/sclorg/nodejs-ex project. In the devfile, I commented both the occurrences of `workdir` as @adisky recommended and did `odo push`.

On the minishift web console, I see the URL/Route for the component. But application is not accessible on that URL.

**Comment by girishramnani** [comment]
but shouldn't this be scoped as a different bug? @dharmit

**Comment by girishramnani** [comment]
might possibly be implemented by this PR https://github.com/openshift/odo/pull/3160 as there seems to be an overlap.

**Comment by girishramnani** [comment]
@mohammedzee1000 please confirm before moving forward

**Comment by dharmit** [comment]
> but shouldn't this be scoped as a different bug? @dharmit

Yes. But I'm not able to reproduce this right now.
