### ISSUE TITLE
odo allows creating mutliple URLs with same name in experimental mode

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2984]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
```
$ odo create nodejs
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [114792ns]
 ✓  Validating devfile component [201390ns]

Please use `odo push` command to create the component with source deployed

$ odo url create --host apps-crc.testing nodejs-300
 ✓  URL created for component: nodejs, cluster host: apps-crc.testing

To create the URL on the cluster, please use `odo push`

$ odo url create --host apps-crc.testing           
 ✓  URL created for component: nodejs, cluster host: apps-crc.testing

To create the URL on the cluster, please use `odo push`

$ cat .odo/env/env.yaml
ComponentSettings:
  Name: nodejs
  Namespace: myproject
  Url:
  - Name: nodejs-300
    Port: 3000
    host: apps-crc.testing
  - Name: nodejs-3000
    Port: 3000
    host: apps-crc.testing
```

## Actual behavior
`odo url create` allows creation of multiple URLs with same name

## Expected behavior
It shouldn't allow creation of multiple URLs with same name. Or at least it doesn't when I execute any of the above two `odo url create` commands again.

## Any logs, error output, etc?
* The component was not pushed to the cluster when I faced the bug. 
* Backend cluster was OpenShift

**Comment by mik-dass** [comment]
I think there is a similar issue https://github.com/openshift/odo/issues/2980. Can you please check?

**Comment by dharmit** [comment]
Yep. Closing since this is dupe as mentioned above.
