### ISSUE TITLE
In a operator installed cluster odo catalog list services stuck while fetching services details 

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2994]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported
**Output of `odo version`:**
master
## How did you run odo exactly?
I tried 3 times, in none of try i could see it. This is observed in CI
```
------------------------------
Running odo with args [odo project set ci-operator-hub-project]
[odo] Switched to project : ci-operator-hub-project



Running odo with args [odo catalog list services] <------ here it stuck



• Failure [1.873 seconds]
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:17
  When using dry-run option to create operator backed service
  /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:58
    should only output the definition of the CR that will be used to start service [It]
    /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:59
    Timed out after 1.009s.
      
    Running odo with args [odo catalog list services]
    Expected process to exit.  It did not.
    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34
------------------------------
```

## Actual behavior
```odo catalog list services``` stuck

## Expected behavior
Either it should throw error or should fetch the details.

## Any logs, error output, etc?

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2986/pull-ci-openshift-odo-master-v4.2-integration-e2e-benchmark/2282#1:build-log.txt%3A592

**Comment by dharmit** [comment]
```
Timed out after 1.009s.
```
Message indicates that the timeout is just about 1 second. I think for a cluster that's not setup on a local network, more timeout would be helpful.

@amitkrout when you tried to reproduce this, where was the cluster located? Was it a CRC node or a remote cluster?

**Comment by amitkrout** [comment]
> Timed out after 1.009s.
>Message indicates that the timeout is just about 1 second. I think for a cluster that's not setup on a local network, more timeout would be helpful.

I ma not sure which timeout is it ? i am sure it is not coming from the test script. Can we overwrite this timeout like we did for pushtimeout.

> @amitkrout when you tried to reproduce this, where was the cluster located? Was it a CRC node or a remote cluster?

Its a flake. i never tried it out locally. However it is found once or may be twice in OpenShift CI that runs the cluster on AWS.

**Comment by dharmit** [comment]
> I ma not sure which timeout is it ? i am sure it is not coming from the test script. Can we overwrite this timeout like we did for pushtimeout.

No, it's not set from our side. So we can't configure it. 

> Its a flake. i never tried it out locally. However it is found once or may be twice in OpenShift CI that runs the cluster on AWS.

I don't see this locally either. How do you suggest to fix this?

**Comment by amitkrout** [comment]
Got it.
The issue was coming due to because there was no ```EventuallyTimeout``` and ```ConsistentlyDuration``` in test script. This issue is fixed by pr https://github.com/openshift/odo/pull/3010.
