### ISSUE TITLE
odo doesn't honour "ODO_EXPERIMENTAL=false" on command line

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2999]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
```sh
$ odo preference view
PARAMETER             CURRENT_VALUE
UpdateNotification    
NamePrefix            
Timeout               
PushTimeout           
Experimental          true
PushTarget

$ ODO_EXPERIMENTAL=false odo catalog list services
Operators available in the cluster
NAME                          CRDs
etcdoperator.v0.9.4           EtcdCluster, EtcdBackup, EtcdRestore
mongodb-enterprise.v1.4.5     MongoDB, MongoDBUser, MongoDBOpsManager
```

## Actual behavior
odo prints the list of operators in spite of having set `ODO_EXPERIMENTAL=false` on CLI

## Expected behavior
Odo should not have listed operators. In my experience, CLI value gets preference over configuration. But what behaviour we want odo to emulate is up to the team. Also, document the same (if required)

**Comment by johnmcollier** [comment]
+1 for having the `ODO_EXPERIMENTAL` value override the value in the preference file. We did the same for the pushtarget preference and if `ODO_PUSHTARGET=<target>` is set, it uses that over whatever's stored in the preferences file.

**Comment by dharmit** [comment]
At the moment, if `ODO_EXPERIMENTAL` is set to `false` in shell but it's set to `true` in preferences, we consider this to be `true`.

Shouldn't it be considered `false` instead?

```sh
$ odo preference view
PARAMETER             CURRENT_VALUE
UpdateNotification    
NamePrefix            
Timeout               
PushTimeout           
Experimental          true
PushTarget            

$ echo $ODO_EXPERIMENTAL
false

$ odo create nodejs
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [130136ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [114683ns]
 ✓  Validating devfile component [214227ns]

Please use `odo push` command to create the component with source deployed
```

**Comment by girishramnani** [comment]
Yeah this is something we need to have because ODO_EXPERIMENTAL would be used even after devfilev2 becomes GA

**Comment by dharmit** [comment]
We don't have the experimental mode any more. Closing this.

/close

**Comment by girishramnani** [comment]
Are we sure - we would never need odo experimental feature again?

**Comment by dharmit** [comment]
It's never a 100% thing, I guess. But we can re-open this if we put anything behind experimental mode. Hopefully we won't. :smile:
