### ISSUE TITLE
Organize debugging information into separate sections.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3007]
/kind documentation
/kind code-refactoring

## What mistake did you find / what is missing in the documentation?

There is *a lot* of debugging information that's on `V(4)`.

We should organize all the debugging information into separate sections relevant to the logs.

For example:

`V(0)` Normal logging output
`V(1)` is for experimental features / testing suite
`V(2)` is for Devfile
`V(3)` is for Kubernetes and OpenShift debugging information
`V(4)` is for ALL other generic debugging information

`V(10)` is reserved for http requests (used within OpenShift and Kubernetes code)

etc.

There also needs to be some investigation of what other levels of debugging is used. For example, `V(10)` shows http debugging information from the OpenShift / Kubernetes clients.

We also need to discuss on what the "highest" level of debugging should be for users. For example, if one were to open up a new issue / bug that they occured, what should we suggest for them to run with the debugging command, for example, we currently use `-v 4` as our generic debugging output command. 

Should this be `odo -v 8` or something else?

TODO:

 - [ ] Documentation on each level, and add that to `/docs/development.adoc`
 - [ ] Discussions as to what level is used for what
 - [ ] Discussions on what the "highest" level of debug should be. For example, `odo -v 4` is too low, it may need to be `odo -v 8`.

## What is the relevance of it?

More organization :)

**Comment by prietyc123** [comment]
feature request looks good to me. @cdrage please go ahead and draft the pr. On the pr we will discuss more or maybe you get some more valuable input from reviewer cc_ @amitkrout
