### ISSUE TITLE
External dependencies in integrations test

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3020]
The integrations test should not have external dependency unless it is absolutely unavoidable.
It creates unnecessary external dependencies that lead to flaky tests.
```
        util_test.go:1464: Error downloading zip: Get https://github.com/che-samples/web-nodejs-sample/archive/master.zip: dial tcp: lookup github.com on [::1]:53: read udp [::1]:52934->[::1]:53: read: connection refused
```

The example app should be stored with tests, and then copied into a temp directory using `helper.CopyExample`

These are some of the test scenarios that are unnecessary cloning GitHub repos.

https://github.com/openshift/odo/blob/10826cc3f43c74ebadd917c3c53e9b40d6853aa6/tests/integration/devfile/utils/utils.go#L38
https://github.com/openshift/odo/blob/10826cc3f43c74ebadd917c3c53e9b40d6853aa6/tests/integration/devfile/docker/cmd_docker_devfile_url_test.go#L48
https://github.com/openshift/odo/blob/2086305a0caaaf603b90a4fb9139ebb0453f3a10/tests/integration/devfile/cmd_devfile_url_test.go#L53
https://github.com/openshift/odo/blob/12801e01b47dc5b4a08e3b30b346417540e5b385/tests/integration/devfile/cmd_devfile_delete_test.go#L51

/assign @maysunfaisal 
/assign @yangcao77

/area testing

**Comment by maysunfaisal** [comment]
One of the PR review feedback was to clone the project, but I'll add it back since its creating flakes

**Comment by maysunfaisal** [comment]
Though the first log trace in OP

```
 util_test.go:1464: Error downloading zip: Get https://github.com/che-samples/web-nodejs-sample/archive/master.zip: dial tcp: lookup github.com on [::1]:53: read udp [::1]:52934->[::1]:53: read: connection refused
```

is from utils_test.go acc to PR https://github.com/openshift/odo/pull/3019 and is used to extract a downloaded project. @EnriqueL8 can you pls look at the disabled flake acc to PR #3019?

I can tackle the other integration tests like @kadel pointed out in the rest of the OP.

**Comment by kadel** [comment]
> One of the PR review feedback was to clone the project, but I'll add it back since its creating flakes

hmm :-( Sorry for the confusion. Unless it is is really necessary for the test we should try to avoid any external dependencies like this. 



> Though the first log trace in OP
> 
> ```
>  util_test.go:1464: Error downloading zip: Get https://github.com/che-samples/web-nodejs-sample/archive/master.zip: dial tcp: lookup github.com on [::1]:53: read udp [::1]:52934->[::1]:53: read: connection refused
> ```
> 
> is from `utils_test.go` acc to PR #3019 and is used to extract a downloaded project. @EnriqueL8 can you pls look at the disabled flake acc to PR #3019 and assign yourself as well?

I forgot to include this one in the list.
/assign @EnriqueL8

**Comment by dharmit** [comment]
ping @kadel :man_shrugging:
