### ISSUE TITLE
Test and Release/Build environment should match

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3023]
It is important that the test environment and release/build environment match.
For example, the same Go version should be used everywhere. 

- RPM Spec is currently specifying Go 1.11. https://github.com/openshift/odo/blob/08c339c744f8d92848b50ba816fc0a82e5cff302/rpms/openshift-odo.spec#L6
- Release build on Red Hat Brew instance is happening on 1.12.
- Travis-CI is using Go 1.13.1 https://github.com/openshift/odo/blob/08c339c744f8d92848b50ba816fc0a82e5cff302/.travis.yml#L19
- OpenShift CI is using Go 1.13 https://github.com/openshift/odo/blob/08c339c744f8d92848b50ba816fc0a82e5cff302/openshift-ci/build-root/Dockerfile#L3

Acceptance criteria:
 - [ ] use the same go versions everywhere (1.12)
 - [ ] document how to change go version (all places where it needs to be updated) 

/area release-eng
/area testing
/kind bug
/priority high

/cc @amitkrout @mohammedzee1000

**Comment by mohammedzee1000** [comment]
It seems like a pretty straightforward but important problem.
/assign

**Comment by dharmit** [comment]
And on developer system I'm using `1.14.2`. :laughing:

**Comment by mohammedzee1000** [comment]
I guess that is ok as CI will detect any issues that you try to pass off :P
