### ISSUE TITLE
odo binaries for v1.2.0 release have not been uploaded to mirror.openshift.com

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#3024]
/kind bug

Latest release download [link](https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.2.0/) leads to missing folder
![image](https://user-images.githubusercontent.com/620330/80435762-4916ab00-88b2-11ea-828e-dff0a9de6149.png)

**Comment by kadel** [comment]
1.2.0 has not been released yet

**Comment by kadel** [comment]
done, and fixed 
/close
