### ISSUE TITLE
Fix Kubernetes integration test issues: create a non-colliding random string generator for namespace generation

### ISSUE THREAD

**Issue by jgwest** [openshift/odo#3028]
/kind feature

## Which functionality do you think we should add?

This test bug is opened to track the following issue with the Odo integration tests against Kubernetes:

#### [kubectl] Error from server (AlreadyExists): namespaces "xvqjwfscgf" already exists

This error occurs in local and CI runs of Kubernetes-targetted devfile tests, because the existing random string generator (`RandString`) is generating colliding strings across multiple Ginkgo processes. My solution is to use a pseudorandom generator initialized with a seed value from the OS crypto RNG.

Since the failing behaviour is a race condition this problem only occurs intermittently, but one can find this error in the Jenkin CI builds, and the above issue is the reason (though after https://github.com/openshift/odo/pull/3041 was merged, it has become significantly more intermittent/less likely to occur)

PR:
https://github.com/openshift/odo/pull/2976

**Comment by jgwest** [comment]
Waiting on https://github.com/openshift/odo/pull/3041 to get merged before continuing this.

**Comment by jgwest** [comment]
Closing as the issue has been handled by https://github.com/openshift/odo/pull/3358 by switching everything to use crypto rand.

**Comment by elsony** [comment]
done
/close
