### ISSUE TITLE
[Docker] Hard to recover if supervisord volume is empty/corrupted

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3034]
/kind bug
/area devfile
/area local

I've found that if the user exits odo while the supervisord image is being pulled, it can leave the user's system in a bad state that's hard to recover from:

```
Johns-MacBook-Pro-3:nodejs johncollier$ odo push

Validation
 ✓  Validating the devfile [55787ns]
^C
Johns-MacBook-Pro-3:nodejs johncollier$ odo push

Validation
 ✓  Validating the devfile [163221ns]

Creating Docker resources for component nodejs
 ✓  Pulling image quay.io/eclipse/che-nodejs10-ubi:nightly [2s]
 ✗  Starting container for quay.io/eclipse/che-nodejs10-ubi:nightly [505ms]
 ✗  Failed to start component with name nodejs.
Error: Failed to create the component: unable to create or update component: unable to pull and start container runtime for component nodejs: Unable to start container for devfile component runtime: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/opt/odo/bin/supervisord\": stat /opt/odo/bin/supervisord: no such file or directory": unknown
```

The volume exists, but doesn't have the supervisord binary on it. It's not really clear to the user _how_ to recover from this. For me, I had to do the following:
1) Restart docker
2) Run `docker system prune`
3) Delete the supervisord volume
4) Delete the supervisord image

(Alternatively a single docker restart + `docker system prune -a` would've worked too)

This happens because we create the supervisord volume before we pull the image. So, when `odo push` is run again, we check only for the existence of the volume, not that the volume actually contains the binary. I think we need to add a check that confirms that the supervisord volume has the binary on it, and if not, re-pull the image and re-create the volume.

**Comment by maysunfaisal** [comment]
A container needs to mount the vol, to be able to verify if the binary is there.

Thinking if we should instead pull down a supervisord inti container everytime we push, and instead of copying the binary and exiting; it checks if the vol has been initialized, if not; it copies it.

what do you think @johnmcollier 

I can take a look at this
/assign
