### ISSUE TITLE
Odo push fails on 3.11 cluster having docker version (18.06.0-ce) running on travis xenial distro

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3055]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?
Running tests jobs on travis CI

## Actual behavior
Hitting error https://travis-ci.com/github/openshift/odo/jobs/324857465#L582 and some more different errors in the test running on openshift 3.11 with xenial distro of travis CI.

I am suspecting ```oc cluster up``` is having compatibility issue with the default docker available on xenial distro causing error like i mentioned above.

## Expected behavior

Tests associated with openshift should also run on xenial distro of travis CI.

## Any logs, error output, etc?
 more details of errors : https://github.com/openshift/odo/pull/2913/checks?check_run_id=632261884

**Comment by prietyc123** [comment]
Xenial distribution of travis CI is required to run latest kubernetes cluster. On the other hand we can use older version of minikube but odo push does not support the older version of minikube, which has been elaborated in issue : #2928 .

However there are some other consequences also of using older version of minikube like lag of latest feature implementation and I am suspecting this could be one of the reason that odo push is not supporting on older version of minikube. IMO we should move towards latest version minikube and hence xenial distribution of travis CI could be one of the solution.

Currently we are running our test on travis CI with trusty distribution, ubuntu version 14.04. And running the latest minikube needs systemd which was added in ubuntu 16.04, therefore we need to bump the ubuntu version to 16.04+ using xenial distribution of travis CI.

So, IMO we need to think for docker support on xenial distribution of travis CI. ```Xenial``` is providing docker version ```$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
which is not supported by ```oc```

**Comment by kadel** [comment]
@prietyc123 you might need to configure docker daemon to allow unsecured registry on `172.30.1.1:5000`

**Comment by prietyc123** [comment]
> @prietyc123 you might need to configure docker daemon to allow unsecured registry on `172.30.1.1:5000`

Ahh... Thanks for the tips. I will try it out for sure 👍

**Comment by prietyc123** [comment]
In ubuntu xenial configuring docker daemon ```/etc/docker/daemon.json``` with insecure registry ```"insecure-registries": ["172.30.0.0\/16"]``` worked fine for ```oc cluster up```
