### ISSUE TITLE
For secured url1 'odo url describe url1 -o json' prints 'secure' attribute as `false`

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#3060]
/kind bug

## What versions of software are you using?

**Operating System:**
windows 10
**Output of `odo version`:**
1.2.0
## How did you run odo exactly?
Component has one secured url.
Running:
`odo url describe`
`odo url list`
show the same url with different values for 'secure' attribute.

## Actual behavior
```
denis@denis-ThinkPad-P50:~/test/test-1$ odo url describe url1 -o json
{
    "kind": "url",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "url1",
        "creationTimestamp": null
    },
    "spec": {
        "port": 8080,
        "secure": false
    },
    "status": {
        "state": "Pushed"
    }
}
```
`odo ulr list` prints out different json with correct value.
```
denis@denis-ThinkPad-P50:~/test/test-1$ odo url list -o json
{
    "kind": "List",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {},
    "items": [
        {
            "kind": "url",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "url3",
                "creationTimestamp": null
            },
            "spec": {
                "host": "url3-app1-p1.apps-crc.testing",
                "protocol": "https",
                "port": 8080,
                "secure": true
            },
            "status": {
                "state": "Pushed"
            }
        }
    ]
}
```

## Expected behavior
In both outputs `secure` equals `true`

**Comment by jeffmaury** [comment]
Adding to this use case: if url is created with secure attribute but not pushed to the cluster, then `odo url list` reports it as non secure. After the url is pushed to the cluster then `odo url list` is correct.

**Comment by jeffmaury** [comment]
Also please note that the URL is not retrieved by `odo url describe`

**Comment by yangcao77** [comment]
Should be fixed via: https://github.com/openshift/odo/pull/3160
/assign

**Comment by mik-dass** [comment]
#3269 needs to be merged
