### ISSUE TITLE
Odo list URL for component with no context removed 

### ISSUE THREAD

**Issue by sbouchet** [openshift/odo#3078]
/kind bug

## What versions of software are you using?

**Operating System:**
RHEL 8

**Output of `odo version`:**
odo v1.1.1 (02fbd3d08)

Server: https://api.rh-us-east-1.openshift.com:443
OpenShift: v3.11.154
Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?
related bug in IntelliJ openShift connector : https://github.com/redhat-developer/intellij-openshift-connector/issues/186 

in home directory, following odo command is performed to retrieve the URL list for a particular component with no context:
`odo url list --component java --app app --project jbt-test -o json`

this command no longer works in recent odo version, it was removed in 1.0.0.

## Actual behavior
Exception is thrown, command returns help usage.

## Expected behavior
in previous version, odo returned 
```
/home/sbouchet/.odo/cache/1.0.0-beta5/odo url list --component java --app app --project jbt-test
Found the following URLs for component java in application app:
NAME     STATE               URL                                                              PORT
port     Locally Deleted     http://port-app-jbt-test.6923.rh-us-east-1.openshiftapps.com     8080

There are local changes. Please run 'odo push'.
---
A newer version of odo (version: v1.1.3) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/openshift/odo/master/scripts/installer.sh | sh
to update manually, or visit https://github.com/openshift/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo preference set UpdateNotification false'
```

**Comment by sbouchet** [comment]
Is this actually still relevant to list URLs for components with no context?

**Comment by dharmit** [comment]
@sbouchet if you'd like to list URLs for a component from a directory other than its component directory (a.k.a. context), it's best you'd use something like:
```sh
$ odo url list --context /path/to/component/dir
```
The url list command doesn't have flags that you've mentioned in issue description.

**Comment by sbouchet** [comment]
@dharmit the problem is that I do not have any context when using these flags. 
in the IDEs, we use odo to interact with the user to display a tree that contains all project from a cluster. these projects can be created with different tools ( oc, web console, Eclipse, VSCode, ...)
if I know the context, I directly run 
`odo url list `
in that directory.

So I think we should remove that piece of code on our side and simply do not displays URL because odo removed this feature/flags.

**Comment by sbouchet** [comment]
closing since we modified our logic to not use this command anymore with no context components.
