### ISSUE TITLE
Document the Kube RBACs required to run odo experimental

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3089]
/kind documentation

## What mistake did you find / what is missing in the documentation?
If we're running odo in experimental mode in a Kube platform other than OpenShift, Minishift; we need to document the Roles required for the user to run odo in experimental mode successfully.

## What is the relevance of it?
Odo experimental mode, is Kube platform agnostic and thus, the user would require the appropriate Roles to create the various Kubernetes resources.

**Comment by johnmcollier** [comment]
Debating on the best way to document this:
- Do we provide a role that cluster administrators can apply to users that need to use odo?
     - How do we keep this up to date?
- Do we just document the permissions that odo needs and leave it up to the user?
    - Documenting each individual role that odo needs seems messy and again, would need to be kept up to date

**Comment by Preeticp** [comment]
@kadel @girishramnani these docs should probably reside only in GH?

**Comment by cdrage** [comment]
Hey @maysunfaisal bit confused regarding this. I have updated all documentation on the `odo.dev` site to reflect that it's Kubernetes / OpenShift agnostic, so you can deploy on either one. 

Do you mean RBAC roles or anything else we need to apply?
