### ISSUE TITLE
odo binary SHA256_SUM is incorrect for odo-darwin

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#3093]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS - For odo 1.2.0 release

## How did you run odo exactly?
https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.2.0/SHA256_SUM

## Actual behavior
Double entries for odo-darwin-amd64.tar.gz for SHA256_SUM

## Expected behavior
odo-darwin-amd64.tar.gz should have correct SHA256_SUM

**Comment by kadel** [comment]
Reported at https://issues.redhat.com/browse/ART-1854

**Comment by kadel** [comment]
fixed
/close
