### ISSUE TITLE
Add 'odo preference list` command with '-o' options support

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#3094]
/kind feature

## Which functionality do you think we should add?

There should be a way to get full list of supported preferences with human readable description and preferably information about preference value type. So dependent tools can build UI based on this information rather than hardcode supported preferences for every odo version.

## Why is this needed?

Using information above we can build nice UI in every tools to configure odo preferences.

**Comment by girishramnani** [comment]
I can work on this

**Comment by girishramnani** [comment]
also by `odo preference list` u mean `odo preference view` right?
