### ISSUE TITLE
odo should be aware of component state and block some conflicting commands

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#3095]
/kind feature

## Which functionality do you think we should add?

odo should be aware what is going on with component to prevent execution of some conflicting commands. 
Simplest example prevent running push command when 'odo watch' is running for the same component.

Current implementation supports only three states for component, it is based on presence in local file system and component related resources in cluster
1. Not Pushed (exists locally, but not in cluster)
2. Pushed (exists locally and in cluster)
3. Unknown (does not exists locally, but exists in cluster - called 'No Context' OpenShift Connector Extension)

It might make sense to have additional states for transition between 1 and 2, because it is usually not atomic operation and takes time to update/delete all related resources. other command my interfere with resources while component in transition between sates and lead to unpredictable component state or bizarre errors.

Possible additional states are:
- Is being pushed
- Is being watched
- Is being deleted
- Pushed with errors

## Why is this needed?

To avoid conflicts between commands and unpredictable errors.

**Comment by kadel** [comment]
This should be eventually addressed with https://github.com/openshift/odo/issues/2550#issuecomment-591261501
@dgolovin can you check what is proposed there?

**Comment by girishramnani** [comment]
Any update on this @dgolovin
