### ISSUE TITLE
odo link fails to link components

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3101]
/kind bug

## What versions of software are you using?

**Operating System:**
all supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Steps:

1. Created the nodejs frontend and backend component in two different context. Also specify ```--app``` flag for one of the component
2. Add url having same name but different port for both the component
3. Add storage volume for both.
4. Push the components
5. Perform ```odo link``` operation

I ran the steps manually in regular mode on 4.4 openshift cluster.

## Actual behavior

```
$ odo project create nodejss
 ✓  Project 'nodejss' is ready for use
 ✓  New project created and now using project: nodejss
$ cd manualtest/
$ odo create nodejs backend --port 8080,8100/tcp --context . --project nodejss
 ✓  Validating component [996ms]

Please use `odo push` command to create the component with source deployed
$ odo url create abcd --port 8100 --context .
 ✓  URL abcd created for component: backend

To create URL on the OpenShift Cluster, please use `odo push`
$ odo storage create pv2 --path /mnt/pv2 --size 1Gi --context .
 ✓  Added storage pv2 to backend

Please use `odo push` command to make the storage accessible to the component
$ odo push --context .
Validation
 ✓  Checking component [2s]

Configuration changes
 ✓  Added storage pv2 to backend
 ✓  Initializing component
 ✓  Creating component [5s]

Applying URL changes
 ✓  URL abcd: http://abcd-app-nodejss.apps.ci-ln-3fsz22k-d5d6b.origin-ci-int-aws.dev.rhcloud.com created

Pushing to component backend of type local
 ✓  Checking files for pushing [4ms]
 ✓  Waiting for component to start [1m]
 ✓  Syncing files to the component [7s]
 ✓  Building component [15s]
 ✓  Changes successfully pushed to component
$ odo create nodejs frontend --context ../tests/examples/source/nodejs/ --project nodejss --app testing
 ✓  Validating component [733ms]

Please use `odo push` command to create the component with source deployed
$ odo url create abcd --port 8080 --context ../tests/examples/source/nodejs/
 ✓  URL abcd created for component: frontend

To create URL on the OpenShift Cluster, please use `odo push`
$ odo storage create pv1 --path /mnt/pv1 --size 1Gi --context ../tests/examples/source/nodejs/
 ✓  Added storage pv1 to frontend

Please use `odo push` command to make the storage accessible to the component
$ odo push --context ../tests/examples/source/nodejs/
Validation
 ✓  Checking component [1s]

Configuration changes
 ✓  Added storage pv1 to frontend
 ✓  Initializing component
 ✓  Creating component [4s]

Applying URL changes
 ✓  URL abcd: http://abcd-testing-nodejss.apps.ci-ln-3fsz22k-d5d6b.origin-ci-int-aws.dev.rhcloud.com created

Pushing to component frontend of type local
 ✓  Checking files for pushing [6ms]
 ✓  Waiting for component to start [34s]
 ✓  Syncing files to the component [4s]
 ✓  Building component [10s]
 ✓  Changes successfully pushed to component
$ odo link backend --port 8080 --context ../tests/examples/source/nodejs/
 ✗  Neither a service nor a component named backend could be located. Please create one of the two before attempting to use 'odo link'
```

## Expected behavior

```odo link``` should link the component successfully.

**Comment by kadel** [comment]
This is the correct behavior.
Your components are in different applications (backend in default "app" application, frontend in "testing" application)
You can't just call `odo link backend --port 8080 --context ../tests/examples/source/nodejs/` this will look in the same application where the frontend is (component in `../tests/examples/source/nodejs/`). If the backend in a different application you have to specify it `odo link backend --app  app --port 8080 --context ../tests/examples/source/nodejs/`

/close

**Comment by prietyc123** [comment]
> This is the correct behavior.
> Your components are in different applications (backend in default "app" application, frontend in "testing" application)
> You can't just call `odo link backend --port 8080 --context ../tests/examples/source/nodejs/` this will look in the same application where the frontend is (component in `../tests/examples/source/nodejs/`). If the backend in a different application you have to specify it `odo link backend --app app --port 8080 --context ../tests/examples/source/nodejs/`
> 
> /close
> 
> Feel free to reopen if the above command doesn't solve the issue

I seems we can not specify app if context is provided.
Error:
```
$ odo link backend --app app --port 8080 --context ../tests/examples/source/nodejs/
 ✗  cannot provide --app, --project or --component flag when --context is provided
```
As I have the component in two different directory, I am not how to handle this situation in odo. @kadel @girishramnani  Could you please provide some input on this?

**Comment by amitkrout** [comment]
@prietyc123 Can you move out from the current component dir ```.``` and execute the last command ```odo link backend --port 8080 --context ../tests/examples/source/nodejs/```

**Comment by prietyc123** [comment]
> odo link backend --port 8080 --context ../tests/examples/source/nodejs/

@amitkrout I am still facing the same failure:
```
$ cd ..
$ odo link backend --port 8080 --context ../tests/examples/source/nodejs/
 ✗  Neither a service nor a component named backend could be located. Please create one of the two before attempting to use 'odo link'
```

**Comment by amitkrout** [comment]
> > odo link backend --port 8080 --context ../tests/examples/source/nodejs/
> 
> @amitkrout I am still facing the same failure:
> 
> ```
> $ cd ..
> $ odo link backend --port 8080 --context ../tests/examples/source/nodejs/
>  ✗  Neither a service nor a component named backend could be located. Please create one of the two before attempting to use 'odo link'
> ```

Interesting!!!
Almost scenario in our test script works properly https://github.com/openshift/odo/blob/master/tests/integration/cmd_link_unlink_test.go#L85. Can you please map and find out the missing part in your test.

**Comment by prietyc123** [comment]
> Almost scenario in our test script works properly https://github.com/openshift/odo/blob/master/tests/integration/cmd_link_unlink_test.go#L85. Can you please map and find out the missing part in your test.

Yes, this will work because both the components in this scenario are on the same application i.e `app` in this case. But my requirement is to link the components which are located in two different app. I also tried the ```--app``` flag to connect both component as per @kadel suggestion but it didn't work rather it throws [error](https://github.com/openshift/odo/issues/3101#issuecomment-625072287). 

I wonder do we really support such kind of scenarios like `linking of component located in two different app`?

**Comment by amitkrout** [comment]
@prietyc123 ahh...may be you hit the same scenario - https://github.com/openshift/odo/issues/2394

@kadel @girishramnani Can you please confirm ? is it still a invalid case as reported in https://github.com/openshift/odo/issues/2394

**Comment by girishramnani** [comment]
As far as I remember,
—context and (—app and —project) are mutually exclusive flag groups i.e. you cannot use one with the other.

**Comment by amitkrout** [comment]
>As far as I remember,
—context and (—app and —project) are mutually exclusive flag groups i.e. you cannot use one with the other.

Understood
So the scenario @prietyc123 trying is a bug or we do not support such scenario ?

**Comment by girishramnani** [comment]
can you please confirm if the `app` in both the component contexts are same?

**Comment by prietyc123** [comment]
> can you please confirm if the `app` in both the component contexts are same?

@girishramnani app in both the context are different. When you will go through the steps I mentioned in the issue you will find that the `backend` component has app `app` whereas fronten  app is `testing`. When you will go through `actual behavior` you will find more clarity on this.

**Comment by dharmit** [comment]
Lowering the priority because things might change completely with the s2i to devfile convertor showing up and then this issue might become irrelevant at least as far as the backend is concerned.

**Comment by dharmit** [comment]
1. We're discussing linking of s2i components in this issue. This might become obsolete if we go ahead with automagically converting s2i components to devfile as discussed in one of the cabals.
2. `--app` and `--project` flags are not supposed to be used with `--context`. We need to do a better job at documenting this or throwing an error when the user tries to do this.

Removing the stale flag for now but this is surely low on priority.

**Comment by valaparthvi** [comment]
I think it is safe to close this issue.
https://github.com/openshift/odo/commit/843e520f6b6c7085406d6ef9036edf355a0a9896
https://github.com/openshift/odo/pull/4866
cc : @feloy

**Comment by prietyc123** [comment]
I tried the same scenario and it works successfully for me now. So closing this issue.
