### ISSUE TITLE
Categorizing integration tests

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#3111]
/kind feature

## Which functionality do you think we should add?
As devfile support for both k8s and docker are in, we should categorize those integration tests properly. Idea from @johnmcollier 
```
Devfile integration tests that require Kube
Devfile integration tests that require Docker
Devfile integration tests that don't require a specific runtime (eg. catalog and registry)
```
Another thing we should consider is that which job runs on which environment (k8s cluster VS OpenShift cluster). Also do we have special case like `docker devfile url` as it needs to run on k8s cluster for getting k8s config file?

## Why is this needed?
Integrations tests would be more clear with proper categorizing, and testing resource can be allocated efficiently.

**Comment by amitkrout** [comment]
@GeekArthur Thanks for the issue.

> Another thing we should consider is that which job runs on which environment (k8s cluster VS OpenShift cluster). Also do we have special case like docker devfile url as it needs to run on k8s cluster for getting k8s config file?

We had a pr https://github.com/openshift/odo/pull/2996 already went in few days back that solves the purpose you are looking.

> As devfile support for both k8s and docker are in, we should categorize those integration tests properly. Idea from @johnmcollier
               Devfile integration tests that require Kube
               Devfile integration tests that require Docker
               Devfile integration tests that don't require a specific runtime (eg. catalog and registry)

+100 for spec level categorization

**Comment by GeekArthur** [comment]
> @GeekArthur Thanks for the issue.
> 
> > Another thing we should consider is that which job runs on which environment (k8s cluster VS OpenShift cluster). Also do we have special case like docker devfile url as it needs to run on k8s cluster for getting k8s config file?
> 
> We had a pr #2996 already went in few days back that solves the purpose you are looking.
> 
> > As devfile support for both k8s and docker are in, we should categorize those integration tests properly. Idea from @johnmcollier
> > Devfile integration tests that require Kube
> > Devfile integration tests that require Docker
> > Devfile integration tests that don't require a specific runtime (eg. catalog and registry)
> 
> +100 for spec level categorization, however can you please specify few spec from our existing test that deserves a categorization.

Yep, I saw that PR before, but I mean if we still have other tests similar to `docker devfile url` case or not and if we have we need to address them as well, just would like to bring that up.

Regarding categorization, currently we can separate those test suites that only need odo runtime, for example, `odo create`, `odo catalog`, `odo registry`, but need to do some testing before categorization in case we still have cases similar to `docker devfile url`. Another thing is about testing environment, do we want to test devfile test suites against both OpenShift cluster and k8s cluster or only k8s cluster should be sufficient?

**Comment by amitkrout** [comment]
> Yep, I saw that PR before, but I mean whether we still have other tests similar to docker devfile url case or not and if we have we need to address them as well, just would like to bring that up.

+1 

> Regarding categorization, currently we can separate those test suites that only need odo runtime, for example, odo create, odo catalog, odo registry, but need to do some testing before categorization in case we still have cases similar to docker devfile url.

Understood
It sounds like a plan to me. It requires a proper analysis effort to categorize such test. As part of ```docker devfile…``` is concerned, we need to define a docker version test matrix. For example which version of docker supports devfile docker pushtarget then accordingly we need to test devfile against these docker version in CI. Anyway I have created a separate issue https://github.com/openshift/odo/issues/2995 for devfile docker version test matrix support. Can you please comment on the issue. Thanks

> Another thing is about testing environment, do we want to test devfile test suites against both OpenShift cluster and k8s cluster or only k8s cluster should be sufficient?

Devfile is supported on both openshift and kubernetes cluster. So we have to test it on Both the cluster. Infact we have already running dvfile test ```test-cmd-devfile-catalog``` and ```test-cmd-devfile-watch``` on both the cluster, also we have prs in progress #3041, #2913 and #2884 to run rest of devfile test on both cluster that needs Kube environment cc_ @prietyc123
