### ISSUE TITLE
Weird message gets printed for many odo commands

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#3113]
/kind bug

## Actual behavior

```
[mrinaldas@localhost che-nodejs]$ odo create nodejs
Experimental mode is enabled, use at your own risk

I0507 13:03:02.277990   22568 cert_rotation.go:137] Starting client certificate rotation controller
^C
[mrinaldas@localhost che-nodejs]$ odo push
I0507 13:03:13.364180   22587 cert_rotation.go:137] Starting client certificate rotation controller

Validation
 ✓  Validating the devfile [88861ns]
```

## Expected behavior

```
I0507 13:03:02.277990   22568 cert_rotation.go:137] Starting client certificate rotation controller
```
not to be printed

**Comment by mik-dass** [comment]
This seems to be happening only on minikube

**Comment by varsharain-a11y** [comment]
@mik-dass 
Hi Mrinal,
I tried odo commands on minikube. However i don't see the "Starting client certificate rotation controller" message.
~~~~~~~
@vasharma minikube]# odo version
odo v1.2.0 (7f14dab08)

Server: https://openshift.varsha111.lab.pnq2.cee.redhat.com:443
OpenShift: v3.11.200
Kubernetes: v1.11.0+d4cacc0

~~~~~~~~~
[@vasharma nodejs-ex]# odo create nodejs
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [228155ns]
 ✓  Validating devfile component [77530ns]

Please use `odo push` command to create the component with source deployed
[root@vasharma nodejs-ex]# odo push

Validation
 ✓  Validating the devfile [60238ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [3m]

Syncing to component nodejs
 ✓  Checking files for pushing [3ms]
 ✓  Syncing files to the component [2s]

Executing devfile commands for component nodejs
 ◒  Executing devbuild command "npm install" ✗  
Unable to exec command [/bin/sh -c cd ${CHE_PROJECTS_ROOT}/nodejs-web-app/app && npm install]: 
/bin/sh: line 0: cd: /projects/nodejs-web-app/app: No such file or directory

 ✗  Executing devbuild command "npm install" [840ms]
 ✗  Failed to start component with name nodejs.
Error: Failed to create the component: unable to execute the build command: error while streaming command: command terminated with exit code 1

**Comment by mik-dass** [comment]
> I tried odo commands on minikube. However i don't see the "Starting client certificate rotation controller" message.

Can you please share the minikube version?

**Comment by varsharain-a11y** [comment]
-->Can you please share the minikube version?

[@vasharma minikube]# minikube version
minikube version: v1.10.0

**Comment by mik-dass** [comment]
@varsharain-a11y My minikube version is 
```
[mrinaldas@localhost ~]$ ./minikube version
minikube version: v1.9.2
```

> Hi Mrinal,
I tried odo commands on minikube. However i don't see the "Starting client certificate rotation controller" message.
@vasharma minikube]# odo version
odo v1.2.0 (7f14dab08)
Server: https://openshift.varsha111.lab.pnq2.cee.redhat.com:443
OpenShift: v3.11.200
Kubernetes: v1.11.0+d4cacc0

Also you are using a openshift cluster and not minikube as openshift version is being displayed.

**Comment by varsharain-a11y** [comment]
@mik-dass 

With experimental mode set to false i am getting below error:

~~~
[vasharma@vasharma nodejs-ex]$ odo create nodejs
 ✗  the server could not find the requested resource (get imagestreams.image.openshift.io nodejs)
~~~

With experimental mode set to true:

 [vasharma@vasharma nodejs-ex]$ odo preference set experimental true
? experimental is already set. Do you want to override it in the config Yes
Global preference was successfully updated
[vasharma@vasharma nodejs-ex]$ odo create nodejs
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [48951ns]
 ✓  Validating devfile component [105480ns]

Please use `odo push` command to create the component with source deployed

[vasharma@vasharma nodejs-ex]$ kubectl cluster-info
Kubernetes master is running at https://192.168.39.247:8443
KubeDNS is running at https://192.168.39.247:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

[vasharma@vasharma minikube]$ odo version
odo v1.2.0 (7f14dab08)

Don't know if i am missing anything.

**Comment by mik-dass** [comment]
> [vasharma@vasharma minikube]$ odo version
odo v1.2.0 (7f14dab)
Don't know if i am missing anything.

This time it's a kubernetes cluster as openshift version is not displayed compared to https://github.com/openshift/odo/issues/3113#issuecomment-627209757. I started facing this problem after https://github.com/openshift/odo/pull/3081 got in. Looking at the commit hash, it seems to be a older version of odo. Can you please update to the master branch of odo and try again?

**Comment by mik-dass** [comment]
I can't reproduce it anymore. The latest master or a updated minikube might have fixed this issue.
