### ISSUE TITLE
Better error when incorrect component type has been specified

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3128]
/kind bug
## What versions of software are you using?
1.2

**Operating System:**
mac

**Output of `odo version`:**

## How did you run odo exactly?
When I specified a wrong component type name during on create in the devfile scenario, the error message that comes back does not clearly point out on what may have caused the problem.

## Actual behavior
```
eyuentp2:springboot-ex eyuen$ odo create java-sprint-boot myspring
Experimental mode is enabled, use at your own risk

Validation
 ✗  Checking devfile compatibility [42454ns]

Please run 'odo catalog list components' for a list of supported devfile component types
 ✗  imagestreams.image.openshift.io "java-sprint-boot" not found
eyuentp2:springboot-ex eyuen$ odo create java-spring-boot myspring
```

## Expected behavior
It should return a more direct error that indicates the component type does not exists.

## Any logs, error output, etc?
See actual behaviour section

/area devfile

**Comment by johnmcollier** [comment]
So the root issue of this is that we always fall back to checking for an s2i image stream of that name, if a devfile component wasn't found. And if no s2i imagestream is found, we output the above error message, which may be consufin

We discussed on an earlier team meeting and decided to change the error message that gets printed when experimental mode is enabled and no devfile component or image stream was found:

Before
```
 ✗  imagestreams.image.openshift.io "java-sprint-boot" not found
```

After
```
 ✗  component "java-sprint-boot" not found
```

If experimental mode is not enabled, the original error message would still show up.

@kadel @elsony Any concerns with that?
