### ISSUE TITLE
Supported versions of Node.js out of date

### ISSUE THREAD

**Issue by mhdawson** [openshift/odo#3130]
/kind documentation

## What mistake did you find / what is missing in the documentation?

https://github.com/openshift/odo#officially-supported-languages-and-corresponding-container-images

Node.js 8.x is EOL and I don't believe it is supported by RH any more. The doc also likely needs to add Node.js 12.x which is LTS now.

## What is the relevance of it?

The doc has invalid/incorrect information.

**Comment by boczkowska** [comment]
Updated the table of images in this PR: https://github.com/openshift/openshift-docs/pull/23984

**Comment by mhdawson** [comment]
Thanks
