### ISSUE TITLE
Re-enforce Complete Validate Run methodology on cli commands

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3133]
There are some cli commands which right now don't enforce Complete-Validate-Run idealogy. i.e. Complete code is actually doing Validations etc. one instance https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L336-L339

Also I observed that the `Validation` phase for `odo create` starts in the `Complete` function https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L428

So we need to re-enforce this CVR design.

**Comment by metacosm** [comment]
While I agree on principle, I think there are cases where it makes sense to validate (and error out when needed) during the complete phase, in particular when all the information is available during that stage. In some cases, separating the validation process completely would mean duplicating processes that happen in `Complete` which, I think, should be avoided. This goes to the "fail fast" philosophy which `odo` should adhere to, in my opinion.

**Comment by dharmit** [comment]
I recently came across a PR #3118 where doing validation earlier helped provide a better user experience. For example what I've commented here https://github.com/openshift/odo/pull/3118#issuecomment-625660310. 

IMO, if it makes sense, we could keep exceptions to this rule. Of course, it shouldn't mean a license to break it at will. :)

**Comment by dharmit** [comment]
This still matters to us and is likely among the basic requirements to improve the overall code quality.

/reopen

/good-first-issue

/remove-lifecycle rotten
