### ISSUE TITLE
Remove duplicate code between push and file indexing 

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3135]
There's a good bit of repetition of code between `func (cpo *CommonPushOptions) Push()` and `func (a Adapter) SyncFiles(syncParameters common.SyncParameters) (isPushRequired bool, err error)`. Can we reduce this before we introduce a bug by making change at one place and forgetting to do it at the other?

_This issue is a spin-off of the comment https://github.com/openshift/odo/pull/2751#pullrequestreview-408913849._

/kind code-refactoring

**Comment by jichenjc** [comment]
yeah, this is something we need handle
