### ISSUE TITLE
devfile v2 support for odo push (k8s and OpenShift)

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3140]
/kind user-story

## User Story
As an odo user, I want to be able to use devfile.yaml defined using v2 spec

## Acceptance Criteria 
- [x] `odo push` should autodetect devfile.yaml version
- [x] `odo push` It should create Deployment with containers and Services based on the devfile.yaml v2 containers definition
- [x] `odo push` should create URL (Route or Ingress) based on devfile v2 definition
- [x] `odo push` should create storage for storage defined in devfile v2

above is relevant for `odo preference set pushtarget kube`

some examples of devfile v2 https://github.com/sbose78/stack-registry/tree/sbose78-patch-1/stacks

## Links 
https://github.com/openshift/odo/issues/3145 handles this for Docker (local pustarget)

/kind user-story
/area devfilev2
/area devfile
/priority high

**Comment by girishramnani** [comment]
We need to consider if `odo push` support for docker for devfile v2 needs to be a different issue or not.

**Comment by kadel** [comment]
> We need to consider if `odo push` support for docker for devfile v2 needs to be a different issue or not.

good point. I've created https://github.com/openshift/odo/issues/3145 to address the local (docker) case
