### ISSUE TITLE
Migrate the devfile v1 Tests to devfile  v2

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3142]
/kind test

Followup issue for PR https://github.com/openshift/odo/pull/3216

**Comment by prietyc123** [comment]
Thanks @adisky  for sharing the doc [1] for ```devfile v2 implementation plan```. AFAIU we are just adding a compatibility matrix of v2 for devfile support, I mean both v1 and v2 will be supported for devfile implementation and in later state v1 will be deprecated, right ?

However TBH I am clueless what test plan you are looking for it whereas we have the test for devfile in place. So can you please be more specific of what else test you are looking for. 

[1] https://docs.google.com/document/d/11BVhP1gViu5C3IGYQpiulX1lUkSGOG8p-lOJq4I5mUs/edit#heading=h.bw3vmyuddut1

**Comment by prietyc123** [comment]
I am not sure about keeping this issue in this sprint. As I have gone through the planned execution for V2 parser and it seems more challenging that it might take time, may be the whole sprint. So, keeping this issue in this sprint doesn't make sense to me.

Even I feel if we assign this task to the owner of the V2 parser this will be done parallely without consuming additional time that someone may take in getting the context. This will release some bandwidth for other tasks. So, I am unassigning myself.

/unassign @prietyc123

**Comment by prietyc123** [comment]
> I am not sure about keeping this issue in this sprint. As I have gone through the planned execution for V2 parser and it seems more challenging that it might take time, may be the whole sprint. So, keeping this issue in this sprint doesn't make sense to me.
> 
> Even I feel if we assign this task to the owner of the V2 parser this will be done parallely without consuming additional time that someone may take in getting the context. This will release some bandwidth for other tasks. So, I am unassigning myself.

ping @adisky
