### ISSUE TITLE
Support non-GitHub URLs for projects in devfiles

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3147]
/kind user-story
/area devfile

## User Story
Currently, the `--downloadSource` flag in `odo create <comp>`, only supports projects hosted on Github, as `odo` is using the Go-Github API.

As a user, I want to be able to host my code templates for devfiles in other Git repositories like Gitlab, and then use `odo create --downloadSource` to pull down those projects

## Acceptance Criteria 
- [ ] It should support any Git repository, regardless of where it is hosted
- [ ] It should use the Go-Git API

/kind user-story

**Comment by mik-dass** [comment]
@kadel I think we can close this

**Comment by mik-dass** [comment]
We have moved to go-git and currently support non github projects #3867
