### ISSUE TITLE
CI/tests should not run on documentation changes

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#3149]
/kind feature

## Which functionality do you think we should add?
Cf. title. 

## Why is this needed?
This would free up some resources for PRs that actually need the tests to be run and speed up documentation updates.

**Comment by metacosm** [comment]
It doesn't look like the [skip ci] command is working and it'd be better if it was enforced automatically since people might miss it when opening doc PRs…

**Comment by amitkrout** [comment]
> It doesn't look like the [skip ci] command is working and it'd be better if it was enforced automatically since people might miss it when opening doc PRs…

@metacosm It works if you pass the [skip ci] through git commit message. See https://github.com/openshift/odo/issues/2704#issuecomment-638294853

**Comment by amitkrout** [comment]
I am closing this as same stuff is being worked on in the issue https://github.com/openshift/odo/issues/2704
