### ISSUE TITLE
`odo url list` failing for push components, creating route, but trying to list ingress

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3153]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master
## How did you run odo exactly?
```
$ odo create nodejs ex1
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [80728ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [127980ns]
 ✓  Validating devfile component [143308ns]

Please use `odo push` command to create the component with source deployed
$ odo url create url1ex1 --host apps-crc.testing 
 ✓  URL url1ex1 created for component: ex1

To apply the URL configuration changes, please use `odo push`
$ odo push 

Validation
 ✓  Validating the devfile [26105ns]

Creating Kubernetes resources for component ex1
 ✓  Waiting for component to start [9s]

Applying URL changes
 ✓  URL url1ex1: http://url1ex1-myproject.apps-crc.testing created

Syncing to component ex1
 ✓  Checking files for pushing [404316ns]
 ✓  Syncing files to the component [132ms]

Executing devfile commands for component ex1
 ✓  Executing devbuild command "npm install" [2s]
 ✓  Executing devrun command "nodemon app.js" [1s]

Pushing devfile component ex1
 ✓  Changes successfully pushed to component
[adisky@localhost project]$ odo url list
 ✗  no URLs found for component ex1
```
Trying to list ingress, but it created route
```
$ odo url list --v 5
I0512 13:32:29.798081   18901 preference.go:188] The path for preference file is /home/adisky/.odo/preference.yaml
I0512 13:32:29.798273   18901 preference.go:188] The path for preference file is /home/adisky/.odo/preference.yaml
I0512 13:32:29.811293   18901 preference.go:188] The path for preference file is /home/adisky/.odo/preference.yaml
I0512 13:32:29.811416   18901 url.go:292] Listing ingresses with label selector: app.kubernetes.io/instance=ex1
```
```
$ oc get routes
NAME      HOST/PORT                            PATH   SERVICES   PORT   TERMINATION   WILDCARD
url1ex1   url1ex1-myproject.apps-crc.testing          ex1        3000                 None
```

## Actual behavior
`odo url list`, should list the created url

**Comment by mik-dass** [comment]
Seems like a duplicate of https://github.com/openshift/odo/issues/2985. Can you please confirm?

**Comment by dharmit** [comment]
@mik-dass the PR corresponding to that issue has been merged a while back. Is it expected to still face this issue wherein listing routes on OpenShift is not possible?

I commented about it here https://github.com/openshift/odo/issues/2983#issuecomment-627174901.

**Comment by adisky** [comment]
@mrianl yup it looks the same.
@dharmit I think the blocker PR to the issue gets merged. The issue itself is not fixed. correct me if i am wrong @mik-dass

**Comment by mik-dass** [comment]
> @mik-dass the PR corresponding to that issue has been merged a while back. Is it expected to still face this issue wherein listing routes on OpenShift is not possible?

@dharmit Actually https://github.com/openshift/odo/pull/2885 just added the route supported but the listing part wasn't implemented there.

> I think the blocker PR to the issue gets merged. The issue itself is not fixed. correct me if i am wrong @mik-dass

Yes only the blocker #2885 was merged.

**Comment by adisky** [comment]
@mik-dass closing this as issue, as it is dupe of #2985
