### ISSUE TITLE
Modify "genericclioptions.NewContext" to return context based on configuration of experimental mode

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3154]
Instead of checking for experimental mode and requesting a devfile context at different places in the code, wouldn't it make more sense to put that logic in NewContext so that the same logic doesn't need to be implemented everywhere?

_Originally posted by @metacosm in https://github.com/openshift/odo/pull/3069_

/kind code-refactoring

**Comment by johnmcollier** [comment]
@dharmit @metacosm I think my PR https://github.com/openshift/odo/pull/2981 should handle this 🙂

**Comment by dharmit** [comment]
Closing this in favour of #4081
