### ISSUE TITLE
"odo delete" and "odo create" follow different rules to decide upon component's existence in pwd

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3155]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
In below case, `odo create` and `odo delete` both fail.
```
$ odo preference view                                                                                                                                                                         
PARAMETER             CURRENT_VALUE                                                                                                                                                           
UpdateNotification                                                                                                                                                                            
NamePrefix                                                                                                                                                                                    
Timeout                                                                                                                                                                                       
PushTimeout                                                                                                                                                                                   
Experimental          true                                                                                                                                                                    
PushTarget

$ time odo create nodejs
Experimental mode is enabled, use at your own risk

 ✗  This directory already contains a devfile.yaml, please delete it and run the component creation command again
odo create nodejs  0.29s user 0.07s system 1% cpu 33.101 total

$ odo delete --all -f
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

## Actual behavior
 Apparently, `odo delete` doesn't delete `devfile.yaml` and `odo create` doesn't create a component in the same directory if it finds `devfile.yaml`.

Also, it takes 30+ seconds before telling the user that it can't create a component in `pwd` because `devfile.yaml` is already present. This validation about `devfile.yaml`'s existence should happen before going to the Internet. It's a bad user experience.

## Expected behavior
`odo delete` and `odo create` should converge on the definition of what a component means and what it doesn't! 

/area devfile
/priority high

**Comment by GeekArthur** [comment]
> Also, it takes 30+ seconds before telling the user that it can't create a component in pwd because devfile.yaml is already present. This validation about devfile.yaml's existence should happen before going to the Internet. It's a bad user experience.

This is covered by this PR https://github.com/openshift/odo/pull/3118, see the new performance here: https://github.com/openshift/odo/pull/3118#issuecomment-626036410

**Comment by prietyc123** [comment]
> odo delete doesn't delete devfile.yaml 

AFAIK `odo delete` deletes everything from the cluster even `devfile.yaml`. But yes it won't delete `devfile.yaml` locally.
