### ISSUE TITLE
url Application Not Available 

### ISSUE THREAD

**Issue by elizabethlumban** [openshift/odo#3164]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS 10.15.4
**Output of `odo version`:**
odo v1.2.0
## How did you run odo exactly?
I make sure I'm logged in to the OCP (v4.3) cluster (in our cloud account) and make sure I have my own namespace. Once inside my own namespace, I execute the following.

my repo are in :
https://github.com/elizabethlumban/react-starter2.git
https://github.com/elizabethlumban/odo-api2.git 

to deploy the react-starter 2 repo in OCP (in Server)

odo create nodejs odo-react-starter2
odo url create
odo push 

* we use nodejs v10 

to deploy the odo-api2 repo in OCP (in Server)
odo create nodejs odo-api2
odo url create
odo push 

here is a screenshot when I execute odo catalog list components
![Screenshot 2020-05-13 at 10 06 05 AM](https://user-images.githubusercontent.com/56430617/81763280-734aa880-9501-11ea-8c6c-cc147a5a67f2.png)

## Actual behavior
when i try to view the url generated for odo-react-starter2
I'm not able to see the homepage (see screenshot in expected behaviour)

## Expected behavior

when running this in local, It should show localhost running, showing item1, item2 and item 3
![Screenshot 2020-05-13 at 9 25 57 AM](https://user-images.githubusercontent.com/56430617/81762715-e9e6a680-94ff-11ea-861a-76805ce07194.png)

## Any logs, error output, etc?

when i do an odo log on the odo-api and odo-react-starter, i don't really see an error specific to the application, but when i try to view the app url, I get Application not available.
![Screenshot 2020-05-13 at 9 29 34 AM](https://user-images.githubusercontent.com/56430617/81763014-c5d79500-9500-11ea-87d8-19abe4e0a7cb.png)

I've spent quite of time troubleshooting this. Would really appreciate if you could advise as to why I'm not able to see the homepage. Thanks in advance..

**Comment by mik-dass** [comment]
I tried using odo with the repo https://github.com/elizabethlumban/react-starter2.git. For me, the build seems to be failing and thus application didn't start. Can you do `odo log` and provide the logs?

**Comment by elizabethlumban** [comment]
hi @mik-dass - I didn't get the same error as you. But I did make some changes in the code, just simple change to move the server.js in a server folder.. I pushed some code yesterday. Here is the log when I did a odo push --v 9 (saw this somewhere) ..

[odo_push_log_react_ui_13May2020.txt](https://github.com/openshift/odo/files/4625539/odo_push_log_react_ui_13May2020.txt)

Thank you again for your help.

**Comment by mik-dass** [comment]
```
sh-4.4$ nodemon server/server.js 
[nodemon] master: <none>
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server/server.js`
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/projects/nodejs-web-app/server/build/index.html'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/projects/nodejs-web-app/server/server.js:17:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
[nodemon] app crashed - waiting for file changes before starting...
^Csh-4.4$ pwd   
/projects/nodejs-web-app
sh-4.4$ mv server/server.js ../
sh-4.4$ ls
README.md  devfile.yaml  docs  manifest-prod.yml  manifest-sit.yml  node_modules  package.json  public  server  serverold.js  src  tsconfig.json  type-definitions  types  yarn.lock
sh-4.4$ ls server
sh-4.4$ cd ..
sh-4.4$ ls
nodejs-web-app  server.js
sh-4.4$ mv server.js nodejs-web-app/
sh-4.4$ ls
nodejs-web-app
sh-4.4$ cd nodejs-web-app/
sh-4.4$ ls
README.md  devfile.yaml  docs  manifest-prod.yml  manifest-sit.yml  node_modules  package.json  public  server  server.js  serverold.js  src  tsconfig.json  type-definitions  types  yarn.lock
sh-4.4$ nodemon server.js 
[nodemon] master: <none>
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/projects/nodejs-web-app/build/index.html'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/projects/nodejs-web-app/server.js:17:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
[nodemon] app crashed - waiting for file changes before starting...
```
The code crashes as it is looking for a `build/index.html` but the build folder doesn't exist. The `index.html` exists in the public folder.

**Comment by elizabethlumban** [comment]
hi @mik-dass - I've managed to resolve this issue.. from time to time, when I do a push, some of the files doesn't get pushed but I can't recreate the issue yet. Will raise a ticket once I have the concrete steps to reproduce it. Thanks again.
