### ISSUE TITLE
[question] how to generate a https url

### ISSUE THREAD

**Issue by elizabethlumban** [openshift/odo#3166]
Hi - I need to generate a https url, I've read the documentation (https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_developer_cli/odo-cli-reference.html#url) as well but I can't seem to find a way to generate a https url  using odo url create? Is this currently supported in odo? if yes, please kindly share as to how to generate a https url in odo. Thanks in advance!

**Comment by mik-dass** [comment]
@elizabethlumban You can use the `--secure` flag to generate the https URL.

**Comment by elizabethlumban** [comment]
thanks you!! @mik-dass

**Comment by mik-dass** [comment]
> thanks you!! @mik-dass , please close this issue(i don't seem to have the option to do so)

OK :+1: 
/close
