### ISSUE TITLE
[question] how to update nodejs to use v12

### ISSUE THREAD

**Issue by elizabethlumban** [openshift/odo#3168]
Hi, I did a odo catalog list components, and I can see (in the yaml file of the Build>Image stream ) that the latest is using node 10 only. Would you be able to advise as to how to update this to include node12. 

![Screenshot 2020-05-13 at 4 41 42 PM](https://user-images.githubusercontent.com/56430617/81791848-d9532200-9539-11ea-8b30-87368acdc705.png)

I was able to find rhscl/nodejs-12-rhel7 here

https://catalog.redhat.com/software/containers/detail/5da02401bed8bd2245d95cae?container-tabs=overview

and executed oc import-image rhscl/nodejs-12-rhel7 --from=registry.redhat.io/rhscl/nodejs-12-rhel7 --confirm

there was no error after I executed this.

 but it still didn't show up in the nodejs list of tags when I do  'odo catalog list components'. 

thanks in advance

**Comment by kadel** [comment]
OpenShift Components in odo are based on s2i builder images.

After importing the image you have to also tag is as a builder image.

Something like this should work.
```
oc import-image nodejs12 \
--from=registry.redhat.io/rhscl/nodejs-12-rhel7  \
--confirm

oc annotate istag/nodejs12:latest tags=builder
```


https://docs.openshift.com/dedicated/4/cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.html#adding-a-custom-builder-to-specify-a-build-image_creating-a-single-component-application-with-odo






> there was no error after I executed this.

What was the error that you got?


The to access  `registry.redhat.io` registry you need to be authenticated.

**Comment by elizabethlumban** [comment]
thanks @kadel - There was no error message,  I was able to update it, the tag command was the missing step that allows me to update the nodejs ... thanks again
