### ISSUE TITLE
odo should support devfile components with devRun but without devBuild

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3170]
/kind bug

## What versions of software are you using?
1.2

**Operating System:**
mac

**Output of `odo version`:**
odo v1.2.0 (7f14dab08)

## How did you run odo exactly?
A Quarkus devfile has been added to the default devfile registry (https://github.com/elsony/devfile-registry/tree/master/devfiles/quarkus).  However, the `odo catalog list components` does not currently show that component as supported.  The reason for it to show up is because the Quarkus component only defines the devRun command but not the devBuild command. odo should support component that does not have a devBuild command with only a devRun command since not all component type requires an actual build depending on the language and runtime.

## Actual behavior
```
eyuentp2:eynode2 eyuen$ odo catalog list components
Odo Devfile Components:
NAME                 DESCRIPTION                           SUPPORTED
maven                Upstream Maven and OpenJDK 11         YES
nodejs               Stack with NodeJS 10                  YES
openLiberty          Open Liberty microservice in Java     YES
java-spring-boot     Spring Boot® using Java               YES
```

## Expected behavior
The list show contain the Quarkus one on the list.

## Any logs, error output, etc?
No specific error output

/area devfile

**Comment by johnmcollier** [comment]
I can take a look at this

/assign
