### ISSUE TITLE
Synchronize upstream vs downstream with OpenShift and Kubernetes documentation

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3176]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Some notes from an earlier call with @kadel and @boczkowska 

Downstream = docs.openshift.com
Upstream = our docs on gh-pages

A list of what should be implemented:

- [ ] Properly have downstream vs upstream synchronization whether it's upstream -> downstream OR downstream -> upstream.
- [ ] Use `modules` and `attributes` in order to correctly separate between OpenShift, Docker and Kubernetes documentation. For example, if we are syncing to downstream to docs.openshift.com we should *remove* Kubernetes / Docker documentation and vice-versa if we decide on going from downstream -> upstream.

## What is the relevance of it?

Synchronization & kubernetes/docker documentation distinction.

**Comment by boczkowska** [comment]
I just noticed that the `Using odo in a restricted environment` is not synced. 
No template for it and the script doesn't pick them up bc the docs are in a subdirectory https://github.com/openshift/openshift-docs/tree/master/cli_reference/developer_cli_odo

**Comment by Preeticp** [comment]
@cdrage we are also considering a restructuring of the docs to bring information on storage etc outside of unrelated assemblies. Please let us get that in too as part of this exercise, please. That would make it user friendly by making content easy to find.

**Comment by cdrage** [comment]
Not a problem! When the docs are written @Preeticp we can sync them to the directory. Unfortunately we have to do it manually for now.
