### ISSUE TITLE
URL describe under experimental mode should work for both routes and ingresses

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#3182]
/kind bug

This bug is due to the new change for adding support for routes under experimental mode. 
The current logic for `list` and `describe` only search for ingresses if experimental mode is turned on. An expected bug, need to modify the logic. 
  
## How did you run odo exactly?
With experimental mode set, create a route UR
Run `url describe <route url>`

## Actual behavior
`url describe <route url>` complains the URL does not exist

## Expected behavior
`url describe` should be able to look for routes as well in experimental mode

**Comment by johnmcollier** [comment]
@yangcao77 I think this is the same issue as https://github.com/openshift/odo/issues/2985?

**Comment by yangcao77** [comment]
@johnmcollier Yes. #2985 is part of this issue, the issue should also include the change for `odo describe`

**Comment by yangcao77** [comment]
Actually I will convert this issue for `url describe` only. So we have separate issues for these two different commands.

**Comment by yangcao77** [comment]
Blocked by: https://github.com/openshift/odo/pull/3160
/statue blocked

**Comment by yangcao77** [comment]
/area devfile
Adding devfile label since it's for experimental mode. but it's not restricted to devfile component.
