### ISSUE TITLE
odo v2 - CLI overhaul  and dropping old style components support

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3190]
As we are adding more support for Devfiles it is getting increasingly hard to support both old s2i based components and new devfile way of doing things with the same CLI commands and flags.
This will get even more complex with devfile v2.
Problem is that we are trying to fit new Devfile workflow into old CLI commands that were designed with slightly different flow in mind. For example, one rule that we had was that the user should be able to do anything without editing YAML files. Due to Devfile complexity, it won't be possible to have commands for modifying every single aspect of a Devfile. We might try to cover some easy and most common situations,  but for anything beyond that users will have to go and modify the devfile.yaml manually. 

**Release of odo v2 is a good opportunity to do a small odo CLI overhaul and drop old s2i component support.**
We will provide a convertion tool for existing users to convert their old-style components to Devfiles (https://github.com/openshift/odo/issues/3156)

A few CLI updates that I can currently think of:
- update odo commands and terminology to be aligned with devfile, mainly use of "component" term. We need to figure out the details.
- in `odo create <component_type> [component_name] [flags]`  we should remove optional argument `[component_name]` making it flag `--name` and making first positional argument `[component_type]` optional.
- removing `odo storage` commands for now, as they will need big changes. Users will have to modify devfile.yaml directly to add or remove storage.

Some of the problems that we currently face with supporting both old-style and devfile components:
- odo terminology (mainly components) https://github.com/openshift/odo/issues/3076
- use of positional arguments https://github.com/openshift/odo/pull/3118#issuecomment-628573932
- odo storage will need additional flags to make it possible to use with devfile based components (no created issue yet)
- plus many bugs that we have just due to the complexity of supporting both

**Comment by GeekArthur** [comment]
One small point should be mentioned under this issue, when we work on the CLI overhaul, we can handle the use case "overwriting existing resource" properly such as
- Create component with `--devfile` when devfile is present
- Create URL when URL is present

Currently we error out and let users manually remove those existing resources, better option would be prompt and help users overwrite automatically or do nothing depends on users choice.

**Comment by dharmit** [comment]
> one rule that we had was that the user should be able to do anything without editing YAML files. Due to Devfile complexity, it won't be possible to have commands for modifying every single aspect of a Devfile.

That is a really good that we had in odo. That principle guided everything we did!

Mine is going to be an unpopular opinion but if devfile is so complex that user will have to touch the yaml, we're setting up ourselves for failure in long-term. The rule of not touching YAML was odo's rule, not s2i's rule! It should stay as-is irrespective of s2i or devfile v1 or devfile v2, IMO. 

IIUC, yaml comes in the way of developers who care only about deploying their code to a k8s cluster. If moving to devfile means that they have to deal with the yaml mess, then it's not worth it, IMO.

> removing odo storage commands for now, as they will need big changes. Users will have to modify devfile.yaml directly to add or remove storage.

Since we've mentioned "for now", we will be eventually adding the functionality back to odo cli, right?

> plus many bugs that we have just due to the complexity of supporting both

Is it possible that we let the user know that the functionality they're trying to use is not available with s2i based components and they must use devfile based component if they want to use xyz feature? That could reduce complexity by a bit?

**Comment by kadel** [comment]
> Mine is going to be an unpopular opinion but if devfile is so complex that user will have to touch the yaml, we're setting up ourselves for failure in long-term. The rule of not touching YAML was odo's rule, not s2i's rule! It should stay as-is irrespective of s2i or devfile v1 or devfile v2, IMO.
> 
> IIUC, yaml comes in the way of developers who care only about deploying their code to a k8s cluster. If moving to devfile means that they have to deal with the yaml mess, then it's not worth it, IMO.

Thanks to the parent system in devfile v2 most of the users shouldn't need to touch Devfile at all, and even if they need to change something thanks to the inheritance system they will just edit really small Devfile. Most of the heavy lifting will be in parent Devfile, which normal users shouldn't need to touch.



> > removing odo storage commands for now, as they will need big changes. Users will have to modify devfile.yaml directly to add or remove storage.
> 
> Since we've mentioned "for now", we will be eventually adding the functionality back to odo cli, right?

yes



> > plus many bugs that we have just due to the complexity of supporting both
> 
> Is it possible that we let the user know that the functionality they're trying to use is not available with s2i based components and they must use devfile based component if they want to use xyz feature? That could reduce complexity by a bit?

I don't think that that would help much :/ The code will be still present, and because some of the function calls are shared there is still a big chance of breaking something.

If someone is still dependent on old s2i based component definition they will still have an option to not upgrade or convert to devfile (#3156 )

**Comment by dharmit** [comment]
@kadel as we discussed, we might want to break this issue into individual issues to brainstorm:
* How should s2i based components be supported in odo v2?
  * Should we convert `.odo/config.yaml` to `devfile.yaml`?
  * Should we read `.odo/config.yaml` and convert it into devfil structs on the fly each time?
* CLI overhaul to discuss what commands could be possibly removed/modified from odo v1.
* Discuss what could be sane defaults for complex features (eg: storge). This would be helpful for the application devs who don't want to get into complexities but still want to use the powerful features provided by devfile. For the users who would like to really touch the yaml, point them to appropriate documentation on odo or devfile side.

**Comment by kadel** [comment]
Let's postpone this big change for later. We don't have enough time to properly design and implement this in time for v2
