### ISSUE TITLE
Release changelog includes rotten issues

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#3192]
/kind bug

This is a nit, but I noticed that the 1.2.1 release report [1] includes issues that were closed due to inactivity (e.g. [2]) as  'New features'. Don't know if there's a quick/easy way to exclude these.

[1] https://github.com/openshift/odo/releases/tag/v1.2.1
[2] https://github.com/openshift/odo/issues/2464

**Comment by GeekArthur** [comment]
@cdrage Please take a look.

**Comment by kadel** [comment]
I've been discussing with @cdrage that we should probably change the changelog format. Currently, it is autogenerated is of the issues and PRs closed in between there releases. 
Not sure if it is just me, but I don't find the current format that useful. If I want to check PRs that were merged I can easily query PRs on GitHub or check git log.

It might be good if we start generating separate Release Notes and Changelog.

The **changelog** can be autogenerated similarly to what we are currently doing (+ fixing the problem of the rotten issue).

**Release Notes**  would be more focused on what is interesting for odo users. I would break it into the sections like  "Breaking changes", "New Features", "Bugfixes" and provide an additional explanation for each item.  We can easily skip anything that is not visible to users like tests or internal code refactoring.

A changelog could live in a file in our repo. Release Notes could be published on a GitHub release page.

**Comment by cdrage** [comment]
Thanks. I'll coordinate with @boczkowska as we currently have release notes downstream (that we make manually). But not upstream.

I agree with @kadel that we should differentiate between Changelog and Release Notes. 

For example, in our new releases, we should include a short demo on a new feature that was added, etc.
