### ISSUE TITLE
odo should allows user to customize project deletion timeout

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3199]
## User Story
As a user I want to be able to customize project deletion timeout so that I can wait for longer/shorter time for a project to be deleted. Current default of 3 minutes is not configurable. 

As a user, I might want longer timeout for slower/latent connection or for a project that's got large number of resources (services, components, etc.) started within it. I might want a shorter timeout for quicker feedback since I'm working on an air-gapped environment.

## Acceptance Criteria 
- [ ] `odo preference` command should have the feature to set/unset the project deletion timeout

## Links 
- Related issue: #1884, #2397
- _Originally discussed in PR review at https://github.com/openshift/odo/pull/2397#discussion_r420573695._

/kind user-story
/kind discussion
/area project

**Comment by girishramnani** [comment]
We have alot of times, I cannot keep track of them. We need to generalise this to a timeout that already exists - by renaming an existing timeout if need be

**Comment by dharmit** [comment]
> Current default of 3 minutes is not configurable.

Thinking out loud - 3 minutes should be enough for most environments. Closing this since it hasn't come up as a concern from anyone yet. Re-open if it becomes relevant at some point.

/close
