### ISSUE TITLE
odo describe for a component does not lists down all the ports if a url is already created

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#3201]
/kind bug

## What versions of software are you using?
odo 1.2.1

**Operating System:** 

**Output of `odo version`:**
```
bash-3.2$ "/Users/mohitsuman/Projects/vscode-openshift-tools/out/tools/darwin/odo" version
odo v1.2.1 (b7b7c2fac)
Server: https://api.crc.testing:6443
Kubernetes: v1.14.6+b294fe5
```

# How did you run odo exactly?
1. Create a URL from IDE and select the port(if the component has multiple ports)
2. Create a new URL second time, here the `odo describe -ojson` output for a component doesn't list down all the ports available for the component, the ports object just has the entry of the port selected in Step 1.

## Actual behavior
Step 1:  For a given component: `odo describe -ojson` lists all ports available for the component
<img width="769" alt="Screenshot 2020-05-18 at 6 07 45 PM" src="https://user-images.githubusercontent.com/3133356/82214741-eace6c80-9933-11ea-9622-c376a1dcace3.png">

Step 2: For the same component: `odo describe -ojson` only lists the port selected in Step1. It does not list all ports.
<img width="799" alt="Screenshot 2020-05-18 at 6 12 38 PM" src="https://user-images.githubusercontent.com/3133356/82214946-35e87f80-9934-11ea-92de-382ed819b194.png">

## Expected behavior

Whenever we run `odo describe -ojson` for a component , all the ports available to a component should be listed down.

Repo used for reference: Java component: https://github.com/spring-projects/spring-petclinic

**Comment by mohitsuman** [comment]
@girishramnani @kadel This issue will be a blocker for vscode OpenShift Connector.

**Comment by dgolovin** [comment]
@kadel this is clearly a mistake introduced by this commit https://github.com/openshift/odo/commit/bd48c525407e8c877c0a4beb8165e8542dadf232.

**Comment by dharmit** [comment]
> @kadel this is clearly a mistake introduced by this commit [bd48c52](https://github.com/openshift/odo/commit/bd48c525407e8c877c0a4beb8165e8542dadf232).

My bad! I'm sorry that this broke json output. :disappointed:
