### ISSUE TITLE
Sync test script code for KUBECONFIG related operation on prow

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3203]
/kind feature
/kind code-refactoring

## Which functionality do you think we should add?

kubectl will prevent multiple concurrent writes to the configuration file: it uses a config.lock file and if the lock exists then changes to the configuration file are prevented which has been fixed in the pr https://github.com/openshift/odo/pull/3041. 

Now to make the test code in the same logic need to be implemented for OpenShift cluster, however it does not looks straight forward when running it on **prow**. I can see different type of failure even after implementing the suggestion given on pr https://github.com/openshift/odo/pull/3041. So i am creating a separate issue make the code in sync for both OpenShift and Kubernetes cluster type.

NOTE: Our existing test code is not broken, actually the --project flag which is saving us from the failure against multiple concurrent writes to the KUBECONFIG configuration file.

Discussion thread - https://github.com/openshift/odo/pull/3041#discussion_r420708872

## Why is this needed?
Code refactoring and ofcourse syncing of test code for OpenShift and Kubernetes cluster type.

**Comment by prietyc123** [comment]
I have tried out multiple fixes but It seems something fishy happening on prow. @kadel has also given some suggestions on this in [comment](https://github.com/openshift/odo/pull/3041#discussion_r425834514) but it again leads to [failure](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3041/pull-ci-openshift-odo-master-v4.2-integration-e2e/450#1:build-log.txt%3A5178)

Again I can see the [KUBECONFIG](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3041/pull-ci-openshift-odo-master-v4.2-integration-e2e/440#1:build-log.txt%3A44) file exported from `/tmp/admin.kubeconfig` on prow and I tried hardcoding the path just to check where it is getting stuck. Again some [failure](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3041/pull-ci-openshift-odo-master-v4.2-integration-e2e/440#1:build-log.txt%3A507)

In both the cases I observed `KUBECONFIG` gets copied and set to the temporary config but I am not sure about the behavior of the test. Though our tests are working as expected on travis CI with both kubernetes and openshift cluster. So, It should not be the test related problem. I suspect this could be infra related issue. 

Anyway I am going to do a workaround in separate pr in this sprint.

**Comment by kadel** [comment]
> I have tried out multiple fixes but It seems something fishy happening on prow. @kadel has also given some suggestions on this in [comment](https://github.com/openshift/odo/pull/3041#discussion_r425834514) but it also leads to [failure](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3041/pull-ci-openshift-odo-master-v4.2-integration-e2e/450#1:build-log.txt%3A5178)

It doesn't look like that the failures in this log are due to `KUBECONFIG`.
I see the same failures even in other PRs (https://github.com/openshift/odo/pull/3204)

**Comment by amitkrout** [comment]
closing it on behalf of https://github.com/openshift/odo/pull/3221.
