### ISSUE TITLE
Remove wrong reference from create command UX

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#3215]
/kind documentation

## What mistake did you find / what is missing in the documentation?
The [Documentation](https://docs.openshift.com/online/starter/cli_reference/openshift_developer_cli/odo-cli-reference.html#create) this contains a wrong reference in example portion like https://github.com/openshift/odo/blob/master/docs/examples.adoc  

This [example](https://github.com/openshift/odo/blob/master/docs/examples.adoc) says `no such file present` 

## What is the relevance of it?
Wrong reference may create bad user experience.

**Comment by girishramnani** [comment]
@anandrkskd can you please work on this?

**Comment by cdrage** [comment]
https://github.com/openshift/openshift-docs/pull/23982 has been merged. Closing.
