### ISSUE TITLE
Interactive mode for `odo create` with experimental mode should populate default namespace

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3222]
/kind bug

## How did you run odo exactly?

```sh
▶ odo create
Experimental mode is enabled, use at your own risk

? Which devfile component type do you wish to create java-spring-boot
? What do you wish to name the new devfile component java-spring-boot
? What namespace do you want the devfile component to be created in 
```

## Actual behavior

When using `odo create` in interactive mode with experimental enabled. It asks for the namespace, but in reality, we should populate it with a default value (the current namespace)

## Expected behavior

Populate with the default namespace.

## Any logs, error output, etc?

N/A

**Comment by GeekArthur** [comment]
I think we already support default namespace (currently active namespace) in interactive mode, by design in interactive mode, we provide an option to let user specify namespace, but if user doesn't want to specify namespace `odo create` will uses the currently active namespace as namespace.

Below is the UI of specifying namespace in interactive mode
```
? What namespace do you want the devfile component to be created in (default)
```
We display the currently active namespace which is `default` to user, user can either specify namespace or use the currently active namespace directly by hitting the _enter_ key.

**Comment by cdrage** [comment]
@GeekArthur What version are you trying against? 

This does not actually populate for me, see below:


```sh
~/openshift/springboot-ex  master ✔                                                                                                                                            125d  
▶ odo create     
Experimental mode is enabled, use at your own risk

? Which devfile component type do you wish to create java-spring-boot
? What do you wish to name the new devfile component java-spring-boot
? What namespace do you want the devfile component to be created in 
```

**Comment by GeekArthur** [comment]
That doesn't look right, I am using the latest master, you can check my gif below:

![Kapture 2020-05-20 at 11 33 36](https://user-images.githubusercontent.com/15131537/82466344-490f6280-9a8e-11ea-9081-613f19457ba2.gif)

I can see the default component name is pop up in your terminal, so can confirm there is no issue on your terminal configuration/environment.

I think I know why. Can you run `odo preference view` to check your `PushTarget`? One issue I can think of is if you set `PushTarget` to docker you might hit that weird issue as there is no default namespace (docker scenarios doesn't need cluster/namespace) but we still display that option to user, that's a known issue: https://github.com/openshift/odo/issues/2978

**Comment by GeekArthur** [comment]
@cdrage Let me know if the root cause is what I describe above, then we can prioritize the known issue or do more investigation.

**Comment by cdrage** [comment]
@GeekArthur Heck. You're right. It was set to Docker :(

I'm going to close this for now.
