### ISSUE TITLE
Use MatchAllInOutput instead of multilple assert statement

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3245]
/kind bug
/kind code-refactoring

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## Actual behavior

Using Multiple assert statement in https://github.com/openshift/odo/blob/master/tests/integration/operatorhub/cmd_service_test.go#L207-L208  instead of `MatchAllInOutput`

## Expected behavior
Use `MatchAllInOutput` for such scenarios.

**Comment by amitkrout** [comment]
Please find out all such occurrence in our test suite, so that it can be fixed in a single shoot.
