### ISSUE TITLE
filepath.Join("/tmp", randomFileName) does not support on windows

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3246]
/kind bug

## What versions of software are you using?

**Operating System:**
Windows

**Output of `odo version`:**
master

## How did you run odo exactly?
Running `filepath.Join("/tmp", randomFileName)` on windows.

## Actual behavior
`/tmp/randomFileName` throws error as `/tmp` won't be identified on windows.

## Expected behavior 
Defining `/tmp` in some context should work

**Comment by johnmcollier** [comment]
Can we safely use `os.TempDir()` in place of  that?

**Comment by amitkrout** [comment]
> Can we safely use `os.TempDir()` in place of that?

yes, we can do that
