### ISSUE TITLE
odo log for devfile component

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3260]
`odo log` command errors out when executed in directory with devfile component.

```
▶ odo log
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

`odo log` should show the stdout and stderr output of the main "run" command.

/kind bug
/priority high
/area devfile
/area devfilev2

**Comment by adisky** [comment]
two things needs to be done for `odo log`
- Get logs from the container, since it is already implemented for S2i component, a function to get logs is available in `occlient`, need to implement same for kclient
https://github.com/openshift/odo/blob/master/pkg/occlient/occlient.go#L2042

- From which container to get logs from, Discussed with @mik-dass on the approach he is
taking for `odo exec`, he suggested to determine run container from `devfile.yaml` and show log from there.
```
exec:
  id: "run app"
  commandLine: "/run-command.sh"
  group:
    - kind: run
    - isDefault: true
```

**Comment by kadel** [comment]
> * From which container to get logs , Discussed with @mik-dass on the approach he is

The logs should be shown form the container where the "run" command is executed.

**Comment by adisky** [comment]
> > * From which container to get logs , Discussed with @mik-dass on the approach he is
> 
> The logs should be shown form the container where the "run" command is executed.

 i wanted to say here how to get the information about the container where "run" command is executed.

**Comment by dharmit** [comment]
RE: discussion about adding support for debug phase.

Is the debug phase different from `odo debug` as far as devfile v2 components are concerned? The reason I'm asking this is because for s2i components, AFAIK, `odo debug` is a long running task that prints logs to stdout automatically, no?

**Comment by adisky** [comment]
@dharmit I am not aware how it is handled for s2i based components, AFAIK for devfile debug phase is similar as run phase handled by supervisord, @tkral Please correct me if i am wrong here

**Comment by adisky** [comment]
if user wants to see log for debug container(I think it is possible that run and debug have different component), then how it should be handle for `odo log`

`odo log --debug`
   or
 use only  `odo log`, if run container not found then fallback to debug to container?
