### ISSUE TITLE
Add support for starterProjects in v2 devfiles

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3263]
/kind user-story

## User Story
As a user, I want to be able to select a starter project when running `odo create` and have odo pull down that project's source code for use. I should also be able to select the starter code with the `--starter` flag (replacing the current `--downloadSource` flag)

## Acceptance Criteria 
- [x] The devfile parser should be updated to support the `starterProjects` field
- [x] It should allow the user to select a project when running `odo create`.
- [x] The user should be able to pick from multiple starter projects, if they are present

## Links 
https://github.com/devfile/kubernetes-api/issues/42

Originally discussed in https://github.com/openshift/odo/pull/3216. As `starterProjects` is not yet part of the devfile v2 schema (though it has been agreed to, see https://github.com/devfile/kubernetes-api/issues/42), it was left out of the initial devfile-v2 implementation in odo.

/kind user-story
/area devfileV2

**Comment by kadel** [comment]
> We will also want to think how we handle sync as part of this story. Currently, if there is a single project defined in the devfile, we sync to `/projects/<projectName>`, otherwise we sync to `/projects`.
> We need to think about how the `starterProjects` field will affect that, and where the code should get synced to when there are starter projects defined in a devfile.

My understanding is that the  `starterProject` is just a template of a project.
If I run `odo create devfile --downloadSource` the starter project from the devfile should get downloaded to the current directory. This is the only place and operation where the starterProject would be used.
btw: we should probably rename `--downloadSource` to something more fitting like `--starter`

Then the file syncing process only depends on `projects` definition in a devfile and it should use the logic that you described. 
But the `starterProject` shouldn't have any effect on the file syncing, it is just used to populate the local directory so users can easily start a new project.

**Comment by kadel** [comment]
`starterProject` field is getting added to devfile v2 spec and schema here https://github.com/devfile/kubernetes-api/pull/

**Comment by adisky** [comment]
Things need to be done to support starter projects.

[ ] schema update (After this one gets merged) devfile/kubernetes-api#92
[ ] if --starter flag is specified download the first project
[ ] user can specify starter project name `--starter <starter-project-name>`, downloads that project
[ ] should list the `starterProjects` in interactive mode and user should be able to pick one of them
[ ] starter projects have different behavior than projects in terms of cloning the repo
https://github.com/devfile/kubernetes-api/issues/42#issuecomment-627490849
[ ] syncing mechanism needs to be updated for starter projects, sync them to `CHE_PROJECTS_ROOT` or `/projects`

**Comment by adisky** [comment]
@kadel @johnmcollier Most things we are already doing for `projects`, git cloning mechanism and file sync path needs to be changed. 

I have a question what we need to do about projects then? how we could download them?

**Comment by kadel** [comment]
> * [x]  schema update (After this one gets merged) [devfile/kubernetes-api#92](https://github.com/devfile/kubernetes-api/pull/92)
> *

this one is merged

**Comment by adisky** [comment]
@kadel currently we are doing source syncing as
if `SourceMapping` is set in a container component, we are syncing it there.
if `SourceMapping` is not set we are syncing to 
- `/projects`
- `/projects/project-name` (This option needs to be removed for starter projects)
- `/projects/clone-path` (what about this one?)

I am little confused here about `clonePath`

**Comment by adisky** [comment]
@johnmcollier @kadel for asking about starter projects in interactive, the devfile is downloaded first then parsed then we can list starter projects, it looks like this
```
[adisky@localhost check-interactive]$ odo create 
Experimental mode is enabled, use at your own risk

? Which devfile component type do you wish to create java-maven
? What do you wish to name the new devfile component java-maven
? What namespace do you want the devfile component to be created in default
Validation
 ✓  Checking devfile existence [165582ns]
 ✓  Checking devfile compatibility [273716ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [295812ns]
 ✓  Validating devfile component [460221ns]
? Do you want to download starter projects
? Which starter project you want to download
> starter-project1
> starter-project2
```
Is this fine?

**Comment by johnmcollier** [comment]
@adisky Looks good to me

**Comment by kadel** [comment]
> @kadel currently we are doing source syncing as
> 
> if `SourceMapping` is set in a container component, we are syncing it there.
> 
> * `/sourceMapping`
> 
> if `SourceMapping` is not set we are syncing to
> 
> * `/projects`
> * `/projects/project-name` (This option needs to be removed for starter projects)
> * `/projects/clone-path` (what about this one?)
> 
> I am little confused here about `clonePath`

@adisky `sourceMapping` has no relationship to starterProject. 

starterProject should simply be downloaded into the current directory. If `clonePath` path is specified it the starter project should be downloaded into that directory.


If starterProject contains `clonePath: frontend`
Than `odo create --starter` should download start project source into `./frontend`

**Comment by adisky** [comment]
@kadel We cannot have different syncing mechanism for `starterProjects` and `local source code`, as `odo push` does not know what it is syncing, it syncs everything from local context dir.

**Comment by kadel** [comment]
> problem is during `odo push` how we will judge it is `starterProject` or user's local source code?

`odo push` should not do anything with `starterProject`.
The only time when you use `startProject` is with `odo create`

**Comment by adisky** [comment]
as discussed with @kadel on bjns, for `starterProjects` and innerloop scenerios, `clonePath` specifies the local directory(relative to context dir) in which the `starterProject` should be downloaded, it is meant to be specify the download dir not syncing dir to container. It would be useful in scenarios when we download multiple projects.
