### ISSUE TITLE
Porting template based test to Multi Stage testing

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3270]
/kind user-story

## User Story
As a user, I want to be able to use the `custom credential` features for multi-stage tests. So that I can get all the support of the feature added in [issue](https://issues.redhat.com/browse/DPTP-988). 

## Acceptance Criteria 
- [x] Our test should be multi-stage and run on prow
- [x] It should be able to use `custom credential` features for multi-stage testing on OpenShift CI.

## Links 

Currently we are running [template based test](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml#L15-L21) due to which not able to get the `custom credential` for [issue](https://github.com/openshift/odo/issues/2537). Possible approach has been discussed in [comment](https://github.com/openshift/odo/issues/2537#issuecomment-635941209)

/kind user-story
/kind test

**Comment by amitkrout** [comment]
cc_ @petr-muller

**Comment by prietyc123** [comment]
In [template based test](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml#L15-L21) lot of environment variable is not accessible, so moving our test to multi-stage.

Things need to be done here :

1. Use `ipi-aws` [workflow](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/workflow/ipi-aws)
2. Add Custom steps to run [odo tests](https://github.com/openshift/odo/blob/master/scripts/openshiftci-presubmit-all-tests.sh) in [`ci-operator config file`](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/).
3. Extract the mounted [secret](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml#L20-L21)

Not sure about the mounted secret whether the same volume mount will work for multi-stage also.  We may need to do some work around this. cc_ @amitkrout @mohammedzee1000

**Comment by prietyc123** [comment]
Facing permission issue with our [current config](https://github.com/openshift/odo/blob/master/openshift-ci/build-root/Dockerfile#L3) `error: failed to copy secret mount: open /tmp/secret/kubeconfig: permission denied`

Opened a pr which may fix it https://github.com/openshift/odo/pull/3290

**Comment by prietyc123** [comment]
It seems in the multi-state test structure oc binary is not copied in the test container https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9431/rehearse-9431-pull-ci-openshift-odo-master-v4.2-integration-e2e-steps/8#1:build-log.txt%3A61 . Ideally it should be copied by default but not sure why this weird is happening. @mohammedzee1000 can you please share your thought on this?

**Comment by mohammedzee1000** [comment]
@openshift/openshift-team-developer-productivity-platform ^

**Comment by thrasher-redhat** [comment]
I think you may want @openshift/openshift-team-developer-productivity-test-platform

**Comment by petr-muller** [comment]
Providing `oc` to multi-steps automatically is https://issues.redhat.com/browse/DPTP-1242, not yet delivered. Currently it's possible to include `oc` in an image by building a new image and only adding `oc` to it, like people are doing it e.g. [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml#L12-L20).

**Comment by prietyc123** [comment]
Added `oc` binary to the test container `bin` path in pr https://github.com/openshift/odo/pull/3351

**Comment by prietyc123** [comment]
This issue is blocked on copying `oc` binary to the `bin` path of build image. There is one pr on this https://github.com/openshift/odo/pull/3362. Once it gets merged expecting I can proceed with this.

**Comment by prietyc123** [comment]
As per the last slack discussion i need another dockerfile to inject `oc` in test container path.  It seems shell script approach doesn't work.

**Comment by kadel** [comment]
> As per the last slack discussion i need another dockerfile to inject `oc` in test container path. It seems shell script approach doesn't work. Once this is done it is likely to get migrated into multistage but again I am not sure about the uncertainty of the issue.

Can you provide more info on this. Why we need another Dockerfile just with `oc`?

**Comment by amitkrout** [comment]
> > As per the last slack discussion i need another dockerfile to inject `oc` in test container path. It seems shell script approach doesn't work. Once this is done it is likely to get migrated into multistage but again I am not sure about the uncertainty of the issue.
> 
> Can you provide more info on this. Why we need another Dockerfile just with `oc`?

@kadel Unlike other project we tried a nice and simple shell script workaround to inject oc binary to the test container path but unfortunately it did not work for a reason which even surprises @petr-muller from platform team. We should not spend more time on it to debug as this is a workaround ,so we can follow the same way like other project has been done it through another Dockerfile instead. For example - https://github.com/openshift-knative/serverless-operator/tree/6805a2d1b560dbc6955ad1d4aa9686f5d8f8a9c8/openshift/ci-operator.    

NOTE: oc binary auto injection feature is not delivered yet.

**Comment by petr-muller** [comment]
> @kadel Unlike other project we tried a nice and simple shell script workaround to inject oc binary to the test container path but unfortunately it did not work for a reason which even surprises @petr-muller from platform team.

Not just that, but also Build API team was not able to help... :/

**Comment by prietyc123** [comment]
After banging head a lot `oc` got injected to the multi-stage 😀 But here comes the new challenge, now facing permission issue with `KUBECONFIG` Failure : https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9431/rehearse-9431-periodic-ci-openshift-odo-master-v4.2-integration-e2e-periodic-steps/1277932938616377344#1:build-log.txt%3A68

Due to this permission issue we are not able to change the current namespace for operatorhub `oc new-project ci-operator-hub-project`. So, there is a workaround for this. 

Workaround:
1. Need to copy the `KUBECONFIG` file to some temporary file
2. Give Read and Write permission and use it.

**Comment by prietyc123** [comment]
pr https://github.com/openshift/odo/pull/3462 is a fix for https://github.com/openshift/odo/issues/3270#issuecomment-651838728

**Comment by prietyc123** [comment]
Facing some weird behaviour of kubeconfig on openshift release repo. Issue tracked https://github.com/openshift/odo/issues/3501

**Comment by prietyc123** [comment]
I am observing cluster specific issue https://github.com/openshift/odo/issues/3547 and till now I can see it is purely specific to 4.5 cluster. None of the time I have seen it passing on 4.5 and also did not get this failure on any of other cluster. Failure logs can been seen https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/pr-history/?org=openshift&repo=release&pr=9431

**Comment by prietyc123** [comment]
Blocked on #3547 due to [comment](https://github.com/openshift/odo/issues/3547#issuecomment-660114118) . Completely new to me and I need to debug more for the solution.

**Comment by prietyc123** [comment]
Multistage pr https://github.com/openshift/release/pull/9431 already merge. So closing this issue.

/close
