### ISSUE TITLE
Add integration test part of odo brew build

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3275]
https://issues.redhat.com/browse/ODO-25

**Comment by amitkrout** [comment]
ping @prietyc123 @mohammedzee1000

**Comment by amitkrout** [comment]
Right now we are not verifying the odo bits just after building it in our internal system (brew build). So need to attach the integration test step to make sure the the bits works fine without manual intervention.

The release process will be done in 3 steps.
1. brew build
2. integration test
3. Publish (Only if integration test is passed)

**Comment by amitkrout** [comment]
will be fixed part of - https://github.com/openshift/odo/issues/3276

**Comment by mohammedzee1000** [comment]
I think this should be done once the new pipelines are up honestly
#3276
