### ISSUE TITLE
Migrate odo product under new openshift developer tools and services product

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#3276]
/kind feature
See https://issues.redhat.com/browse/ODO-24

This involves:

- [x] setup new internal build pipelines
- [x] update internal release scripts and docs

Stretch

- [x] Setup internal tests for the builds (currently internal builds are only tested manually)

**Comment by dharmit** [comment]
We have most things in place (dist-git, bugzilla). @mohammedzee1000 needs to verify things and test the scripts. On-track to close this in Sprint 186.

**Comment by mohammedzee1000** [comment]
Internal things are now functional. We will need to do full release before complete verification

**Comment by mohammedzee1000** [comment]
Now all that remains to do a full release.

Also I'm already working on a script that will act as entry point on internal testing

**Comment by mohammedzee1000** [comment]
I think this task is done. CVP tests are a stretch goal, they are being worked on and we can use a separate issue to track that.

As I said, a full release is needed, but it should work as normal

**Comment by mohammedzee1000** [comment]
Migration complete, furthur testing will need using cpaas, which can be tracked seperately

**Comment by mohammedzee1000** [comment]
Once we can do a full release using the new route, lets close this
