### ISSUE TITLE
Wrong error formatting in devfile

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3280]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

```
$ odo push

Validation
 ✗  Validating the devfile [35201ns]
 ✗  Failed to start component with name nodejs.
Error: Failed to create the component: failed to validate devfile build and run commands: 
The command "devbuild" was found but its actions are not supported: Problem with command "devbuild" action #1: Actions must be of type "exec"%!!(MISSING)(EXTRA string=
)
```

## Actual behavior
if an invalid action is specified, the error is `Actions must be of type "exec"%!!(MISSING)(EXTRA string=)`, the error formatting is wrong, same applies to all other validation errors.

## Expected behavior
error should be `actions must be of type exec`

**Comment by maysunfaisal** [comment]
can be closed, fixed by https://github.com/openshift/odo/pull/3291
