### ISSUE TITLE
Support application testing defined in the devfile v2

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3284]
/kind user-story

## User Story
As a user, I want to test my application using the test defined in a devfile.  Devfile 2.0 supports defining commands belongs to the `test` group (https://github.com/devfile/kubernetes-api/issues/27). The test command will be used for running automated testing on the application.

## Acceptance Criteria 
- [ ] `odo test` will run test command (command belongs to the `test` group) specified in the command that belongs to the group `test` defined in the devfile
- [ ] odo uses this logic to decide which test command to run on `odo test`:
    - if only one test command is define, use that command regardless of whether that command with isDefault is set to true or not.
    - if more than one test command, execute the one with `isDefault` set to true
    -`odo test --test-command <command name>` will execute the command with the given command name regardless of a default test command is defined or not.
   - if more than one test command but no default is defined, error out if `--test-command` is not use.

## Links 

/kind user-story
/area devfile

**Comment by yangcao77** [comment]
blocked by: https://github.com/openshift/odo/pull/3291 
requires the code for command group validation to be merged

**Comment by cdrage** [comment]
ping @girishramnani @kadel @dharmit should we discuss this a bit more before we merge the PR?

**Comment by kadel** [comment]
> ping @girishramnani @kadel @dharmit should we discuss this a bit more before we merge the PR?

@cdrage is there anything specific that you want to discuss?

**Comment by cdrage** [comment]
@kadel Nope, just wanted to make sure that there is a clear consensus on getting this merged in since I didn't see any discussion.

But I think this command is great in order to test the commands
