### ISSUE TITLE
Refactor Devfile Validation

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3285]
/kind cleanup
/kind code-refactoring

Currently we are doing devfile validation at two places in odo
https://github.com/openshift/odo/tree/master/pkg/devfile/validate
https://github.com/openshift/odo/blob/master/pkg/devfile/adapters/common/command.go#L91

This should be refactored, validation should happen at a single place, followup issue from review comments in devfile V2 PR
https://github.com/openshift/odo/pull/3216#discussion_r432071154
https://github.com/openshift/odo/pull/3216#issuecomment-637560498

**Comment by johnmcollier** [comment]
We discussed this yesterday too, and we also suggested that the devfile validation occur in the `Validate()` function of each command that requires it (rather than within `Run()` as it is today)

**Comment by maysunfaisal** [comment]
There are three validations being done:
1. Validation with schema - done on every odo commands
2. Validation of components - done only on odo create
3. Validation of commands - done only on odo push

I agree that we can refactor these and move them to `Validate()`

For example, schema and component validation can be done for every odo command unless the odo command does not need to work on components. Odo push can have schema, component and command validation.

**Comment by adisky** [comment]
/close
as refactoring has been done as part of some other issue, and we are moving out validation to library.
