### ISSUE TITLE
Verify devfile command test script on a windows host

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3288]
/kind user-story

## User Story
As a tester/developer I want to run my devfile test script on windows platform to verify the existing test against Win platform. Actually it will boost the issue https://github.com/openshift/odo/issues/2540 by fixing any windows specific issue.  

## Acceptance Criteria 
- [x] Each devfile test should pass on windows platform on Powershell and Cygwin
- [x] Create issues for all the failures observed

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by amitkrout** [comment]
We have a win10 box available on PSI, we can use that for test verification purpose.

**Comment by prietyc123** [comment]
To achieve the acceptance criteria we need:

A cluster setup (we already own that)
Win10 setup (we have one running on our PSI Openstack Platform)
Configuration on Win10 to run odo test
Running the test script individually and Find out the bugs, label it properly.
Example:

- [ ] make test-cmd-devfile-push

Note : We can fix those issues accordingly but not as part of this issue.

**Comment by girishramnani** [comment]
We have a windows 10 VM @amitkrout right?

**Comment by amitkrout** [comment]
> We have a windows 10 VM @amitkrout right?

yes

**Comment by prietyc123** [comment]
Devfile test verification individually 

- [x] make test-cmd-devfile-catalog

**Comment by prietyc123** [comment]
Full test run on powershell is completed. Still needs to verify on Cygwin terminal.

**Comment by prietyc123** [comment]
I need to verify all the test on windows with 3.x cluster. For which I need to do below tasks.

Steps :

1. Setup Minishift single node cluster on windows VM

or

1. We can use [3.11 cluster](https://gitlab.cee.redhat.com/openshiftdo/PSI#known-clusters) which is on PSI but need to explore on DNS configuration part for windows. Which is unknown currently 

2. Run all the test individually like https://github.com/openshift/odo/issues/3288#issuecomment-644565271

3. Also 1-2 test should be verified on cygwin

**Comment by prietyc123** [comment]
Running test on windows 3.11 cluster:

- [x] make test-cmd-devfile-url https://github.com/openshift/odo/issues/3527

**Comment by prietyc123** [comment]
I have covered all the issues related to windows for devfile tests. So closing this issue.

/close
