### ISSUE TITLE
Verify regular command test script on a windows host

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3289]
/kind user-story

## User Story
As a tester/developer I want to run my regular command test script on windows platform to verify the existing test against Win platform. Actually it will boost the issue #2540 by fixing any windows specific issue.

## Acceptance Criteria 
- [x] Each regular command test should be run on windows platform on powershell and cygwin
- [x] Create regular command issues for failing tests

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by amitkrout** [comment]
We have a win10 box available on PSI, we can use that for test verification purpose.

**Comment by prietyc123** [comment]
To achieve the acceptance criteria we need:

1. A cluster setup (we already own that)
2. Win10 setup (we have one running on our PSI Openstack Platform)
3. Configuration on Win10 to run odo test
4. Running the test script individually and Find out the bugs, label it properly.

Example:
- [ ] make test-cmd-login-logout

Note : We can fix those issues accordingly but not as part of this issue.

**Comment by prietyc123** [comment]
Individual test verification on windows:

- [ ] make test-cmd-push  #3328

**Comment by girishramnani** [comment]
applies here https://github.com/openshift/odo/issues/3288#issuecomment-648785109

**Comment by prietyc123** [comment]
Running test on windows 3.11 cluster:

- [x] make test-cmd-service  https://github.com/openshift/odo/issues/3482

**Comment by kadel** [comment]
Where we are on automating running our tests on windows?

**Comment by amitkrout** [comment]
> Where we are on automating running our tests on windows?

@kadel We are blocked right now - https://github.com/openshift/odo/issues/2540#issuecomment-636791166. There is a WIP pr https://github.com/openshift/release/pull/9431 to unblock it.

/close
