### ISSUE TITLE
`odo catalog list components` fails if registry is not set up properly 

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#3297]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:**
Latest master

## How did you run odo exactly?
```
odo registry add Fake https://fake                                                                                      ✔  14:29:21 
New registry successfully added
odo catalog list components                                                                                             ✔  14:29:35 
 ⚠  Registry  is not set up properly with error: <nil>
 ✗  Get "https://fake/devfiles/index.json": dial tcp: lookup fake: no such host
```

## Actual behavior
`odo catalog list components` fails if registry is not set up properly.

## Expected behavior
We should use warning instead of error, because we need to support the case where user has multiple registries but only part of the registries is not set up properly, for that case we shouldn't block user from listing registry that is set up properly and listing s2i components. 

## Any logs, error output, etc?
N/A

## Special Notes:
This regression starts from this PR https://github.com/openshift/odo/pull/3112 gets merged, we need to do the following things to fix the issue:
1. Use warning instead of error for registry that is not set up properly
2. Display the registry name properly when throwing warning
3. Add tests to cover the case to avoid regression in the future

**Comment by johnmcollier** [comment]
I think there's a couple things that need to be done as part of this:
1) `odo catalog list` shouldn't error out if one of the registries is invalid or cannot be reached. A warning should be displayed instead
2) `odo registry add` should not allow users to add invalid registries.

**Comment by GeekArthur** [comment]
> 1. odo catalog list shouldn't error out if one of the registries is invalid or cannot be reached. A warning should be displayed instead

Do you mean `odo registry list` instead of `odo catalog list`? Because `odo catalog list` issue is already under this issue description. If you mean `odo registry list`, I think that error is unlikely as `odo registry add` already validates for the error so that the error won't be moved to `odo registry list`

> odo registry add should not allow users to add invalid registries.

We already have that validation in existing code base

**Comment by johnmcollier** [comment]
> Do you mean odo registry list instead of odo catalog list? Because odo catalog list issue is already under this issue description. If you mean odo registry list, I think that error is unlikely as odo registry add already validates for the error so that the error won't be moved to odo registry list

Yes, I mean `odo catalog list`

> We already have that validation in existing code base

We don't validate that the URL we're adding is valid or that the URL + `devfiles/index.json` is valid. I think an error should occur for the following (which it does not do today)
```
odo registry add Fake https://fake
```

**Comment by GeekArthur** [comment]
> > We already have that validation in existing code base
> 
> We only validate that what's being given to `odo registry add` is a url. We don't currently validate that the URL points to something or that the URL + `devfiles/index.json` points to something. I think an error should occur for the following (which it does not do today)
> 
> ```
> Johns-MacBook-Pro-3:odo johncollier$ odo registry add Fake https://Fake
> New registry successfully added
> ```

Yes, that behavior is expected and is by design. The design is that we divide the validation into two stages:
Early validation stage: Only validate URL basic format, happens when user adds registry URL
Validation stage: Validate URL accessibility, happens when user uses registry URL

That design is based on `yum-config-manager`, design proposal with details under this thread: https://github.com/openshift/odo/pull/2940#discussion_r417440866
