### ISSUE TITLE
Code coverage report does not work as expected

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3299]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## Actual behavior
`Codecov` report is not triggered in some of the prs like https://github.com/openshift/odo/pull/2913 

## Expected behavior
It should get triggered for all the prs

**Comment by girishramnani** [comment]
Yeah I mean at this point, we dont think its important at all as a metric.
