### ISSUE TITLE
On each release we should bundle the site into the source code release

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3302]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Charlie's notes (TO BE UPDATED LATER).

We should deliver the site odo.dev whenever we release so that we have a version of the docs from that particular date of release for users to look back to.

## What is the relevance of it?

Charlie's notes (TO BE UPDATED LATER).

**Comment by dharmit** [comment]
This still matters to us. We need to figure out a way to pack the `gh-pages` branch or just the part that's served when we do `jeyll serve` into a tar and make it available as a release artifact.

/area infra
