### ISSUE TITLE
Test odo interoperability support for upcoming OpenShift release

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3320]
/kind user-story
/kind test

## User Story
As a user I want to confirm the odo test runs for upcoming openshift release.

## Acceptance Criteria 
Run odo test against OpenShift cluster for all the supported versions `3.11, 4.2, 4.3, 4.4` along with platforms where OpenShift is also supported.

- [ ] different cloud deployments (GCP, Azure, or OSD)

- [ ] Upcoming versions of OpenShift like 4.5

## Links 
See : 
- Related issue: https://issues.redhat.com/browse/ODO-27

/kind user-story

**Comment by amitkrout** [comment]
@prietyc123 On AWS (Up coming ocp 4.5) and PSI (4.2 ocp version) platform we are covering interoperability support verification and rest of these platform we have not started yet. Need to figure out if there are such clusters running on those platform, we can just make use of that or else need to create our own.
