### ISSUE TITLE
Leverage RHOAR in `odo`

### ISSUE THREAD

**Issue by slemeur** [openshift/odo#333]
## Description
[RHOAR](https://developers.redhat.com/products/rhoar/overview/) provides application runtimes for OpenShift. Associated to the application runtimes, RHOAR provides a set of project templates which showcase how developers can use the application runtime for building fundamental blocks of cloud-native applications. (like creating RESTful APIs, implementing health checks, configmap or resiliency features like circuit breakers). . A complete experience is provided on https://developers.redhat.com/launch/.

Leveraging those application runtimes and project templates in `odo` would actually help developers to quickly bootstrap project (and new blocks of cloud native application), with an application runtime validated and productized by Red Hat offered through the [Red Hat Container Catalog](https://access.redhat.com/containers/). 

The goal of this epic is to define how RHOAR would be leveraged in `odo`

**Comment by cdrage** [comment]
I have a feeling we're moving away from RHOAR and into using operators / something custom.

Could we close this @dharmit / @slemeur / @kadel  ?

**Comment by girishramnani** [comment]
yeah we are moving away from RHOAR and we have a PR which removes them from supported list https://github.com/openshift/odo/pull/2729
