### ISSUE TITLE
Cache devfile registries to improve performance

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3330]
/kind user-story

## User Story
When discussing solutions about issue https://github.com/openshift/odo/issues/3249, we have identified that it would be better if we could cache the entire registry.

This will have a great performance benefit:
- `odo catalog` can just read the index.json locally
- `odo create` can use the devfile.yaml stored locally

Odo should have the capability to determine if registries needs to be pulled down again and refresh the local cache. Users should have the option to force refresh the local cache

## Acceptance Criteria 
- [ ] It should cache the devfile registries
- [ ] odo catalog and odo create should use the local cache if available
- [ ] odo should be able to determine if local cache needs to be refreshed and pull down registries
- [ ] odo should allow users to force refresh local cache

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

cc: @kadel @metacosm

**Comment by metacosm** [comment]
I'd argue, though, that it's not a user story… 😉

**Comment by gorkem** [comment]
@elsony we should have this in our radar

**Comment by kadel** [comment]
One part of this is already implemented. 
Odo already uses cache for index.json. But Devfiles are not cached.

**Comment by mik-dass** [comment]
> One part of this is already implemented.
> Odo already uses cache for index.json. But Devfiles are not cached.

I think currently devfiles are cached too.

**Comment by gorkem** [comment]
If everything is cached why is this open ? :)

**Comment by kadel** [comment]
someone forgot to close it 😇 
/close
