### ISSUE TITLE
PlatformAdapter interface seems redundant and should be removed

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#3333]
/kind bug

## What versions of software are you using?

**Operating System:** N/A

**Output of `odo version`:** N/A

## How did you run odo exactly?
N/A

## Actual behavior
N/A

## Expected behavior
N/A

## Any logs, error output, etc?
N/A

**Comment by girishramnani** [comment]
I am quite sure the title cannot be NA 😆

**Comment by EnriqueL8** [comment]
+1 on this
