### ISSUE TITLE
Lack of pullsecret which cause S2I build from authenticated registry can't pull image

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3335]
/kind bug

## What versions of software are you using?

**Operating System:**
Red Hat Enterprise Linux 8.2 (Ootpa)
**Output of `odo version`:**
odo v1.2.2 (b815649)
## How did you run odo exactly?
make test-cmd-cmp

## Expected behavior
In myproject , there is pullsecret with kind of dockerconfigjson

## Any logs, error output, etc?
```
[odo] Cloning "https://github.com/openshift/nodejs-ex" ...
[odo]         Commit:        a096bd299d65517cef8079f4559e9b0b9f97ff57 (Merge pull request #237 from bparees/nodejs12)
[odo]         Author:        Honza Horak <hhorak@redhat.com>
[odo]         Date:        Tue Mar 3 16:35:01 2020 +0100
[odo] Caching blobs under "/var/cache/blobs".
[odo] Warning: Pull failed, retrying in 5s ...
[odo] Warning: Pull failed, retrying in 5s ...
[odo] Warning: Pull failed, retrying in 5s ...
[odo] error: build error: After retrying 2 times, Pull image still failed due to error: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
[odo] I0609 12:22:04.392396  492873 occlient.go:1768] Status of cmp-git-testing-1 build is Running
[odo] I0609 12:22:04.393080  492873 occlient.go:1768] Status of cmp-git-testing-1 build is Running
[odo] I0609 12:22:04.393092  492873 occlient.go:1768] Status of cmp-git-testing-1 build is Failed
[odo]  ✗  Waiting for build to finish [53s]
[odo]  ✗  Failed to create component with name cmp-git. Please use `odo config view` to view settings used to create component. Error: failed to build component with args {Name:cmp-git SourcePath:https://github.com/openshift/nodejs-ex SourceRef: SourceType:git ImageName:nodejs EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:testing Wait:true StorageToBeMounted:map[] StdOut:0xc000010018}: unable to build cmp-git-testing-1, error: : build cmp-git-testing-1 status Failed
```

**Comment by zhengxiaomei123** [comment]
I got the bug info here https://bugzilla.redhat.com/show_bug.cgi?id=1771335
the problem described in this issue has be resolved in the advisory :https://access.redhat.com/errata/RHBA-2020:0062
BTW , I tested on OCP Z [4.5-nightly-build](https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp-dev-preview/4.5.0-0.nightly-s390x-2020-07-10-214321/). I will close the issue.

**Comment by zhengxiaomei123** [comment]
Reopen this issue to add testcases releated to pull-secret error for upstream CI of s390x.

**Comment by amitkrout** [comment]
@zhengxiaomei123 In 4.5 we have cluster-scoped secrets and is used globally. Before that every namespace had to have a secrets for all registries that will be used in the namespace. if your test needs to pull something from registry.redhat.io, it should have a secret for this registry. The pull secret from the installer should live in the openshift-config namespace as secret/pull-secret, if you want to reuse in another namespace, it should be copied to this namespace. 

So oc-import will throw error if you run your configuration script on < 4.5 cluster. I have a pr https://github.com/openshift/odo/pull/3737 that solves the problem. You can have alook.

**Comment by zhengxiaomei123** [comment]
> In 4.5 we have cluster-scoped secrets and is used globally. 
This is coincident with what I tested. Thanks for your confirmation.
