### ISSUE TITLE
refactoring integrations and e2e tests - abstracting Before/After Each

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3337]
We have a lot of duplicated code in our tests, mainly in After and Before Each function.

All common logic from those functions should be abstracted away to separate functions.
This will make it much easier to manage resources that are being created and it will be easier to do a proper clean up.

I've tried to do that at https://github.com/openshift/odo/pull/3221 but sadly before I could finish it it got out of sync with the master to the point that it can't be saved. It is going to be easier to start from scratch than trying to resolve all conflicts.

The above PR is not perfect there is a lot of things that can be done better, but it can be used as an example of how to streamline After and Before Each function.

/area testing
/kind code-refactoring

**Comment by dharmit** [comment]
@amitkrout has a PR that runs locally. He'll be driving this further.

**Comment by amitkrout** [comment]
I will send the pr after alpha or beta release to avoid painful rebase effort. As the test contains all the test file changes so it will be really painful for me each time after a new feature test script goes into master. cc_ @kadel @girishramnani

**Comment by prietyc123** [comment]
I have gone through the PR #3221 and observed we have to commonalise BeforeEach() and AfterEach() tests steps for devfile and regular tests. Also All the test needs to be changed accordingly.
