### ISSUE TITLE
No odo version verification is done, only information parttern is matched

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3342]
/kind bug

## What versions of software are you using?

**Output of `odo version`:**
master

## Actual behavior
```odo version``` test spec https://github.com/openshift/odo/blob/master/tests/integration/generic_test.go#L266 only checks the server pattern URL but does not validate the actual server URL and other information too. 

## Expected behavior
Server URL and other information in ```odo version``` string output should be verified with ```oc version``` output.

## Any logs, error output, etc?

Born from discussion - https://github.com/openshift/odo/issues/3325#issuecomment-643594506

**Comment by zhengxiaomei123** [comment]
@amitkrout So, for #3325 , The Server URL and other information in `odo version` string output should be verified with `oc version `output and `oc project` output. Is it right?
```
$ oc version
Client Version: 4.3.18
Server Version: 4.3.22
Kubernetes Version: v1.16.2

$ oc project
Using project "myproject" on server "https://api.ocp43b.rhocp.boe:6443".

$ odo version
odo v1.2.2 (b815649d4)
Server: https://api.ocp43b.rhocp.boe:6443
Kubernetes: v1.16.2

```

**Comment by metacosm** [comment]
@zhengxiaomei123 yes, I have implemented such a fix since I thought I should walk the walk… 😉

**Comment by zhengxiaomei123** [comment]
@metacosm Thanks. If so, I will close the pr #3326 .

**Comment by metacosm** [comment]
@zhengxiaomei123 I kept the regexp check because I didn’t want to open a « competing » PR but I believe it’s probably best to remove it. What do you think?

**Comment by zhengxiaomei123** [comment]
@metacosm The PR has been merged last night, I think you can go ahead after rebasing master .
