### ISSUE TITLE
json match throws error due to source attribute mismatch on windows terminal

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3350]
/kind bug

## What versions of software are you using?

**Operating System:**
win10

**Output of `odo version`:**
master

## How did you run odo exactly?

Ran `make test-cmd-cmp` on windows.

## Actual behavior

```
SSSSSCreated dir: C:\Users\Admin\AppData\Local\Temp\209745756
Creating a new project: xgvocbsngm
Running odo.exe with args [odo project create xgvocbsngm -w -v4]
[odo]  -  Waiting for project to come up  ...
[odo] I0615 05:53:34.877438    8988 occlient.go:543] Status of creation of project xgvocbsngm is Active
[odo] I0615 05:53:34.923391    8988 occlient.go:548] Project xgvocbsngm now exists
[odo] I0615 05:53:34.953368    8988 occlient.go:583] Status of creation of service account &ServiceAccount{ObjectMeta:{default  xgvocbsngm /api/v1/namespaces/xgvocbsngm/serviceaccounts/default 493ec3a9-5db9-4eae-ab6f-794c313ad5ed 42582 0 2020-06-15 05:53:35 +0000 GMT <nil> <nil> map[] map[] [] []  []},Secrets:[]ObjectReference{ObjectReference{Kind:,Namespace:,Name:default-token-mv29v,UID:,APIVersion:,ResourceVersion:,FieldPath:,},ObjectReference{Kind:,Namespace:,Name:default-dockercfg-dddjj,UID:,APIVersion:,ResourceVersion:,FieldPath:,},},ImagePullSecrets:[]LocalObjectReference{LocalObjectReference{Name:default-dockercfg-dddjj,},},AutomountServiceAccountToken:nil,} is ready
 V  Waiting for project to come up [1s]
[odo]  V  Project 'xgvocbsngm' is ready for use
[odo]  V  New project created and now using project: xgvocbsngm
[odo] I0615 05:53:34.974973    8988 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Current working dir: C:\Users\Admin\go\src\github.com\openshift\odo\tests\integration
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\209745756
Running odo.exe with args [odo component create nodejs cmp-git --project xgvocbsngm --context C:\Users\Admin\AppData\Local\Temp\209745756 --app testing -o json]
[odo] {
[odo]     "kind": "Component",
[odo]     "apiVersion": "odo.dev/v1alpha1",
[odo]     "metadata": {
[odo]         "name": "cmp-git",
[odo]         "namespace": "xgvocbsngm",
[odo]         "creationTimestamp": null
[odo]     },
[odo]     "spec": {
[odo]         "app": "testing",
[odo]         "type": "nodejs",
[odo]         "source": "file:///./",
[odo]         "sourceType": "local",
[odo]         "ports": [
[odo]             "8080/TCP"
[odo]         ]
[odo]     },
[odo]     "status": {
[odo]         "state": "Not Pushed"
[odo]     }
[odo] }
Deleting project: xgvocbsngm
Running odo.exe with args [odo project delete xgvocbsngm -f]
[odo]  V  Deleted project : xgvocbsngm
[odo]  !  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project 
may still exist on a different node.
Setting current dir to: C:\Users\Admin\go\src\github.com\openshift\odo\tests\integration
Deleting dir: C:\Users\Admin\AppData\Local\Temp\209745756

------------------------------
+ Failure [2.093 seconds]
odo sub component command tests
C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  Creating component
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:52
    should describe not pushed component when it is created with json output [It]
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:262

    Expected
        <string>: "...le:///./","..."
    to equal               |
        <string>: "...le://./","s..."

    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:268
```

## Expected behavior

json output should match all the attribute

## Any logs, error output, etc?

Manually verified on windows.

**Comment by amitkrout** [comment]
I have gone through the official Microsoft documentation [1] and Wikipedia doc [2] on file URI.

As per Wikipedia doc [2] on file URI :
Over a network the file URI will be like file://localhost/ on both unix and windows setup and if the file is local then the URI will be file:/// on both platform

As per Microsoft documentation [1] on file URI :
File URI will be like - file:///sDrives[|sFile]. whereas sDrives Specifies the local or network drive.

BTW, In our case we are dealing with the local component dir which reflects file URI in the json output against the source key. May be we need to revisit the backend code regarding how the json output prints file URI differently for the same local component on different platform

Lets not add bandage through test script fix. So i am closing the pr until we get a proper fix. ping @girishramnani 

[1] https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/jj710207(v=vs.85)
[2] https://en.wikipedia.org/wiki/File_URI_scheme

Slack discussion - https://openshiftdo.slack.com/archives/CQK6HE78S/p1592466401238200

**Comment by prietyc123** [comment]
I have changes the priority to high because we have already set up our periodic job on PSI for fedora, windows and macOS. However the platform specific issues are acting as hindrance for the test run, so IMO its high time we fix these bugs or test script issues.

**Comment by prietyc123** [comment]
@amitkrout @girishramnani  I have gone through the backend code and observed we are intentionally changing the source file uri on windows to get it work in url. AFAIU for not pushed component with `local` sourcetype, we get the source file uri from https://github.com/openshift/odo/blob/2e8304e3df88f4e2525863d082ba2f9b02634eeb/pkg/util/util.go#L203-L215 and this function intentionally converts the file uri for windows https://github.com/openshift/odo/blob/2e8304e3df88f4e2525863d082ba2f9b02634eeb/pkg/util/util.go#L212 by adding one more `/` . So its obvious to get `"source": "file:///./"` on windows. So I don't think we should look more into the code, this seems a fix from test side.

**Comment by kadel** [comment]
> by adding one more `/` . So its obvious to get `"source": "file:///./"` on windows. So I don't think we should look more into the code, this seems a fix from test side.

odo code is not correct. It needs to be fixed there. `file://./` is not a valid URI. Correct format is `file:///./` no matter what OS is being used.

**Comment by prietyc123** [comment]
> > by adding one more `/` . So its obvious to get `"source": "file:///./"` on windows. So I don't think we should look more into the code, this seems a fix from test side.
> 
> odo code is not correct. It needs to be fixed there. `file://./` is not a valid URI. Correct format is `file:///./` no matter what OS is being used.

@kadel Yes, true but `file:///./` URI make sense iff we have absolute source path refer [1] for more info. However AFAIU when we execute `odo component create <cmp-name> -o json` the generated source field takes relative location with dot-segment `.` ex `"source": "file:///./"` . Even the doc we were referring earlier [2] [3] only states about absolute path. 
I have observed some conflicting backend code where we are using relative source path https://github.com/openshift/odo/blob/2e8304e3df88f4e2525863d082ba2f9b02634eeb/pkg/util/util.go#L203-L215 and writing unit test for absolute path https://github.com/openshift/odo/blob/master/pkg/util/util_test.go#L165 which means we need to handle both properly.

[1] https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files 
[2] https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/jj710207(v=vs.85)
[3] https://en.wikipedia.org/wiki/File_URI_scheme
