### ISSUE TITLE
Unit tests failing with security error

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#3356]
/kind bug

## Actual behavior

```
[/home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_generic.go:28] - G404 (CWE-338): Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
  > rand.Intn(len(letterBytes))
[/home/travis/gopath/src/github.com/openshift/odo/pkg/util/util.go:87] - G404 (CWE-338): Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
  > rand.Intn(len(letterRunes))
```
https://travis-ci.com/github/openshift/odo/jobs/349244708

## Expected behavior

Unit tests should pass

**Comment by kadel** [comment]
@mik-dass @girishramnani, wasn't this fixed by https://github.com/openshift/odo/pull/3358?

**Comment by girishramnani** [comment]
yes it should have been

**Comment by girishramnani** [comment]
can @mik-dass rebase?

**Comment by girishramnani** [comment]
confirming that there is no instance of `math/rand` in upstream/master
![C0399F3B-0FDA-4636-B072-47E68C75ED8D_4_5005_c](https://user-images.githubusercontent.com/6551988/85148788-28dde980-b26e-11ea-8c76-08d65b3eab93.jpeg)

**Comment by mik-dass** [comment]
This was created when the error was there. https://github.com/openshift/odo/pull/3358 didn't mention it closes this issue.
