### ISSUE TITLE
pin down the version of ginkgo on CI scripts

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3361]
/kind user-story

## User Story
pin down the version of ginkgo on CI scripts so that an upgrade doesn't give us unexpected failures

## Links 
- Feature Request: 
- Related issue: https://github.com/openshift/odo/issues/3359

/kind user-story

**Comment by girishramnani** [comment]
@amitkrout please take a look at his story.

**Comment by girishramnani** [comment]
I will be pinning down the wwhrd and gosec versions as part of this issue https://github.com/openshift/odo/issues/3359

**Comment by amitkrout** [comment]
```
$ go get github.com/onsi/ginkgo@1.12.0
go: cannot use path@version syntax in GOPATH mode
```
It does not work because odo does not use go mod package management.

However the new feature in go version 1.4.* can fetch the specific tag version like ```go get github.com/onsi/ginkgo@<tag>``` but our CI environment comprises go version 1.13.*. I have raised a concern via https://github.com/onsi/ginkgo/issues/707 to know how ginkgo binary is built and published.

**Comment by amitkrout** [comment]
```
+ go install github.com/onsi/ginkgo/ginkgo
build github.com/onsi/ginkgo/ginkgo: cannot load github.com/fsnotify/fsnotify: open /go/src/github.com/onsi/ginkgo/vendor/github.com/fsnotify/fsnotify: no such file or directory
```
Hitting the failure due the flag ```GOFLAGS="-mod=vendor”```. This will be fixed just by overwriting it for example

```
go install -mod=“” github.com/onsi/ginkgo/ginkgo
```

Tomorrow I will fix it and open the pr https://github.com/openshift/odo/pull/3657 for review.

**Comment by kadel** [comment]
> [<img alt="@girishramnani" width="20" height="20" src="https://avatars0.githubusercontent.com/u/6551988?s=60&amp;u=93eaf1f99f7a22757db5bad83759b6cf8fd40007&amp;v=4">](/girishramnani) [girishramnani](/girishramnani) added [priority/Low](/openshift/odo/labels/priority%2FLow) [status/blocked](/openshift/odo/labels/status%2Fblocked) labels [15 days ago](#event-3624721053)

why is this blocked?

**Comment by amitkrout** [comment]
> > [<img alt="@girishramnani" width="20" height="20" src="https://avatars0.githubusercontent.com/u/6551988?s=60&amp;u=93eaf1f99f7a22757db5bad83759b6cf8fd40007&amp;v=4">](/girishramnani) [girishramnani](/girishramnani) added [priority/Low](/openshift/odo/labels/priority%2FLow) [status/blocked](/openshift/odo/labels/status%2Fblocked) labels [15 days ago](#event-3624721053)
> 
> why is this blocked?

https://github.com/openshift/odo/issues/3700

**Comment by amitkrout** [comment]
I am un assigning myself here as it blocked by #3700. And i am not actively working on this too since couple of weeks.

**Comment by kadel** [comment]
/remove-status blocked

#3700 has been resolved so this is no longer blocked

**Comment by girishramnani** [comment]
It seems this was done when we moved to go mod 
https://github.com/openshift/odo/blob/9200a7f99c2627c64d8ea2145aecf3ea2868d244/Makefile#L109
