### ISSUE TITLE
Install command should fit in the box

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#3372]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Ok, I'll admit this is a bit of a nit, but currently the installation commands at https://odo.dev/docs/installing-odo/ that you copy/paste to install odo are not fully visible and you need to drag as you copy. IMHO they should be fully visible up front, e.g. either make the boxes wider or the font smaller.

## What is the relevance of it?
I have two reasons for this request:

1. It's slightly awkward to start copying and have to drag in the middle and make sure you get it all; also a potential to miss a bit of it.
2. If I'm paranoid I can't actually see what it is doing to my system without pasting elsewhere or scrolling back and forth. Would be better to just see it all up front.

**Comment by GeekArthur** [comment]
Probably we can do the following two things to improve the UX of odo installation:
1. Adjust box and font size to provide a better view
2. Add clipboard button to the top right of the box so that user doesn't need to worry about drag & copy

Similar example can be found here: https://docs.openshift.com/container-platform/4.4/cli_reference/developer_cli_odo/installing-odo.html

**Comment by Preeticp** [comment]
We do use the clipboard button on https://docs.openshift.com/container-platform/4.4/cli_reference/developer_cli_odo/installing-odo.html so I assume this issue is relevant only to docs on odo.dev

**Comment by deboer-tim** [comment]
Yes, this is just for odo.dev.

**Comment by GeekArthur** [comment]
Yes, there is no issue of https://docs.openshift.com/container-platform/4.4/cli_reference/developer_cli_odo/installing-odo.html, I mean we can use https://docs.openshift.com/container-platform/4.4/cli_reference/developer_cli_odo/installing-odo.html as an example to follow for odo.dev improvement work.

**Comment by deboer-tim** [comment]
Still noticing this compared with other clis, we should at least 'copy the copy button' from docs.openshift.com.

/remove-lifecycle stale

**Comment by valaparthvi** [comment]
/close

Closing this issue in favor of the documentation update on https://odo.dev/docs/getting-started/installation. Feel free to open it if it still seems relevant.
