### ISSUE TITLE
Build progress does not show correctly when the command line is too long

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3373]
/kind bug
## What versions of software are you using?
1.2.2

**Operating System:**
mac

**Output of `odo version`:**
odo v1.2.2 (53530e0e5)

## How did you run odo exactly?
When I have a devfile with the devBuild command too long, the build progress shows a new line when the executed command is too long. To reproduce it:
1. use --downloadSource to create the component java-spring-boot.  
2. Add a bunch of spaces at the end of the devBuild command in the devfile.yaml, e.g.
        command: "/artifacts/bin/build-container-full.sh                                           "
3. Do an odo push

## Actual behavior
```
◐  Executing devbuild command "/artifacts/bin/build-container-full.sh           
◓  Executing devbuild command "/artifacts/bin/build-container-full.sh           
◑  Executing devbuild command "/artifacts/bin/build-container-full.sh           
◒  Executing devbuild command "/artifacts/bin/build-container-full.sh           
◐  Executing devbuild command "/artifacts/bin/build-container-full.sh
```

## Expected behavior
The animation show stay on the same line instead of creating a new line for each update.

## Any logs, error output, etc?
See actual behaviour.

/area devfile

**Comment by jgwest** [comment]
Able to reproduce on Linux using the provided step, and with lastest source on master branch.

**Comment by elsony** [comment]
merged
/close
