### ISSUE TITLE
add debug commands to odo devfile registry

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3377]
/kind user-story

## User Story
As an odo user, I want to be able to use the debugger to debug the application running in the cluster.

## Acceptance Criteria 
- [x] Every devfile that is in odo devfile registry should have "debug" group defined
- These are devfiles that need debug command -  
    - [x] java-maven
    - [x] java-openliberty
    - [x] java-sprintboot
    - [x] java-quarkus
- [ ] Tests for e2e scenerios
    - [ ] java-maven
    - [x] java-openliberty
    - [x] java-sprintboot
    - [x] java-quarkus

 
/kind user-story
/priority medium
/area debug

**Comment by dev-gaur** [comment]
#### Tentative Debug commands for all the 4 Java variants

1. for quarkus, ```mvn quarkus:dev```

2. for openLiberty, ```mvn liberty:dev```

3. for generic java-maven type and 4. spring-boot type 

Something like this command should work. 
```
java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n \
       -jar target/myapplication-0.0.1-SNAPSHOT.jar
```

**Comment by dev-gaur** [comment]
Blocked on #3740

**Comment by kadel** [comment]
> Blocked on #3740

this was resolved, it is not blocked anymore

**Comment by dev-gaur** [comment]
All the devfiles have been amended with debug command. E2E scenarios remain.

**Comment by prietyc123** [comment]
Removing `required-for-v2` label as v2.0.0 has been released.

**Comment by dev-gaur** [comment]
@prietyc123 can you co-assign this to Rodolfo as well?

**Comment by prietyc123** [comment]
@rnapoles-rh assigned for part of this issue `Tests for e2e scenerios`

**Comment by rnapoles-rh** [comment]
E2E scenarios tested manually. All functionality works as expected.
Automation in progress
Dependency for java-maven automated scenario blocked by https://github.com/devfile/api/issues/115

**Comment by rnapoles-rh** [comment]
e2e test for java maven pending due to dependency with devfile/api#115

**Comment by prietyc123** [comment]
Adding e2e tests for java-maven will be handled as part of https://github.com/openshift/odo/issues/4162 . @rnapoles-rh please update this issue according if I missed something.
