### ISSUE TITLE
.odo/env is not in .gitignore

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3386]
/kind bug

## How did you run odo exactly?

```
odo create maven

cat .gitignore
# git ignore contains just line with 
# .odo/odo-file-index.json
```

## Expected behavior
in addition to `.odo/odo-file-index.json` odo should also populate .gitingore with `.odo/env` as this is an environment-specific configuration that shouldn't get to git repository.

**Comment by girishramnani** [comment]
I can work on this
