### ISSUE TITLE
odo storage with devfile components

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3398]
## User Story
As an odo user, I want to be able to add simple storage to my component without needing to go and edit the devfile.yaml

## Acceptance Criteria
- If `odo storage` is executed in a directory with LocalConfig (.odo/config.yaml):
  - [x] `odo storage` executed in a LocalConfig component should keep doing what it does now.
- If `odo storage` is executed in a directory with devfile.yaml:
  - [x] `odo storage` should add a volume  into `components` fields in the devfile.yaml  and add `volumeMount` to all container components in devfile.yaml
  - [x] `odo storage delete <name>` should delete the volume and all its `volumeMounts` from the `devfile.yaml`
- [x] all storage commands should have json output

## Links 
Devfile documentation https://devfile.github.io/

/priority high
/area storage
/kind user-story

**Comment by mik-dass** [comment]
It seems we are defining volumes in a wrong manner in our devfiles for v2. We should declare the volumes in the Volumes field under components and reference them in the volumeMounts as volumeMounts don't have the size field defined for them. We are using a fixed size for our volumes https://github.com/openshift/odo/blob/9934f0fc1b8b0b5d6c8876b9d92ef3319eebe646/pkg/devfile/adapters/common/utils.go#L62

**Comment by adisky** [comment]
> It seems we are defining volumes in a wrong manner in our devfiles for v2. We should declare the volumes in the Volumes field under components and reference them in the volumeMounts as volumeMounts don't have the size field defined for them. We are using a fixed size for our volumes
> 
> https://github.com/openshift/odo/blob/9934f0fc1b8b0b5d6c8876b9d92ef3319eebe646/pkg/devfile/adapters/common/utils.go#L62

yes correct, I needs to me implemented as a part of shared volume across components. This has been discussed on V2 PR
https://github.com/openshift/odo/pull/3216/files#r432256103

**Comment by mik-dass** [comment]
> yes correct, It needs to be implemented as a part of shared volume across components. This has been discussed on V2 PR

I think the sharing volumes issue can be a part of this issue as storage creation will create a volume and reference it in the volume mounts of all the components. @kadel @girishramnani WDYT?

**Comment by adisky** [comment]
> > yes correct, It needs to be implemented as a part of shared volume across components. This has been discussed on V2 PR
> 
> I think the sharing volumes issue can be a part of this issue as storage creation will create a volume and reference it in the volume mounts of all the components. @kadel @girishramnani WDYT?

Implementation of shared volume across component also needs to be done for `odo push`, I guess this issue deals with `odo storage` commands.

**Comment by mik-dass** [comment]
> Implementation of shared volume across component also needs to be done for odo push, I guess this issue deals with odo storage commands.


OK then `odo storage create` won't work properly until https://github.com/openshift/odo/pull/3216/files#r432256103 is fixed. The command will just  add the volumes to the devfile and also mount it to the components in the devfile.

**Comment by adisky** [comment]
agreed as you said, it is dependent on this one https://github.com/openshift/odo/issues/3407

**Comment by kadel** [comment]
> agreed, as you said it is dependent on this one #3407

We can work on both issues independently. 
This issue is just about adding volumes to devfile.yaml. 
Issue  #3407 will make sure that the definition is correctly interpreted. 
None of those issues is blocker or prerequisite for the other

**Comment by mik-dass** [comment]
> This issue is just about adding volumes to devfile.yaml.
Issue #3407 will make sure that the definition is correctly interpreted.
None of those issues is blocker or prerequisite for the other

Yes but I was thinking of adding https://github.com/openshift/odo/issues/3407 into this issue because `odo storage list` will fetch the wrong size as the PVC size from the cluster and we need the cluster list to determine the current state i.e locally deleted etc.

**Comment by maysunfaisal** [comment]
@mik-dass I think for the size during `odo storage list`, if this issue is closed before #3407 then you can just print the `5Gi` for now and it should be fixed with #3407 

If #3407 is finished before this issue, it solves all your concerns i think regd displaying size?

**Comment by mik-dass** [comment]
>
If #3407 is finished before this issue, it solves all your concerns i think regd displaying size?

If #3407 is closed before this issue, then the problem with displaying size should be solved.

**Comment by mik-dass** [comment]
- `odo storage create` will only add the storage to the devfile.yaml and mount to all the containers
- `odo storage delete` will delete the given storage from the devfile.yaml and unmount from all the containers
- `odo storage list` will display the all the storage from the devfile and mention the size, current STATE etc of each storage by comparing with the cluster. (blocked because of #3407)

These commands will need JSON output too. 
@kadel @girishramnani Do we need `odo storage describe` too?

**Comment by dharmit** [comment]
Storage creation creates 5GiB volume by default. It needs to be fixed as a part of this issue so that other size is respected/considered.

**Comment by maysunfaisal** [comment]
@dharmit storage size is going to be covered by https://github.com/openshift/odo/issues/3407
I will be putting up a PR today for it

**Comment by mik-dass** [comment]
Storage `create` and `delete` have been implemented with https://github.com/openshift/odo/pull/3626
Storage `list` is being tracked here https://github.com/openshift/odo/issues/3704
/close
