### ISSUE TITLE
odo environment command for environment settings in env.yaml

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3401]
/kind user-story

## User Story
As a developer, I want to configure my environment specific settings in env.yaml of devfile style components so that I can change the settings after the initial creation.

## Background
The storing of the environment specific settings in the file .odo/env/env.yaml the devfile style components on #2592. However, the user currently cannot edit the settings in using the command line after the environment settings has been created as part of other commands.

##### odo environment
`odo environment` is doing all operations on `env.yaml`, should not touch any other file.

- [ ] The command can be shortened to `odo env`
- [ ] `odo env` should  have the same semantics and subcommands (set/unset/view) as `odo config`
- [ ] `odo env set Namespace` set namespace field in `env.yaml`
- [ ] `odo env set Project` set namespace field in `env.yaml`
- [ ] `odo env set DebugPort` set DebugPort field in `env.yaml`
- [ ] All `odo env` options should have clear description explaining what they are for
- [ ] `odo env` will error out with information that the command is not available for s2i builder images based components.

## Links 
- Related issue: #2592, this item is a spin off issue of #2688 which is focusing on editing the configuration settings in the devfile.yaml

/kind user-story
/area devfile

**Comment by GeekArthur** [comment]
From the `env.yaml` file loader in the source code, here is the list of fields that `odo env` can set/unset:
```
type ComponentSettings struct {
	Name        string              `yaml:"Name,omitempty"`
	Namespace   string              `yaml:"Namespace,omitempty"`
	URL         *[]EnvInfoURL       `yaml:"Url,omitempty"`
	PushCommand *EnvInfoPushCommand `yaml:"PushCommand,omitempty"`

	// DebugPort controls the port used by the pod to run the debugging agent on
	DebugPort *int `yaml:"DebugPort,omitempty"`
}

type EnvInfoURL struct {
	// Name of the URL
	Name string `yaml:"Name,omitempty"`
	// Port number for the url of the component, required in case of components which expose more than one service port
	Port int `yaml:"Port,omitempty"`
	// Indicates if the URL should be a secure https one
	Secure bool `yaml:"Secure,omitempty"`
	// Cluster host
	Host string `yaml:"Host,omitempty"`
	// TLS secret name to create ingress to provide a secure URL
	TLSSecret string `yaml:"TLSSecret,omitempty"`
	// Exposed port number for docker container, required for local scenarios
	ExposedPort int `yaml:"ExposedPort,omitempty"`
	// Kind is the kind of the URL
	Kind URLKind `yaml:"Kind,omitempty"`
}

type EnvInfoPushCommand struct {
	Init  string `yaml:"Init,omitempty"`
	Build string `yaml:"Build,omitempty"`
	Run   string `yaml:"Run,omitempty"`
}
```

**Comment by GeekArthur** [comment]
In this PR https://github.com/openshift/odo/pull/3075, we added some push parameters to the `env.yaml`, but I didn't find we call function `SetConfiguration` to set up those push parameters and use those push parameters for `odo push`.

![Screen Shot 2020-07-15 at 2 37 44 PM](https://user-images.githubusercontent.com/15131537/87584765-f9bf6a00-c6ab-11ea-877e-95319b88ee2a.png)

I don't think it's good to leave partial completed code in the code base so we need to decide if we still need the feature of setting up push parameters (Init, Build, Run) in `env.yaml`:
1. If we still need, we should implement the code to pick up the push parameters from `env.yaml` for `odo push`
2. If we don’t need, we should remove all the code and corresponding tests related with the push parameters

Once we make the decision we can implement/decide the push parameters for the `odo env`, if we implement the push parameters configuration directly for `odo env` using the partial completed code, we will hit the problem where user is allowed to use `odo env` to configure the push parameters in `env.yaml`, but we won’t pick up those push parameters when user run `odo push`.

@kadel @elsony please take a look this.
FYI @maysunfaisal

**Comment by GeekArthur** [comment]
```
type ComponentSettings struct {
	Name        string              `yaml:"Name,omitempty"`
	Namespace   string              `yaml:"Namespace,omitempty"`
	URL         *[]EnvInfoURL       `yaml:"Url,omitempty"`
	PushCommand *EnvInfoPushCommand `yaml:"PushCommand,omitempty"`

	// DebugPort controls the port used by the pod to run the debugging agent on
	DebugPort *int `yaml:"DebugPort,omitempty"`
}

type EnvInfoURL struct {
	// Name of the URL
	Name string `yaml:"Name,omitempty"`
	// Port number for the url of the component, required in case of components which expose more than one service port
	Port int `yaml:"Port,omitempty"`
	// Indicates if the URL should be a secure https one
	Secure bool `yaml:"Secure,omitempty"`
	// Cluster host
	Host string `yaml:"Host,omitempty"`
	// TLS secret name to create ingress to provide a secure URL
	TLSSecret string `yaml:"TLSSecret,omitempty"`
	// Exposed port number for docker container, required for local scenarios
	ExposedPort int `yaml:"ExposedPort,omitempty"`
	// Kind is the kind of the URL
	Kind URLKind `yaml:"Kind,omitempty"`
}

type EnvInfoPushCommand struct {
	Init  string `yaml:"Init,omitempty"`
	Build string `yaml:"Build,omitempty"`
	Run   string `yaml:"Run,omitempty"`
}
```

Given all individual fields and nested struct fields above are the fields we can configure in `env.yaml`, so from CLI perspective the implementation could be:

For configuring individual field such as  `Name` and `Namespace` in `env.yaml`:
```
odo env set <property name> <property value>
odo env unset <property name>
```

For configuring URL entry in `env.yaml`:
```
odo env set-url <URL name> --[property name] [property value]
odo env unset-url <URL name>
```

For configuring push parameters:
We need to wait for the decision in this comment https://github.com/openshift/odo/issues/3401#issuecomment-658955652
Also I don't think we need to use extra struct for push parameters, push parameters can belong to the component so they should be in the same level with `Name` and `Namespace` then we can treat them as individual field and use the same way/CLI to configure them.

@kadel @elsony Please review.

**Comment by GeekArthur** [comment]
Based on the discussion in today's status meeting we have a new plan for the following struct configurations that exist in the `env.yaml`

1. Generic fields configuration:
```
type ComponentSettings struct {
	Name        string              `yaml:"Name,omitempty"`
	Namespace   string              `yaml:"Namespace,omitempty"`
	URL         *[]EnvInfoURL       `yaml:"Url,omitempty"`
	PushCommand *EnvInfoPushCommand `yaml:"PushCommand,omitempty"`

	// DebugPort controls the port used by the pod to run the debugging agent on
	DebugPort *int `yaml:"DebugPort,omitempty"`
}
```
Use the following commands to configure:
```
odo env set <property name> <property value>
odo env unset <property name>
```

2. URL struct fields configuration:
```
type EnvInfoURL struct {
	// Name of the URL
	Name string `yaml:"Name,omitempty"`
	// Port number for the url of the component, required in case of components which expose more than one service port
	Port int `yaml:"Port,omitempty"`
	// Indicates if the URL should be a secure https one
	Secure bool `yaml:"Secure,omitempty"`
	// Cluster host
	Host string `yaml:"Host,omitempty"`
	// TLS secret name to create ingress to provide a secure URL
	TLSSecret string `yaml:"TLSSecret,omitempty"`
	// Exposed port number for docker container, required for local scenarios
	ExposedPort int `yaml:"ExposedPort,omitempty"`
	// Kind is the kind of the URL
	Kind URLKind `yaml:"Kind,omitempty"`
}
```
We don't need to implement this as we already have `odo url` command to configure URL struct fields

3. Push struct fields configuration:
```
type EnvInfoPushCommand struct {
	Init  string `yaml:"Init,omitempty"`
	Build string `yaml:"Build,omitempty"`
	Run   string `yaml:"Run,omitempty"`
}
```
This needs to wait for the code implementation of picking up the push parameters in `env.yaml` when user run `odo push` or `odo watch`, separate issue will be open to track the code implementation.
