### ISSUE TITLE
Allow volume definition to be shared across containers in a devfile

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3407]
/kind user-story

## User Story
As a stack creator, I want to specify a volume definition that can be shared across different containers in the devfile so that I don't need to repeat the same volume definition in each container.

## Acceptance Criteria 
- [ ] It should support the volume definition in a component as specified in the devfile 2.0 spec: https://github.com/devfile/kubernetes-api/issues/19
- [ ] It should support volume size as part of the volume definition as specified in the devfile 2.0 spec: https://github.com/devfile/kubernetes-api/issues/14

## Links 
- Related issue: 
https://github.com/devfile/kubernetes-api/issues/19
https://github.com/devfile/kubernetes-api/issues/14

/kind user-story
/area devfile

**Comment by mik-dass** [comment]
Isn't this related to https://github.com/openshift/odo/issues/3398?

**Comment by maysunfaisal** [comment]
VolumeMount volumes are not implicitly added anymore. Schema definition has been updated - https://github.com/devfile/kubernetes-api/pull/101
