### ISSUE TITLE
Debugger does not hit breakpoints on reattach

### ISSUE THREAD

**Issue by skoh7645** [openshift/odo#3417]
/kind bug

## What versions of software are you using?

**Operating System:** macOS 

**Output of `odo version`:** master

## How did you run odo exactly?
1. Get the devfile from https://github.com/neeraj-laad/nodejs-stack-registry/blob/master/devfiles/nodejs/devfile.yaml onto my local machine
2. `odo create --downloadSource`
3. `odo url create --port 3000`
4. `odo push --debug`
5. `odo debug port-forward`
6. Set breakpoints, attach debugger and hit breakpoints successfully
7. Detach and reattach debugger, debugger no longer stops at the breakpoints as expected

## Actual behavior
If I reattach the debugger (after the first time), it does not stop at the set breakpoints. I have to rerun `odo push --debug`
and `odo debug port-forward` to hit the breakpoints again.

## Expected behavior
I can detach and reattach the debugger and still hit the set breakpoints every time

**Comment by mik-dass** [comment]
The exact steps seem to work for me. I am able to detach and reattach successfully.

**Comment by skoh7645** [comment]
@mik-dass explained to me that I should be setting breakpoints in the loaded scripts section, rather than directly in the local file. It works as expected after all! Perhaps there is some documentation needed for this, though this should be on the VSCode side rather than Odo. Closing this issue as it is not a problem with Odo.
