### ISSUE TITLE
Additional flag --log_file along with odo subcommand doesn't work

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3444]
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
$ odo project create test123

$ oc --request-timeout 5m import-image nodejs --namespace=test123 --from=registry.access.redhat.com/rhscl/nodejs-10-rhel7:latest --confirm

$ oc annotate istag/nodejs:latest --namespace=test123 tags=builder --overwrite

$ odo create nodejs nodejs-app --project test123 --context tests/examples/source/nodejs/

$ odo push --context tests/examples/source/nodejs/

// open another terminal. Then run command
$ odo watch --context tests/examples/source/nodejs/ --log_file <logfile_path>

// create a file or dir in the context dir 
```
## Actual behavior
No log file is generated in the specified path 
```
$ tree -a -v /Users/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs
/Users/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs
├── .gitignore
├── .odo
│   ├── config.yaml
│   └── odo-file-index.json
├── check.sh
├── package.json
└── server.js

1 directory, 6 files
```

## Expected behavior
Should create log file as per the UX description
```
$ odo watch -h
[...]
Flags:
      [...]
Additional Flags:
      [...]
      --log_file string          If non-empty, use this log file
      [...]
```

**Comment by amitkrout** [comment]
The same additional flags are also available for other sub commands too. I checked --log_file with preference command and it doesn't generate log file in the specified path.

I am changing the issue title to a generic one.

**Comment by girishramnani** [comment]
This doesn't seem like high priority to me. Any reason to put high priority
/remove-priority high
/priority medium

**Comment by kadel** [comment]
/triage duplicate
/close

This is related to 
https://github.com/openshift/odo/issues/3446
