### ISSUE TITLE
 Additional flag --log_file_max_size and --skip_log_headers along with odo subcommand doesn't work

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3445]
follow up issue of https://github.com/openshift/odo/issues/3444

**Comment by girishramnani** [comment]
This doesn't seem like high priority to me. Any reason to put high priority
/remove-priority high
/priority medium

**Comment by kadel** [comment]
this is the same as https://github.com/openshift/odo/issues/3446
/triage duplicate
/close
