### ISSUE TITLE
What additional flag --add_dir_header, --skip_headers and --vmodule does ?

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3446]
I am observing weird behaviour while using with watch and perference sub command 

With watch command looks ok, but i don't know what it does 

```
$ odo watch --context tests/examples/source/nodejs/ --add_dir_header true
Waiting for something to change in /Users/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs
```

With preference command it throws error

```$ odo preference set Experimental true --add_dir_header true -f
Error: only one value per parameter is allowed
  [...]
Additional Flags:
      --add_dir_header           If true, adds the file directory to the header (default false)
      --log_file string          If non-empty, use this log file
      --log_file_max_size uint   Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --skip_headers             If true, avoid header prefixes in the log messages (default false)
      --skip_log_headers         If true, avoid headers when opening log files
  -v, --v Level                  Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec       Comma-separated list of pattern=N settings for file-filtered logging

 ✗  only one value per parameter is allowed
```

**Comment by amitkrout** [comment]
ping @girishramnani @kadel

**Comment by amitkrout** [comment]
Same behaviour i am observing for ```--skip_headers``` too. 

I need more information on ```--vmodule```. For example how to verify it 
```
--vmodule moduleSpec       Comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by kadel** [comment]
Why high priority?

/remove-priority high
/priority low

**Comment by kadel** [comment]
Those flags are coming from https://github.com/kubernetes/klog

**Comment by amitkrout** [comment]
> Why high priority?
> 
> /remove-priority high
> /priority low

@kadel @girishramnani As a user i see these flags in odo help and there are no information from odo side to explain those, i mean where to use, how to use. It's odo responsibility to provide the detail information about these flags, may be a reference how to uses this. Interesting part is that since a long time we have been exposing it through odo but no one has verified it i guess. 

TBH as a QE (first face of user) when i was executing it and found no information from odo side regarding these flags i felt like kind of block to test those. 

Then why not priority atleast major ?

Question: What is the importance of these additional flags in odo except the verbose flag.

**Comment by prietyc123** [comment]
Even I kind of feel lost with these flags. Not getting the exact purpose for this to be in odo.

**Comment by kadel** [comment]
Those flags are there so we should make sure that they work.



> Then why not priority atleast major ?

It doesn't have any effect odo do functionality or usability
