### ISSUE TITLE
build issues with ppc64le on travis ci environment

### ISSUE THREAD

**Issue by PradipPanigrahi** [openshift/odo#3449]
/on ppc64le environment :

when we go for travis ci build with ppc64le there is failure in build with master branch of code.
the error log is :
0.00s$ travis_install_go_dependencies 1.11.x -v
2.10s$ travis_script_go -v
go build -ldflags="-w -X github.com/openshift/odo/pkg/version.GITCOMMIT=f8ea5a5" cmd/odo/odo.go
cmd/odo/odo.go:7:2: cannot find package "github.com/openshift/odo/pkg/log" in any of:
	/home/travis/gopath/src/github.com/PradipPanigrahi/odo/vendor/github.com/openshift/odo/pkg/log (vendor tree)
your suggestion helpful for me .

- From the travis environment it is failed to import "github.com/openshift/odo/pkg/odo/cli" 
- And the dependency "go " library is make some issues during the build.

**Comment by kadel** [comment]
Problem is location of odo source code. It needs to be in `$GOPATH/src/github.com/openshift/odo` on Travis that would be  `/home/travis/gopath/src/github.com/openshift/odo`. You have it in `/home/travis/gopath/src/github.com/PradipPanigrahi/odo`.


You need to make sure that the odo's go source code is correctly placed in $GOPATH. You should be able to achieve that by setting `go_import_path`(https://docs.travis-ci.com/user/languages/go/#go-import-path) directive in .travis.yaml. See our .travis.yaml https://github.com/openshift/odo/blob/67da8a12c085ad18996ca271ba553249416686e1/.travis.yml#L11

**Comment by sarveshtamba** [comment]
Issue seems to have been resolved by setting the correct path variables, can be closed out for now, will reopen again if required.

**Comment by prietyc123** [comment]
> Issue seems to have been resolved by setting the correct path variables, can be closed out for now, will reopen again if required.

/close
