### ISSUE TITLE
Fix odo devfile test dependency

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3456]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

Two issues: 
- [ ] Currently, odo repo has some copies of devfile.yaml of various stacks which are written in different ways to test the various use case scenarios. These devfiles are not updated when the devfile registry is updated at https://github.com/odo-devfiles/registry/
- [ ] Updating the devfiles at https://github.com/odo-devfiles/registry/ may potentially break odo tests

/area devfile

**Comment by girishramnani** [comment]
Ideally willy nilly merging PRs on odo-devfiles/registry, we should follow what we do for odo-init-image repo i.e. We should run the odo tests on PRs running on odo-devfiles/registry so that each change is validated

**Comment by kadel** [comment]
> Ideally we shouldn't recklessly merging PRs on odo-devfiles/registry, we should follow what we do for odo-init-image repo i.e. We should run the odo tests on PRs running on odo-devfiles/registry so that each change is validated

that should be fixed as part of https://github.com/openshift/odo/issues/3378



tests should not depend on devfiles in odo-devfile/registry without a few expectations that are actually testing registry integration. The rest of the test should use devfile that are part of the testing scripts to minimalize external dependencies.
