### ISSUE TITLE
Operator Hub and experimental mode

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3467]
/kind discussion
/area service-operators

What's the plan with regard to Operator Hub and experimental mode? My understanding is that we're going to move devfile support from currently experimental to supported with odo v2 release. However, Operator Hub integration has been happening in experimental mode, and we're still working on it.

ping @kadel @girishramnani

**Comment by kadel** [comment]
OperatorHub integration should be finished and moved out of experimental for odo v2 release

**Comment by dharmit** [comment]
Do you mean to have everything mentioned in Acceptance Criteria for #2613 to be finished for that?

**Comment by kadel** [comment]
> Do you mean to have everything mentioned in Acceptance Criteria for #2613 to be finished for that?

yep

**Comment by girishramnani** [comment]
We need operator hub out of experimentation mode

**Comment by girishramnani** [comment]
So, my thoughts were that we need operator hub outside of experimental mode. That doesn’t mean we want everything like - service to service linking, forbid self linking.
But the minimum set needs to be done

**Comment by kadel** [comment]
> So, my thoughts were that we need operator hub outside of experimental mode. That doesn’t mean we want everything like - service to service linking, forbid self linking.
> But the minimum set needs to be done

https://github.com/openshift/odo/issues/2613 Is not about linking

**Comment by dharmit** [comment]
> We need operator hub out of experimental mode

And the only luxury that I've enjoyed so far in Experimental mode is not be bothered about supporting both Operator Hub and Service Catalog. Please note that it's not straightforward to support both at the same time.

I'm not saying that we can't do it. But it's a non-trivial task to take Operator Hub out of experimental mode and support it along with Service Catalog for devfile based components. AFAIK, linking service catalog based services and devfile based components has not been verified. Probably we don't care about it? I don't know. Let me know.

> So, my thoughts were that we need operator hub outside of experimental mode. That doesn’t mean we want everything like - service to service linking, forbid self linking.

This, I agree, we discussed in the cabal and we're on the same page. :+1:



>  But the minimum set needs to be done

What we have right now is:
1. `odo catalog list services` - lists operators and their crds. (JSON output works as well.)
2. `odo service create <operator-name> --crd <cr-name>` works. (JSON output doesn't.)
3. `odo service create --from-file /path/to/file.yaml` works since we don't support interactive mode yet. (JSON output doesn't.)
4. `odo service list` works. (JSON output works as well.)
5. `odo link <CR-name>/<service-name>` works on my local system but I need some clarification on acceptance criteria as mentioned elsewhere.

Do we want anything else in "minimum set" here? If not, I can focus on polishing things and what we decide about Service Catalog plus Operator Hub for devfile components.



> #2613 Is not about linking

My bad. It wasn't in the acceptance criteria. I just added it to the list. Hope that is OK.



> I consider that Users story to be required for moving Operator backed services out of the experimental.

You mean the statement: "As a user, I want to create a new instance of my database or another service managed by operators So that I can use it (link it) with my application"? Or the acceptance crtiria mentioned below that?

> Regarding linking I agree with you. All we need is basic support for linking component and service

IMO, we're close. Maybe done. Let's discuss this on a call.

**Comment by kadel** [comment]
> Do we want anything else in "minimum set" here? If not, I can focus on polishing things and what we decide about Service Catalog plus Operator Hub for devfile components.
> 
> >

yes, from https://github.com/openshift/odo/issues/2613 : 
>  - [ ] User should not be required to provide or write any CR definitions or YAML
>  - [ ]  It should be possible to provide additional arguments for operator via the command line (as arguments to odo service create command) #2785

Otherwise, odo user has only two options (use example as it is, or edit service CR yaml) to create service and non of it is a good experience

**Comment by dharmit** [comment]
I do not deny that it's a bad user experience. But every CR has different set of parameters that it cares about. To get this to work, we need to provide a way for the user to know the parameters that are acceptable for the CR. So, something like:

```sh
$ odo catalog describe service etcdoperator/EtcdCluster
```
Above command would list the possible parameters (likely from the `spec` field).

And then we accept each of these as a parameter. It's doable. The only concern is you cannot be 100% sure if it would work with all the types of CRs. We need to do extensive testing for that. Simply playing with EtcdCluster CR won't suffice.

**Comment by girishramnani** [comment]
This issue is about discussion so removing the `required-for-v2` label

**Comment by kadel** [comment]
Do we need to keep this issue?

**Comment by dharmit** [comment]
> Do we need to keep this issue?

No. I have clarity on what's needed. We need #2613 fully in for v2.

/close
