### ISSUE TITLE
More documentation needed on "odo create" --downloadSource flag 

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#3470]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Doesn't show any error/ warning message when --git  and --downloadSource are used at once in `odo create` (no matter what the order is)  

```
$ odo create --downloadSource nodejs --env VariableName=Value --env app=nodejstest --git git@github.com:xxyyz/Projecdemo.git  --now --port 3000/TCP
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [129064ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [115234ns]
 ✓  Validating devfile component [286627ns]

Please use `odo push` command to create the component with source deployed
```
Informing the user that `--downloadSource` will be prioritized over `--git` for creating odo component if they use both flag at once.

## What is the relevance of it?

If the above info is provided in `odo create -h`  --downloadSource flag will create better UX and will create less confusion from users perspective.

**Comment by kadel** [comment]
- `downloadSource` is being renamed to `starter` https://github.com/openshift/odo/pull/3425
- this is not yet fully implemented. It will be handled in https://github.com/openshift/odo/issues/3263

I'm closing this one. If you have inputs on how this should be done you can add comments to https://github.com/openshift/odo/issues/3263

/close
