### ISSUE TITLE
Editing the file using "vim" editor leads to fail component push at syncing stage

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3471]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
master

## How did you run odo exactly?

Steps to reproduce:

1. `mkdir -p testbackend` and copy the project file from `tests/examples/source/devfiles/nodejs` to the create directory

```
$ ls -a /Users/pkumari/go/src/github.com/openshift/odo/testbackend
.       ..      project
```
2. `mkdir -p testfrontend` and do the same as in step 1
3. `odo create nodejs backend` and `odo create nodejs frontend` accordingly in both the directory
4. `odo push` for both the component
5. Start `odo watch` for both at the same time.
6. changing the message in `app.js` for both the component at the same time.

Backend nodejs component:

```
$ odo watch
Waiting for something to change in /Users/pkumari/go/src/github.com/openshift/odo/testbackend/project
File /Users/pkumari/go/src/github.com/openshift/odo/testbackend/project/app/.app.js.swp changed
Pushing files...

Validation
 ✓  Validating the devfile [85391ns]

Creating Kubernetes resources for component backend
 ✓  Waiting for component to start [449ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component backend
 ◓  Syncing files to the component ✗  Error while creating tar: &os.PathError{Op:"open", Path:"/Users/pkumari/go/src/github.com/openshift/odo/testbackend/project/app/.app.js.swp", Err:0x2}
```

Frontend nodejs component:

```
$ odo watch
Waiting for something to change in /Users/pkumari/go/src/github.com/openshift/odo/testfrontend/project
File /Users/pkumari/go/src/github.com/openshift/odo/testfrontend/project/app/.app.js.swp changed
Pushing files...

Validation
 ✓  Validating the devfile [112277ns]

Creating Kubernetes resources for component frontend
 ✓  Waiting for component to start [5s]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component frontend
 ◒  Syncing files to the component ✗  Error while creating tar: &os.PathError{Op:"open", Path:"/Users/pkumari/go/src/github.com/openshift/odo/testfrontend/project/app/.app.js.swp", Err:0x2}
```
But If I change `app.js` for one component at a time it works fine.

```
$ odo watch
Waiting for something to change in /Users/pkumari/go/src/github.com/openshift/odo/testbackend/project
File /Users/pkumari/go/src/github.com/openshift/odo/testbackend/project/app/.app.js.swp changed
Pushing files...

Validation
 ✓  Validating the devfile [428446ns]

Creating Kubernetes resources for component backend
 ✓  Waiting for component to start [290ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component backend
 ✓  Syncing files to the component [7s]

Executing devfile commands for component backend
 ✓  Executing install command "npm install" [3s]
 ✓  Executing run command "npm start" [6s]
Waiting for something to change in /Users/pkumari/go/src/github.com/openshift/odo/testbackend/project
```

## Actual behavior

Parallel execution of `odo watch` for two different components fails on same file change at the same time. In this case `app.js`

## Expected behavior

It should push the change as both the component looking for change in two different directory.

## Any logs, error output, etc?

Manually verified in experimental mode.

**Comment by prietyc123** [comment]
ping @mik-dass

**Comment by mik-dass** [comment]
I ran watch for two components in a parallel manner and don't pushed works fine for me.

Nodejs component
```
Waiting for something to change in /home/mrinaldas/che-nodejs
File /home/mrinaldas/che-nodejs/app/app.js changed
Pushing files...

Validation
 ✓  Validating the devfile [37012ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [616ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs
 ✓  Executing install command "npm install" [5s]
 ✓  Executing run command "npm start" [9s]
Waiting for something to change in /home/mrinaldas/che-nodejs
^C
[mrinaldas@localhost che-nodejs]$ 
```
Openliberty component
```
Waiting for something to change in /home/mrinaldas/openliberty-ex
File /home/mrinaldas/openliberty-ex/src/main/java/dev/appsody/starter/StarterApplication.java changed
Pushing files...

Validation
 ✓  Validating the devfile [91942ns]

Creating Kubernetes resources for component openliberty
 ✓  Waiting for component to start [478ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component openliberty
 ✓  Syncing files to the component [9s]

Executing devfile commands for component openliberty
 ✓  Executing devrun command "mvn -DhotTests=true -DappsDirectory=apps -Dmaven.repo.local=/mvn/repository liberty:dev", if not running [4s]
Waiting for something to change in /home/mrinaldas/openliberty-ex
^C
```

**Comment by mik-dass** [comment]
Which editor are you using for making the changes? Are you running a script?
```
 ◓  Syncing files to the component ✗  Error while creating tar: &os.PathError{Op:"open", Path:"/Users/pkumari/go/src/github.com/openshift/odo/testbackend/project/app/.app.js.swp", Err:0x2}
```
Looking the error log, I can see a swp file. Are you using  a vi based editor? If you are performing the changes manually, please try the above scenarios using VS Code.

**Comment by prietyc123** [comment]
> Looking the error log, I can see a swp file. Are you using a vi based editor? If you are performing the changes manually, please try the above scenarios using VS Code.

I was running the steps on VS Code itself.

**Comment by mik-dass** [comment]
> Can you please replicate the same component that I am using like nodejs frontend and backend component

Which nodejs repo are you using?

**Comment by mik-dass** [comment]
>  ◒  Syncing files to the component ✗  Error while creating tar: &os.PathError{Op:"open", Path:"/Users/pkumari/go/src/github.com/openshift/odo/testfrontend/project/app/.app.js.swp", Err:0x2}

I think it's a problem with `odo push` not watch. The .swp file, created during the edit operation, gets deleted when the VI editor is closed during the syncing process. Thus the tar operation fails. I think this parallel watch scenario should work with vs code as no temporary file is created in the repo folder.

**Comment by prietyc123** [comment]
> I think it's a problem with odo push not watch. The .swp file, created during the edit operation, gets deleted when the VI editor is closed during the syncing process. Thus the tar operation fails. I think this parallel watch scenario should work with vs code as no temporary file is created in the repo folder.

Yes, I also performed the steps again and observed the same behaviour. As per the validation I did its the problem with `odo push` hence changing the title.

**Comment by prietyc123** [comment]
Observations:

- Either do `odo push` or `odo watch`
- Edit the file like `vim test/test.js` in between the operation `odo push` or `odo watch`
- .swp file gets created
- Before or during syncing the component close the editor
- It will delete .swp file and tar operation fails.

```
$ odo push

Validation
 ✓  Validating the devfile [58043ns]

Creating Kubernetes resources for component frontend
 ✓  Waiting for component to start [325ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component frontend
 ✓  Checking file changes for pushing [4ms]
 ◒  Syncing files to the component ✗  Error while creating tar: &os.PathError{Op:"open", Path:"/Users/pkumari/go/src/github.com/openshift/odo/testfrontend/project/test/.test.js.swp", Err:0x2}
```
