### ISSUE TITLE
exec into the folder provided in the source mapping for better UX

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3472]
@johnmcollier things work as per the PR description. However, I have a concern that might be relevant for this PR or a different one or entirely irrelevant.

After a successful `odo push`, should the user be able to exec directly to the directory provided by `sourceMapping` field instead of being exec'd into `/projects`?

```sh
# what I see
$ kubectl exec nodejs-7d6bb4dc94-c84xh -c runtime -- pwd
/projects

# what I expect as a user
$ kubectl exec nodejs-7d6bb4dc94-c84xh -c runtime -- pwd
/test
```

Of course, there could be a valid reason to not do so and I'm fine by it.

cc @elsony @kadel

_Originally posted by @dharmit in https://github.com/openshift/odo/pull/3295#issuecomment-652219287_

**Comment by kadel** [comment]
> After a successful `odo push`, should the user be able to exec directly to the directory provided by `sourceMapping` field instead of being exec'd into `/projects`?

This is what I would as a user expect. 

This should be defined in devfile spec because every tool should handle this the same way.

**Comment by dharmit** [comment]
@kadel @girishramnani does this issue still matter?
