### ISSUE TITLE
odo config view does not work for devfile/ devfile registry component

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3476]
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
$ odo preference set Experimental true -f
$ odo registry add nodejs https://raw.githubusercontent.com/odo-devfiles/registry/master
$ odo create nodejs --registry nodejs
$ odo config view
 ✗  the directory doesn't contain a component. Use 'odo create' to create a component
```
```
$ tree -a
.
├── .gitignore
├── .odo
│   └── env
│       └── env.yaml
└── devfile.yaml
```

## Actual behavior
Throws error of missing component directory

## Expected behavior
Should list out the config settings

**Comment by mik-dass** [comment]
Config command is not supported for devfile components yet. https://github.com/openshift/odo/issues/2688

**Comment by amitkrout** [comment]
> Config command is not supported for devfile components yet. #2688

/close
