### ISSUE TITLE
Application URL does not work for nodejs registry component

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3477]
/kind bug

## What versions of software are you using?

**Operating System:**
Supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
$ odo preference set Experimental true -f
$ odo registry add nodejs https://raw.githubusercontent.com/odo-devfiles/registry/master
$ odo create nodejs --registry nodejs
$ odo url create
$ odo push
// Tried till 2 mins
$ curl -Ik http://<cluster>.devcluster.openshift.com
HTTP/1.0 503 Service Unavailable
pragma: no-cache
cache-control: private, max-age=0, no-cache, no-store
content-type: text/html
```

## Actual behavior
Route is not accessible 

## Expected behavior
Route should be accessible

**Comment by kadel** [comment]
This looks more like an issue with source code. What nodejs  example are you using?
I was not able to replicate this
/remove-priority high
/priority low
/remove-area registry
