### ISSUE TITLE
odo watch deletes all files 

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#3479]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS 

**Output of `odo version`:**
built from source.
odo v1.2.3 (33a73e351)
 

## How did you run odo exactly?

I am using https://github.com/gorkem/odo-devfile/tree/master/python-example to do python debugging 

```sh
odo create
odo push --debug
## At this point, application is running and I can attach my debugger
odo watch
```
Modify `app.py` and observe that build fails with missing `requirements.txt`.
I have opened a terminal and noticed that other than the modified file all other files are 
deleted. Doing another `odo push` restores them.

**Comment by mik-dass** [comment]
This seems to happen due to a reployment during the watch phase. The push stages only pushes the modified files and the container now has missing files.

**Comment by gorkem** [comment]
I think that redeployment is also causing #3480. `watch`seems to be doing a needless deployment.  If I use `push --debug` in place of watch the redeployment would not happen. I think watch needs to become a bit smarter and pass the debug flag.

**Comment by gorkem** [comment]
Another variation of this bug is 
```
odo push
odo watch
``` 
modify devfile.yaml

**Comment by mik-dass** [comment]
> I think that redeployment is also causing #3480

The redeployment is not causing #3480. That happens because the push, triggered by watch, always runs the default run command from the devfile or the one provided using the flags. We may need to implement a flag like `odo watch --debug` to run the debug command during pushes triggered by watch or come up with some other mechanism to make it smarter.

**Comment by kadel** [comment]
> I think that redeployment is also causing #3480. `watch`seems to be doing a needless deployment. If I use `push --debug` in place of watch the redeployment would not happen. I think watch needs to become a bit smarter and pass the debug flag.

This is combination of #3480 bug and of the fact that we are using `emptyDir` volume for storing project source in the container. 
EmptyDir approach was chosen to make avoid dependency on `PersistentVolumeClaims`. 

Even when #3480 gets fixed we will still have a similar problem like the one described here. 

`odo watch` is also trying to handle the situation when devfile.yaml is changed.
So considering following scenario will also result in restarting the pod and losing all inside the container.
```
odo create
odo push
odo watch
# edit devfile.yaml (for example add env variables)
```

We have two options to solve this. 
 - We can say that `odo watch` will handle only the source-code updates, and you always have to call `odo push` when you change devfile.yaml
 - Start using  `PVC` volume for storing source-code in pod

**Comment by gorkem** [comment]
I did a quick PR #3536 because it was interrupting my work. Seems to fix at least what I observe. Don't know if it is the way that you would like to fix it though.
