### ISSUE TITLE
odo watch always dismisses debug mode

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#3480]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS 

**Output of `odo version`:**
built from source.
odo v1.2.3 (33a73e351)
 

## How did you run odo exactly?

I am using https://github.com/gorkem/odo-devfile/tree/master/python-example to do python debugging 

```sh
odo create
odo push --debug
## At this point, application is running and I can attach my debugger
odo watch
```
Modify `requirements.py` and observe the following output 

```sh
❯ odo watch
Waiting for something to change in ...../odo-devfile/python-example
File ...../odo-devfile/python-example/requirements.txt changed
Pushing files...

Validation
 ✓  Validating the devfile [51740ns]

Creating Kubernetes resources for component python-example
 ✓  Waiting for component to start [12s]

Applying URL changes
 ✓  URL python-example-8000 successfully deleted
 ✓  URL python-example-8000: http://python-example-8000-XXXXXX.com created

Syncing to component python-example
 ✓  Syncing files to the component [382ms]

Executing devfile commands for component python-example
 ✓  Executing py-build command "pip install --user -r requirements.txt" [17s]
 ✓  Executing py-run command "python /projects/app.py" [2s] <----------------------------
Waiting for something to change in ..../odo-devfile/python-example
```
Notice that on the marked line `odo` is reverting the debug command to run command as a result of a change when I am doing a watch. I expect `odo` to preserve my last choice which is debug in this case.

**Comment by girishramnani** [comment]
I don’t think we have a odo watch —debug command 
We should consider adding that as a feature

**Comment by gorkem** [comment]
Watch seems to have a very simplistic implementation, it needs to become smarter. 
1. It needs to become aware of the conditions that can make `ComponentAdapter.Push` to redeploy. Like modification of devfile and the debug flag so that it does a full resync. 
2. In case of flags like `--debug` and an existing earlier push it should restore them when calling the `ComponentAdapter`. It is unexpected for me for `watch` command to modify my deployment especially since I had it working with the `push`command earlier. `watch` should recognize an existing deployment when exists and start watching for file changes without doing any extra steps.

**Comment by girishramnani** [comment]
@kadel do you think we need this for odo v2?

**Comment by girishramnani** [comment]
I think the odo watch command can check for a running pod and use the same command used while push occurred. But I also want to consider a case where a user might want to run the debug command while doing watch? or can that be handled by the more general `--command=<command-name>` flag?

**Comment by mik-dass** [comment]
> and use the same command used while push occurred

I am not sure if we can get the info without saving it somewhere. This also might confuse users.

> But I also want to consider a case where a user might want to run the debug command while doing watch?

For debugging to work with watch, we also need port forwarding to be on. 

- We can ask the user to start port forwarding when watch was triggered with `--debug` flag
OR
- We can start it (if not already running) and keep it running in the background during watch.

> I think the odo watch command can check for a running pod

Yes we can check if the pod is currently running or not. If not running, we trigger normal push.

If the pod is running, we can check the list of changed files. 
- If the list includes the devfile or the env.yaml, we trigger normal push. This is take care of URLs, Env Vars etc added during the watch session.
- Else we trigger a different version of push. This version will simply push the changed files, build and run/debug.

**Comment by kadel** [comment]
> > and use the same command used while push occurred
> 
> I am not sure if we can get the info without saving it somewhere. This also might confuse users.

We can save this information to env.yaml. 
When `odo push --debug` is executed `runMode: debug` will be added to 
`env.yaml` 
When `odo push` is exectued `runMode: run` will be set in `env.yaml`
 
`odo watch` than can check the information from `env.yaml` to determine the correct mode.

This should be OK as `odo push` is the only way to switch between normal run a debug. 


> * We can ask the user to start port forwarding when watch was triggered with `--debug` flag

I would go with this option.

**Comment by gorkem** [comment]
>     * We can ask the user to start port forwarding when watch was triggered with `--debug` flag

So far I was not fan of `--debug` for `watch` but `watch` command is a blocking command and users always end up starting a new shell to do the debug. If `--debug` can initiate the port forwarding, the flag makes more sense.

**Comment by mik-dass** [comment]
> If --debug can initiate the port forwarding, the flag makes more sense.

But then we will have to add a flag or find a way to get the user desired local-port. 

> When odo push is exectued runMode: run will be set in env.yaml

Let's just start with detecting the runMode after starting watch. Till we figure out the approach for local-port, we can simply show a info message, asking the user to start port-forwarding in a separate terminal. We can later start a port forwarding during watch too.

> When odo push --debug is executed runMode: debug will be added to
env.yaml

RunMode will be saved in the env.yaml only after a successful push.
