### ISSUE TITLE
The default odo-init-image value to support multi-arch

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3481]
/kind feature

## Which functionality do you think we should add?
The default odo-init-image is "registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.1.3" which is not supported by s390x arch. 

```
Pulling image "registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.1.3"20s         Warning   Failed              pod/nodejs-nodejs-ex-vsit-app-1-xlvch               Failed to pull image "registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.1.3": rpc error: code = Unknown desc = Error choosing image instance: no image found in manifest list for architecture s390x, OS linux
```

To support s390x arch, we have to set env `ODO_BOOTSTRAPPER_IMAGE`. 

## Why is this needed?
We should make the default odo-init-image to release the s390x or other non-x86 arch version on upstream registry So the user is not necessary to set the `ODO_BOOTSTRAPPER_IMAGE` manually.

**Comment by zhengxiaomei123** [comment]
We found there has been offically built odo-init-image for s390x [here](https://quay.io/repository/multi-arch/openshiftdo-odo-init-image-rhel7).  We team can help build the odo-init-image for s390x arch, What we want is to relese this image to offical registry to be used default by user.

**Comment by PanYaLian** [comment]
I think the purpose is to have an official s390x arch odo-init-image in some public registry like "registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.1.3", and for the defaultBootstrapperImage below, point to the different  odo-init-image based on the arch.
https://github.com/openshift/odo/blob/9a470629475bf6339dec637ee5ea8e326188a7fd/pkg/devfile/adapters/common/utils.go#L35

**Comment by zhengxiaomei123** [comment]
I got confirmation that images will be uploaded with manifests to registry so cluster should be able to pull correct image. The image is getting built as per results on the internal buildsystems . We will probably need to wait till they push an actual release to redhat registry to confirm without doubt. And then We will verify it .

**Comment by girishramnani** [comment]
@zhengxiaomei123 I think we have a registry release recently can you please verify and close this issue if its resolved?

**Comment by zhengxiaomei123** [comment]
@girishramnani Yes. I will do ASAP.
