### ISSUE TITLE
Devfile v2: No ClonePath integration tests

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3484]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

N/A

Just a reminder that there are no integration tests for ClonePath within the Devfile schema. 

See: https://github.com/openshift/odo/blob/20f84de3ece0393bb957de3267824dabdc15dec4/pkg/sync/adapter_test.go#L80 for unit tests, but no actual integration tests (yet)

## Actual behavior

N/A

## Expected behavior

N/A

**Comment by girishramnani** [comment]
@anandrkskd could you please work on this issue?

**Comment by prietyc123** [comment]
@cdrage Can you please provide the user acceptance scenario for this?

**Comment by cdrage** [comment]
> @cdrage Can you please provide the user acceptance scenario for this?

Unsure what you mean by this. But essentially we just need tests for `ClonePath` as I guess the acceptance?
