### ISSUE TITLE
Dosen't produce any error for unreachable custer

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#3489]
/kind bug

## What versions of software are you using?

**Operating System:** supported(fedora)

**Output of `odo version`:** master

## How did you run odo exactly?
```
$ odo version                 
I0703 18:13:07.984099  159771 cert_rotation.go:137] Starting client certificate rotation controller
odo v1.2.3 (33a73e351)
$ odo create --downloadSource
Experimental mode is enabled, use at your own risk

I0703 18:13:46.959177  160041 cert_rotation.go:137] Starting client certificate rotation controller
? Which devfile component type do you wish to create  [Use arrows to move, type to filter]
 
 
 
>
 
 
```

## Actual behaviour
Doesn't show any errors or cluster not reachable 

## Expected behaviour
Should show an error if server is not reachable or similar message.

## Any logs, error output, etc?

N/A

**Comment by kadel** [comment]
> $ odo create --downloadSource
> Experimental mode is enabled, use at your own risk
> 
> I0703 18:13:46.959177  160041 cert_rotation.go:137] Starting client certificate rotation controller
> ? Which devfile component type do you wish to create  [Use arrows to move, type to filter]
>  
>  
>  
> >

this runs odo in interactive mode, the failure will happen after you go through tall the questsion

/priority low
/area UX
