### ISSUE TITLE
odo project create throws error of connection refused on ppc64le

### ISSUE THREAD

**Issue by sarveshtamba** [openshift/odo#3491]
I have made changes to the `scripts/openshiftci-presubmit-all-tests.sh` and `scripts/configure-installer-tests-cluster.sh` for Power on the lines of the [Z changes](https://github.com/zhengxiaomei123/odo/commit/63913d652fef0f31c2a61b4b77e5a6c447ec9f0b).
Also done the setup required like creating the secret to pull redhat registry images. Currently I am trying to run the `scripts/openshiftci-presubmit-all-tests.sh` and seeing the below issues for `test-cmd-link-unlink` test suite:
```
Summarizing 5 Failures:

[Fail] odo link and unlink command tests When handling link/unlink between components [It] should successfully delete component after linked component is deleted
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo link and unlink command tests When handling link/unlink between components [It] should link the frontend application to the backend and then unlink successfully
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo link and unlink command tests [BeforeEach] When handling link/unlink between components Wait till frontend dc rollout properly after linking the frontend application to the backend
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo link and unlink command tests [BeforeEach] When link between components using wrong port should fail
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo link and unlink command tests [BeforeEach] when running help for link command should display the help
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

Ran 6 of 177 Specs in 104.869 seconds
FAIL! -- 1 Passed | 5 Failed | 0 Pending | 171 Skipped


Ginkgo ran 1 suite in 1m49.571020075s
Test Suite Failed
make: *** [Makefile:159: test-cmd-link-unlink] Error 1
```
Attaching detailed test run and some post failure investigation steps - 
[odo_test-cmd-link-unlink_failures_ppc64le.txt](https://github.com/openshift/odo/files/4878282/odo_test-cmd-link-unlink_failures_ppc64le.txt)

**Comment by sarveshtamba** [comment]
@amitkrout ^^

**Comment by amitkrout** [comment]
``````
Running odo with args [odo project create mdztesrmaf -w -v4]
[odo]  •  Waiting for project to come up  ...
[odo]  ✗  Waiting for project to come up [4ms]
[odo]  ✗  Get https://api.shivani2.example.com:6443/apis/project.openshift.io/v1/projects?fieldSelector=metadata.name%3Dmdztesrmaf&watch=true: dial tcp 9.20.204.72:6443: connect: connection refused
```
We had also similar script failure on prow in the early stage of our test migration. Surprisingly it has not been reported in odo github. may be we consider that a very rare flake which even we did not see down the line. Anyway @sarveshtamba thanks for the issue. 

ping @girishramnani

**Comment by kadel** [comment]
> We had also similar script failure on prow in the early stage of our test migration. Surprisingly it has not been reported in odo github. may be we consider that a very rare flake which even we did not see down the line. Anyway @sarveshtamba thanks for the issue.

this look like an issue with the clutter or network

**Comment by sarveshtamba** [comment]
@kadel do you suggest I check anything with the cluster or network at my end?

**Comment by amitkrout** [comment]
> @kadel do you suggest I check anything with the cluster or network at my end?

Probably it network glitch. @sarveshtamba How many times this issue has been hit ? is it the link test only you are only hitting the issue ?

**Comment by sarveshtamba** [comment]
Successfully executed ODO test suite 'test-cmd-link-unlink' on Openshift 4.4 Cluster.
[odo_test-cmd-link-unlink_ppc64le_ocp4.4.txt](https://github.com/openshift/odo/files/4957732/odo_test-cmd-link-unlink_ppc64le_ocp4.4.txt)

**Comment by sarveshtamba** [comment]
@amitkrout Facing the following issues in `test-cmd-link-unlink` test suite:-
```
Summarizing 3 Failures:

[Fail] odo link and unlink command tests When link between components using wrong port [It] should fail
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo link and unlink command tests When handling link/unlink between components [It] should link the frontend application to the backend and then unlink successfully
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo link and unlink command tests When handling link/unlink between components [It] Wait till frontend dc rollout properly after linking the frontend application to the backend
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

Ran 6 of 184 Specs in 209.740 seconds
FAIL! -- 3 Passed | 3 Failed | 0 Pending | 178 Skipped


Ginkgo ran 1 suite in 3m36.731273535s
Test Suite Failed
make: *** [Makefile:172: test-cmd-link-unlink] Error 1
```

Attaching the detailed spec failure log -
[odo_test-cmd-link-unlink_failures_ppc64le_1.txt](https://github.com/openshift/odo/files/5097996/odo_test-cmd-link-unlink_failures_ppc64le_1.txt)

**Comment by amitkrout** [comment]
We hit similar issue in prow CI too - https://github.com/openshift/odo/issues/3754

**Comment by sarveshtamba** [comment]
Will track this common issue in #3454 .
