### ISSUE TITLE
Component push throws error of "Waiting for component to start" on ppc64le

### ISSUE THREAD

**Issue by sarveshtamba** [openshift/odo#3497]
I have made changes to the `scripts/openshiftci-presubmit-all-tests.sh` and `scripts/configure-installer-tests-cluster.sh` for Power on the lines of the [Z changes](https://github.com/zhengxiaomei123/odo/commit/63913d652fef0f31c2a61b4b77e5a6c447ec9f0b).
Also done the setup required like creating the secret to pull redhat registry images. Currently I am trying to run the `scripts/openshiftci-presubmit-all-tests.sh` and seeing the below issues for `test-cmd-pref-config` test suite:
```
Summarizing 1 Failure:

[Fail] odo preference and config command tests when using --now with config command [It] should successfully set and unset variables
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

Ran 15 of 177 Specs in 130.070 seconds
FAIL! -- 14 Passed | 1 Failed | 0 Pending | 162 Skipped


Ginkgo ran 1 suite in 2m14.896996829s
Test Suite Failed
make: *** [Makefile:189: test-cmd-pref-config] Error 1
```
Attaching detailed test run and some post failure investigation steps - 
[odo_test-cmd-pref-config_failures_ppc64le.txt](https://github.com/openshift/odo/files/4882816/odo_test-cmd-pref-config_failures_ppc64le.txt)

**Comment by sarveshtamba** [comment]
cc:- @amitkrout ^^

**Comment by jichenjc** [comment]
seems should not related to p/z arch ? looks like a config set failed?

**Comment by amitkrout** [comment]
```
[odo]  •  Waiting for component to start  ...
[odo] I0707 01:47:33.480309   58445 occlient.go:1926] Status of nodejs-app-1-zlgls pod is Pending
[odo]  ✗  Waiting for component to start [2m]
[odo]  ⚠  Watch channel was closed
[odo]  ✗  watch channel was closed
```
@jichenjc I am sure config set is correct. it looks similar to https://github.com/openshift/odo/issues/3454.

**Comment by sarveshtamba** [comment]
@amitkrout do you want me to check anything wrt config set?

**Comment by amitkrout** [comment]
> @amitkrout do you want me to check anything wrt config set?

@sarveshtamba Not required. From the log output i do not see anything weird w.r.t. config set.

**Comment by sarveshtamba** [comment]
Successfully executed ODO test suite 'test-cmd-pref-config' on Openshift 4.4 Cluster.
[odo_test-cmd-pref-config_ppc64le_ocp4.4.txt](https://github.com/openshift/odo/files/4957720/odo_test-cmd-pref-config_ppc64le_ocp4.4.txt)

**Comment by sarveshtamba** [comment]
@amitkrout Facing the following issues in `test-cmd-pref-config` test suite:-
```
Summarizing 1 Failure:

[Fail] odo preference and config command tests when using --now with config command [It] should successfully set and unset variables
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

Ran 15 of 184 Specs in 91.605 seconds
FAIL! -- 14 Passed | 1 Failed | 0 Pending | 169 Skipped


Ginkgo ran 1 suite in 1m36.748016712s
Test Suite Failed
make: *** [Makefile:202: test-cmd-pref-config] Error 1
```

Attaching the detailed spec failure log - 
[odo_test-cmd-pref-config_failures_ppc64le_1.txt](https://github.com/openshift/odo/files/5101462/odo_test-cmd-pref-config_failures_ppc64le_1.txt)

**Comment by prietyc123** [comment]
Its again the same issue that has been reported with `test-cmd-app` https://github.com/openshift/odo/issues/3530#issuecomment-681098317

**Comment by amitkrout** [comment]
Same issue we have been hitting in prow CI too - https://github.com/openshift/odo/issues/3754

**Comment by kadel** [comment]
https://github.com/openshift/odo/pull/3851 should make it easy to see the reason for this failure

**Comment by sarveshtamba** [comment]
Will track this common issue in #3454 .
