### ISSUE TITLE
Test failures while running `test-cmd-watch` test suite on ppc64le

### ISSUE THREAD

**Issue by sarveshtamba** [openshift/odo#3500]
I have made changes to the `scripts/openshiftci-presubmit-all-tests.sh` and `scripts/configure-installer-tests-cluster.sh` for Power on the lines of the [Z changes](https://github.com/zhengxiaomei123/odo/commit/63913d652fef0f31c2a61b4b77e5a6c447ec9f0b).
Also done the setup required like creating the secret to pull redhat registry images. Currently I am trying to run the `scripts/openshiftci-presubmit-all-tests.s` and seeing the below issues for `test-cmd-watch` test suite:
```
Summarizing 1 Failure:

[Fail] odo watch command tests when running help for watch command [It] should display the help
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:67

Ran 4 of 177 Specs in 16.146 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 173 Skipped


Ginkgo ran 1 suite in 21.055101896s
Test Suite Failed
make: *** [Makefile:280: test-cmd-watch] Error 1
```
Attaching detailed test run and some post failure investigation steps - 
[odo_test-cmd-watch_failures_ppc64le.txt](https://github.com/openshift/odo/files/4884101/odo_test-cmd-watch_failures_ppc64le.txt)

**Comment by sarveshtamba** [comment]
cc:- @amitkrout ^^

**Comment by amitkrout** [comment]
```
to contain substring
        <string>: git components
```
Test it on latest master odo binary. It should work.
/close
Feel free to reopen if you hit it again

**Comment by sarveshtamba** [comment]
Works with latest master odo:-

```
+ make test-cmd-watch
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=2 -focus="odo watch command tests" tests/integration/
Running Suite: Integration Suite
================================
Random Seed: 1594279922 - Will randomize all specs
Will run 177 specs

Running in parallel across 2 nodes

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•
Ran 4 of 177 Specs in 14.328 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 173 Skipped


Ginkgo ran 1 suite in 19.250429218s
Test Suite Passed
+ odo logout
Logged "kube:admin" out on "https://api.shivani2.example.com:6443"
```
Thanks!
