### ISSUE TITLE
Automate documentation syncing to odo.dev

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3511]
The current process for updating documentation is quite confusing.
Especially when someone updates `docs/public` in master it is not apparent that there is manual process that needs to be followed in order to update those files in odo.dev webpage.

This needs to be automated so the only thing that is needed is just modifying the markdown or asciidoc files.

This could be done by Prow or Travis-CI job running whenever there is change on the master branch.

/priority medium
/kind documentation

**Comment by valaparthvi** [comment]
/close

With Docusaurus in place, I think it is safe to close this issue.
