### ISSUE TITLE
Test failures while running `test-operator-hub` test suite on ppc64le

### ISSUE THREAD

**Issue by sarveshtamba** [openshift/odo#3512]
I have made changes to the `scripts/openshiftci-presubmit-all-tests.sh` and `scripts/configure-installer-tests-cluster.sh` for Power on the lines of the [Z changes](https://github.com/zhengxiaomei123/odo/commit/63913d652fef0f31c2a61b4b77e5a6c447ec9f0b).
Also done the setup required like creating the secret to pull redhat registry images. Currently I am trying to run the `scripts/openshiftci-presubmit-all-tests.s` and seeing the below issues for `test-operator-hub` test suite:
```
Summarizing 7 Failures:

[Fail] odo service command tests for OperatorHub When using from-file option [JustBeforeEach] should fail to create service if metadata doesn't exist or is invalid
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

[Fail] odo service command tests for OperatorHub JSON output [JustBeforeEach] listing catalog of services
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

[Fail] odo service command tests for OperatorHub When operator backed services are created [JustBeforeEach] should list the services if they exist
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

[Fail] odo service command tests for OperatorHub When creating an operator backed service [JustBeforeEach] should be able to create EtcdCluster from its alm example
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

[Fail] odo service command tests for OperatorHub When experimental mode is enabled [JustBeforeEach] should list operators installed in the namespace
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

[Fail] odo service command tests for OperatorHub When using from-file option [JustBeforeEach] should be able to create a service
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

[Fail] odo service command tests for OperatorHub When using dry-run option to create operator backed service [JustBeforeEach] should only output the definition of the CR that will be used to start service
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:41

Ran 7 of 7 Specs in 453.812 seconds
FAIL! -- 0 Passed | 7 Failed | 0 Pending | 0 Skipped
--- FAIL: TestOperatorhub (453.81s)
FAIL

Ginkgo ran 1 suite in 7m38.47119071s
Test Suite Failed
make: *** [Makefile:353: test-operator-hub] Error 1
```
Attaching detailed test run and some post failure investigation steps - 
[odo_test-operator-hub_failures_ppc64le.txt](https://github.com/openshift/odo/files/4890144/odo_test-operator-hub_failures_ppc64le.txt)

**Comment by sarveshtamba** [comment]
cc:- @amitkrout ^^

**Comment by amitkrout** [comment]
```
Running oc with args [oc get csv]
[oc] No resources found in yrofhaucfo namespace.
```

@sarveshtamba You need to setup operator in ```./scripts/configure-installer-tests-cluster.sh``` otherwise it won't get the required resource. 

For your reference you can check how it has been done - https://github.com/openshift/odo/blob/master/scripts/configure-installer-tests-cluster.sh#L56

**Comment by sarveshtamba** [comment]
This is not supported on Z for lack of executable format and removed from Z as well ( https://github.com/openshift/odo/commit/960a6d408af63543214070fa824a1282c1cbbcf5 ). Closing this issue for now, will revisit if required later.
