### ISSUE TITLE
Test failures while running `test-e2e-beta` test suite on ppc64le

### ISSUE THREAD

**Issue by sarveshtamba** [openshift/odo#3513]
I have made changes to the `scripts/openshiftci-presubmit-all-tests.sh` and `scripts/configure-installer-tests-cluster.sh` for Power on the lines of the [Z changes](https://github.com/zhengxiaomei123/odo/commit/63913d652fef0f31c2a61b4b77e5a6c447ec9f0b).
Also done the setup required like creating the secret to pull redhat registry images. Currently I am trying to run the `scripts/openshiftci-presubmit-all-tests.s` and seeing the below issues for `test-e2e-beta` test suite:
```
Summarizing 3 Failures:

[Fail] odo core beta flow when component is in the current directory [It] create local java component and push code
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo core beta flow [BeforeEach] when component is in the current directory 'odo component' should fail if there already is .odo dir
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

[Fail] odo core beta flow when --context flag is used [It] create local java component and push code
/usr/local/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34

Ran 6 of 21 Specs in 257.022 seconds
FAIL! -- 3 Passed | 3 Failed | 0 Pending | 15 Skipped


Ginkgo ran 1 suite in 4m28.915432231s
Test Suite Failed
make: *** [Makefile:307: test-e2e-beta] Error 1
```
Attaching detailed test run and some post failure investigation steps - 
[odo_test-e2e-beta_failures_ppc64le.txt](https://github.com/openshift/odo/files/4891464/odo_test-e2e-beta_failures_ppc64le.txt)

**Comment by sarveshtamba** [comment]
cc:- @amitkrout ^^

**Comment by amitkrout** [comment]
same failures has been reported in #3454, #3491 and #3497 
/close
