### ISSUE TITLE
Implement `hotReloadCapable`  flags from devfile v2 spec

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3548]
https://github.com/devfile/kubernetes-api/issues/64

Let's implement support for `restartOnChange` field as defined in the above issue

/triage needs-information

**Comment by kadel** [comment]
I've just opened PR to add those fields to devfile v2 spec https://github.com/devfile/kubernetes-api/pull/96

**Comment by adisky** [comment]
@kadel little confused on `backgroud` flag, we determine the process has to be run in background by its kind (I believe kind is for this purpose), am i missing some motive behind adding the `background` flag?

**Comment by dharmit** [comment]
Scope of this issue is only for `restartOnChange`. `background` will be handled separately.

**Comment by kadel** [comment]
> Scope of this issue is only for `restartOnChange`. `background` will be handled separately.

Opened separate issue for `background` https://github.com/openshift/odo/issues/3580

**Comment by kadel** [comment]
PR https://github.com/devfile/api/pull/96 got merged

Please note that the field was renamed to `hotReloadCapable`

/remove-status blocked
