### ISSUE TITLE
preStart lifecycle event support

### ISSUE THREAD

**Issue by upLukeWeston** [openshift/odo#3565]
## User Story
As a stack creator, I want to be able to define commands that will be run before any containers have been initialized during `odo push` (preStart events), in the form of [Init Containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/).

## Acceptance Criteria
- It should follow the specification as defined in [devfile/kubernetes-api#32](https://github.com/devfile/kubernetes-api/issues/32) to support execution of the commands based on the events.
- `preStart` events should run before any of the other containers are started. Refer to design and discussions [here](https://github.com/openshift/odo/pull/3413/commits/9d94c008015c8f76fd3991c30b1d48da00626955) for further details.

## Links
- Related issue: [devfile/kubernetes-api#32](https://github.com/devfile/kubernetes-api/issues/32)
- [Proposal for lifecycle events](https://github.com/openshift/odo/pull/3413/commits/9d94c008015c8f76fd3991c30b1d48da00626955)

/kind user-story
/area devfile

**Comment by maysunfaisal** [comment]
will check if we need this issue or it can be covered by https://github.com/openshift/odo/issues/3569 in a single sprint

**Comment by maysunfaisal** [comment]
Had discussion about this on Jul 21'st odo contributors meeting https://docs.google.com/document/d/127JAIs5NJze9W5yVOpULgnD-2HXuGZu1x6_LXGd8keY

To summarize,
```
Q. Acc to odo proposal doc, preStart translates to init containers. But init containers are mutually exclusive to app containers in a pod acc to Kube doc. So is there a point to preStart if the preStart commands won't have a pvc? Do we rely on devfile authors to be aware of this?

A. Start as init containers, check if access to /projects break sync. We could document it as a warning. Most probably this use case will be  for something external
```

**Comment by maysunfaisal** [comment]
Ran into a few issues during implementation of `preStart`. Raised a few points for discussion here https://github.com/devfile/kubernetes-api/issues/105
