### ISSUE TITLE
preStop lifecycle event support

### ISSUE THREAD

**Issue by upLukeWeston** [openshift/odo#3566]
## User Story
As a stack creator, I want to be able to define commands that will be executed before my component is deleted as a part of `odo delete` (preStop events)

## Acceptance Criteria
- It should follow the specification as defined in [devfile/kubernetes-api#32](https://github.com/devfile/kubernetes-api/issues/32) to support execution of the commands based on the events.
- `preStop` events should run before the component is deleted. Refer to design and discussions [here](https://github.com/openshift/odo/pull/3413/commits/9d94c008015c8f76fd3991c30b1d48da00626955) for further details.

## Links
- Related issue: [devfile/kubernetes-api#32](https://github.com/devfile/kubernetes-api/issues/32)
- [Proposal for lifecycle events](https://github.com/openshift/odo/pull/3413/commits/9d94c008015c8f76fd3991c30b1d48da00626955)

/kind user-story
/area devfile

**Comment by maysunfaisal** [comment]
will check if we need this issue or it can be covered by parent issue https://github.com/openshift/odo/issues/3569 in a single sprint
