### ISSUE TITLE
Add preStart, preStop and postStop lifecycle event support

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3569]
/kind user-story

## User Story
As a stack creator, I want to make use of the preStart, preStop and postStop events defined in the devfile 2.0.  
Devfile 2.0 providers ability to execute commands based on lifecycle events.

Overall design of how to handle those lifecycle events is defined in https://github.com/openshift/odo/pull/3413.

## Acceptance Criteria 
- [ ] It should follow the specification as defined in https://github.com/che-incubator/devworkspace-api/issues/32 to support execution of the commands based on the events.

## Links 
- Related issue: https://github.com/che-incubator/devworkspace-api/issues/32
https://github.com/openshift/odo/pull/3413

/kind user-story
/area devfile

**Comment by neeraj-laad** [comment]
@elsony There are separate issue for each of these events too.. Looks  @upLukeWeston created them while you had created a common one for this too.

We should close this or close the other three.

https://github.com/openshift/odo/issues/3565
https://github.com/openshift/odo/issues/3566
https://github.com/openshift/odo/issues/3577

**Comment by elsony** [comment]
Closing off this one since the 3 events will be implemented separately via #3565, #3566 and #3577
