### ISSUE TITLE
Download of starter project stored in a secure repo

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3574]
/kind user-story

## User Story
As a devfile creator, I want to store my starter project in a secured repo which is different from a secured devfile registry.

As part of https://github.com/openshift/odo/issues/2893, odo supports accessing a secured devfile registry.  That item only covers access to a secured devfile repo and also the download of the devfile stored in the same repo as the devfile registry.  However, a typical stack may store their starter project in another repo which may require different authentication. 

## Acceptance Criteria 
- [ ] It should provide a way to authenticate and access starter project that are stored under a different secured repo provided by the stack creator.

## Links 
- Related issue: https://github.com/openshift/odo/issues/2893

/kind user-story
/area devfile

**Comment by GeekArthur** [comment]
Duplicate of https://github.com/openshift/odo/issues/3567, we may close 3567 and leave this one open since this one already triages to sprint 187.

**Comment by GeekArthur** [comment]
The design proposal of the code flow:
We add the new flag (eg. `--starter-token`) for `odo create` to let user pass in the token for only downloading start project. Then from odo perspective, odo should check the `--starter-token` firstly to use for downloading start project, if the `--starter-token` is not set, odo should do:
- If the registry is secure registry, odo uses the secure registry token to download starter project
- If the registry is not secure registry, odo downloads starter project without token
