### ISSUE TITLE
Move container image used in springboot devfile to some odo owned image repository

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3578]
The image we are using in java-springboot devfile is in @maysunfaisal 's personal image repository, it should be moved to some odo owned repository
https://github.com/odo-devfiles/registry/blob/master/devfiles/java-springboot/devfile.yaml#L12

**Comment by adisky** [comment]
Got image pull error whole day
```
  Normal   Started           5m26s                kubelet, crc-45nsk-master-0  Started container copy-supervisord
  Warning  Failed            118s                 kubelet, crc-45nsk-master-0  Failed to pull image "maysunfaisal/springbootbuild": rpc error: code = Unknown desc = Error writing blob: error storing blob to file "/var/tmp/storage760563944/4": read tcp 192.168.130.11:46146->104.18.124.25:443: read: connection reset by peer
  Normal   Pulling           47s (x2 over 5m26s)  kubelet, crc-45nsk-master-0  Pulling image "maysunfaisal/springbootbuild"
  Warning  Failed            47s                  kubelet, crc-45nsk-master-0  Error: ErrImagePull
  Warning  Failed            47s                  kubelet, crc-45nsk-master-0  Failed to pull image "maysunfaisal/springbootruntime": rpc error: code = Unknown desc = Error writing blob: error storing blob to file "/var/tmp/storage1863
```

**Comment by girishramnani** [comment]
I agree that we need to move from personal image registries but the reason for that is so that we can productise them ( control changes to them ). 
Not sure if being in mayson's personal registry would give you this image pull error?

**Comment by adisky** [comment]
> I agree that we need to move from personal image registries but the reason for that is so that we can productise them ( control changes to them ).
> Not sure if being in mayson's personal registry would give you this image pull error?

I thought maysun might restricted access to his repo :smile:, I just wanted to point here with personal repositories if you get any error you cannot check the reason behind it. I get image pull error from quay also but then you get the status it is down

**Comment by maysunfaisal** [comment]
AFAIK my dockerhub springboot image is not restricted.

I can give you the dockerfiles to build and push to a registry of your choosing, or you can just pull my image, tag and push to the registry of your choosing 🤔

**Comment by adisky** [comment]
> > I agree that we need to move from personal image registries but the reason for that is so that we can productise them ( control changes to them ).
> > Not sure if being in mayson's personal registry would give you this image pull error?
> 
> I thought maysun might restricted access to his repo , I just wanted to point here with personal repositories if you get any error you cannot check the reason behind it. I get image pull error from quay also but then you get the status it is down

said in sarcasm :), it might be some network problem at my end, this error just caught my attention to the issue.

**Comment by girishramnani** [comment]
we need to update the examples of springboot present in odo repo as well

**Comment by gorkem** [comment]
Can we use images supported by runtimes team? @metacosm any suggestions ?

**Comment by amitkrout** [comment]
> The image we are using in java-springboot devfile is in @maysunfaisal 's personal image repository,

@adisky Can you please link the image repository

**Comment by adisky** [comment]
as discussed with @maysunfaisal he used custom images to showcase devfile capability to have separate build and run containers.
@girishramnani  suggested to use image from `che` repository as we do not want to maintain our images. Devfile ability we can show in docs and demo.
I feel we need atleast one devfile with multiple containers for testing purpose to catch errors like these https://github.com/openshift/odo/issues/3711

@tkral @girishramnani Please suggest what needs to be done here.

**Comment by kadel** [comment]
> I feel we need atleast one devfile with multiple containers for testing purpose to catch errors like these #3711

If it is just for testing purposes it doesn't have to be in odo devfile registry, we can just include devfile in our testing directory.


> @girishramnani suggested to use image from `che` repository as we do not want to maintain our images. Devfile ability we can show in docs and demo.

Yes, ideally we should reuse existing images. But if for some reason we can't or don't want to we can build our own, that is ok. But we just need to be aware of the maintenance cost.


If we need a repo for examples it should be in `odo-devfile` Github organization https://github.com/odo-devfile.
If we need custom build images we should use `odo-dev` organization that we have on Quay  (https://quay.io/organization/odo-dev)  and have image repo linked to GitHub repo with auto build enabled. (If you need permission to push images there, send me you Quay user name I'll add you)

**Comment by adisky** [comment]
@kadel che used java maven image for spring boot devfile https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-spring/devfile.yaml#L20, I am thinking to update our springboot devfile in registry with the same image  `quay.io/eclipse/che-java11-maven:nightly`.

For test purpose we can have a multiple containers devfile using the same image as build and run container?

**Comment by kadel** [comment]
> For test purpose we can have a multiple containers devfile using the same image as build and run container?

Not sure how much that would make sense.
I don't think we need multi-container devfile in the registry just for sake of having it.

If wee need multi-container devfile for our test suite it should be a special devfile that is in odo repo together with other test fixtures.

**Comment by adisky** [comment]
> > For test purpose we can have a multiple containers devfile using the same image as build and run container?
> 
> Not sure how much that would make sense.
> I don't think we need multi-container devfile in the registry just for sake of having it.
> 
> If wee need multi-container devfile for our test suite it should be a special devfile that is in odo repo together with other test fixtures.

sorry, i have not explained clearly.
I meant the same having a multicontainers devfile in our odo repo for test suite.
