### ISSUE TITLE
Two devfile component deployed with same name, second component overrides the first one.

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3579]
/kind discussion

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## Actual behavior
If you try two create two devfile component with same, neither `odo push` nor `odo create` gives error. 
e.g 
* create a nodejs component
$ odo create nodejs unique 
$ odo push
* create a springboot component with same name from a different dir
$ odo create springboot unique
$ odo push

odo push succeeds here, with springboot component overridden the nodejs component.

## Expected behavior
odo create should give error, if the devfile component with same name already present on the cluster.

**Comment by girishramnani** [comment]
but this is a concious decision that you as a user are making, so isn't this acceptable?

**Comment by adisky** [comment]
i am not sure about the behavior here, but shouldn't `odo create` should give error if you try to create component with same name?

**Comment by girishramnani** [comment]
Yeah I suppose so

**Comment by adisky** [comment]
got your point we are doing same in s2i, I did not found any harm with this behavior.
/close
