### ISSUE TITLE
Support PROJECTS_ROOT env variable in odo

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3581]
/kind user-story

## User Story
As a user, I want to be able to configure the sync folder using the `$PROJECTS_ROOT` environment variable in my terminal, as per the Devfile 2.0 spec. 

## Acceptance Criteria 
- [ ] It should replace the existing `$CHE_PROJECTS_ROOT` variable used in Odo, and function the same.
- [ ] The sample odo devfiles in github.com/odo-devfiles should be updated accordingly
- [ ] Odo's test automation should be updated accordingly

## Links 
- Related issue: https://github.com/openshift/odo/issues/3494

/kind user-story
/area devfile

**Comment by johnmcollier** [comment]
As a side note, I'll be handling this with the other changes in https://github.com/openshift/odo/issues/3494, but thought I'd open a separate story since this change is not directly related to the changes in https://github.com/openshift/odo/issues/3494.

**Comment by elsony** [comment]
This one is done on Sprint 187
