### ISSUE TITLE
Watch command should better handle file synchronization when push command is invoked before/after the watch

### ISSUE THREAD

**Issue by jgwest** [openshift/odo#3585]
The current behaviour of the watch command assumes that the state of the filesystem is synchronized with the state of the pod. This assumption is not correct, as this may not be true in all cases (depending on user behaviour and when push was invoked).

Likewise, the current behaviour of the push command assumes that the index data under `.odo` is synchronized with the state of the pod. This may not be the case if the watch command is bypassing the index data update logic.

### Scenario A - On launch, `odo watch` assumes that the current filesystem is synchronized to the pod:
1) odo push a generic project
2) Change some source file A
3) odo watch that project
4) Change some other source file B

After step 4's `odo watch` push operation completes:
- Expected behaviour: The k8s pod _should_ include the change made in step 2
- Actual behaviour: The k8s pod _does not_ include the change made in step 2

### Scenario B - `odo watch` doesn't update index data
1) odo push a generic project
2) Start watch command
3) Update some source file A and wait for deploy
4) Terminate watch command
5) odo push the project

- Expected behaviour: Source file A is not synchronized to the pod, because it has not been updated since step 3.
- Actual behaviour: Source file A _is_ synchronized to the pod, because the index file still represents the old version of the file. (Note: this is our expected actual behaviour, I need to verify this is true.)

Related issues/PRs:
https://github.com/openshift/odo/issues/3345
https://github.com/openshift/odo/pull/3536

/kind bug

**Comment by kadel** [comment]
> ### Scenario A - On launch, `odo watch` assumes that the current filesystem is synchronized to the pod:

odo currently assumes that it is executed after `odo push`.
Could be this solved by adding some documentation that explains this?
Another solution might be to simply invoke `odo push` at the beginning of `odo watch` execution. But this will create problems when you modify files while the initial "push" is running. We will have to make sure that the filesystem watching starts right at the beginning  before we invoke initial "push" so we can catch up with changes



> ### Scenario B - `odo watch` doesn't update index data

This is a clear bug.
