### ISSUE TITLE
Move Operator Hub integration out of Experimental mode

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3595]
Currently, Operator Hub specific commands are working when Experimental mode is enabled. Move these out of Experimental mode and make sure these commands work in tandem with Service Catalog (when it's enabled).

/area service-operators
/area service
/assign

**Comment by dharmit** [comment]
On minishift:
```sh
$ oc get csv
error: the server doesn't have a resource type "csv"
```
On CRC:
```sh
oc get csv
NAME                                  DISPLAY                    VERSION             REPLACES   PHASE
etcdoperator.v0.9.4-clusterwide       etcd                       0.9.4-clusterwide              Succeeded
service-binding-operator.v0.1.1-352   Service Binding Operator   0.1.1-352                      Succeeded
```

@kadel @girishramnani I'm thinking about adding a check for something like `IsCSVSupported`. If it is, we assume that user's working with Operators since the cluster has got the required API resource. If not, we assume that it's 3.x and support Service Catalog instead. WDYT?

**Comment by kadel** [comment]
> @kadel @girishramnani I'm thinking about adding a check for something like `IsCSVSupported`. If it is, we assume that user's working with Operators since the cluster has got the required API resource. If not, we assume that it's 3.x and support Service Catalog instead. WDYT?

+1 makes sense

**Comment by dharmit** [comment]
Just being explicit since I missed mentioning in previous comment - this would mean that even if user installs service catalog on 4.x, we'll not try to support it. Installing service catalog is possible up to 4.4. 4.5 onwards, it's neither documented, nor do the commands provided in 4.4 docs work to set it up.

So it's like:
1. If user's running 3.x, support only Service Catalog
2. If user's running 4.x, support only Operator Hub.

Sounds OK? @kadel @girishramnani

**Comment by kadel** [comment]
What about Kubernetes? I could have cluter with both enabled Service Catalog and OperatorHub

**Comment by dharmit** [comment]
> What about Kubernetes? I could have cluter with both enabled Service Catalog and OperatorHub

That would again fall into the category of `IsCSVSupported`. If yes, we assume the user's working with Operators.

Do we have any idea about how widely service catalog might be used in conjunction with k8s?

**Comment by kadel** [comment]
I think that with Kubernetes ServiceCatlog is used much more than the
Operator hub.
But I don't have any numbers to prove this, it is just my hunch.

**Comment by girishramnani** [comment]
Charlie might have an overlap with you on this @dharmit
