### ISSUE TITLE
Add a PreValidate function to generic CLI Run

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3604]
/kind discussion
/kind code-refactoring

## Description
We should add a`PreValidate` function to generic cli run, to validate flags, conflicting flags, basically validations that could be done before `Complete.` or context initialization
https://github.com/openshift/odo/blob/master/pkg/odo/genericclioptions/runnable.go#L14

e.g. checking component existence with path value
checking about config flags
validating registry
validating some devfile fields like `volume size`

**Comment by GeekArthur** [comment]
I agree with this proposal as all the CLI arguments and flags validations should/could be done before `Complete` generic function. Currently we only have one `Validate` generic function and runs after `Complete` generic function according to the running sequence of generic functions in `GenericRun`.
