### ISSUE TITLE
odo log -f terminates earlier

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3610]
/kind bug
/kind flake

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
This is hit in the CI. You can also reproduce it locally by running the spec (keep trying until you reproduce it)

Spec : https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_log_test.go#L51

CI failure at line : https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3601/pull-ci-openshift-odo-master-v4.2-integration-e2e/1285441618282811392#1:build-log.txt%3A94332

## Actual behavior
```
 Running odo with args [odo log -f]
[odo] I0721 07:11:31.820487    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
[odo] I0721 07:11:31.820763    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml 
```

## Expected behavior
```program=devrun``` should be listed in the log output

## Any logs, error output, etc?
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3601/pull-ci-openshift-odo-master-v4.2-integration-e2e/1285441618282811392#1:build-log.txt%3A94345

**Comment by girishramnani** [comment]
the one approach that will work here is to increase the timeout - maybe 5s to be safe?

**Comment by girishramnani** [comment]
we could do something super intelligent like check between each 0.5s that the buffer size of the command has increased or not, if it hasn't that means the `odo log -f` has reached the end but I mean for what gain? 2-3s?

**Comment by amitkrout** [comment]
Refer - https://github.com/openshift/odo/pull/3613#issuecomment-662344950

**Comment by prietyc123** [comment]
One more occurence - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/10346/rehearse-10346-periodic-ci-openshift-odo-master-v4.6-integration-e2e-periodic/1292828790027718656#1:build-log.txt%3A748

**Comment by amitkrout** [comment]
Latest update - https://github.com/openshift/odo/pull/3613#issuecomment-664295219
