### ISSUE TITLE
url list and describe need update to display url defined in devfile endpoint entry

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#3615]
/area devfile
/area url

After https://github.com/openshift/odo/issues/3515 is implemented, Ingress/Route can be created via devfile endpoint definition during odo push. We need to update the logic of `url list` and `url describe` to properly display the url defined in endpoint entry.

## Acceptance Criteria 
- [ ] `url list` should display info of url defined in devfile endpoint entry, also should display it's state
- [ ] `url describe` should display info of url defined in devfile endpoint entry, also should display it's state

**Comment by kadel** [comment]
There is a related issue https://github.com/openshift/odo/issues/3718.

It might be better to address https://github.com/openshift/odo/issues/3718 before this one

**Comment by elsony** [comment]
Blocked by #3718

**Comment by kadel** [comment]
Wouldn't this be covered in https://github.com/openshift/odo/issues/3718 ?

**Comment by yangcao77** [comment]
Yes. This one will be covered in the same PR of #3718.
