### ISSUE TITLE
Update the parent devfile tests

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3638]
## Description
Parent devfile tests using open liberty devfile from an older commit, which contains `configuration`  that has been removed with new schema. Tests cannot be updated to current version of open liberty devfile as there are some issues with it that needs to be investigated.

https://raw.githubusercontent.com/odo-devfiles/registry/f56180b89556ee2945a355ac0dcf3428d3ab35c7/devfiles/java-openliberty/devfile.yaml

Devfiles used in parent tests:

- top parent:
 https://raw.githubusercontent.com/odo-devfiles/registry/f56180b89556ee2945a355ac0dcf3428d3ab35c7/devfiles/java-openliberty/devfile.yaml
- middle parent: 
https://gist.githubusercontent.com/mik-dass/6f88d133b73e90bc52ffcda92833b625/raw/cc46d1ba348cd085855f163b269c0f1be87226c4/devfile-middle.yaml
- child: 
https://github.com/openshift/odo/blob/master/tests/examples/source/devfiles/openliberty/devfile-with-multi-layer-parent.yaml#

Following things need to be done:
1. Middle devfile needs to be added in odo repo
2. Middle devfile needs to  be updated as per new schema (remove configration), currently it is referring old commit of upstream original devfile.
3. As discussed with @mik-dass some issues with the current upstream openliberty devfile.(needs investigation)

**Comment by adisky** [comment]
cc @mik-dass

**Comment by mik-dass** [comment]
I would try to get the middle layer in the odo repo in a seperate PR and will try to convert all the tests for parent to use a nodejs repo as I was facing issues with the open liberty devfile on the registry. @amitkrout WDYT?

**Comment by girishramnani** [comment]
we need to change openliberty to nodejs/maven-java test
