### ISSUE TITLE
Ask for images work on s390x arch

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3670]
/kind bug

## What versions of software are you using?

**Operating System:** 
 Red Hat Enterprise Linux 8.1 (Ootpa

**Output of `odo version`:**
odo v1.2.4 (b3cf59550)
Server: https://api.ocp.openstack:6443
Kubernetes: v1.18.3+6025c28
## How did you run odo exactly?
Enable odo CI on s390x platform

## Actual behavior
./scripts/openshiftci-presubmit-all-tests.sh

## Expected behavior
All the test passed 

## Any logs, error output, etc?
There are some hard code to import S2I images. These images only support amd64 arch which causes failed on s390x arch. 
For odo supported images e2e tests:
These images are:
`oc --request-timeout 5m import-image nodejs:latest --namespace=vsnyjhnygd --from=docker.io/centos/nodejs-12-centos7:latest --confirm`
`oc --request-timeout 5m import-image nodejs:latest --namespace=hcvvpyounm --from=docker.io/centos/nodejs-10-centos7:latest --confirm`
`oc --request-timeout 5m import-image nodejs:latest --namespace=qjycpyjbmo --from=registry.access.redhat.com/rhoar-nodejs/nodejs-10:latest --confirm`
For odo source e2e tests:
`oc --request-timeout 5m import-image dotnet:2.0 --namespace=uezadyekmn --from=registry.centos.org/dotnet/dotnet-20-centos7 --confirm`

**Comment by jichenjc** [comment]
@zhengxiaomei123 there is no centos on z at all.. so apparently need code change
can you paste the link of the code so that it will be easier to know the code comes from?

**Comment by zhengxiaomei123** [comment]
@jichenjc 
[nodejs-10-centos7:latest](https://github.com/openshift/odo/blob/56f860b361e2595b31fc14a09fa0e07263841705/tests/e2escenarios/e2e_images_test.go#L105)
[nodejs-12-centos7:latest](https://github.com/openshift/odo/blob/56f860b361e2595b31fc14a09fa0e07263841705/tests/e2escenarios/e2e_images_test.go#L110)
[rhoar-nodejs/nodejs-10](https://github.com/openshift/odo/blob/56f860b361e2595b31fc14a09fa0e07263841705/tests/e2escenarios/e2e_images_test.go#L100)

**Comment by zhengxiaomei123** [comment]
I think these tests are aim to verify `odo supported images ` , the registry is not important. So Can I request the PR to replaces these above images from other registry? If it is aim to verify the specific image from the specific registry, I think it is meaningless to test those images only for x86 arch. Is my understanding right?

**Comment by jichenjc** [comment]
@zhengxiaomei123 the supported statement might prove here:
https://github.com/openshift/odo  (Table 1. Supported container images ) 

for our platform, we can either use our own image to replace for s390x arch or skip the test..

**Comment by zhengxiaomei123** [comment]
`nodejs-10` and `nodejs-12` for OCP on s390 is available in the RH Registry.
https://catalog.redhat.com/software/containers/ubi8/nodejs-12/5d3fff015a13461f5fb8635a?architecture=s390x&container-tabs=overview
https://catalog.redhat.com/software/containers/ubi8/nodejs-10/5c839aa3d70cc51dd4c425d9?architecture=s390x&container-tabs=gti
https://catalog.redhat.com/software/containers/rhel8/nodejs-10/5ba1f2365a134643ef2f0188?architecture=s390x
https://catalog.redhat.com/software/containers/rhel8/nodejs-12/5d3fff06d70cc5521d0009c2?architecture=s390x
These images are also available for ocp on x86.

**Comment by jichenjc** [comment]
@zhengxiaomei123 but that's UBI, correct?  if so we need update doc to indicate what's really available and point to correct link

**Comment by zhengxiaomei123** [comment]
@amitkrout Since the odo-init-image has supported multi-arch platform, I think there should not be images which only for one x86 platform, Is it OK to replace the [nodejs-12-centos7:latest](https://github.com/openshift/odo/blob/56f860b361e2595b31fc14a09fa0e07263841705/tests/e2escenarios/e2e_images_test.go#L110) with [ubi8/nodejs-12](https://catalog.redhat.com/software/containers/ubi8/nodejs-12/5d3fff015a13461f5fb8635a?architecture=s390x&container-tabs=overview) and replace the [nodejs-10-centos7:latest](https://github.com/openshift/odo/blob/56f860b361e2595b31fc14a09fa0e07263841705/tests/e2escenarios/e2e_images_test.go#L105) with [ubi/nodejs-10](https://catalog.redhat.com/software/containers/ubi8/nodejs-10/5c839aa3d70cc51dd4c425d9?architecture=s390x&container-tabs=gti)  and replace the [rhoar-nodejs/nodejs-10](https://github.com/openshift/odo/blob/56f860b361e2595b31fc14a09fa0e07263841705/tests/e2escenarios/e2e_images_test.go#L100)  with [rhel8/nodejs10](https://catalog.redhat.com/software/containers/rhel8/nodejs-10/5ba1f2365a134643ef2f0188?architecture=s390x)?

**Comment by zhengxiaomei123** [comment]
> @zhengxiaomei123 but that's UBI, correct? if so we need update doc to indicate what's really available and point to correct link

I think we can add those images to doc.

**Comment by amitkrout** [comment]
> @amitkrout Since the odo-init-image has supported multi-arch platform, I think there should not be images which only for one x86 platform, Is it OK to replace the nodejs-12-centos7:latest image with ubi8/nodejs-12 and replace the nodejs-10-centos7:latest image with ubi/nodejs-10 and replace the rhoar-nodejs/nodejs-10 image with rhel8/nodejs10?

TBH i am not sure about the image part. @girishramnani @mohammedzee1000 PTAL

**Comment by mohammedzee1000** [comment]
> `nodejs-10` and `nodejs-12` for OCP on s390 is available in the RH Registry.
> https://catalog.redhat.com/software/containers/ubi8/nodejs-12/5d3fff015a13461f5fb8635a?architecture=s390x&container-tabs=overview
> https://catalog.redhat.com/software/containers/ubi8/nodejs-10/5c839aa3d70cc51dd4c425d9?architecture=s390x&container-tabs=gti
> https://catalog.redhat.com/software/containers/rhel8/nodejs-10/5ba1f2365a134643ef2f0188?architecture=s390x
> https://catalog.redhat.com/software/containers/rhel8/nodejs-12/5d3fff06d70cc5521d0009c2?architecture=s390x
> These images are also available for ocp on x86.

I think this should be ok so long as they are redhat supported. Still it is better if we can get confirmation from inside about these images
@hhorak is part of software collections. whyt?

**Comment by mohammedzee1000** [comment]
also @kadel @girishramnani wdyt

**Comment by kadel** [comment]
It would be interesting what images people using s390x typically use. 

I don't think that it makes sense to have the same set of images for both x86 and s390x.
We can drastically reduce the number of tests that we do on s390x to just bare minimum

**Comment by zhengxiaomei123** [comment]
> It would be interesting what images people using s390x typically use.
> 
> I don't think that it makes sense to have the same set of images for both x86 and s390x.
> We can drastically reduce the number of tests that we do on s390x to just bare minimum

The images are all about `nodejs` and `test-e2e-images`.  Nodejs is the offical supported in Odo. The tests are running to test these offical nodejs images. It's not s390x specific.

**Comment by zhengxiaomei123** [comment]
@kadel @mohammedzee1000 To seperate images for s390x and x86, I would like to create one different context and run all the spec that needs to be skipped on s390x and apply condition
if runtime.GOARCH == "s390x" {
				Skip("Skipping test because there is no supported builder image for s390x.")
			}

in ginkgo built-in tear down steps JustBeforeEach. I think it a good solution and will request the PR. Then please help review it. Thanks.

**Comment by zhengxiaomei123** [comment]
@amitkrout When testing the ubi8/nodejs-10 and ubi8/nodejs-12 and rhel8/nodejs-10 and rhel8/nodejs-12 for `test-e2e-images` case, I also go the error which you mentioned on #3307 and #3420 . It's here always. But for ubi7/nodejs-10 and ubi7/nodejs-12, the case passed and the error is not here. 
The full log I pasted here: https://tpaste.us/WRv0

**Comment by hhorak** [comment]
> I think this should be ok so long as they are redhat supported. Still it is better if we can get confirmation from inside about these images
> @hhorak is part of software collections. whyt?

I can confirm that these images are supported by Red Hat on s390x as well.

**Comment by mohammedzee1000** [comment]
@amitkrout @kadel  can we then consider adding these images to our testing without removing existing ones. 

They can be put under a separate test group if needed

**Comment by zhengxiaomei123** [comment]
@mohammedzee1000 Yes, I created a new separate context to involes those images for x86 not removing them in PR # 3744.
