### ISSUE TITLE
odo devfile push command integration tests (make test-integration-devfile) not work on IBM Z/P

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3671]
/kind feature

## Which functionality do you think we should add?
We are working on odo CI enablement for Z/P. For `make test-integration-devfile` , most of the tests failed because of error `exec format error`. The images defined in devfiles.yaml is only for amd64. 

## Why is this needed?
To enable the tests on IBM P/Z, the default images defined in devfiles.yaml should support s390x or ppcl64le.

**Comment by zhengxiaomei123** [comment]
The DefaultDevfileRegistryURL is "https://github.com/odo-devfiles/registry". The devfiles for java-sprintboot is "https://github.com/odo-devfiles/registry/blob/master/devfiles/java-springboot/devfile.yaml" . The container image in this devfile.yaml is `maysunfaisal/springbootbuild` ,which only support x86.

**Comment by zhengxiaomei123** [comment]
Same problem for java-quarkus , the container image used in [DefaultDevfileRegistryURL](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml) is `quay.io/eclipse/che-quarkus:nightly` ,which only support x86.

**Comment by zhengxiaomei123** [comment]
Same problem for java-quarkus , the container image used in [DefaultDevfileRegistryURL](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-maven/devfile.yaml) is `quay.io/eclipse/che-java11-maven:nightly`,which only support x86.

**Comment by zhengxiaomei123** [comment]
#3578

**Comment by zhengxiaomei123** [comment]
The container images used in the default devfile registry of odo doesn't support P and Z. Actually, the images used in default devfile registry is from personal repo and quay.io/eclipse repo. The images also don't support multi-arch. I think the images used in odo should change to use RH offically built images or RH offically registry (registry.access.redhat.com/) like S2I which support multi-arch.

**Comment by zhengxiaomei123** [comment]
@rgarg1 Is there any plan to support devfiles container image in RH offical registry? Thanks.

**Comment by PanYaLian** [comment]
@mohammedzee1000 Hope to get your comments, whether or when it is possible to replace container image in devfiles to support P and Z. Thanks

**Comment by zhengxiaomei123** [comment]
Hi @yselkowitz , Is there any plan to support devfile container images for multi-arch ? The images are `quay.io/eclipse/che-quarkus:nightly` and `quay.io/eclipse/che-java11-maven:nightly` and so on in repo `quay.io/eclipse/` .  Those images are required by odo using devfiles to create applications. Thanks.

**Comment by rgarg1** [comment]
@mohammedzee1000 @kadel For your visibility.

**Comment by sarveshtamba** [comment]
This issue is applicable for Power as well.

**Comment by zhengxiaomei123** [comment]
same issue with https://github.com/devfile/api/issues/244

**Comment by zhengxiaomei123** [comment]
Since the issue have been solved with the private registry . I would like to close this issue and move the discussion to 
Duplicate of #4228
