### ISSUE TITLE
odo service create from operator hub feature failed on IBM Z and P

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3672]
/kind feature

## Which functionality do you think we should add?
We are working on odo CI enablement for Z/P. For make test-operator-hub , most of the tests failed because of error exec format error. 
## Why is this needed?
To enable the tests on IBM P/Z, the default images used for operator-hub should support s390x or ppcl64le.

**Comment by kadel** [comment]
> To enable the tests on IBM P/Z, the default images used for operator-hub should support s390x or ppcl64le.

This is not something that we control. This needs to be solved on the Operators side.  Operators listed in the operator hub will have to have support for P/Z. 
Cluster administrator will have to ensure that the Operator hub lists only services that support the given architecture. 


/close

**Comment by zhengxiaomei123** [comment]
```
oc get csv -n openshift-operators
NAME                                  DISPLAY                    VERSION             REPLACES   PHASE
etcdoperator.v0.9.4-clusterwide       etcd                       0.9.4-clusterwide              Failed
mongodb-enterprise.v1.6.0             MongoDB                    1.6.0                          Failed
service-binding-operator.v0.1.1-352   Service Binding Operator   0.1.1-352                      Failed
```

**Comment by zhengxiaomei123** [comment]
./odo catalog list services
Operators available in the cluster
```
NAME                                    CRDs
etcdoperator.v0.9.4-clusterwide         EtcdCluster, EtcdBackup, EtcdRestore
mongodb-enterprise.v1.6.0               MongoDB, MongoDBUser, MongoDBOpsManager
service-binding-operator.v0.1.1-352     ServiceBindingRequest
```

**Comment by zhengxiaomei123** [comment]
```
./odo service create etcdoperator.v0.9.4-clusterwide/EtcdCluster
Deploying service of type: EtcdCluster
 ✓  Deploying service [7ms]
 ✓  Service '' was created

Progress of the provisioning will not be reported and might take a long time
You can see the current status by executing 'odo service list'
Optionally, link etcdoperator.v0.9.4-clusterwide to your component by running: 'odo link <component-name>'
```

**Comment by zhengxiaomei123** [comment]
I want to confirm that EtcdCluster service can be created from etcdoperator.v0.9.4-clusterwide operator.

**Comment by jichenjc** [comment]
@zhengxiaomei123 which case failed? sorry, I didn't see error in your screen shoot...

**Comment by zhengxiaomei123** [comment]
I pasted the log here:
```
oc logs pod/vpkbkk-d74779f5b-j4gpw -n pkarjirekf
time="2020-08-12T10:08:52Z" level=info msg="create process:devrun"
time="2020-08-12T10:08:52Z" level=info msg="create process:debugrun"
time="2020-08-12T10:08:57Z" level=debug msg="no auth required"
time="2020-08-12T10:08:57Z" level=info msg="stop the program" program=devrun
time="2020-08-12T10:08:57Z" level=info msg="stop the program" program=debugrun
time="2020-08-12T10:08:57Z" level=info msg="force to kill the program" program=debugrun
time="2020-08-12T10:08:57Z" level=info msg="force to kill the program" program=devrun
time="2020-08-12T10:08:58Z" level=debug msg="no auth required"
time="2020-08-12T10:08:58Z" level=debug msg="succeed to find process:devrun"
time="2020-08-12T10:08:58Z" level=info msg="try to start program" program=devrun
time="2020-08-12T10:08:58Z" level=info msg="success to start program" program=devrun
ODO_COMMAND_RUN is npm start
Changing directory to ${PROJECTS_ROOT}
Executing command cd ${PROJECTS_ROOT} && npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /projects/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/projects/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2020-08-12T10_08_58_473Z-debug.log
time="2020-08-12T10:08:59Z" level=debug msg="wait program exit" program=devrun
time="2020-08-12T10:08:59Z" level=error msg="program stopped with error:exit status 254" program=devrun
time="2020-08-12T10:08:59Z" level=info msg="Don't start the stopped program because its retry times 0 is greater than start retries 0" program=devrun
```

**Comment by sarveshtamba** [comment]
Will need OperatorHub support for Power as well to run `make test-operator-hub` test suites.

**Comment by zhengxiaomei123** [comment]
The multi-arch supported operator are `cluster logging operator` and `elasticsearch operator`. The details info :https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying

I can use `odo service create` command to create service but can’t link the service with my nodejs application by `odo link `command. The error show Error: `secret "nodejs-elasticsearch-elasticsearch" `not found. I found the `servicebindingrequest` is created when run odo link.Does it mean `service binding operator` is required when linking service to components? But the `service binding operator`  is not multiarch supported. 

```
odo service list
NAME                                                         AGE
Elasticsearch/elasticsearch                                  23h57m54s
ServiceBindingRequest/nodejs-elasticsearch-elasticsearch     19h10m59s
```

**Comment by zhengxiaomei123** [comment]
Have confirmed with @dharmit , `odo link service and application` feature require ServiceBinding Operator which is not supported for P&Z. So this feature is blocked.

**Comment by zhengxiaomei123** [comment]
Hi @kadel , We built the etcd operator ourselves to support the operator hub tests. We don't publish the image upsteam. Instead , we use patch locally in our CI to use the image we built. I would like to get your confirmation if it is ok. Thanks.
