### ISSUE TITLE
Include periodic job flakes to odo test statistics

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3678]
/kind feature

## Which functionality do you think we should add?

Currently odo test statistics [1] captures only pr job flakes. To get more odo flake capture coverage around the multiple OCP tests (periodic job) [2] we need to include periodic status in [1].

[1] https://gist.github.com/jgwest/5b28687514970ae6baa5942ee82d5755
[2] https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=periodic-*odo*

## Why is this needed?
Keep tracking of periodic job flakes and fix them

**Comment by amitkrout** [comment]
We just need to add a new column that captures the periodic job OCP version and logs.

| Failure Score*  | Failures | Test Name | Last Seen | PR List and Logs | Periodic OCP version and logs |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |

**Comment by amitkrout** [comment]
ping @jgwest @kadel @girishramnani

**Comment by kadel** [comment]
@amitkrout feel free to fork https://github.com/jgwest/odo-tools/ and add necessary changes.

Not sure where @jgwest has this currently running. But we should have it running somewhere "public and more transparent". It might be a good idea to migrate this into OpenShift Prow as a periodic job.

**Comment by anandrkskd** [comment]
The link provided in issue description can not be used for web scraping, as replacement [Job History](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.4-integration-e2e-periodic)  can be used but it only contains 20 job run including successful periodic dun. 
There is also change in expected table structure as discussed with @prietyc123 

| Failure Score*  | Failures On PR | Failures On PeriodicJobs | Test Name | Last Seen | PR List and Logs | Periodic OCP version and logs | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |

**Comment by anandrkskd** [comment]
Scope of the issue 
- [ ] Increasing the build job numbers using build id

- [ ] Change in table structure

- [ ] Compairing and adding PR Failure with periodic failure

- [ ] Adding Periodic failure which are not present in PR

**Comment by dharmit** [comment]
@anandrkskd what's the update on this? Do we have a dashboard for this yet?

**Comment by anandrkskd** [comment]
The PR needs to be merged, the code is there. or I can create one similar dashboard

**Comment by dharmit** [comment]
Create one that you can change later without relying on anyone else. That would help us better.

**Comment by anandrkskd** [comment]
Understood, Will create one ASAP

**Comment by anandrkskd** [comment]
The [dashboard](https://gist.github.com/anandrkskd/102d08389c61e7f7293570bf38205d3b) is up, we can close the issue now.
/close
