### ISSUE TITLE
Wrong command present in odo documentation(#creating a Node.js application with odo)

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#3680]
/kind documentation

## What mistake did you find / what is missing in the documentation?
In the following [documentation](https://odo.dev/docs/creating-a-single-component-application-with-odo/#creating-a-nodejs-application-with-odo), command to create dir and change to the directory is wrong as shown below.
![image](https://user-images.githubusercontent.com/34443651/89175399-54f6c500-d5a5-11ea-89f6-fc19ac5b6daa.png)
 `$$` should be replaced with `&&`.

## What is the relevance of it?
Correct command will improve UX of users.

**Comment by cdrage** [comment]
Thanks @anandrkskd I've opened up a PR here: https://github.com/openshift/openshift-docs/pull/25090

**Comment by cdrage** [comment]
This has been fixed.
