### ISSUE TITLE
docker integration tests fail to properly clean up after themselves

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#3686]
/kind bug

## What versions of software are you using?

**Operating System:** macOS 10.15.6

**Output of `odo version`:** odo v1.2.4 (516383426)

## How did you run odo exactly?

Run the docker integration tests: `ginkgo tests/integration/devfile/docker/`

## Actual behavior
After the tests are finished `docker volume ls` still shows lots of volumes that were created for test purposes. 

## Expected behavior
No test-created volumes should be left after the tests finish.

## Any logs, error output, etc?
`docker volume rm -f <volume name>` fails with the following error:
```
Running docker with args [docker volume rm -f odo-project-source-qlrwqh-ukze]
[docker] Error response from daemon: remove odo-project-source-qlrwqh-ukze: volume is in use - [92f437e02ab74c7f3309d934704763ce1397ccb2a36172d985118d8a7e79c41e]
Non-zero error code on removing volume with component label qlrwqh, output: 
```

**Comment by girishramnani** [comment]
we currently dont have docker support as priority. Closing this issue

**Comment by metacosm** [comment]
Just because it's not a priority doesn't mean that this issue shouldn't be fixed at some point… Either remove the docker support, remove the tests or fix them. Closing an issue just because it's not being worked on at some point is a bad community practice.
