### ISSUE TITLE
Order of odo registry list entries does not match with the actual order being used by the tools

### ISSUE THREAD

**Issue by elsony** [openshift/odo#3693]
/kind bug

## What versions of software are you using?
v1.2.4

**Operating System:**
mac

**Output of `odo version`:**
odo v1.2.4 (a40fbd34e)

## How did you run odo exactly?
To reproduce:
1. `odo registry add eyrepo https://github.com/elsony/odo-devfiles-registry-version `
2. `odo registry list`
The display is:
```
NAME                       URL                                                         SECURE
DefaultDevfileRegistry     https://github.com/odo-devfiles/registry                    No
eyrepo                     https://github.com/elsony/odo-devfiles-registry-version     No
```

## Actual behavior
Notice that the newly added eyrepo is below the DefaultDevfileRegistry entry.  However, when running `odo create` with this setting, eyrepo which is lower on the list is actually having a higher priority. 

## Expected behavior
I would expect the newly added repo to be above the DefaultDevfileRegistry since it has a higher priority to match the relative priority of the repos.

/area devfile
/kind bug

**Comment by GeekArthur** [comment]
I find we need more changes as we concurrently retrieve devfile index file from different registries after the performance PR is merged, so the original registry priority structure is broken, but I already figure out a new data structure + algorithm to fix that, I can open a PR soon to ensure:
- Registry has priority (Latest added registry has the highest priority)
- Display order is correct + still use concurrent mechanism for performance
