### ISSUE TITLE
odo storage list should list all volumes from devfile components

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3704]
/kind user-story

## User Story
As a developer, I want to list the storage defined for the component so that I can have an idea about the storage which are defined for the component.

## Acceptance Criteria 
- [x] It should list the storage with proper states on `odo storage list`.
- [x] It should have json output.

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by mik-dass** [comment]
The list function will be similar to `ListStorageWithState` and the `list` functions in the storage package.

But our current machine readable storage struct only accepts a single mount path but for a devfile, a storage (volume) can be mounted to different paths in different containers. We will need to come up with a design to display this to the user.

We can simply display all the mount paths without the container names. For a volume not mounted to any container, we can simply leave it blank. @girishramnani @kadel WDYT?

**Comment by kadel** [comment]
> We can simply display all the mount paths without the container names. For a volume not mounted to any container, we can simply leave it blank. @girishramnani @kadel WDYT?

That should work

**Comment by mik-dass** [comment]
We can have two list output 
- one with containers mentioned for the above mentioned case
- one with no containers mentioned (for the general case)

The json output will be the same in both the cases
