### ISSUE TITLE
Wrong command present in multicomponent-application documentation ( odo.dev )

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#3707]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Minor mistakes in documentation,
- [Documentation](https://odo.dev/docs/creating-a-multicomponent-application-with-odo/#deploying-the-front-end-component)
  command in bellow image need to be change with `git clone https://github.com/openshift/nodejs-ex frontend`
  ![image](https://user-images.githubusercontent.com/34443651/89517282-1b1cfd00-d7f7-11ea-86ae-e7d0272e87ae.png)
  
- [Documentation](https://odo.dev/docs/creating-a-multicomponent-application-with-odo/#modifying-the-running-application)
  command in bellow image need to be change with `cd frontend`
 ![image](https://user-images.githubusercontent.com/34443651/89517336-2ec86380-d7f7-11ea-8be8-af3a30d576aa.png)

## What is the relevance of it?
Better user UX

**Comment by girishramnani** [comment]
resolved by #3795
