### ISSUE TITLE
odo watch improvements

### ISSUE THREAD

**Issue by containscafeine** [openshift/odo#371]
- [ ] it should ignore temp files like `.swp`
- [ ] if the directory is git controlled, then unstaged files should be ignored
- [ ] if files are constantly changing, then it should wait for changes to slow down. We should have something like a change_timeout, i.e. if nothing has changed in the past 10 seconds, then do a build, but if things are constantly changing, then wait for changes to stop
- [ ] already started builds should be canceled if they've not finished and a new one has started

**Comment by kadel** [comment]
> if the directory is git controlled, then unstaged files should be ignored

I don't think they should be ignored


> if files are constantly changing, then it should wait for changes to slow down. We should have something like a change_timeout, i.e. if nothing has changed in the past 10 seconds, then do a build, but if things are constantly changing, then wait for changes to stop

There might be no build in the future

**Comment by cdrage** [comment]
I'm 99% sure we're accomplished all these goals :+1: I'm going to close this (for now).

If you think we're missing anything, please re-open this @anmolbabu ! :smile:
