### ISSUE TITLE
Support creating multiple URLs with the same TargetPort

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#3710]
/kind user-story
/area url
/area devfile

## User Story
As a user I want to create multiple URLs with the same port,  so that I have different `path` defined using different ingresses/routes for the same port, and I can create one http URL and another https URL using the same port as well. 

## Acceptance Criteria 
- [ ] modify the current validation on devfile TargetPort to allow multiple identical ports
- [ ] update the logic of url creation. (i.e. any maps use port number as key should use URL name instead)
- [ ] update the test case

**Comment by mik-dass** [comment]
> As a user I want to create multiple URLs with the same port, so that I have different path defined using different ingresses/routes for the same port, and I can create one http URL and another https URL using the same port as well.

It is currently possible to create URLs with the same port.

```

Applying URL changes
 ✓  URL example: http://example.com created
 ✓  URL example-1: http://example-1.com created

Syncing to component nodejs
 ✓  Checking file changes for pushing [378505ns]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
[mrinaldas@localhost project]$ odo url list
Found the following URLs for component nodejs
NAME          STATE      URL                      PORT     SECURE     KIND
example       Pushed     http://example.com       3000     false      ingress
example-1     Pushed     http://example-1.com     3000     false      ingress
[mrinaldas@localhost project]$ 

```
It doesn't work for devfile endpoints and gives validation error. We need to change that.

**Comment by yangcao77** [comment]
To support this,  we want wait for  https://github.com/openshift/odo/issues/3718 to be done first, to move url settings into to devfile.yaml. Also: 

- different containers should not have same Targetport. In kubernetes the containers in same port share single network namespace, so two containers cannot listen to same port, in same pod.

- within a single container, multiple endpoints have same port should only expose once in service spec, as service does not support duplicate ports. 

- within a single container, two endpoints have same port but with different protocal, if it's (UDP & TCP), should be done in https://github.com/openshift/odo/issues/3663
