### ISSUE TITLE
odo documents  changes for IBM P/Z platform

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3725]
/kind documentation

## Which functionality do you think we should add?
Since we have add IBM P/Z support for odo , The documents for user need to add some instructions for using odo on IBM P/Z.

**Comment by jichenjc** [comment]
@zhengxiaomei123 can we list all the potential items
such as images and other potential things ?Thanks

**Comment by zhengxiaomei123** [comment]
- [ ] ReadMe :Officially supported languages and corresponding container images

**Comment by zhengxiaomei123** [comment]
Hi @cdrage , I check all the doc of odo and list all the  required changes for documents of odo in above comments. What's your advice? If it is ok, I will request the PR to update these docs (There has been 2 PRs to update the first and second changes). Thanks.
