### ISSUE TITLE
clonePath should be supported in odo

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3729]
/kind user-story

## User Story
As a user, I want to be able to use a project's `clonePath` setting to determine where my project(s) get synced on the remote containers. If no `clonePath` field is set, it should use the project's name as the clonePath, as per the devfile schema.

## Acceptance Criteria 
- [ ] It should sync the user's source code to the setting of `clonePath` if set for a project
- [ ] If multiple projects are defined in a devfile, odo should use the proper `clonePath` value
- [ ] If `clonePath` is not defined for the user's project, the name of the project should be used as the `clonePath` value
- [ ] It should still support cases where there is no project defined in a devfile, or the user brings their own project.

## Notes
`clonePath` description in Devfile Json Schema:
`clonePath: string` 
Path relative to the root of the projects to which this project should be cloned into. This is a unix-style relative path (i.e. uses forward slashes). The path is invalid if it is absolute or tries to escape the project root through the usage of '..'. If not specified, defaults to the project name.

/kind user-story
/area devfile

**Comment by johnmcollier** [comment]
How should we handle that last case? Where there isn't a clear value that we can set `clonePath` to?

**Comment by adisky** [comment]
as discussed with @kadel local source code should be synced to 
if project is present and clonePath is set
`$PROJECT_ROOT/project.clonePath`
if project is present and clonePath is not set
`$PROJECT_ROOT/project.Name`
if project is not present
`$PROJECT_ROOT`
