### ISSUE TITLE
odo integration and e2e tests failed for 2.0-alpha on s390x

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3757]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

**Comment by zhengxiaomei123** [comment]
@girishramnani Hi , I am confused that why the lable `System-PZ` is removed. Thanks.

**Comment by jichenjc** [comment]
@zhengxiaomei123 how about paste the error info here about what's wrong?

**Comment by zhengxiaomei123** [comment]
```
Running odo with args [odo version]
[odo] I0821 03:10:35.820513 3604710 preference.go:209] The path for preference file is /home/odo44/tmp/artifacts/.odo/preference.yaml
[odo] I0821 03:10:35.820631 3604710 occlient.go:458] Trying to connect to server api.odo44.rhocp.boe:6443
[odo] I0821 03:10:35.822498 3604710 occlient.go:465] Server https://api.odo44.rhocp.boe:6443 is up
[odo] I0821 03:10:35.858884 3604710 occlient.go:2904] Unable to get OpenShift Version - endpoint '/version/openshift' doesn't exist
[odo] odo v2.0.0-alpha-2 (00d408ece)
[odo] 
[odo] Server: https://api.odo44.rhocp.boe:6443
[odo] Kubernetes: v1.18.3+08c38ef
 Failure [0.146 seconds]
odo generic
/home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:15
  when executing odo version command
  /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:281
    should show the version of odo major components including server login URL [It]
    /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:282
    Expected
        <bool>: false
    to be true
    /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:288
```

**Comment by zhengxiaomei123** [comment]
Hi @girishramnani ,I am confused that why the lable `required-for-v2` is removed. Thanks.

**Comment by jichenjc** [comment]
> ```
> Running odo with args [odo version]
> [odo] I0821 03:10:35.820513 3604710 preference.go:209] The path for preference file is /home/odo44/tmp/artifacts/.odo/preference.yaml
> [odo] I0821 03:10:35.820631 3604710 occlient.go:458] Trying to connect to server api.odo44.rhocp.boe:6443
> [odo] I0821 03:10:35.822498 3604710 occlient.go:465] Server https://api.odo44.rhocp.boe:6443 is up
> [odo] I0821 03:10:35.858884 3604710 occlient.go:2904] Unable to get OpenShift Version - endpoint '/version/openshift' doesn't exist
> [odo] odo v2.0.0-alpha-2 (00d408ece)
> [odo] 
> [odo] Server: https://api.odo44.rhocp.boe:6443
> [odo] Kubernetes: v1.18.3+08c38ef
>  Failure [0.146 seconds]
> odo generic
> /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:15
>   when executing odo version command
>   /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:281
>     should show the version of odo major components including server login URL [It]
>     /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:282
>     Expected
>         <bool>: false
>     to be true
>     /home/odo44/go/src/github.com/openshift/odo/tests/integration/generic_test.go:288
> ```

@zhengxiaomei123 this is very generic test...

maybe you want to check
1) whether oc with such API call works
2) what's the error on the version call and provider further info here
```
rawOpenShiftVersion, err := c.kubeClient.CoreV1().RESTClient().Get().AbsPath("/version/openshift").Do().Raw()
        if err != nil {
                // when using Minishift (or plain 'oc cluster up' for that matter) with OKD 3.11, the version endpoint is missing...
                klog.V(4).Infof("Unable to get OpenShift Version - endpoint '/version/openshift' doesn't exist")
```

**Comment by zhengxiaomei123** [comment]
```
./odo version
odo v2.0.0-alpha-2 (00d408ece)

Server: https://api.ocp.openstack:6443
Kubernetes: v1.18.3+6025c28
```

**Comment by zhengxiaomei123** [comment]
The reason is `reOdoVersion := regexp.MustCompile(`^odo\s*v[0-9]+.[0-9]+.[0-9]+(?:-\w+)?\s*\(\w+\)`)`

**Comment by zhengxiaomei123** [comment]
The right regex should be `^odo\s*v[0-9]+\.[0-9]+\.[0-9]+(\-\w+)*\s*\(\w+\)`

**Comment by zhengxiaomei123** [comment]
Because the odo CI on OCP/Z for alpha is passed now. I will close this issue and then reopen If there are new failed cases again in future.
