### ISSUE TITLE
Devfile mode: 'odo push' skips the build command

### ISSUE THREAD

**Issue by dev-gaur** [openshift/odo#3769]
whenever I try the `odo push` , the `build` command in the devfile isn't triggered, only the `run` command is triggered again.

How to verify the bug :

For a java project, try normal `odo push` and you can observe that changes won't be reflected in your running app. But if you run the build command ( `mvn package` ) on your setup to compile your fat jar before `odo push` , then the changes are reflected.

You can also verify from the supervisord logs of the pod.. using `odo log` .

In nodejs projects, It might appear that everything is working fine as the changes do get reflected, but that it because the `npm start` command gets triggered which basically does `node server.js` ..... 

but if you check logs, `npm install` isn't triggered on `odo push` .  So if you make a change in your dependencies, odo push will probably fail.

**Comment by adisky** [comment]
@dev-gaur  I have checked on latest master with springboot devfile, if there are changes `odo push` picking up the changes and running build command, it is not skipping. Please mention exact steps you are following in bug description

**Comment by girishramnani** [comment]
this is currently not happening again so could be a one-off, we are verifying it again just in case

**Comment by dev-gaur** [comment]
sorry for the false alarm. I must have skipped a step of odo workflow, when I observed this behaviour.

**Comment by dev-gaur** [comment]
though we should try that the execution of the build command should also be logged... as supervisord log... for consistency's sake
