### ISSUE TITLE
Allow users to toggle between ephemeral and persistent volumes for devfiles

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3775]
/kind user-story
/area devfile

## User Story
Currently, odo uses an ephemeral emptyDir volume to store the synced project source code in the remote container of a devfile component. There's some use cases however where this is not ideal, such as when the pod needs to be restarted for whatever reason (env update, linking, etc), and then the source code needs to be re-synced. Additionally, to support scenarios with containers in their own dedicated pod (via the `dedicatedPod` field), a single shared emptyDir volume cannot be used.

As a user, I want to have the choice to use persistent storage for my project source if I desire, but also still have the freedom to still use emptyDir/ephemeral volumes if I want or if my cluster does not have storage configured. 

Eclipse Che uses the `persistVolumes` attribute in devfiles to toggle this functionality (default value is true when unset). This would be a good attribute to support, especially if we're still aiming for compatibility with Che devfiles:
<img width="948" alt="Screen Shot 2020-08-18 at 11 44 15 AM" src="https://user-images.githubusercontent.com/6880023/90534844-374e6180-e148-11ea-97d5-b1e052e858d6.png">

Additionally, we could provide a global-level preference in the `~/.odo/preferences.yaml` file if users didn't want to set it on a per-workspace basis.

## Acceptance Criteria 
- [ ] It should allow users to toggle between emptyDir and Persistent Volumes for storage. There should be a default value.
- [ ] It should either be a global setting, or component-level setting (via the `persistVolumes` attribute) or both.

## Links 
- Feature Request: 
- Related issue: https://github.com/openshift/odo/issues/3562

/kind user-story

**Comment by adisky** [comment]
Using a pvc would also solve some of this problems
https://github.com/openshift/odo/issues/4050
https://github.com/openshift/odo/issues/4017

as discussed with @kadel we want to keep pvc as default option, and also allow users to set it to  `emptyDir`

**Comment by adisky** [comment]
findings till now
-  [volume access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) is not a problem as long as we are using single pod with a component
- issue is divided in two parts
   - Adding support to use pvc to store source code
   - Updating the source code sync code.

Apart from this, do we want to add the source code pvc to devfile and do we want to show it in `odo storage list`?

**Comment by adisky** [comment]
Things to be done to support pvc
- Giving configuration option to user to choose between persistent not persistent storage, it would be given via preference.yaml and   devfile.yaml
- Default mode will be using pvc
- Add code to create pvc to store source code
- Update the code sync logic.
- Adding tests and docs for the same

One query on this 
 do we want to add the source code pvc to devfile and do we want to show it in `odo storage list`?

**Comment by girishramnani** [comment]
any reason we moved this out of "in progress"

**Comment by adisky** [comment]
started working out here https://github.com/adisky/odo/commit/843d21eed969e1f4fb91001a88243b5227df85b8, it would conflict with https://github.com/openshift/odo/issues/4131, will start once the extraction is done
