### ISSUE TITLE
We should validate config params for devfile

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3791]
We should validate memory limit, not specifically here may be during `odo push`, if memory limit specified in wrong format like `756g`, `odo config set` `odo push` `k8s api`silently ignores that, and component gets pushed successfully without applying limits.

_Originally posted by @adisky in https://github.com/openshift/odo/pull/3702_

**Comment by prietyc123** [comment]
@girishramnani Are we considering this for devfile v2 because it seems quite important to me. Whatever feature we say is there with odo, IMO we should cover all the cases which validates it.
