### ISSUE TITLE
API version and schema version tests should be migrated to devfileV2

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3794]
/kind cleanup

https://github.com/openshift/odo/blob/master/pkg/devfile/parser/context/apiVersion_test.go
https://github.com/openshift/odo/blob/master/pkg/devfile/parser/context/schema_test.go

**Comment by adisky** [comment]
It is  already covered by this PR https://github.com/openshift/odo/pull/3867/files#diff-7f35ec4e6a21608494408b99bc228981

**Comment by anandrkskd** [comment]
But I see https://github.com/openshift/odo/blob/master/pkg/devfile/parser/context/apiVersion_test.go is not changed/updated in the above PR, is it not required?

**Comment by adisky** [comment]
> But I see https://github.com/openshift/odo/blob/master/pkg/devfile/parser/context/apiVersion_test.go is not changed/updated in the above PR, is it not required?

I haven't checked thoroughly, yes these tests should be migrated to devfile v2
