### ISSUE TITLE
Implement `project` for devfile

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3798]
/kind feature

## Which functionality do you think we should add?
Implement project from devfile schema https://github.com/devfile/api/blob/master/schemas/devfile.json#L3402
with the implementation of `starterProjects`, we are silently ignoring the `projects` field in devfile now.

Implementation Details:
TBD

**Comment by dharmit** [comment]
@mik-dass is this something that we should re-open and work on?

**Comment by mik-dass** [comment]
> @mik-dass is this something that we should re-open and work on?

The refactoring would be covered in https://github.com/openshift/odo/issues/4115

**Comment by mik-dass** [comment]
> @mik-dass is this something that we should re-open and work on?

I think projects in the devfile will be used by the `odo deploy` command in future.
