### ISSUE TITLE
Clean up context in devfile integration tests

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3801]
Currently most of the devfile integration tests that use context flag `--context`, change to the context directory in `BeforeEach` even though we're using the full path in `--context`

Ideally, we should not switch to the context directory when using `--context`. Clean up all devfile integration tests for the flag.

/area devfile
/kind cleanup

**Comment by dharmit** [comment]
Doesn't look like we addressed this. Reopining the issue.

**Comment by valaparthvi** [comment]
I would like to work on this.
/assign me

**Comment by valaparthvi** [comment]
Currently the following devfile integration tests need this cleanup -
```
tests/integration/devfile/cmd_devfile_debug_test.go
tests/integration/devfile/cmd_devfile_delete_test.go
tests/integration/devfile/cmd_devfile_describe_test.go
tests/integration/devfile/cmd_devfile_log_test.go
tests/integration/devfile/cmd_devfile_push_test.go
tests/integration/devfile/cmd_devfile_test_test.go
tests/integration/devfile/cmd_devfile_url_test.go
tests/integration/devfile/cmd_devfile_watch_test.go
```

**Comment by valaparthvi** [comment]
Scope of this issue for sprint 199 - 
[ ] 1. Fix the tests mentioned in https://github.com/openshift/odo/issues/3801#issuecomment-779113525. Some of the tests are a quick fix, some might require a little more work.
[ ] 2. Identify any other tests that might need cleanup.

_Might be a 3-day task._

**Comment by valaparthvi** [comment]
How do we want to go about this? Do we want to remove the `--context` flag wherever it is not used to test the context or remove the `Chdir` in `BeforeEach` and modify all tests to work with the changes? I am not sure if doing either affects the test coverage.

@dharmit @girishramnani @mik-dass thoughts?

**Comment by mik-dass** [comment]
> How do we want to go about this? Do we want to remove the --context flag wherever it is not used to test the context or remove the Chdir in BeforeEach and modify all tests to work with the changes? I am not sure if doing either affects the test coverage.

We should remove the Chdir in BeforeEach wherever possible as that would help us figure out if the context flag works for the command properly or not.
