### ISSUE TITLE
When using a devfile with multiple starter projects, odo should ask the user which one to use

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#3812]
/kind feature

## Which functionality do you think we should add?
Currently when there are multiple starter projects, odo automatically selects the first it finds when creating a component with `--starter`. 

## Why is this needed?
It's not currently possible to download a starter project after a component has been created and it's not trivial to figure out which starter projects exist before the component is created and the devfile downloaded locally. A nicer user experience would be to offer the user the possibility to choose which starter project to use.

**Comment by adisky** [comment]
@metacosm odo slips into interactive mode only when no parameters/arguments specified, only `odo create`  would start interactive mode. for non-interactive mode there is a issue of displaying `starter projects` with `odo catalog list components` so the user would know before creating a component what starter projects it has https://github.com/openshift/odo/issues/3692
