### ISSUE TITLE
Known issues cleanup and update for v2

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3816]
/kind user-story

## User Story
As a i want to know what are the known issues for v2 releases reported here in bugzilla - https://bugzilla.redhat.com/buglist.cgi?component=rhodo&list_id=11305616&product=Red%20Hat%20odo%20for%20OpenShift%20Container%20Platform

## Acceptance Criteria 
- [ ] KIs list should be cleaned up and updated for v2

## Links 
- Feature Request: NA
- Related issue: 

/kind user-story

**Comment by girishramnani** [comment]
Ideally this should the list https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fbug+no%3Aproject+no%3Aassignee

**Comment by prietyc123** [comment]
Till date I have documented all the high priority known issues in Bugzilla. So considering it as done.

/close
