### ISSUE TITLE
Doc verification for v2

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3817]
/kind user-story

## User Story
As a user i should not get any incorrect steps in https://odo.dev/ and https://docs.openshift.com/container-platform/4.5/cli_reference/developer_cli_odo/understanding-odo.html

## Acceptance Criteria 
- [ ] https://odo.dev/ and https://docs.openshift.com/container-platform/4.5/cli_reference/developer_cli_odo/understanding-odo.html should not contain any incorrect or missing content

## Links 
- Feature Request: NA
- Related issue: 

/kind user-story

**Comment by prietyc123** [comment]
@girishramnani @kadel @boczkowska @cdrage Our `odo.dev` doc for devfile - https://odo.dev/docs/deploying-a-devfile-using-odo/ still says devfile needs experimental to be enabled. Could you please confirm the status on this.

**Comment by prietyc123** [comment]
@cdrage @boczkowska I think devfile reference doc - https://odo.dev/file-reference/ also needs to be updated wrt to devfile properties. Could you please have a look and correct me if I am wrong.

**Comment by prietyc123** [comment]
Updated all the issues till now with the doc

```
https://github.com/openshift/odo/issues/3878
https://github.com/openshift/odo/issues/3870
https://github.com/openshift/odo/issues/3869
https://github.com/openshift/odo/issues/3868
https://github.com/openshift/odo/issues/3863
```

**Comment by prietyc123** [comment]
Verified all the doc and updated the issue https://github.com/openshift/odo/issues/3817#issuecomment-686393123 

/close
