### ISSUE TITLE
Update Devfiles and odo to work with breaking changes in devfile spec

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3822]
There are breaking changes coming into Devfile v2 schema before freezing schema for a stable release.

Change is discussed in: https://github.com/devfile/api/issues/102
PR addressing this in Devfile schema: https://github.com/devfile/api/pull/122 

While is being worked on we can actually start implementing required changes on odo side.

[Devfile JSON schema that is included in](https://github.com/kadel/kubernetes-api/blob/top-level-merge-key/schemas/devfile.json) https://github.com/devfile/api/pull/122  should not change much. There might be some minor changes in the description or in Go structs,  but the structure of the schema should be final.

This will require:
 - [ ] Updating Json Schema embedded in odo
 - [ ] Updating odo internal structs
 - [ ] Update all devfiles in tests and odo devfile registry to match updated schema 
 - [ ] update the dev/public docs

/priority high
/area devfile

**Comment by mik-dass** [comment]
In the current master based on the Goland find tool

For the common types:
The composite's ID field has 57 usages(8 reads, 49 writes)
The exec's ID field has 180 usages (11 reads, 169 writes)
The container's NAME field has usages 103 usages (27 reads, 79 writes)

The exec and composite commands in the TestDevfileData struct will have to be written in a more simple way and use the general common command structure.

The registry devfiles will have to change accordingly.
The example devfiles used in integration tests will have to change as well.

**Comment by mik-dass** [comment]
Closed by https://github.com/openshift/odo/pull/3872
/close
