### ISSUE TITLE
Refactor json output match through out the test script

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3823]
/kind code-refactoring

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## Actual behavior

As part of json match is concern it looks pretty weird when we match the whole json (size of a paragraph). If we have a better json parser test script will also look clean and good.

## Expected behavior

Instead of matching the whole json we can match the few key field of that. So we need a proper json parser.

## Proposed solution
We can use the GJSON (https://github.com/tidwall/gjson) package as it meets the requirements and provides additional flexibility.

Implications:
Will have to refactor all test scripts using the current MatchJSON parser

## Acceptance criteria
- [x] Ability to match one or multiple keys
Refactor test scripts using the MatchJSON parser from ginkgo:
- [x] cmd_devfile_url_test.go
- [x] cmd_pref_config_test.go
- [x] cmd_app_test

The following tests were updated but reported failures on areas where the changes were not introduced. A new issue will be opened to track their delivery once all other issues are resolved
cmd_dev_file_storage_test.go
cmd_devfile_describe_test.go
cmd_docker_devfile_url_test.go
cmd_storage_test.go
comd_url_test.go
component.go (called by cmd_cmp_test.go and cmd_cmp_sub_test.go)
generic_test.go
cmd_project_test.go

Executed each test as:
`ginkgo -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=1 -focus="[test string in describe section of the test]" [test_path, e.g. tests/integration]`

**Comment by rnapoles-rh** [comment]
@prietyc123 please include a link to the current parser that needs to be refactored

**Comment by girishramnani** [comment]
as discussed @rnapoles-rh we can either just implement a simple `map[string]interface{}` unmarshalling of the json or consider using https://github.com/tidwall/gjson

**Comment by rnapoles-rh** [comment]
The cmd_devfile_storage_test.go test fails in PSI environment, however it runs OK on Prow. Issue #4319 tracks this problem.
