### ISSUE TITLE
Allow using odo inside a firewall

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3824]
/kind bug

https://bugzilla.redhat.com/show_bug.cgi?id=1871160

**Comment by amitkrout** [comment]
I have aws account to start a cluster however setting up cluster behind a firewall could be a challenge. 

Firewall prereq- https://docs.openshift.com/container-platform/4.5/installing/install_config/configuring-firewall.html

**Comment by amitkrout** [comment]
Copy and pasting @kadel comment from bugzila
```
Use of registry.access.redhat.com is intentional.
Odo doesn't use registry.redhat.io because this registry requires authentication and we want to make sure that the 
same odo binary can be used on OpenShift and also on Kubernetes by users without Red Hat account.

Not sure if it makes sense to update OCP documentation to add Firewall rule for registry.access.redhat.com if
 nothing else is expected to use this registry.

But it might be good to add something like "In case you plan to use odo with your cluster whitelist also
 registry.access.redhat.com" to https://docs.openshift.com/container-platform/4.5/installing/install_config/configuring-firewall.html

**Comment by amitkrout** [comment]
@girishramnani What is the ask in the issue ?

To reproduce the issue does not add value as this is expected. So do you want to verify odo functionality after adding the registry.access.redhat.com to the firewall whitelist ?

**Comment by amitkrout** [comment]
I have pinged the original reporter in bugzila to check it form their end with the suggestion - https://github.com/openshift/odo/issues/3824#issuecomment-683707339

**Comment by prietyc123** [comment]
> Copy and pasting @kadel comment from bugzila
> 
> ```
> Use of registry.access.redhat.com is intentional.
> Odo doesn't use registry.redhat.io because this registry requires authentication and we want to make sure that the 
> same odo binary can be used on OpenShift and also on Kubernetes by users without Red Hat account.
> 
> Not sure if it makes sense to update OCP documentation to add Firewall rule for registry.access.redhat.com if
>  nothing else is expected to use this registry.
> 
> But it might be good to add something like "In case you plan to use odo with your cluster whitelist also
>  registry.access.redhat.com" to https://docs.openshift.com/container-platform/4.5/installing/install_config/configuring-firewall.html
> ```

As per @kadel comment I can see that its a documentation changes needs to be done. And ofcourse as per the above thread I can see we have to verify the suggested change in our test environment as well. So changing the label brom bug to area testing and need doc.

/remove bug
/area testing
/documentation

**Comment by amitkrout** [comment]
I have gone through some reference video on how to configure firewall for aws account and whitelisting part as per the comment https://github.com/openshift/odo/issues/3824#issuecomment-690960220 but could not try it. 

So i am keeping it for next sprint.

**Comment by dharmit** [comment]
The BZ corresponding to this issue has been inactive since over 2 months. And so is this issue. Is this even relevant? @prietyc123 @girishramnani

**Comment by boczkowska** [comment]
@dharmit the bugzilla can be closed: https://github.com/openshift/openshift-docs/pull/27092

**Comment by kadel** [comment]
/close
https://bugzilla.redhat.com/show_bug.cgi?id=1871160#c7
