### ISSUE TITLE
Remove container image from personal repo in RH openshift document

### ISSUE THREAD

**Issue by zhengxiaomei123** [openshift/odo#3833]
/kind documentation

## What mistake did you find / what is missing in the documentation?
 The container image `bucharestgold/centos7-s2i-nodejs `has not been offically supported by odo because there is no `bucharestgold/centos7-s2i-nodejs` in upstream README.doc . The `bucharestgold/centos7-s2i-nodejs` exists in RH openshift  document and plan to delete it .
## What is the relevance of it?
https://docs.openshift.com/container-platform/4.5/cli_reference/developer_cli_odo/understanding-odo.html#odo-supported-languages-and-images

**Comment by jichenjc** [comment]
why open an issue against RHEL official doc? seems this is the place to open bugs for upstream?

**Comment by zhengxiaomei123** [comment]
@jichenjc make sure that this gets solved. requested by @cdrage .

**Comment by boczkowska** [comment]
The image has been removed from the documentation, see: https://docs.openshift.com/container-platform/4.5/cli_reference/developer_cli_odo/understanding-odo.html#odo-supported-languages-and-images
