### ISSUE TITLE
odo watch redeploys component during first push

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#3841]
/kind bug

## How did you run odo exactly?

`odo push`
`odo watch`

## Actual behavior

The component is redeployed during the first push triggered by watch.

## Expected behavior

The component shouldn't be redeployed.

## Any logs, error output, etc?

```

Executing devfile commands for component nodejs
 ✓  Executing install command "npm install" [8s]
 ✓  Executing run command "npm start" [5s]

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
[mrinaldas@localhost project]$ odo watch
Waiting for something to change in /home/mrinaldas/project
File /home/mrinaldas/project/check.sh changed
Pushing files...

Validation
 ✓  Validating the devfile [61668ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [6s]        // redeployed

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs
 ✓  Checking file changes for pushing [1ms]
...
```

**Comment by mik-dass** [comment]
Due to the issue mentioned here https://github.com/openshift/odo/issues/3838#issuecomment-680838286, this causes the component to break too.

**Comment by dev-gaur** [comment]
I think when this redeployment happens, the build command is skipped... and then the run command crashes... (coz build needs to run inside a fresh container)

![image](https://user-images.githubusercontent.com/7551036/91303148-37dc9d00-e7c5-11ea-8db6-337e97201400.png)

**Comment by mik-dass** [comment]
> I think when this redeployment happens, the build command is skipped

The build is not skipped, `npm install` just doesn't fail when package.json is not present. This is something @kadel found out today.
