### ISSUE TITLE
odo registry list causes panic if preference has not been setup

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#3842]
/kind bug

## What versions of software are you using?
Master

**Operating System:**
Fedora 31

**Output of `odo version`:**
```
❯ make bin && sudo cp -avrf ./odo /usr/bin/odo
go build -ldflags="-w -X github.com/openshift/odo/pkg/version.GITCOMMIT=68bc98ba8" cmd/odo/odo.go
'./odo' -> '/usr/bin/odo'
❯ odo version
odo v1.2.5 (68bc98ba8)

```

## How did you run odo exactly?

```
❯ rm -rf ~/.odo && odo registry list
```

## Actual behavior

```
❯ rm -rf ~/.odo && odo registry list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x188db3d]

goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/cli/registry.(*ListOptions).Run(0x316a9c8, 0x0, 0x0)
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/pkg/odo/cli/registry/list.go:60 +0x5d
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2062c80, 0x316a9c8, 0xc000524280, 0x316a9c8, 0x0, 0x0)
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/registry.NewCmdList.func1(0xc000524280, 0x316a9c8, 0x0, 0x0)
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/pkg/odo/cli/registry/list.go:101 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000524280, 0x316a9c8, 0x0, 0x0, 0xc000524280, 0x316a9c8)
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000189180, 0x1e47658, 0xc000043920, 0x2)
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/home/mzee1000/workbench/work/golang/redhat/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x330


```

## Expected behavior

The preference should be initialized

## Any logs, error output, etc?
see above

**Comment by johnmcollier** [comment]
Seems to be the same panic as in https://github.com/openshift/odo/issues/3747#issuecomment-672900015

The solution for the alpha branch/release was to do always make sure we properly initialize the registry in the preferences file https://github.com/johnmcollier/odo/commit/274acb72db1fb3ac4ec06104dae639856d6602f2

But, should we even be allowing the `odo registry` commands to run if experimental mode isn't enabled (and since there's no preferences file, then it's not enabled).

**Comment by mohammedzee1000** [comment]
I ran it with experimental mode enabled. Note: once I did `odo registry add default blah` or tried creating etc, it worked fine.

Also, the issue here is panic. Something we ideally SHOULD NOT have, if we can prevent it, maybe gracefully exit if you are not initializing preference

**Comment by johnmcollier** [comment]
I'm guessing you're setting experimental mode via the `ODO_EXPERIMENTAL` variable? (Otherwise, `odo preference set experimental true` would initialize the preferences file)

Agreed that we shouldn't have the panic, and so backporting https://github.com/johnmcollier/odo/commit/274acb72db1fb3ac4ec06104dae639856d6602f2 should fix things

**Comment by johnmcollier** [comment]
I can work on this

/assign

**Comment by cdrage** [comment]
Just an FYI. I do have it in this PR as well: https://github.com/openshift/odo/pull/3705

Unsure if the current test failures I'm facing are because of this issue or not. But going to do a quick /retest and will report back.

**Comment by johnmcollier** [comment]
Decided to close my PR in favour of https://github.com/openshift/odo/pull/3705, which has the same change in there

**Comment by girishramnani** [comment]
closeing this issue then as #3705 got merge @johnmcollier
