### ISSUE TITLE
Update devfile "odo.dev" doc

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3868]
/kind documentation

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Verifying devfile doc https://odo.dev/docs/deploying-a-devfile-using-odo/ manually

## Actual behavior

Jotting out the fields that needs to get modified.

## Expected behavior

The doc should meet proper devfile command and behaviour expectation

## Any logs, error output, etc?

Logs will be updated in the comment

**Comment by prietyc123** [comment]
List the content of the directory still pointing to the older format files like `app`

![image](https://user-images.githubusercontent.com/51620925/91634084-474d2780-ea0b-11ea-8b1c-0516a4af50e3.png)

This is how we are now with nodejs devfile
```
$ git clone https://github.com/odo-devfiles/nodejs-ex && cd nodejs-ex
Cloning into 'nodejs-ex'...
remote: Enumerating objects: 353, done.
Receiving objects:
[...]
Receiving objects: 100% (353/353), 275.42 KiB | 10.00 KiB/s, done.
Resolving deltas: 100% (74/74), done.

$ ls
LICENSE
README.md
package-lock.json
package.json
server.js
test
```

**Comment by prietyc123** [comment]
When are we planning to remove devfile Experimental from doc https://github.com/openshift/odo/issues/3817#issuecomment-682581351

**Comment by cdrage** [comment]
@prietyc123 Can you open a PR for this?

**Comment by prietyc123** [comment]
> @prietyc123 Can you open a PR for this?

@cdrage I am very sorry actually I have other portion of the doc to verify as well as need to research on periodic failure. Most importantly we are currently dealing with `operator hub` stability issue on 4.6 ocp cluster and some more test related failure to fix.
