### ISSUE TITLE
Remove technology preview feature for debug command

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3869]
/kind documentation

## What mistake did you find / what is missing in the documentation?

AFAIK debug command is no more tech preview feature for 2.0 release. Please update https://odo.dev/docs/debugging-applications-in-odo/ accordingly

## What is the relevance of it?

Remove tech preview for debug feature.

**Comment by prietyc123** [comment]
@kadel Correct me if I am wrong

**Comment by cdrage** [comment]
@prietyc123 I have updated the upstream documentation here: https://github.com/openshift/openshift-docs/pull/25165
