### ISSUE TITLE
Short alias in CLI

### ISSUE THREAD

**Issue by NissesSenap** [openshift/odo#3875]
/kind feature

## Which functionality do you think we should add?
Add short aliases for CLI commands. Currently I have to type `odo list` I would like to be able to type `odo ls`

## Why is this needed?
Currently the CLI is forcing the developers to be very verbose when typing commands which takes time.
I have given a example above with list vs ls.
There is probably more "standard" aliases that could be implemented in the cli to make life easier for developers.

**Comment by kadel** [comment]
Hi, @NissesSenap to save some typing you can also use autocompletion, this is much more useful than aliases.
If you execute  `source <(odo utils terminal bash)` (or  `source <(odo utils terminal zsh)` if you use ZSH) you will be able to do `odo li<tab>`. Autocompletion should also work for flags. To make it persistent you add the command to your `.bashrc` `.zshrc`.

**Comment by NissesSenap** [comment]
Thanks for the tip @kadel I have done this and as you say it saves some time but I guess me and most developers today is used of doing "ls" or "get" when you want a list of things within kubernetes.

I haven't had time to look at the odo code but I assume it uses a cli framework like cobra or something similar so adding aliases shouldn't be a super big feature but my two cents is that it will make life easier for developers.

**Comment by kadel** [comment]
Yes, we use Cobra, aliases are not a problem. We are actually already doing it.
In reality `odo list` is already an alias for `odo component list` :-) 

We will look into making commands a little bit shorter and use common shortcuts that people are used to.
