### ISSUE TITLE
Make the `odo.dev` front page documentation simpler

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3887]
/kind documentation

## What mistake did you find / what is missing in the documentation?
The front page document should focused with `deploying applications with odo` or say `Easy way deploying application on Kubernetes cluster using odo`.

e.g This page https://odo.dev/docs/deploying-a-devfile-using-odo/ could be referenced as  `deploying app using odo`

on the front page if we focus on `devfile` term too much, it would refrain from new users to adapt it. The Front page could have headings like this
- `Easy way of Development with Kubernetes/Openshift  ` OR `Developing Applications with Kuberenetes/Openshift in a simpler way` 
- `Configuring odo with devfiles` (This would include details about how to modify `command` `endpoints` using `odo config` and writing to file both ways.)
- `Troubleshooting with odo` (It would  include commands like `odo exec` or `odo log`)
-  `Architecture`

Already existing headings on the page
- `Installing odo`
-  `Debugging Applications with odo`
- ` odo CLI reference`

Advance users:
- `Creating Devfile stacks`
- `Devfile reference`

**Comment by cdrage** [comment]
You're correct. We should be agnostic and focus on deploying an application and not focus on Devfile. Essentially, we use Devfile under the hood and we can edit it to our liking. But we shouldn't focus on it :+1:

**Comment by cdrage** [comment]
I've update the main website @adisky to be more neutral / avoid over-using "Devfile" in the titles / descriptions.

I'm closing this issue. Please re-open if there are any further changes you'd like.
