### ISSUE TITLE
odo starter project unable to download behind proxy

### ISSUE THREAD

**Issue by NissesSenap** [openshift/odo#3889]
/kind bug

Trying to use the starter project feature but is unable to do so while being behind a proxy.

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**
odo version
odo v1.2.6 (55c074e97)

Server: https://api.sb.se.mydomain:6443
Kubernetes: v1.18.3+002a51f

## How did you run odo exactly?

export no_proxy=mydomain
export http_proxy=http://serviceproxy.se.mydomain:8100
export https_proxy=http://serviceproxy.se.mydomain:8100

odo create -v 9
I0903 11:23:18.584796   32355 util.go:734] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
I0903 11:23:18.584957   32355 util.go:755] Response will be cached in /tmp/odohttpcache for 1h0m0s
I0903 11:23:18.585102   32355 util.go:768] Cached response used.
I0903 11:23:18.586337   32355 loader.go:375] Config loaded from file:  /usr/users/edno02/.kube/config
I0903 11:23:18.588523   32355 loader.go:375] Config loaded from file:  /usr/users/edno02/.kube/config
I0903 11:23:18.589110   32355 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: odo/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer Dj1JAz0CqGSU9iXkRLQqPEp7d5chkezZx1TOBoK_llU" 'https://api.sb.se.mydomain:6443/apis/project.openshift.io/v1/projects/odo-demo2-openliberty'
I0903 11:23:18.634480   32355 round_trippers.go:443] GET https://api.sb.se.mydomain:6443/apis/project.openshift.io/v1/projects/odo-demo2-openliberty 200 OK in 45 milliseconds
I0903 11:23:18.634495   32355 round_trippers.go:449] Response Headers:
I0903 11:23:18.634500   32355 round_trippers.go:452]     Content-Type: application/json
I0903 11:23:18.634504   32355 round_trippers.go:452]     Date: Thu, 03 Sep 2020 09:22:43 GMT
I0903 11:23:18.634509   32355 round_trippers.go:452]     X-Kubernetes-Pf-Flowschema-Uid: 8f5020ea-7f89-4d94-ba42-54199ffeb13c
I0903 11:23:18.634513   32355 round_trippers.go:452]     X-Kubernetes-Pf-Prioritylevel-Uid: bb8d3645-3539-4b87-a21c-0370a9ef9d33
I0903 11:23:18.634518   32355 round_trippers.go:452]     Content-Length: 1411
I0903 11:23:18.634521   32355 round_trippers.go:452]     Audit-Id: aad822a7-cd69-45a4-9c1b-37f39029cc11
I0903 11:23:18.634525   32355 round_trippers.go:452]     Cache-Control: no-cache, private
I0903 11:23:18.634530   32355 round_trippers.go:452]     Cache-Control: no-store
I0903 11:23:18.634564   32355 request.go:1022] Response Body: {"kind":"Project","apiVersion":"project.openshift.io/v1","metadata":{"name":"odo-demo2-openliberty","selfLink":"/apis/project.openshift.io/v1/projects/odo-demo2-openliberty","uid":"22cf193f-8c68-4ea4-a977-72ab337d8ca0","resourceVersion":"142095013","creationTimestamp":"2020-09-02T12:15:13Z","annotations":{"openshift.io/description":"","openshift.io/display-name":"","openshift.io/requester":"joya02","openshift.io/sa.scc.mcs":"s0:c32,c9","openshift.io/sa.scc.supplemental-groups":"1001010000/10000","openshift.io/sa.scc.uid-range":"1001010000/10000"},"managedFields":[{"manager":"openshift-apiserver","operation":"Update","apiVersion":"v1","time":"2020-09-02T12:15:13Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:openshift.io/description":{},"f:openshift.io/display-name":{},"f:openshift.io/requester":{}}},"f:status":{"f:phase":{}}}},{"manager":"openshift-controller-manager","operation":"Update","apiVersion":"v1","time":"2020-09-02T12:15:13Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:finalizers":{}}}},{"manager":"cluster-policy-controller","operation":"Update","apiVersion":"v1","time":"2020-09-02T12:15:19Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:openshift.io/sa.scc.mcs":{},"f:openshift.io/sa.scc.supplemental-groups":{},"f:openshift.io/sa.scc.uid-range":{}}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
I0903 11:23:18.635256   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
Experimental mode is enabled, use at your own risk

I0903 11:23:18.635346   32355 util.go:429] path .odo/config.yaml doesn't exist, skipping it
I0903 11:23:18.635355   32355 util.go:429] path .odo/env/env.yaml doesn't exist, skipping it
I0903 11:23:18.635361   32355 util.go:429] path devfile.yaml doesn't exist, skipping it
I0903 11:23:18.635366   32355 util.go:429] path devfile.yaml doesn't exist, skipping it
I0903 11:23:18.635372   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:18.636879   32355 loader.go:375] Config loaded from file:  /usr/users/edno02/.kube/config
I0903 11:23:18.637446   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:18.637561   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:18.637671   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:18.637714   32355 util.go:734] HTTPGetRequest: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/index.json
I0903 11:23:18.637760   32355 util.go:755] Response will be cached in /tmp/odohttpcache for 15m0s
I0903 11:23:18.637873   32355 util.go:768] Cached response used.
? Which devfile component type do you wish to create  [Use arrows to move, type to filter]
  java-maven
> java-openliberty
  java-quarkus
  java-springboot
  nodejs
? Which devfile component type do you wish to create java-openliberty
? What do you wish to name the new devfile component (java-openliberty)
? What do you wish to name the new devfile component java-openliberty
I0903 11:23:21.710640   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
? What namespace do you want the devfile component to be created in (odo-demo2-openliberty)
? What namespace do you want the devfile component to be created in odo-demo2-openliberty
I0903 11:23:23.319280   32355 util.go:429] path devfile.yaml doesn't exist, skipping it
Validation
 •  Checking devfile existence  ...
 ✓  Checking devfile existence [20274ns]
 •  Checking devfile compatibility  ...
 •  Creating a devfile component from registry: DefaultDevfileRegistry  ...
 ✓  Checking devfile compatibility [43752ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [47388ns]
I0903 11:23:23.319410   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
 •  Validating devfile component  ...
I0903 11:23:23.319517   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
 ✓  Validating devfile component [59150ns]
I0903 11:23:23.319567   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:23.319609   32355 util.go:429] path devfile.yaml doesn't exist, skipping it
I0903 11:23:23.319617   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:23.319651   32355 preference.go:209] The path for preference file is /usr/users/edno02/.odo/preference.yaml
I0903 11:23:23.319697   32355 util.go:734] HTTPGetRequest: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/java-openliberty/devfile.yaml
I0903 11:23:23.319748   32355 util.go:755] Response will be cached in /tmp/odohttpcache for 15m0s
I0903 11:23:23.319891   32355 util.go:768] Cached response used.
I0903 11:23:23.320114   32355 context.go:69] absolute devfile path: '/usr/users/edno02/projects/lek/devfile.yaml'
I0903 11:23:23.320466   32355 content.go:33] converted devfile YAML to JSON
I0903 11:23:23.320541   32355 apiVersion.go:50] devfile apiVersion: '2.0.0'
I0903 11:23:23.320562   32355 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
I0903 11:23:23.327376   32355 schema.go:47] validated devfile schema
I0903 11:23:23.327923   32355 validate.go:37] Successfully validated devfile sections
? Do you want to download a starter project (y/N) y
? Do you want to download a starter project Yes

Starter Project
 •  Downloading starter project user-app from https://github.com/OpenLiberty/application-stack.git  ...
I0903 11:23:27.596231   32355 util.go:734] HTTPGetRequest: https://codeload.github.com/OpenLiberty/application-stack/legacy.zip/master
 ✗  Downloading starter project user-app from https://github.com/OpenLiberty/application-stack.git [30s]
 ✗  Get https://codeload.github.com/OpenLiberty/application-stack/legacy.zip/master: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

## Actual behavior
Download of starterproject times out.

## Expected behavior
To download the starter project and apply it according to the odo template.

## Any logs, error output, etc?

I have verefied that I can downlodad and clone https://codeload.github.com/OpenLiberty/application-stack/legacy.zip/master and https://github.com/OpenLiberty/application-stack.git behind the proxy

wget https://codeload.github.com/OpenLiberty/application-stack/legacy.zip/master
--2020-09-03 11:24:08--  https://codeload.github.com/OpenLiberty/application-stack/legacy.zip/master
Resolving serviceproxy.se.mydomain (serviceproxy.se.mydomain)... 172.18.80.36, 172.18.80.35
Connecting to serviceproxy.se.mydomain (serviceproxy.se.mydomain)|172.18.80.36|:8100... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master’

    [ <=>                                                                    ] 32,777      --.-K/s   in 0.03s  

2020-09-03 11:24:08 (1.10 MB/s) - ‘master’ saved [32777]

git clone https://github.com/OpenLiberty/application-stack.git
Cloning into 'application-stack'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 329 (delta 17), reused 25 (delta 10), pack-reused 291
Receiving objects: 100% (329/329), 60.39 KiB | 0 bytes/s, done.
Resolving deltas: 100% (97/97), done.

**Comment by NissesSenap** [comment]
In the end i solved this by adding my company specific settings.xml to the same folder and overwriting some values in the devfile to use. Thus it was able to download it from my internal artifactory. 
It's not a bug but, there is a big lack of documentation.

**Comment by mclhrn** [comment]
> In the end i solved this by adding my company specific settings.xml to the same folder and overwriting some values in the devfile to use. Thus it was able to download it from my internal artifactory. It's not a bug but, there is a big lack of documentation.

Can you elaborate on what this looks like? I am struggling with this issue as well...

**Comment by NissesSenap** [comment]
@mclhrn I don't work at the same company any more so I can't access it. But the important part is that you add your proxy settings to your xml file that odo uses.
At the last company I was we have xml files that was in our .m2 folder so we always had these settings by default. But of course ODO couldn't reach it. So we had to add this config file to the xml file that odo ran so it was able to get the proxy config.

I hope this point you in the correct direction, I'm talking it all from memory and it was some time ago so I can defiantly be wrong.

**Comment by mclhrn** [comment]
> @mclhrn I don't work at the same company any more so I can't access it. But the important part is that you add your proxy settings to your xml file that odo uses. At the last company I was we have xml files that was in our .m2 folder so we always had these settings by default. But of course ODO couldn't reach it. So we had to add this config file to the xml file that odo ran so it was able to get the proxy config.
> 
> I hope this point you in the correct direction, I'm talking it all from memory and it was some time ago so I can defiantly be wrong.

Thanks @NissesSenap it did indeed. I ended up dropping in a local settings.xml and point the odo commands at this file. Thanks again
