### ISSUE TITLE
The `odo test` command doesn't give enough feedback, by default; odo test exit status

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#3899]
/kind bug

(This is a minor suggestion, not really a true "bug").

## What versions of software are you using?

**Operating System:**  Win10, Linux

**Output of `odo version`:** 1.2.6

## How did you run odo exactly?

A sequence like: 

1.  `odo create java-openliberty --starter`
2. `odo test`

## Actual behavior

$ odo test

Executing devfile test command for component dd3win10
 -  Executing test command "mvn -Dmaven.repo.local=/mvn/repository -Dmicroshed_hostname=localhost -Dmicroshed_http_port=9080 -Dmicroshed_manual_env=true -Dmicroshed_app_context_root=/ failsafe:integration-test", if not runnin

## Expected behavior

I'd expect that by default I'd see some indication of whether my tests pass or fail, e.g. the output I get if I do:  `odo test -v 1`.   In other words, I'm wondering if the default `-v 0`  logging should include the log records currently logged at `-v 1`.

Another idea (which could be combined or separated from this one):

Could `odo test` propagate an exit status/code, so that success return 0 in `$?`  and failure non-zero?

**Comment by mik-dass** [comment]
Currently we have `--show-log` to get the logs of the test run but the error status/code is not propagated.
You want `odo test` to show the logs by default without logs and also propagate the exit status/code?

**Comment by scottkurz** [comment]
> 
> Currently we have `--show-log` to get the logs of the test run but the error status/code is not propagated.
> You want `odo test` to show the logs by default without logs and also propagate the exit status/code?

@mik-dass  - yes, that was my suggestion.  Thanks

**Comment by scottkurz** [comment]
I think `odo test` already does propagate the exit status...  I should've been using:

`mvn ...  failsafe:integration-test failsafe:verify`

not just:

`mvn ...  failsafe:integration-test`
