### ISSUE TITLE
converting s2i items to devfile items does not set the Endpoint's name properly

### ISSUE THREAD

**Issue by yangcao77** [openshift/odo#3910]
/kind bug
/area devfile
/area url

Converting s2i items to devfile items does not set the Endpoint's name properly. 

## How did you run odo exactly?

run `odo url create url1 --port 8080` for a s2i item
and run `odo utils convert-to-devfile`

## Actual behavior
the endpoint created in devfile is named `port-8080`

## Expected behavior
expect to use the urlName defined during url creation

**Comment by adisky** [comment]
#3930 resolves this
