### ISSUE TITLE
installing odo documents changes for IBM  Z platform 

### ISSUE THREAD

**Issue by PanYaLian** [openshift/odo#3913]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Here is the link for installing odo, https://odo.dev/docs/installing-odo/, and I think it is from https://github.com/openshift/odo/blob/master/docs/public/installing-odo.adoc. since we have add IBM Z support for odo, we hope to update the doc to include  some instructions for installing odo on IBM Z

**Comment by jichenjc** [comment]
@PanYaLian can we be more specific on what we hope to change and what's the proposal etc if you have ?

**Comment by PanYaLian** [comment]
just like what we did on odo 1.2.5 for Z,  add the following content for installing odo on Linux on IBM Z and LinuxONE
@zhengxiaomei123  you mentioned in https://github.com/openshift/odo/issues/3725#issuecomment-673909339 that it is not required since "the v2.0.0-alpha of odo is not available for s390x, tips are required for user." Now we have already pass CI test on odo 2.0 -alpha,  do we need to modify the doc now?
```
Installing odo on Linux on IBM Z and LinuxONE
Binary installation
# curl -L https://github.com/openshift/odo/releases/download/v2.0.0-alpha-2/odo-linux-s390x -o /usr/local/bin/odo
# chmod +x /usr/local/bin/odo

```

**Comment by PanYaLian** [comment]
Done
