### ISSUE TITLE
"remotes" property under starterProjects conflicts the devfile 

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3915]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Steps:

```
$ odo preference view
PARAMETER             CURRENT_VALUE
UpdateNotification    
NamePrefix            
Timeout               
BuildTimeout          
PushTimeout           
Experimental          true
PushTarget            

$ odo project create blah
 ✓  Project 'blah' is ready for use
 ✓  New project created and now using project: blah

$ mkdir -p testinvdevfile

// Copy the project from ../tests/examples/source/devfiles/nodejs/
$ cd testinvdevfile/project/      

$ odo create nodejs abcdef
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile existence [4ms]
 ✓  Checking devfile compatibility [361854ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [356773ns]
 ✓  Validating devfile component [417716ns]

Please use `odo push` command to create the component with source deployed

// replace the existing devfiles `..testinvdevfile/project/devfile.yaml` content with 
 `../tests/examples/source/devfiles/nodejs/devfile-with-parent.yaml` then `odo push`
$ odo push --project blah
 ✗  invalid devfile schema. errors :
- starterProjects.0.git: Additional property remotes is not allowed
```

## Actual behavior

Parent devfile triggers `https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml` devfile.yaml file which has `remotes` property under `starterProjects.0.git` . It seems we can not add such properties in the devfile, though I am not sure.
I will try to get the root cause but it is critical issue which is blocking our master CI to run

## Expected behavior

devfile should accept such properties.

## Any logs, error output, etc?

Verified manually as well it is breaking our master CI.

**Comment by adisky** [comment]
@prietyc123 can you add link to the failure here? Mostly it could me solved by rebasing the PR's.

**Comment by prietyc123** [comment]
> @prietyc123 can you add link to the failure here? Mostly it could me solved by rebasing the PR's.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3906/pull-ci-openshift-odo-master-v4.5-integration-e2e/1303387080759447552#1:build-log.txt%3A1006

**Comment by prietyc123** [comment]
@adisky I have also rebased my pr lets see how it works. Thanks.

**Comment by adisky** [comment]
> @adisky I have also rebased my pr lets see how it works. Thanks.

 I tries, not reproducible locally on latest master,  PR needs rebase.

**Comment by prietyc123** [comment]
Ah Yes I tried this again on the latest master and it works. Thanks @adisky 

/close
