### ISSUE TITLE
Help for `odo push -f` should explain that the full set of project source is pushed to the container

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#3919]
/kind documentation

## What mistake did you find / what is missing in the documentation?

The `odo help push` output shows:

>   -f, --force-build            Use force-build flag to force building the component

but this omits the important fact that the entire project is pushed/synced to the appropriate container, as opposed to the default behavior in which only the files odo has detected as changed are pushed.

I think this is a moderately intutitive analogue to say `git push -f`... it's not obvious but once you learn the behavior I think one can accept and appreciate it (or I could).

But the doc should at least describe this behavior.   I would never think that "force building the component" covers this.

**Comment by johnmcollier** [comment]
@scottkurz How about something like: ` Use force-build flag to re-sync and force-build the component`?

**Comment by scottkurz** [comment]
@johnmcollier  - maybe just a bit more explicit?
`Use force-build flag to re-sync and force-build the entire component (not just changed files)` ?

**Comment by johnmcollier** [comment]
@scottkurz I'm not crazy about the `(not just changed files)` part, what about
```
Use force-build flag to re-sync the entire source code and force-build the component`?
```

**Comment by scottkurz** [comment]
> 
> 
> @scottkurz I'm not crazy about the `(not just changed files)` part, what about
> 
> `Use force-build flag to re-sync the entire source code and force-build the component`?

That's fine.. I have to admit though I'm a bit ignorant about what the "force-build" part of this means.   Does this signify doing something beyond re-synching the entire source code?   Wouldn't it build anyway on a push ?

**Comment by johnmcollier** [comment]
Probably `re-build the component` is better than `force-build the component` I'm thinking. `force-build` is really just re-syncing everything and re-building, the build itself is no different

**Comment by elsony** [comment]
If the behaviour is re-sync everything and rebuild, I agree `re-build` is better than `force-build`.  The other term that we can consider is `clean-build`
