### ISSUE TITLE
Beta release: Operator Hub does NOT work & tests are disabled (tracking issue) 

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3932]
/kind bug

## Beta information / tracking information

This is an open issue to track that Operator Hub / services do NOT work in the current beta.

Everything else should work as intended. 

- [ ] Operator Hub tests are currently DISABLED in this commit in the `beta` branch: https://github.com/openshift/odo/commit/59cc5d2508b9e98bee93cba288d2a313b600cf16
- [ ] Operator Hub does NOT work, however https://github.com/openshift/odo/pull/3922 will fix it.

**Comment by dharmit** [comment]
I have opened PR https://github.com/openshift/odo/pull/3937 which is basically the work I did in PR #3883 rebased on top of beta branch.

Before opening the PR, I manually verified on CRC box running OpenShift 4.5 that the tests in `tests/integration/operatorhub` directory and `tests/integration/cmd_link_unlink_test.go` file cleared.

I have uncommented the Operator Hub tests as well.

**Comment by dharmit** [comment]
This has been fixed via #3938. It was an issue with certain tests other than those for Operator Hub not working on the CI. Commenting those tests helped sort things.

/close
