### ISSUE TITLE
rename odo env variable namespace to project

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3947]
We are using "project" everywhere else in odo. We even have `odo project` command.

`odo env` should follow the same terminology

**Comment by metacosm** [comment]
I understand the will to make things consistent. However, doesn't that go against the idea of making odo more k8s-native as opposed to OpenShift-centric? If anything, wouldn't it make more sense (though, of course, that's a much bigger endeavor) to rename everything project-related to namespace?

**Comment by kadel** [comment]
I view it similarly as what we do with url. We have `odo url` as an abstraction for Ingress and Routes. So here I look at the project not as OpenShift project, but as a generic project term that has nothing to do with OpenShift projects, but it is more abstraction on top of Kubernetes Namespaces and OpenShift projects.
