### ISSUE TITLE
Beta testing on windows and macOS

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3952]
/kind user-story
/area testing

## User Story
As a QE I want to run test scripts on windows and macOS host successfully

## Acceptance Criteria 
- [x] Test scripts should pass on macOS
- [x] Test scripts should pass on windows

**Comment by amitkrout** [comment]
verified [beta-2](https://github.com/openshift/odo/releases/tag/v2.0.0-beta-1) bit on macOS host with one symlink issue - https://github.com/openshift/odo/issues/3797.

**Comment by prietyc123** [comment]
verified the bits on windows and everything looks fine. The issue faced was known and it has already been tracked.

/close
