### ISSUE TITLE
Determine if we want to keep Docker support in experimental mode, or disable it

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3955]
~As discussed on today's odo contributor's call, for the time-being, let's hardcode the `pushtarget` preference in odo to Kube, and don't allow it to be set to `Docker`~

The Docker support in odo is currently not being developed, and is not feature-equivalent with a number of v2 odo features that are available when using Kube/OpenShift. We should determine if we can safely disable it or if there's value in keeping it gated behind experimental mode for now.

I have a PR up at https://github.com/openshift/odo/pull/3956 (currently on hold) that will disable the pushtarget functionality, but does not yet remove all of the Docker adapter code.

/assign
/area devfile
/area local

**Comment by kadel** [comment]
A few people expressed a desire to keep Docker in experimental mode until we have a clear view of all implications

**Comment by johnmcollier** [comment]
Discussed on a call last week. We'll keep it in for now, behind experimental mode and re-evaluate it in the future if needed.

Gonna close out this issue for now, feel free to re-open when this comes up again in the future
