### ISSUE TITLE
"odo link" doesn't link a devfile component with a service catalog backed service

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3965]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
1. Created & pushed a nodejs component
1. Started a service on minishift from Service Catalog
1. Tried creating a link between the two.

## Actual behavior
Fails with below message:
```sh
$ odo link dh-postgresql-apb 
 ✗  The service was not created via odo. Please delete the service and recreate it using 'odo service create dh-postgresql-apb'
```

## Expected behavior
It should link the two

/area component
/kind bug

**Comment by dharmit** [comment]
I have pushed a fix for this to [my branch](https://github.com//dharmit/odo/tree/fix-3965). The catch here is that component's URL fails to load after doing `odo link`. And if we do `odo push`, the link information gets deleted. Not spending more time on this since it's "3.x + devfile".

Would make sense to spend more cycles if there are users looking for this.

**Comment by dharmit** [comment]
@girishramnani unassigned myself from this based on our discussion.

**Comment by scottkurz** [comment]
Should this now be closed because of: https://github.com/openshift/odo/issues/4890 ?

**Comment by dharmit** [comment]
Indeed. Thanks for pointing @scottkurz 👍🏾 

/close
