### ISSUE TITLE
Enable service catalog on minikube using PSI cluster

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3980]
Running service catalog tests on 3.11 PSI cluster requires service catalog to be enabled.
https://issues.redhat.com/browse/ODO-40

**Comment by dharmit** [comment]
We could try to run Service Catalog tests on k8s (minikube) because that's where we mainly expect odo users to use it. I get it that it's available on 3.11 as well. But more users of the Service Catalog would be on k8s than on OCP 3.11.

WDYT @kadel?

/remove-lifecycle rotten

**Comment by prietyc123** [comment]
Enabling service catalog on 3.11 would be addressed in #4288. As far as Service Catalog tests on k8s (minikube) is concerned, yes we can work on it once we close #4287 . As this issue is left out with minikibe service catalog implementation, changing issue title.

**Comment by prietyc123** [comment]
Steps needs to be verified and implemented:
- [ ] Install helm
- [ ] kubernetes configuration file needs to be installed https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/
- [ ] Helm repository setup 
- [ ] Install service catalog
- [ ] Run operator hub tests on it successfully, Resolve blockers if any
- [ ] Create a custom image and modify jenkins configuration script accordingly

**Comment by prietyc123** [comment]
Working on https://github.com/openshift/odo/issues/4287 to get fixed first. Then jump into add ons.

**Comment by kadel** [comment]
> Working on #4287 to get fixed first. Then jump into add ons.

#4287 was fixed.
We need to start working on this again. We currently don't test ServiceCatalog integration at all and that is a problem.

**Comment by prietyc123** [comment]
We are removing service catalog from odo

/close
