### ISSUE TITLE
make goget-tools fails due to go mod dependency

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3983]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Failure on CI 

```
$ make goget-tools
https://go-review.googlesource.com/c/go/+/198438/
GOFLAGS='' go get github.com/onsi/ginkgo/ginkgo@v1.14.0
go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make: *** [goget-ginkgo] Error 1
```
I have also verified it locally and hitting the same failure. 

## Actual behavior

It seems like issue is in vendor file github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 which has some dependency. 

## Expected behavior

Need to explore more on fixing the real issue.

## Any logs, error output, etc?

Detailed logs: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.5-integration-e2e-periodic/1306835554498777088#1:build-log.txt%3A479

**Comment by kadel** [comment]
fix in  https://github.com/openshift/odo/pull/3984
