### ISSUE TITLE
"odo link -h" output is too long to comprehend

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4011]
At the moment, `odo link -h` output is very long. We should consider reducing the number of scenarios/examples in the output to make it more understandable for an end-user.

A command's help message should not become a substitute for documentation. Detailed scenarios should be covered in documentation. 

/kind cleanup
/area service-operators
/area component

**Comment by mohammedzee1000** [comment]
Figuring out how to shorten the help message
