### ISSUE TITLE
Add better message for component create when devfile does not exists

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4018]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
Master

## How did you run odo exactly?

Common steps on 4.5 and 3.11 cluster:
```
$ odo project create wcldizlwqg 
✓  Project 'wcldizlwqg' is ready for use
 ✓  New project created and now using project: wcldizlwqg

$ odo registry list
 ✗  No devfile registries added to the configuration. Refer `odo registry add -h` to add one

$ oc --request-timeout 5m import-image nodejs:latest --namespace=wcldizlwqg --from=docker.io/centos/nodejs-10-centos7:latest --confirm
imagestream.image.openshift.io/nodejs imported

Name:                   nodejs
Namespace:              wcldizlwqg
Created:                Less than a second ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2020-09-22T15:08:26Z
Image Repository:       image-registry.openshift-image-registry.svc:5000/wcldizlwqg/nodejs
Image Lookup:           local=false
Unique Images:          1
Tags:                   1

latest
  tagged from docker.io/centos/nodejs-10-centos7:latest
[...]

$ oc annotate istag/nodejs:latest --namespace=wcldizlwqg tags=builder --overwrite
imagestreamtag.image.openshift.io/nodejs:latest annotated
```

On 4.5 cluster
```
$ odo create nodejs:latest nodejs-app --project wcldizlwqg --context . --app app
Devfile path: 
 ⚠  Registry is empty, please run `odo registry add <registry name> <registry URL>` to add a registry

Validation
 ✓  Validating component [483ms]

Please use `odo push` command to create the component with source deployed

$ odo push --context .
Validation
 ✓  Checking component [864ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [3s]
[...]
✓  Changes successfully pushed to component
```

On 3.11 cluster running on travis
```
Running odo with args [odo create nodejs:latest nodejs-app --project wcldizlwqg --context /tmp/396049560 --app app]
[...]
[odo] Devfile path: 
[odo] I0920 18:33:45.143396   28128 util.go:425] path /tmp/396049560/.odo/config.yaml doesn't exist, skipping it
[odo] I0920 18:33:45.143411   28128 util.go:425] path /tmp/396049560/.odo/env/env.yaml doesn't exist, skipping it
[odo] I0920 18:33:45.143428   28128 util.go:425] path /tmp/396049560/devfile.yaml doesn't exist, skipping it
[odo] I0920 18:33:45.143439   28128 preference.go:209] The path for preference file is /tmp/396049560/config.yaml
[odo] I0920 18:33:45.144850   28128 util.go:425] path /tmp/396049560/devfile.yaml doesn't exist, skipping it
[odo] I0920 18:33:45.144868   28128 preference.go:209] The path for preference file is /tmp/396049560/config.yaml
[odo] I0920 18:33:45.144939   28128 preference.go:209] The path for preference file is /tmp/396049560/config.yaml
[odo] I0920 18:33:45.144965   28128 preference.go:209] The path for preference file is /tmp/396049560/config.yaml
[odo] I0920 18:33:45.144983   28128 util.go:730] HTTPGetRequest: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/index.json
[odo] I0920 18:33:45.145046   28128 util.go:751] Response will be cached in /tmp/odohttpcache for 15m0s
[odo] I0920 18:33:45.145194   28128 util.go:764] Cached response used.
[odo] I0920 18:33:45.145391   28128 preference.go:209] The path for preference file is /tmp/396049560/config.yaml
[odo] I0920 18:33:45.145443   28128 util.go:425] path /tmp/396049560/devfile.yaml doesn't exist, skipping it
[odo] Validation
[odo]  •  Checking devfile existence  ...
[odo]  ✗  Checking devfile existence [10659ns]
[odo]  •  Checking devfile compatibility  ...
[odo]  ✗  Checking devfile compatibility [4744ns]
[odo]  ⚠  Devfile component type nodejs:latest is not supported, please run `odo catalog list components` for a list of supported devfile component types
[odo] I0920 18:33:45.145522   28128 preference.go:209] The path for preference file is /tmp/396049560/config.yaml
[odo] I0920 18:33:45.152353   28128 occlient.go:764] Found exact image tag match for nodejs:latest
[...]

 ✓  Validating component [19ms]
[odo] 
[odo] Please use `odo push` command to create the component with source deployed
[odo] I0920 18:33:45.198019   28128 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)

Running odo with args [odo push --context /tmp/396049560]
[...]
✓  Changes successfully pushed to component
```
logs: https://travis-ci.com/github/openshift/odo/jobs/387731515#L1549-L1572

## Expected behavior

AFAIU it should fail on creating s2i component when we don't pass `--s2i` flag and `defaultDevfileRegistry` are also not added.

**Comment by prietyc123** [comment]
ping @dev-gaur

**Comment by dev-gaur** [comment]
### EXPLANATION

Hi @prietyc123 , just to clear out. Absense of --s2i flag ( or --s2i=false) doesn't rule out the ability to create S2I type components. 
If odo can't find a `Devfile type` component named `nodejs` then it will it automatically create the `s2i type` `nodejs` type 
component.

However, If --s2i flag is present (--s2i=true). Then odo ENFORCES the creation of an s2i type component or fails if no s2i component is found with the requested name.

Please refer to #3545

The main motive behind the introduction of `--s2i` was to resolve the conflict when two components ( 1 devfile type and 1 s2i type ) have the same name (which the case with nodejs , when defaultDevfileRegistry is added ) .
By default, the devfile type nodejs component will be created. 
But for users who want to force the creation of the s2i type nodejs component, can use the `--s2i` flag.

You can check the screenshot below. When --s2i flag is passed. odo create command doesn't even bother checking the devfile components list.

![image](https://user-images.githubusercontent.com/7551036/94351467-5e1c8380-0076-11eb-9dca-3a14d0a91f95.png)



### CONCLUSION

For the the s2i specific e2e scenarios, you should use --s2i flag to ensure the enforcement of s2i type components. While same some computing time :) . You won't even have to bother checking `odo registry list` .

I'm closing the issue now. Please re-open if you still have any doubt.

**Comment by prietyc123** [comment]
> For the the s2i specific e2e scenarios, you should use --s2i flag to ensure the enforcement of s2i type components. 

@dev-gaur Understood. However I am really concerned about the scenario where user specifically trying to create s2i component and forgot/does not aware of `--s2i` flag. In that case don't you think we should let user decide what type of component they need. Like if user does not mention `--s2i` flag lets ask them what type of component they need using interactive mode. If they say `s2i` we will add `--s2i` functionality to the create command and create the component. For devfile it will as it is. Please let me know your point of view.

**Comment by dev-gaur** [comment]
Even If the user does not provide the --s2i flag, they can create s2i type components. Its just that if there is a devfile type component with name, for eg., nodejs and another component type nodejs available in the catalog list. Devfile type nodejs will be created. If the user wants to create S2i based nodejs, --s2i flag will help them with it.


If there is no conflict of names, `odo create cmpType` command behaves like this :

1. Check if cmpType exists in the devfileCatalogList, if yes, Create devfile component and exit successfully. if no, try step 2.
2. Check if cmpType exists in the s2iCatalogList,  if yes, Create the s2i type component. Else, exit and log "No component found for cmpType".

For eg., for the command, `odo create php` the s2i type component php component will be created because there is no devfile type php component.

**Comment by prietyc123** [comment]
@dev-gaur As per our 1-1 and cabal discussion, if devfile does not exists in the context `odo create cmpType:version` should fail on 3.11/4.* cluster but with better message until we add versioning feature in devfile. So I am changing the title of the issue accordingly.
