### ISSUE TITLE
postStart command never runs if odo loses connectivity during initial push

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#4030]
/kind bug

## PROBLEM BACKGROUND 

I've noticed a couple cases where there is an issue on the initial push, preventing the "postStart" command from ever running.

Before adding a "postStart" command to my devfile (e..g [here](https://github.com/OpenLiberty/application-stack/blob/62fa765a719b53c377ddbb28de764ee9bc5f2fa4/dev/devfile.yaml#L86-L88) this wasn't a big deal, my build and run commands would still function and things would be made right on the next push if necessary.  

In one case, I hit this on the initial push: 
> I0924 10:10:26.763248   23568 streamwatcher.go:114] Unexpected EOF during watch stream event decoding: unexpected EOF
>  X  Waiting for component to start [1m]
>  X  Failed to start component with name c8. Error: Failed to create the component: error while waiting for deployment rollout: watch channel was closed

This has happened to me now and then on my cluster, working from home, say once every 10-20 times.   

But my component is useless now, the **postStart** didn't run and won't ever run.

Here is a log: [a.zip](https://github.com/openshift/odo/files/5277192/a.zip)

### Another case

Another case in which I saw a similar problem is when I had an active file in the project dir that I hadn't yet added to .gitignore.   (Maybe this is more obviously user error).

## DISCUSSION

It's possible this could be classified as working as designed, but l thought it was worth bringing up.       

Is the user responsible for understanding and verifying that postStart was successful?  
Should odo be doing something around postStart, ensuring it runs?   
Or is it just a matter of fixing all the individual problems that can cause a "loss of connectivity" in my terms?

### RELATED ISSUES:
https://github.com/openshift/odo/issues/3905
https://github.com/openshift/odo/issues/4017

## What versions of software are you using?

**Operating System:**  Win10

**Output of `odo version`:** odo v2.0.0

**Comment by sarveshtamba** [comment]
Hi @scottkurz, I was hitting this `Unexpected EOF during watch stream event decoding: unexpected EOF` while running latest odo test suites on one of my clusters earlier ( tracked via issue #3905 ). Now, I am hitting this same issue on another cluster which was good earlier ( all odo test suites for ppc64le were passing on it ) and was working fine consistently. Any thing that I can do to resolve/avoid/workaround this issue?

**Comment by scottkurz** [comment]
> 
> 
> Hi @scottkurz, I was hitting this `Unexpected EOF during watch stream event decoding: unexpected EOF` while running latest odo test suites on one of my clusters earlier ( tracked via issue #3905 ). Now, I am hitting this same issue on another cluster which was good earlier ( all odo test suites for ppc64le were passing on it ) and was working fine consistently. Any thing that I can do to resolve/avoid/workaround this issue?

In my experience, simply pushing a second time will often, in general, work for a devfile that doesn't define a postStart command.

**Comment by kadel** [comment]
Not sure if odo will ever be able to completely recover from `Unexpected EOF during watch stream event decoding: unexpected EOF`

The safest thing to do after this is `odo delete` and `odo push -f`. :-/ 

Odo already communicates to the user whenever the postStart command failed or not. 
```

Executing postStart event commands for component python-ex
 ✗  Executing poststart command "false" [1s]
 ✗  Failed to start component with name python-ex. Error: Failed to create the component: unable to execute devfile command postStart: unable to execute the run command: unable to exec command [/bin/sh -c false]:
: error while streaming command: command terminated with exit code 1
```


But you are right that we have a problem in odo. If an event command like `postStart` fails we don't have a way to re-trigger it.

I created a user story to address this, can you please provide your input? https://github.com/openshift/odo/issues/4142

**Comment by kadel** [comment]
We could also look into checking if postStart command successes and trying to invoke it again with the next `odo push`.
This might be a better solution for this particular issue

**Comment by sarveshtamba** [comment]
@kadel any luck here?
