### ISSUE TITLE
odo create nodejs failed on unable to unmarshal devfile on 4.6 cluster

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4031]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Running on 4.6 cluster

```
$ odo create nodejs --context . bchdcg
Devfile path: 
 ⚠  Registry DefaultDevfileRegistry is not set up properly with error: Unable to unmarshal the devfile index.json from https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/index.json: invalid character ']' after top-level value, please check the registry URL and credential (refer `odo registry update --help`)
Validation
 ✗  Checking devfile existence [52519ns]
 ⚠  Devfile component type nodejs is not supported, please run `odo catalog list components` for a list of supported devfile component types
Validation
Warning: nodejs is not fully supported by odo, and it is not guaranteed to work
 ✓  Validating component [800ms]
Please use `odo push` command to create the component with source deployed
```

Note: image stream on 4.6. is `registry.redhat.io/ubi8/nodejs-12:latest` 

## Actual behavior

It fails to get the devfile to create the component

## Expected behavior

index.json has the `ubi8` image
```
[
  {
    "name": "java-maven",
    "displayName": "Maven Java",
    "description": "Upstream Maven and OpenJDK 11",
    "tags": [
      "Java",
      "Maven"
    ],
    "projectType": "maven",
    "language": "java",
    "links": {
      "self": "/devfiles/java-maven/devfile.yaml"
    }
  },
[...]
  {
    "name": "nodejs",
    "displayName": "NodeJS Runtime",
    "description": "Stack with NodeJS 12",
    "tags": [
      "NodeJS",
      "Express",
      "ubi8"
    ],
    "projectType": "nodejs",
    "language": "nodejs",
    "links": {
      "self": "/devfiles/nodejs/devfile.yaml"
    }
  },
```
It should not fail. Debugging into the issue to get more content.

**Comment by johnmcollier** [comment]
This looks like this weird registry response-caching issue @cdrage and I have seen before.  

@prietyc123 If you run `odo preference set registrycachetime 0`, does `odo create nodejs` now work?

**Comment by kadel** [comment]
I don't see how this error can be related to the openshift version that is being used.

@johnmcollier has a good point. This might be related to weird issues with catching that we sometimes see.

**Comment by prietyc123** [comment]
> This looks like this weird registry response-caching issue @cdrage and I have seen before.

Yes, I think that is only the reason behind this.

> @prietyc123 If you run `odo preference set registrycachetime 0`, does `odo create nodejs` now work?

Thanks @johnmcollier I tried setting `registrycashetime` and it works fine for me.
```
$ odo preference set registrycachetime 0
Global preference was successfully updated

$ odo create nodejs --context . bchdcg
Devfile path: 
Validation
 ✓  Checking devfile existence [39297ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [38873ns]
 ✓  Validating devfile component [233921ns]

Please use `odo push` command to create the component with source deployed
```
However I think we need to look for proper fix because on 4.6 I am hitting it frequently 🙁

**Comment by cdrage** [comment]
@kadel Is there any reason we can disable cache / remove it? What benefit does it have at the moment?

**Comment by kadel** [comment]
> @kadel Is there any reason we can disable cache / remove it? What benefit does it have at the moment?

If we disable cache, our CI will soon reach github request limit and start failing. 
The problem is that every `odo create` hits odo devfile registry and does request to `raw.githubusercontent.com` and github applies rate limiting on those requsets.

The other solution would be to update all our tests so they don't use our odo devfile registry and use devfiles present in odo repo unless they really need to (testing the code that handles the registry)

**Comment by adisky** [comment]
@prietyc123 have you seen this error again?

**Comment by dharmit** [comment]
Lowering the priority since this doesn't seem to be an annoyance to anyone. Or no one has said so yet on this issue, AFAICS.

/remove-priority high
/priority medium
