### ISSUE TITLE
odo catalog list components should truncate long descriptions

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#4044]
/kind bug

## What versions of software are you using?

**Operating System:**
MacBook Pro running Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?
odo catalog list components

## Actual behavior
Due to one really long description I had to make my console 207 characters wide to be able to read the output:
```
Odo Devfile Components:
NAME     DESCRIPTION                                                                                                                                                                     REGISTRY

         Che4z Mainframe Basic Stack is an all-in-one extension pack for developers working with z/OS applications, suitable for all levels of mainframe experience, even beginners.     CheDevfileRegistry
```

## Expected behavior
If the description is longer than some reasonable amount (60 chars?) it should be truncated with an ellipsis (...) so that the command is still usable. Especially once users start to create devfiles there could be one that's 200 chars or more.

**Comment by girishramnani** [comment]
technically its not a bug, so making it a feature request

**Comment by mohammedzee1000** [comment]
- [ ] Check length and trunicate description as if needed https://github.com/openshift/odo/blob/master/pkg/odo/cli/catalog/list/components.go#L201-L209
- [ ] Tests to check if very long desription is truncating correctly

**Comment by mohammedzee1000** [comment]
Ok I got something:

```
❯ odo catalog list components
Odo Devfile Components:
NAME                 DESCRIPTION                                                                                                                                                                     REGISTRY
                     Stack for developing NodeJS Angular Web Application                                                                                                                             CheRegistry
                     Stack with tooling ready to develop Integration projects with Apache Camel K                                                                                                    CheRegistry
                     Stack with environment ready to develop Integration projects with Apache Camel based on Spring Boot.                                                                            CheRegistry
                     Che4z Mainframe Basic Stack is an all-in-one extension pack for developers working with z/OS applications, suitable for all levels of mainframe experience, even beginners.     CheRegistry
 ❯ ./odo catalog list components
Odo Devfile Components:
NAME                 DESCRIPTION                                                         REGISTRY
                     Stack for developing NodeJS Angular Web Application                 CheRegistry
                     Stack with tooling ready to develop Integration projects wit...     CheRegistry
                     Stack with environment ready to develop Integration projects...     CheRegistry
                     Che4z Mainframe Basic Stack is an all-in-one extension pack ...     CheRegistry

```

Altho I must say, without a name, that looks weird. Might be a good idea to add names to your stuff

@deboer-tim ^

**Comment by mohammedzee1000** [comment]
@girishramnani personally, I think name must be a required field

**Comment by mohammedzee1000** [comment]
How does someone use them without a name? I think we should skip showing entries without names(show why we are skipping in verbose logs)

**Comment by deboer-tim** [comment]
FWIW, the missing names were due to having used previous experimental versions of odo and having an old registry configured (and yes, you couldn't do anything with them :) ). Once I fixed that it goes to the current registry and names are ok.

+1 to the ... It does show that stack creators need to be a little more concise in the descriptions, but IMHO that's a good thing and this change will help accelerate it.

**Comment by mohammedzee1000** [comment]
Ok il have a WIP pr up shortly. Adding tests for this, however, will be harder as we need a devfile in a registry that has an extra-long description

**Comment by mohammedzee1000** [comment]
> FWIW, the missing names were due to having used previous experimental versions of odo and having an old registry configured (and yes, you couldn't do anything with them :) ). Once I fixed that it goes to the current registry and names are ok.
>
Oki tho I still think we should error if we have entries without a name. It could be graceful like I said, by skipping  those and logging it on -v 4 or something
> +1 to the ... It does show that stack creators need to be a little more concise in the descriptions, but IMHO that's a good thing and this change will help accelerate it.
Done. PR up. If they cant make it concise, then at least they should now try to fit the most important info in 60 chars :)
