### ISSUE TITLE
Misleading url name issue when using the java-openliberty devfile

### ISSUE THREAD

**Issue by sympatheticmoose** [openshift/odo#4060]
/kind bug

## What versions of software are you using?

**Operating System:** MacOS 10.15.7

**Output of `odo version`:**odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?

1. `odo create java-openliberty --starter`
2. `odo url create --host localhost`

## Actual behavior
Output is ` ✓  URL java-openliberty-9080 created for component: java-openliberty`
Then with `odo push` you get the message:
`✓  URL java-openlibert: http://java-openlibert.localhost/ created`

and `odo url list` gives:
<img width="679" alt="Screenshot 2020-09-30 at 13 57 41" src="https://user-images.githubusercontent.com/19860021/94687996-e9bb3c00-0324-11eb-9583-24398ae3c16e.png">

However, you can't do `odo url delete java-openlibert`... ` ✗  the URL java-openlibert does not exist` as the url name is actually `java-openliberty-9080` as with the output msg from `url create`.

## Expected behavior
I'd expect the service to be available at 'java-openliberty-9080.localhost' and the url name to be java-openliberty-9080. Not sure where the truncation is happening.

**Comment by dharmit** [comment]
While I'm not facing the problem you have described, I'm quite sure that the URL character limit is not 15 but 64 characters. However, I'll need to dig the code a bit to find that, and I think it's not mentioned in the docs either. I tried the steps you've mentioned on current latest master:
```sh
$ odo create java-openliberty --starter
 ⚠  odo may not work as expected in a default project, please run the odo component in a non-default project. To create a new project, use `odo project create`.
Validation
 ✓  Checking devfile existence [28898ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [49914ns]
 ✓  Validating devfile component [181975ns]

Starter Project
 ✓  Downloading starter project user-app from https://github.com/OpenLiberty/application-stack-starters.git [2s]

Please use `odo push` command to create the component with source deployed

$ odo url create --host localhost
 ✓  URL java-openliberty-9080 created for component: java-openliberty

To apply the URL configuration changes, please use `odo push`

$ odo url list
Found the following URLs for component java-openliberty
NAME                      STATE          URL                                        PORT     SECURE     KIND
java-openliberty-9080     Not Pushed     http://java-openliberty-9080.localhost     9080     false      ingress
There are local changes. Please run 'odo push'.

$ odo url delete java-openliberty-9080 -f
 ✓  URL java-openliberty-9080 removed from component java-openliberty

To delete the URL on the cluster, please use `odo push`

$ odo url create --host `minikube ip`.nip.io                                      
 ✓  URL java-openliberty-9080 created for component: java-openliberty

To apply the URL configuration changes, please use `odo push`

$ odo url list
Found the following URLs for component java-openliberty
NAME                      STATE          URL                                                   PORT     SECURE     KIND
java-openliberty-9080     Not Pushed     http://java-openliberty-9080.192.168.39.26.nip.io     9080     false      ingress
There are local changes. Please run 'odo push'.
```

**Comment by mik-dass** [comment]
Here's the function which seems to do the truncation https://github.com/openshift/odo/blob/e6be2586f5824bade91599f24686def26b53f1ee/pkg/url/url.go#L1043

and here's the usage during `Push()`
https://github.com/openshift/odo/blob/e6be2586f5824bade91599f24686def26b53f1ee/pkg/url/url.go#L883

**Comment by yangcao77** [comment]
> While I'm not facing the problem you have described, I'm quite sure that the URL character limit is not 15 but 64 characters. 

@dahorak The URL name limit is 64 chars in odo, but when creating ingress/route, it calls `getValidURLName`, which @mik-dass has mentioned. It is required to limit the URL name to be less than 15, because it is limited by K8s
```
The Pod "test-pod" is invalid: spec.containers[0].ports[0].name: Invalid value: "test1test2test34": must be no more than 15 characters
```

The way how odo currently handles it is, odo takes 63 chars URL name, but only takes the front 15 chars upon ingress/route creation; which would cause issue if there are multiple URLs have different name but the first 15 chars are the same. 
I would say it's better to have a 15 chars validation upon url creation.

**Comment by dharmit** [comment]
> I would say it's better to have a 15 chars validation upon url creation.

Makes sense. But `odo url list` should print correct/consistent information. The way it currently works is that `.odo/env/env.yaml` contains the URL name that has to be used for deletion while `odo url list` shows the truncated/trimmed name. If `odo url list` could show the name that has to be used for deletion, that would help users better. @sympatheticmoose WDYT?

> The way how odo currently handles it is, odo takes 63 chars URL name, but only takes the front 15 chars upon ingress/route creation; which would cause issue if there are multiple URLs have different name but the first 15 chars are the same.

I think we should ensure that odo doesn't get into this situation.

**Comment by kadel** [comment]
> I'd expect the service to be available at 'java-openliberty-9080.localhost' and the url name to be java-openliberty-9080. Not sure where the truncation is happening.

I agree with @sympatheticmoose. There is no real reason for truncating names to 15. 
DNS allows a maximum of 63 characters between dots and a maximum total length of 253 characters.

@yangcao77 
>@mik-dass has mentioned. It is required to limit the URL name to be less than 15, because it is limited by K8s

What part of k8s has limit of 15 characters? Kubernetes resource names are limited to 63 chars.




Current behavior doesn't make sense to me.

```
▶ odo url create --host localhost
 ✓  URL java-openliberty-9080 created for component: java-openliberty

▶ odo push

▶ odo url list
Found the following URLs for component java-openliberty
NAME                STATE      URL                                  PORT     SECURE     KIND
java-openlibert     Pushed     http://java-openlibert.localhost     9080     false      ingress

▶ oc get ing
NAME                               CLASS    HOSTS                       ADDRESS   PORTS   AGE
java-openlibert-java-openliberty   <none>   java-openlibert.localhost             80      2s


▶ cat .odo/env/env.yaml
ComponentSettings:
  Name: java-openliberty
  Project: default
  Url:
  - Name: java-openliberty-9080
    Host: localhost
    Kind: ingress
  AppName: app
  RunMode: run

▶ oc get ingress -o yaml | grep odo.openshift.io/url-name
      odo.openshift.io/url-name: java-openlibert
```

**Comment by kadel** [comment]
## What needs to change:
### Stop truncating name to 15 chars.
The only truncating that we can consider should be 63 characters limit. And that one shoudl be probably enforced by Devfile schema.

### Consistent naming
- Ingress/Route label `odo.openshift.io/url-name` needs to match  `Url.Name` in `env.yaml`.
- `odo url list` should take url names from `odo.openshift.io/url-name` label (if it is not already doing it)

### Fix odo url delete
`odo url delete` should take url name as an argument. The url name is what is displayed in `odo url list`,
When performing delete action it needs to use labels (`odo.openshift.io/url-name`, `app.kubernetes.io/instance`, `app.kubernetes.io/part-of`) to find the right resource for deletion.

**Comment by mik-dass** [comment]
https://github.com/devfile/api/issues/287 is closed now. We should pull the changes and remove the function `getValidURLName()`

**Comment by deboer-tim** [comment]
This URL defect may be the same underlying issue: #4218. After fixing please test that and close if it is fixed.

**Comment by mik-dass** [comment]
> This URL defect may be the same underlying issue: #4218. After fixing please test that and close if it is fixed.

Yes this defect is causing #4218 .

**Comment by mik-dass** [comment]
This requires https://github.com/openshift/odo/issues/4346 to be completed first.
