### ISSUE TITLE
CRC Getting Started - Command in step 4 of chapter 3.3.2 needs to be updated

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#4069]
/kind documentation

## What mistake did you find / what is missing in the documentation?
For https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.16/html/getting_started_guide/using-codeready-containers_gsg#deleting-the-virtual-machine_gsg , when executing the command in step 4 of 3.3.2 : 
`odo create nodejs --git https://github.com/openshift/nodejs-ex`
returns:
```
x
 ✗ flag --git, requires --s2i flag to be set, when deploying S2I (Source-to-Image) components.

```

Need to be updated to:
`odo create nodejs --s2i --git https://github.com/openshift/nodejs-ex`

## What is the relevance of it?
First time users can get frustrated by getting error messages when following steps in a getting started guide. This can push the possible new user of our product to abandon the intent to use it.

**Comment by sympatheticmoose** [comment]
Just a suggestion - but given s2i is no longer the default deployment method with odo 2.0.0, it would perhaps be better to update to `odo create nodejs --starter` and use the Node.js devfile. This would similarly remove the error message and promote the new deploy strategy.

**Comment by rnapoles-rh** [comment]
@sympatheticmoose I tried:

**Comment by sympatheticmoose** [comment]
@rnapoles-rh Glad to hear you're trying it out :) in the example I gave is using devfiles and you don't need the `--git` flag. Just do `odo create nodejs --starter` no additional arguments/flags are required. The [Node.js devfile](https://github.com/odo-devfiles/registry/blob/master/devfiles/nodejs/devfile.yaml) has a property called 'starterProjects' which points to an example Express app here - https://github.com/odo-devfiles/nodejs-ex.git. The `--starter` flag will pull down this starter project to your local workspace and create a new component with this as the source code.

`--git` and `--s2i` can be used if you want to create components using [s2i](https://github.com/openshift/source-to-image)

Hope this info helps

**Comment by boczkowska** [comment]
The CRC documentation has been updated, so this issue can be closed: https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.22/html-single/getting_started_guide/index#deploying-sample-application-with-odo_gsg
