### ISSUE TITLE
Refactor devfile parser code to produce a common devfile parser can work in all tools

### ISSUE THREAD

**Issue by elsony** [openshift/odo#4073]
/kind user-story

## User Story
As a tools developer, I want to use a common devfile library to read and write a devfile.

## Background
There are currently multiple instances of the parser implementation, e.g. the parser in odo repo and also the one in https://github.com/devfile/parser. This work will consolidate those implementations and create one single parser implementation and make it available to on https://github.com/devfile/parser.

- This work will be started from the parser code in the odo repo
- Restructure the code in odo repo to extract the generic parser library (refactor out anything that is odo specific)
- May include any extra functions that is currently available in the existing devfile/parser repo but not available in the odo repo
- Move the common library to the devfile/parser repo
- odo will switch to use the common library on the devfile parser repo and remove the corresponding code from the odo repo

## Acceptance Criteria 
- [ ] The common library parser should only contain support for the devfile 2.0 specification, any odo specific support will be move outside of the common library.
- [ ] Support both read and write of devfile

## Links 
- Related issue: This issue provides the ground work of the devfile libraryhttps://github.com/devfile/api/issues/144

Detailed design notes: https://docs.google.com/document/d/1ffLi37fM7LAjRK5SXAw-yVNwr9GchFYy_e_5VD-FOZc/

/kind user-story
/area devfile

**Comment by maysunfaisal** [comment]
@girishramnani any concerns with the issue description, since there is a triage needs information tag? The issue OP outlines what is required to be done and the detailed work has been outlined in the attached document. Do we want to copy paste it out here?

**Comment by maysunfaisal** [comment]
@yangcao77  validate pkg has been refactored and I guess there is nothing that needs to be refactored in the parser pkg. So we should be able to just copy paste any of the pkgs to devfile/parser or devfile/api..

I think this can be closed now?

**Comment by yangcao77** [comment]
Yes. I think we can close this one. We can have separate issues for 
```

- Move the common library to the devfile/parser repo

- odo will switch to use the common library on the devfile parser repo and remove the corresponding code from the odo repo

```
