### ISSUE TITLE
feature: odo push --s2i

### ISSUE THREAD

**Issue by dev-gaur** [openshift/odo#4074]
IMHO, the user-story of `odo utils convert-to-devfile` looks unfinished to me.

If the `convert-to-devfile` command creates an equivalent of an existing s2i component in the working directory, without deleting the s2i component, we have 2 co-existing components deployed for our app, the s2i one and the new devfile one which becomes the default.

Now, the user might want to push their code to the s2i type component as well. The current way to achieve that is to delete the devfile component and then the s2i component becomes the default component again and then a simple `odo push`.
Or we just give the user the ability to do `odo push --s2i`.

Or just delete the s2i component, when we convert to the devfile component. Simple that way. Lesser complications in user experience.

**Comment by dev-gaur** [comment]
Additionally, not deleting the s2i component when doing `convert-to-devfile` also goes on to complicating the UX for odo delete.

![image](https://user-images.githubusercontent.com/7551036/94983225-51100080-055e-11eb-93af-6ef381662af8.png)

you have to run `odo delete` twice. I know --s2i flag is there for `odo delete` as well. But still.

One suggestion : `odo delete` should warn the user that the s2i component is still not deleted, they need to run `odo delete` one more time if they want to delete that as well.

**Comment by adisky** [comment]
> Now, the user might want to push their code to the s2i type component as well

@dev-gaur `odo utils convert-to-devfile` not meant to persist both the components at the same time, as soon as the user finished deploying devfile component we want to delete the s2i component. It is temporary state to have both components together just to assure the s2i components does not gets deleted before it is successfully migrated to devfile.

**Comment by dev-gaur** [comment]
Thanks for the explanation. Just for the sake of clarity, we should inform the user saying that the devfile type component will the one in focus for all future commands. And the user can do `odo delete --s2i` to get rid of the out of focus s2i component.
