### ISSUE TITLE
fix windows installation instructions

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4077]
Install instructions for windows are confusing
https://odo.dev/docs/installing-odo/

The current documentation mentions `GOPATH/bin` and `C:\go-bin` users not familiar with Go might not know that this is.
The documentation needs to be more generic so even users without any Go knowledge can understand it.

/kind documentation
/priority high
/area windows

**Comment by deboer-tim** [comment]
FWIW, I assumed it must have been a typo and meant 'path', Windows install seemed to work fine this way. I have a Windows box, can help verify the changes.

**Comment by girishramnani** [comment]
seems to be duplicate of https://github.com/openshift/odo/issues/4062 @kadel
