### ISSUE TITLE
No starter project in "java-maven" component's devfile

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4082]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
`$ odo create java-maven --starter`

## Actual behavior
```
odo create java-maven --starter
Validation
 ✓  Checking devfile existence [10921ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [13215ns]
 ✓  Validating devfile component [58186ns]
 ✗  no starter project found in devfile.
```

## Expected behavior
As a user, I would like to be able use some starter project in the devfile just like I can do so for other component types

## Any logs, error output, etc?
```
$ odo registry list
NAME                       URL                                                                SECURE
DefaultDevfileRegistry     https://raw.githubusercontent.com/odo-devfiles/registry/master     No
```

/area devfile
/area component

**Comment by mik-dass** [comment]
Starter project for java-maven has been added recently https://github.com/odo-devfiles/registry/blob/51d1360a97f094a9e0b77b8976ccd25bbf571274/devfiles/java-maven/devfile.yaml#L6
