### ISSUE TITLE
Spring Boot example reports "running on IBM Cloud"

### ISSUE THREAD

**Issue by burrsutter** [openshift/odo#4095]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

From this example/doc
https://odo.dev/docs/deploying-a-devfile-using-odo/

and specifically in 
git clone https://github.com/odo-devfiles/springboot-ex

## Actual behavior
Seen in this screenshot
https://www.screencast.com/t/3ZPzjw1e1c

## Expected behavior
should be something related to "odo", not IBM cloud

**Comment by dharmit** [comment]
@kadel you mentioned that there's a PR to fix this. Can you please link it?

**Comment by kadel** [comment]
/assign
PR at https://github.com/odo-devfiles/springboot-ex/pull/2

**Comment by dharmit** [comment]
The PR's merged. Closing this.

@burrsutter, please re-open the issue if there's anything amiss.

/close
