### ISSUE TITLE
odo url delete should work without arguments

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#4106]
/kind feature

## Which functionality do you think we should add?

If there is only one url, `odo url delete` should delete it. I'd be ok if it prompted to confirm or required a -f.
If there is more than one url, it would also be a quicker way to get rid of them all.

## Why is this needed?

I find it annoying having to use `odo url list` followed by 'odo url delete some-url-name', especially when I know there is only 1 url.

**Comment by girishramnani** [comment]
Closing this issue as a user story https://github.com/openshift/odo/issues/4147 for this feature request has been recorded
