### ISSUE TITLE
Nit: odo url list shows :// before it is pushed

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#4109]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

Server: https://api.crc.testing:6443
Kubernetes: v1.18.3+2cf11e2

## How did you run odo exactly?
I created a url using 'odo url create' and noticed the URL listed is a bit odd until you've pushed it.

## Actual behavior
`deboer-mac:node2 deboer$ odo url create --port 3000
 ✓  URL node2-3000 created for component: node2

To apply the URL configuration changes, please use `odo push`
deboer-mac:node2 deboer$ odo url list
Found the following URLs for component node2
NAME           STATE          URL     PORT     SECURE     KIND
node2-3000     Not Pushed     ://     3000     false      route
There are local changes. Please run 'odo push'.
deboer-mac:node2 deboer$ odo push
...
Applying URL changes
 ✓  URL node2-3000: http://node2-3000-node2-timproj.apps-crc.testing/ created
...
 ✓  Changes successfully pushed to component
deboer-mac:node2 deboer$ odo url list
Found the following URLs for component node2
NAME           STATE      URL                                                  PORT     SECURE     KIND
node2-3000     Pushed     http://node2-3000-node2-timproj.apps-crc.testing     3000     false      route`

## Expected behavior
The url value of '://' above is confusing. We should probably leave the URL blank until later.

**Comment by girishramnani** [comment]
I can look into this
