### ISSUE TITLE
Refactor odo specific packages like url, storage etc

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#4115]
/kind code-refactoring

## Acceptance Criteria 

`odo` specific packages like storage, url etc should have interface so that it becomes easier to use and mock them.

The packages we are scoping for refactoring are 
- [ ] Application
- [ ] Catalog
- [ ] Component
- [ ] Project
- [ ] Service (#4242)
- [x] Storage (@mik-dass)
- [x] URL (@mik-dass #4185)

**Comment by girishramnani** [comment]
I would suggest breaking this into smaller tasks if we want to include all packages

**Comment by mik-dass** [comment]
> I would suggest breaking this into smaller tasks if we want to include all packages

Yes, we would break this into smaller tasks once a framework for the packages is designed.

**Comment by mik-dass** [comment]
I have added the doc regarding the refactoring here https://docs.google.com/document/d/1miLfw0m0nWGmoBsYr9jkHp0mFSSXW84eLv_dSRC8Sm4/edit?usp=sharing. @metacosm @girishramnani @kadel @adisky @dharmit Please have a look and share your feedback.

**Comment by girishramnani** [comment]
- [ ] Application
- [ ] Catalog
- [ ] Component
- [ ] Project
- [ ] Service
- [ ] Storage (@mik-dass)
- [ ] URL (@adisky)

**Comment by dharmit** [comment]
@mik-dass you've done a great job of separating the code into different files especially at `occlient` and `kclient` level. I think you had something for `url` package that was more interface-y. Are you planning to open a PR for it?

@girishramnani you mentioned that you were going to work on the `config` part of `context` package. However, I don't think @adisky will be working further on `context` package refactor. Can you please share how you plan to take this further?

**Comment by dharmit** [comment]
Either this has to be done on a high priority or completely dropped. We can't keep dragging refactoring task into sprints if it's not making sense to anyone to work upon. Can't keep just @mik-dass working on it all the time.

@kadel @girishramnani @adisky 

/priority high

**Comment by mik-dass** [comment]
> @mik-dass you've done a great job of separating the code into different files especially at `occlient` and `kclient` level. I think you had something for `url` package that was more interface-y. Are you planning to open a PR for it?

The PR https://github.com/openshift/odo/pull/4185 was an concept. I clean it up and it will be ready for review.

**Comment by dharmit** [comment]
Closing this since we already refactored url and storage packages and we can reference that for further refactoring, if any.

/close
