### ISSUE TITLE
odo push (and watch) should offer a "follow" (log) command

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#4123]
/kind feature

## Which functionality do you think we should add?

The `odo push` command offers a `--show-log` option but it still returns at the same point within the push sequence.    This usually happens after the 'build' command finishes, after the 'run' command is issued (using the 'java-openliberty' component type at least).

It would be nice to have an `odo push -f` to combine `odo push` (optionally with --show-log) and `odo log -f`.   

For the java-openliberty component type, the completion of build isn't too interesting or useful, and it's necessary to watch the log to determine when the component is ready to use.  

## Why is this needed?

(Because you have to do two commands:   odo push;  odo log -f   to achieve this now).

**Comment by scottkurz** [comment]
Also `odo watch --show-log` should at least have an option to follow the 'run' command execution

**Comment by dharmit** [comment]
@scottkurz seems like you wanted to reopn this as well.

/reopen
