### ISSUE TITLE
`odo url describe` reported as not supported subcommand in v2.0.0

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4126]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?

Was working fine in odo 1.2.6 

```
Available Commands:
  create      Create a URL for a component
  delete      Delete a URL
  describe    Describe a URL
  list        List URLs
```
Now in latest release it is not.

`odo url describe`

## Actual behavior

` Subcommand not found, use one of the available commands: create, delete, list`

## Expected behavior

Print url's description.

## Any logs, error output, etc?

N/A

**Comment by girishramnani** [comment]
@dgolovin The `odo url describe` was removed because the current `odo url list` implementation provides equivalent information. Sorry for not effectively communicating this.

Current output for `odo url list`

```
(base) girish@MacBook-Pro asdasdf % odo url list
Found the following URLs for component nodejs
NAME          STATE          URL     PORT     SECURE     KIND
http-3000     Not Pushed             3000     false      route
There are local changes. Please run 'odo push'.
(base) girish@MacBook-Pro asdasdf % odo url list -o json
{
        "kind": "List",
        "apiVersion": "odo.dev/v1alpha1",
        "metadata": {},
        "items": [
                {
                        "kind": "url",
                        "apiVersion": "odo.dev/v1alpha1",
                        "metadata": {
                                "name": "http-3000",
                                "creationTimestamp": null
                        },
                        "spec": {
                                "port": 3000,
                                "secure": false,
                                "kind": "route"
                        },
                        "status": {
                                "state": "Not Pushed"
                        }
                }
        ]
}
```

We assumed that finding the url needed from the whole list would be possible on adapter side by just filtering over the list and matching the url name.
If there is any information missing in the current list implementation do share with us.

**Comment by girishramnani** [comment]
closing this as we have a better way to describe the url now
