### ISSUE TITLE
Provide the way to get list of starter projects with id/display name/description for specific component type

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4129]
/kind feature

## Which functionality do you think we should add?

`odo create` provides a --starter option to create component based on simple working project. --starter option also allows to use project name listed inside devfiles' starterProjects node. Considering that usually remote registry is going to be used, there is no easy way to get list of starter projects form devfile for specific component type. The only way right now is to go to remote registry's repository and look inside devfile.yaml.

There should be ether odo command to list starter projects for specific component type as a table consists of ID, Name, Display Name, Description or information about starter projects should be part of `odo catalog list components' output.

## Why is this needed?

* To speed up creating and deploying first application on Kubernetes or OpenShift
* To improve odo integration with IDEs and allow to create IDEs specific UI to create starter projects

**Comment by adisky** [comment]
> The only way right now is to go to remote registry's repository and look inside devfile.yaml.
 
starter projects of a component is listed in `odo catalog describe component <component-name>`
```
$ odo catalog describe component java-quarkus
Devfile Component(s):

* Registry: DefaultDevfileRegistry

Starter Projects:
---
name: quarkus-ex
git:
  remotes:
    origin: https://github.com/odo-devfiles/quarkus-ex
```

Though `odo catalog describe component <component-name> -o json ` contains whole devfile,  the output could be improved.

**Comment by dgolovin** [comment]
@adisky Thank you for info :+1: That is what needed. Could it have `description` property with sort basic info about the project?

**Comment by girishramnani** [comment]
We currently dont have any `description` for starter projects @dgolovin

**Comment by adisky** [comment]
@dgolovin It prints the whole starter projects struct from devfile, https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml#L6, Its just that we do not have starter project description in odo devfile registry. We need to update the devfiles there

**Comment by dgolovin** [comment]
@girishramnani @adisky Sounds like devfile does have description attribute for starter project. It just not used. That attribute only makes sense when there are more than one starter project though. 

Thanks! Closing the issue.
