### ISSUE TITLE
We need  clarity around installing and using Operators with odo both on OCP & k8s environments

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4130]
## What mistake did you find / what is missing in the documentation?
odo has the feature to start services from Operators and link Devfile components to it. But installing Operators in itself is not a task that can be done by odo. We need to document that it's not in the scope of odo and point users to relevant documentation for OCP and k8s about how to install Operators on their cluster.

## What is the relevance of it?
Lately we're seeing confusion around Operators wherein certain users are expecting to use odo to install Operators. 

/kind documentation
/area service-operators

**Comment by boczkowska** [comment]
We kind of have this info in the prerequisites here https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.html
`Note that the configuration of the cluster determines the services available to you. To access the Operator services, a cluster administrator must install the respective Operator on the cluster first. To learn more, see Adding Operators to the cluster.`

@dharmit maybe adding a big note will work better for visibility - https://github.com/openshift/openshift-docs/pull/27668 ?

**Comment by dharmit** [comment]
@boczkowska that looks neat! I had, however, opened this issue more from the perspective of making this clear on odo.dev website. We're not doing a good job of explaining this there, which I must fix. :)

**Comment by boczkowska** [comment]
@dharmit let's just copy what we have in downstream :D

**Comment by dharmit** [comment]
> @dharmit let's just copy what we have in downstream :D

While I would love it if that was going to suffice, I'm afraid that on odo.dev we need to provide more info to users to work with Operators. But I think that the warning you've added in your PR is a good thing and my PR #4274 could make use of it.
