### ISSUE TITLE
xUnit/jUnit test report generation

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4137]
/kind user-story

## User Story
As a QE I want to get xUnit/jUnit result file for each and every test execution.

## Acceptance Criteria 
- [x] Tests execution should generate xUnit/jUnit result file, so that we can use to it to compare test results easily.
- [x] No manual effort should be required for getting the test execution reports.

## Links 
- Feature Request: https://projects.engineering.redhat.com/browse/INTEROP-2704
- Related issue: Verify the suggested solution https://github.com/onsi/ginkgo/issues/628#issuecomment-680220138 

Details on the results : https://docs.engineering.redhat.com/display/PIT/Xunit+File+Details

/kind user-story

**Comment by anandrkskd** [comment]
> RE: https://github.com/onsi/ginkgo/issues/628#issuecomment-680220138

I verified expected result for parallel node execution, For getting the reports against multi-test node we have to follow the above ginkgo functionality. Gingko reads the parallel node config and generates reports according to the number of nodes.

```
junitReporter := reporters.NewJUnitReporter(fmt.Sprintf("junit_%d.xml", config.GinkgoConfig.ParallelNode))
```

Two Junit reports are generated when I roughly made the changes and executed it against a single test file, even it works for the whole integration test suit too. But I am facing issue while I am redirecting the same report file to a destination directory _reports_. make target gets stuck after end of execution. I will be fixing that as part of this PR. 

Thanks @amitkrout for your tips and extended support

**Comment by anandrkskd** [comment]
AFAIK the same code skeleton was working earlier for previous version of gingko though it was giving wrong junit result but at least there was no issue with path redirection.
