### ISSUE TITLE
odo should use 'hotReloadCapable' to determine if build command is run on subsequent push

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#4141]
/kind bug

## What versions of software are you using?

**Operating System:**  Win10, Linux

**Output of `odo version`:**  odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?

1. odo create java-openliberty --starter
2. odo push
3. ... make edit..
4. odo push

## Actual behavior

Within the [java-openliberty](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-openliberty/devfile.yaml) devfile, the 'build' command will run both times, but the 'run' command only runs the first time, since we use: `hotReloadCapable: true`.

As you can see from the way the build command lays down a marker file to no-op the second time, this implementation would work more naturally if the `hotReloadCapable: true` setting would prevent the 'build' command running after the first time.

**Comment by kadel** [comment]
`hotRealodCapable` field was intended mainly for `run` commands. 


The behavior that you are describing should be achieved with `postStart` event
remove
```
      group:
        kind: build 
        isDefault: true
```
from build command and add
```
events:
  postStart:
    - build
```
to the devfile

**Comment by scottkurz** [comment]
I think we steered away from postStart because of these:
https://github.com/openshift/odo/issues/4017
https://github.com/openshift/odo/issues/4030
so if they were addressed maybe that'd be better.
