### ISSUE TITLE
Refactor all the cli packages

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4145]
Currently the cli packages break the original odo architecture
- by using the `Kclient` directly
- checking information about the cluster like if `routes` are supported

Also the cli packages contain alot of logic which should be moved to lower layers of the code. Ideally cli packages should only be responsible for collecting information from user, showing them information and building structs that the lower layers need.

**Comment by kadel** [comment]
Also as noted at https://github.com/openshift/odo/issues/4057 all cli commands should  follow Complete/Validate/Run pattern
