### ISSUE TITLE
Add e2e scenario for java-maven devfile debug command 

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#4162]
/kind flake

## Actual behavior
As an odo user, I want to create a java-maven project from a devfile starter project, then be able to use the debugger to debug the application running in the cluster.

This is continuation of issue #3377 , there is a dependency on issue  devfile/api#115 as starterProject is not available for java-maven.

## Expected behavior
starterProject should be included in the java-maven devfile

## Acceptance Criteria 
- [ ] Update e2e scenario to add java-maven coverage
- [ ] Run test e2e scenario (make test-e2e-devfile) to ensure it passes

**Comment by prietyc123** [comment]
@rnapoles-rh It seems now we have starter project for java maven as well https://github.com/odo-devfiles/registry/blob/master/devfiles/java-maven/devfile.yaml
