### ISSUE TITLE
"odo create" needs "--s2i" flag in the multi-component example in the documentation

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4184]
/kind documentation
/kind bug

## What mistake did you find / what is missing in the documentation?
In the [multi-component example](https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/creating-a-multicomponent-application-with-odo.html#deploying-the-back-end-component_creating-a-multicomponent-application-with-odo), we need to mention the need for `--s2i` flag in `odo create` command:
```sh
$ odo create openjdk18 backend --binary target/wildwest-1.0.jar
 ✗  flag --binary, requires --s2i flag to be set, when deploying S2I (Source-to-Image) components.
```

Even for the `odo link` to work [as mentioned in that documentation](https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.html#linking-both-components_creating-a-multicomponent-application-with-odo), we need to make sure that both the components in that example are created using `--s2i` flag.

## What is the relevance of it?
Invalid command for odo v2.

**Comment by dharmit** [comment]
@Preeticp @boczkowska I've got a dumb question. Can you folks please suggest which repo the change needs to be made to fix this documentation error? :slightly_smiling_face:

**Comment by Preeticp** [comment]
Hi Dharmit, We work in the OpenShift-docs GH repository: https://github.com/openshift/openshift-docs

This is the assembly for the multi-component work  flow: https://github.com/openshift/openshift-docs/blob/3fefe7cdd928231790a005763000c5baff84fdc0/cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.adoc

The modules/actual files you might be looking for are these: 
https://github.com/openshift/openshift-docs/blob/master/modules/developer-cli-odo-deploying-the-back-end-component.adoc
and 
https://github.com/openshift/openshift-docs/blob/master/modules/developer-cli-odo-linking-both-components.adoc
Do let us know if you need any more help.

**Comment by dharmit** [comment]
So the thing is that linking a component with another component is something that works only for s2i based components. It doesn't work with devfile components. I'm a bit confused by looking at all those links (I mean their contents) as to where the change should really go in.

I'll spin up a fresh OCP cluster, try to follow ths [multi-component guide](https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.html), and come back to you with info about where we need to make what changes. Sounds OK?

**Comment by boczkowska** [comment]
@dharmit I've searched through the docs, I only found two instances where this is applicable, PTAL https://github.com/openshift/openshift-docs/pull/27250 I couldn't test it though as clusterbot kept giving up on me today -_- 

I'll merge the fixes downstream first and then create a PR for upstream docs (w/ Charlie's script).

**Comment by boczkowska** [comment]
This has been fixed.
