### ISSUE TITLE
Odo should use apply command for preStart(and postStop when its implemented)

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#4187]
There is a semantic difference between an exec and apply command - exec commands are to be executed only when a container is up and running and apply commands are applied when there is no running container.

However, odo only has exec and composite commands in its scope and preStart utilizes an exec command. But according to the schema definition and interpretation this is not right. See issue https://github.com/devfile/api/issues/204 for discussion.

Currently no odo devfiles have a preStart, so it would be good to update the implementation to use apply commands before a devfile starts using it.

For more information on which events use apply/exec, pls read devfile validation doc - https://github.com/devfile/api/blob/master/pkg/validation/validation-rule.md. Also note the condition for composite commands when it comes to events!

cc: @kadel

**Comment by maysunfaisal** [comment]
@kadel @dharmit FYI, this issue will be need to be addressed when odo switches validation to devfile library and api as per https://github.com/openshift/odo/issues/4361

There is currently an open PR to  consolidate validations in https://github.com/devfile/api/pull/301

**Comment by kadel** [comment]
odo currently doesn't support `apply` commands. This means that do can't currently support `preStart` event.
A temporary solution until we have `apply` support in odo is not to support `preStart` event. So odo will error out in case of devfile with `preStart`
