### ISSUE TITLE
Show components created by other tools in odo

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4192]
## Goal
Developers using odo today are only able to see components & applications which if their associated source code is local.  This means that users starting their projects in the developer console and moving to odo, will not see anything created in the Console ( or any other Red Hat tool ) .

## Acceptance Criteria
- Developers should be able to view all components and applications in a namespace, regardless of which Red Hat tools is used to create them, assuming they follow Gorkem's lables
- Developers can only modify components & applications if their associated source code (and devfile) is local
- Developers can only delete components & applications created by odo

## User story for the Epic
https://github.com/openshift/odo/issues/4192

## JIRA Epic Tracking
[ODO-59](https://issues.redhat.com/browse/ODO-59)

**Comment by dgolovin** [comment]
Related issue #4183.

**Comment by girishramnani** [comment]
The most initial step would be to show external deployments in `odo list`, we also need to understand what kind of annotations/ labels those deployments would have that we can use - deployments done using webconsole could have some information in their labels about the kind of component that deployment is?

**Comment by serenamarie125** [comment]
@kadel Are the goal and acceptance criteria defined enough to provide an estimate?  If so, could we get one added please?

**Comment by dharmit** [comment]
Labels to be referred to for different tools - https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

**Comment by valaparthvi** [comment]
I would like to work on this one. I can research and hopefully get somewhere with the implementation in the upcoming sprint.
/assign valaparthvi

**Comment by dharmit** [comment]
> Labels to be referred to for different tools - https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

If for any reason this URL fails to redirect, the repo now lives under - https://github.com/redhat-developer/app-labels.

**Comment by dharmit** [comment]
Does this look related - https://github.com/openshift/odo/issues/4544?

@kadel @serenamarie125

**Comment by kadel** [comment]
> Does this look related - #4544?

 #4544 is about the other direction - WebConsole showing things created by odo.


This current issue #4192 is about odo showing things created in WebConsole. 




Most of the things for  #4544 are already there. One things that might be left is to make sure that every odo component has label or annotation that includes source repo url

**Comment by valaparthvi** [comment]
@kadel What labels should I take into account? Only the REC ones or all of them?

**Comment by kadel** [comment]
> @kadel What labels should I take into account? Only the REC ones or all of them?

all that are set on the resource 

You should check how the application created by the developer console is labeled 


I was imagining output along those lines

```
▶ odo list
odo Devfile Components: 
APP     NAME                       PROJECT         TYPE                       STATE
        java-quarkus-remotedev     tkral-test2     java-quarkus-remotedev     Pushed


Other components running on the cluster:
APP        NAME         PROJECT           TYPE 
myapp     frontend     tkral-test2        nodejs    
otherapp  something    tkral-test2        dotnet
```

The "Other components running on the cluster:" is basically list of all Deployments  in a given namespace.
value for `APP` column is from `app.kubernetes.io/part-of`
`NAME` - `app.kubernetes.io/instance`
`TYPE` - `app.kubernetes.io/name`

**Comment by valaparthvi** [comment]
>I was imagining output along those lines

Yup, I was planning on going with that instead of the one I proposed earlier, this one just seems simpler, easier, and more readable.

Thinking Out Loud - 
1. The output you suggested covers components from all the apps.
2. When you say Deployments, do you mean DeploymentConfigs as well?

**Comment by kadel** [comment]
> * The output you suggested covers components from all the apps.

That was a mistake.
It should work as it does with odo components. 
`odo list` - list components form current project and application (based on the context directory)
`odo list --all-apps`  - list components from all apps, from the current project
`odo list --all-apps --project myproject` - list components form all apps from `myproject` namespace 
`odo list --project myproject` - list components from current application from `myproject` namespace
` odo list --project myproject --app myapp` - list component from `myproject` namespace that are in `myapp` app.
`odo list --app myapp` - list component from the current project that are in `myapp` app.




> 2\. When you say Deployments, do you mean DeploymentConfigs as well?

I forgot about DeploymentConfigs, yes, it should list DCs as well.

**Comment by dharmit** [comment]
@valaparthvi is this epic fully addressed by #4742 or is anything pending?

**Comment by valaparthvi** [comment]
I would say everything has been covered.

**Comment by dharmit** [comment]
> I would say everything has been covered.

OK. Thank you.

/close
