### ISSUE TITLE
Cleanup odo cluster configure scripts

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4199]
Cleanup odo configure cluster scripts to make them more manageable.

- [x] Move auth configuration into a lib (and update scripts accordingly)
- [x] Relocate setup-operators script and update scripts accordingly
- [x] Move Kubeadmin login to a seperate script
- [ ] ~~Move platform-specific stuff into its on scripts~~ (done as much as I could, moving to its own task)
- [x] Merge configure-installer scripts into single script

**Comment by mohammedzee1000** [comment]
The above PR is the first phase of the cleanup

**Comment by dharmit** [comment]
@mohammedzee1000 can you please update the issue with its current status? The PR associated with it has already gone in. Have all the items mentioned in the issue description been taken care of?

**Comment by mohammedzee1000** [comment]
I am working on the 2nd phase of this issue. The 3rd part, which is platform-specific stuff, I am expecting the alt arch teams to handle it.

**Comment by mohammedzee1000** [comment]
https://github.com/openshift/odo/pull/4292

**Comment by mohammedzee1000** [comment]
Closing as what needs to be done from our side is done
/close
