### ISSUE TITLE
describe and create commands test for existing component in context folder is inconsistent

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4210]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 2.0.0

## How did you run odo exactly?

Current folder has .odo/env left after previous component and no devfile.yaml

```
$ odo describe
✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

## Actual behavior

```
$ odo create nodejs
✗  this directory already contains a component
```

## Expected behavior

```odo create nodejs```  creates component

## Any logs, error output, etc?

N/A

**Comment by girishramnani** [comment]
I think as there is no devfile present - the user cannot move forward in anyway, one solution I feel is allowing the user to override the `env/env.yaml` when user does `odo create nodejs`.

**Comment by kadel** [comment]
> I think as there is no devfile present - the user cannot move forward in anyway, one solution I feel is allowing the user to override the `env/env.yaml` when user does `odo create nodejs`.

This should work. 

It would be interesting to know how this situation can happen.


> Current folder has .odo/env left after previous component and no devfile.yaml

@dgolovin, how did you get it into this state? There should be no way to create this situation with odo.

**Comment by dgolovin** [comment]
@kadel I probably did it outside of odo, by deleting devfile.yaml form file browser, but did not see `.odo` folder because it was hidden. Behaviour should be ether overwriting .odo/env/env.yaml in case of something missing to detect component or recognizing component with invalid configuration, but it should be consistent throughout all commands.

**Comment by girishramnani** [comment]
Understood moving forward on the approach I have mentioned above
