### ISSUE TITLE
openshift-bot stuck in endless loop if travis fails

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4216]
If travis test fail, the openshift-bot ends up spamming PR with `/retest`.

You can see it in many PRs, one example is here https://github.com/openshift/odo/pull/4207#issuecomment-726345471

It looks like that openshift-bot can correctly detect that the test failed, but the `/retest` command doesn't trigger Travis tests so it ends up in this infinite commenting looop. 

/area testing

**Comment by prietyc123** [comment]
@kadel AFAIK its quite obvious that `/retest` bot trigger will go in endless loop if any of the job fails. It has no knowledge of prow or non-prow jobs unfortunately, rather it just reacts on failures. I think this is how `openshift-bot` has been designed. This seems more like a bug to me.

**Comment by kadel** [comment]
> This seems more like a bug to me.

That is why I opened this so we can fix it.
