### ISSUE TITLE
odo 2.0.1 crashes

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#4217]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS Catalina.

**Output of `odo version`:**
`Killed: 9`
(It's 2.0.1)

## How did you run odo exactly?
Note the version numbers in the url:
```
deboer$ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/v2.0.0/odo-darwin-amd64 -o /usr/local/bin/odo
   ...
deboer$ chmod +x /usr/local/bin/odo
deboer$ odo
  odo is a CLI tool for ...
deboer$ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/v2.0.1/odo-darwin-amd64 -o /usr/local/bin/odo
   ...
deboer$ chmod +x /usr/local/bin/odo
deboer$ odo
  Killed: 9
deboer$ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/v2.0.0/odo-darwin-amd64 -o /usr/local/bin/odo
   ...
deboer$ odo
  odo is a CLI tool for ...
```

## Actual behavior
I've tried this multiple times - any 2.0.1 command fails the same way; going back to 2.0.0 works fine.

## Expected behavior
odo 2.0.1 working just like 2.0.0.

## Any logs, error output, etc?
Just `Killed: 9`.

**Comment by elsony** [comment]
I just tried 2.0.1 and I see the same problem. However, in my case, the problem looks like it only happens if I run it under /usr/local/bin. If I copy that odo to some other directory and run ./odo, odo ran fine.
```
eyuentp2:v2.0.1 eyuen$ odo version
Killed: 9
eyuentp2:v2.0.1 eyuen$ cp /usr/local/bin/odo .
eyuentp2:v2.0.1 eyuen$ ./odo version
odo v2.0.1 (a9fff7da4)
eyuentp2:v2.0.1 eyuen$ 
```

**Comment by deboer-tim** [comment]
Ditto, after Elson pointed this out I confirmed I can also run odo 2.0.1 in another folder, just not in the default (/usr/local/bin) folder.

**Comment by kadel** [comment]
This is weird. 
I've tried the same on my MacOS 10.15.7 and it worked in `/usr/local/bin` as well as in any other directory.
I don't think that the fact that I have a different point version than Elson plays any role here. 

My theory is that there might be some kind of MacOS security restriction. It is quite possible that I have disabled something in past on my system, and now I don't remember it 😇 

@prietyc123, as far I know you are also running on MacOS can you try this:?
```
curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/v2.0.1/odo-darwin-amd64 -o /usr/local/bin/odo
chmod +x /usr/local/bin/odo
which odo
odo
```

**Comment by deboer-tim** [comment]
FWIW, I am on 10.15.6.

I couldn't find any security warning or any way to tell why it's crashing, so I tried looking at this the other way instead: what changed between 2.0.0 and 2.0.1 that's always executed (i.e. no specific command), but there are 165 changed files and with less knowledge of odo I couldn't make any headway. It could also be something changed in the build process/signing.

**Comment by kadel** [comment]
This is not odo crashing. Something on your system is killing odo. There could be something wrong with odo that could make the system to kill it (like leaking memory). First, we should find why it is getting killed.
The problem is that I still can't reproduce it :-(

@mohammedzee1000 did we changed something in the signing process between 2.0.0 and 2.0.1?

@deboer-tim Just out of curiosity, can you please try to install odo using [odo homebrew tap](https://github.com/kadel/homebrew-odo)? I've recently updated it to 2.0.1

**Comment by deboer-tim** [comment]
Sorry, bad choice of words, it is clearly getting Killed :).

brew install was incredibly slow and then I had to use `brew link --overwrite odo` b/c it wouldn't overwrite the previous 2.0.0 install, but doing it this way works fine. I now have `odo v2.0.1 (a9fff7d)` installed and running w/o getting killed.

**Comment by kadel** [comment]
> brew install was incredibly slow and then I had to use `brew link --overwrite odo` b/c it wouldn't overwrite the previous 2.0.0 install, but doing it this way works fine. I now have `odo v2.0.1 (a9fff7d)` installed and running w/o getting killed.

The brew tap is using exactly the same code as the official binary, only difference is that it builds in on the local system.
It really looks like there is something weird going on with the build on mirror.openshift.com

Got my hands on an old laptop with old MacOS 10.14.1 (Mojave).
I'm able to execute odo 2.0.1 in `/usr/local/bin`, but interestingly it takes looooooog time to execute `odo`. It hangs up for 2min 30seconds before I can see the output. It is always exactly 2:30.

**Comment by deboer-tim** [comment]
/remove-lifecycle stale

Happened again when I try to go to 2.0.4.

**Comment by dharmit** [comment]
/reopen

Reopening because we didn't actually do anything to address this, nor did we check with OP if the problem persists with 2.2.4.

@deboer-tim do you still see this issue with 2.2.4?
@kadel @prietyc123 you're the only ones on Mac that I know of. Can you PTAL if this is still a problem?
