### ISSUE TITLE
odo service list fails with one service 

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#4221]
/kind bug

When odo encounters a problem with one of the operators it fails the listing for all services. For instance in this case it fails to get services with tekton and fails the listing of services for all operators although the rest is fine.

## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:**
❯ odo version
odo v2.0.1 (a9fff7da4)

## How did you run odo exactly?
odo service list 

## Actual behavior
 ✗  the server could not find the requested resource

## Expected behavior
list of available services especially operators. 

## Any logs, error output, etc?
```
I1115 13:42:12.398461    9288 service.go:314] Getting services started from operator: openshift-pipelines-operator.v1.0.1
I1115 13:42:12.398478    9288 service.go:454] Getting instances of: config.operator.tekton.dev
I1115 13:42:12.398548    9288 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer -nUI" 'https://.../apis/operator.tekton.dev/v1alpha1/namespaces/gercan-stage/config'
I1115 13:42:12.401809    9288 util.go:764] Cached response used.
I1115 13:42:12.430347    9288 round_trippers.go:443] GET https://api.member.crt-stage.com:6443/apis/operator.tekton.dev/v1alpha1/namespaces/gercan-stage/config 404 Not Found in 31 milliseconds
I1115 13:42:12.430366    9288 round_trippers.go:449] Response Headers:
I1115 13:42:12.430369    9288 round_trippers.go:452]     X-Content-Type-Options: nosniff
I1115 13:42:12.430373    9288 round_trippers.go:452]     X-Kubernetes-Pf-Flowschema-Uid: 7c172f0f-
I1115 13:42:12.430376    9288 round_trippers.go:452]     X-Kubernetes-Pf-Prioritylevel-Uid: e3dbd267
I1115 13:42:12.430379    9288 round_trippers.go:452]     Content-Length: 19
I1115 13:42:12.430382    9288 round_trippers.go:452]     Date: Sun, 15 Nov 2020 18:42:12 GMT
I1115 13:42:12.430385    9288 round_trippers.go:452]     Audit-Id: f030c88a
I1115 13:42:12.430388    9288 round_trippers.go:452]     Cache-Control: no-cache, private
I1115 13:42:12.430392    9288 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
```

**Comment by dharmit** [comment]
@gorkem We'll need more info here to be able to debug/fix the issue you've reported. 

1. Which Operator is this exactly? Is it "Red Hat OpenShift Pipelines Operator"? On my CRC box, I see two options when I search for "pipelines" in the OperatorHub interface:
    1. Red Hat OpenShift Pipelines Operator
    1. GitOps Service
1. How did you start the Operator backed service? Can you share the command you used to start the service?
1. I'm seeing the following error message in the logs you provided:
    ```
    GET https://api.member.crt-stage.com:6443/apis/operator.tekton.dev/v1alpha1/namespaces/gercan-stage/config 404 Not Found in 31 milliseconds
    ```
    Can you confirm that you created the service in the same namespace as the one where you're trying to execute `odo service list`?

**Comment by gorkem** [comment]
I do not think the operator matters here. This is probably an upgrade issue with Tekton operator. I will follow that with Tekton seperately. However the problem of one operator should not affect the listing of all operators in odo. Basically I am asking if there is a way to isolate.

**Comment by dharmit** [comment]
> However the problem of one operator should not affect the listing of all operators in odo. Basically I am asking if there is a way to isolate.

No, there's no way to do this currently. The `odo service list` command itself would break in such a scenario. I see how this could become a problem in the future.

**Comment by dharmit** [comment]
Moving this to Sprint 194 since I couldn't manage to fix it in this sprint. :(
