### ISSUE TITLE
Create a Test Strategy plan for project

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4222]
/kind documentation

## What mistake did you find / what is missing in the documentation?

The test strategy will define general approach, test processes, notification and escalation procedures, change management, metrics and analysis, release criteria, risks and mitigations.

Document is WIP: 
https://docs.google.com/document/d/1x6yuZuBRSqbY9Hdon2jGU0cEogVl-wszE5JxbKaQRA4/edit?usp=sharing

**Comment by rnapoles-rh** [comment]
@prietyc123 when you say "what is missing in the documentation" do you refer to the [test-Architecture.adoc](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc) ?
If that is the case, that document focuses on guidelines for setting test env.  and how to write test scripts. That is only one aspect of a test strategy.
A test strategy defines general approach, test processes, notification and escalation procedures, change management, metrics and analysis, release criteria, risks and mitigations.

**Comment by rnapoles-rh** [comment]
Document link was updated to provide commenter access.

**Comment by rnapoles-rh** [comment]
@prietyc123 @anandrkskd do you have any feedback?

**Comment by prietyc123** [comment]
> @prietyc123 @anandrkskd do you have any feedback?

@rnapoles-rh I did 1st round of review and commented out my concerns. Could you please have a look.

**Comment by prietyc123** [comment]
@rnapoles-rh I think test strategy doc are in place. Should we close this?

**Comment by rnapoles-rh** [comment]
I delivered a walkthrough of the strategy and integrated all feedback. Although the strategy is a living document, the required work to get it defined is complete so I am closing this.
