### ISSUE TITLE
odo link should work in absence of Service Binding Operator

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4237]
## User Story
As a user I want to be able to link a component to an Operator backed service or another component without the need to install Service Binding Operator.

## Acceptance Criteria 
- [ ] `odo link <service-name>` should work without having Service Binding Operator installed
- [ ] `odo link <component-name>` should work without having Service Binding Operator installed

## Links 
- Feature Request: #2613

/kind user-story
/area linking

**Comment by dharmit** [comment]
/lifecycle frozen

We might still use Service Binding for this but without the Operator. The Service Binding team plans to make the tool available as a library so that users who don't have the Service Binding Operator installed can still use the `odo link` feature.

**Comment by kadel** [comment]
/close
in favor of https://github.com/openshift/odo/issues/4543
