### ISSUE TITLE
Proposal for improved and interactive operator backed services

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4240]
/kind user-story

## User Story
As a developer the proposal should contain the workflow for improved interactive and non-interactive operator backed services workflow driven by schema present in the CRDs.

## Acceptance Criteria 
- [ ] It should consider both kuberenetes and openshift parts if they are different
- [ ] It should `odo service create` interactive and non-interactive flows
- [ ] It should consider validating parameters provided on non-interactive flows
- [ ] It should consider a route to still use the `alm-examples` of the CR
- [ ] It should consider providing useful information on `odo catalog describe services` command
- [ ] It should also provide json output that would be provided when these commands are executed
- [ ] These things should be documented in a markdown proposal which when merge would only then accomplish all the ACs of this issue

Note - `It` here is the proposal

### Not in scope
- This proposal **doesn't** scope out the storage of operator backed services in the devfile 
- This proposal **doesn't** scope out creation of operators only on `odo push` ( odo new workflow for operator services )

## Links 
- Feature Request: 
- Related issue: 
- https://github.com/openshift/odo/issues/2785
- https://github.com/openshift/odo/issues/2615

/kind user-story

**Comment by dharmit** [comment]
This looks nicely laid out. But I'm not sure if we need one more Proposal doc. The reason I'm not sure is that we already have a [proposal doc for Operator Hub integration](https://github.com/openshift/odo/blob/master/docs/proposals/operator-hub.md) in the repo. Sure that proposal could use some modification/update based on what we've learned during past few months.

**Comment by girishramnani** [comment]
that proposal outlines operator hub integration - this is about a different approach to building the schema which is a different proposal entirely.

**Comment by dgolovin** [comment]
**Just an idea **

What if we would be able to provide `machine readable` interaction? Imagine:

```
$odo create -o json
{
    type: "request",
    kind: "list",
    items: [
       "java-maven",
       "java-openliberty",
       "java-quarkus",
       "java-springboot",
       "java-vertx",
       "nodejs",
       "python"
    ]
}
```
IDE would translate it to UI element - QuickPick for VSCode - and then write result back to input stream
odo would respond ether with error json event or continue for next request json event.

That would mean if you have interactive mode to create odo objects on odo side we would automatically have it on IDE side.

**Comment by girishramnani** [comment]
I went through the openshift console to see how it builds its form and this the url which it was using for a service binding request

url - 
```
<cluster-url>/api/kubernetes/apis/apiextensions.k8s.io/v1/customresourcedefinitions/servicebindings.operators.coreos.com
```

```
{
  "kind": "CustomResourceDefinition",
  "apiVersion": "apiextensions.k8s.io/v1",
  "metadata": {
    "name": "servicebindings.operators.coreos.com",
    "selfLink": "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/servicebindings.operators.coreos.com",
    "uid": "8d92fd7d-e982-4ad5-9805-59fbdcdf02b1",
    "resourceVersion": "39711",
    "generation": 1,
    "creationTimestamp": "2020-11-25T09:00:01Z",
    "labels": {
      "operators.coreos.com/rh-service-binding-operator.openshift-operators": ""
    },
    "managedFields": [
      {
        "manager": "catalog",
        "operation": "Update",
        "apiVersion": "apiextensions.k8s.io/v1beta1",
        "time": "2020-11-25T09:00:01Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:spec":{"f:conversion":{".":{},"f:strategy":{}},"f:group":{},"f:names":{"f:kind":{},"f:listKind":{},"f:plural":{},"f:shortNames":{},"f:singular":{}},"f:preserveUnknownFields":{},"f:scope":{},"f:subresources":{".":{},"f:status":{}},"f:validation":{".":{},"f:openAPIV3Schema":{".":{},"f:description":{},"f:properties":{".":{},"f:apiVersion":{".":{},"f:description":{},"f:type":{}},"f:kind":{".":{},"f:description":{},"f:type":{}},"f:metadata":{".":{},"f:type":{}},"f:spec":{".":{},"f:description":{},"f:properties":{".":{},"f:application":{".":{},"f:description":{},"f:properties":{".":{},"f:bindingPath":{".":{},"f:description":{},"f:properties":{".":{},"f:containersPath":{".":{},"f:description":{},"f:type":{}},"f:secretPath":{".":{},"f:description":{},"f:type":{}}},"f:type":{}},"f:group":{".":{},"f:type":{}},"f:labelSelector":{".":{},"f:description":{},"f:properties":{".":{},"f:matchExpressions":{".":{},"f:description":{},"f:items":{},"f:type":{}},"f:matchLabels":{".":{},"f:additionalProperties":{},"f:description":{},"f:type":{}}},"f:type":{}},"f:name":{".":{},"f:description":{},"f:type":{}},"f:resource":{".":{},"f:type":{}},"f:version":{".":{},"f:type":{}}},"f:required":{},"f:type":{}},"f:customEnvVar":{".":{},"f:description":{},"f:items":{},"f:type":{}},"f:detectBindingResources":{".":{},"f:description":{},"f:type":{}},"f:envVarPrefix":{".":{},"f:description":{},"f:type":{}},"f:mountPathPrefix":{".":{},"f:description":{},"f:type":{}},"f:services":{".":{},"f:description":{},"f:items":{},"f:type":{}}},"f:type":{}},"f:status":{".":{},"f:description":{},"f:properties":{".":{},"f:applications":{".":{},"f:description":{},"f:items":{},"f:type":{}},"f:conditions":{".":{},"f:description":{},"f:items":{},"f:type":{}},"f:secret":{".":{},"f:description":{},"f:type":{}}},"f:required":{},"f:type":{}}},"f:type":{}}},"f:version":{},"f:versions":{}},"f:status":{"f:storedVersions":{}}}
      },
      {
        "manager": "kube-apiserver",
        "operation": "Update",
        "apiVersion": "apiextensions.k8s.io/v1",
        "time": "2020-11-25T09:00:01Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:status":{"f:acceptedNames":{"f:kind":{},"f:listKind":{},"f:plural":{},"f:shortNames":{},"f:singular":{}},"f:conditions":{}}}
      },
      {
        "manager": "olm",
        "operation": "Update",
        "apiVersion": "apiextensions.k8s.io/v1",
        "time": "2020-11-25T09:00:02Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:metadata":{"f:labels":{".":{},"f:operators.coreos.com/rh-service-binding-operator.openshift-operators":{}}}}
      }
    ]
  },
  "spec": {
    "group": "operators.coreos.com",
    "names": {
      "plural": "servicebindings",
      "singular": "servicebinding",
      "shortNames": [
        "sbr",
        "sbrs"
      ],
      "kind": "ServiceBinding",
      "listKind": "ServiceBindingList"
    },
    "scope": "Namespaced",
    "versions": [
      {
        "name": "v1alpha1",
        "served": true,
        "storage": true,
        "schema": {
          "openAPIV3Schema": {
            "description": "ServiceBinding expresses intent to bind an operator-backed service with an application workload.",
            "type": "object",
            "properties": {
              "apiVersion": {
  "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
  "type": "string"
},
              "kind": {
  "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
  "type": "string"
},
              "metadata": {
  "type": "object"
},
              "spec": {
  "description": "ServiceBindingSpec defines the desired state of ServiceBinding",
  "type": "object",
  "properties": {
    "application": {
  "description": "Application is used to identify the application connecting to the backing service operator.",
  "type": "object",
  "required": [
    "group",
    "resource",
    "version"
  ],
  "properties": {
    "bindingPath": {
  "description": "BindingPath refers to the paths in the application workload's schema where the binding workload would be referenced. If BindingPath is not specified the default path locations is going to be used.  The default location for ContainersPath is going to be: \"spec.template.spec.containers\" and if SecretPath is not specified, the name of the secret object is not going to be specified.",
  "type": "object",
  "properties": {
    "containersPath": {
  "description": "ContainersPath defines the path to the corev1.Containers reference If BindingPath is not specified, the default location is going to be: \"spec.template.spec.containers\"",
  "type": "string"
},
    "secretPath": {
  "description": "SecretPath defines the path to a string field where the name of the secret object is going to be assigned. Note: The name of the secret object is same as that of the name of SBR CR (metadata.name)",
  "type": "string"
}
  }
},
    "group": {
  "type": "string"
},
    "labelSelector": {
  "description": "A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.",
  "type": "object",
  "properties": {
    "matchExpressions": {
  "description": "matchExpressions is a list of label selector requirements. The requirements are ANDed.",
  "type": "array",
  "items": {"description":"A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.","type":"object","required":["key","operator"],"properties":{"key":{"description":"key is the label key that the selector applies to.","type":"string"},"operator":{"description":"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.","type":"string"},"values":{"description":"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.","type":"array","items":{"type":"string"}}}}
},
    "matchLabels": {
  "description": "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.",
  "type": "object",
  "additionalProperties": {"type":"string"}
}
  }
},
    "name": {
  "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?",
  "type": "string"
},
    "resource": {
  "type": "string"
},
    "version": {
  "type": "string"
}
  }
},
    "customEnvVar": {
  "description": "Custom env variables",
  "type": "array",
  "items": {"description":"EnvVar represents an environment variable present in a Container.","type":"object","required":["name"],"properties":{"name":{"description":"Name of the environment variable. Must be a C_IDENTIFIER.","type":"string"},"value":{"description":"Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \"\".","type":"string"},"valueFrom":{"description":"Source for the environment variable's value. Cannot be used if value is not empty.","type":"object","properties":{"configMapKeyRef":{"description":"Selects a key of a ConfigMap.","type":"object","required":["key"],"properties":{"key":{"description":"The key to select.","type":"string"},"name":{"description":"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?","type":"string"},"optional":{"description":"Specify whether the ConfigMap or its key must be defined","type":"boolean"}}},"fieldRef":{"description":"Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.","type":"object","required":["fieldPath"],"properties":{"apiVersion":{"description":"Version of the schema the FieldPath is written in terms of, defaults to \"v1\".","type":"string"},"fieldPath":{"description":"Path of the field to select in the specified API version.","type":"string"}}},"resourceFieldRef":{"description":"Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.","type":"object","required":["resource"],"properties":{"containerName":{"description":"Container name: required for volumes, optional for env vars","type":"string"},"divisor":{"description":"Specifies the output format of the exposed resources, defaults to \"1\"","type":"string"},"resource":{"description":"Required: resource to select","type":"string"}}},"secretKeyRef":{"description":"Selects a key of a secret in the pod's namespace","type":"object","required":["key"],"properties":{"key":{"description":"The key of the secret to select from.  Must be a valid secret key.","type":"string"},"name":{"description":"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?","type":"string"},"optional":{"description":"Specify whether the Secret or its key must be defined","type":"boolean"}}}}}}}
},
    "detectBindingResources": {
  "description": "DetectBindingResources is flag used to bind all non-bindable variables from different subresources owned by backing operator CR.",
  "type": "boolean"
},
    "envVarPrefix": {
  "description": "EnvVarPrefix is the prefix for environment variables",
  "type": "string"
},
    "mountPathPrefix": {
  "description": "MountPathPrefix is the prefix for volume mount",
  "type": "string"
},
    "services": {
  "description": "Services is used to identify multiple backing services.",
  "type": "array",
  "items": {"description":"Service defines the selector based on resource name, version, and resource kind","type":"object","required":["group","kind","version"],"properties":{"envVarPrefix":{"type":"string"},"group":{"type":"string"},"id":{"type":"string"},"kind":{"type":"string"},"name":{"description":"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?","type":"string"},"namespace":{"type":"string"},"version":{"type":"string"}}}
}
  }
},
              "status": {
  "description": "ServiceBindingStatus defines the observed state of ServiceBinding",
  "type": "object",
  "required": [
    "conditions",
    "secret"
  ],
  "properties": {
    "applications": {
  "description": "Applications contain all the applications filtered by name or label",
  "type": "array",
  "items": {"description":"BoundApplication defines the application workloads to which the binding secret has injected.","type":"object","required":["group","kind","version"],"properties":{"group":{"type":"string"},"kind":{"type":"string"},"name":{"description":"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?","type":"string"},"version":{"type":"string"}}}
},
    "conditions": {
  "description": "Conditions describes the state of the operator's reconciliation functionality.",
  "type": "array",
  "items": {"description":"Condition represents the state of the operator's reconciliation functionality.","type":"object","required":["status","type"],"properties":{"lastHeartbeatTime":{"type":"string","format":"date-time"},"lastTransitionTime":{"type":"string","format":"date-time"},"message":{"type":"string"},"reason":{"type":"string"},"status":{"type":"string"},"type":{"description":"ConditionType is the state of the operator's reconciliation functionality.","type":"string"}}}
},
    "secret": {
  "description": "Secret is the name of the intermediate secret",
  "type": "string"
}
  }
}
            }
          }
        },
        "subresources": {
          "status": {}
        }
      }
    ],
    "conversion": {
      "strategy": "None"
    },
    "preserveUnknownFields": true
  },
  "status": {
    "conditions": [
      {
        "type": "NamesAccepted",
        "status": "True",
        "lastTransitionTime": "2020-11-25T09:00:01Z",
        "reason": "NoConflicts",
        "message": "no conflicts found"
      },
      {
        "type": "Established",
        "status": "True",
        "lastTransitionTime": "2020-11-25T09:00:01Z",
        "reason": "InitialNamesAccepted",
        "message": "the initial names have been accepted"
      },
      {
        "type": "NonStructuralSchema",
        "status": "True",
        "lastTransitionTime": "2020-11-25T09:00:01Z",
        "reason": "Violations",
        "message": "spec.preserveUnknownFields: Invalid value: true: must be false"
      }
    ],
    "acceptedNames": {
      "plural": "servicebindings",
      "singular": "servicebinding",
      "shortNames": [
        "sbr",
        "sbrs"
      ],
      "kind": "ServiceBinding",
      "listKind": "ServiceBindingList"
    },
    "storedVersions": [
      "v1alpha1"
    ]
  }
}
```

**Comment by girishramnani** [comment]
See the comparison of the json and the form to confirm
<img width="1006" alt="Screenshot 2020-11-25 at 2 52 32 PM" src="https://user-images.githubusercontent.com/6551988/100207933-29219580-2f2e-11eb-9704-29a765d1522e.png">

<img width="893" alt="Screenshot 2020-11-25 at 2 52 19 PM" src="https://user-images.githubusercontent.com/6551988/100207917-258e0e80-2f2e-11eb-8c9a-f94edcd3fb0e.png">

**Comment by girishramnani** [comment]
now - I have to check if using a non-admin user allows you to fetch this information

**Comment by girishramnani** [comment]
So using a non-admin user fails so we need to reconsider the approach

<img width="1791" alt="Screenshot 2020-11-25 at 4 07 29 PM" src="https://user-images.githubusercontent.com/6551988/100216464-55421400-2f38-11eb-82ec-7db6d448bb36.png">

**Comment by girishramnani** [comment]
ok so current idea is "we do what web console does" which means if we can fetch the openv3schema then we do else we elegantly only provide the information we have access to.

We already have the `yaml view` type of capability using the file edit feature of `odo service create`

**Comment by girishramnani** [comment]
first step is to now implement the `odo catalog describe service` 
- `-o json` would provide the openV3Schema as is to adapter and then they build the form themselves - need to confirm with @dgolovin if they are ok with getting an openV3Schema
- the non json output would recursively print a human readable way to show the schema - probably using dot notions `port.type` for struct fields

**Comment by dharmit** [comment]
> the non json output would recursively print a human readable way to show the schema - probably using dot notions `port.type` for struct fields

We need to take a cue from how we currently print this output for Service Catalog based service. I don't mean to do it exactly the way we do it for Service Catalog but a thing to keep in mind would be - how would we print the output for minikube users who have both svc cat and OLM based Operators installed on their cluster?

**Comment by dgolovin** [comment]
@girishramnani @dharmit If we think in simplified odo model we should use object classes below: 
* component
* service
* link
   * component to service
   * component to component

I assume this issue is about linking component and operator backed service instance. For IDE linking ideally should be just 
```
$ odo list components
component1
component...
componentN

$odo list services
service1
service...
serviceN

$odo link componentN serviceN
```

Do you mean `odo link` requires additional options that are going to be different for different services and we have to pull that from openV3Schema and request that info from extension user?

**Comment by dharmit** [comment]
> Do you mean `odo link` requires additional options that are going to be different for different services and we have to pull that from openV3Schema and request that info from extension user?

This issue is around `odo service create`. Specifically the parameterization part.

For Service Catalog based services, odo provides both interactive mode (user only does `odo service create` on 3.11 cluster and odo interactively guides/helps user in service creation)  as well as ability to pass parameters for creating the service (`odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret -p postgresql_database=my_data -p postgresql_version=9.6
`).

However, odo doesn't support either of the two modes for Operator Hub backed services because I couldn't manage to figure this info out using OLM. That's what @girishramnani is trying to fix/address here.

**Comment by girishramnani** [comment]
so the conclusion with the adapter team was that
- `odo catalog describe service -o json` would provide the json schema from the CRD definition if the user is signed in as admin, if the user isn't signed in as admin we provide the alm-example and also a flag `notAdmin` allowing the adapter to "suggest the user to add the role they need to see CRD for better experience"

- also `odo service create` would allow providing parameters as it usually does but also has `--input-file` which would take the file path of the yaml file that the adapter team can use. They would create the CR yaml file and provide that as an argument.

**Comment by girishramnani** [comment]
we need to find a way to convert openAPIv3schema to jsonSchema

**Comment by kadel** [comment]
> * also `odo service create` would allow providing parameters

How would this work? The parameters for constructing CustomResource can be quite complex. Take this for example https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/dfb75dbaff7848ac42fffb55bc3b5063c702f690/helm_chart/crds/mongodb.mongodb.com.yaml#L36-L573

I guess we will need some kind of convention to create a mapping between command line parameters and CustomResource structure that is defined by openAPIV3Schema.


> we need to find a way to convert openAPIv3schema to jsonSchema

Why do we need to convert it? This is going just another layer of complexity. Tools and plugins should be able to work with openAPIv3schema, there are libraries for openAPIv3schema for almost every language.

**Comment by girishramnani** [comment]
> Why do we need to convert it? This is going just another layer of complexity. Tools and plugins should be able to work with openAPIv3schema, there are libraries for openAPIv3schema for almost every language.

its easy to deal with json schema as per what denis and jeff mentioned to me

**Comment by kadel** [comment]
> > Why do we need to convert it? This is going just another layer of complexity. Tools and plugins should be able to work with openAPIv3schema, there are libraries for openAPIv3schema for almost every language.
> 
> its easy to deal with json schema as per what denis and jeff mentioned to me

Conversion is a little bit worrying for me. I bet that there is a reason why it is in OpenAPI and not JSON Schema. 
It would be much better if we can use OpenAPI Schema from start to end and completely avoid conversion to JSON Schema.

@dgolovin @jeffmaury How big a problem it would be for you to work with OpenAPI Schema?

**Comment by dharmit** [comment]
>  * `odo catalog describe service -o json` would provide the json schema from the CRD definition if the user is signed in as admin, if the user isn't signed in as admin we provide the alm-example and also a flag `Admin` allowing the adapter to "suggest the user to add the role they need to see CRD for better experience"

From what I have seen, "alm-examples" are filled with placeholder data. Fields under the `spec` are not going to be able to help us provide a meaningful output to the user. For example, below are two alm-examples - one for EtcdCluster and one for ServiceBinding - how do you suggest we use this in `odo catalog desribe service`?

```yaml
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  annotations:
    etcd.database.coreos.com/scope: clusterwide
  name: example
spec:
  size: 3
  version: 3.2.13
```

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: example-servicebinding
spec:
  application:
    group: apps
    name: nodejs-rest-http-crud
    resource: deployments
    version: v1
  mountPathPrefix: /var/credentials
  services:
  - group: postgresql.example.dev
    kind: Database
    name: pg-instance
    version: v1alpha1
```
Here the alm-example of ServiceBinding is making a bunch of assumptions about the application and service being linked! It's useless as-is in odo's context.

Or here's the alm-example of openshift-pipelines Operator's "Config" service:
```yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: Config
metadata:
  name: name.must.be-cluster
spec:
  targetNamespace: openshift-pipelines
```
Without CRD access (`kubectl get crds`), we're not going to be able to do much, IMO.

**Comment by kadel** [comment]
@dharmit I think that the idea was that in the case user doesn't have access to OpenAPIV3Schema we can leverage the fact that it is natural for IDEs to work with files. So they can just show users the example that they can edit themself. Not ideal, but it is at least something. This is also what OCP Web console is doing.

**Comment by kadel** [comment]
Let's completely skip the interactive part for now. The interactive mode won't be usable by plugins. If we have non-interactive flow then we can easily add interactive mode later.

**Comment by girishramnani** [comment]
Found this article that underlines how the form is built in the web console - but still the access limitations say https://www.openshift.com/blog/openshift-4-2-declarative-dynamic-ui-for-your-operator

**Comment by girishramnani** [comment]
On further exploration - this is the form https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/operand/operand-form.tsx in web console

**Comment by girishramnani** [comment]
It seems the frontend team is directly using https://github.com/rjsf-team/react-jsonschema-form and they are getting the jsonschema from the cluster, trying to search if I can get json schema as well.
