### ISSUE TITLE
odo env view -o json outputs raw text

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#4243]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
```
odo v2.0.0 (6fbb9d9bf)

Server: https://172.16.0.10:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
`odo env view -o json`

## Actual behavior
```
PARAMETER NAME    PARAMETER VALUE 
Name              nodecomp        
Project           devfile         
DebugPort                         
```

## Expected behavior
JSON output

**Comment by girishramnani** [comment]
json output is not supported for `odo env view` command yet.

**Comment by girishramnani** [comment]
I would like to work on this
