### ISSUE TITLE
Elaborate what it means by "persistent" in the context of odo

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4256]
From odo users' perspective it could add value to elaborate what "persistent" storage means. We're talking about users who don't have any (or much) experience with Kubernetes and odo's doing the job of abstracting k8s/OCP terminologies from them.

> maybe explain what does it mean when you say `persistent`, like is that when a developer wants to keep their data safe between `odo push`?

_Originally posted by @girishramnani in https://github.com/openshift/odo/pull/4249#discussion_r529685956_

**Comment by girishramnani** [comment]
yeah - this is a good idea
