### ISSUE TITLE
No 2.0.2 binary on mirrors

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#4269]
/kind bug

There's no 2.0.2 binary available in the mirrors, so impossible to download.

**Comment by mohammedzee1000** [comment]
Yes, we are blocked in the release pipeline atm. They will be available shortly. I have an explicit warning that official binaries will be made available

**Comment by mohammedzee1000** [comment]
@jorgemoralespou sync complete http://mirror.openshift.com/pub/openshift-v4/clients/odo/v2.0.2/
/close
