### ISSUE TITLE
odo complains of failing to create ingress but URL gets created

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4270]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
```sh
$ odo url create --host `minikube ip`.nip.io
 ✓  URL node-todo-8080 created for component: node-todo

To apply the URL configuration changes, please use `odo push`

$ odo url list                              
Found the following URLs for component node-todo
NAME               STATE          URL                                             PORT     SECURE     KIND
node-todo-8080     Not Pushed     http://node-todo-8080.192.168.39.156.nip.io     8080     false      ingress
There are local changes. Please run 'odo push'.

$ odo push
```

## Actual behavior
```sh
odo push

Validation
 ✓  Validating the devfile [32094ns]

Creating Kubernetes resources for component node-todo
 ✓  Waiting for component to start [7s]
 ⚠  Unable to create ingress, missing host information for Endpoint http-8080, please check instructions on URL creation (refer `odo url create --help`)


Applying URL changes
 ✓  URL node-todo-8080: http://node-todo-8080.192.168.39.156.nip.io/ created

Syncing to component node-todo
 ✓  Checking files for pushing [568651ns]
 ✓  Syncing files to the component [188ms]

Executing devfile commands for component node-todo
 ✓  Executing install command "npm install" [20s]
 ✓  Executing run command "npm start" [1s]

Pushing devfile component node-todo
 ✓  Changes successfully pushed to component

$ kubectl get ingress
NAME                       CLASS    HOSTS                                  ADDRESS          PORTS   AGE
node-todo-8080-node-todo   <none>   node-todo-8080.192.168.39.156.nip.io   192.168.39.156   80      75s
```
In above output, odo complains `Unable to create ingress, missing host information for Endpoint http-8080, please check instructions on URL creation (refer odo url create --help)`

But ingress has been successfully created and I can also access the app on the URL that was created

## Expected behavior
odo should not complain when things just work

/kind bug
/area url
/area UX

**Comment by mik-dass** [comment]
> In above output, odo complains Unable to create ingress, missing host information for Endpoint http-8080, please check instructions on URL creation (refer odo url create --help``

The creation of URL `http-8080` failed. It was the default URL in the `devfile.yaml`. 

> Applying URL changes
 ✓  URL node-todo-8080: http://node-todo-8080.192.168.39.156.nip.io/ created

The URL created was node-todo-8080.

**Comment by dharmit** [comment]
> > In above output, odo complains Unable to create ingress, missing host information for Endpoint http-8080, please check instructions on URL creation (refer odo url create --help``
> 
> The creation of URL `http-8080` failed. It was the default URL in the `devfile.yaml`.

But the original devfile for nodejs has port 3000. I changed it from 3000 to 8080 before doing `odo push`. So `http-8080` isn't default in that case, no?

**Comment by mik-dass** [comment]
> But the original devfile for nodejs has port 3000. I changed it from 3000 to 8080 before doing `odo push`. So `http-8080` isn't default in that case, no?

`http-8080` was the URL present when the component was created. It is the default endpoint in the nodejs devfile from the registry (https://github.com/odo-devfiles/registry/) https://github.com/odo-devfiles/registry/blob/0b0e73401e462324a8db32b60c625f56ad639391/devfiles/nodejs/devfile.yaml#L20. `odo url create` created a new URL in the devfile.

**Comment by dharmit** [comment]
I think we both are talking about `http-3000` and not `http-8080`. The link you shared has `http-3000` as the endpoint in devfile. Am I missing something? :thinking:

**Comment by adisky** [comment]
While doing `odo push`, odo tries to create url from devfile.yaml, this message is generating during that,
```
Unable to create ingress, missing host information for Endpoint http-8080, please check instructions on URL creation (refer `odo url create --help`)
```

however, you already have created the url using `odo url create`  which is successful.

This behavior of odo url gets confusing for ingress, i mean we are auto creating url during `odo push`  which works ok for route case but not for ingress one, as we cannot provide `host` information in devfile.

**Comment by adisky** [comment]
checked the code, we are checking against endpoint name, before default creating against `odo push`


> But the original devfile for nodejs has port 3000. I changed it from 3000 to 8080 before doing odo push. So http-8080 isn't default in that case, no?

@dharmit you have updated the port but have you changed endpoint name?

**Comment by dharmit** [comment]
> @dharmit you have updated the port but have you changed endpoint name?

Yes. I changed the port number as well the endpoint name. I just did `sed -i s/3000/8080/' devfile.yaml` on the default devfile that `odo create` pulls for me.

**Comment by adisky** [comment]
> Yes. I changed the port number as well the endpoint name. I just did `sed -i s/3000/8080/' devfile.yaml` on the default devfile that `odo create` pulls for me.

hmm, then something is broken here :|

**Comment by dharmit** [comment]
Don't see this any more against `main` branch.

/close
