### ISSUE TITLE
Get rid of references to experimental mode in the documentation

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4273]
/kind documentation

## What mistake did you find / what is missing in the documentation?
While scrolling through [OCP 4.6 docs](https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/odo-cli-reference.html#preference), I found references to enable experimental mode. However, nothing in odo is currently in experimental mode. We need to get rid of these references.

## What is the relevance of it?
Outdated information in the docs.

**Comment by dharmit** [comment]
@boczkowska honest question since I don't know who could be best placed to address/fix this - is this something you need help with from odo team or is this something docs folks can look into?

**Comment by boczkowska** [comment]
@dharmit I'll pick it up.

**Comment by boczkowska** [comment]
The only place where experimental is mentioned is in the CLI reference: https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/odo-cli-reference.html#preference
I believe I removed it everywhere else, so the issue can be closed
