### ISSUE TITLE
Test compilation fails on "vet" check with ginkgo

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4277]
/kind failing-test
/area testing

## What versions of software are you using?

**Operating System:**
win10

**Output of `odo version`:**
master

## How did you run odo exactly?

Trying to execute the test locally on windows
```
> ginkgo .\tests\integration\
Failed to compile integration:
# github.com/onsi/ginkgo
vet.exe: decoding facts for "github.com/onsi/ginkgo/internal/remote": EOF
FAIL
Ginkgo ran 1 suite in 16.956306s
Test Suite Failed
```

## Actual behavior

Whenever we execute the tests, it fails on compilation saying 
```
Failed to compile integration:
# github.com/onsi/ginkgo
vet.exe: decoding facts for "github.com/onsi/ginkgo/internal/remote": EOF
```

## Expected behavior

Tests should not throw such compilation error.

## Any logs, error output, etc?

Running locally.

## Proposed action plan
Start research by setting up environment on windows to try to replicate the problem locally.
Will run the tests against:
 - 4.6.0 OCP cluster
 - Minishift
 - minikube
Could not fine any online references to this problem.

**Comment by rnapoles-rh** [comment]
Tried on a local windows 10 box with minishift and tests start executing after running 
`> ginkgo .\tests\integration\`
Next step is to reinstall ginkgo in the CI win10 env.

**Comment by rnapoles-rh** [comment]
I tried on the PSI windows VM where the problem was reported. I restarted the VM and I was able to execute the tests. I did not get the compilation error. I will try to run the tests again and if all goes well I will close it.

I noticed that the gingko version we have installed is alder that the one defined in the Makefile. I will open another issue to make sure we upgrade the ginkgo version in all our test VM so we have consistency across all test beds.

**Comment by rnapoles-rh** [comment]
Tried again on the VM where we were getting the compilation failure and test were executed as expected:
```
PS C:\Users\Admin\go\src\github.com\openshift\odo> ginkgo .\tests\integration\
Running Suite: Integration Suite
================================
Random Seed: 1607612640
Will run 2 of 177 specs

SSSSSSSSSSSSSSS+SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS+SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
JUnit report was created: C:\Users\Admin\go\src\github.com\openshift\odo\reports\junit_2020-12-10_15-04-05_1.xml

Ran 2 of 177 Specs in 9.276 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 175 Skipped
PASS | FOCUSED

Ginkgo ran 1 suite in 15.1674498s
Test Suite Passed
```
Closing
