### ISSUE TITLE
Enable 4.7 cluster on periodic jobs

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4280]
/kind user-story
/area testing

## User Story
As a user I want to run periodic jobs on 4.7 cluster

## Acceptance Criteria 
- [ ] Fixing the blockers (if any) for enabling 4.7 cluster on Periodic jobs
        - https://github.com/openshift/odo/issues/4303
- [ ] Jobs should run successfully on 4.7 ocp cluster.

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by prietyc123** [comment]
It s blocked on https://github.com/openshift/odo/issues/4303

**Comment by kadel** [comment]
> * [ ]  Fixing the blockers (if any) for enabling 4.7 cluster on Periodic jobs
> *

Can you please link blocker issues here?

**Comment by prietyc123** [comment]
Fixed via https://github.com/openshift/release/pull/14234
