### ISSUE TITLE
Move from using master branch to main branch

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4284]
We should move odo project to using `main` branch instead of the `master` branch that it's currently using.

**Comment by dharmit** [comment]
@mohammedzee1000 can you PTAL at this issue? Changing branch name might affect the scripts you're working on or already have for the CI/tests.

**Comment by mohammedzee1000** [comment]
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/
I think shis should help

**Comment by mohammedzee1000** [comment]
Another thing we can consider is using github actions https://github.com/marketplace/actions/default-branch-migration altho this will need us to enable it first. This will apparently also handle updating the PRs.

One thing that is unclear is how PRs will be affected if we go manual route

**Comment by mohammedzee1000** [comment]
Scope:

- [ ] Create main branch based on master
- [ ] Update PRs to be against main
- [ ] Delete master branch (not sure how this will affect existing releases, probably not)

**Comment by mohammedzee1000** [comment]
The first step in this is to prep the PR that will go into openshift/release so it can be merged as early as possible once the main branch is ready.

The second step to this is to enact a soft freeze on merging PRs, soft because it does not mean we can stop the merge of PRs already in the merge queue by automation, but to prevent more PRs from going into the queue.

The third step, after a reasonable wait, to allow PRs in the merge to merge, is to create the main branch based on master.

The fourth step is to merge the openshift/release PR.

The fifth step is to update open PRs to be targetted towards main branch by their respective OPs https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by mohammedzee1000** [comment]
cc @dharmit @kadel ^ wdyt?

**Comment by kadel** [comment]
@mohammedzee1000 It might be a good idea to create a testing repo in your own namespace (or use your odo fork) and test this process first (of course without prow updates)

**Comment by mohammedzee1000** [comment]
Tried it on https://github.com/mohammedzee1000/test-repo

1. Created repo with `main` as default branch
2. Added some commit to `main`
3. Created PR branch, pushed a commit and raised PR https://github.com/mohammedzee1000/test-repo/pull/1
4. Created another branch `newdefault`, based on `main`
5. Added extra commit to `newdefault`
6. Updated PR https://github.com/mohammedzee1000/test-repo/pull/1 to be based on `newdefault`
7. Rebased PR and pushed
8. Merged the PR.

**Comment by mohammedzee1000** [comment]
@dharmit @kadel I was thinking doing the migration today afternoon as there will be less activity today.

What do you guys think?

**Comment by girishramnani** [comment]
Why is this high priority? Its just a branch name, does it affect us in any way?

**Comment by mohammedzee1000** [comment]
Branch created, configs pushed. All that remains is waiting for things to stabilize/fix anything if needed.
Also ci-firewall needs to switch the main branch for which, the pr is up.

**Comment by dharmit** [comment]
@mohammedzee1000 do you think we can consider this as Done?

**Comment by kadel** [comment]
the last step should be deleting `master` branch, or renaming it to something like `backup-master` fi we want to be extra safe
Than we can close this

**Comment by mohammedzee1000** [comment]
The tests are stable and all open prs are against `main` so I can say. that the analysis is complete. I will send pr tomorrow to delete test configs for master branch followed by renaming `master` to `backup-master`

**Comment by mohammedzee1000** [comment]
Anand has raised the PR for deleting test configs for `master` branch https://github.com/openshift/release/pull/18248
Once this goes in il complete the rename

**Comment by mohammedzee1000** [comment]
PR merged. `master` branch renamed to `master-backup`
The last step is to remove the branch protection rules for the master branch. @kadel @dharmit @girishramnani one of you needs to do this.
Once its done, we can close this issue

**Comment by dharmit** [comment]
I've removed the branch protection rule for `master-backup`. 

/close
