### ISSUE TITLE
Update ci-reference test doc

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4289]
/kind documentation

## What mistake did you find / what is missing in the documentation?

ci-reference doc https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc does not have details about about tests on CI. Like what are the test run on travis, prow ...

**Comment by anandrkskd** [comment]
ci-reference doc does not contain information regarding 

- [ ] the test that are running on CI, e.g : under travisCI we run test for kubernetes, 
- [ ] Test workflow/diagram of CI.
