### ISSUE TITLE
`odo describe` does not work when cluster is not accessible or user is logged out

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4302]
/kind bug

odo version is 2.0.2.

Was working in previous release until this line was added.
https://github.com/openshift/odo/blob/1cb28b2f07b878a699843daffe01bfe5a8159686/pkg/component/component_full_description.go#L154

When not connected returns the error below after delay:
```
~/p/vscode-openshift-tools/out/tools/linux/odo describe -o json -v 10
{
	"kind": "Error",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"creationTimestamp": null
	},
	"message": "Get \"https://api.crc.testing:6443/apis/route.openshift.io/v1?timeout=32s\": dial tcp 192.168.130.11:6443: connect: no route to host"
}
```

When not logged in it returns error below:

```
~/p/vscode-openshift-tools/out/tools/linux/odo describe -o json
{
	"kind": "Error",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"creationTimestamp": null
	},
	"message": "forbidden: User \"system:anonymous\" cannot get path \"/apis/route.openshift.io/v1\""
}
```

When line above modified to continue in case of error as

```
if e != nil {
   routeSupported = true;
}
```

It helps to get it back printing the component's description, but urls are still missing because it only works when connected to cluster.

**Comment by girishramnani** [comment]
I can work on this bug for this sprint

**Comment by girishramnani** [comment]
blocked on https://github.com/openshift/odo/pull/4496

**Comment by girishramnani** [comment]
and on this as well https://github.com/openshift/odo/pull/4472

**Comment by girishramnani** [comment]
was able to create a PR based off https://github.com/openshift/odo/pull/4472 so have a working PR but we cannot merge it until 4472 isn't done. 
But no active work is needed from my end hence moving this to review
