### ISSUE TITLE
Broken link in Releases page

### ISSUE THREAD

**Issue by tetchel** [openshift/odo#4308]
/kind bug

![image](https://user-images.githubusercontent.com/8888438/102105823-da18a300-3dfd-11eb-8f52-42e77b2a044d.png)

[The latest release page](https://github.com/openshift/odo/releases/tag/v2.0.3) links to https://docs.openshift.com/container-platform/4.6/cli_reference/openshift_developer_cli/installing-odo.html which does not exist.

**Comment by kadel** [comment]
It looks like OpenShift Docs slightly changed URL in the latest release.
The correct link is now
https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/installing-odo.html

I've fixed the link in our release notes.

Thank you @tetchel for reporting this.

/close
