### ISSUE TITLE
Confusing message about default project.

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4309]
```
▶ odo create java-maven
 ⚠  odo may not work as expected in a default project, please run the odo component in a non-default project. To create a new project, use `odo project create`.
Validation
 ✓  Checking devfile existence [23679ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [51231ns]
 ✓  Validating devfile component [95996ns]

Please use `odo push` command to create the component with source deployed
```

> ⚠  odo may not work as expected in a default project, please run the odo component in a non-default project. To create a new project, use `odo project create`.

This is a really confusing message for both Kubernetes and OpenShift users

### Kubernetes
For minikube or any other Kubernetes users this message provides no value. It doesn't matter if they are using the `default` project or not. 
#### Solution
Add a condition that will check if the cluster supports `Project` resource. If not, the warning should not be displayed even if the `default` project is being used.

### OpenShift
OpenShift users should not use the `default` project. 
But the problem is that if the user does what the warning says; run `odo project create` it won't help them, the component project name is already recorded in `env.yml`, so it will have no effect on the existing component.
#### Solution
Not sure what to do here. I would probably make this warning error and completely prevent users from using `default` project on OpenShift. 

(a little bit of background why we don't users to use `default` project is in https://github.com/openshift/odo/issues/4027#issuecomment-700179907)

**Comment by girishramnani** [comment]
I can work on this

**Comment by niconosenzo** [comment]
@dharmit I would like to work on this if you don't mind.

**Comment by dharmit** [comment]
/assign @niconosenzo 

Nicolas, it's yours. Make sure to take a look at solution proposed by @kadel and ask us questions if anything's confusing. As for checking if the `project` resource is supported, we already have a function in odo code: https://github.com/openshift/odo/blob/474bfd6a30274a8e86691e9e3aa8f200bfb921cb/pkg/occlient/projects.go#L209-L212

**Comment by niconosenzo** [comment]
@dharmit @kadel  

```
		// Check whether resource "Project" is supported
		projectSupported, err := co.Client.IsProjectSupported()

		if err != nil {
			// we don't need to return (fail) if this happens
			log.Warning("Project resource supportability check failed.")
		}

		if projectSupported && componentNamespace == "default" {
			return errors.New("odo may not work as expected in a default project, please run the odo component in a non-default project")
		}
```
This code is currently lacking of user-kind verification, it will fail and exit if "default" project is being used,  is there any preferred way to check if it's a kubernetes or Openshift User?

**Comment by dharmit** [comment]
> This code patch is currently lacking of user-kind verification
> is there any preferred way to check if it's a kubernetes or Openshift User?

I'm lost about why the "user" thing matters here. I think the idea is to check if the user's running k8s cluster in backend or an OCP cluster. And the way to do that would be to check if `Project` is supported.

As far as user is concerned, we don't bother much about it.

Please let me know if I'm missing something w.r.t your question.

**Comment by niconosenzo** [comment]
> I'm lost about why the "user" thing matters here. I think the idea is to check if the user's running k8s cluster in backend or an OCP cluster.

Sorry that's what I meant. So, IsProjectSupported() would be fairly enough for that means, correct ? If so, I will submit the patch code.

**Comment by dharmit** [comment]
Yes, `IsProjectSupported` should be good for starters. Once you have a patch, let's see if that suffices. I think it should. :+1:
