### ISSUE TITLE
Implement containerize local test environment

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4326]
/kind user-story
/area testing

## User Story
As a user I want to replicate prow CI test environment locally.

## Acceptance Criteria 
- [ ] It should provide a containerize local test environment
- [ ] We should be able to replicate prow CI test environment locally

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by girishramnani** [comment]
I am not sure what `provide a containerize local test environment` means?

**Comment by prietyc123** [comment]
> I am not sure what provide a containerize local test environment means?

@girishramnani Basically our CI test environment runs on a container. IMO its better to open an option to use the same CI container images locally, as they provide the same test environment as the final CI validation.
Currently developer/tester runs local test on their host machine which may require some changes on their host machine to run odo test. In containerize local env we will provide a container and from there odo pre configuration/test will run. We just need to mount the test result directory path in the container to get the test log in the host machine.

**Advantage :**
- No configuration changes done on host machine to run odo test
- Get the almost same CI environment 
- Help in debugging CI specific failure to some extent

**Disadvantage:**
- The whole test process will be slow down by couple of minutes as we need to spinnup a test container.

**Comment by dharmit** [comment]
> Basically our CI test environment runs on a container

Really? I think it runs on an OpenShift cluster that's running in VMs on a cloud. Same for PSI - it will still be running in VMs on PSI, no? Or are you talking about the tests themselves being called from inside some container? I'm not aware if that's the case either.

> Currently developer/tester runs local test on their host machine which may require some changes on their host machine to run odo test

I use CRC. Most of the devs use CRC or minikube instead of running OpenShift/k8s directly on host machine.

> In containerize local env we will provide a container and from there odo pre configuration/test will run.

And where will the OpenShift/k8s instance that we should be testing against be? Running as containers on the host system?

Overall, I'm quite lost as to what problem we're trying to fix. I'm hoping to not be the only one who's lost here. :disappointed:

**Comment by prietyc123** [comment]
> Really? I think it runs on an OpenShift cluster that's running in VMs on a cloud. Same for PSI - it will still be running in VMs on PSI, no? Or are you talking about the tests themselves being called from inside some container? I'm not aware if that's the case either.

Absolutely, the cluster runs somewhere in ASW cloud (CI provided cluster) and in PSI its on a VM. But from the test container https://github.com/openshift/odo/blob/master/openshift-ci/build-root/Dockerfile we are launching reconfiguration and test script. I want to bring this test container locally and provide the same configuration to launch odo test.

> I use CRC. Most of the devs use CRC or minikube instead of running OpenShift/k8s directly on host machine.

Even I uses CRC sometime. My intention is to crate a test container like CI locally irrespective of hosted cluster.

> And where will the OpenShift/k8s instance that we should be testing against be? Running as containers on the host system?

I am not touching OpenShift/k8s instance. I am just providing a test container as CI does for launching odo test.

**Comment by girishramnani** [comment]
I mean I understand that problem but currently its not a big problem as odo doesn't do a lot of damage to local machine when running the tests but 
if you want to have a local test env then write a .devcontainer https://code.visualstudio.com/docs/remote/containers

**Comment by girishramnani** [comment]
would be a good thing for new devs?

**Comment by prietyc123** [comment]
> I mean I understand that problem but currently its not a big problem as odo doesn't do a lot of damage to local machine when running the tests but
> if you want to have a local test env then write a .devcontainer https://code.visualstudio.com/docs/remote/containers

It's not only for damage done to local machine but also it has advantage like getting the same test env like openshift CI provides. Moreover we can verify complain like it fails on CI but passes locally and certainly this indirectly reduces load on CI as this is verified locally before sending the pr. But still it will be a developer/tester choice to use this option.
TBH now I have information on how .devcontainer https://code.visualstudio.com/docs/remote/containers. works. I will go through it to get more clarity on it, But I am not sure whether .devcontainer provide the same solution for the issue I opened. I will park this issue aside until I get more clarity on .devcontainer in a separate issue.

**Comment by prietyc123** [comment]
> if you want to have a local test env then write a .devcontainer https://code.visualstudio.com/docs/remote/containers

.devcontainer vs-code extension uses docker in the backend to spinner the containerize environment. My plan is also to do the same thing but not by using any tool extension. I will use the default tool set that we are using for building and testing the binary. For example - Docker and make.
I need to create a docker file having minimum build dependency with mounted odo local directory root path. Then we have to manage the test run through make target.
For example:
```
make test-integration - will build and run odo test in the test container
make test-integration-local - will build and run odo test in the local machine
```
AFAIK @mik-dass uses goland for his development work and I am not sure who else using it in our team. I think it is not a good idea to enforce a single tool where people are comfortable with other third party tooling, but yes we can write a blog post on how we can containerize odo dev/test environment using vs-code .devcontainer extension.

**Comment by prietyc123** [comment]
Task associated with this issue:

- [ ] Create a docker file ( Like https://github.com/openshift/odo/blob/master/openshift-ci/build-root/Dockerfile )
- [ ] Create a docker mount point with the local odo directory
- [ ] Write the make target (include running the docker file)
