### ISSUE TITLE
Incorrect error message relating to default project

### ISSUE THREAD

**Issue by sympatheticmoose** [openshift/odo#4342]
/kind bug

Not severe. Just a bit of a gotcha which I keep hitting since I often run odo pointing at docker-desktop, but frequently kill docker when not in use. Partly relates to https://github.com/openshift/odo/issues/4309

## What versions of software are you using?

**Operating System:** macOS

**Output of `odo version`:** odo v2.0.3 (9ae754023)

## How did you run odo exactly?
kube context set to docker-desktop, but not currently running docker
`odo create [any]` 

## Actual behavior
Error msg:
 ✗  You don't have permission to create or set project 'default' or the project doesn't exist. Please create or set a different project
	odo project create|set <project_name>

Which is completely unrelated to the actual problem but seeing it as a fatal error reminds me to check docker is running, and sure enough that will fix it. Otherwise I'd guess a user would try that `project create` cmd, and then hit the connection refused error:
 ✗  Get "https://kubernetes.docker.internal:6443/apis/project.openshift.io/v1?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused

Which is a bit clearer towards what the issue is, but still doesn't guide the user to resolve.

## Expected behavior
Perhaps something similar to the check we had in Appsody which would give the following output on `appsody init`:
[Warning] Failed to check prerequisites: docker does not seem to be installed or running - failed to execute docker ps
...
[Error] Could not inspect the image: exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by kadel** [comment]
The plan is to stop checking the cluster on `odo create` (https://github.com/openshift/odo/issues/4096).
`odo create` should work even if the cluster is not running,There is no real reason why the cluster should be required for `odo create`. 
The cluster connection should be required only once odo needs to perform or fetch information from cluster.
