### ISSUE TITLE
Update import paths for github.com/devfile/api to github.com/devfile/api/v2

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#4346]
We've recently updated the module path for the [github.com/devfile/api](https://github.com/devfile/api) Go module to now be `github.com/devfile/api/v2`, to enable us to release tagged versions of the Go module that match the Devfile schema's version (e.g. module version v2.0.0 for a 2.0.0 schema version). Some discussion on why this was needed can be found [here](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

This doesn't need to be done immediately, but once a new version of the devfile api is pulled into odo, the import paths for the Devfile API package that odo uses will need to be updated to change instances of `import github.com/devfile/api/pkg...` in odo to `import github.com/devfile/api/v2/pkg...`. (e.g. in https://github.com/openshift/odo/blob/adaa1b44e8de5ab0aa0d357294174f8efb8bdd24/pkg/odo/cli/storage/create.go#L7 and https://github.com/openshift/odo/blob/526ce0af8ce506ea4709595a5a9abb160ea3abe1/pkg/url/status_test.go#L8, among other instances)

**Comment by dharmit** [comment]
This will most likely get addressed as a part of what I'm doing on #4160 to add CRD to devfile when user does `odo service create`.

**Comment by mik-dass** [comment]
This is a breaking change and many apis have changed in the latest version of the library. Thus a lot of our code base need to change including many unit tests.
