### ISSUE TITLE
Odo create on the same directory works when run multiple times

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4354]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
Odo create on the same directory works when run multiple times.

## Actual behavior
```
odo create nodejs
odo create nodejs
odo create
```

## Expected behavior
```
odo create nodejs
odo create <- this should fail
```

## Any logs, error output, etc?
It even works with giberish component type
```
(base) girish@MacBook-Pro bhas % odo create nojde
Validation
 ✓  Creating a devfile component from devfile path: /Users/girish/GoProjects/src/github.com/openshift/odo/bhas/devfile.yaml [141639ns]
 ✓  Validating devfile component [107212ns]

Please use `odo push` command to create the component with source deployed
(base) girish@MacBook-Pro bhas % odo create nsdfdfgdfhgfghgfh
Validation
 ✓  Creating a devfile component from devfile path: /Users/girish/GoProjects/src/github.com/openshift/odo/bhas/devfile.yaml [390480ns]
 ✓  Validating devfile component [144130ns]

Please use `odo push` command to create the component with source deployed
```

**Comment by deboer-tim** [comment]
Is this a regression? On 2.0.1 I get this error:
```
 ✗  this directory already contains a component
```
And when I try gibberish I get:
```
Validation
 ✗  Checking devfile existence [711627ns]
 ⚠  Devfile component type kfglsjhr is not supported, please run `odo catalog list components` for a list of supported devfile component types
 ✗  component type not found
```

**Comment by girishramnani** [comment]
seems so

**Comment by girishramnani** [comment]
maybe try 2.0.3 @deboer-tim ?

**Comment by girishramnani** [comment]
> And when I try gibberish I get:
> 
> ```
> Validation
>  ✗  Checking devfile existence [711627ns]
>  ⚠  Devfile component type kfglsjhr is not supported, please run `odo catalog list components` for a list of supported devfile component types
>  ✗  component type not found
> ```

This should also not happen it should fail with `this directory alread contains a component`

**Comment by anandrkskd** [comment]
Not able to reproduce it on 2.0.3 

``` 
$ odo create nodejs     
Validation
 ✓  Checking devfile existence [76021ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [145668ns]
 ✓  Validating devfile component [266867ns]

Please use `odo push` command to create the component with source deployed
```
running it for 2nd time it gives this error
 
```
 $ odo create nodejs
 ✗  this directory already contains a component
```

**Comment by girishramnani** [comment]
I would like to work on this

**Comment by dharmit** [comment]
I'm seeing this when I execute same `odo create` command with component name successive times:
```sh
$ odo create nodejs node-todo
Validation
 ✓  Checking devfile existence [15949ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [30943ns]
 ✓  Validating devfile component [92379ns]

Please use `odo push` command to create the component with source deployed

$ odo create nodejs node-todo
 ✗  accepts between 0 and 1 arg when using existing devfile, received 2
```

**Comment by girishramnani** [comment]
> I'm seeing this when I execute same `odo create` command with component name successive times:
> 
> ```shell
> $ odo create nodejs node-todo
> Validation
>  ✓  Checking devfile existence [15949ns]
>  ✓  Creating a devfile component from registry: DefaultDevfileRegistry [30943ns]
>  ✓  Validating devfile component [92379ns]
> 
> Please use `odo push` command to create the component with source deployed
> 
> $ odo create nodejs node-todo
>  ✗  accepts between 0 and 1 arg when using existing devfile, received 2
> ```

there should be an error but its the wrong kind
