### ISSUE TITLE
Expand E2E test case coverage - Creating multicomponent applications with odo

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#4356]
/kind user-story

## User Story
Create end-to-end scenario to cover creation of multicomponent applications

## Acceptance Criteria 
- [ ] At least two components are created and linked 
- [ ] for this story will cover s2i components as linking devfile components is not supported at this time (as per Dharmit's comment below)

/kind user-story

**Comment by dharmit** [comment]
> [ ] At least two components are linked

If this means using `odo link` to link two devfile components, I'm afraid it's not implmented yet. It's being tracked in #3423 which is waiting on #4159 which is blocked on https://github.com/devfile/api/issues/216.

Hopefully I'm wrong. :crossed_fingers:

**Comment by rnapoles-rh** [comment]
I am starting with s2i components which I tried to link manually and works as expected Thanks for pointing out that devfile components linking is not implemented yet. I will create the corresponding tests when supported.

**Comment by dharmit** [comment]
> I am starting with s2i components which I tried with `odo link` manually and works as expected

We're not going to have an explicit s2i component once #4281 is addressed. And, AFAIK, @girishramnani has already started working on it.

What we'll have after that is addressed is odo automagically creating devfile.yaml for the user when they do `odo create --s2i`. So I'm not sure how much value will be added if we try to expand test scenarios for `odo link` between s2i components.

**Comment by rnapoles-rh** [comment]
@dharmit thanks for pointing that. Closing it base on your input.
