### ISSUE TITLE
Watch mode doesn't support debug command

### ISSUE THREAD

**Issue by ehsavoie** [openshift/odo#4357]
/kind feature

## Which functionality do you think we should add?
**odo watch** should be able to use debug kind commands
so the **'--debug'** flag and **'debug-command'** parameter should be added to the **odo watch** command

## Why is this needed?
Currently when doing *odo watch* you can't specify the debug command to use. Specifying the command as *run-command* is not working so we don't have a workaround.

**Comment by mik-dass** [comment]
Currently if the component was pushed in debug mode, `odo watch` will also run in debug mode
```
[mrinaldas@localhost project]$ odo push --debug

Validation
 ✓  Validating the devfile [64989ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [8ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs
 ✓  Checking file changes for pushing [588158ns]

Executing devfile commands for component nodejs
 ✓  Executing install command "npm install" [2s]
 ✓  Executing debug command "npm run debug" [1s]

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component

[mrinaldas@localhost project]$ odo watch
Component is running in debug mode
Please start port-forwarding in a different terminal
Waiting for something to change in /home/mrinaldas/project
```

**Comment by kadel** [comment]
> Currently if the component was pushed in debug mode, `odo watch` will also run in debug mode

what if you need to specify a custom debug command? like `odo push --debug-command my-other-debug`?

**Comment by mik-dass** [comment]
> what if you need to specify a custom debug command? like odo push --debug-command my-other-debug?

We currently can push with a custom debug command `odo push --debug-command my-other-debug` and `odo watch` will use the given debug command.

**Comment by mik-dass** [comment]
Here's a older discussion regarding the flag https://github.com/openshift/odo/issues/3480

**Comment by kadel** [comment]
> We can currently push with a custom debug command `odo push --debug-command my-other-debug` and `odo watch` will use the given debug command.

I see. But from the user's point of view, this is a little bit confusing.
If you want to change `run` or `build` command for `odo watch` you do `odo watch --run-command --build-command`. 
But if you want to change `debug` command you have to do first `odo push --debug-command` and than run `odo watch`.

Running `odo push --run-command run2  --build-command build` and then `odo watch` results in `watch` using the default `run` and `build` commands not the ones specified in `odo push` command.

We should create a unified experience. What we are doing with `debug` command makes sense (`odo push` defines how it is supposed to be run, for both `odo push` and `odo watch`. 

This means that we will have to remove `--run-command` and `--build-command` from `odo watch` make sure that `odo watch` executes the same commands as prvious `odo push`  did.

**Comment by dharmit** [comment]
Above all, we need more documentation to avoid confusion. Let's not simply rely on `odo push -h` and/or `odo watch -h`. I'd go one step further and request a documentation based on how things are right now. As far as I can see, there's no doc explaining how to use `--run-command` and `--build-command` in the repo. Correct me if I'm wrong.

> > We can currently push with a custom debug command `odo push --debug-command my-other-debug` and `odo watch` will use the given debug command.
> 
> I see. But from the user's point of view, this is a bit confusing.

Can you point what's confusing? I'm asking because the same steps have been documented on [odo website](https://odo.dev/docs/debugging-using-devfile/), and I'd like to ensure we capture what needs to be improved to eliminate confusion.

**Comment by ehsavoie** [comment]
As a user, I got confused by the fact that you can provide 'run-command' and 'build-command' with 'watch' but not 'debug-command'. So I was wondering how to debug with 'watch' on. The steps to debug on the odo website were useful, but they don't cover the watch mode.

**Comment by mik-dass** [comment]
> We can currently push with a custom debug command odo push --debug-command my-other-debug and odo watch will use the given debug command.

My bad, `odo watch` doesn't use the previous used debug command during `odo push` and thus we should add `--debug-command` to `odo watch` for a unified experience.

But according to the discussion https://github.com/openshift/odo/issues/3480 we decided against adding `--debug` flag to `odo watch`. Currently `odo watch` runs in debug mode if the component was pushed using `odo push --debug`.

**Comment by dharmit** [comment]
@ehsavoie can you PTAL if `odo watch` with debug support looks more clear than it did earlier? Also, if you face any issues/confusion while following the docs (CLI docs or those on [odo.dev](https://odo.dev) website), please open an issue to let us know.

**Comment by ehsavoie** [comment]
I will take a look next week
