### ISSUE TITLE
build command should be optional

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4363]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
devfile without default build command

```
▶ odo push

Validation
 ✗  Validating the devfile [222784ns]
 ✗  Failed to start component with name java-jboss-eap-xp. Error: Failed to create the component: failed to validate devfile build and run commands:
there should be exactly one default command for command group build, currently, there is no default command
```

## Expected behavior
Odo should not fail in this case. default build command should be optional. 
In that case, should simply skip the build step. There are valid use cases for this. For example, some of the interpreted languages don't require a build step, or some frameworks with hot reload can handle rebuilds themself.

 
/bug 
/priority high

**Comment by girishramnani** [comment]
I can probably look into this?

**Comment by girishramnani** [comment]
should we also warn with message if there are multiple build commands present but non is set as `default`

**Comment by girishramnani** [comment]
we shouldn't show the warning if there are no `build` commands specified as they would become optional

**Comment by kadel** [comment]
> should we also warn with message if there are multiple build commands present but non is set as `default`

yes, it makes sense to show a warning. Multiple build commands with no default is a perfectly valid scenario. But it might also a case that someone simply forgot to set default. Showing warning makes a lot of sense.


> we shouldn't show the warning if there are no `build` commands specified as they would become optional

+1

**Comment by mik-dass** [comment]
`validateCommandsForGroup()` https://github.com/openshift/odo/blob/ede98da442cdfdd8691a9b7ba4b3421f5507bb33/pkg/devfile/adapters/common/command.go#L70 should return a error type which would be handled and ignored if the error is of `no default type` by `GetBuildCommand()` https://github.com/openshift/odo/blob/ede98da442cdfdd8691a9b7ba4b3421f5507bb33/pkg/devfile/adapters/common/command.go#L167
