### ISSUE TITLE
Document the support for PersistentVolumeClaim to store component code

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4371]
/kind documentation
/area storage

## What mistake did you find / what is missing in the documentation?
We don't have documentation for using the preference `Ephemeral` that we added in #3775.

## What is the relevance of it?
Users now have the ability to toggle between using either `emptyDir` (Ephemeral) or `PersistentVolume` backed storages. However, it's not documented clearly.

## Additional notes
We should clarify what storage backends are supported by odo or how user can use a different storage backend since introducing PVC as default storage led to confusion to users which is covered in https://github.com/openshift/odo/issues/4331.

**Comment by boczkowska** [comment]
@dharmit I've created a draft here, PTAL https://github.com/openshift/openshift-docs/pull/29492
