### ISSUE TITLE
Verify automation process to run windows tests on PSI

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4379]
/kind user-story

## User Story
As a QE I want to analyse/research on the process to run windows tests using PSI

## Acceptance Criteria 
- [x] Manually verify the flow to automate the process
- [x] Resolve the blockers, if any

## Links 
- Feature Request: NA
- Related issue: https://github.com/openshift/odo/issues/2540 

/kind user-story

**Comment by anandrkskd** [comment]
So the scope of this issue will be:

- [ ] Create a windows friendly 
  - setup script
  - run script
- [ ] A prow job for windows 
- [ ] send queues corresponding the jenkins jobs in rabbit mq
- [ ] Create jenkins job for windows
