### ISSUE TITLE
odo v2.0.4 has invalid 'zip' format for windows tar.gz archive 

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4386]
/kind bug

## What versions of software are you using?

**Output of `odo version`:** 2.0.4

```
$ file out/tools-cache/odo-windows-amd64.exe.tar.gz 
out/tools-cache/odo-windows-amd64.exe.tar.gz: Zip archive data, at least v2.0 to extract
$ file out/tools-cache/odo-darwin-amd64.tar.gz 
out/tools-cache/odo-darwin-amd64.tar.gz: gzip compressed data, was "/mnt/redhat/staging-cds/developer/odo/2.0.4-1/signed/macos/odo-darwin-amd64.tar", last modified: Thu Jan 21 09:28:27 2021, max compression, original size modulo 2^32 54589440
$ file out/tools-cache/odo-linux-amd64.tar.gz 
out/tools-cache/odo-linux-amd64.tar.gz: gzip compressed data, last modified: Wed Jan 20 09:51:55 2021, from Unix, original size modulo 2^32 48527360
$
```

**Comment by dgolovin** [comment]
@kadel @jeffmaury this is not issue for vscode-openshift-connector, but for IntelliJ plug-in it could be an issue because it downloads odo at runtime. lt will fail when unpacking zip archive as a tag.gz (gzip) archive. 

It should be named odo-windows-amd64.exe.zip or file format should be changed to real tar.gz archive.

**Comment by dgolovin** [comment]
CC: @sbouchet

**Comment by mohammedzee1000** [comment]
My guess now is the mess up happened during signing

**Comment by mohammedzee1000** [comment]
Yes, can confirm this is an issue with signing scripts. That is all I can say. Have informed relevant teams about the issue.
