### ISSUE TITLE
`odo login` overwrites the current active project/namespace

### ISSUE THREAD

**Issue by mcouliba** [openshift/odo#4387]
/kind bug

## What versions of software are you using?

**Operating System:**

MacosX

**Output of `odo version`:**

odo v2.0.4 (ffb7d79aa)

## How did you run odo exactly?

`odo login`
`odo project create my-project`
`odo project get`
`odo login`
`odo project get`

## Actual behavior

The outcome of the last `odo project get` is the first project listed by `odo project list` command.

## Expected behavior

The outcome of the last `odo project get` should be the active project (the project I just created) ie `my-project`

**Comment by dharmit** [comment]
Marking closed since the PR is merged.

/close
