### ISSUE TITLE
Refactor Devfile Volumes for devfile/library

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#4397]
The volume specific code and logic are the only remaining pieces of odo code that is remaining to be refactored and moved out to devfile/library so that all the devfile consumers may use it. This was marked as a [second pass](https://docs.google.com/document/d/1ffLi37fM7LAjRK5SXAw-yVNwr9GchFYy_e_5VD-FOZc/edit?skip_itp2_check=true&pli=1#heading=h.v1ex47x85625) and needs be moved out.

These functions have been identified that are related to the devfile volume logic:
- pkg/devfile/adapters/common/utils.go GetVolumes()
- pkg/devfile/adapters/kubernetes/component/adapter.go volumeNameToPVCName, uniqueStorages logic
- pkg/devfile/adapters/kubernetes/storage/utils.go GetPVCAndVolumeMount(), getPVC(), addVolumeMountToContainers(), generateVolumeNameFromPVC(), GeneratePVCNameFromDevfileVol
- pkg/envinfo/storage.go GetVolumeMountPath()

The only minor issue i see is, devfile tools/consumers not liking the way a pvc name is defined. That may need to be taken into consideration when refactoring these logic

Parent Issue: https://github.com/devfile/api/issues/181

**Comment by maysunfaisal** [comment]
This issue refactors and cleans up the odo code before migrating to devfile/library. The devfile/library issue to track is https://github.com/devfile/api/issues/181

**Comment by dharmit** [comment]
@maysunfaisal do you want this to be tracked via a Sprint board of odo project? I'm fine by whatever you would prefer. I'm asking because Sprint 200 is nearing closure and I was wondering if you would want to move this to 201.

**Comment by maysunfaisal** [comment]
@dharmit this issue is done, there was a typo and the PR didnt close the issue
