### ISSUE TITLE
Remove docker specific code from certain packages

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4404]
In odo contributors' call dated [12 Jan 2021](https://docs.google.com/document/d/1M7iakRFuyHm2E8M6iLKMebX8bhcpIyQitiLglG1xPUI/edit#heading=h.xnbmwfrajz1s), it was discussed and agreed upon to remove docker specific code from certain packages.

/kind cleanup
/kind discussion
/area local

**Comment by dharmit** [comment]
ping @kadel @mik-dass can we please list the places where we need to remove this code from? I'm hoping we could make this into a `/good-first-issue`.

**Comment by kadel** [comment]
If I remember correctly this is about removing `pkg/devfile/adapters/docker` and `pkg/lclient` packages.

**Comment by mik-dass** [comment]
> If I remember correctly this is about removing pkg/devfile/adapters/docker and pkg/lclient packages.

Yes and also the CLI packages where we are checking the condition `pushTarget=docker` needs to be cleaned too.
