### ISSUE TITLE
Automate integration and unit test for windows on PSI

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#4412]
/kind user-story

## User Story
As a QE I want to automate both integration and unit test on Windows.

## Acceptance Criteria 
- [ ] Automate the test for Windows.
- [ ] Resolve the blockers, if any.

## Links 
- Feature Request: N/A
- Related issue: https://github.com/openshift/odo/issues/4379 , #2540

/kind user-story

**Comment by anandrkskd** [comment]
/kind area/testing
/kind area/windows

List of acceptance criteria
https://github.com/openshift/odo/issues/4379#issuecomment-769066687

**Comment by anandrkskd** [comment]
/area testing
/area windows

List of acceptance criteria
https://github.com/openshift/odo/issues/4379#issuecomment-769066687

**Comment by anandrkskd** [comment]
Below are some steps needed to be done to move Tests on windows PSI for sprint 198:
- [ ] Fix gcc library issue on windows
- [ ] Run Unit test

**Comment by anandrkskd** [comment]
Windows Jobs on jenkins are failing due to 
- scripts,
- Golang related issue `cannot install, GOBIN must be an absolute path` but its already set .
Need to check why tests are getting triggered, when it is not involved in the release repo, same as macos jobs.

**Comment by anandrkskd** [comment]
The above failures are resolved, As the previous PSI cluster was 4.5, tests were failing for operatorhub tests and some service related test. Until the new 4.7 cluster is online, I will test it on local for 4.7 for my PR if the tests are failing or passing.

**Comment by anandrkskd** [comment]
For e2e test:
- There are some tests that are failing because of `4min timeout`,  some test are failing due to `Could not get the latest release information in time. Never mind, exiting gracefully :)` 
For unit test:
- added a new make target for unit test that will not using `-race` flag

**Comment by anandrkskd** [comment]
failures faced in Windows tests:
1. Under TestIntegration  `should build when a file and a folder is renamed in the directory`
```
odo push command tests
[ssh:Windows 10] [1] C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/cmd_push_test.go:15
[ssh:Windows 10] [1]   when push command is executed
[ssh:Windows 10] [1]   C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/cmd_push_test.go:76
[ssh:Windows 10] [1]     should build when a file and a folder is renamed in the directory [It]
[ssh:Windows 10] [1]     C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/cmd_push_test.go:114
[ssh:Windows 10] [1] 
[ssh:Windows 10] [1]     Unexpected error:
[ssh:Windows 10] [1]         <*os.LinkError | 0xc00096d440>: {
[ssh:Windows 10] [1]             Op: "rename",
[ssh:Windows 10] [1]             Old: "C:\\Users\\Admin\\923769850\\README.md",
[ssh:Windows 10] [1]             New: "C:\\Users\\Admin\\923769850\\NEW-FILE.md",
[ssh:Windows 10] [1]             Err: 0x20,
[ssh:Windows 10] [1]         }
[ssh:Windows 10] [1]         rename C:\Users\Admin\923769850\README.md C:\Users\Admin\923769850\NEW-FILE.md: The process cannot access the file because it is being used by another process.
[ssh:Windows 10] [1]     occurred
[ssh:Windows 10] [1] 
[ssh:Windows 10] [1]     C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/helper/helper_filesystem.go:90
```
2. under TestDevfiles , should only extract the specified path in the subDir field 
```
[ssh:Windows 10] [2] + Failure [2.884 seconds]
[ssh:Windows 10] [2] odo devfile create command tests
[ssh:Windows 10] [2] C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:19
[ssh:Windows 10] [2]   When executing odo create with devfile component, --starter flag and subDir has a valid value
[ssh:Windows 10] [2]   C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:457
[ssh:Windows 10] [2]     should only extract the specified path in the subDir field [It]
[ssh:Windows 10] [2]     C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:458
[ssh:Windows 10] [2] 
[ssh:Windows 10] [2]     No future change is possible.  Bailing out early after 0.736s.
[ssh:Windows 10] [2]     Running odo.exe with args [odo create gtjegy --project cmd-devfile-create-test458ugj --starter]
[ssh:Windows 10] [2]     Expected
[ssh:Windows 10] [2]         <int>: 1
[ssh:Windows 10] [2]     to match exit code:
[ssh:Windows 10] [2]         <int>: 0
[ssh:Windows 10] [2] 
[ssh:Windows 10] [2]     C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/helper/helper_run.go:34
```
3. under TestDevfiles , should successfully create the devfile component and show json output for a unreachable cluster  
```
[ssh:Windows 10] [2] + Failure [112.790 seconds]
[ssh:Windows 10] [2] odo devfile create command tests
[ssh:Windows 10] [2] C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:19
[ssh:Windows 10] [2]   When executing odo create with devfile component type argument and --context flag
[ssh:Windows 10] [2]   C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:79
[ssh:Windows 10] [2]     should successfully create the devfile component and show json output for a unreachable cluster [It]
[ssh:Windows 10] [2]     C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:137
[ssh:Windows 10] [2] 
[ssh:Windows 10] [2]     Expected
[ssh:Windows 10] [2]         <*os.PathError | 0xc000ff1530>: {
[ssh:Windows 10] [2]             Op: "remove",
[ssh:Windows 10] [2]             Path: "C:\\Users\\Admin\\011921268\\newKUBECONFIG",
[ssh:Windows 10] [2]             Err: 0x20,
[ssh:Windows 10] [2]         }
[ssh:Windows 10] [2]     to be nil
[ssh:Windows 10] [2] 
[ssh:Windows 10] [2]     C:/Users/Admin/amqp_ci_rcv_odo-windows-e2e-pr-build_PR_4658/repo/tests/integration/devfile/cmd_devfile_create_test.go:161
```
4. https://github.com/openshift/odo/pull/4658#issuecomment-826821065

**Comment by anandrkskd** [comment]
scope for sprint 201:
- fix operatorhub tests, e2e tests and failures on https://github.com/openshift/odo/issues/4412#issuecomment-831208815

**Comment by anandrkskd** [comment]
Tests on Windows is failing due to 
- https://github.com/openshift/odo/issues/2877 / https://github.com/openshift/odo/issues/3256 
   These are flakes, number of flakes was reduced if we are increasing the build timeout.
- https://github.com/openshift/odo/issues/4727

**Comment by anandrkskd** [comment]
Scope for sprint 201:
- Ensure parallel run on mac and windows don't fail due to resource
- Create PR on release repo to start testing on PRs

**Comment by dharmit** [comment]
@rnapoles-rh is working on setting up OCP cluster on IBM Cloud. Once that's up, point the Windows & macOS tests to use that cluster instead of PSI.

Need to figure out a way to create an equivalent of `developer` account on OCP on IBM Cloud.

**Comment by anandrkskd** [comment]
Scope of the issue:

- [ ] merge https://github.com/openshift/odo/pull/4873
- [ ] merge https://github.com/openshift/odo/pull/4877
- [ ] Run tests using jenkins
- [ ] create job on prow for windows test

**Comment by anandrkskd** [comment]
This issue is dependent on 
- [ ] https://github.com/openshift/odo/issues/4944 
- [ ] https://github.com/openshift/odo/issues/4800

**Comment by dharmit** [comment]
Those two issues are likely going to take majority of the sprint. Also, what about enabling these tests on PSI setup till IBM cloud is ready for switchover?

**Comment by anandrkskd** [comment]
I am now thinking to make an if else case in the test script and setup env according to PSI or IBM cloud.
so that we will have a working script for PSI as well as the IBM one.

**Comment by dharmit** [comment]
I don't know about the code around this, but on many calls we've discussed that we should simply be able to switchover to IBM Cloud when it's ready. We have also discussed using or try using whatever infra we have available at the moment - which is currently PSI.

If..else or no if..else, IMO the tests should ideally be able to run on any infra that we provide to it.

**Comment by anandrkskd** [comment]
Before we were able to run tests on PSI and it was working with only one failure that is https://github.com/openshift/odo/issues/3256 and @prietyc123 did all the research on it arrived at conclusion that the issue can be PSI network instability. As we decided to use IBM Cloud for test there was some changes needed in the script. due to which we are currently not able to run test on PSI using those script I will update the script and test it once with the PSI as Tomas said on the call.

**Comment by dharmit** [comment]
> As we decided to use IBM Cloud for test there was some changes needed in the script. due to which we are currently not able to run test on PSI using those script I will update the script and test it once with the PSI as Tomas said on the call.

Were these "some changes" documented somewhere? I'm asking because that would help you / @prietyc123 / @rnapoles-rh quickly figure what needs to be done when you actually do it.

On the call, we discussed running these tests on PSI till the time IBM Cloud is available for use.

**Comment by anandrkskd** [comment]
>Were these "some changes" documented somewhere? I'm asking because that would help you / @prietyc123 / @rnapoles-rh quickly figure what needs to be done when you actually do it.

No, I will document it.
> On the call, we discussed running these tests on PSI till the time IBM Cloud is available for use.

yes, I will check if this https://github.com/openshift/odo/issues/3256 issue still a problem for us, as @prietyc123 said last update from PSI team mentioned network issue is resolved.
If it is resolved we can use PSI cluster for time being.

**Comment by anandrkskd** [comment]
> I will check if this #3256 issue still a problem for us

we are still facing this #3256 issue on PSI

**Comment by anandrkskd** [comment]
Steps Done for IBMCloud 

- [ ] jenkins job configured for IBMCloud
- [ ] tested on jenkins with temporary login
- [ ] scripts required for test

need to be Done
- [ ] prow job
- [ ] setting up env vars for IBMcloud login and cluster login

**Comment by anandrkskd** [comment]
Acceptance criteria
- [ ] create job on prow for windows test
- [ ] Create a file for reference of Ibmcloud varriable
- [ ] update IBMCloud vars on Jenkins
