### ISSUE TITLE
Exception encountered when running odo link on minikube

### ISSUE THREAD

**Issue by ajm01** [openshift/odo#4431]
/kind bug

## What versions of software are you using?

**Operating System:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Kubernetes v1.20.2 on Docker 20.10.2

**Output of `odo version`:**
odo v2.0.4 (5544b25ec)

## How did you run odo exactly?
After listing an available service:
```
root@unwisest1:~/odoprojects/application-stack-samples/jpa# odo service list
NAME                   AGE
Database/database3     6m35s
```

I then attempted  to link to that service:
`root@unwisest1:~/odoprojects/application-stack-samples/jpa# odo link Database/database3`

## Actual behavior
Exception is raised when issuing the odo link.

## Expected behavior
odo link is successful

## Any logs, error output, etc?
Exception raised:
```
root@unwisest1:~/odoprojects/application-stack-samples/jpa# odo link Database/database3
panic: runtime error: index out of range [2] with length 1
goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/cli/component.(*commonLinkOptions).complete(0xc000305680, 0xc0006a0510, 0x4, 0xc00019b180, 0xc00076e290, 0x1, 0x1, 0x1682b9a, 0xc0006a0510)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_link.go:138 +0xfe6
github.com/openshift/odo/pkg/odo/cli/component.(*LinkOptions).Complete(0xc0006b35c0, 0xc0006a0510, 0x4, 0xc00019b180, 0xc00076e290, 0x1, 0x1, 0xc000140800, 0x1e66f93)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:100 +0x121
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2208960, 0xc0006b35c0, 0xc00019b180, 0xc00076e290, 0x1, 0x1)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:29 +0xb8
github.com/openshift/odo/pkg/odo/cli/component.NewCmdLink.func1(0xc00019b180, 0xc00076e290, 0x1, 0x1)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:158 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc00019b180, 0xc00076e270, 0x1, 0x1, 0xc00019b180, 0xc00076e270)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a6280, 0x1fac418, 0xc00010efc0, 0x2)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x32a
root@unwisest1:~/odoprojects/application-stack-samples/jpa#
```

**Comment by dharmit** [comment]
@ajm01 I tried to reproduce this on both CRC and minikube. I followed below steps:

* On CRC, the Operator was available through the Operator Hub interface. On minikube, I installed it from the [Operator's page on operatorhub.io](https://operatorhub.io/operator/postgresql-operator-dev4devs-com) website.
* I started the service with the command: `odo service create postgresql-operator.v0.1.1/Database`.
* Next I linked the service to my component and pushed the component.
* Overall, things worked for me. Here's shell output:
    ```sh
    $ odo service create postgresql-operator.v0.1.1/Database          
        
    $ kubectl get pods
    NAME                                  READY   STATUS              RESTARTS   AGE
    database-677bc5dbb6-kldf2             0/1     ContainerCreating   0          11s        <---- this belongs to service we started
    postgresql-operator-c54c98f79-95qjl   1/1     Running             0          83s        <---- this belongs to the Operator we installed
    
    # Checked again after some time
    $ kubectl get pods
    NAME                                  READY   STATUS    RESTARTS   AGE
    database-677bc5dbb6-kldf2             1/1     Running   1          2m17s
    postgresql-operator-c54c98f79-95qjl   1/1     Running   0          3m29s
    
    $ odo link Database/database
     ✓  Successfully created link between component "node" and service "Database/database"
    
    To apply the link, please use `odo push`
    
    $ odo push
    ```

* Lastly, I checked if the env var was injected in the component's pod:
    ```sh
    # this is the secret created by SBO
    $ kubectl describe secrets node-database-database 
    Name:         node-database-database
    Namespace:    default
    Labels:       <none>
    Annotations:  <none>
    
    Type:  Opaque
    
    Data
    ====
    DATABASE_CLUSTERIP:  13 bytes  <--- this is the env var we should look for in component's pod
    
    $ kubectl exec node-68757bc9d7-rwgc4 -- env | grep CLUSTER 
    DATABASE_CLUSTERIP=10.99.183.208
    ```

**Comment by ajm01** [comment]
Thanks Dharmit - 

Based on your success, I got myself a clean linux vm and tried this again from the beginning, but I continue to hit the exception on the new machine as well. I don't know what might be broken in my process, but still cannot get link to work against minikube on linux:

```Service "Database/sampledatabase" has been successfully deleted
[root@pappuses1 jpa]# odo service create postgresql-operator.v0.1.1/Database
Deploying service of type: Database
 ✓  Deploying service [8ms]
 ✓  Service 'database' was created

Progress of the provisioning will not be reported and might take a long time
You can see the current status by executing 'odo service list'
Optionally, link postgresql-operator.v0.1.1 to your component by running: 'odo link <component-name>'
[root@pappuses1 jpa]# odo link Database/database
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/cli/component.(*commonLinkOptions).complete(0xc0005c6960, 0xc00016a480, 0x4, 0xc0005e0500, 0xc0008920d0, 0x1, 0x1, 0x180348a, 0xc00016a480)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_link.go:138 +0xfe6
github.com/openshift/odo/pkg/odo/cli/component.(*LinkOptions).Complete(0xc000410fe0, 0xc00016a480, 0x4, 0xc0005e0500, 0xc0008920d0, 0x1, 0x1, 0xc000622100, 0x1e688b3)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:100 +0x121
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2207e00, 0xc000410fe0, 0xc0005e0500, 0xc0008920d0, 0x1, 0x1)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:29 +0xb8
github.com/openshift/odo/pkg/odo/cli/component.NewCmdLink.func1(0xc0005e0500, 0xc0008920d0, 0x1, 0x1)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:158 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0005e0500, 0xc0008920b0, 0x1, 0x1, 0xc0005e0500, 0xc0008920b0)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000164c80, 0x1faddf8, 0xc0008a6000, 0x2)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x32a
[root@pappuses1 jpa]# ```

**Comment by kadel** [comment]
@dharmit  I didn't try to reproduce this but I think that the Go panic trace provides enough information to know what is happening. 

It is panicking on this line
https://github.com/openshift/odo/blob/5544b25ec083506393090faad5b4205126e4f675/pkg/odo/cli/component/common_link.go#L138
and from the error panic message, you see that the `deploymentSelfLinkSplit` array has length 1, but in the code you are trying to read the second item.

The array is created from this split https://github.com/openshift/odo/blob/5544b25ec083506393090faad5b4205126e4f675/pkg/odo/cli/component/common_link.go#L133
And if the length is 1 that means that `deployment.SelfLink` doesn't have any `/` or it is empty. 

Checking comments for `deployment.SelfLink` gives a pretty good idea of what is happening. 

https://github.com/openshift/odo/blob/5544b25ec083506393090faad5b4205126e4f675/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L65-L69

@ajm01 is using Kubernetes 1.20 and I guess that your minikube is running a Kubernetes < 1.20. and the current CRC version is definitely not based on 1.20.

**Comment by ajm01** [comment]
Hi

Based on Tomas' comments I went forward and downgraded my kubernetes to 1.19.x and indeed I can confirm that my scenario on minikube (using docker as the driver as i had been doing) does now work with odo link - I am able to create the link using odo:

```[root@pappuses1 jpa]# odo link Database/database
 ✓  Successfully created link between component "mysboproj" and service "Database/database"

To apply the link, please use `odo push`
[root@pappuses1 jpa]# odo push```

**Comment by ajm01** [comment]
The sample application is now working fully on minikube with kubernetes v1.19.8

I have documented the current process here:
https://github.com/ajm01/application-stack-samples/blob/minikube-readme/jpa/README-minikube.md

**Comment by dharmit** [comment]
@kadel thanks for helping me out there. I hadn't looked at it from this POV. I guess this also means we will have to modify odo before the issue faced by Andrew becomes a widespread problem for odo users.

@ajm01 thanks for sharing the doc! I followed it and made a few changes so that a user can use more odo commands wherever possible and less kubectl commands as a result. PTAL [this forked README](https://github.com/dharmit/application-stack-samples/blob/minikube-readme/jpa/README-minikube.md). If you'd like, I can open a PR on your repo.

**Comment by ajm01** [comment]
@dharmit - I looked it over, looks good to me - thanks for streamlining the database creation process using odo and the --dryrun flag.  You can send me a PR and I will add it in. I will fix up some of the broken image links etc after i get your version merged.

**Comment by kadel** [comment]
> @kadel thanks for helping me out there. I hadn't looked at it from this POV. I guess this also means we will have to modify odo before the issue faced by Andrew becomes a widespread problem for odo users.

yes, we need to fix it

**Comment by dharmit** [comment]
Reproducible on 4.8. Makes case for having https://github.com/openshift/odo/issues/4503 stronger!
```sh
$ odo link EtcdCluster/example
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/cli/component.(*commonLinkOptions).complete(0xc000788f00, 0xc00067c480, 0x4, 0xc000790500, 0xc0007d30f0, 0x1, 0x1, 0x162ac5a, 0xc00067c480)
	/home/dshah/go/src/github.com/openshift/odo/pkg/odo/cli/component/common_link.go:142 +0x1029
github.com/openshift/odo/pkg/odo/cli/component.(*LinkOptions).Complete(0xc000644f20, 0xc00067c480, 0x4, 0xc000790500, 0xc0007d30f0, 0x1, 0x1, 0xc000798300, 0x1f793f6)
	/home/dshah/go/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:100 +0x121
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2332a60, 0xc000644f20, 0xc000790500, 0xc0007d30f0, 0x1, 0x1)
	/home/dshah/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:29 +0xb8
github.com/openshift/odo/pkg/odo/cli/component.NewCmdLink.func1(0xc000790500, 0xc0007d30f0, 0x1, 0x1)
	/home/dshah/go/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:158 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc000790500, 0xc0007d30d0, 0x1, 0x1, 0xc000790500, 0xc0007d30d0)
	/home/dshah/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000670c80, 0x20c7830, 0xc000056360, 0x2)
	/home/dshah/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/dshah/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/home/dshah/go/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x330
```

**Comment by dharmit** [comment]
Currently, we're fetching a deployment from the cluster using https://github.com/openshift/odo/blob/45d4098e3884918de9edca5d148c0be8a34dafa5/pkg/odo/cli/component/common_link.go#L123

I tried looking at things like `deployment.GetObjectKind().GroupVersionKind()`, `deployment.APIVersion`, but couldn't find the information anywhere.

Then I thought that we are trying to link a `Deployment` with a service. In which case we can "hardcode" these values. This would become a problem when we create a `DeploymentConfig` for an odo component, but I don't think that's on the radar any time soon.

So what I'm proposing is to replace https://github.com/openshift/odo/blob/45d4098e3884918de9edca5d148c0be8a34dafa5/pkg/odo/cli/component/common_link.go#L139-L146

with below:
```go
// Populate the application selector field in service binding request
o.serviceBinding.Spec.Application = &servicebinding.Application{
	GroupVersionResource: metav1.GroupVersionResource{
		Group:    "apps",
		Version:  "v1",
		Resource: "deployments" ,
	},
}
```

Would it be OK to hardcode these values?

@kadel @mik-dass WDYT?
