### ISSUE TITLE
Devfile deletion does not respect context

### ISSUE THREAD

**Issue by valaparthvi** [openshift/odo#4437]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 32

**Output of `odo version`:**
odo v2.0.5 (2180507a4)

## How did you run odo exactly?
![Screenshot from 2021-02-16 15-49-43](https://user-images.githubusercontent.com/11015077/108049805-c04e4300-706e-11eb-9878-0686333fc653.png)

## Actual behavior
Listing directory elements - 
![Screenshot from 2021-02-16 15-50-11](https://user-images.githubusercontent.com/11015077/108049830-ca704180-706e-11eb-9b61-5fde38a31c23.png)

Listing odo components - 
![Screenshot from 2021-02-16 15-47-29](https://user-images.githubusercontent.com/11015077/108049841-ce03c880-706e-11eb-9c60-2e52a72026b3.png)

## Expected behavior
devfile.yaml of sub_dir should have been deleted instead of emtpy_dir's. Context should be taken into account while deleting devfile.

**Comment by valaparthvi** [comment]
Looks like a duplicate of - #4135

**Comment by dharmit** [comment]
> Looks like a duplicate of - #4135

I think the same. Also, I don't think we have ever thought of a component inside a component scenario like the one you have tried here.

Since you have reopened this, I'm wondering if you feel that it's not a dupe of #4135.

**Comment by valaparthvi** [comment]
I reopened it because of #4451 which covers cases on similar line but it didn't take `--context` into account. I guess it does turn out to be a duplicate of either 4451 or 4135 in one way or another. I'll close it for now.
