### ISSUE TITLE
odo CI shoud not run "v4.6-e2e-4x-psi" check for Docs PRs

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4439]
Documentation PRs are going through "v4.6-e2e-4x-psi" test even though `skip-ci` is mentioned. I think that we don't have to provide `skip-ci` any more for the CI to skip other checks. We need to make changes to ensure that "v4.6-e2e-4x-psi" and subsequent tests on PSI for 4.7 and so on do not get executed either.

/area testing

**Comment by dharmit** [comment]
@anandrkskd can you help with this?

**Comment by dharmit** [comment]
One such reference of CI running for docs PR is https://github.com/openshift/odo/pull/4434.

**Comment by anandrkskd** [comment]
yes, we don't need to mention `skip-ci` to skip running tests on cluster. I guess the other tests also executed because the current regex only skips any docs related change under `/docs` dir.
And we have not added that on our PSI tests, I will make sure my PR will adds that and skips the tests.

**Comment by prietyc123** [comment]
> And we have not added that on our PSI tests

I think it will get fixed once we add doc check in `v4.6-e2e-4x-psi` job. PR https://github.com/openshift/release/pull/16274 should fix this as well.

**Comment by anandrkskd** [comment]
I have added the required change for this issue on my recent PR as well :( I think we should have a conversation on this @prietyc123

**Comment by prietyc123** [comment]
This has been done by pr https://github.com/openshift/release/pull/16274
