### ISSUE TITLE
exec permissions not preserved in starters

### ISSUE THREAD

**Issue by maxandersen** [openshift/odo#4440]
/kind bug

`odo create java-quarkus --starter`

the resulting files like `mvnw` does not have execute permission set.

Is that a bug in odo or somehow something we can fix/mark in the devfile/starter ?

**Comment by kadel** [comment]
This needs to be fixed in the starter project source code.

**Comment by maxandersen** [comment]
okey, submitted https://github.com/odo-devfiles/quarkus-ex/pull/1

**Comment by kadel** [comment]
/close
 odo-devfiles/quarkus-ex#1

**Comment by maxandersen** [comment]
still an issue.

using zip with https://code.quarkus.io/d?s=98e.Bqi.tqK.Svz&cn=test
it fails with odo but unzip of it works fine.
