### ISSUE TITLE
Be explicit about "odo project" set of commands running against a cluster

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4442]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
Ran set of `odo project` commands:
* `odo project create -h`
* `odo project delete -h`
* `odo project set -h`

## Actual behavior
None of the help messages clearly indicate that they will be run against a kubernetes cluster.

## Expected behavior
Help messages should be clear because odo does most things with "create+push" workflow wherein cluster resources are created only when `odo push` is executed. For commands that would do things on a cluster without `odo push`, this should be clear from help message

/good-first-issue
/area project
/kind bug

**Comment by girishramnani** [comment]
A help message like - `this command directly performs actions on the cluster and doesn't require a push`?

**Comment by dharmit** [comment]
Yeah that would do.
