### ISSUE TITLE
Json output for odo create in devfile flow

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4443]
The JSON output of odo create -o json command should have the same structure as odo create --s2i --o json

Prerequisite for #4281.

Json output needs to have a proper state https://github.com/openshift/odo/issues/4492

**Comment by kadel** [comment]
The JSON output of `odo create -o json` command should have the same structure as `odo create --s2i --o json`
```
odo create nodejs --s2i -o json
{
	"kind": "Component",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"name": "nodejs-odo-tomd",
		"namespace": "tkral-test",
		"creationTimestamp": null
	},
	"spec": {
		"app": "app",
		"type": "nodejs",
		"source": "./",
		"sourceType": "local",
		"ports": [
			"8080/TCP"
		]
	},
	"status": {
		"state": "Not Pushed"
	}
}
```
