### ISSUE TITLE
odo service list is fixed on running on default namespace 

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#4444]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

odo v2.0.4 (5544b25ec)
Kubernetes: v1.19.0+1833054

## How did you run odo exactly?

odo service list seems to run on the "default" namespace no matter what is the currently active project. 
Here is the output I have when running against crc 1.22.0 

```shell
❯ odo project list
ACTIVE     NAME
*          quarkus-test
❯ odo service list
 ✗  clusterserviceversions.operators.coreos.com is forbidden: User "developer" cannot list resource "clusterserviceversions" in API group "operators.coreos.com" in the namespace "default"
❯ k get csv
NAME                              DISPLAY                    VERSION   REPLACES                          PHASE
azure-service-operator.v0.37.0    Azure Service Operator     0.37.0                                      Succeeded
service-binding-operator.v0.4.0   Service Binding Operator   0.4.0     service-binding-operator.v0.3.0   Succeeded
```

**Comment by valaparthvi** [comment]
From what I have seen, if the current directory contains a component, it takes into account the namespace from it .odo/env/env.yaml. But if you run it outside a non-component directory, it will take into account the active namespace. I cannot say for sure whether this is intended or something that happened along the way.

For more details, https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/resolve.go#L61
