### ISSUE TITLE
Document odo installation instructions via "yum" 

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4453]
/kind documentation

## What mistake did you find / what is missing in the documentation?
odo can be installed on a RHEL system using `yum install`. We need to document it for users of RHEL and explore if the same can be documented for Fedora and CentOS users.

## What is the relevance of it?
Relevant for the users of rpm ecosystem.

**Comment by dharmit** [comment]
@mohammedzee1000 can you help here? Do we know which copr/yum repo to enable to install odo on Fedora/RHEL?

**Comment by boczkowska** [comment]
The PR for yum installation https://github.com/openshift/openshift-docs/pull/32298

**Comment by cfergeau** [comment]
> The PR for yum installation [openshift/openshift-docs#32298](https://github.com/openshift/openshift-docs/pull/32298)

This PR has been merged, this can most likely be closed.
