### ISSUE TITLE
Stabilize tests on PSI

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4459]
Our current tests that are executed against PSI are quite unstable. 
The whole purpose of running tests on PSI was to make it more stable and faster than Prow tests.

The last successful run that I can see was a week ago. It failed 32 times in a row.

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-odo-master-v4.6-e2e-4x-psi?buildId=

A few reasons for failures are here?

- Failing tests on PSI - Failed Error: ImagePullBackOff #4454
- Failing tests on PSI - timeout on internal image registry #4458

But I'm sure that there will be many more different errors in logs. 

But as a minimal thing, we need to fix all those connection errors.

**Comment by anandrkskd** [comment]
Issues related to Failing test on PSI:
- component push throws error of waited 4m0s but couldn't find running pod matching selector https://github.com/openshift/odo/issues/2877

**Comment by rnapoles-rh** [comment]
For [failing tests on PSI - Failed Error: ImagePullBackOff #4454](https://github.com/openshift/odo/issues/4454) I ran it locally agains the PSI cluster and it passed. Debugging to try to figure out why this is unstable

**Comment by rnapoles-rh** [comment]
Closing as the related 2 issues. We will keep an eye on stability and reopen if needed once the required scripts for CI are merged
