### ISSUE TITLE
Remove "experimental" from odo preferences

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4461]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master (2.0.5)

## How did you run odo exactly?
`odo preference view`
`odo preference set -h`

## Actual behavior
odo preferences mention `Experimental` mode that was added during the run up to v2 release

## Expected behavior
`Experimental` mode is not being used any more. So odo should remove it.

/good-first-issue
/kind bug

**Comment by kadel** [comment]
/status blocked

Docker support is currently experimetnal, before we  can remove it from preference we need to decide on its fate. 
https://github.com/openshift/odo/issues/4500

**Comment by kadel** [comment]
/reopen
/remove-lifecycle rotten
still a prolem

**Comment by kadel** [comment]
```
▶ odo preference view
PARAMETER             CURRENT_VALUE
UpdateNotification    
NamePrefix            
Timeout               
BuildTimeout          
PushTimeout           
Experimental          
Ephemeral             true
ConsentTelemetry      false
```

There is still `Experimental` config option in odo preference. This option should not be used for anything.

**Comment by dimitraz** [comment]
I'm happy to take this on for Hacktoberfest, if it's still available

**Comment by valaparthvi** [comment]
@dimitraz Thank you for your interest, let me confirm it and get back to you.

@kadel I think we can move this forward, I don't see any reference to Experimental except in its code implementation and some help docs.

**Comment by dharmit** [comment]
@valaparthvi  Should we be adding some hacktoberfest related label to this issue and its PR?
