### ISSUE TITLE
ODO link should allow developers to create link as file

### ISSUE THREAD

**Issue by wtrocki** [openshift/odo#4469]
/kind documentation

Most of the extensions like quarkus will require service binding to be spec compliant (use file structure to mount values). When working with ODO it is not clear/easy/documented. 

Technically custom sbo can be passed but entire concept of linking as file is not well documented.
Having simple parameter or documentation to support as file would support entire story of service binding extensions for tools like quarkus that use those.

**Comment by dharmit** [comment]
Closing since this feature has been implemented.

/close
