### ISSUE TITLE
list available starters instead of saying user is wrong

### ISSUE THREAD

**Issue by maxandersen** [openshift/odo#4481]
/kind bug

## What versions of software are you using?

**Operating System:**
osx

**Output of `odo version`:**
odo v2.0.6 (4f140f98f)

Server: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
Kubernetes: v1.19.0+1833054

## How did you run odo exactly?

`odo create --devfile ../registry/devfiles/java-quarkus/devfile.yaml --starter=getting-started-codequarkus`

## Actual behavior

complains with `the project: getting-started-codequarkus specified in --starter does not exist`
or if none specified it says `There are multiple projects in this devfile but none have been specified in --starter. Downloading the first: community`

## Expected behavior
in both cases it would be awesome if odo would list the other starters found so the user can know what options he has instead of leaving him guessing.

**Comment by kadel** [comment]
> in both cases it would be awesome if odo would list the other starters found so the user can know what options he has instead of leaving him guessing.

There is an option to list the starter projects - `odo catalog describe component java-quarkus`.
But I completely agree with you. It would be much better if the user doesn't have to run another command (especially this log). 
Odo should list available starter projects as part of the error message.

**Comment by girishramnani** [comment]
should we also consider jumping into interactive mode so the user can select the starter if they were not able type it correctly?

**Comment by kadel** [comment]
> should we also consider jumping into interactive mode so the user can select the starter if they were not able type it correctly?

nope, that would make it harder to build scripts around odo. If the user provides an invalid starter it odo needs to error out and return non zero return code.
