### ISSUE TITLE
odo cli builds produces odo-windows-amd64.exe.tar.gz binary

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4485]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
v2.0.6

## How did you run odo exactly?
Verifying odo cli release SHA256_SUM and rpm builds binary

## Actual behavior
odo cli binary has `odo-windows-amd64.exe.tar.gz` extension, however there is no SHASUM available for the same.

## Expected behavior
It should not produce `odo-windows-amd64.exe.tar.gz`

## Any logs, error output, etc?

manually execution

**Comment by kadel** [comment]
/close
it looks like this was resolved in the last release https://mirror.openshift.com/pub/openshift-v4/clients/odo/v2.0.7/ there is no .tar.gz for windows binary, only zip
