### ISSUE TITLE
Disable periodic jobs for all versions except "latest' and "latest - 1"

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4490]
Currently, odo periodic jobs are running for the OCP versions 4.2 through 4.7. However, only the latest (4.7) and one version older than that are supported from features point of view. As of opening this issue:
* 4.7 is the latest and fully supported issue
* 4.6 is also fully supported
* 4.5 is in maintenance mode and release of 4.8 will cause its EOL

When 4.8 is released, 4.6 will enter maintenance mode and release of 4.9 will cause EOL of 4.6. So on and so forth.

Periodically testing odo against versions other than two latest versions (4.7 and 4.6 at the time of writing this) makes no sense. It's as good as wasting resources. We need to disable these periodic jobs.

/area testing
/priority high

**Comment by dharmit** [comment]
For 4.5, disable Operator Hub tests completely due to SBO breaking changes.

**Comment by prietyc123** [comment]
PR https://github.com/openshift/release/pull/16813 will disable unsupported periodic jobs. Plan is to run periodic jobs on all the ocp supported version 4.5, 4.6 and 4.7, also the upcoming version 4.8 . Yes, ofcourse 4.5 will break until 4.8 GA comes out, but thats ok it will only fail for SBO.
