### ISSUE TITLE
Remove docker/local mode related code from odo

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4500]
We have a lot of docker -> local scenerio code present which isn't used anywhere. So we should remove it.

## Acceptance Criteria

- [ ] If there are any references to Docker support in the code, remove it. Few PRs have already been merged (scroll below to see which PRs) for this, so Docker references should be minimal or nil.
- [ ] Remove blocked status on #4461.

**Comment by dharmit** [comment]
Quite a few PRs have been opened to address this item. We now need to figure out if there's anything related to Docker support still lingering around in the code.

Adding this to upcoming sprint so that someone take a look at it.

**Comment by dharmit** [comment]
@feloy you might need to figure out what places in odo code still refer to Docker/local support.

/remove-triage ready

**Comment by feloy** [comment]
The files I can find to be removed are:
- pkg/devfile/adapters/docker/*
- pkg/lclient/*
