### ISSUE TITLE
Use official devfile registry

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4504]
The New Official Devfile registry is running at https://registry.devfile.io/  
Devfiles served by the registry are at https://github.com/devfile/registry

Odo should deprecate and stop using https://github.com/odo-devfiles/registry and use over one instead.

The new registry has a different API, so all commands and function operating on the registry will have to be updated

/priority high
/area registry

**Comment by GeekArthur** [comment]
Related issue from devfile service side: https://github.com/devfile/api/issues/367

**Comment by girishramnani** [comment]
is this the OCI registry with devfile as an manifest type?

**Comment by kadel** [comment]
> is this the OCI registry with devfile as an manifest type?

yes, but OCI registry is just an implementation detail. There is an HTTP REST interface. odo and other tools will interface just with that.

**Comment by GeekArthur** [comment]
All the PRs for OCI-based registry migration are merged, close this issue.
