### ISSUE TITLE
odo link should support providing name of the SBO object

### ISSUE THREAD

**Issue by wtrocki** [openshift/odo#4505]
ServiceBindingOperator plans to use file-based mounted bindings. 
This will mean that name of the service binding objects should be easy to control.

This way odo can be used the same way as service binding objects - creating paths that are expected by devs.

CC @petemuir @sbose78

**Comment by kadel** [comment]
@wtrocki I'm lost :/ Can you point me to some documentation or an example?

**Comment by wtrocki** [comment]
Odo link will create SBO object with `metadata.name` that cannot be specified by end user.

See: https://github.com/redhat-developer/service-binding-operator/issues/893

**Comment by kadel** [comment]
> Odo link will create SBO object with metadata.name that cannot be specified by end user.
Can we change that? Will also discuss the same with OpenShift console team.

That should not be a problem. We could allow users to optionally set a name. It could look like this `odo link Database/database --name  mybinding`

**Comment by wtrocki** [comment]
@kadel no problem. I'm trying to aggregate all those requirements in the ecosystem first and prioritize them. Already checked the code and see that this will be trivial to add so I can either do it myself after some time or someone from odo core team can pick that up. Thank you.

**Comment by kadel** [comment]
I've created user story to cover this issue https://github.com/openshift/odo/issues/4693

**Comment by dharmit** [comment]
> I've created user story to cover this issue #4693

Done as a part of this issue.

/close
