### ISSUE TITLE
Fails due to KUBECONIG location

### ISSUE THREAD

**Issue by joshuawilson** [openshift/odo#4510]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 33

**Output of `odo version`:**
2.0.4

## How did you run odo exactly?
Trying to use s2i on Openshift VSCode ext

## Actual behavior
`odo list --app foo --project josh -ojson`

returns:
```
{
        "kind": "Error",
        "apiVersion": "odo.dev/v1alpha1",
        "metadata": {
                "creationTimestamp": null
        },
        "message": "Please specify the application name and project name\nOr use the command from inside a directory containing an odo component."
}
```

I found this is because I have my KUBECONFIG set in an env var and it is not in `~/.kube/config`. When I changed to that location it worked. 

## Expected behavior
Return:
```
{
        "kind": "List",
        "apiVersion": "odo.dev/v1alpha1",
        "metadata": {},
        "s2iComponents": [],
        "devfileComponents": []
}
```

I expect to be able to configure the location of the kubeconfig according to all kubernetes acceptability places.

**Comment by kadel** [comment]
We are using `KUBECONFIG` a lot in our tests and on my local system I also have `KUBECONFIG` set to a different path than `.kube/config`. 

Did you run `odo` command in your "normal" terminal or it was in VSCode integrated terminal?

If you run odo with verbose logging `-v 10` you should where the kube config is loaded from.

```
▶ odo -v 10 list
I0316 10:03:11.849734    3404 preference.go:235] The path for preference file is /home/tomas/.odo/preference.yaml
I0316 10:03:11.850182    3404 util.go:422] path devfile.yaml doesn't exist, skipping it
I0316 10:03:11.850248    3404 list.go:87] New Context
I0316 10:03:11.850297    3404 util.go:727] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
I0316 10:03:11.850362    3404 util.go:748] Response will be cached in /tmp/odohttpcache for 1h0m0s
I0316 10:03:11.850533    3404 util.go:761] Cached response used.
I0316 10:03:11.850890    3404 loader.go:375] Config loaded from file:  /tmp/test/config
```

**Comment by joshuawilson** [comment]
I ran it in both vscode and standard terminal. 
If I have kubeconfig in both locations it works. But if it is missing from `.kube/config` I got that error.

**Comment by joshuawilson** [comment]
Did any of you ever take a look at this?
