### ISSUE TITLE
convert cmd helpers to new CmdRunner

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4517]
/kind feature

## Which functionality do you think we should add?
Currently we have alot of functions in https://github.com/openshift/odo/blob/master/tests/helper/helper_run.go which can be de-duplicated ( they have a lot of common code ). There is some code already that does that using https://github.com/openshift/odo/blob/master/tests/helper/helper_cmd_wrapper.go 

The ideal target functions would be -
- CmdShouldRunAndTerminate
- CmdShouldFail
- CmdShouldFailWithRetry
- CmdShouldRunWithTimeout

## Why is this needed?
If the chaining design pattern is used then the current helper code can be improved significantly, This would allow for better maintainability and extensibility

## Sub Issues (tasks)
- [x] Createing new functions https://github.com/openshift/odo/issues/4694
- [ ] Updating test to use new functions - issue to be created

**Comment by girishramnani** [comment]
The tests should also use the newer CmdRunner so changes to the tests should also be scoped here

**Comment by dharmit** [comment]
@anandrkskd do you have bandwidth to look at this in Sprint 200 or should we move it to 201?

**Comment by anandrkskd** [comment]
As discussed on QE-Dev sync, we decided to completely focus on the PSI test, so I would say we should move issue to sprint 201

**Comment by dharmit** [comment]
> As discussed on QE-Dev sync, we decided to completely focus on the PSI test,

Indeed. But IIRC, your issues were blocked on having an OCP 4.7 cluster on PSI first. So I thought that you might have some spare bandwidth to look into this. However, I guess @rnapoles-rh has got that running as a part of #4515.

**Comment by anandrkskd** [comment]
scope of this issue is:
- Add below functions ( Required logic are already in helper functions )
    - ShouldRunAndTerminate
    - ShouldFail
    - ShouldFailWithRetry
    - ShouldRunWithTimeout
- Replace the helper functions with above Runner functions
- Remove all the helper function that will be replaced from [helper_run.go](https://github.com/openshift/odo/blob/master/tests/helper/helper_run.go)

**Comment by anandrkskd** [comment]
scope of this issue is:

- Replace the helper functions with above Runner functions, in all the test cases
- Remove all the helper function that will be replaced from helper_run.go

**Comment by anandrkskd** [comment]
Breaking down the changes for easy of understanding and tracking
- [ ] e2e-suite
- [ ] test helper
- [ ] integration test
- [ ] integration devfile test
- [ ] debug test
- [ ] login-logout
- [ ] operator hub
- [ ] project
- [ ] service catalog

**Comment by anandrkskd** [comment]
Pr #4788 will partly fix this issue, the follow up PR will remove the tests and updates the `operator hub` and `project` tests with the new runner functions.
