### ISSUE TITLE
Execute ci firewall tests on master for release repo pr

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4522]
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Currently we are fetching prs from odo repo which results release repo jobs to fail.

```
[ssh:Fedora 32] Executing command [git clone https://github.com/openshift/odo amqp_ci_rcv_odo-minikube-pr-build_PR_16852/repo]
[ssh:Fedora 32] Cloning into 'amqp_ci_rcv_odo-minikube-pr-build_PR_16852/repo'...
[ssh:Fedora 32] Executing command [git fetch origin pull/16852/head:pr16852]
[ssh:Fedora 32] fatal: couldn't find remote ref pull/16852/head
```
PR https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16852/rehearse-16852-pull-ci-openshift-odo-master-psi-kubernetes-integration-e2e/1372054632230031360#1:build-log.txt%3A87

## Expected behavior

Run tests on master if its not odo repo

**Comment by prietyc123** [comment]
I did some initial level of analysis and found we are not handling stderr `[ssh:Fedora 32] Executing command [git fetch origin pull/17283/head:pr17283]
[ssh:Fedora 32] fatal: couldn't find remote ref pull/17283/head` in function 
https://github.com/mohammedzee1000/ci-firewall/blob/main/pkg/worker/worker.go#L146-L194 which leaves it with success and nil error msg and executes furthur. I think we need to capture `stderr`, returns error and stop executing further steps in https://github.com/mohammedzee1000/ci-firewall/blob/main/pkg/worker/worker.go#L214 . Once we are done we will start executing our test on odo master branch.

**Comment by mohammedzee1000** [comment]
As we discussed, it is not that stderr is not captured, rather stdout and stderr is combined into single-stream using `io.MultiReader` for logging purpose. Instead, success or fail is returned and used to determine if next command is to be skipped.

What I would recommend is updating the below code, such that
 - failure of fetching pr does not result in skipping of code. Basically, we ignore the status of the git fetch command. We should still store it for 3rd point 
 - the git checkout mainbranch always runs (replace status with `true`)
 - skip the git merge if fetch command failed

https://github.com/mohammedzee1000/ci-firewall/blob/686a62dbce1391859373f7e4c7fd10e8b383715d/pkg/worker/worker.go#L247-L263

**Comment by mohammedzee1000** [comment]
https://github.com/mohammedzee1000/ci-firewall/blob/686a62dbce1391859373f7e4c7fd10e8b383715d/pkg/worker/worker.go#L247-L263

**Comment by prietyc123** [comment]
PR https://github.com/mohammedzee1000/ci-firewall/pull/16 closed this issue.
