### ISSUE TITLE
PushTimeout preference is not being valued for devfiles

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4529]
/kind bug

## What versions of software are you using?

**Operating System:** MacOS

**Output of `odo version`:** odo master

## Expected behavior
For devfile if you set `odo preference set PushTimeout <seconds>` and then try to push a component - it won't timeout after those seconds. but this works for s2i components.

**Comment by girishramnani** [comment]
just so its known - I found this as part of my half day of “exploring odo’s limits”

**Comment by kadel** [comment]
Test had to be commented out because of this in https://github.com/openshift/odo/pull/4518/files#diff-959d7173037ca057614f19d5dec825f383d808739d9d930933a6d6203405d203R33
After this is implemented the test needs to be uncommented.
