### ISSUE TITLE
Migrate csb jenkins to ocp 4.6 cluster

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4532]
/kind user-story

## User Story
As a QE I want to run jenkins as ocp 4.6 inspite of 3.11 to reduce failures on jenkins side

## Acceptance Criteria 
- [ ] Initial research on migration part.
- [ ] Resolving failures and meet the expectation to Onboard on ocp 4.6 

## Links 
- Feature Request: NA
- Related issue: https://issues.redhat.com/browse/ODO-46

/kind user-story

**Comment by prietyc123** [comment]
Tasks needs to be done:

- [ ] Going through doc https://docs.engineering.redhat.com/display/CentralCI/On-boarding+request
- [ ] Understand the whole migration process following https://docs.engineering.redhat.com/display/CentralCI/User+documentation
- [ ] Collect the required data
```
1. State that's this is a migration.
2. Name of your team.
3. Jenkins instance name.
4. Current Jenkins URL.
5. Current Jenkins version.
6. Current JCASC location URL.
7. Name of rover group or groups to be assigned as admins for Jenkins and OpenShift project.
8. Current PVC capacity (`oc get pvc`).
```
- [ ] File a ticket with details
- [ ] Follow up with the central ci tools members 
- [ ] Verify the jenkins url provided by the concerned team

**Comment by prietyc123** [comment]
I was trying to verify the new jenkins url and the console. Console with project name `jenkins-csb-devtoolsodo` is not accessible, it seems the access has not been given to `devtools-odo`. Following up with the ci tool members on this.

```
projects.project.openshift.io "jenkins-csb-devtoolsodo" is forbidden: 
User "pkumari" cannot get resource "projects" in API group "project.openshift.io" in the namespace "jenkins-csb-devtoolsodo"
```

**Comment by prietyc123** [comment]
> it seems the access has not been given to devtools-odo

As per ci-tools member, the group has been given access but problem is that this group is un-synced with OCP4. Already created a ticket on service now and following up on that.

**Comment by prietyc123** [comment]
Blocked due to https://github.com/openshift/odo/issues/4532#issuecomment-824603536

**Comment by dharmit** [comment]
Jenkins part of this issue is working. VMs take a long time to spin up on PSI.
