### ISSUE TITLE
Add ability to reflect service binding type (secret vs filesystem)

### ISSUE THREAD

**Issue by wtrocki** [openshift/odo#4533]
Service binding (odo link) offers ability to connect using bindingAsFile (creates filesystem based on secret) or link as environment variables.

It is crucial for usability to reflect that in odo.

See also
https://github.com/openshift/odo/issues/4505

**Comment by kadel** [comment]
I've created a user story that covers this issue. https://github.com/openshift/odo/issues/4693

**Comment by dharmit** [comment]
> I've created a user story that covers this issue. #4693

`--bind-as-files` has been added as a part of above issue. If you meant something else, please feel free to re-open.

/close
