### ISSUE TITLE
[Discussion] Update version of the ServiceBinding operator from 0.3.0 to 0.5.0

### ISSUE THREAD

**Issue by wtrocki** [openshift/odo#4534]
SBO as dependency is used to build Binding CR, but current version is 0.5.0. 
It will be good to update it to latest version to support bindAsFiles flag.

This blocks:

https://github.com/openshift/odo/issues/4533

**Comment by wtrocki** [comment]
/assign @wtrocki 

This might be controversial but I will see if can bump package

**Comment by dharmit** [comment]
Updated to 0.7.1 - https://github.com/openshift/odo/blob/main/go.mod#L41

/close
