### ISSUE TITLE
Delete more than one project at once

### ISSUE THREAD

**Issue by valaparthvi** [openshift/odo#4556]
/kind feature

## Which functionality do you think we should add?
Delete more than one project at once either.

1. Delete a list of projects separated by space.
```
odo project delete cmd-service-test60xec cmd-service-test60yed cmd-service-test207iab
```
2. Delete projects matching a pattern.
```
odo project delete cmd-service-test-*
```

## Why is this needed?
It is just annoying when I want to delete more than one project and I can only delete 1 at a time.

**Comment by kadel** [comment]
> It is just annoying when I want to delete more than one project and I can only delete 1 at a time.

I understand your use case, but when would normal odo user need that?

**Comment by valaparthvi** [comment]
>I understand your use case (btw, you can use oc or kubectl for that), but when would normal odo user need that?

There isn't any particular use case I can think of. I encountered this while cleaning up my cluster where I had multiple projects I wanted to delete and it was annoying to delete one project at a time via odo, and web console and I was not aware that kubectl and oc could do it easily. I understand this would be a rarely used case, but it can be helpful when people are not aware of kubectl and oc. It is a nice-to-have feature.
