### ISSUE TITLE
Update documentation for ServiceBindingOperator 0.6.0

### ISSUE THREAD

**Issue by wtrocki** [openshift/odo#4559]
/kind documentation

New version of the service binding operator was released that brings significant amount of fixes.
Documentation should recommend this version to be installed etc.

There is no breaking API so changes in the code are unlikely.

https://operatorhub.io/operator/service-binding-operator

**Comment by dharmit** [comment]
I gave a quick try to SBO 0.6.0 on minikube. `odo push` after doing `odo link` failed for me with:
```sh
$ odo push
 ✓  Waiting for component to start [6ms]

Validation
 ✓  Validating the devfile [35774ns]

Creating Kubernetes resources for component node-todo
 ✗  Waiting for component to start [5m] [WARNING x7: Failed]
 ✗  Failed to start component with name node-todo. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for node-todo deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
See below for a list of failed events that occured more than 5 times during deployment:

 NAME                                         COUNT  REASON  MESSAGE                         

 node-todo-7d4c498864-f2nrl.166feae64ccf5756  7      Failed  Error: secret                   
                                                             "node-todo-etcdcluster-example" 
                                                             not found                       
 node-todo-7fdc569f64-xknxl.166fea8f6ff985e9  5      Failed  Error: ImagePullBackOff         

```
I'll give this more time next week. But my initial hunch is that once #4554 helps us get rid of the dependency on the Secret name, we should be in a better position.

**Comment by wtrocki** [comment]
@kadel Secret problem that exists in my PR also popping up in the latest release as seen. 
We are going to use this release in Sandbox. While ODO is not being used in our workshops etc. still anyone using ODO will get failures. 

As for how to make this happen. My take is that ODO tries to do too much and relies on the internal parts of the Service Binding Operator implementation - things like intermediate secret names etc.
Users should be able to assess binding themselves or rely on liveness probes etc.
My take is that removing some specific checks in ODO push will enable us to integrate with SBO without much effort (however it will be somewhat breaking/behaviour change for ODO)

In long run I think we need to work out patterns for collaboration between SBO, Cloud and ODO teams so failures will be detected before releases etc.

**Comment by wtrocki** [comment]
Related issue #4469
