### ISSUE TITLE
Handoff ci-firewall and psi stuff to qe folk

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4582]
Hand off

**Comment by mohammedzee1000** [comment]
Had some discussions with qe folk including 2 walkthroughs

**Comment by mohammedzee1000** [comment]
Completed progress so far
- Had a discussion with QE folk related to the ci-firewall code base
- Added QE as collaborators on ci-firewall repo

On-going:
- helping QE as needed with their issues/pr
- Helping QE get more familiar with how to provision openshift clusters on PSI

Todo:
 - Ensure QE has full know-how about PSi stuff
 - Grant Qe collaborator on internal repos

**Comment by mohammedzee1000** [comment]
@rnapoles-rh is currently working on provisioning newer ocp cluster on psi. This should help ensure at least one other person is amiliar with the process, and the issues that may crop up

**Comment by mohammedzee1000** [comment]
@rnapoles-rh has successfully provisioned a cluster and @prietyc123 has been working on jenkins migration which should help her gain familiarity with the casc setup of csb jenkins on openshift

**Comment by dharmit** [comment]
Is this task over?

**Comment by prietyc123** [comment]
> Is this task over?

yes, we can close this issue.
