### ISSUE TITLE
--now flag for odo config set --env not supported for devfiles

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4594]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

**Comment by kadel** [comment]
Test had to be commented out because of this in https://github.com/openshift/odo/pull/4518/files#diff-f55d1dcfa285f4e2e11df9fce169ec0b4256649e7a7c67ab11e33ed667d6dc8fR317
After this is implemented the test needs to be uncommented.
