### ISSUE TITLE
vm configuration delay leads ssh to fail

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4603]
/kind flake

issue: https://github.com/mohammedzee1000/ci-firewall/issues/19

**Comment by mohammedzee1000** [comment]
This is a openstack delay issue

Adding retry loop for cases where executor itself fails (ssh failure is regarded as that). This will not cover cases where command itself fails.

See a linked issue in ci-firewall for more details

**Comment by mohammedzee1000** [comment]
linked PR has been merged. What remains is making new release of ci-firewall and deploying it

**Comment by mohammedzee1000** [comment]
We have done all we can over here. Any further persistence is outside our control
