### ISSUE TITLE
odo env set DebugPort doesn't work for converted devfile 

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4615]
/kind bug

## What versions of software are you using?

**Operating System:** MacOS

**Output of `odo version`:**

## How did you run odo exactly?
The reason this is not working for an s2i converted devfile because there is not dedicated `debug` command present for s2i converted devfiles and hence the `DebugPort` in env is not respected.

**Comment by girishramnani** [comment]
added a workaround for now https://github.com/openshift/odo/pull/4518#discussion_r613205859

**Comment by girishramnani** [comment]
uncomment the workaround once this issue is fixed

**Comment by dharmit** [comment]
Workaround for this is documented in #4683.

**Comment by girishramnani** [comment]
The ideal fix for this should be to have `debug` command on converted devfile.

**Comment by girishramnani** [comment]
One fix would be to set the `DEBUG_PORT` env variable when someone sets `DebugPort` in localEnvInfo?

**Comment by girishramnani** [comment]
@kadel thoughts on the possible fix^
