### ISSUE TITLE
converted devfiles directly creates a url for you

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4621]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
Currently as there is no equivalent of "ports" in devfile world when an s2i component is converted to a devfile component the ports described by the s2i image are converted to urls. This is a breaking change and can create issues when the s2i component name is quite large.

## Any logs, error output, etc?
```

odo create nodejs --s2i
Validation
 ✓  Validating component [524ms]
Conversion
 ✓  Successfully generated devfile.yaml and env.yaml for provided S2I component

Please use `odo push` command to create the component with source deployed
(base) girish@MacBook-Pro 3453456345 % odo url list
Found the following URLs for component nodejs-x3453456345-bcab
NAME                             STATE          URL     PORT     SECURE     KIND
nodejs-x3453456345-bcab-8080     Not Pushed             8080     false      route

```

**Comment by girishramnani** [comment]
A solution for this problem is implementing support for `exposure: none` kind urls in devfile which are present on the devfile as a reference and only get created when someone change their exposure to `public`.

Currently if a `exposure: none` url is present in the devfile it doesn't list you the url and also doesn't let you create one.

```
% odo url list
 ✗  no URLs found for component nodejs-x3453456345-bcab. Refer `odo url create -h` to add one
% odo url create
 ✗  URL creation failed:
        - url nodejs-x3453456345-bcab-8080 already exist in devfile endpoint entry under container s2i-builder
```

**Comment by kadel** [comment]
> Currently if a `exposure: none` url is present in the devfile it doesn't list you the url and also doesn't let you create one either

this needs to be fixed as well. It could be related to https://github.com/openshift/odo/issues/4493 and solution described in https://github.com/openshift/odo/issues/4493#issuecomment-818667275 should fix this.

**Comment by kadel** [comment]
> This is a breaking change and can create issues when the s2i component name is quite large.

we need to make sure that the component name lenght doesn't affect this.

**Comment by girishramnani** [comment]
The scope of this issue is to make sure the url length doesn't go over 63 chars. Now the length of the url is dependent on the cluster's url so either I keep check the cluster url's length and reduce the url length based on that or just make an educated guess that url length shouldn't be more then 15 chars (example) and the "random chars" show up in the beginning.

Earlier scope was to add `exposure:none` when we are converting ports to urls in s2i but thats actually fine. And even after the convertion of the port to default url the url would fail to create as its length is incorrect so we dont wanna consider this approach.

**Comment by kadel** [comment]
> The scope of this issue is to make sure the url length doesn't go over 63 chars. Now the length of the url is dependent on the cluster's url so either I check the cluster url's length and reduce the url length based on that or just make an educated guess that url length shouldn't be more then 15 chars (example) [part that we control url name] and the "random chars" show up in the beginning.

based on the devfile spec, endpoint name has to be  "string (up to 63 chars) and must match ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ "
when odo generates new endpoint it needs to make sure that the name is valid

**Comment by girishramnani** [comment]
but thats not the only thing, should we reduce its size if overall url becomes too large? like max at 20 chars?

**Comment by girishramnani** [comment]
> > The scope of this issue is to make sure the url length doesn't go over 63 chars. Now the length of the url is dependent on the cluster's url so either I check the cluster url's length and reduce the url length based on that or just make an educated guess that url length shouldn't be more then 15 chars (example) [part that we control url name] and the "random chars" show up in the beginning.
> 
> based on the devfile spec, endpoint name has to be "string (up to 63 chars) and must match `^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ "`
> when odo generates new endpoint it needs to make sure that the name is valid

I could be wrong here but endpoint name would include the cluster url? or its just the name?

**Comment by girishramnani** [comment]
I still dont have an action item on this, 

- should I just the url name be as is? then we can just close this issue.
- should I trim it if it goes beyond a certain characters [ max - 30 chars ] ? - also there is an issue with triming it from right side as the sufix is the random string - which means if I trim it too much we might have conflicting url name. ( as the random string might get trimed )

**Comment by kadel** [comment]
from the original descrption:

> This is a breaking change and can create issues when the s2i component name is quite large.

Creating urls for ports is ok.
It is not ok to create url that has an invalid name. 

This is a situation that you need to prevent:

```
▶ cd Work/odo-examples/1234567890123456789012434567890               

▶ odo create 

▶  cat devfile.yaml
...
...
    endpoints:
    - name: nodejs-x12345678901-irop-8080
      targetPort: 8080
....
....
                                                                                                     
▶ odo push

Validation
 ✓  Validating the devfile [31300ns]

Creating Kubernetes resources for component nodejs-x12345678901-irop
 ✓  Waiting for component to start [34s]
 ✓  Waiting for component to start [15ms]

Applying URL changes
 ✗  Failed To Update Config To Component Deployed.
Error: unable to create route: error creating route: Route.route.openshift.io "nodejs-x12345678901-irop-8080-nodejs-x12345678901-irop" is invalid: spec.host: Invalid value: "nodejs-x12345678901-irop-8080-nodejs-x12345678901-irop-tkral-test.apps-crc.testing": host must conform to DNS 1123 naming conventions: [spec.host: Invalid value: "nodejs-x12345678901-irop-8080-nodejs-x12345678901-irop-tkral-test": must be no more than 63 characters]
````

**Comment by girishramnani** [comment]
> * should I trim it if it goes beyond a certain characters [ max - 30 chars ] ? - also there is an issue with triming it from right side as the sufix is the random string - which means if I trim it too much we might have conflicting url name. ( as the random string might get trimed )

Would this approach work^ so that a url doesn’t go over 20 or 30 characters?

**Comment by kadel** [comment]
> Would this approach work^ so that a url doesn’t go over 20 or 30 characters? @kadel

url name (endpoint name) can be up to 63 characters, why would you limit it to just 20?

Problem is that it generates Ingres/Route with a host that is too long.

**Comment by girishramnani** [comment]
I have implemented an approach similar to what devfile does in this https://github.com/openshift/odo/pull/4670
Please take a look
