### ISSUE TITLE
converted wildfly and dotnet application error out with permission denied 

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4623]
/kind bug

## What versions of software are you using?

**Operating System:** MacOS

**Output of `odo version`:**

## How did you run odo exactly?
`"odo", "create", "--s2i", "wildfly", "wildfly-app"`
"odo", "create", "--s2i", "dotnet:2.0"

## Actual behavior
```
 + PV_MNT_PT=/opt/app-root              
INFO[2021-04-14T23:04:26Z] [odo] + ODO_UTILS_DIR=/opt/odo               
INFO[2021-04-14T23:04:26Z] [odo] + '[' '!' -f /opt/app-root/conf/supervisor.conf ']' 
INFO[2021-04-14T23:04:26Z] [odo] + cp -rp /opt/odo/conf /opt/app-root   
INFO[2021-04-14T23:04:26Z] [odo] cp: cannot create directory '/opt/app-root/conf': Permission denied 
INFO[2021-04-14T23:04:26Z] [odo]  ✗  Executing s2i-assemble command "/opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart" [179ms] 
INFO[2021-04-14T23:04:26Z] [odo]  ✗  Failed to start component with name wildfly-app. Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c /opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart]:  
INFO[2021-04-14T23:04:26Z] [odo] + set -eo pipefail                     
INFO[2021-04-14T23:04:26Z] [odo] + PV_MNT_PT=/opt/app-root              
INFO[2021-04-14T23:04:26Z] [odo] + ODO_UTILS_DIR=/opt/odo               
INFO[2021-04-14T23:04:26Z] [odo] + '[' '!' -f /opt/app-root/conf/supervisor.conf ']' 
INFO[2021-04-14T23:04:26Z] [odo] + cp -rp /opt/odo/conf /opt/app-root   
INFO[2021-04-14T23:04:26Z] [odo] cp: cannot create directory '/opt/app-root/conf': Permission denied 
INFO[2021-04-14T23:04:26Z] [odo] : error while streaming command: command terminated with exit code 1 
INFO[2021-04-14T23:04:26Z] Deleting project: e2e-source-test36ipy       
INFO[2021-04-14T23:04:26Z] Running odo with args [odo project delete e2e-source-test36ipy -f] `
```

```
   Generating MSBuild file /opt/app-root/src/obj/asp-net-hello-world.csproj.nuget.g.targets.
[odo]   Restore completed in 4.99 sec for /opt/app-root/src/asp-net-hello-world.csproj.
[odo] ---> Publishing application...
[odo] Microsoft (R) Build Engine version 15.4.8.50081 for .NET Core
[odo] Copyright (C) Microsoft Corporation. All rights reserved.
[odo] 
[odo]   asp-net-hello-world -> /opt/app-root/src/bin/Release/netcoreapp2.0/asp-net-hello-world.dll
[odo]   asp-net-hello-world -> /opt/app-root/app/
[odo] chmod: changing permissions of '/opt/app-root/app/default-cmd.sh': Operation not permitted
[odo] : error while streaming command: command terminated with exit code 1
```

## Expected behavior
Component should be working

- [ ] Persistent volumes should be mounted into `/opt/app-root` and in `$DEPLOYMENTS_DIR`
- [ ] `$DEPLOYMENTS_DIR` can be inside `/opt/app-root`, in this case mount only one PV in `/opt/app-root`
- [ ] An init container should copy the content of the original `/opt/app-root` into the persistent volume mounted on this endpoint
- [ ] Declare a `preStart` event in the devfile to run this init container (blocked by #4901)

**Comment by girishramnani** [comment]
A test in the code has been comment out due to this error, once fixed uncomment the test
PR - https://github.com/openshift/odo/pull/4518

**Comment by johnmcollier** [comment]
FWIW, I hit the same permission denied error with the `java-wildfly` devfile that's in odo-devfiles/registry

**Comment by feloy** [comment]
I suspect there is some relation with this PR on odo-init-image: https://github.com/openshift/odo-init-image/pull/70

**Comment by feloy** [comment]
Images running the component have an `/opt/app-root` directory. Some images (ex: nodejs) have this directory with `g+w` file permission, some others (ex: wildfly) without this permission (`g-w`).

In s2i mode, a persistent volume were mounted into this `/opt/app-root`, so the permissions were not taken into account.

In normal mode, the persistent volume is not mounted anymore, and the permissions are now taken into account.
