### ISSUE TITLE
Odo integration tests should use staging devfile registry (registry.stage.devfile.io)

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#4639]
With https://github.com/openshift/odo/pull/4525 now merged, Odo now supports the new community devfile registry at https://registry.devfile.io, and uses it by default.

While most Odo integration tests don't directly use the registry for testing, there are a few other integration tests that do:
- `odo catalog` tests
- `odo create --registry` tests
- `odo registry` tests

A few of us on devfile services were chatting and think that for the integration tests in Odo that _do_ use the registry, it might be a good idea to use the staging devfile registry (https://registry.stage.devfile.io) instead of production for a couple reasons:
- It'll reduce unnecessary load on the production registry, especially when there's multiple test runs running concurrently
- The staging and production registries are largely identical, the only difference is _when_ they are updated
    - Staging is updated with each commit to master in [devfile/registry](https://github.com/devfile/registry), production is updated manually each Wednesday
- Telemetry will eventually be enabled on the production devfile registry and we do not want the integration tests polluting the data we get back from the telemetry.

Let me know if this sounds like a reasonable thing to do, or if there's any concerns about this approach.

**Comment by johnmcollier** [comment]
I just want to clarify too, this is **not** something that necessarily needs to be done urgently or soon - we're still a ways away from implementing telemetry on the devfile registry, and the extra load that the tests are creating on the registry is useful for us as we monitor load in this transition period.

But it is something that will need to be done _once_ we implement telemetry

**Comment by josephca** [comment]
Currently, the following tests are using the staging registry - https://github.com/openshift/odo/pull/4679
- odo catalog test 
- odo registry tests

Thus, `odo create --registry tests` is remained to use the staging registry for the test.

**Comment by valaparthvi** [comment]
This issue is still in progress w.r.t. PR #4775.
