### ISSUE TITLE
Release readiness status for v2.2.0

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4643]
/kind user-story

## User Story
As a user I want to know the status of v2.2.0 release that covers

- [ ] Matrix on Blocker / TestBlocker / AutomationBlocker / Bugs
- [ ] Test automation status
- [ ] Defect Metrics (Defect Backlog, Defects Arrival, Defects Regression, Defects Resolution, Defects Reopen, Defects Verification, Defect Rejected)
- [ ] Test platform coverage

## Acceptance Criteria 
- [ ] The above story matrix should be documented and reviewed

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by dharmit** [comment]
@prietyc123 do we still want to keep this one arond ?

**Comment by prietyc123** [comment]
> @prietyc123 do we still want to keep this one arond ?

I think it does not make sense anymore. 

/close
