### ISSUE TITLE
Known issues cleanup and update for v2.2.0 in Bugzilla

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4644]
/kind user-story

## User Story
As a User i want to know what are the known issues for v2.2.0 release reported in bugzilla - https://bugzilla.redhat.com/buglist.cgi?component=odo&product=OpenShift%20Developer%20Tools%20and%20Services&resolution=---

## Acceptance Criteria 
- [ ] KIs list should be cleaned up and updated for v2.2.0

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by dharmit** [comment]
Closing since we have 2.2 out.

/close
