### ISSUE TITLE
Run Opreator integration tests on Kubernetes cluster in CI

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4651]
/kind user-story

## User Story
As an odo developer I want to run Operator integration tests on a Kubernetes cluster so that the functionality is tested for both OpenShift and Kubernetes.

## Acceptance Criteria 
- [ ] Install the Operators on Kubernetes. For OpenShift cluster, we run the [setup-operators.sh](https://github.com/openshift/odo/blob/66935fca219dd8ceee25ad4639f5b07ac4d58c86/scripts/configure-cluster/common/setup-operators.sh) script. For Kubernetes, we would require enabling OLM first before we can run this script successfully.
- [ ] Remove the check that skips running Operator tests on Kubernetes and verify that all integration tests for Operators support run on the Kubernetes cluster in CI.

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story
/area testing

**Comment by dharmit** [comment]
> For Kubernetes, we would require enabling OLM first before we can run this script successfully.

If we're using minikube in the CI, we can do this by running `minikube addons enable olm`. However, this uses old images for enabling OLM, and we would need to make sure to use newer images by running `minikube addons enable olm --images`. More infromation can be found at https://github.com/kubernetes/minikube/pull/10769#pullrequestreview-609180386 and https://github.com/kubernetes/minikube/issues/10768#issuecomment-799576265.

**Comment by kadel** [comment]
> If we're using minikube in the CI, we can do this by running `minikube addons enable olm`. However, this uses old images for enabling OLM, and we would need to make sure to use newer images by running `minikube addons enable olm --images`. More infromation can be found at [kubernetes/minikube#10769 (review)](https://github.com/kubernetes/minikube/pull/10769#pullrequestreview-609180386) and [kubernetes/minikube#10768 (comment)](https://github.com/kubernetes/minikube/issues/10768#issuecomment-799576265).

olm addon is horrible, we should avoid it. Using offial installation method from operatorhub.io is much better 
`$ curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/install.sh | bash -s v0.17.0`

**Comment by dharmit** [comment]
@prietyc123 are you interested in picking this one up for Sprint 202?

**Comment by prietyc123** [comment]
Ahh... so here again `docker` rate limit thing happening on kubernetes cluster now, when I tried running operator hub tests on it. 
Its actually `busybox` 🙁 
```
Events:             
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Type     Reason     Age                From               Message 
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   ----     ------     ----               ----               ------- 
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Normal   Scheduled  68s                default-scheduler  Successfully assigned cmd-service-test361wcv/example-8z66tnfj67 to minikube 
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Normal   Pulling    28s (x3 over 67s)  kubelet, minikube  Pulling image "busybox:1.28.0-glibc" 
INFO[2021-05-31T06:59:22Z]                                              
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Warning  Failed     28s (x3 over 67s)  kubelet, minikube  Failed to pull image "busybox:1.28.0-glibc": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Warning  Failed     28s (x3 over 67s)  kubelet, minikube  Error: ErrImagePull 
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Normal   BackOff    2s (x5 over 66s)   kubelet, minikube  Back-off pulling image "busybox:1.28.0-glibc" 
INFO[2021-05-31T06:59:22Z] [ssh:Fedora-32-minikube]   Warning  Failed     2s (x5 over 66s)   kubelet, minikube  Error: ImagePullBackOff 
```
@dharmit `etcd` services using `busybox` images pulled out of `dockerhub` . Shouldn't we use different images other than `etcd`. 
I am not if we can do `configure` secret for `docker` into kubernetes cluster too. @kadel @mohammedzee1000 could you please share your thoughts.

**Comment by kadel** [comment]
> Shouldn't we use different images other than `etcd`.
> I am not if we can do `configure` secret for `docker` into kubernetes cluster too.

Ideally, we should use an entirely different service. Ideal would be MariaDB/MySQL, PostgreSQL/Percona, MongoDB or Redis.
Those are probably the most widely used databases using one of these for our test would be much better.

**Comment by prietyc123** [comment]
On ocp 4 `mongodb-enterprise` operator failed to install due to 
```
installing: waiting for deployment mongodb-enterprise-controller-manager to become ready: deployment "mongodb-enterprise-controller-manager" not available: Deployment does not have minimum availability.
```
I will look for some other operator which installs smoothly.

For minikube, I guess we have some problem in our backend implementation https://github.com/openshift/odo/pull/4754#issuecomment-854744010

**Comment by dharmit** [comment]
First image - I created a 4.8 cluster using the cluster bot and I'm seeing the Postgres Operator that I mentioned in my previous comment. 

Second image - What's different from the OCP cluster you showed me on the call is that this cluster has a total of 447 items (total number of Operators available to install) compared to <200 on that cluster. I think this is because the catalog sources are not fully/properly started in the cluster you were using. You can look at output of `oc get catsrc -A` to get info about catalog sources.

![image](https://user-images.githubusercontent.com/713521/121656223-e768ce80-cabc-11eb-89af-f30729c08c07.png)
![image](https://user-images.githubusercontent.com/713521/121656302-f8b1db00-cabc-11eb-93e6-b730292f3db3.png)

**Comment by prietyc123** [comment]
blocked on https://github.com/openshift/odo/pull/4704

**Comment by dharmit** [comment]
Added it back to "In Progress" for Sprint 202 since @girishramnani removed it by mistake.

**Comment by dharmit** [comment]
Try to install a "clusterwide" operator from operatorhub.io @prietyc123 @girishramnani

**Comment by prietyc123** [comment]
I have found redis operator which works on both minikube and ocp https://github.com/openshift/odo/commit/a6afd62c3b389a6108bfd49540f31e91ffd3f1c1

**Comment by prietyc123** [comment]
Scope of the task for sprint 203:

- [ ] Refactoring operatorhub test for using `redis` operator
- [ ] Create issue and Fixing failures, if any

**Comment by dharmit** [comment]
* You could add tests for making sure that env vars are rightly populated in the pod of odo component. 
* Check for existence of files if `odo link --bind-as-files`.
