### ISSUE TITLE
Show deprecation warning when someone tries to use a github based registry 

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4666]
/kind user-story

## User Story
As we have oci based registry support now, we should consider eventually removing github based registry support for devfile.

## Acceptance Criteria 
- [ ] It should show a deprecation warning when someone tries to use github based registry.

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by dharmit** [comment]
As far as I can see, GH based registry doesn't show up in `odo registry list` output anyway https://github.com/openshift/odo/issues/4626#issuecomment-820908807.



> It should show a deprecation warning when someone tries to use github based registry.

Where/when should this warning be shown exactly?

**Comment by girishramnani** [comment]
Ok so I need suggestion on when to show this warning, when someone tries to add github based registry?,
Or when they list all registries and we see a github one
Or at odo create we find the devfile from github registry?

**Comment by dharmit** [comment]
>  Or at odo create we find the devfile from github registry?

I think it makes sense when the user's doing this.



> As far as I can see, GH based registry doesn't show up in `odo registry list` output anyway [#4626 (comment)](https://github.com/openshift/odo/issues/4626#issuecomment-820908807).

As a user, I don't even see the GH based registry so if odo says that I'm using GH based registry, I'm going to be confused why odo's even talking about a registry that doesn't exist in `odo registry list` output. No?

**Comment by kadel** [comment]
> Ok so I need suggestion on when to show this warning, when someone tries to add github based registry?,
> Or when they list all registries and we see a github one
> Or at odo create we find the devfile from github registry?

I would put it into multiple places
- when someone tries to download something from github registry - this means during `odo create`
- when someone tries to add github based registry - `odo registry add` command
- when someone runs `odo registry list` and at least one registry is github based

**Comment by dharmit** [comment]
> when someone tries to add github based registry - `odo registry add` command

Why should we stop a user from adding a GH based registry if they want to?

> when someone runs `odo registry list` and at least one registry is github based

Why? What if an org has a registry on GH? Just having it on GH would make it invalid?

PS: My questions are genuine ones because I don't understand how this works. There's no pun intended.

**Comment by girishramnani** [comment]
> Why should we stop a user from adding a GH based registry if they want to?
We wont stop them, we would just show a deprecation warning. And well because we want to promote oci based registry, as GH based registry would be removed if we are adding the warning

**Comment by kadel** [comment]
> I mean the idea here is that GH registry wouldn't support newer features that OCI based registry would like helm charts etc.. so shouldn't we remove it **soon** and make OCI the primary one?

yes :+1:

**Comment by dharmit** [comment]
I think you folks are talking about one specific GH based registry and my question is more around - is odo not going to support "any" GH based registry?

**Comment by girishramnani** [comment]
no we are talking about GH based registry as a feature. We wont support them as a whole.

**Comment by kadel** [comment]
> I think you folks are talking about one specific GH based registry and my question is more around - is odo not going to support "any" GH based registry?

Yes, odo should NOT support any GH-based registries, because no other tool will ever support that.

**Comment by girishramnani** [comment]
I added "a" in the title so its clear that its not "the" GH registry its all **Github based registries** because are deprecating the feature.

**Comment by dharmit** [comment]
I wasn't aware of https://github.com/devfile/registry-operator and hence asked the questions I asked. I still have some confusion but I think the PR might clear my doubts.

**Comment by girishramnani** [comment]
So we are on-board with add the warning?

**Comment by dharmit** [comment]
> So we are on-board with add the warning?

Sure.

**Comment by girishramnani** [comment]
> I would put it into multiple places
> 
> * when someone tries to download something from github registry - this means during `odo create`
> * when someone tries to add github based registry - `odo registry add` command
> * when someone runs `odo registry list` and at least one registry is github based

Currently this would be the approach - adding it at multiple places.

**Comment by girishramnani** [comment]
Assigning to myself, will pick up in the next sprint.

**Comment by mohammedzee1000** [comment]
I believe this is pretty straightforward at this point. Provide deprecation warning the 3 commands as @kadel said. I guess the only problematic part would be detecting if a registry is git-based. For now, I will go with simple approach, checking if `git` is present in URL

Acceptance:

- [ ] Create a function that prints registry deprecation warning if called.
- [ ] Create function for the `Registry` struct in preference that checks if the registry is git based
- [ ] Add function in the `Validate` section of the `odo create` command that prints deprecation warning if registry being used is git based
- [ ] Add a check in the `odo registry list` command, that prints deprecation warning at the end if even 1 registry is git based
- [ ] Add a check in the `Validate` section of `odo registry add` that prints deprecation warning if the specified registry is git based

**Comment by mohammedzee1000** [comment]
We need this going in before this release so users get ample notice so marking as release blocker
