### ISSUE TITLE
Configure a long running VM for minikube

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4675]
Kubernetes tests configure on fly vms for each and every prs on PSI infrastructure. We want to run it on a long running cluster to avoid creating VMs everytime.

## Acceptance Criteria
- [ ] Long running minikube VM on PSI
- [ ] Kubernetes Tests for every pr

/area testing
/priority high

**Comment by prietyc123** [comment]
We should try increasing `--retryloopcount` to may be 7 and observe ssh behavior. For Now its low priority.

/priority low

**Comment by prietyc123** [comment]
Sometimes Build of instance fails on `aborted: Failed to allocate the network(s), not rescheduling`. In this scenario even increasing `--retryloopcount` won't help as its completely psi issue. I am going to create one ticket and do a follow up on that. Now I feel it would be great idea to have long running VM until psi vm creation issue gets fixed.
@kadel @mohammedzee1000 WDYT?

**Comment by kadel** [comment]
> Now I feel it would be great idea to have long running VM until psi vm creation issue gets fixed.

+1 on long-running VMs and never going back :-)

**Comment by prietyc123** [comment]
Scope of the issue:
- [ ] Provisions VM on OpenStack with ssh key login
- [ ] Gathers the IP acquired by VM and generates a ssh node list (https://github.com/mohammedzee1000/ci-firewall#sshnodefile)
- [ ] configure minikube pre setup inside the created VM as mentioned https://github.com/openshift/odo/issues/4287#issuecomment-755316954 
- [ ] Customise script https://github.com/openshift/odo/blob/main/scripts/minikube-minishift-setup-env.sh according to long running VM configuration
- [ ] Change psi and jenkins configuration
- [ ] Ensure single pr test runs at a time and cleanup works properly after test execution

**Comment by prietyc123** [comment]
Closing this issue as the acceptance criteria has been met. 

/close
