### ISSUE TITLE
Custom link names and bindAsFiles option for SB

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4693]
/kind user-story

## User Story
As an odo user, I want to be able to control if linking information is provided as env variables or as files.
As an odo user, I want to be able to customize the name of the file when linking information is provided in file.

## Acceptance Criteria 
- [x] It should be possible to optionally specify `ServiceBinding` name that is created when `odo link` is called. (example: `odo link mydb --name customersDB`
- [x] It should be possible to set  `bindAsFiles` field for `ServiceBinding` that gets created when `odo link` is called. By default, odo should keep using env variables. (example: `odo link mydb --bindAsFiles=true`, default for `--bindAsFiles` will be false) 

## Links 
- Related Epic (mandatory): https://github.com/openshift/odo/issues/4590

/kind user-story
/priority medium

**Comment by kadel** [comment]
This issue requires https://github.com/openshift/odo/pull/4648 to be merged first.

**Comment by wtrocki** [comment]
> default, odo should keep using env variables

CC @pedjak @slemuir

**Comment by kadel** [comment]
> > default, odo should keep using env variables
> 
> CC @pedjak @slemuir

This is to ensure compatibility with the current `odo link` behavior.

**Comment by feloy** [comment]
`odo unlink` will need to know the name of the ServiceBinding to delete it. Should the user pass the `--name` option again during the `unlink` command, or should `odo` save this name somewhere, so it can reference it when running `unlink`?

Looking at the file .odo/env/env.yaml, I understand the name is already stored there. Is it right?

**Comment by kadel** [comment]
> `odo unlink` will need to know the name of the ServiceBinding to delete it. Should the user pass the `--name` option again during the `unlink` command, or should `odo` save this name somewhere, so it can reference it when running `unlink`?

odo link will store `ServiceBinding` in a devfile (#4208). `odo unlink` should be able to extract the name from there.

But there could be multiple links. You are right `odo unlink` will need `--name`, but only if there are multiple links. If there is only one link odo should be able to get the name from devfile.

**Comment by dharmit** [comment]
Even if a component's linked to multiple components/services, it will have only one link to a particular component/service. A link name is unique and hence doing `odo unlink <service-name>` (which unlinks the component under `pwd` from the `<service-name>`) should unlink the component and the service. I think providing the name of the link won't be required.

**Comment by girishramnani** [comment]
@feloy if you are working on this then please assign it to yourself
