### ISSUE TITLE
odo delete with wait flag tests are flaky

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4733]
/kind flaky-test
/priority High

**Comment by mohammedzee1000** [comment]
First occurrence I saw was in https://github.com/openshift/odo/pull/4732

**Comment by feloy** [comment]
I understand from this doc [1] that the dependent resources must have `ownerReference.blockOwnerDeletion=true` if we want to wait for the deletion of the dependent resource when deleting the parent with `propagationPolicy=Foreground`

I tried to update `odo` to add this field `ownerReference.blockOwnerDeletion=true` to the service, but an error occurs:

```
[36mINFO[0m[2021-05-25T10:32:39Z] [odo]  ✗  Failed to start component with name "openjdk-app".
Error: Failed to create the component: unable to create or update component: unable to create Service for openjdk-app:
services "openjdk-app" is forbidden:
cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil> 
```

[1] https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion
