### ISSUE TITLE
every PR should have "kind/*" label

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4745]
Configure Prow so merge bot doesn't merge PR if they don't have at least one `kind` label

**Comment by anandrkskd** [comment]
There's a plugin for this upstream but it's not yet enabled openshift, I have created a enhancement request on their side.

**Comment by anandrkskd** [comment]
The plugin required to check for label of type kind is [require-matching-label](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/require-matching-label), which will be used by [plugin.yaml](https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L504-#L509).

But we are currently blocked on the prow team for this, I have created a jira ticket for the enhancement request. From there side they have stated that they need to figure out what is its impact on token consumption, and they are running pretty thin on resources.
They have also stated that the ticket may end up being declined if the impact on token consumption would be too high (label-related actions tend to do that).

**Comment by prietyc123** [comment]
@anandrkskd Could you please add the enhancement issue here.

**Comment by kadel** [comment]
/reopen

This doesn't work.  PRs without `kind` label still get merged.
One such example is https://github.com/openshift/odo/pull/5046

**Comment by prietyc123** [comment]
According to `shipwrite` team the changes were working at the first point but then ordering in those prow/plugin config files has bearing. I will follow up with platform team on this.

**Comment by rnapoles-rh** [comment]
This will not be relevant if we move to GitHub Actions

**Comment by dharmit** [comment]
It's relevant for changelog generator which helps us summarize things for every release. So it is relevant in that context.

**Comment by dharmit** [comment]
@rnapoles-rh let's see if the PR https://github.com/openshift/odo/pull/5154 goes in without the label. I have not added any to it and so even if someone approves the PR, merging should be blocked.

**Comment by rnapoles-rh** [comment]
> @rnapoles-rh let's see if the PR #5154 goes in without the label. I have not added any to it and so even if someone approves the PR, merging should be blocked.

Sounds good

**Comment by rnapoles-rh** [comment]
Might need to remove - needs-kind from missingLabels and have kind in the two lables sections, checking with DPTP

**Comment by rnapoles-rh** [comment]
- [ ] Review what [require-matching-label](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/require-matching-label/require-matching-label.go) does 
- [ ] Figure out how to integrate it
- [ ] Decide what label to add if none was in place
