### ISSUE TITLE
use go 1.16

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4778]
all our build and tests should run using go 1.16

Few things that needs to be updated
- [ ] prow jobs
- [ ] psi jobs
- [ ] release build scripts (#5140)

/priority high

**Comment by prietyc123** [comment]
> all our build and tests should run using go 1.16

Instead of calling it with versions, how about when we just say, run test on latest go?

**Comment by kadel** [comment]
> Instead of calling it with versions, how about when we just say, run test on latest go?

sure, we can do that. But latest go needs to mean latest stable version as it is on https://golang.org/dl/ not latest version that is awailable for a given system.

Test run on different systems, Linux (fedora, centos ...), win, mac ... We need to make sure that at least we use the same minor (1.16.x) version everywhere.  We should not have one system running 1.14.x and the other 1.16.x

**Comment by prietyc123** [comment]
> sure, we can do that. But latest go needs to mean latest stable version as it is on https://golang.org/dl/ not latest version that is awailable for a given system.

+1

**Comment by anandrkskd** [comment]
The release builds currently has a go 1.15 for latest build target, I think we should do that instead going for 1.16 for now.
We can create a separate ticket to add a newer version of golang(1.16).

**Comment by dharmit** [comment]
OCP uses go 1.16 everywhere. They have their own build targets; ours are decided by a different team. 

* We could open a request with the build team to use 1.16 for odo's build targets if we want to move to 1.16 in odo repo.
* Or, figure out how OCP always uses latest go version in their build targets and do that for odo as well. (preferred approach)

Else, we bump to 1.15 (current latest in build systems) for now.

**Comment by anandrkskd** [comment]
As 1.16 is not available should we create a ticket and spend time on figuring out if we can also have a custom build target that is latest? 
or move forward with 1.15 for now and figure out how can we use latest on build target?
what do you think?
cc_ @dharmit @kadel

**Comment by dharmit** [comment]
> As 1.16 is not available should we create a ticket and spend time on figuring out if we can also have a custom build target that is latest?

Where is it not available? On the infra used to build odo artefacts?

> or move forward with 1.15 for now and figure out how can we use latest on build target?

If answer to my question about artefacts is yes, then I think this is our only option, no?

**Comment by anandrkskd** [comment]
> Where is it not available? On the infra used to build odo artefacts?

yes, In our brew build target.

> If answer to my question about artefacts is yes, then I think this is our only option, no?

I was a little confused about what should we do now, do we want to use 1.16 directly or invest time to figure out the way to use the latest.
And also I was thinking about all the possibility that we can go through, we can also create a ticket for 1.16 and use 1.15 for now, and  figure out how can we use latest on build target?

For my perspective I think we should " create a ticket for 1.16 and use 1.15 for now, and  figure out how can we use latest on build target "

**Comment by dharmit** [comment]
> > If answer to my question about artefacts is yes, then I think this is our only option, no?
> 
> I was a little confused about what should we do now, do we want to use 1.16 directly or invest time to figure out the way to use the latest.
> And also I was thinking about all the possibility that we can go through, we can also create a ticket for 1.16 and use 1.15 for now, and figure out how can we use latest on build target?
> 
> For my perspective I think we should " create a ticket for 1.16 and use 1.15 for now, and figure out how can we use latest on build target "

My understanding of the build infra we use is very limited. But using the currently available latest (1.15 at the time of writing this), and figuring out how we can decide/control the version we want to use (1.16 at the time of writing this) sounds like a good idea.

@kadel @mohammedzee1000 wdyt?

**Comment by prietyc123** [comment]
Scope of the task

- [x] onboard to go 1.15 
- [x] create issue getting go 1.16 into cloud build
- [ ] automate cloud build process to use go latest
- [ ] Update built-in dockerfile in odo repo

**Comment by dharmit** [comment]
Should the odo-init image also be updated to use go 1.15?

https://github.com/openshift/odo-init-image/blob/27dc3d4193ca8f6d34e781907ceb584a2d8f5ae4/Dockerfile#L7-L9

Should it be a part of this issue or should we have a separate issue for it?

**Comment by anandrkskd** [comment]
> Should the odo-init image also be updated to use go 1.15?

yeah, I completely missed to change in odo-init-image repo, as it was not mentioned on the doc i was following. I will update both the doc and image tag in `odo-init-image` repo.

> Should it be a part of this issue or should we have a separate issue for it?

Both works fine for me. I can add this to scope of the issue which is mentioned above https://github.com/openshift/odo/issues/4778#issuecomment-872935635

**Comment by dharmit** [comment]
@anandrkskd there's already a PR for it - https://github.com/openshift/odo-init-image/pull/88/

**Comment by anandrkskd** [comment]
Understood! I guess we don't need to create a new issue then as a PR is already created.

**Comment by prietyc123** [comment]
reducing the priority to medium.

/priority medium
