### ISSUE TITLE
Windows unit tests times out way to often

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4789]
pull-ci-openshift-odo-main-psi-unit-test-windows often ends on 2h timeout.

As of now in last 24hours **26 runs failed** after 2 hours and **only 2 were successful** 

https://prow.ci.openshift.org/?repo=openshift%2Fodo&job=pull-ci-openshift-odo-main-psi-unit-test-windows

**Comment by kadel** [comment]
also, this test should have a lower timeout. If it is successful it usually takes 9 minutes. Setting timeout to 20 would be more than enough. And it would avoid the situation like we have right now where we have over 10 jobs in queue just waiting to fail.

**Comment by dharmit** [comment]
Take a look at the existing Windows VM and try to figure out why unit tests are not running at all on it.

**Comment by anandrkskd** [comment]
After restarting the vm and a cleanup the tests are now passing with a good rate. In addition to that I have created a new VM(needs to be setup to tests) that we will use in such case of rapid failure.

**Comment by anandrkskd** [comment]
A backup VM is up and running. We can use it in this kind of scenario where tests are failing due to VM related issue. The tests duration is already reduced to 20 mins.
And the tests on windows are currently running fine again, and timeout is not observed.

**Comment by anandrkskd** [comment]
> timeout is not observed. 
Timeout observed on test for PR #4806. but test passed successfully on the jenkins (took 24 mins to complete). Sometime the builds are taking long time to build, two occurrence noted in last 15 tests.

**Comment by anandrkskd** [comment]
Closing this issue as no Timeout is observed, and tests are taking 10 to 15 mins to complete.
/close
