### ISSUE TITLE
`odo catalog service describe service/cr -o json` output is not openAPIV3Schema json

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4790]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 2.2.1

## How did you run odo exactly?

`odo catalog service describe service/cr -o json`

## Actual behavior

Output contains resource description from ClusterServiceVersion not actual CRD's openAPIV3Schema, thus type and format attributes are missing, which are required to generate usable form with parameter specific input elements and validation.

## Expected behavior

When creating operator backed service to generate form to request input from user the same way it is done in DC, both resource description from ClusterServiceVersion and CRD's openAPIV3Schema data required.

**Comment by girishramnani** [comment]
@dgolovin - I am really sorry for the confusion, but this is intentional and to know more please go over the revised proposal https://github.com/openshift/odo/pull/4751

**Comment by girishramnani** [comment]
Closing this as it’s expected behaviour
