### ISSUE TITLE
Run test on kubernetes using IBM cloud

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4798]
/kind user-story

## Scope of Issue
- [x] Get a fedora VM running on IBM Cloud for kubernetes testing (marked done since we'll us the existing VM on PSI instead of spining up a new one on IBM Cloud).
  - Currently there's Jenkins running on PSI.
  - A VM acts as Jenkins slave/worker node and executes tests on target cluster
  - The target cluster is going to be IBM Cloud Kubernetes Service - https://www.ibm.com/cloud/kubernetes-service
- [ ] Update scripts to use kubernetes cluster running on IBM cloud
- [ ] Make sure test runs concurrently on jenkins
- [ ] Get rid of minikube VM in PSI
#### Added on 2021-07-28

- [x] We're relying on "service IDs" for admin & developers users with "@ redhat" email address to get created.
- [x] Next run the tests against the k8s cluster and see if these "service IDs" was the only thing blocking us or was there something else
- [x] Run the tests on IBM k8s cluster assuming there weren't any other surprises.
- [ ] Fix the failing tests, if any.
- [ ] Create new scripts to run PRs builds in a concurrent fashion from the beginning.
    - Delete the dangling projects before touching this!

## Links 
- Related Epic (mandatory): https://github.com/openshift/odo/issues/4792
- #4800 

/kind user-story

**Comment by dharmit** [comment]
>   * [ ]  Get a fedora VM running on IBM Cloud for kubernetes testing

Just wondering why we can't use [IBM Cloud Kubernetes Service](https://cloud.ibm.com/docs/containers?topic=containers-getting-started) for this, just like we're using Red Hat OpenShift on IBM Cloud for OCP testing? Probably this was discussed on some call but I forgot the reasoning.

**Comment by dharmit** [comment]
- [ ] We're relying on "service IDs" for admin & developers users with "@ redhat" email address to get created.
- [ ] Next run the tests against the k8s cluster and see if these "service IDs" was the only thing blocking us or was there something else
- [ ] Run the tests on IBM k8s cluster assuming there weren't any other surprises.
- [ ] Fix the failing tests, if any.

**Comment by rnapoles-rh** [comment]
Adittioal changes were made to the permission settings for service ID:

**Comment by rnapoles-rh** [comment]
Service IDs for developer and admin roles were created and tested for the IBM Cloud, now working properly. 
Ran tests manually against the K8S cluster in the IBM Cloud using the service IDs.
Test results:

```
make test-cmd-devfile-create
...
Ran 37 of 197 Specs in 58.904 seconds
SUCCESS! -- 37 Passed | 0 Failed | 0 Pending | 160 Skipped

make test-cmd-devfile-push
...
Ran 38 of 197 Specs in 373.318 seconds
FAIL! -- 32 Passed | 6 Failed | 0 Pending | 159 Skipped

make test-cmd-devfile-exec
...
Ran 4 of 197 Specs in 50.086 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 193 Skipped

make test-cmd-project
...
Ran 8 of 8 Specs in 15.258 seconds
SUCCESS! -- 8 Passed | 0 Failed | 0 Pending | 0 Skipped
```

**Comment by rnapoles-rh** [comment]
Updated / created scripts to run tests in K8S cluster hosted in the IBM cloud. PR #5022  pending review
Made required changes in the release repo to trigger test in the IBM Cloud. PR will be submitted once #5022 get merged
