### ISSUE TITLE
`odo create` command takes unusually long to complete

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4799]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
`odo create nodejs -v4`

## Actual behavior
odo takes little over 5 seconds to create a component even with Telemetry disabled/

## Expected behavior
odo sholdn't take this long to create a component when Telemetry is disabled

## Any logs, error output, etc?

It's the validation that's taking longest. I tried verbose and have a hunch that it's taking long at two places. Both after the validation is done.
```sh
$ time odo create nodejs node -v4
....
....
Validation
 •  Validating if devfile name is correct  ...
 ✓  Validating if devfile name is correct [36785ns]
I0611 18:14:53.211880   31622 util.go:442] path devfile.yaml doesn't exist, skipping it
I0611 18:14:55.671283   31622 preference.go:220] The path for preference file is /home/dshah/.odo/preference.yaml
....
....
....
I0611 18:14:55.677722   31622 preference.go:220] The path for preference file is /home/dshah/.odo/preference.yaml

Please use `odo push` command to create the component with source deployed
I0611 18:14:57.616533   31622 odo.go:75] Could not get the latest release information in time. Never mind, exiting gracefully :)
odo create nodejs node -v4  0.14s user 0.03s system 2% cpu 5.427 total
```
* For the first one, diff is over 2 seconds - 18:14:53.211880 to 18:14:55.671283
* Near the end there's again diff of two seconds  - 18:14:55.677722 to 18:14:57.616533.

/area component

**Comment by kadel** [comment]
we are not able to safely reproduce this. I'm putting this on 
/priority low
for now.
