### ISSUE TITLE
`odo create nodejs <custom-name>` should store component name in `.metadata.name` field of devfile

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4802]
/kind bug

## What versions of software are you using? 

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
`odo create --s2i nodejs node`

## Actual behavior
```sh
$ grep metadata -A2 devfile.yaml
metadata:
  name: node
  version: 1.0.0
```
## Expected behavior
```
$ grep metadata -A2 devfile.yaml
metadata:
  name: nodejs
  version: 1.0.0
```

/milestone 2.4

**Comment by kadel** [comment]
This is correct behavior. 

If you are running 
```
odo create --s2i nodejs node
```
you are specifying that your component should be named `node` and this should reflect `metadata.name`

**Comment by dharmit** [comment]
> you are specifying that your component should be named `node` and this should reflect `metadata.name`

Then IMO it's a bug that `odo create nodejs nodejs-ex-123` (note that there's no `--s2i` passed this time) doesn't set `.metadata.name` to `nodejs-ex-123` in the resulting devfile:

```sh
$ odo create nodejs nodejs-ex-123
Devfile Object Validation
 ✓  Checking devfile existence [37955ns]
 ✓  Creating a devfile component from registry: OCI [49465ns]
Validation
 ✓  Validating if devfile name is correct [36998ns]

Please use `odo push` command to create the component with source deployed

$ grep -A3 metadata devfile.yaml
metadata:
  name: nodejs
  version: 1.0.1
  displayName: NodeJS Runtime

$ grep 123 devfile.yaml
# no output
```

**Comment by kadel** [comment]
> Then IMO it's a bug that `odo create nodejs nodejs-ex-123` (note that there's no `--s2i` passed this time) doesn't set `.metadata.name` to `nodejs-ex-123` in the resulting devfile:

This is something that we should change. When we start with devfile there was no other way to do this so we used  `env.yaml` to store the custom name. Now there is no reason to keep doing this, and we should use `metadata.name` for it.

**Comment by dharmit** [comment]
@kadel modifying current issue description seems like a mess. I'll create another issue.

Another problem is that if we do `odo create --s2i nodejs nodejs-ex-123`, `.metadata.name` gets set correctly, but `.metadata.language` doesn't. Which would become a problem for telemetry because there won't be any way to find `componentType` information.

Opening separate issue for both the problems.

/close
