### ISSUE TITLE
`odo list` output should have a column indicating if component is managed by odo

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4808]
/kind feature

## Which functionality do you think we should add?
`odo list` output should have a column (or multiple columns?) like that for `odo service list` (`MANAGE_BY_ODO` column) which indicates if the component is managed by odo or not.

There doesn't have to be any differentiation between devfile and s2i components (https://github.com/openshift/odo/issues/4808#issuecomment-862228191). 

## Why is this needed?
This is needed because current output can confuse users who are not aware of terms like between devfile, s2i, etc. It also aligns the output with what we show for `odo service list`.

## Acceptance Criteria
- [ ] `s2i`, `binary` and `git` support is going away. We don't need to differentiate there. Just remove the code. (Do this after https://github.com/openshift/odo/issues/4951)
- [ ] We only need to differentiate it for components managed by odo vs. other tools (ODC). 
    - [ ] Add a column `MANAGED_BY_ODO`. `YES`/`NO`.
    - [ ] Add JSON output for it.

```
$ odo list
Devfile Components: 
APP     NAME          PROJECT       TYPE                STATE       MANAGED_BY_ODO
app     petclinic     petclinic     java-springboot     Pushed        YES
app     nodejs-ex-git     petclinic     nodejs        NO

$ odo list -o json
```

/area component

**Comment by girishramnani** [comment]
if we are gonna remove s2i soon, do we wanna do this?

**Comment by kadel** [comment]
+1 for coming up with a better format for `odo list`, and if possible aligning it with `odo service list`

-1 for adding information about s2i component

> I think we will continue to have `odo create --s2i` support. It's just that odo would create devfile.yaml for it.

after this command is executed the component is a regular devfile component, beyond `odo create` we should not make any difference between components, it as all Devfile after this.

BTW: spoke to Mohit and Stephane, OpenShift connector plugin and Code Ready Studio are planning to drop support for `--git` and `--binary` components when that happens we will be able to remove that as well and get rid `LocalComponent` completely.

**Comment by dharmit** [comment]
> ``
> 
> -1 for adding information about s2i component
> 
> > I think we will continue to have `odo create --s2i` support. It's just that odo would create devfile.yaml for it.
> 
> after this command is executed the component is a regular devfile component, beyond `odo create` we should not make any difference between components, it as all Devfile after this.

Modified the issue description accordingly.

**Comment by mik-dass** [comment]
There is already a separate section for components created by other tools
https://github.com/openshift/odo/blob/b2ca2a81a03d076cf1c6d24c3991363d6f1124e4/pkg/odo/cli/component/list.go#L326

**Comment by kadel** [comment]
current status:
```
▶ odo list
Devfile Components: 
APP     NAME          PROJECT       TYPE                STATE
app     petclinic     petclinic     java-springboot     Pushed

Other Components running on the cluster(read-only): 
APP     NAME              PROJECT       TYPE
app     nodejs-ex-git     petclinic     nodejs

```

**Comment by mik-dass** [comment]
@kadel The current json output already has a section for components not managed by odo.
```
$ odo list --all-apps -o json
{
        "kind": "List",
        "apiVersion": "odo.dev/v1alpha1",
        "metadata": {},
        "s2iComponents": [],
        "devfileComponents": [
                {
                        "kind": "Component",
                        "apiVersion": "odo.dev/v1alpha1",
                        "metadata": {
                                "name": "nodejs-project-crmp",
                                "namespace": "blah",
                                "creationTimestamp": null
                        },
                        "spec": {
                                "app": "app",
                                "type": "nodejs",
                                "sourceType": "local",
                                "url": [
                                        "http-3000"
                                ],
                                "env": [
                                        {
                                                "name": "PROJECTS_ROOT",
                                                "value": "/project"
                                        },
                                        {
                                                "name": "PROJECT_SOURCE",
                                                "value": "/project"
                                        },
                                        {
                                                "name": "DEBUG_PORT",
                                                "value": "5858"
                                        }
                                ]
                        },
                        "status": {
                                "state": "Pushed"
                        }
                }
        ],
        "otherComponents": [
                {
                        "kind": "Component",
                        "apiVersion": "odo.dev/v1alpha1",
                        "metadata": {
                                "name": "nodejs-nodejs-basic-ummk",
                                "namespace": "blah",
                                "creationTimestamp": null
                        },
                        "spec": {
                                "app": "new-app",
                                "type": "nodejs",
                                "sourceType": "local",
                                "url": [
                                        "http-3000"
                                ],
                                "env": [
                                        {
                                                "name": "PROJECTS_ROOT",
                                                "value": "/project"
                                        },
                                        {
                                                "name": "PROJECT_SOURCE",
                                                "value": "/project"
                                        },
                                        {
                                                "name": "DEBUG_PORT",
                                                "value": "5858"
                                        }
                                ]
                        },
                        "status": {
                                "state": "Pushed"
                        }
                }
        ]
}
```
I think changing the json output might break other tools.

**Comment by kadel** [comment]
> @kadel The current json output already has a section for components not managed by odo.

ok, we can keep this as it is
