### ISSUE TITLE
`odo create <comp-type> <comp-name>` should use `<comp-name>` value in devfile's `.metadata.name`

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4815]
/kind feature

## Which functionality do you think we should add?
As pointed out in https://github.com/openshift/odo/issues/4802#issuecomment-862297237, `odo create` did what it's doing right now because there was no other option at the time.

But now the behaviour should be changed so that it looks like the **Expected** section.
### Now
```sh
$ odo create nodejs nodejs-ex-123
Devfile Object Validation
 ✓  Checking devfile existence [37955ns]
 ✓  Creating a devfile component from registry: OCI [49465ns]
Validation
 ✓  Validating if devfile name is correct [36998ns]

Please use `odo push` command to create the component with source deployed

$ grep -A3 metadata devfile.yaml
metadata:
  name: nodejs
  version: 1.0.1
  displayName: NodeJS Runtime
```

### Expected
```sh
$ odo create nodejs nodejs-ex-123
Devfile Object Validation
 ✓  Checking devfile existence [37955ns]
 ✓  Creating a devfile component from registry: OCI [49465ns]
Validation
 ✓  Validating if devfile name is correct [36998ns]

Please use `odo push` command to create the component with source deployed

$ grep -A3 metadata devfile.yaml
metadata:
  name: nodejs-ex-123
  version: 1.0.1
  displayName: NodeJS Runtime
```

## Why is this needed?
More info on https://github.com/openshift/odo/issues/4802.

/area component

**Comment by dharmit** [comment]
@kadel do we treat this as a bug or a feature? Asking because of https://github.com/openshift/odo/issues/4813#issuecomment-862406352.

**Comment by valaparthvi** [comment]
@dharmit I would like to take this up for the next sprint. I already have a PR open.
