### ISSUE TITLE
`odo create --s2i` should set `.metadata.language` in devfile.yaml

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4816]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
`odo create --s2i nodejs nodejs-123`

## Actual behavior
`.metadata.language` is not set in the devfile.yaml

## Expected behavior
`.metadata.language` should be set to nodejs in the devfile.yaml

## Any logs, error output, etc?
This is required because telemetry relies on this configuration to find `componentType`.

/area component

**Comment by girishramnani** [comment]
and what should be the  `.metadata.name` for both s2i and devfile?

**Comment by dharmit** [comment]
> and what should be the `.metadata.name` for both s2i and devfile?

IMO, if user passes the name, it should be that. https://github.com/openshift/odo/issues/4815.
If the user doesn't pass a name, we already generate one at the moment. So that's already sorted.

**Comment by valaparthvi** [comment]
To fix this issue, I am thinking to focus on normalize things between the way --s2i and normal create command works. So devfiles for both should have `.metadata.name`, `.metadata.language`, and perhaps `.metadata.projectType`, currently which in the case of normal create has the same value as language.
So if the user provides component name, it should be assigned to `.metadata.name` and the component type can be assigned to `.metadata.language` and `.metadata.projectType`.

The problem with normal create as described in #4815 is that it does not assign user provided component name to `.metadata.name`, but it sets everything else right.

And the problem with --s2i create is that it does not set `.metadata.language` and `.metadata.projectType`, but it sets `.metadata.name` correctly.

**Scope of the issue for Sprint 204** - 
- [ ] Fix normal create to set correct `.metadata.name`.
- [ ] Fix --s2i create to set `.metadata.language` and `.metadata.projectType`.
- [ ] Fix test cases in case of an failure.
- [ ] Add integration test cases or checks to an already existing test cases.
