### ISSUE TITLE
Dangling directories left by unit test run on all platforms (Windows, macOS, Linux)

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4817]
/kind bug
/area testing

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
`make test`

## Actual behavior
Large number of dangling directories from unit test run

## Expected behavior
Dangling directories to be not there.

/priority high

**Comment by anandrkskd** [comment]
In unit tests we are using function named `CleanupEnv` to cleanup all the mock config file and anything that SetupEnv generated.
but it doesn't deletes directories that are created while setup.
So adding `os.Remove(filepath.Dir(confFile.Name()))` after  https://github.com/openshift/odo/blob/e308b6bc8cf9309a5d11f01a59cf84136eb90f74/pkg/testingutil/configs.go#L138 should fix this issue.
I have checked it manually on windows and linux.
