### ISSUE TITLE
Skip CI for changes to Changelog.md

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4818]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

**Comment by dharmit** [comment]
@mohammedzee1000 can you help @anandrkskd regarding the regex thing?

**Comment by anandrkskd** [comment]
https://github.com/openshift/release/pull/19948

**Comment by anandrkskd** [comment]
closing this issue as PR https://github.com/openshift/release/pull/19948 is now merged!
/close
