### ISSUE TITLE
Applications in pods not starting on CodeReady Container restart

### ISSUE THREAD

**Issue by steinrr** [openshift/odo#4822]
/kind bug

## What versions of software are you using?

**Operating System:**
Macos latest

**Output of `odo version`:**
odo v2.2.1 (17a078b67)

Server: https://api.crc.testing:6443
Kubernetes: v1.20.0+75370d3

# How did you run odo exactly?
Running latest CodeReady Container version of OpenShift on my Mac. I am able to push applications to the cluster and they are working fine. Using the "odo push" command. Scaling number of pods works fine, and they all start and run the node application.

When I stop the CodeReady Container (crc stop), and start it again (crc start) - the pods are starting and seems to run fine. But when I open the URL of any of them - I get "Application is not available". I get the same on all applications - even "Hello World" kind of applications.

So somehow shutting down CRC and starting it again creates some "strange status" on the pods. I have tried to delete the pods from OpenShift console and also to scale to 0 instances and then add instances, but they still do not work. So even if OpenShift removes the pods and start new instances - they fail. Logs do not give any info. They only way to "fix" the application is to do a "odo push -f" that forces rebuild and redeploy of the application in the OpenShift cluster.

I did some investigation, and it seems that when restarting CRC, the pods are started, but the "npm start" is not run to actually start the node application within the pod. So the pod is running, the code is deployed in /project, but the application is not started. If I open the pod terminal, I can see that sometimes the /project folder has data in it and if I run "npm start" manually from the /project folder, the application starts again, but scaling e.g. to 2 pods are not working - the second pod is not working - because it will have the /project folder empty for some reason. Sometimes on crc restart, I find that the /project folder is empty also.

This is pod log from a series of events:

* Initial odo push and 2 few test pages in browser - everything working fine:

```
time="2021-06-17T05:09:21Z" level=info msg="create process:devrun" 
time="2021-06-17T05:09:21Z" level=info msg="create process:debugrun" 
time="2021-06-17T05:09:32Z" level=debug msg="no auth required" 
time="2021-06-17T05:09:32Z" level=debug msg="succeed to find process:devrun" 
time="2021-06-17T05:09:32Z" level=info msg="try to start program" program=devrun 
time="2021-06-17T05:09:32Z" level=info msg="success to start program" program=devrun 
ODO_COMMAND_RUN is npm start
Changing directory to /project
Executing command cd /project && npm start

> nodejs-ex@0.0.1 start /project
> node server.js

Server running on http://0.0.0.0:8080
time="2021-06-17T05:09:33Z" level=debug msg="wait program exit" program=devrun 
time="2021-06-17T05:09:35Z" level=debug msg="no auth required" 
10.217.0.1 - - [17/Jun/2021:05:09:41 +0000] "GET / HTTP/1.1" 200 40430 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"
10.217.0.1 - - [17/Jun/2021:05:14:56 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"

```
* Running crc stop to shut down:

```
time="2021-06-17T05:15:17Z" level=info msg="receive a signal to stop all process & exit" signal=terminated 
time="2021-06-17T05:15:17Z" level=info msg="stop the program" program=devrun 
time="2021-06-17T05:15:17Z" level=info msg="force to kill the program" program=devrun 
time="2021-06-17T05:15:18Z" level=error msg="program stopped with error:signal: terminated" program=devrun 
time="2021-06-17T05:15:18Z" level=info msg="Stopped by user, don't start it again" program=devrun 
time="2021-06-17T05:15:19Z" level=info msg="stop the program" program=debugrun 
```

* Running crc start to start again - application is not started:

```
ime="2021-06-17T05:21:46Z" level=info msg="create process:devrun" 
time="2021-06-17T05:21:47Z" level=info msg="create process:debugrun" 

```

## Actual behavior
odo pushed applications are not running after CRC restart. The pods are running, but they are not started. Sometimes the application code has disappeared from the "/project" folder as well. "odo push -f" is only way to fix.

## Expected behavior
Running pods should have the application running as well.

## Any logs, error output, etc?
See above.

**Comment by guillaumerose** [comment]
I look at it a bit and here my theory. copy/paste from https://github.com/code-ready/crc/issues/2474#issuecomment-867431188.

For the nodejs example, odo starts a dev container based on a vanilla node image + a volume with the code. 
The volume is declared as follow:
```
  volumes:
    - name: odo-projects
      emptyDir: {}
    - name: odo-supervisord-shared-data
      emptyDir: {}
```

I believe this directory is filled by odo during the push. I think this kind of directory (emptyDir) are temporary and doesn't survive a reboot.

**Comment by kadel** [comment]
Right. I completely forgot about  this :innocent: 
Odo is by default using empty dirs, to achieve wider compatibility with different clusters.

@steinrh You can change this behavior by setting `odo preference set Ephemeral false`.
This will instruct odo to use PVC for volume that is used to store source code.

We are going to consider changing the default value to make odo use persistent volume claims by default.

**Comment by steinrr** [comment]
The issue still persists. Created a new app and tested the Ephemeral setting. 

Output from oc describe pod:

```
% oc describe pod nodejs-nodejs-ex-cohf-6d7998f9bb-r2ggc
Name:         nodejs-nodejs-ex-cohf-6d7998f9bb-r2ggc
Namespace:    srrtest
Priority:     0
Node:         crc-m89r2-master-0/192.168.126.11
Start Time:   Thu, 24 Jun 2021 11:55:08 +0200
Labels:       app=app
              app.kubernetes.io/instance=nodejs-nodejs-ex-cohf
              app.kubernetes.io/managed-by=odo
              app.kubernetes.io/managed-by-version=v2.2.1
              app.kubernetes.io/name=nodejs
              app.kubernetes.io/part-of=app
              component=nodejs-nodejs-ex-cohf
              pod-template-hash=6d7998f9bb
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.217.0.12"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "interface": "eth0",
                    "ips": [
                        "10.217.0.12"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: restricted
Status:       Running
IP:           10.217.0.12
IPs:
  IP:           10.217.0.12
Controlled By:  ReplicaSet/nodejs-nodejs-ex-cohf-6d7998f9bb
Init Containers:
  copy-supervisord:
    Container ID:  cri-o://40c2457d7529a94cfb498d6c33f7200c58008de8645ccfbe6531ae58c5e690e7
    Image:         registry.access.redhat.com/ocp-tools-4/odo-init-container-rhel8:1.1.10
    Image ID:      registry.access.redhat.com/ocp-tools-4/odo-init-container-rhel8@sha256:0b25f37779ac09c197ef18e003cc6e49ac590cc79b058783f6f0a21eeb81581b
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/cp
    Args:
      -r
      /opt/odo-init/.
      /opt/odo/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 24 Jun 2021 12:00:39 +0200
      Finished:     Thu, 24 Jun 2021 12:00:41 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/odo/ from odo-supervisord-shared-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-r7bgz (ro)
Containers:
  runtime:
    Container ID:  cri-o://3b0298eba9e587357f26c2936d747428b4f78179b9eae577c2d48ced76c9f83d
    Image:         registry.access.redhat.com/ubi8/nodejs-14:latest
    Image ID:      registry.access.redhat.com/ubi8/nodejs-14@sha256:f03d58a9adaf56900dc96bce927bf33cd8720991fd090e3a8ae5037f3a0c2539
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /opt/odo/bin/supervisord
    Args:
      -c
      /opt/odo/conf/devfile-supervisor.conf
    State:          Running
      Started:      Thu, 24 Jun 2021 12:01:12 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  1Gi
    Requests:
      memory:  1Gi
    Environment:
      PROJECTS_ROOT:                  /project
      PROJECT_SOURCE:                 /project
      ODO_COMMAND_RUN:                npm start
      ODO_COMMAND_RUN_WORKING_DIR:    /project
      ODO_COMMAND_DEBUG:              npm run debug
      ODO_COMMAND_DEBUG_WORKING_DIR:  /project
      DEBUG_PORT:                     5858
    Mounts:
      /opt/odo/ from odo-supervisord-shared-data (rw)
      /project from odo-projects (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-r7bgz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  odo-projects-nodejs-nodejs-ex-cohf-oxts-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  odo-projects-nodejs-nodejs-ex-cohf-oxts
    ReadOnly:   false
  odo-projects:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  odo-supervisord-shared-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-r7bgz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-r7bgz
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason          Age    From               Message
  ----    ------          ----   ----               -------
  Normal  Scheduled       11m    default-scheduler  Successfully assigned srrtest/nodejs-nodejs-ex-cohf-6d7998f9bb-r2ggc to crc-m89r2-master-0
  Normal  AddedInterface  11m    multus             Add eth0 [10.217.0.50/23]
  Normal  Pulled          11m    kubelet            Container image "registry.access.redhat.com/ocp-tools-4/odo-init-container-rhel8:1.1.10" already present on machine
  Normal  Created         11m    kubelet            Created container copy-supervisord
  Normal  Started         11m    kubelet            Started container copy-supervisord
  Normal  Pulling         11m    kubelet            Pulling image "registry.access.redhat.com/ubi8/nodejs-14:latest"
  Normal  Pulled          11m    kubelet            Successfully pulled image "registry.access.redhat.com/ubi8/nodejs-14:latest" in 1.290752153s
  Normal  Created         11m    kubelet            Created container runtime
  Normal  Started         11m    kubelet            Started container runtime
  Normal  AddedInterface  6m2s   multus             Add eth0 [10.217.0.12/23]
  Normal  Pulled          5m51s  kubelet            Container image "registry.access.redhat.com/ocp-tools-4/odo-init-container-rhel8:1.1.10" already present on machine
  Normal  Created         5m43s  kubelet            Created container copy-supervisord
  Normal  Started         5m41s  kubelet            Started container copy-supervisord
  Normal  Pulling         5m32s  kubelet            Pulling image "registry.access.redhat.com/ubi8/nodejs-14:latest"
  Normal  Pulled          5m26s  kubelet            Successfully pulled image "registry.access.redhat.com/ubi8/nodejs-14:latest" in 6.074923684s
  Normal  Created         5m9s   kubelet            Created container runtime
  Normal  Started         5m9s   kubelet            Started container runtime
```

Seems that the files are there (from pod terminal):

```
sh-4.4$ ls /project/
README.md  devfile.yaml  helm  node_modules  openshift  package-lock.json  package.json  server.js  tests  views
```
From pod log, it seems that the application is killed on stop of CRC, and never started again when CRC are started:
ODO_COMMAND_RUN is not run after CRC restart, just with the initial odo push.

```
time="2021-06-24T09:55:14Z" level=info msg="create process:devrun"
time="2021-06-24T09:55:14Z" level=info msg="create process:debugrun"
time="2021-06-24T09:55:34Z" level=debug msg="no auth required"
time="2021-06-24T09:55:34Z" level=debug msg="succeed to find process:devrun"
time="2021-06-24T09:55:34Z" level=info msg="try to start program" program=devrun
time="2021-06-24T09:55:34Z" level=info msg="success to start program" program=devrun
ODO_COMMAND_RUN is npm start
Changing directory to /project
Executing command cd /project && npm start

> nodejs-ex@0.0.1 start /project
> node server.js

Server running on http://0.0.0.0:8080
time="2021-06-24T09:55:35Z" level=debug msg="wait program exit" program=devrun
time="2021-06-24T09:55:36Z" level=debug msg="no auth required"
10.217.0.1 - - [24/Jun/2021:09:56:52 +0000] "GET / HTTP/1.1" 200 40430 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
10.217.0.1 - - [24/Jun/2021:09:56:52 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://http-8080-nodejs-nodejs-ex-cohf-srrtest.apps-crc.testing/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
time="2021-06-24T09:56:59Z" level=info msg="receive a signal to stop all process & exit" signal=terminated
time="2021-06-24T09:56:59Z" level=info msg="stop the program" program=devrun
time="2021-06-24T09:57:00Z" level=info msg="force to kill the program" program=devrun
time="2021-06-24T09:57:01Z" level=error msg="program stopped with error:signal: terminated" program=devrun
time="2021-06-24T09:57:01Z" level=info msg="Stopped by user, don't start it again" program=devrun
time="2021-06-24T09:57:01Z" level=info msg="stop the program" program=debugrun
time="2021-06-24T10:01:12Z" level=info msg="create process:devrun"
time="2021-06-24T10:01:12Z" level=info msg="create process:debugrun"
```

Output from ps -ef shows that the app is not running on the pod:
```
sh-4.4$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
1000610+       1       0  0 10:01 ?        00:00:00 /opt/odo/bin/supervisord -c /opt/odo/conf/devfile-supervisor.conf
1000610+      16       0  0 10:03 pts/0    00:00:00 sh
1000610+      30       0  0 10:13 pts/1    00:00:00 sh
1000610+      37       0  0 10:17 pts/2    00:00:00 sh
1000610+      45      37  0 10:17 pts/2    00:00:00 ps -ef
```

Doing a manual cd /project and then npm start makes the application work again.
But if I I scale an additional pod (from 1->2), the newly created pod has empty /project folder and does not run any application.

**Comment by steinrr** [comment]
Can it be that it creates a persistent volume, but it is actually not used? I see in the details of the app it says:

![image](https://user-images.githubusercontent.com/12039073/123248346-184af980-d4e8-11eb-80fb-46a5f2057b0c.png)

So even if it creates a PVC called odo-projects-nodejs-nodejs-ex-cohf-oxts-vol, it seems to use the one called odo-projects, which is actually still an EmptyDir.

**Comment by kadel** [comment]
> Output from ps -ef shows that the app is not running on the pod:

This looks like an issue in odo. 
odo is starting application via SupervisorD. After first start it should configure SupervisorD service to automatically restart. It looks like this is not happening. 
Autorestart is still set to `false` :-( 

This is bug in odo.

When creates Depyloment and injects `supervisord` , `/opt/odo/conf/devfile-supervisor.conf`  has `autostart=false` to make sure that the application is not started before the source code is uploaded.
But after the code is uploaded odo should recondiure all services in `/opt/odo/conf/devfile-supervisor.conf`  and set `autostart=true`

**Comment by steinrr** [comment]
> > Output from ps -ef shows that the app is not running on the pod:
> 
> This looks like an issue in odo.
> odo is starting application via SupervisorD. After first start it should configure SupervisorD service to automatically restart. It looks like this is not happening.
> Autorestart is still set to `false` :-(
> 
> This is bug in odo.
> 
> When creates Depyloment and injects `supervisord` , `/opt/odo/conf/devfile-supervisor.conf` has `autostart=false` to make sure that the application is not started before the source code is uploaded.
> But after the code is uploaded odo should recondiure all services in `/opt/odo/conf/devfile-supervisor.conf` and set `autostart=true`

Ok - thanks for investigation. What about this PVC issue? Do I still need to set Ephemeral to false? Is it really using this at all?

**Comment by kadel** [comment]
Yes, it is using the PVC. If you enable persistent mode using `odo
preference set Ephemeral false` odo will use PVC to store source
problem.
The only problem that it doesn't automatically re-starts the
application when the pod fails :-(
We will try to fix that.

**Comment by steinrr** [comment]
Ok - thanks!

**Comment by feloy** [comment]
Also, when setting Ephemeral to false, odo creates a volume named `odo-projects-api-app-vol` but this volume is not used for the project sources, an emptyDir is used instead:

```
      containers:
      - name: runtime
        [...]
        volumeMounts:
        - mountPath: /project
          name: odo-projects
      volumes:
      - name: odo-projects-api-app-vol
        persistentVolumeClaim:
          claimName: odo-projects-api-app
      - emptyDir: {}
        name: odo-projects
```

**Comment by feloy** [comment]
More information about the odo-init container and the supervisorD configuration:

- An init container is defined in the component deployment, that will copy files from the odo-init container to the `/opt/odo` directory (on which is mounted an emptyDir)
- The init container entrypoint is supervisord with the configuration file in `/opt/odo`. 

A solution to make supervisord get a specific configuration when source files are present could be:
- At startup, th emain container should take care if files are present in the `/project` directory, and start supervisord with a specific configuration file (we should add this specific file into the odo-init image, so it is copied with the other configuration file)
- When the files are synced to the container for the first time, odo should modify the configuration of supervisord, and make supervisord take into consideration this new configuration (supervisord is able to hot reload its config when receiving an HUP signal)

**Comment by dharmit** [comment]
> - mountPath: /project
>           name: odo-projects

Should be fixed by #4979

**Comment by feloy** [comment]
There are 2 appls defined in the supervisorD config: devrun & debugrun

```
[program:devrun]
command=/opt/odo/bin/devfile-command devrun
stdout_logfile=/dev/stdout
stdout_events_enabled=true
stderr_logfile=/dev/stderr
stderr_events_enabled=true
stopasgroup=true
killasgroup=true
autostart=true
startretries=0

[program:debugrun]
command=/opt/odo/bin/devfile-command debugrun
stdout_logfile=/dev/stdout
stdout_events_enabled=true
stderr_logfile=/dev/stderr
stderr_events_enabled=true
stopasgroup=true
killasgroup=true
autostart=true
startretries=0

[inet_http_server]
port=localhost:9001
```

If `autostart=true` is set for both, the app will be started twice :(

How can we know at startup which app should run, dev or debug?

**Comment by feloy** [comment]
Fix proposal: https://github.com/openshift/odo-init-image/pull/93

The `devrun` program will be autostarted by supervisord when the container starts, unless there is no file in the PROJECT directory.
