### ISSUE TITLE
Run periodic tests in cluster hosted in IBM Cloud

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#4827]
/kind user-story

## User Story
As a tester I want to run tests on IBM Cloud So that tests run faster and more reliably

## Acceptance Criteria 
- [ ] It should run periodic tests in cluster hosted in IBM Cloud

## Links 
- Related Epic (mandatory): #4800 

/kind user-story

**Comment by dharmit** [comment]
Periodic tests are already running on AWS. Closing this based on discussion with @prietyc123 @anandrkskd 

/close
