### ISSUE TITLE
Roadmap/milestones

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#483]
Is there a roadmap or milestones defined about ODO's next developments ? Which commands will be then developed ? Will it be used too as scaffolding tool ?

**Comment by surajnarwade** [comment]
@kadel , what is the status for this ? do we have doc somewhere for this ?

**Comment by kadel** [comment]
> @kadel , what is the status for this ? do we have doc somewhere for this ?

this will be one of the topics for f2f

**Comment by kadel** [comment]
next odo development is managed using github milestones  https://github.com/openshift/odo/milestones

/close
