### ISSUE TITLE
'odo create --s2i' creates invalid metadata name in devfile.yaml

### ISSUE THREAD

**Issue by sbouchet** [openshift/odo#4839]
/kind bug

## What versions of software are you using?

**Operating System:** RHEL

**Output of `odo version`:** 
```
/home/sbouchet/.odo/cache/2.2.2/odo version
odo v2.2.2 (93b7dd5f9)

Server: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
Kubernetes: v1.20.0+2817867

```

## How did you run odo exactly?
using CLI, creating s2i components with odo 2.2.X ends to have incorrect component Type returned by odo. ComponentTypes are wrongly set to the component name.

## Actual behavior

below the step to reproduce:
1- create dummy component 
2- look at the metadata section of the created devfile
3- describe command returns  wrong info

```
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.2.2/odo create java:latest toto --project stephane-bouchet-dev --app app --s2i
Validation
 ✓  Validating component [211ms]
Conversion
 ✓  Successfully generated devfile.yaml and env.yaml for provided S2I component

Please use `odo push` command to create the component with source deployed
sbouchet@sbouchet:spring-petclinic [master]$ tail devfile.yaml 
    - name: ODO_S2I_CONVERTED_DEVFILE
      value: "true"
    image: registry.redhat.io/openjdk/openjdk-11-rhel7:latest
    mountSources: true
    sourceMapping: /tmp/projects
  name: s2i-builder
metadata:
  name: toto
  version: 1.0.0
schemaVersion: 2.0.0
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.2.2/odo describe
W0623 10:23:24.689170  712783 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Component Name: toto
Type: toto
Environment Variables:
 · DEBUG_PORT=5858
 · ODO_S2I_SCRIPTS_URL=/usr/local/s2i
 · ODO_S2I_SCRIPTS_PROTOCOL=image://
 · ODO_S2I_SRC_BIN_PATH=/tmp
 · ODO_S2I_DEPLOYMENT_DIR=/deployments
 · ODO_S2I_WORKING_DIR=/home/jboss
 · ODO_S2I_BUILDER_IMG=ubi8/openjdk-11
 · ODO_SRC_BACKUP_DIR=/opt/app-root/src-backup
 · ODO_S2I_CONVERTED_DEVFILE=true
URLs:
 · URL named http-8080 will be exposed via 8080
 · URL named http-8443 will be exposed via 8443
 · URL named http-8778 will be exposed via 8778
```
## Expected behavior
creating a devfile components for the same type (springboot) correctly generates metadata: 
```
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.2.2/odo create java-springboot toto --project stephane-bouchet-dev --app app
Devfile Object Validation
 ✓  Checking devfile existence [39724ns]
 ⚠  Git based registries Deprecated  Please see https://github.com/openshift/odo/tree/main/docs/public/git-registry-deprecation.adoc
 ✓  Creating a devfile component from registry: test [149802ns]
Validation
 ✓  Validating if devfile name is correct [64007ns]

Please use `odo push` command to create the component with source deployed
sbouchet@sbouchet:spring-petclinic [master]$ head devfile.yaml 
schemaVersion: 2.0.0
metadata:
  name: java-springboot
  version: 1.1.0
starterProjects:
  - name: springbootproject
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/springboot-ex.git"
components:
sbouchet@sbouchet:spring-petclinic [master]$ /home/sbouchet/.odo/cache/2.2.2/odo describe
W0623 10:34:08.593132  714906 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Component Name: toto
Type: java-springboot
Storage:
 · m2 of size 3Gi mounted to /home/user/.m2
URLs:
 · URL named 8080-tcp will be exposed via 8080
```

## Any logs, error output, etc?

it may be linked to #4816

**Comment by sbouchet** [comment]
CC @dgolovin @jeffmaury

**Comment by kadel** [comment]
Yes, this is related to https://github.com/openshift/odo/issues/4816.

What is `odo create --s2i` doing is actually correct. `metadata.name` field in devfile is actually supposed to be the name of the project, not a type. We originally reused this as a component type because of the limitations of an early devfile v2 version. 

now when the devfile has `metadata.language` field we will use it as a component type. and `metadata.name` will be the component name.

**Comment by girishramnani** [comment]
> What is `odo create --s2i` doing is actually correct. `metadata.name` field in devfile is actually supposed to be the name **of the project, not a type.** We originally reused this as a component type because of the limitations of an early devfile v2 version.

I assume you wanted to say of the **component** and not **project** @kadel?

**Comment by kadel** [comment]
> I assume you wanted to say of the "name of **component** and not **project**"@kadel?

yes

**Comment by sbouchet** [comment]
ok. so I assume it's a duplicate? is so, you can close it. 
we just want to be sure that odo JSON output response indicates the correct component type.

**Comment by kadel** [comment]
Closing this in favor of https://github.com/openshift/odo/issues/4816

/close
