### ISSUE TITLE
RRD Defect matrix automation 

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4875]
/kind feature
/area testing

Develop scripts to pull issues (bugs) from GitHub into Google sheets to generate defect metrics for:

- [x] Defect backlog [WIP]
- [x] Defect regression
- [x] Defects resolution
- [x] Defects reopen

Related issue: https://github.com/openshift/odo/issues/4649

**Comment by prietyc123** [comment]
**Scope of the issue:**
Write google sheet scripting for api uri satisfy

- [ ] Defect backlog [WIP] (Difference between number of issue opened and closed in a sprint)
- [ ] Defect regression (Issue count satisfying `is:issue label:area/regression label:kind/bug  created:s_date..e_date
`)
- [ ] Defects resolution (Issue count satisfying)
      -  is:issue label:kind/bug label:triage/unresolved 
      - is:issue label:kind/bug is:closed 
      - is:issue label:kind/bug label:triage/duplicate 
      - is:issue label:kind/bug label:triage/not-reproducible 

- [ ] Defects reopen

**Comment by dharmit** [comment]
>  - is:issue label:kind/bug label:triage/unresolved

Maybe consider issues that got closed with `lifecycle/rotten`.

**Comment by prietyc123** [comment]
Acceptance criteria has been met.

/close
