### ISSUE TITLE
Remove unused flags under odo link and odo unlink commands

### ISSUE THREAD

**Issue by valaparthvi** [openshift/odo#4889]
With the new changes to odo link and odo unlink introduced in https://github.com/openshift/odo/commit/843e520f6b6c7085406d6ef9036edf355a0a9896 there are flags such as `--port`, `--wait` and `--wait-for-target`  that can be removed from the codebase.

### Acceptance Criteria - 
1. - [x] odo link 
    1. - [x] Remove `--port` flag and its references
    2. - [x] Remove `--wait` flag and its references
    3. - [x] Remove `--wait-for-target` flag and its references
    4. - [x] Remove `--app`
    5. - [x] Remove `--project`
    4. - [ ] Remove related tests
2. - [x] odo unlink
    1. - [x] Remove `--port` flag and its references
    2. - [x] Remove `--wait` flag and its references
    3. - [ ] Remove related tests
    4. - [x] Remove `--app`
    5. - [x] Remove `--project`

**Comment by feloy** [comment]
Also, there is a lot of code related to Service Catalog in the link/unlink implementation, which will disappear when Service catalogs are not supported.

**Comment by valaparthvi** [comment]
> Also, there is a lot of code related to Service Catalog in the link/unlink implementation, which will disappear when Service catalogs are not supported.

Is that a work in progress? If so, we can raise another issue for it when it is in.

**Comment by dharmit** [comment]
@valaparthvi let's remove all of these flags from `odo link` and `odo unlink`. @kadel already verified that when a component, say `component B`, which exposes multiple ports is linke to `component A`, odo injects into `component A` the configuration related to both the Kubernetes Services created for the two ports that `component B` exposes.

**Comment by dharmit** [comment]
> With the new changes to odo link and odo unlink introduced in [843e520](https://github.com/openshift/odo/commit/843e520f6b6c7085406d6ef9036edf355a0a9896) there are flags such as `--port`, `--wait` and `--wait-for-target` that can be removed from the codebase.

It's more of a side effect of #4777, IMO.

**Comment by valaparthvi** [comment]
> @valaparthvi let's remove all of these flags from `odo link` and `odo unlink`. @kadel already verified that when a component, say `component B`, which exposes multiple ports is linked to `component A`, odo injects into `component A` the configuration related to both the Kubernetes Services created for the two ports that `component B` exposes.

Okay. In any case, we can add a test case(if it doesn't exist already) to ensure that these ports really are injected into the container env.

**Comment by dharmit** [comment]
> Is that a work in progress? If so, we can raise another issue for it when it is in.

#4890

**Comment by mohammedzee1000** [comment]
Hey I had one question here regarding port flag. There is a function DetermineSecretName that uses port. Do we want to alter it so it no longer needs to use port number

**Comment by feloy** [comment]
> Hey I had one question here regarding `--port` flag.
> 
> There is a function DetermineSecretName that uses port as part of common link `complete` (https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/common_link.go#L109).
> 
> Do we want to alter it so it no longer needs to use port number?

It seems to me that this function is never used, now that we are always using devfiles.

More specifically, `o.Context.EnvSpecificInfo` seems to be always non nil, and so most of the code in the `complete` and `run` functions is not used anymore.

@dharmit @kadel WDYT?

**Comment by dharmit** [comment]
+1 to what @feloy said. I stepped through the code and didn't find it useful while trying to link a component to another component. I'd wager it's safe to remove it altogether. 

@mohammedzee1000 could you check if it's getting used while linking a component to a service? If not, we can remove it.

**Comment by mohammedzee1000** [comment]
It seems the tests have already been removed
