### ISSUE TITLE
Remove code and cli docs related to 3.11 and Service Catalog

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4890]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## Expected behavior
OCP 3.11 is not supported any more. Service Catalog is not supported on any supported OCP versions. So, we should remove code and docs related to 3.11 and Service Catalog.

**Comment by dharmit** [comment]
By docs, I mainly mean the CLI docs. The new docs site we're working on isn't going to talk about Service Catalog anyway.

**Comment by mohammedzee1000** [comment]
I guess that kind of makes it simple. I guess this will also involve updating current odo.dev

**Comment by mohammedzee1000** [comment]
Acceptance Criteria (in progress):

## Service catalog

### cli layer

#### odo service list

https://github.com/openshift/odo/blob/e308b6bc8cf9309a5d11f01a59cf84136eb90f74/pkg/odo/cli/service/list.go#L83-L107

### service layer

https://github.com/openshift/odo/blob/e308b6bc8cf9309a5d11f01a59cf84136eb90f74/pkg/service/service.go#L245-L299

**Comment by kadel** [comment]
ping @mohitsuman @dgolovin @jeffmaury @sbouchet This is going to be a big chance that might affect your projects.
