### ISSUE TITLE
Data must be sent even if user terminates the command execution.

### ISSUE THREAD

**Issue by valaparthvi** [openshift/odo#4929]
/kind feature

## Which functionality do you think we should add?
Currently, telemetry data is only sent on the complete execution of a command, but we should also be able to send data in case a user terminates the command(Ctrl+C^).

## Why is this needed?
This will help us understand why the command was terminated, maybe the command took a long time and the user decided to terminate it, if that is the case we will be able to know which commands.

**Comment by valaparthvi** [comment]
cc: @kadel

**Comment by dharmit** [comment]
This provides value for `odo push` taking long. It makes more sense if it also collects the time taken before the user did `Ctrl+C`.

/triage needs-information

**Comment by dharmit** [comment]
My concern is that "why" the user did `Ctrl+C` is something Telemetry can't capture. Or can it? @valaparthvi @kadel?

The fact that `odo push` creates a few resources even in the case when user does `Ctrl+C` and these resources come in the way when user does `odo push` again without doing `odo delete` is something I don't think can be solved by this either.

So, AFAIU, this only provides the information about user doing `Ctrl+C`. Adding the amount of time user waited before hitting `Ctrl+C` to Telemetry can provide some value. Is there anything else that could be in the scope of this issue?

**Comment by kadel** [comment]
> So, AFAIU, this only provides the information about user doing `Ctrl+C`. Adding the amount of time user waited before hitting `Ctrl+C` to Telemetry can provide some value. Is there anything else that could be in the scope of this issue?

We already track how long the command was running. So only things that is missing is to know if odo was terminated by user or finished normally.

**Comment by valaparthvi** [comment]
I got a draft PR https://github.com/openshift/odo/pull/4963 ready and it is in a working state.
It can currently capture `odo push` telemetry data on user interrupt(captures: SIGTERM, SIGQUIT, SIGINT) along with the time.
I'll need to dig more if we also want to capture the signal, but I don't think that data would be of any value to us.
