### ISSUE TITLE
 Remove code related to s2i

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4932]
In #4906 we're removing Service Catalog related code from odo. We also need to remove everything else that's tied to OCP 3.11. Few places to look at:
- s2i code beyond what's helping with `odo create --s2i`
- DeploymentConfigs, maybe?

/kind cleanup

**Comment by mohammedzee1000** [comment]
So far I have found at least two objects that we can consider removing i.e deployment configs and build configs.

Deployment Configs have a usage in a bunch of places across the odo code base.
BuildConfigs seems to mostly be used for building from git and is linked to localconfig (the old odo config)

Both are heavily tied to s2i which we are currently supporting conversion for.

I would assume we want to keep localconfig structs around for a bit longer to support conversion of existing local config components. 

So the first step would be to remove build configs and deployment configs from occlient (while removing usages across odo code). The only other openshift only resource is route but that is not heavily tied to s2i and is in fact used in devfile as well

wdyt @dharmit @mik-dass ?

**Comment by dharmit** [comment]
>  BuildConfigs seems to mostly be used for building from git and is linked to localconfig (the old odo config)

@kadel how long should we support `odo create --git` and `odo create --binary`? How much do the Adapters folks rely on it? cc @mohitsuman



> The only other openshift only resource is route but that is not heavily tied to s2i and is in fact used in devfile as well

Right. Route has to be kept as-is.

**Comment by kadel** [comment]
title got me confused. I'm not sure how 3.11 support is related to s2i 

/title Remove code related to s2i

Lets be a little nice to our users:
First lets add a  deprecation notice to s2i related features
  - add deprecation warning when someone executes `odo create --s2i`
  - add deprecation warning when someone executes `odo create --binary`
  - add deprecation warning when someone executes `odo create --git` or `odo create --ref`
  - 
After the warning is there for at least one release we can start removing it.
- removing all flags related to s2i from `odo create`
- remove everything that touches DeploymentConfigs, BuildConfigs, ImageStreams
- remove everything that touches LocalConfig `.odo/config.yaml`

**Comment by mohammedzee1000** [comment]
I don't think we need to remove s2i support as is as we have devfile conversation for s2i.
But we should remove server side implementation that is openshift specific  as it's not likely to be used anymore due to conversion.
@kadel @dharmit wdyt

**Comment by mohammedzee1000** [comment]
But for git I think it makes sense to deprecate git first

**Comment by mohammedzee1000** [comment]
Based on the information I have gathered:
 - odo create --s2i converts to devfile automatically
 - odo push does not convert existing s2i component
 - While we have conversion code, we dont seem to have a command to convert s2i to devfile

I agree with @kadel that this will have to happen in 2 phases

**1. Deprecation**
   1. odo push with s2i component should show deprecation and recommend the user to recreate component with --s2i flag to allow automatic conversion to devfile
   2. usage of `--git` should throw deprecation warning that this will no longer be supported (unless we can support git for devfile)

**2. Removal**
 - Drop support and strip dcand buildconfigs. Image streams should continued to be supported for as long as we support conversion of s2i to devfile

**Comment by kadel** [comment]
> * Drop support and strip dcand buildconfigs. Image streams should continued to be supported for as long as we support conversion of s2i to devfile

The goal is to drop s2i to devfile conversion as well.

**Comment by mohammedzee1000** [comment]
> > * Drop support and strip dcand buildconfigs. Image streams should continued to be supported for as long as we support conversion of s2i to devfile
> 
> The goal is to drop s2i to devfile conversion as well.

I guess it still kinda holds true :D, just more quickly

**Comment by mohammedzee1000** [comment]
Task 1: #4951
Task 2: 4952

**Comment by mohitsuman** [comment]
> @kadel how long should we support `odo create --git` and `odo create --binary`? How much do the Adapters folks rely on it? cc @mohitsuman

@dharmit Regarding the workflow from adapters, it should be fine if we gradually deprecate the `git` and `binary` create component  support.

**Comment by valaparthvi** [comment]
Replying to: https://github.com/openshift/odo/issues/4932#issuecomment-888071007
>While we have conversion code, we dont seem to have a command to convert s2i to devfile

@mohammedzee1000 I think we do. There is subcommand `convert-to-devfile` under `odo utils` which seems to be doing just this.
