### ISSUE TITLE
[Telemetry] Add data about s2i vs devfile component

### ISSUE THREAD

**Issue by valaparthvi** [openshift/odo#4933]
/kind feature

## Which functionality do you think we should add?
Telemetry should show whether components created are s2i vs devfile.

## Why is this needed?
This is needed so that we can know how many people are still using s2i and devfile.

# Acceptance Criteria 
- [ ] `odo create` should send data about this.
- [ ] TBD

**Comment by kadel** [comment]
Probably not worth it as we are already planning to remove s2i related code https://github.com/openshift/odo/issues/4932

/close
