### ISSUE TITLE
`odo create` errored out but created devfile.yaml

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4939]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

```
▶ mkdir asdf
▶ ls

▶ odo create nodejs --starter=ffff
Devfile Object Validation
 ✓  Checking devfile existence [24770ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [55600ns]
Validation
 ✓  Validating if devfile name is correct [33970ns]
 ✗  the project: ffff specified in --starter does not exist, available projects: nodejs-starter

▶ ls
devfile.yaml
```

## Actual behavior
`odo create`  failed but `devfile.yaml` was created

## Expected behavior
if `odo create` fails it should not create `devfile.yaml

**Comment by kadel** [comment]
/priority high

This can be especially confusing if user tries to run `odo create` again with a different devfile

```
▶ odo create nodejs --starter=asdf
Devfile Object Validation
 ✓  Checking devfile existence [18290ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [40250ns]
Validation
 ✓  Validating if devfile name is correct [46130ns]
 ✗  the project: asdf specified in --starter does not exist, available projects: nodejs-starter

▶ odo create java --starter
Devfile Object Validation
 ✓  Creating a devfile component from devfile path: /home/tomas/Code/odo-examples/spring-petclinic/asadf/devfile.yaml [23760ns]
Validation
 ✓  Validating if devfile name is correct [13090ns]

Please use `odo push` command to create the component with source deployed

▶ ls
devfile.yaml  LICENSE  package.json  package-lock.json  README.md  server.js  test

```

now there is a have nodejs project, but the command was ` odo create java --starter`. This is due to local devfile.yaml being used for second odo create command

**Comment by mohammedzee1000** [comment]
reproduced
```bash
> odo create nodejs --starter=asdf
Devfile Object Validation
 ✓  Checking devfile existence [73869ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [106509ns]
Validation
 ✓  Validating if devfile name is correct [195353ns]
 ✗  the project: asdf specified in --starter does not exist, available projects: nodejs-starter
> odo create java --starter
Devfile Object Validation
 ✓  Creating a devfile component from devfile path: /home/mzee1000/workbench/work/testbench/node-ex/devfile.yaml [54530ns]
Validation
 ✓  Validating if devfile name is correct [129910ns]

Starter Project
 ✓  Downloading starter project nodejs-starter from https://github.com/odo-devfiles/nodejs-ex.git [725ms]

Please use `odo push` command to create the component with source deployed
> ls -a
.  ..  devfile.yaml  .gitignore  LICENSE  .odo  package.json  package-lock.json  README.md  server.js  test
```

**Comment by mohammedzee1000** [comment]
The problem here is that we basically need to download devfile from the registry before we can read it and validate some of the information.

I feel that the best solution is that devfile is downloaded to a temp location, validated, and only then moved to the expected location.

Another possible solution is if an error occurs during devfile validation, any error then part of handling that error should include removal of devfile. I would prefer option 1. wdyt @kadel @kadel

**Comment by dharmit** [comment]
> The problem here is that we basically need to download devfile from the registry before we can read it and validate some of the information.

PTAL how `odo catalog describe <component-name>` and `odo catalog describe <component-name> -o json` work. 

That command downloads devfile in memory, and we have a helper function already to get starter projects. Combining that, IMO, we could do something similar in `odo create`.

https://github.com/openshift/odo/blob/9c4a3f7f35afa1538e5141043cc24056965c32a1/pkg/odo/cli/catalog/describe/component.go#L141-L149

**Comment by mohammedzee1000** [comment]
Ah yea, that makes sense. Based on this input, I guess we are going ahead with method 1

So acceptance criteria are in essence to:

- [ ] Parse devfile in-memory as done in describing catalog component (as in the excerpt above)
- [ ] Add test to ensure that devfile i non-existent in case of failure

**Comment by dharmit** [comment]
>  Parse devfile in-memory as done in describing catalog component (as in the excerpt above)

But at the moment, `odo create` downloads the devfile.yaml before doing the check for starter project. Should that workflow be changed to create the devfile.yaml only when validation passes? And what about the messages we print on the CLI?

```shell
$ odo create nodejs --starter=ffff
Devfile Object Validation
 ✓  Checking devfile existence [24770ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [55600ns]
Validation
 ✓  Validating if devfile name is correct [33970ns]
 ✗  the project: ffff specified in --starter does not exist, available projects: nodejs-starter
```

Should we not print any of these messages? Or should we only add a message at the end which tells the user that a component was not created?

Another approach could be to not change anything we're doing right now and simply delete the devfile.yaml when the check for starter project fails. 

@feloy @mik-dass @valaparthvi what do you folks think we should do here?

**Comment by feloy** [comment]
Failing as soon as possible by checking the starter sooner is a quick win.

But if there are already other issues where `odo` is failing and leaving files behind it, it could be interesting to have some kind of rollback strategy (either by creating the files first in a temp dir, or by cleaning the created files on failure)
