### ISSUE TITLE
Deprecate s2i and localconfig

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4951]
As the first step of #4932 we need to deprecate all s2i operations

/kind cleanup
/priority High

Acceptance Criteria:
- [ ] add deprecation warning when someone executes `odo create --s2i`
- [ ] add deprecation warning when someone executes `odo create --binary`
- [ ] add deprecation warning when someone executes `odo create --git` or `odo create --ref`
- [ ] add deprecation warning when someone executed `odo push` with existing local config, recommending them to delete a component and recreate with `odo create --s2i` flag to allow automatic conversion.

**Comment by valaparthvi** [comment]
> add deprecation warning when someone executed `odo push` with existing local config, recommending them to delete a component and recreate with `odo create --s2i` flag to allow automatic conversion.

@mohammedzee1000 I do not understand the part about recreating with `odo create --s2i` if we are also going to add deprecation warning for `odo create --s2i`. Can you elaborate more on this?

**Comment by mohammedzee1000** [comment]
> > add deprecation warning when someone executed `odo push` with existing local config, recommending them to delete a component and recreate with `odo create --s2i` flag to allow automatic conversion.
> 
> @mohammedzee1000 I do not understand the part about recreating with `odo create --s2i` if we are also going to add deprecation warning for `odo create --s2i`. Can you elaborate more on this?

@valaparthvi 

What I meant is if user does odo push, with local config then push doesn't convert. There fore as part of deprecation warning we either tell them to use devfile proper or if they wish to use s2i builder image, then the simplest way is to delete existing stuff and recreate with s2i flag which does the conversation.
