### ISSUE TITLE
Drop support for s2i and localconfig

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4952]
In the second step of #4932 we need to deprecate all s2i operations

/kind cleanup
/priority High

Acceptance Criteria:

Try to open smaller PRs.

- [x] removing all flags related to s2i from odo create
- [ ] remove everything that touches DeploymentConfigs, BuildConfigs, ImageStreams
- [ ] remove everything that touches LocalConfig .odo/config.yaml
- [ ] Close user story #4932 when this closes

**Comment by mohammedzee1000** [comment]
Just marking it as needs info to make it clear we wont hanlde it in this sprint
/triage needs-information

**Comment by dharmit** [comment]
Need to figure out what's still pending on this one.
