### ISSUE TITLE
odo can't create link using  client-side service binding library if user doesn't have permissions to list cluster wide resources

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4965]
Original epic: https://github.com/openshift/odo/issues/4543

It looks like service binding library is trying to get cluster-wide resources.
This is especially problematic on OpenShift as normal cluster users usually don't have permissions to do so.
If the code base is supposed to be useful as a library it should avoid calls that require special privileges.

Issue reported to SBO: https://github.com/redhat-developer/service-binding-operator/issues/1003

/priority high
/kind bug

**Comment by dharmit** [comment]
/status blocked

Blocked on https://github.com/redhat-developer/service-binding-operator/issues/1003

**Comment by kadel** [comment]
Based on information in

https://github.com/redhat-developer/service-binding-operator/issues/1003#issuecomment-891906752

It looks like there's is an option to make the Pipeline skip reading cluster wide resources by providing custom context.


/remove-status blocked

**Comment by kadel** [comment]
Process of how one can customize pipeline to skip reading CRDs is explained in video in this comment https://github.com/redhat-developer/service-binding-operator/issues/1003#issuecomment-901008042

**Comment by valaparthvi** [comment]
@kadel What type of user do you suggest I create to recreate this? I am having a hard time just recreating this bug :/

**Comment by valaparthvi** [comment]
I think I managed to recreate it - 
```shell
$ odo link mypy         
 ✓  Successfully created link between component "mynode" and component "mypy"

To apply the link, please use `odo push`
$ odo push --show-log -f

Validation
 ✓  Validating the devfile [98216ns]

Creating Services for component mynode
 ✓  Services are in sync with the cluster, no changes are required

Creating Kubernetes resources for component mynode
 ✓  Waiting for component to start [273ms]
 ✗  Failed to start component with name "mynode". Error: Failed to create the component: failed to create service(s) associated with the component: please install the service binding operator
```
Can you confirm it? @kadel

**Comment by valaparthvi** [comment]
Nevermind, I got it.

**Comment by kadel** [comment]
@valaparthvi, I'm not sure if it was said somewhere, but it is quite important to make sure that if user has permission to read CRD it will use the information from CRD. If user doesn't have permissions it should skip it without failing. Ideal when the CRDs are skipped it should print warning informing user that due to lack of permissions binding information on CRDs will not be checked.

**Comment by valaparthvi** [comment]
I'll add the warning part, but as far as I can tell, if the user has access to CRD, it will take CRD into account, because the only thing I will be adding is to check if the error is of type `Forbidden` and if so, you continue.

**Comment by kadel** [comment]
> if the user has access to CRD, it will take CRD into account, because the only thing I will be adding is to check if the error is of type `Forbidden` and if so, you continue.

:+1:
