### ISSUE TITLE
Remove the unnecessary use of --context from tests/integration/component.go

### ISSUE THREAD

**Issue by valaparthvi** [openshift/odo#4971]
/kind cleanup

There seems to be an unnecessary use of --context directory in [tests/integration/component.go::When("in context directory", func(){})](https://github.com/openshift/odo/blob/main/tests/integration/component.go#L116).

The test checks for when inside the context directory, which means the use of the `--context` flag is unnecessary, and in a way, these tests are not being tested the way they should be, which is without the flag.

**Comment by dharmit** [comment]
/close

this issue is focussed on s2i tests which we're anyway removing.
