### ISSUE TITLE
Strip out remaining unused service catalog code from odo linking

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4978]
Follow up of #4890
/kind cleanup

**Comment by kadel** [comment]
this should be done in https://github.com/openshift/odo/pull/4906

**Comment by mohammedzee1000** [comment]
@kadel as discussed in standup, the link code has altered since I last researched the original issue. Therefore we decided it is better halt the pr where it is and get it in and then do the link update separately.

I will need to look at the link and serivce catalog code again properly which chould cause the pr to spillover again

**Comment by dharmit** [comment]
> this should be done in #4906

The reason I recommended freezing #4906 was it was going beyond Service Catalog. It started removing code for linking/unlinking components. I am being pedantic here and want to ensure that the PRs don't get too big.

**Comment by kadel** [comment]
> The reason I recommended freezing #4906 was it was going beyond Service Catalog. It started removing code for linking/unlinking components. I am being pedantic here and want to ensure that the PRs don't get too big.

ok
