### ISSUE TITLE
Capture OS info in telemetry

### ISSUE THREAD

**Issue by deboer-tim** [openshift/odo#4994]
/kind feature

## Which functionality do you think we should add?
Telemetry from other tools typically includes additional context information including OS and location or timezone, e.g.:
```
  "context": {
    "locale": "en-US",
    "location": {
      "country": "TH"
    },
    "os": {
      "name": "Mac",
      "version": "20.6.0"
    },
    "timezone": "Asia/Bangkok"
    ...
  }
```
I'm not suggesting we need to send all of this, but the OS and locale or timezone would be useful.

## Why is this needed?
This should help us get a better idea of what platforms our users are on and where in the world they are, which in turn should help us focus our efforts.

## Acceptance Criteria

- [ ] Docs to help new folks understand debugging with telemetry code
- [ ] Capturing the info related to "Locale", "Timezone", and "Location".

**Comment by deboer-tim** [comment]
I'll admit I do see a graph showing OS breakdown, but I can't tell where the data for this is coming from...

@valaparthvi

**Comment by kadel** [comment]
> I'll admit I do see a graph showing OS breakdown, but I can't tell where the data for this is coming from...


OS info gets send as part of the "identify" event. Those properties get assigned to "People". You can see it in properties in  "People" section

**Comment by deboer-tim** [comment]
Ok, there are no identify events in Segment at the moment which explains why I couldn't see it there. I also clicked in the properties as suggested, and about half didn't have an OS listed. Most other components are including the OS in every event as per the first comment, so I think this request is still valid.

**Comment by valaparthvi** [comment]
>I also clicked in the properties as suggested, and about half didn't have an OS listed.

If you checked the properties for TRACK event, that might explain why you didn't see any OS listed, we only show this information in IDENTIFY event, which is when a new user joins in.

**Comment by valaparthvi** [comment]
> > I also clicked in the properties as suggested, and about half didn't have an OS listed.
> 
> If you checked the properties for TRACK event, that might explain why you didn't see any OS listed, we only show this information in IDENTIFY event, which is when a new user joins in.

Segment only seems to be keeping data from the past day, maybe that's the reason why you didn't find any IDENTIFY event. @deboer-tim  Do you think it adds value to add OS and location information in TRACK events as well?

PS: I've added this issue to be discussed in the next grooming call.

**Comment by kadel** [comment]
@valaparthvi 
Let's add location data into identify event.

> I also clicked in the properties as suggested, and about half didn't have an OS listed.

This is a big problem. We need to find why is this happening.  28% of people that did some action in past 90 days don't have OS info.

**Comment by kadel** [comment]
> This is a big problem. We need to find why is this happening. 28% of people that did some action in past 90 days don't have OS info.

Checking the code I found the problem. It looks like odo is sending Identify event only when new `anonymousId` is created (https://github.com/openshift/odo/blob/3642d17f09ed09dc0bb0265653b9236328fcba24/pkg/segment/segment.go#L160-L164). If  user already has `anonymousId` from other tools (crc, vscode etc...) odo won't send the identify event with OS info

**Comment by valaparthvi** [comment]
It's not a problem. It was made that way. We made it that way to avoid the time it took to send telemetry data, but if this seems like a problem now, we can fix it since time is not an issue anymore.

**Comment by valaparthvi** [comment]
>If user already has anonymousId from other tools (crc, vscode etc...) odo won't send the identify event with OS info

Right, in that case we might have to send IDENTIFY with every TRACK event, because there is no way to check what users are registered with segment.

**Comment by deboer-tim** [comment]
FWIW other tools appear to just be including the context in every track event, not sending additional identify events.

**Comment by dharmit** [comment]
IIUC, #5040 handled the part of capturing OS info upon every odo event. What's missing now is the locale info, right? Also, where are you folks checking the data? Segment? Woopra? Both? I'll admit that I have access to both, but I have never looked at either unless when reviewing PRs; even then only Segment. Woopra is quite alien to me.

**Comment by valaparthvi** [comment]
> IIUC, #5040 handled the part of capturing OS info upon every odo event. What's missing now is the locale info, right? 

I think what we are missing is the location data. @deboer-tim I hope the changes brought by #5040 serves your purpose; it sends IDENTIFY with every TRACK event so that you can see OS information. Do you still prefer we add OS information to TRACK?

> Also, where are you folks checking the data? Segment? Woopra? Both? I'll admit that I have access to both, but I have never looked at either unless when reviewing PRs; even then only Segment. Woopra is quite alien to me.

@dharmit I usually check Segment. I think Tomas and Time are well versed with Woopra. Woopra has some useful graphs, and it's easier to deduce patterns with those graphs.

**Comment by dharmit** [comment]
@deboer-tim can you point me to some project that's fetching the time zone info as you have mentioned in issue description - `"timezone": "Asia/Bangkok"`? I'm asking because I'm having a hard time figuring out how to get IANA format tz info using Go. 😞 

The value obtained using `time.Now().Zone()` gives zones like `IST` which are ambiguous, i.e., IST stands for Indian Standard Time as well as Israel Standard Time.

I haven't tried figuring the location info yet, but I suspect hitting a wall on that as well.

**Comment by feloy** [comment]
> @deboer-tim can you point me to some project that's fetching the time zone info as you have mentioned in issue description - `"timezone": "Asia/Bangkok"`? I'm asking because I'm having a hard time figuring out how to get IANA format tz info using Go. 
> 
> The value obtained using `time.Now().Zone()` gives zones like `IST` which are ambiguous, i.e., IST stands for Indian Standard Time as well as Israel Standard Time.
> 
> I haven't tried figuring the location info yet, but I suspect hitting a wall on that as well.

@dharmit  I'm not sure the precise location in the timezone is available in a time description (it is more a configuration information of a system IMO). But you also get the offset in the reply of Zone(), with which you can write something like UTC+5

**Comment by dharmit** [comment]
> But you also get the offset in the reply of Zone(), with which you can write something like UTC+5

Yes. That's the best I could figure out. But getting IANA format seems impossible to me right now. And because of that, I'm inclined to believe that getting Location info, as Tim has mentioned in issue description, would also be non-trivial.

**Comment by kadel** [comment]
> @deboer-tim can you point me to some project that's fetching the time zone info as you have mentioned in issue description - `"timezone": "Asia/Bangkok"`? I'm asking because I'm having a hard time figuring out how to get IANA format tz info using Go.

It looks like it is from vscode telemetry (https://github.com/redhat-developer/vscode-redhat-telemetry/blob/a7b19aa3d5d4982e701cfe61408f354ca6792b72/src/utils/events.ts#L135-L141)

**Comment by deboer-tim** [comment]
Agreed this is language dependent - looking at Segment I see several Node and Java clients that are sending things like `"timezone": "Asia/Calcutta"` and `"timezone": "America/Indiana/Indianapolis"` but none from the other Go sources.

IMHO the fundamental problem I was seeing was due mostly to the missing identify events than anything else though, so I'd be happy closing once we know that there is at least one identify event being sent with whatever information we can easily get from Go. Ideally this would not be sent from every command since that will double our event usage, but once the first time you use odo and then only if anything in the content changes (or if it's any cheaper, just every couple weeks).

**Comment by dharmit** [comment]
How do you prefer to get the location information? If simply by converting the time zone information, it might be doable with some effort. But that's prone to be inaccurate or even ambiguous because a time zone like "IST" could translate to multiple zones, and "UTC +0530" also corresponds to more countries than just India.

What we will have as a result of #5040, #5066 & #5067 is the info about user's OS, time zone and locale every time they execute any odo command.

**Comment by dharmit** [comment]
@deboer-tim the PRs to fetch locale and timezone info have been merged. I'm closing this PR since capturing location information is not possible without some third-party tool, as far as we understand.

/close
