### ISSUE TITLE
odo test statistics dashboard not working

### ISSUE THREAD

**Issue by anandrkskd** [openshift/odo#5006]
/area testing

Currently odo test statistics dashboard[1] is not working for PR job or periodic jobs. Dashboard help in assigning the flakes the correct priority.

1. [Dashboard](https://gist.github.com/anandrkskd/102d08389c61e7f7293570bf38205d3b) 
 
Why is this needed?
Keep tracking of flakes.

**Comment by anandrkskd** [comment]
Acceptance criteria:
- dashboard should contain
- [ ] PR flakes
- [ ] Periodic failure

**Comment by anandrkskd** [comment]
Observation:
- [ ]  PR Flakes can be fixed with updated url
- [ ] Periodic failure need
   - [ ] update of url
   - [ ] change in code to use both master and main urls

**Comment by prietyc123** [comment]
Dashboard is working as expected.

/close
