### ISSUE TITLE
odo storage list json items[].kind data is case sensitive

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#5037]
/kind bug

## What versions of software are you using?

**Operating System:**All supported

**Output of `odo version`:** main

## How did you run odo exactly?

$ odo project create test
$ odo create nodejs ozeymw --context . --project test
$ odo storage create mystorage --path=/opt/app-root/src/storage/ --size=1Gi --context .
$ odo storage list --context . -o json

## Actual behavior

Sometimes list out contains capitalised `"kind": "Storage"` data sometimes not.
```
Running odo with args [odo storage list --context /tmp/122983734 -o json]

[ssh:Fedora-32-minikube] [odo] {

[ssh:Fedora-32-minikube] [odo] 	"kind": "List",

[ssh:Fedora-32-minikube] [odo] 	"apiVersion": "odo.dev/v1alpha1",

[ssh:Fedora-32-minikube] [odo] 	"metadata": {},

[ssh:Fedora-32-minikube] [odo] 	"items": [

[ssh:Fedora-32-minikube] [odo] 		{

[ssh:Fedora-32-minikube] [odo] 			"kind": "Storage",

[ssh:Fedora-32-minikube] [odo] 			"apiVersion": "odo.dev/v1alpha1",
[...]
```

2nd run
```
$ odo storage list --context . -o json
{
        "kind": "List",
        "apiVersion": "odo.dev/v1alpha1",
        "metadata": {},
        "items": [
                {
                        "kind": "storage",
                        "apiVersion": "odo.dev/v1alpha1",
[...]
```

## Expected behavior
items[].kind should not be case sensitive.

**Comment by feloy** [comment]
Note that the change "storage" -> 'Storage' happened on https://github.com/openshift/odo/pull/4948
It should be only uppercase now
