### ISSUE TITLE
Some integration tests still using the production devfile registry

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#5056]
A while back https://github.com/openshift/odo/pull/4752 was merged to move the odo integration tests from using the production devfile registry (https://registry.devfile.io) to staging (https://registry.stage.devfile.io) as we didn't want the telemetry for the devfile registry polluted.

We recently set up telemetry on the devfile registry service and saw a **ton** of pollution coming back from what appears to be an automated process, for both listing devfiles, and download nodejs & python stacks. Since odo's integration tests primarily test with those stacks (mainly nodejs, but also python for link/unlink tests), we suspected it would be these tests.

I looked through odo's integration tests and saw that the following test files call out to the registry but don't set the registry to staging:
- cmd_link_unlink_test.go: `odo create` without `--s2i` flag
- cmd_pref_config_test.go: `odo create` without `--s2i` flag
- operatorhub/cmd_link_test.go `odo create` without `--s2i` flag
- operatorhub/cmd_service_test.go `odo create` without `--s2i` flag
- component.go: `odo create` without `--s2i` flag and `odo catalog list components`
- generic_test.go: `odo catalog list components`

I wonder if would be more straightforward to call `helper.SetDefaultDevfileRegistryAsStaging()` from within `helper.CommonBeforeEach()` so that helper.SetDefaultDevfileRegistryAsStaging() doesn't have to be called from each individual test file?

**Comment by dharmit** [comment]
> I wonder if would be more straightforward to call `helper.SetDefaultDevfileRegistryAsStaging()` from within `helper.CommonBeforeEach()` so that helper.SetDefaultDevfileRegistryAsStaging() doesn't have to be called from each individual test file?

This made sense to me. I have opened #5057 which could address the issue.

**Comment by GeekArthur** [comment]
Link to the main telemetry issue: https://github.com/devfile/api/issues/281
