### ISSUE TITLE
Update operator document about mphealth version for Z

### ISSUE THREAD

**Issue by xkwangcn** [openshift/odo#5071]
/kind documentation

## What mistake did you find / what is missing in the documentation?

For JPA part In https://odo.dev/docs/tutorials/deploying-java-app-with-database, Z don’t support mphealth-3.0 version based their openliberty image, so in https://github.com/OpenLiberty/application-stack-samples.git, need to change to mphealth-2.0 for Z. We want doc the change here to replace the version by one command like `sed`.

**Comment by xkwangcn** [comment]
https://github.com/OpenLiberty/application-stack-samples/blob/main/jpa/src/main/liberty/config/server.xml

**Comment by dharmit** [comment]
@xkwangcn are you suggesting that a change needs to be made in https://github.com/OpenLiberty/application-stack-samples.git?

**Comment by xkwangcn** [comment]
No. I mean maybe we can add a new point before this [line](https://odo.dev/docs/tutorials/deploying-java-app-with-database/#:~:text=Initialize%20the%20application%3A). - 3. Initialize the application:

In case of IBM Z and Power architectures, replace mphealth version using below command:
`sed -i "s/mpHealth-3.0/mpHealth-2.0/" src/main/liberty/config/server.xml`

**Comment by scottkurz** [comment]
There's a more fundamental issue here, which is that the https://odo.dev/docs/tutorials/deploying-java-app-with-database/  sample uses the java-openliberty devfile in the default devfile registry, which uses the **openliberty/application-stack** image that is amd64 only.   

We plan to publish multi-arch versions of this image for p/z but haven't yet.   

I'm confused because documenting the use of an alternative devfile with alt. image seems to be required before changing the Liberty config (server.xml) within the doc.

**Comment by xkwangcn** [comment]
> There's a more fundamental issue here, which is that the https://odo.dev/docs/tutorials/deploying-java-app-with-database/ sample uses the java-openliberty devfile in the default devfile registry, which uses the **openliberty/application-stack** image that is amd64 only.
> 
> We plan to publish multi-arch versions of this image for p/z but haven't yet.
> 
> I'm confused because documenting the use of an alternative devfile with alt. image seems to be required before changing the Liberty config (server.xml) within the doc.

Hello, sorry, what do you mean for this?

**Comment by xkwangcn** [comment]
For this part https://odo.dev/docs/tutorials/deploying-java-app-with-database#importing-the-jpa-microservice, here is the update sample doc we want:

In this example we will use odo to manage a sample Java JPA MicroService application.
1. Clone the sample application to your system:
```
git clone https://github.com/OpenLiberty/application-stack-samples.git
```
2. Go to the sample JPA app directory:
```
cd ./application-stack-samples/jpa
```
3. In case of IBM Z and Power architectures, replace mpHealth version using below command:
```
sed -i "s/mpHealth-3.0/mpHealth-2.0/" src/main/liberty/config/server.xml
```
4. Initialize the application:
```
odo create java-openliberty mysboproj
```

`java-openliberty` is the type of your application and `mysboproj` is the name of your application.

@scottkurz Is this clear? 
I will do the verify again next week. any issues from your side pls let me know, thanks ~~

**Comment by scottkurz** [comment]
I'm just confused how is the user supposed to end up with the z/p devfile?   

Are you expecting them to create it themselves, using the image mentioned here:  
https://odo.dev/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power

I see instructions there to create a devfile registry but not a devfile itself.   

If that's the expectation, that could be OK, I'm just trying to understand the workflow..since these are tutorials and we're walking them through carefully, step-by-step, and the devfile creation is something I'd have expected to see documented.

**Comment by xkwangcn** [comment]
OK. Let me put the whole workflow on Z here:
1. clone code
```
[odo@69a3e1a0de8b odo]$ git clone https://github.com/OpenLiberty/application-stack-samples.git
Cloning into 'application-stack-samples'...
remote: Enumerating objects: 616, done.
remote: Counting objects: 100% (212/212), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 616 (delta 74), reused 159 (delta 46), pack-reused 404
Receiving objects: 100% (616/616), 279.41 KiB | 1.46 MiB/s, done.
Resolving deltas: 100% (194/194), done.
```
2. go to jpa
```
[odo@69a3e1a0de8b odo]$ cd ./application-stack-samples/jpa
```
3. create component
```
[odo@69a3e1a0de8b jpa]$ odo create java-openliberty mysboproj
Devfile Object Validation
 ✓  Checking devfile existence [27348ns]
 ✓  Creating a devfile component from registry: IBMDevfileRegistry [67577ns]
Validation
 ✓  Validating if devfile name is correct [45643ns]

Please use `odo push` command to create the component with source deployed
```
4. then can see here is a devfile.yaml, in fact, it's got by OCI resgitry from https://github.com/xkwangcn/registry-support/blob/oldversion/tests/registry/stacks/java-openliberty/devfile.yaml
```
5. vi devfile.yaml, then replace 20.0.0.10 -> 21.0.0.6, replace `registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8` -> `registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8:latest`, then show the devfile.yaml content:
```
[odo@69a3e1a0de8b jpa]$ cat devfile.yaml 
commands:
- exec:
    commandLine: if [ -e /projects/.disable-bld-cmd ]; then echo "found the disable
      file" && echo "devBuild command will not run" && exit 0; else echo "will run
      the devBuild command" && mkdir -p /projects/target/liberty && if [ ! -d /projects/target/liberty/wlp
      ]; then echo "...moving liberty"; mv /opt/ol/wlp /projects/target/liberty; touch
      ./.liberty-mv; elif [[ -d /projects/target/liberty/wlp && ! -e /projects/.liberty-mv
      ]]; then echo "STACK WARNING - LIBERTY RUNTIME WAS LOADED FROM HOST"; fi &&
      mvn -Dliberty.runtime.version=21.0.0.6 package && touch ./.disable-bld-cmd;
      fi
    component: devruntime
    group:
      isDefault: true
      kind: build
    hotReloadCapable: true
    workingDir: /projects
  id: build
- exec:
    commandLine: mvn -Dliberty.runtime.version=21.0.0.6 -Ddebug=false -DhotTests=true
      -DcompileWait=3 liberty:dev
    component: devruntime
    group:
      isDefault: true
      kind: run
    hotReloadCapable: true
    workingDir: /projects
  id: run
- exec:
    commandLine: mvn -Dliberty.runtime.version=21.0.0.6 -Ddebug=false liberty:dev
    component: devruntime
    group:
      kind: run
    hotReloadCapable: true
    workingDir: /projects
  id: run-test-off
- exec:
    commandLine: mvn -Dliberty.runtime.version=21.0.0.6 -DdebugPort=${DEBUG_PORT}
      liberty:dev -Dliberty.env.WLP_DEBUG_REMOTE=y
    component: devruntime
    group:
      isDefault: true
      kind: debug
    hotReloadCapable: true
    workingDir: /projects
  id: debug
- exec:
    commandLine: mvn -Dmicroshed_hostname=localhost -Dmicroshed_http_port=9080 -Dmicroshed_manual_env=true
      -Dmicroshed_app_context_root=/ failsafe:integration-test
    component: devruntime
    group:
      isDefault: true
      kind: test
    hotReloadCapable: true
    workingDir: /projects
  id: test
components:
- container:
    endpoints:
    - exposure: public
      name: ep1
      path: /
      protocol: http
      targetPort: 9080
    image: registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8:latest
    memoryLimit: 1512Mi
    mountSources: true
  name: devruntime
metadata:
  description: Java application stack using Open Liberty runtime
  name: mysboproj
  version: 0.3.0
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/OpenLiberty/application-stack-starters.git
  name: user-app
```
6. run `odo push --show-log`
7. run `odo log` can see:
```
ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.115 s <<< FAILURE! - in org.example.app.it.DatabaseIT
[ERROR] testGetAllPeople  Time elapsed: 0.589 s  <<< ERROR!
java.lang.NullPointerException
	at org.example.app.it.DatabaseIT.testGetAllPeople(DatabaseIT.java:67)

[ERROR] testGetPerson  Time elapsed: 0.043 s  <<< ERROR!
java.lang.NullPointerException
	at org.example.app.it.DatabaseIT.testGetPerson(DatabaseIT.java:55)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DatabaseIT.testGetAllPeople:67 NullPointer
[ERROR]   DatabaseIT.testGetPerson:55 NullPointer
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[ERROR] Integration tests failed: There are test failures.

Please refer to /projects/target/test-reports/it for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[INFO] Tests will run automatically when changes are detected. You can also press the Enter key to run tests on demand.

**Comment by xkwangcn** [comment]
After https://github.com/openshift/odo/issues/5073#issuecomment-923972049 replace 20.0.0.10 -> 21.0.0.6, this is succeed on Z without change mphealth version. So the change about mphealth is not need any more, thank you.

**Comment by xkwangcn** [comment]
@scottkurz 
Hello, After #5073 (comment) replace 20.0.0.10 -> 21.0.0.6, then it is working on Z without change mphealth version. 
So the change about mphealth is not need any more, thanks for your clarification.
This issue can be close from our side, thank you.
