### ISSUE TITLE
Notifications for failing tests 

### ISSUE THREAD

**Issue by kadel** [openshift/odo#5083]
Notification to slack chanell #odo-notifications shoudl be send only for failing tests.

Right now both, sucesfull and failed tests are send there, problem is that if both are reported it is easy to miss failing tests

**Comment by dharmit** [comment]
Maybe just post it to forum-odo if we can post "only" failure messages.

**Comment by anandrkskd** [comment]
We can do it but should be directly start there, I think it would be a good Idea if we are first use odo-notification  and see if it make sense to move it to forum-odo??

**Comment by anandrkskd** [comment]
As discussed in retro call, I will add `@all`/`@here` in `odo-notification`. We will monitor the channel for 1 sprint and if it makes sense to move to main `fourm-odo` channel we will move it.
