### ISSUE TITLE
Document what command "oc app create odo1" does

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#510]
Document what command "oc app create odo1" does within the doc and enhance existing command to describe concretely what will happen

Output of the command issued explains that an application has been created. This concept is very abstract as we don't know what is physically created (openshift project, deploymentconfig, ...)

```
odo app create odo1
Creating application: odo1
Switched to application: odo1

# No openshift resources have been added
oc get all
No resources found.

# odo file has been created
cat ~/.kube/odo
activeApplications:
- active: true
  activeComponent: ""
  name: odo1
  project: odo
```

**Comment by cmoulliard** [comment]
Feedback from @kadel 

When you create an application using the command "odo app create odo1", it just saves the application name to the local config file nothing more under `~/.kube/odo`. Application doesn't have any representations in the cluster. Once you create component in the application, the value from the `odo` config file is used to label the component with the application name so we know which component belongs to which application.

We use standard openshift app label to apply them to the deploymentConfig created including also the related resources such as service, route, ....  and also Kubernetes label app.kubernetes.io so potentially other tools can make use of it (https://docs.google.com/document/d/1EVy0wRJRm5nogkHl38fNKbFrhERmSL_CLNE4cxcsc_M/edit#heading=h.d4sq468sb5i)

**Comment by surajnarwade** [comment]
Closing this since we don't have `odo app create` command
