### ISSUE TITLE
Protocol error during tests

### ISSUE THREAD

**Issue by feloy** [openshift/odo#5116]
/kind bug

## How did you run odo exactly?

The error happens during integration tests, on different clusters (IBM Cloud, PSI)

## Actual behavior

```
protocol error: received *http.http2GoAwayFrame before a SETTINGS frame
Get "https://registry.stage.devfile.io/index": connection error: PROTOCOL_ERROR
```

```
protocol error: received *http.http2GoAwayFrame before a SETTINGS frame
[odo]  ✗  Failed to pull stack nodejs from registry.stage.devfile.io/devfile-catalog/nodejs:latest with allowed media types [application/vnd.devfileio.devfile.layer.v1 image/png image/svg+xml application/vnd.devfileio.vsx.layer.v1.tar application/x-tar]: failed to do request: Head "https://registry.stage.devfile.io/v2/devfile-catalog/nodejs/manifests/latest": connection error: PROTOCOL_ERROR
```

**Comment by kadel** [comment]
This looks it might be something with devfile registry instance or registry library.
Maybe @GeekArthur or @johnmcollier could know something about this.

**Comment by feloy** [comment]
@kadel In your opinion, what would be the effort (installation + maintenance) of having our own devfile registry on the test cluster?

**Comment by kadel** [comment]
> @kadel In your opinion, what would be the effort (installation + maintenance) of having our own devfile registry on the test cluster?

I don't think it is worth it to host our own instance. But we could avoid using devfile registry in most of the tests.

We can modify our test to not use any registry and use devfile.yaml files that are part of our test fixtures instead.

The only tests that are meant to test registry integration would be using remote devfile registry. Theoretically it could be only one test that does that.
