### ISSUE TITLE
PVC resource should not be created by default

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#512]
When a new component is created, then a PVC is automatically added to the project/namespace.

```
odo create openjdk18 sb1 --binary ./target/ocp-fmp-build-install-1.0-exec.jar
Please wait, creating sb1 component ...
...
oc get pvc
NAME          STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
sb1-s2idata   Bound     pv0044    100Gi      RWO,ROX,RWX                   22m
```

I propose that such pvc creation should be optional and defined using a parameter

**Comment by kadel** [comment]
Closing this one.

- We really need some kind of persistent storage to store source code. No way around that.
- No volume is used for git components.
- created https://github.com/openshift/odo/issues/1793 to add "refereneOwner"
