### ISSUE TITLE
using odo with dotnet core

### ISSUE THREAD

**Issue by ramgopireddy** [openshift/odo#5147]
/kind bug

## What versions of software are you using?

**Operating System:**
Mac OS

**Output of `odo version`:**
odo v2.4.0 (b0b2480dc)

## How did you run odo exactly?
odo create dotnet:3.1

## Actual behavior
Devfile Object Validation
 ✗  Checking devfile existence [26524ns]
 ✗  devfile component type "dotnet:3.1" is not supported, please run `odo catalog list components` for a list of supported devfile component types

## Expected behavior
There should be a devfile for dotnet core that can be used. 
This is functional in ODO 2.1 with s2i components. In ODO 2.2 and 2.3 the odo push fails.

**Comment by ramgopireddy** [comment]
It appears this leaves no options to use odo with dotnet core. Is there a functioning devfile that can be used with dotnet core?

**Comment by kadel** [comment]
I've created first draft for .NET devfile v2 for odo. You can find it at https://github.com/kadel/registry/blob/add-dotnet/stacks/dotnet/devfile.yaml

To test it just run following command in empty directory
```
odo create --devfile https://raw.githubusercontent.com/kadel/registry/add-dotnet/stacks/dotnet/devfile.yaml --starter dotnetcore
odo push
```
The above commands should bootstrap new application using example from https://github.com/redhat-developer/s2i-dotnetcore-ex and then push it to cluster to the current namespace/project  using odo.


Or another way to test this with different applications is to just download https://raw.githubusercontent.com/kadel/registry/add-dotnet/stacks/dotnet/devfile.yaml and place it to existing .net project and then just execute `odo push`.


I haven't done much testing beyond the example application, but once we have it working at least to the same degree as what was possible with s2i based devfile I'll submit PR with this devfile to https://github.com/devfile/library

**Comment by kadel** [comment]
@ramgopireddy 

I've created simple devfile v2 with .net 5.0 https://github.com/kadel/registry/tree/add-dotnet/stacks/dotnet50 and .net 3.1 https://github.com/kadel/registry/tree/add-dotnet/stacks/dotnet31

I'll open PR to add them to registry.devfile.io so it shows in odo.


It should cover the basics. Later we can extend .net devfiles with debug support and additional use cases

**Comment by kadel** [comment]
> I'll open PR to add them to registry.devfile.io so it shows in odo.

opened https://github.com/devfile/registry/pull/77

**Comment by mohitsuman** [comment]
@kadel I see the devfile registry now has .NET 5.0 support. But when I run `odo push` for the repo mentioned in the devfile, I encounter the following error:

```
Executing devfile commands for component s2i-dotnetcore-ex
 •  Executing build command "dotnet build -c $CONFIGURATION $STARTUP_PROJECT"  ...
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: app.csproj
 ✗  Executing build command "dotnet build -c $CONFIGURATION $STARTUP_PROJECT" [2s]
 ✗  Failed to start component with name "s2i-dotnetcore-ex". Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c cd ${PROJECTS_ROOT} && dotnet build -c $CONFIGURATION $STARTUP_PROJECT]: 
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: app.csproj
: error while streaming command: command terminated with exit code 1
```

Do you folks also encounter the same while testing with odo 2.3.1 ?

**Comment by kadel** [comment]
> @kadel I see the devfile registry now has .NET 5.0 support. But when I run `odo push` for the repo mentioned in the devfile, I encounter the following error:

I have tested this with odo 2.3.1 and it works ok.

<details>
 <summary>odo with dotnet5.0 starter</summary>

```
▶ odo version
odo v2.3.1 (2ae31fb66)

Server: https://api.crc.testing:6443
Kubernetes: v1.22.0-rc.0+894a78b

▶ odo create dotnet50 --starter dotnet
Devfile Object Validation
 ✓  Checking devfile existence [22060ns]
 ✓  Creating a devfile component from registry: staging [31470ns]
Validation
 ✓  Validating if devfile name is correct [39460ns]

Starter Project
 ✓  Downloading starter project dotnet from https://github.com/redhat-developer/s2i-dotnetcore-ex [939ms]

Please use `odo push` command to create the component with source deployed

▶ odo create dotnet50 --starter dotnet
Devfile Object Validation
 ✓  Checking devfile existence [22060ns]
 ✓  Creating a devfile component from registry: staging [31470ns]
Validation
 ✓  Validating if devfile name is correct [39460ns]

Starter Project
 ✓  Downloading starter project dotnet from https://github.com/redhat-developer/s2i-dotnetcore-ex [939ms]

Please use `odo push` command to create the component with source deployed

▶ curl --head http://http-8080-app-test.apps-crc.testing/ 
HTTP/1.1 200 OK
date: Mon, 01 Nov 2021 09:33:23 GMT
content-type: text/html; charset=utf-8
server: Kestrel
set-cookie: 21fc3bb480494816a48ea162dd7c0cae=7d1e447e60747aa1954d7646bf80c3a6; path=/; HttpOnly
cache-control: private


```
</details>

@mohitsuman What application you're using? By default, the .Net Devfiles are expecting that the project file is called `app.csproj`.
If your project is using a different project file, you will need to edit `STARTUP_PROJECT` env variable in devfile.yaml.  You can either do this by editing `devfile.yaml` directly, or via odo using `odo config set --env` command. For example if your project has `web.csproj` you can update the env variable running  `odo config set --env STARTUP_PROJECT=web.csproj`
