### ISSUE TITLE
`odo deploy` should trigger  a default deploy command (`group.kind: deploy`.) and execute all the defined steps

### ISSUE THREAD

**Issue by kadel** [openshift/odo#5151]
User story:
As a developer I want to be able to easily deploy my application based on the outerloop definition in devfile, so I can test my application running exactly how it will run in production.

Acceptance criteria:
- [ ] `odo deploy` should trigger a default deploy command (group.kind: deploy.) and execute it based on how it is defined
- [ ] during `push`, do not deploy components referenced in a devfile command1

part of the bigger user story #5109

**Comment by kadel** [comment]
> @kadel can you provide an example of the devfile that should be workable with odo as a part of this feature?

https://github.com/devfile/api/blob/main/samples/devfiles/outerloop-dockerfile-build-inlined-deploy-devfile.yaml

**Comment by valaparthvi** [comment]
Look into composite commands.

**Comment by feloy** [comment]
`pkg.devfile.adapters.common` provides an object to work with commands, but Apply commands are not supported yet, only Composite and Exec commands. Support for Apply commands should be added

**Comment by feloy** [comment]
- [ ] during `push`, do not deploy components referenced in a devfile command

**Comment by feloy** [comment]
@kadel Do we need to set owner References in the deployed Kubernetes resources? Which resource should be the owner?

**Comment by kadel** [comment]
> @kadel Do we need to set owner References in the deployed Kubernetes resources? Which resource should be the owner?

I don't think that we need to.
If the devfile is using `kubernetes` components for deploy definition, odo doesn't have a way to know which resource is the "main" one.  So if we would like to set it we wouldn't know to what resource we should point.
