### ISSUE TITLE
Run integration-e2e tests in 4.9 cluster

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#5157]
/kind testing

## User Story
As a developer and QE I want to run integration and e2e tests on Openshift 4.9 cluster for PRs

## Acceptance Criteria 

- [ ] integration and 2e2 tests are executed on 4.9 by prow

/kind user-story

**Comment by dharmit** [comment]
https://github.com/openshift/release/pull/16274/ for how we moved to 4.7

**Comment by rnapoles-rh** [comment]
Submitted PR https://github.com/openshift/release/pull/23264
