### ISSUE TITLE
Fix use description for commands

### ISSUE THREAD

**Issue by kadel** [openshift/odo#516]
We are not using the correct syntax to describe our commands in `Use` section.

Some of our commands are using `[]` to describe required arguments but this is a  usual way to describe optional arguments. 

Based on  https://developers.google.com/style/code-syntax  and  http://docopt.org/

I propose this syntax:
- required positional argument  -  `REQUIRED_ARGUMENT`
   ( docopt.org also mentions this as an option`<required argument>`)
- optional positional argument - `[optional argument]`
- one of the options is required -`FIRST_OPTION | SECOND_OPTION`  
  (docopt.org also mentions this as an option `(<first option> | <second option>)` )

I like the styl where required argumens are in capital letters a bit more. 
Also I found that it is more commonly used (in heroku and cloud foundry cli)

Task:
Go through all `Use` descriptions and fix them to follow the mentioned style.

**Comment by surajnarwade** [comment]
@kadel , I think we are following the standards which you mentioned in all commands, closing this issue.
