### ISSUE TITLE
Can not ssh using non root user to Linux VM in IBM cloud 

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/odo#5160]
/kind testing
## Problem
Can not ssh to linux Virtual Server instance in IBM cloud so tests fail when trying to ssh. Can only ssh manually using root account.

**Comment by feloy** [comment]
If an ubuntu VM, you can use the `ubuntu` user name. Not sure for fedora which user to use

**Comment by rnapoles-rh** [comment]
it works with ssh
