### ISSUE TITLE
Environment variables' info in `odo link -h` output inconsistent with `odo link` behaviour

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#5175]
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## How did you run odo exactly?
```sh
$ odo link -h
$ odo link backend --component frontend
```

## Actual behavior
`odo link -h` says that linking will lead to output with env vars like below:
```sh
Let us say we have created a nodejs application called 'frontend' which we link to an another component called
'backend' which exposes port 8080, then linking the 2 using:
odo link backend --component frontend

The frontend has 2 ENV variables it can use:
COMPONENT_BACKEND_HOST=backend-app
COMPONENT_BACKEND_PORT=8080 
```

But the actual env vars being injected (and output by `odo link backend --component frontend`) are `SERVICE_BACKEND_IP`  and `SERVICE_BACKEND_PORT_PORT-8080`.

## Expected behaviour
`odo link -h` and `odo link` should be consistent.

## Any logs, error output, etc?

/area linking
/kind documentation

**Comment by dharmit** [comment]
Trying this locally, I don't see the env variable info when doing linking:
```sh
$ odo link backend
 ✓  Successfully created link between component "frontend" and component "backend"

$ odo link backend --component frontend
 ✓  Successfully created link between component "frontend" and component "backend"

To apply the link, please use `odo push`
```
I'm working with `main` branch.

**Comment by kadel** [comment]
> Trying this locally, I don't see the env variable info when doing linking:

problem is not output of `odo link` but `odo link -h` it  sayis that env variables will be `COMPONENT_BACKEND_HOST`  and `COMPONENT_BACKEND_PORT`  which is not true, it is `SERVICE_BACKEND_IP` and `SERVICE_BACKEND_PORT_PORT-8080`

**Comment by kadel** [comment]
fix in https://github.com/openshift/odo/pull/5227

/asssign
