### ISSUE TITLE
`odo catalog describe service postgresoperator.v5.0.3/PostgresCluster` is not helpfull

### ISSUE THREAD

**Issue by kadel** [openshift/odo#5214]
For example the output mentions `instances` that should be array of the object, but it doesn't say how the objects should look like

```
   instances ([]object)   -required-
```

This is the same for every embedded object mentioned in the spec, there are no detail about their structure.

/priority high
/area service-operators

**Comment by feloy** [comment]
More specifically, details for the object are missing for fields that are an array of objects. 

For non-array objects, details are present, for example:

```
   backups (object)   -required-
     PostgreSQL backup configuration

     backups.pgbackrest (object)   -required-
       pgBackRest archive configuration

       backups.pgbackrest.repos ([]object)   -required-
         Defines a pgBackRest repository
```
