### ISSUE TITLE
Docs still include reference to the pre-5079 `odo create --starter` syntax

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#5224]
/kind documentation

## What mistake did you find / what is missing in the documentation?

There are references in the doc source to the old `odo create` syntax prior to the change in #5079 .

E..g. [here](https://odo.dev/docs/using-odo/create-component/#starter-projects-in-non-interactive-mode) we see the command:
`odo create java-springboot myFirstComponent --starter`

### Other examples

Searching the source I see some more hits, e.g. :  
**public/debugging-using-devfile.adoc**
however I'm not too clear which source files are currently still published and which might be dead code.

But someone who knows could easily search.

## What is the relevance of it?

This isn't really relevant to the fix, but if I'm understanding wrong, would appreciate anyone clearing things up for me.

If I understand the #5014 discussion correctly, we decided then that because   `odo create type --starter starter-value` couldn't be distinguished from:   `odo create type name --starter` we would eliminate this syntax.   

So to create using the default starter, you have to know its name, and do:
`odo create type --starter default-starter-name`

There's no shortcut for defaulting to the default starter.

Thanks

**Comment by dharmit** [comment]
> E..g. [here](https://odo.dev/docs/using-odo/create-component/#starter-projects-in-non-interactive-mode) we see the command:
> `odo create java-springboot myFirstComponent --starter`

This is a bug. Thanks for pointing it out. I have opened a PR (#5225) to fix this.


> Searching the source I see some more hits, e.g. :
> **public/debugging-using-devfile.adoc**
> however I'm not too clear which source files are currently still published and which might be dead code.

As per https://github.com/openshift/odo/issues/5139#issuecomment-951750403, the doc you have mentioned here will be moved as a tutorial to the new website. @valaparthvi is working on it.

As for what's published, it's the stuff you see under `docs/website` in the repo. That's what goes to https://odo.dev

> This isn't really relevant to the fix, but if I'm understanding wrong, would appreciate anyone clearing things up for me.
> 
> If I understand the #5014 discussion correctly, we decided then that because `odo create type --starter starter-value` couldn't be distinguished from: `odo create type name --starter` we would eliminate this syntax.
> 
> So to create using the default starter, you have to know its name, and do: `odo create type --starter default-starter-name`
> 
> There's no shortcut for defaulting to the default starter.

Your understanding is correct. We made the change mainly because the cobra library that odo uses has an issue.
