### ISSUE TITLE
Provide refactored supervisor for more universal/robust components

### ISSUE THREAD

**Issue by kadel** [openshift/odo#588]
1) ~~Use InitContainer to inject SupervisorD to container. #556
    This sholud be basic implemetation with no additional benefit (expect the speed) to the current approach.~~ fixed
 
2) ~~Use image labels to generate better config file for SupervisorD~~ fixed in #869 

3) Fix volumes probelm  described in #445

**Comment by cdrage** [comment]
The last issue: https://github.com/openshift/odo/issues/445 has been closed.

Closing this :+1:
