### ISSUE TITLE
Remove annotations from services created during component creation

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#597]
Currently we are adding annotations in the default Service which is created during component creation. But we are not using those annotations anywhere.

So for easier maintainability and simpler logic of component update, it might be a better idea to remove them for now and add them later in future when a need arises.

**Comment by jorgemoralespou** [comment]
@mik-dass what annotations are these?

**Comment by kadel** [comment]
@jorgemoralespou 
We use annotations to store source type (git, local or binary) of a component and path to the source (git repository url, path to local directory or path to binary file).

We need to store this information for `odo push` and `odo watch` commands.

**Comment by mik-dass** [comment]
@jorgemoralespou Currently there are two annotations during the Service creation part 
```
const componentSourceURLAnnotation = "app.kubernetes.io/url"
const componentSourceTypeAnnotation = "app.kubernetes.io/component-source-type"
```
As @kadel mentioned, one stores the component source type (git/local/binary) and other stores the path to the git repo or the local directory.

**Comment by jorgemoralespou** [comment]
@tkral, why the `app.kubernetes.io/` namespace for the annotations?

**Comment by kadel** [comment]
@jorgemoralespou `app.kubernetes.io/url` is based on this https://docs.google.com/document/d/1EVy0wRJRm5nogkHl38fNKbFrhERmSL_CLNE4cxcsc_M/edit#

**Comment by jorgemoralespou** [comment]
@kadel I think that was superseded by #599

**Comment by girishramnani** [comment]
@mik-dass is this issue still relevant?

**Comment by mik-dass** [comment]
@girishramnani I am closing this for now. We can have a look at it later if the need arises.
