### ISSUE TITLE
Add validation for empty values in pkg/occlient/occlient.go

### ISSUE THREAD

**Issue by ashetty1** [openshift/odo#598]
Several functions in [pkg/occlient/occlient.go](https://github.com/redhat-developer/odo/blob/master/pkg/occlient/occlient.go) have no checks for empty values. This is an issue for adding checks for all the functions where parameters are going unchecked under pkg/occlient/occlient.go. 

This issue needs to be fixed to enable unit tests for the above mentioned checks which are currently failing: PR #478

**Comment by kadel** [comment]
there is a test related to this issue https://github.com/redhat-developer/odo/blob/0ee8c4ed778181dce21b5d9b8a898338573611b8/pkg/occlient/occlient_test.go#L1906

It is probably still valid, but need a little bit of investigation

**Comment by dharmit** [comment]
We recently opened #2493 after an extensive discussion on https://github.com/openshift/odo/pull/2491#discussion_r362746030 & https://github.com/openshift/odo/pull/2491#discussion_r362734118. Two arguments (one of them mine) mentioned that it should be OpenShift API's responsibility to perform these checks https://github.com/openshift/odo/pull/2491#discussion_r362739891 & https://github.com/openshift/odo/pull/2491#discussion_r362788522.

@kadel wdyt? Mee and, I guess, @girishramnani are of the opinion that such checks should be in OpenShift API that we consume in the `occlient` package.

**Comment by prietyc123** [comment]
> @kadel wdyt? Me and, I guess, @girishramnani are of the opinion that such checks should be in OpenShift API that we consume in the occlient package. Besides that, we're also focusing on moving as many things to kclient as possible. So, at this stage, this issue probably doesn't hold much merit.

Based on the discussion in #2493 , I will move forward with this issue.
