### ISSUE TITLE
Adhere to new labels created for tool standarization in k8s

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#599]
There's been an effort on the kubernetes community that has defined some labels for tooling to be able to work with applications.
We should investigate if these fit and if we can incorporate them:

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by sspeiche** [comment]
Bumping this priority as it is having fairly negative impacts on some of the other work we are doing and hopefully it is fairly straightforward to do.

There is currently a guideline on supporting this at https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

Here's an example of how they are applied and powering the new topology view in the OpenShift dev console:
```
$oc get dc --show-labels -n sspeiche1
NAME        REVISION   DESIRED   CURRENT   TRIGGERED BY                     LABELS
caching     1          1         1         config,image(caching:latest)     app.kubernetes.io/instance=caching,app.kubernetes.io/name=nodejs,app.kubernetes.io/part-of=app2,app.kubernetes.io/version=latest,app=nodejs
njs         1          11        11        config,image(njs:latest)         app.kubernetes.io/name=openjdk,app.kubernetes.io/part-of=app3,app=njs
nodejs-ex   1          2         2         config,image(nodejs-ex:latest)   app.kubernetes.io/component=nodejs-ex,app.kubernetes.io/instance=backend,app.kubernetes.io/name=nodejs,app.kubernetes.io/part-of=app1,app=nodejs-ex
payment     1          1         1         config,image(payment:latest)     app.kubernetes.io/instance=payment,app.kubernetes.io/name=mysql-database,app.kubernetes.io/part-of=app1,app=payment
```

**Comment by kadel** [comment]
use of labels in odo, and it's mapping to guidelines in https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

| use | currently use label | new label based on [guidelines](https://github.com/gorkem/app-labels) |
|-|-|-|
| application name | app.kubernetes.io/name | app.kubernetes.io/part-of |
| component name | app.kubernetes.io/component-name |app.kubernetes.io/name |
| component type (image builder e.g. java, nodejs) | app.kubernetes.io/component-type | app.openshift.io/runtime |
| component version (builder image version e.g. latest, 0.17) | app.kubernetes.io/component-version | app.kubernetes.io/component-version | app.openshift.io/runtime-version |
| URI for the source code under version control (only if component is created from git repo) | app.kubernetes.io/url | app.openshift.io/vcs-uri |

**Comment by sspeiche** [comment]
It appears the dev console is using `app.kubernetes.io/name=openjdk` to decorate the node in the graph with the right icon. It appears odo used the image stream `java` but then puts that value in `app.openshift.io/runtime`.

I think we need to align on if we really need `app.openshift.io/runtime` or if `app.kubernetes.io/name` is really what we should use. Also, we make want to change to dev console to recognize `java` as a valid value.

/cc @sbose78 @gorkem

**Comment by kadel** [comment]
What is the difference between `app.kubernetes.io/name` and `app.openshift.io/runtime` than?

**Comment by sspeiche** [comment]
Can you update the PR to use `app.kubernetes.io/name` and hold it? I can at least have a good demo for next week until it gets sorted

**Comment by jorgemoralespou** [comment]
How can name for the component be the one of the runtime? If I deploy 2 components based of openjdk, I want the name displayed to be descriptive while the icon can be based on the builder image of there's not s more specific one.

I think you're approaching label problem from the with angle. I've excited this before on Gorkem's pr, the upstream app label issue, DXP meeting with Serena for Dev console.

I think you guys need to think labels through a bit.

**Comment by sspeiche** [comment]
Agree @jorgemoralespou the names #sig-apps came up with don't make total sense unless you look at a variety of scenarios. Gorkem's doc was intended to help clarify this, it could use some more work. We plan to take our findings to #sig-apps to confirm/complain.

**Comment by kadel** [comment]
> Agree @jorgemoralespou the names #sig-apps came up with don't make total sense unless you look at a variety of scenarios. Gorkem's doc was intended to help clarify this, it could use some more work. We plan to take our findings to #sig-apps to confirm/complain.


So we are sticking with labels that we have right now?

**Comment by sbose78** [comment]
We are continuously working on covering more use cases for the labelling - it tends to get into tricky areas very soon :) 

At the moment, this is how we went ahead with the usage.

-  we use the builder image name in `app.kubernetes.io/name`. This is what is used to render the node's image in the topology view. We couldn't find a better way to visualize the node without using this label recommendation. I'm open to re-adjusting things later on.
- `app.kubernetes.io/runtime` tends to become optional because for a lot of non-Java-based `component`s  , that field is redundant. But if it's a java based component, it should have `spring boot` , `thorntail`, etc.
- `app.kubernetes.io/instance`could possibly have a more business friendly name (`account`, `payment`) _if_ needed. For now it takes up the value of the `app.kubernetes.io/component` itself.
- `app.kubernetes.io/component` conveys if it's a backend, frontend, storage. etc.

**Comment by kadel** [comment]
> * we use the builder image name in `app.kubernetes.io/name`. This is what is used to render the node's image in the topology view. We couldn't find a better way to visualize the node without using this label recommendation. I'm open to re-adjusting things later on.

this looks a bit weird to me, why should `app.kubernetes.io/name` strictly corresponds to the language that is used?

> * `app.kubernetes.io/runtime` tends to become optional because for a lot of non-Java-based `component`s  , that field is redundant. But if it's a java based component, it should have `spring boot` , `thorntail`, etc.

Why do we need to store both information, language, and framework?  If it is `springboot` than information that it is java redundant.

**Comment by sspeiche** [comment]
> > * we use the builder image name in `app.kubernetes.io/name`. This is what is used to render the node's image in the topology view. We couldn't find a better way to visualize the node without using this label recommendation. I'm open to re-adjusting things later on.
> 
> this looks a bit weird to me, why should `app.kubernetes.io/name` strictly corresponds to the language that is used?

If you read the label name without reading the guidelines, I feel the same way. The approach #sig-apps took was more around like apps you'd name in a catalog, such as "nginx", "mysql", "java". So they said it made sense to use "name" for that. Then when you create an "instance" you use "instance".

We should go back to sig-apps to clarify if we need to.

> 
> > * `app.kubernetes.io/runtime` tends to become optional because for a lot of non-Java-based `component`s  , that field is redundant. But if it's a java based component, it should have `spring boot` , `thorntail`, etc.
> 
> Why do we need to store both information, language, and framework? If it is `springboot` than information that it is java is redundant.

There isn't an `app.kubernetes.io/runtime` there is an openshift namespaced one. This was added by recommendation by Charles I believe, we may need to revisit this.

**Comment by jorgemoralespou** [comment]
So instead of making what should be intuitive let's just make what works for us. Then complain to #sig-apps?

If the UI is driving what odo should put there just because now there's no other option to show an icon, we're going the wrong way. 
We better have a generic icon, work through the proposal with many examples (not a few as the original or Gorkem's proposal do) and make sure that what we raise is what should be raised. I understand the need to show a nice demo/ui but I don't support doing the wrong things. I did complain back then to the original spec, and I would hate to complain to our updated proposal.

**Comment by sspeiche** [comment]
On Sun, May 5, 2019 at 8:35 PM Jorge Morales Pou <notifications@github.com>
wrote:

> So instead of making what should be intuitive let's just make what works
> for us. Then complain to #sig-apps?
>
That is not at all what I was saying and you shouldn't twist it that way.
We are trying to follow the recommendations and based on the review and
guidance we did as a group, the dev console is following the
recommendations and odo isn't.

> If the UI is driving what odo should put there just because now there's no
> other option to show an icon, we're going the wrong way.
> We better have a generic icon, work through the proposal with many
> examples (not a few as the original or Gorkem's proposal do) and make sure
> that what we raise is what should be raised. I understand the need to show
> a nice demo/ui but I don't support doing the wrong things. I did complain
> back then to the original spec, and I would hate to complain to our updated
> proposal.
>

It is not about a demo, it is about aligning on what the labels mean and
doing something interesting with them. Let's focus on the labeling
recommendation and our usage, and highlight where we are off. Gorkem's
updates to the recommendations provide examples on how to do this. It would
be good to evolve those with many teams. odo team has been part of this
since the beginning. I'm uncertain where you are saying we are off the
spec. If we need more examples that highlight certain cases, then let's
identify the kind of applications they are.

**Comment by sspeiche** [comment]
Bumping this, it is a MUST HAVE for 1.0. Confirmed with @gorkem that dev console is following the recommendation as we have outlined.

I tested the master of `odo` just now and still is generated the wrong labels.

Project created by`odo`:

```
oc get dc -L app.kubernetes.io/component-name -L app.kubernetes.io/component-type -L app.kubernetes.io/component-version -L app.kubernetes.io/name -L app
NAME                      REVISION   DESIRED   CURRENT   TRIGGERED BY   COMPONENT-NAME   COMPONENT-TYPE   COMPONENT-VERSION   NAME             APP
backend-wild-west-game    1          1         1         config         backend          java             latest              wild-west-game   wild-west-game
frontend-wild-west-game   1          1         1         config         frontend         nodejs           latest              wild-west-game   wild-west-game
```

Project created by Dev Console

```
oc get dc -L app.kubernetes.io/component-name -L app.kubernetes.io/component-type -L app.kubernetes.io/component-version -L app.kubernetes.io/name -L app -n adevconsole1
NAME       REVISION   DESIRED   CURRENT   TRIGGERED BY                    COMPONENT-NAME   COMPONENT-TYPE   COMPONENT-VERSION   NAME      APP
backend    1          1         1         config,image(backend:latest)                                                          openjdk   backend
frontend   1          1         1         config,image(frontend:latest)                                                         nodejs    frontend
```

`odo` should be producing these:
```
oc get dc -L app.kubernetes.io/component -L app.kubernetes.io/instance -L app.kubernetes.io/name -L app.kubernetes.io/part-of -L app -n adevconsole1
NAME       REVISION   DESIRED   CURRENT   TRIGGERED BY                    COMPONENT   INSTANCE   NAME      PART-OF          APP
backend    1          1         1         config,image(backend:latest)    backend     backend    openjdk   wild-west-game   backend
frontend   1          1         1         config,image(frontend:latest)   frontend    frontend   nodejs    wild-west-game   frontend
```

ALSO, the naming convention for DCs and other resources should be the SAME between dev console, `odo` and other clients.

/fyi @sbose78 @christianvogt

**Comment by sspeiche** [comment]
![devconsole](https://user-images.githubusercontent.com/727196/61605314-ec93aa80-ac12-11e9-9861-e565dcbc3c02.png)
![odo](https://user-images.githubusercontent.com/727196/61605315-ec93aa80-ac12-11e9-95f8-6dec8e43ebf7.png)

**Comment by kadel** [comment]
The first thing that we need to do is to figure out the right labels for odo.

What I have described in  https://github.com/openshift/odo/issues/599#issuecomment-488610781 is not correct.



| use | current odo label | new label based on [guidelines](https://github.com/gorkem/app-labels) |
|-|-|-|
| application name | app.kubernetes.io/name | ?? |
| component name | app.kubernetes.io/component-name | ?? |
| component type (image builder e.g. java, nodejs) | app.kubernetes.io/component-type | ?? |
| component version (builder image version e.g. latest, 0.17) | app.kubernetes.io/component-version | ?? |
| URI for the source code under version control (only if component is created from git repo) | app.kubernetes.io/url | ?? |

**Comment by cdrage** [comment]
I'm re-opening this issue as I believe we should have some form of documentation with regards to what labels that Odo looks for / uses in Kubernetes / OpenShift yaml. The above table that @kadel has posted we could possibly use in some form of "advanced document".

Ping @boczkowska

**Comment by kadel** [comment]
/unassign @pmacko1 
/close

created #2434 to address missing documentaion
