### ISSUE TITLE
Interest of integration for Tomcat-in-the-cloud

### ISSUE THREAD

**Issue by maxime-beck** [openshift/odo#601]
In the JWS team, we have been working on porting the clustering and session replication mode of Apache Tomcat to a Cloud environment[1] (Kubernetes and OpenShift). Our current logic works in a Microservice approach: one Tomcat Embedded running one Webapp per pod, the number of pods can be increased and decreased dynamically, session replication will follow.

We wanted to discuss if there was any interest to integrate such a project in odo to provide continuous delivery.

__
[1] https://github.com/web-servers/tomcat-in-the-cloud

**Comment by girishramnani** [comment]
closing this issue as its stale
