### ISSUE TITLE
java runtime does not work for online pro - permission issue

### ISSUE THREAD

**Issue by gshipley** [openshift/odo#629]
$ odo create java:latest --binary ./target/myjar.jar

Collecting wheel
Downloading https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl  (41kB)
Installing collected packages: pip, setuptools, wheel
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/app-root'
Check the permissions.

error: build error: non-zero (13) exit code from registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift@sha256:431a7147ec655106b8cfa1a6c4738542e54c0523a6c75a771686727cb931f2a3

**Comment by jorgemoralespou** [comment]
@kadel This issue, as well as node:10 is because how the images are made. Injecting a prebuilt go supervisor should get rid of these issues, although there might still be others to look into.

**Comment by kadel** [comment]
yes, this issue should be resolved after we start using initCotainers to inject go implementation of SupervisorD. 
I'm also currently looking how to properly detect path in s2i images to avoid issues like this in the future and to also resolve #445

**Comment by jorgemoralespou** [comment]
@kadel maybe worth looking at this comment: https://github.com/redhat-developer/odo/issues/556#issuecomment-412764607

There's a link to s2i documentation that states where s2i scripts are/should be located.

**Comment by kadel** [comment]
@jorgemoralespou yep I know, detecting s2i scripts is a less complicated part. 
Problem is with detecting various paths that are used by s2i scripts to store compiled artifact for example.

**Comment by girishramnani** [comment]
is this issue still relevant?

**Comment by girishramnani** [comment]
closing this issue as its stale
