### ISSUE TITLE
I've launched a web stack via the Web Console. Can I use odo to update it?

### ISSUE THREAD

**Issue by ryanj** [openshift/odo#631]
As a team lead, I'd like to use the Service Catalog to distribute my team's web development stack as a template. I need information on how to structure the template and labels to work with `odo`. I also need advice on how to document the basic "Getting Started" workflow for my team members. How can I ensure that my develops will be able to list and update components that were created from the web?

As a developer, I'd like to use `odo` to iterate on web development solutions that were created via the Service Catalog.

Note: currently, this may require making modifications to `~/.kube/odo`

**Comment by jorgemoralespou** [comment]
I think this is a valid request that we could consider. Being able to get a deployment that happened via web and change it to work iteratively through odo. 

This will require to:
- being able to `import` a component. This will be a git based component.
- being able to add all the labels that odo require
- being able to update the current application in `odo` config file
- being able to change the component back to be git based.

**Comment by ryanj** [comment]
@jorgemoralespou What if I had a template that already included the appropriate labels and the correct base configuration (git or binary or whatever)?  

It might be possible to run a few label queries within the resulting project to detect any apps that were pre-configured according to odo's labeling scheme.  That info could then be used to update / synchronize the `.kube/odo` config to reflect the current state.

**Comment by jorgemoralespou** [comment]
@ryanj if the application deployed has the correct labels, you can easily keep working on it from a different machine, just by selecting it (making it active).

e.g.
```
odo application my-app
odo component set my-component
```

or the most simple command:
```
odo component set my-component -a my-app
```

The second form doesn't work yet until https://github.com/redhat-developer/odo/issues/814 is fixed.

**Comment by girishramnani** [comment]
@ryanj can you please confirm if your queries were resolved?

**Comment by girishramnani** [comment]
closing this issue as its stale
