### ISSUE TITLE
Components in catalog without 'latest' tag fail to deploy with `odo create component-name`

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#634]
Running `odo create component-name` assumes `latest` version tag, but not all components have it and `odo create component-name` fails in this case.

```
C:\Temp\odo-test\java> odo create redhat-openjdk18-openshift
Invalid component version: latest
Run 'odo catalog list' to see a list of supported component versions
```

Catalog command shows list below. You can see that most components have no 'latest' tag.

```
C:\Temp\odo-test> odo catalog list
NAME                                    TAGS
fis-java-openshift                      1.0,2.0
fis-karaf-openshift                     1.0,2.0
httpd                                   2.4,latest
jboss-decisionserver62-openshift        1.2
jboss-decisionserver63-openshift        1.3,1.4
jboss-decisionserver64-openshift        1.0,1.1,1.2,1.3
jboss-eap70-openshift                   1.3,1.4,1.5,1.6,1.7
jboss-eap71-openshift                   1.0-TP,1.1,1.2,TP
jboss-processserver63-openshift         1.3,1.4
jboss-processserver64-openshift         1.0,1.1,1.2,1.3
jboss-webserver30-tomcat7-openshift     1.1,1.2,1.3
jboss-webserver30-tomcat8-openshift     1.1,1.2,1.3
jboss-webserver31-tomcat7-openshift     1.0,1.1,1.2
jboss-webserver31-tomcat8-openshift     1.0,1.1,1.2
nginx                                   1.10,1.12,1.8,latest
nodejs                                  0.10,4,6,8,8-RHOAR,latest
perl                                    5.16,5.20,5.24,latest
php                                     5.5,5.6,7.0,7.1,latest
python                                  2.7,3.3,3.4,3.5,3.6,latest
redhat-openjdk18-openshift              1.0,1.1,1.2,1.3
ruby                                    2.0,2.2,2.3,2.4,2.5,latest
```

IMO ether there should be no assumptions about tags and `odo create' should always require ':tag' suffix, or all components should be fixed to have 'latest' tag.

**Comment by kadel** [comment]
> IMO ether there should be no assumptions about tags and `odo create' should always require ':tag' suffix,

Requiring tag might a bit weird from a users point of view :-(
I'm not saying that current behavior is ideal, but it is the same what docker does. If a tag is not specified explicitly than "latest" is assumed, and it fails when there is no "latest".

Would it help if we communicate this behavior better in documentation and descriptions?


> or all components should be fixed to have 'latest' tag.

That is out of odo control, we can't enforce that.

**Comment by dgolovin** [comment]
@kadel I am not very familiar with docker, but if that goes from docker it should be fine.

**Comment by surajnarwade** [comment]
@dgolovin , which environment is this, I never seen an image without latest tag, which is strange

**Comment by dgolovin** [comment]
@surajnarwade it was probably CDK, I don't remember now.

**Comment by kadel** [comment]
@surajnarwade 
This can happens for example if you import images from somewhere else.
You can also easily reproduce this if you enable xpass addon for minishift (most of the images there are without latest tag)

**Comment by cdrage** [comment]
We now error out if "latest" is unavailable and we now offer the solution of passing in a tag.. 

Example (from `odo create --help`):

```sh
  # Create a new Node.js component of version 6 from the 'openshift' namespace                                                                                                               
  odo create openshift/nodejs:6 --context /nodejs-ex                
```

I'm going to close this for now
