### ISSUE TITLE
Support machine readable output formats

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#655]
Odo should provide options to change output format to:
* text
* json
* yaml
* cvs

Well known CLI's do the same:
* Amazon AWS CLI https://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html
* Kubernetes https://kubernetes.io/docs/reference/kubectl/overview/#formatting-output
* Azure CLI https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest

**Comment by jorgemoralespou** [comment]
what would be the goal? odo is not meant for automation but for human's to use it.

**Comment by dgolovin** [comment]
As we discussed with @gorkem using odo behind vscode-openshift-tools extension would be the best and fastest option to provide OpenShift tools in Visual Studio Code. We mostly need to get info about internal objects to provide visual representation in VSCode for UI obects like:
* OpenShift Explorer - tree of projects/apps/components/storage
* New Component QuickInput - some of the steps would require information about available component types/image streams

as an option we can definitely get the same info with 'oc' as I suggested here https://github.com/redhat-developer/vscode-openshift-tools/issues/21.

**Comment by gorkem** [comment]
@jorgemoralespou This is not an automation case but an integration case. Odo provides an inner-loop flow that we would like to take surface on IDEs and editors. I think providing structured output to enable integration is good also for odo. 

@dgolovin other than the inner loop actions like `odo push` vscode extension should prefer to retrieve all the other information via `kubectl` because it will allow us to implement custom CRD support easier (odo will not expose them ever). Let's chat about this on the vscode repo.

**Comment by jorgemoralespou** [comment]
@dgolovin This was clarified at the devtools planning but I still think that depending on the information looked at, `odo` should not be the proxy for them. I agree with @gorkem that apart from the some `odo` specific actions, most of the stuff should use `oc`, `kubectl` or the `client-go`for these.

But definitely we should be able to provide for some of the actions the output in a structured way, although this structure should not be what these other tools provide.

**Comment by dgolovin** [comment]
@jorgemoralespou @gorkem I agree, that `kubectl` or `oc` are better source of structured output vscode-openshift-tools can depend on.

**Comment by kadel** [comment]
/close
we have basic json output using `-o json`
issues related to this topic are labeled https://github.com/openshift/odo/labels/area%2Fjson-output
