### ISSUE TITLE
R&D - component configuration semantics 

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#675]
We need to provide configuration semantics in different scenarios:

- Component creation time. When creating a component, we need to be able to provide configuration for this component in different manners.
  - Just a value as an environment variable
  - A list of values as environment variables
  - A list of values stored in a Configuration object (ConfigMap/Secret)
  - A list of values injected as a file in the component (ConfigMap/Secret) 

- After the fact. When a component exists, we need to be able to provide/update/remove configuration for this component in different manners.
  - Just a value as an environment variable
  - A list of values as environment variables
  - A list of values stored in a Configuration object (ConfigMap/Secret)
  - A list of values injected as a file in the component (ConfigMap/Secret)

We need to define what will be the primitives and possibilities supported. Let's use this issue to define possible options and then come up with a proposal before implementation.

Following is a list of examples that show what needs to be done now, and how this could look like.

### **UC-CF1: Create a component with an environment variable**
* Current state:
```
odo create wildfly frontend
oc set env dc/frontend DEBUG=true                       # This triggers a redeployment
```

* Desired state at creation time: **UC-CF1_1: Create a component with an environment variable**

```
odo create wildfly frontend -e DEBUG=true
```

* Desired state after creation time: **UC-CF1_2: Update a component with an environment variable**

```
odo create wildfly frontend
odo update -e DEBUG=true
```

### **UC-CF2: Create a component with properties from a configmap**

* Current state at creation time:

```
odo create wildfly frontend
oc create configmap my-config --from-file=path/to/ba
oc set env dc/frontend --from=configmap/my-config       # This triggers a redeployment
```

* Desired state: **UC-CF2_1: Create a component with properties from a configmap**

```
odo create wildfly frontend -E path/to/ba 
```

* Desired state after creation time: **UC-CF2_2: Update a component with properties from a configmap**

```
odo create wildfly frontend
odo update -E path/to/ba
```

* Alternate desired state after creation time: **UC-CF2_2: Add configuration to a component with properties from a configmap**

```
odo create wildfly frontend
odo config create path/to/ba
```

### **UC-CF3: Create a component with a configmap as a file**

* Current state:

```
odo create wildfly frontend
oc create configmap my-config --from-file=path/to/ba
oc set volume dc/frontend --add -m /myapp/config --configmap-name=my-config       # This triggers a redeployment
```

* Desired state at creation time: **UC-CF3_1: Create a component with a configmap as a file**

```
odo create wildfly frontend --config-file path/to/ba:/myapp/config
```

* Desired state after creation time: **UC-CF3_2: Update a component with a configmap as a file**

```
odo create wildfly frontend
odo update --config-file path/to/ba:/myapp/config
```

* Desired state after creation time: **UC-CF3_3: Update a component with a configmap as a file**

```
odo create wildfly frontend
odo config create --config-file path/to/ba:/myapp/config
```

cc/ @kadel @marekjelen @gshipley

**Comment by cmoulliard** [comment]
> file in the component (ConfigMap/Secret)

Are you sure that a ConfigMap or Secret is the appropriate format @jorgemoralespou ? That will imply that the user knows the YAML/JSON syntax to be used to pass such additional information.

We could start with a very simple file as we prototype with Spring Boot to pass additional info such by example name of the application, env vars, service instance (parameters,...)

E.g

```
name: my-spring-boot
env:
  - name: SPRING_PROFILES_ACTIVE
    value: openshift-catalog
services:
  - class: dh-postgresql-apb
    name: my-postgresql-db
    plan: dev
    parameters:
      - name: postgresql_user
        value: luke
      - name: postgresql_password
        value: secret
      - name: postgresql_database
        value: my_data
      - name: postgresql_version
        value: 9.6
```

**Comment by cmoulliard** [comment]
> ssl certificate

I agree with you that here we need a secret or a vault store to manage certificate/keys and mount them within the pod of the developer. Nevertheless, it could be possible that the developer will add within the METADATA yaml file some fields needed in order to know the algorithm to be used, ... to encrypt or decrypt the keys, ... So, again, this METADATA or APPLICATION.yml file will help us

**Comment by jorgemoralespou** [comment]
@cmoulliard then we need to define this METADATA file, and it's something that should be out of the scope of this issue. Maybe this issue should depend on us having defined that metadata file. There's an issue for that. https://github.com/redhat-developer/odo/issues/579

**Comment by cmoulliard** [comment]
> having defined that metadata file

Ok to define the spec of the MANIFEST or application.yml file with the ticket #579

**Comment by cmoulliard** [comment]
> that should be out of the scope of this issue

This is perhaps out of scope excepted if we will offer the possibility when we create a component to by example pass the `env` vars to be added to the DeploymentConfig - supervisord created using this file. Then, in this case, we need also to define this line too for the configuration semantics

- A list of key/values stored in a Configuration file (MANIFEST or application.yml file)

**Comment by syamgk** [comment]
So I assume the goal here is to: Implement ways to 
-  Create, delete, modify and show the environment variables
-  Create, delete, modify and show the ConfigMaps
-  Create, delete, modify and show the Secrets
-  link configmaps, sectets to the environment variables

**Comment by syamgk** [comment]
### Environment variable operations
- for creating Environment variables
 if using from configmap or secret that should be created before creating environment variable
```
$ odo env set <env_name>=<value/configmapname:keyname>
```
- for editing environment var
```
$ odo env set <env_name>=<new value/configmapname:keyname>
env already exist confirm to update?(y/n)
```
- for listing environment vars
```
$ odo env show/view
```

**Comment by syamgk** [comment]
@kadel @jorgemoralespou ^ If this looks good for you guys, then I can look forward for Implementation part.

**Comment by syamgk** [comment]
@cmoulliard

**Comment by kadel** [comment]
> This will create a Config map with `<variable name>` as key in it and define env to consume from config map in deployment config.

What will be the name of the ConfigMap?

What happens if I run 
`odo config set variable <variable name>=<Value>`
multiple times for the same component? Will this add new data to the existing ConfigMap? 


> ###### for viewing environment variables in a particular application

I think that it might be better to show variables just for particular compnent rather then for the whole app.



> ###### for pushing a local configuration file
> ```shell
> $odo config set file <path to file> mountat <path to mount>
> ```

This syntax look weird. It should be `--mountpath` as  it is argument, or even better we could use syntax like this:

`odo config set file <path to file>:<path to mount>`

**Comment by syamgk** [comment]
> > This will create a Config map with `<variable name>` as key in it and define env to consume from config map in deployment config.
> 
> What will be the name of the ConfigMap?

configmap name will be unique for each component, so <app_name>-<component_name>
> 
> What happens if I run
> `odo config set variable <variable name>=<Value>`
> multiple times for the same component? Will this add new data to the existing ConfigMap?

if specifying same <variable_name>, prompt for
 ```The variable with the name which you specified already exist. do you want to update `variable_name`?(Yes/No)```
> 
> > ###### for viewing environment variables in a particular application
> 
> I think that it might be better to show variables just for particular compnent rather then for the whole app.

aggree :+1:
so by default current component,
and an option for specifying component and application.
same for `odo config view variable`

> 
> > ###### for pushing a local configuration file
> > ```shell
> > $odo config set file <path to file> mountat <path to mount>
> > ```
> 
> This syntax look weird. It should be `--mountpath` as it is argument, or even better we could use syntax like this:
> 
> `odo config set file <path to file>:<path to mount>`

`odo config set file <path to file>:<path to mount>`

aggree, ^ this one looks more appealing to me.

**Comment by jorgemoralespou** [comment]
Can we turn this into a proposal document type as a PR, as they do in K8S, so we can fix the proposal when comments are made, and when merge we have the full document of what we want and how we want?

 Some examples:
- https://github.com/kubernetes/community/pull/254
- https://github.com/kubernetes/community/pull/2052

**Comment by kadel** [comment]
> Can we turn this into a proposal document type as a PR, as they do in K8S, so we can fix the proposal when comments are made, and when merge we have the full document of what we want and how we want?

Sometimes I have a feeling that you are reading my mind :-D 
Yesterday I was thinking about exactly this. It gets messy to discuss proposals like this using just comments.

**Comment by syamgk** [comment]
can continue discussions on this PR https://github.com/redhat-developer/odo/pull/806

**Comment by kadel** [comment]
Some commands related to this are specified in
 https://docs.google.com/document/d/1RKva9lvIR6dLmDm2tlqmp8V4nFjlrXdulOQ4FSmLkr8/edit?ts=5c5ac66b

**Comment by kadel** [comment]
https://github.com/redhat-developer/odo/issues/1390

**Comment by kadel** [comment]
A lot of has changed since this issue started. We have reworked some of the commands, and partially implemented some of the ideas from this issue.
I'm going to close this. We will continue on improving the component configuration, but it needs a fresh look
