### ISSUE TITLE
Confusing syntax : odo catalog list components 

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#692]
The command `odo catalog list components`  is really confusing as we list the imageStream images 

```
NAME        TAGS
dotnet      2.0,latest
httpd       2.4,latest
nginx       1.10,1.12,1.8,latest
nodejs      0.10,4,6,8,latest
perl        5.16,5.20,5.24,latest
php         5.5,5.6,7.0,7.1,latest
python      2.7,3.3,3.4,3.5,3.6,latest
ruby        2.0,2.2,2.3,2.4,2.5,latest
wildfly     10.0,10.1,11.0,12.0,8.1,9.0,latest
```
= builder's image but not the components created for an application

I suggest to rename `component` to `builder` to make it more user's friendly

```
odo catalog list imagestreams or odo catalog list builders
```

**Remark**

if we follow the convention `odo <entity> <sub-entity> <verb>`, then the name of the command should be

```
odo catalog builders list
```

**Comment by cdrage** [comment]
I'm on the fence about this, since we have another issue with regards to keeping the terminology *away* from OpenShift (only using terminology such as services, components, applications, etc.).

I feel that if we start using "builders" or "imagestreams" then this negates the simplicity of using `odo`. If that makes any sense.

**Comment by cmoulliard** [comment]
As the idea of odo is to compose an application which is designed around x components (a nodejs frontend, a springboot backend, a service from the catalog, ...), then you will use an applicationthe name `application` to group related modules that we call `components = DeploymentConfig + pod(s) + service + ....). From this point of view, listing the builders or runtimes docker image as `component` is a mistake

**Comment by kadel** [comment]
more in `odo catalog list/search` revamp #926
/close
