### ISSUE TITLE
Add a new parameter to the command "odo push --mode" 

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#709]
There is something that I don't like with the existing approach as we pass the name of the binary file to uploaded with the command `odo create`. 

```
 odo create openjdk18 sb1 --binary ./target/ocp-fmp-build-install-1.0-exec.jar
```

As the developer will most probably change/rename the artifactId or version for java/vertc/spring boot projects, then the binary executable crated using the command `mvn package` will change. 

By consequence, it is more logic that we pass such info to the `odo push` command

Example : 

- For source upload

```
odo push --mode source 
```

- For binary upload

```
odo push --mode binary <./path/binary/file>
odo push --mode binary ./target/cool-demo-1.0.0-SNAPSHOT-exec.jar
```

**Comment by cdrage** [comment]
Hey @cmoulliard do you believe this is still an issue / we can close this, considering we've drastically have changed our style of workflow?

**Comment by cmoulliard** [comment]
I will do a new test and then update the ticket @cdrage

**Comment by surajnarwade** [comment]
@cmoulliard did you tested new workflow ?
AFAIK, we now store mode in local config file, hence no need to add `--mode` flag
Closing this issue, feel free to reopen for further discussion
