### ISSUE TITLE
[service catalog][feature] Add command to create a secret from service instance's parameters

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#724]
### Use case

Add a command to create a secret from a service instance using the service's parameters as input for the secret data.

- If no `secret_name` is defined, then the name of the `service_instance` will be used
- The parameters needed to create the secret's content/data will be recuperated from the service_instance > spec > parameters

### Command syntax

`odo create secret <service_instance> [<secret_name>] [flags]`

**Comment by geoand** [comment]
What is reasoning for providing a separate command that creates a secret?

**Comment by cmoulliard** [comment]
If for any reason the secret of a serviceInstance hasn't been created or need to be recreated due to parameter's changes, then we need a separate command. Make sense @geoand ?

This command could become generic in order to support to create a secret from key/value pairs, files, ... and not only using serviceInstance's parameters as we can do with oc 

```
oc create secret -h
Create a secret using specified subcommand.

Usage:
  oc create secret [flags]

Available Commands:
  docker-registry Create a secret for use with a Docker registry
  generic         Create a secret from a local file, directory or literal value
  tls             Create a TLS secret
```

and then the `oc create secret` will not required anymore as odo will support it

**Comment by geoand** [comment]
@cmoulliard Thanks for the explanation.

I propose that we add an flag like `--force-update` the secret already exists - otherwise the command should fail.

Furthermore I propose that this be done (by me) once #723 is merged since it relies on and ties into that work

**Comment by cmoulliard** [comment]
In fact, when the secret has been created from the `servicebinding`'s object, then it could be changed like every secret at the condition of course that we can edit/write the content as base64

**Comment by geoand** [comment]
OK, let's revisit then when #723 get's merged
