### ISSUE TITLE
Make UX / UI consistent across all `lists` / consistency

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#728]
odo list
odo component list
odo service list
etc..

**Comment by kadel** [comment]
We need to define how the output should look like.

**Comment by jorgemoralespou** [comment]
Are we going to support different output formats, like `oc` or `kubectl`, or structured output, so one can select/filter what he sees and how he sees it?

**Comment by cdrage** [comment]
This was more in terms of tables / UX, such as what is being outputted in `odo catalog list` and `odo service list`

At this point, I'm going to close this as I believe it's pretty uniform between the commands now.
