### ISSUE TITLE
[RFE] Releases should have executable binaries packaged

### ISSUE THREAD

**Issue by aditya-konarde** [openshift/odo#747]
For the sake of onboarding experience: 

The .gz releases which can be downloaded through: https://github.com/redhat-developer/odo/releases/

Should have the binary named `odo` instead of `odo-linux-amd64`

As I'd then have to: 

- `chmod +x odo-linux-amd64`
- `mv odo-linux-amd64 odo`
- Copy file to PATH

We can make it as easy as:
- Copy file to PATH

Example: https://github.com/minishift/minishift/releases

**Comment by cdrage** [comment]
I'm going to close this as there was no other discussion and to be honest, we follow the same conventions as `kubectl` and other Kubernetes/OpenShift-like tools.

If this comes up again, we'll take this again into consideration!
