### ISSUE TITLE
[RFE] Knative Support

### ISSUE THREAD

**Issue by bbrowning** [openshift/odo#762]
As we integrate [Knative](https://github.com/knative/docs/) into OpenShift, I'd love to see odo support Knative directly. This is a high level epic to track that desire, which will need to be broken down into a number of individual pieces after some discussion.

There are 3 main components to Knative - Serving, Eventing, and Build. Here's a high level breakdown of how each one intersects with odo:

**Knative Serving**
- Components would be represented as Knative Configurations instead of OpenShift DeploymentConfigs
- Components would be exposed via Knative Routes instead of OpenShift Routes
- Supervision would have to be handled differently as Knative does not allow init containers nor storage volumes
- Related to the above, the storage subcommand would not apply to Knative
- `odo service` becomes even more confusing as a subcommand since both Kubernetes and Knative have the concept of Service that's unrelated to what `odo service` does

**Knative Eventing**
We'd want a new odo subcommand to wire Knative Event Sources to Components deployed via odo. `odo link` wouldn't be a bad name for this, but that already serves a different purpose. The exact terms and how you do this in Knative is still in flux. It's something we should keep an eye on.

**Knative Build**
Depending on how the integration between Knative Build and OpenShift Builds shakes out, we may want to switch from creating OpenShift BuildConfigs to Knative Builds.

**Other Thoughts**
An open question is whether this work should target any Knative or specifically Knative on OpenShift. If targeting any Knative then the scope of `odo` changes a bit into a more generic community project on top of Knative instead of something only for use by Red Hat employees and customers.

And, as Knative isn't shipped in OpenShift yet, we'll need to figure out the proper place to work on this that doesn't disrupt work against vanilla OpenShift. Perhaps a branch, perhaps another project, depending on the answer from the previous paragraph.

Feel free to disagree with any of the above. These are just my thoughts about how odo fits in to the Knative world.

**Comment by gorkem** [comment]
@bbrowning What are the differences between KNative and KNative on Openshift ?

**Comment by bbrowning** [comment]
@gorkem That's a good question, and one that's really up to us to decide. Knative in general is in sore need of some developer-focused tooling similar in vein to odo. So, that's one discussion that needs to be had - should something be done upstream in the Knative community directly, instead of in vendor-specific tools like odo?

**Comment by sspeiche** [comment]
We discussed some of this at the last F2F and agreed this is on our backlog and high priority after we nail down a "1.0" release focused on openshift and innterloop story. Some ideas were to have `odo` to work in a mode that would generate and expect Knative features, we refer to this as `kdo`. Ben has a good list of things to consider. We should take a look at some specific scenarios, trying to nail down a flow with a certain cluster configuration.

**Comment by debianmaster** [comment]
i hope there is no separate effort that is being worked at RH on  any other cli tools for knative.   

having it on  odo makes sense

**Comment by sspeiche** [comment]
> i hope there is no separate effort that is being worked at RH on any other cli tools for knative.
> 
> having it on odo makes sense
There will be the built in support in `kubectl` and `oc` through the use of the CRD extensions for the CLI, though this is the bare bones experience. We'd need to look at something like `knctl` as something for those wanting to work directly with Knative resources. `odo` is abstracting all underlying implementation details away, so it will be used for a good bit of Knative use cases but in the end, there will need to be a lower-level resource specific tool as well. I just wanted to be clear on the separation and expectations that there could be different CLIs for different use cases, just like `oc` and its relationship to `odo`.

**Comment by sspeiche** [comment]
@bbrowning This is quite old and not really relevant anymore, I propose we close it and create new focused epics around separate use cases:
* Knative serving - being able to deploy apps with `knative.Service` instead of DC
* Knative evening - being able to "subscribe" to events, via some command

**Comment by bbrowning** [comment]
I agree!
