### ISSUE TITLE
Refactor code to reduce number of arguments in some functions 

### ISSUE THREAD

**Issue by kadel** [openshift/odo#774]
One of the many function that has a lot of arguments:
```
component.CreateFromGit(client, componentName, componentImageName, componentGit, applicationName, componentPorts, componentEnvVars)
```

This is really hard to read and hard to mantain.

**Comment by cdrage** [comment]
@kadel 

Similar to:

```go
  func (c *Client) BootstrapSupervisoredS2I(commonObjectMeta metav1.ObjectMeta, builderImage string, inputPorts []string, envVars []string) error {
```

We should use a "commonObjectMeta" parameter.

Perhaps: `commonMeta` or `commonContainerMeta` struct? We'll add:

 - inputPorts
 - envVars
 - builderImage / image name

To the struct, that should at least reduce it to 3 parameters.
