### ISSUE TITLE
show warning messages for unsupported version of server

### ISSUE THREAD

**Issue by syamgk** [openshift/odo#778]
odo should warn the user by showing warning messages while running odo commands across unsupported versions of openshift cluster.

**Comment by syamgk** [comment]
use this as a reference for supported versions: https://github.com/kubernetes/client-go#compatibility-matrix

**Comment by girishramnani** [comment]
@kadel is this issue still relevant?

**Comment by kadel** [comment]
> @kadel is this issue still relevant?

yes
