### ISSUE TITLE
[RFE] odo list <application> name -> show components/services of an application

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#798]
### Suggestion

One of the big improvment of the `component`'s or service's concepts and thelinks of odo is that they offer a better way to describe what an application looks like, what are the artifacts and how they are connected/releated.

This is for that reason that I would like to suggest that we have a  command `odo list <applicationName>` able to show components/services associated to an application. 

### Command

```
odo <applicationName> list | odo list <applicationName>

NAME        	    Category      Type                Version
payment-frontend    runtime       nodejs              0.8
payment-backend     runtime       spring-boot        1.5.15
payment-database    service       db-postgresql-apb  dev
...
```

Remarks :  
- The list could be extended with configMap/secret .... 
- An artifact could be described using a `component` CRD and in the future processed ate the server side by an operator

**Comment by jorgemoralespou** [comment]
There's a command for this, that is called `describe` that gives full information on what's in a component, or an application. And yes, output can be improved.

```
$ odo application describe
Application odo-website has:
Component web-2 of type jekyll-2 with source in file:///Users/jmorales/repositories/jorgemoralespou/odo/odo
Component web-3 of type jekyll-3 with source in file:///Users/jmorales/repositories/jorgemoralespou/odo/odo
Component web of type jekyll with source in file:///Users/jmorales/repositories/jorgemoralespou/odo/odo
Externally exposed via web-odo-website-odo.apps.osevg.openshiftworkshop.com
```

**Comment by cmoulliard** [comment]
Great to know that such command exists. I have also reviewed my table as I think that it doesn't yet include all the info needed to describe completely the components/services....

```
odo application describe

NAME        	    Category      Type               Version       Source       Visible Externaly
payment-frontend    runtime       nodejs             0.8           local        yes
payment-backend     runtime       spring-boot        1.5.15        binary       no
payment-database    service       db-postgresql-apb  dev                        no
...
```

Question : Do we have to add a column to specify the `Link` @jorgemoralespou @kadel @metacosm @lincolnthree  ?

**Comment by metacosm** [comment]
Not sure what you mean by `Link`, @cmoulliard?

**Comment by cmoulliard** [comment]
Link refers to inject env var, secret, ... to a DeploymentConfig. See [here](https://goo.gl/QUFPdx) @metacosm

**Comment by girishramnani** [comment]
@cmoulliard is this issue still relevant?

**Comment by dharmit** [comment]
At the moment, we have this output:
```sh
$ odo app describe app
Application Name: app has 1 component(s) and 2 service(s):
--------------------------------------
Component Name: node
Type: nodejs
Source: file://./
Environment Variables:
 · DEBUG_PORT=5858
--------------------------------------
Service Name: psql-1
Type: dh-postgresql-apb
Status: ProvisionedAndBound
--------------------------------------
Service Name: psql-debug
Type: dh-postgresql-apb
Status: ProvisionedSuccessfully
--------------------------------------
```

A tabular output as suggested in the OP would be a better idea, IMO.
