### ISSUE TITLE
Add current repository git URL if exists to the deployment as annotation

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#799]
When I do:

```
git clone http://github.com/jorgemoralespou/my-awesome-project
odo create java test
odo describe
```

I would like to see that the sources for the deployment are:
- local to my laptop
- but coming from a repository checkout

This would help anyone work on an existing application deployed in a cluster.

If in another laptop, I want to keep working, I don't have any hint where the original (if existent) git repository is located, to checkout it again and keep working.

**Comment by jorgemoralespou** [comment]
@surajnarwade 

> so we have to deal with .git/config toml file to get url, but what if there are multiple remotes ?

Yes. We should have only origin (if it exists)

> what if given directory is not git repo

Then, we should do nothing

**Comment by girishramnani** [comment]
@jorgemoralespou is this issue still relevant?

**Comment by jorgemoralespou** [comment]
I guess. I haven't checked it, but as long as it's not resolved, yes, this should remain open.
