### ISSUE TITLE
No unit tests for pkg/storage/storage.go

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#816]
We don't even have a unit test oriented file for storage

Functions in pkg/storage/storage.go

- [x] Create
- [ ] Unmount
- [ ] Delete
- [x] List
- [x] ListMounted
- [ ] ListUnmounted
- [ ] Exists
- [ ] generatePVCNameFromStorageName
- [x] getStorageFromPVC
- [ ] GetComponentNameFromStorageName
- [ ] IsMounted
- [ ] GetMountPath
- [ ] Mount
- [ ] GetStorageNameFromMountPath
- [x] Push

**Comment by mik-dass** [comment]
@kadel Done

**Comment by kadel** [comment]
@mik-dass  can you please check out list that we have covered from your list?

**Comment by mik-dass** [comment]
@kadel You mean ticking the covered functions? Already done. Only one function is covered :D

**Comment by kadel** [comment]
> @kadel You mean ticking the covered functions? Already done. Only one function is covered :D

yes, thank you :-)
