### ISSUE TITLE
Doc - Add a section to explain how to install a java, spring boot application

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#839]
The existing's doc explains how to play with `nodejs`'s [application](https://github.com/redhat-developer/odo#deploying-a-nodejs-application-using-odo) but not how to install a `Java | Spring Boot application`

Tasks :  

- [ ] Enhance the [Getting started](docs/getting-started.md) page to include a java's section
- [ ] Update the [Examples](docs/examples.md) page to include the java's image

**Comment by Preeticp** [comment]
TBD if it needs docs

**Comment by kadel** [comment]
docs now have examples based on java and springboot, for example muliti-component example https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.html

/close
