### ISSUE TITLE
Replace arguments by flags

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#858]
[kind/Proposal]

## What is the expected outcome?
`odo service create dh-postgresql-apb my-postgresql-db` should become something like
`odo service create --class dh-postgresql-apb --instance my-postgresql-db`

## Why do you think this is relevant?
Commands should not use arguments since it increases the cognitive load on users (as they need to remember what the possible arguments are and in what order) and is error-prone. Moreover, it makes things a lot more complex to auto-complete. While this makes things a little more verbose (and typing is reduced when combined with auto-complete), it's also a lot more explicit. For a good argument on how flags are better than arguments in CLI tools, see: https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46#8493

**Comment by kadel** [comment]
I think that it makes sense to use arguments, where you require a value and it is just a single argument, 
 and than use flags for the rest.

 `odo service create` is a good example. `odo service create dh-postgresql-apb my-postgresql-db` second argument is optional and it would be better to replace it with a flag `odo service create dh-postgresql-apb --name my-postgresql-db` . The same for `odo create`. It makes it clear at the first look what is a name and what is service type.


I'm not sure about using `class` and `instance`. One of the goal for odo is to make terminology clear for people who doesn't know anything about OpenShift/Kubernets.

**Comment by geoand** [comment]
Isn't #683 related to this?

**Comment by geoand** [comment]
I see, thanks @kadel

**Comment by metacosm** [comment]
In my opinion, we should only allow arguments when there's only one argument. So yes, I agree that `service create` could use one argument for the service class and then flags. Same for any other commands. Positional arguments should be removed.

**Comment by cdrage** [comment]
Flags have been added here: https://github.com/openshift/odo/pull/683

Closing this issue :+1:
