### ISSUE TITLE
More examples on databases / services

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#862]
We should have some documentation on:

Tasks:

 - [ ] How to import an external mysql database and deploy it (for example, importing a `foobar.sql` file). Converting from a convential database to OpenShift-esque scenario
 - [ ] More documentation on how to actually use services in comparison to the components.

**Comment by cdrage** [comment]
This is a good example: https://github.com/redhat-developer/odo/pull/1059

**Comment by cdrage** [comment]
Notes for myself, using this: https://github.com/sclorg/nodejs-ex  with the example at the bottom with regards to connecting to a database is a good start.

**Comment by dharmit** [comment]
Working with `odo service` command is not really straightforward, IMO. 

- It's not really clear as to wht's the difference between `odo catalog` and `odo service` command. They both seem to deal with the service catalog. Help messages are also ambiguous:
  ```
  $ odo service -h
  Perform service catalog operations
  ....
  ....
  
  $ odo catalog -h
  Catalog related operations
  ....
  ....
  ```
- More examples in `docs/cli-reference.adoc` or a separate doc for advanced use cases of services would be very helpful.

**Comment by girishramnani** [comment]
document katakoda's example as part of this issue

**Comment by cdrage** [comment]
After talking with @veillard we should have some documentation with regards to service integration in preparation for 1.0 GA.

**Comment by cdrage** [comment]
This can actually be closed as I added documentation to the website:

https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-an-application-with-a-database.html

**Comment by dharmit** [comment]
Is the CSS on that page broken only for me or is it a more widespread issue? I checked in a Private window and still see just HTML there.

**Comment by cdrage** [comment]
@dharmit it's broken for you. Maybe your addon or something?
