### ISSUE TITLE
Make odo API friendy

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#873]
Make odo usable as an API.

More tools (VSCode, Developer Studio, ... IntelliJ) are using odo as an API to perform actions. They need to interpret results in a stable fashion. Here are the drawbacks I have:
- stateful: we need to perform several calls sometimes : ex to create an application we first need to set the current project, then perform the application creation. I think every parameter should be given to each command like oc
- return codes: when a command has failed for whatever reasons, it should be reported with a negative return code
- output: in order to interpret results of a command, we need to parse output that is error prone because it may change as it is designed to human interactions. Having a JSON or YAML output like oc would make the integration much more stable

## What is the expected outcome?
Having a command design similar to oc

## Why do you think this is relevent?
For third parties integration

**Comment by kadel** [comment]
Hi @jeffmaury everything that you are mentioning is already in progress.

> * stateful: we need to perform several calls sometimes : ex to create an application we first need to set the current project, then perform the application creation. I think every parameter should be given to each command like oc

#656

> * return codes: when a command has failed for whatever reasons, it should be reported with a negative return code

Can please point to some commands that don't report correct return codes?

> * output: in order to interpret results of a command, we need to parse output that is error prone because it may change as it is designed to human interactions. Having a JSON or YAML output like oc would make the integration much more stable

#784

**Comment by jeffmaury** [comment]
> Hi @jeffmaury everything that you are mentioning is already in progress.
> 
> > * stateful: we need to perform several calls sometimes : ex to create an application we first need to set the current project, then perform the application creation. I think every parameter should be given to each command like oc
> 
> #656
> 
> > * return codes: when a command has failed for whatever reasons, it should be reported with a negative return code
> 
> Can please point to some commands that don't report correct return codes?
odo create --local returns 0
odo create --git returns 1
So should the semantic of rc is:

- =>0: OK
- <0: failure ?
> 
> > * output: in order to interpret results of a command, we need to parse output that is error prone because it may change as it is designed to human interactions. Having a JSON or YAML output like oc would make the integration much more stable
> 
> #784

**Comment by kadel** [comment]
> * =>0: OK
> * <0: failure ?

0 is OK, everything other than that is an error, that is standard Linux way. I believe that this is POSIX standard. 1 is usually considered as a general error

http://tldp.org/LDP/abs/html/exitcodes.html
https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

I just tested `odo create` with`--git` and `--local`, `odo create --git` returns 0 if run was successful and 1 if failed. the same for `--local`.

**Comment by girishramnani** [comment]
we have machine readable output implemented which makes it easy for tools to integrate odo with them. Closing this issue for now as it seems the scope of this issue has been implemented.
