### ISSUE TITLE
Command for importing new component types (builder images)

### ISSUE THREAD

**Issue by kadel** [openshift/odo#882]
[kind/Feature]

Currently, it is not easy for the user to import new component type (s2i builder image).
It needs to be done using `oc`. #780 
Not sure how common operation this is going to be but it might be worth to consider add a command 
that will make it easier to add new builder image to the cluster that will show up as a new component type that can be used with `odo create` command.

Something that would be as easy as running:
``` 
odo add-component-type registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
```

With better name than `add-component` I just can't think of anything better on Friday 😇 . This command could be even a subcommand of `odo component` (`odo component import-type`)

**Comment by metacosm** [comment]
If such a feature were to be implemented, it should be found under the same command that allows listing component types (currently `catalog list components`, which I find a little confusing to be honest since to me `catalog` should be focused around service catalog, but that's a different issue 😉). With that said, I think this feature should therefore be something like `catalog import ...`.

**Comment by jorgemoralespou** [comment]
Agreed with @metacosm and @cdrage.

Now, I see that we can import a s2i builder, for which it would do:
- import the image, creating the imagestream
- add the builder tags annotation to the appropriate istag (to one tag, all tags?)
Worth considering what would be the proper syntax. 
- Would we import a specific tag? Any tag? 
- How would we manage the secret needed to access secure registries? 
- What default options would this put on the openshift resources?
- It would only be on a specific project, as `odo` is meant only for developer type of profile, so not able to install on the openshift namespace.

What I don't see is what would happen when one tries to import a service.

**Comment by cdrage** [comment]
Possibly have this for 1.0 / GA? @kadel @girishramnani

**Comment by kadel** [comment]
> Possibly have this for 1.0 / GA? @kadel @girishramnani

Only if we get time for it. I don't think that this needs to be a high priority.

`oc` can be used to do this and we have it documented here https://github.com/openshift/odo/blob/c27e25e93a6a940b434444e8743f1d9219235aaa/docs/getting-started.adoc#adding-a-custom-builder
