### ISSUE TITLE
Support logs and log as command

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#891]
## What should odo do differently? Which functionality do you think we should change?

Coming from other tools one would sometimes type `log` or `logs`, being the latter not supported. This enhancement is to allow both words to work. 

## What are you trying to do?
Make user experience easier by not failing on a common problem.

**Comment by surajnarwade** [comment]
from `oc log` output:

```
log is DEPRECATED and will be removed in a future version. Use logs instead.
```

**Comment by jorgemoralespou** [comment]
@surajnarwade what we're trying to do here is to make it user friendly, so IMHO supporting both notations is helpful, even if oc deprecates one of the options.

**Comment by kadel** [comment]
I would prefer to have just one command for everything. It can get quite confusing if you have one thing that can be done using multiple commands :-(

To be honest I'm also having problems with `odo log` maybe we should rename it to `odo logs`

**Comment by metacosm** [comment]
I don't like having 2 different commands for the same thing, though commands can have aliases… On `log` vs `logs`, I think we should stick with what is consistent, i.e. keep everything singular.

**Comment by surajnarwade** [comment]
@jorgemoralespou , can you give some example, where user might have to face this situation ?

**Comment by jorgemoralespou** [comment]
Aliases means that the user needs to tweak the user experience for him. The user experience should be already tweaked for him.

There are some commands where it might make sense to accept singular and plural, as this is one of the cases.

Even if oc have deprecated this, just think that they support po, pod and pods, bc, buildconfig and buildconfigs , dc, deploymentconfig and deploymentconfigs, ... And I'm pretty sure that don't look weird to you :-D

**Comment by kadel** [comment]
> Even if oc have deprecated this, just think that they support po, pod and pods, bc, buildconfig and buildconfigs , dc, deploymentconfig and deploymentconfigs, ... And I'm pretty sure that don't look weird to you :-D

It doesn't because those are not commands, but arguments for commands 😬
