### ISSUE TITLE
Add resource utilization stats to odo describe commands

### ISSUE THREAD

**Issue by anmolbabu** [openshift/odo#896]
[kind/Feature]

## Which functionality do you think we should add?

Odo should provide resource utilization information(to start with, the memory, cpu and storage utilizations) as most of the times, these statistics help a developer to find/troubleshoot issues relating to his apps not functioning as expected due to resource constraints being exceeded... In future, we(Odo) can leverage this information to suggest to the user why something went wrong in the developers deployment...

## What are you trying to do?
Enhance debug-ability/ability to troubleshoot applications managed by odo.

**Comment by geoand** [comment]
Sorry but I sort of forgot what we are supposed to do with this :(

Can you please provide more information @anmolbabu @kadel ?

Thanks and sorry again!

**Comment by anmolbabu** [comment]
@geoand If I remember correctly, the idea was to add a command like `odo component status <component_name>` may be even with project and app flags that will give information about the component like the memory, cpu and storage utilizations(current usage vs total provisioned for the component pod, which can be helpful in debugging component code for its developer) and also the status of the component as described in https://github.com/redhat-developer/odo/issues/830

@kadel @jorgemoralespou Please correct me if I am wrong

**Comment by geoand** [comment]
Thanks @anmolbabu !

Where would that component utilization information come from?

**Comment by anmolbabu** [comment]
@geoand I think those stats should/may be available via some monitoring api that the openshift exposes..
We just need to find which one ;) I believe it should be available somewhere in the openshift console the monitoring tab if I remember correctly.. we probably need to reverse engineer it to find the api

**Comment by geoand** [comment]
That makes sense, thanks @anmolbabu! 

@jorgemoralespou Do you have any pointers about were to look for the monitoring API?

**Comment by geoand** [comment]
@kadel @jorgemoralespou any idea were the monitoring APIs are?

Thanks!

**Comment by jorgemoralespou** [comment]
@geoand Not sure what this would be.
To get metrics in OpenShift you need the metrics capability deployed. In OCP 4 this is implemented with Prometheus, but in OCP 3.x changes from hawkular to Prometheus, so not sure what's the stable to to get these.

I've seen these APIs, in the OCP 4 cluster, not sure how to use them though:
```
nodes                                                      metrics.k8s.io                                     false        NodeMetrics
pods                                                       metrics.k8s.io                                     true         PodMetrics
alertmanagers                                              monitoring.coreos.com                              true         Alertmanager
prometheuses                                               monitoring.coreos.com                              true         Prometheus
prometheusrules                                            monitoring.coreos.com                              true         PrometheusRule
servicemonitors                                            monitoring.coreos.com                              true         ServiceMonitor
```

We should probably ask someone from OpenShift team, but again, not sure who. Adding @sspeiche for him to find the right contact.

**Comment by jorgemoralespou** [comment]
In OCP 4:

There's a prometheus deployed by default (via the monitoring/Prometheus operator) that provides the cluster wide prometheus. To get the details for this Prom server:
```
oc get Prometheus/k8s -n openshift-monitoring -o yaml 
```

This means that you can use the internal service URL to access this server:
```
prometheus-k8s.openshift.monitoring.svc.cluster.local
```

To this instance, you can do Prometheus calls like the following PROMQL:
```
kube_pod_container_resource_requests_memory_bytes{pod="portal-workshop-0ec49bb802b411e9abc5"}
```

You can do some testing on the Prometheus Dashboard to find the appropriate metrics to query for.

I'll dig what can be done in 3.x (with Prometheus instances)

**Comment by geoand** [comment]
Thanks @jorgemoralespou !
