### ISSUE TITLE
Automated workflows with Odo

### ISSUE THREAD

**Issue by anmolbabu** [openshift/odo#918]
[kind/Feature]

## Which functionality do you think we should add?

I as a developer of an application, should have a way to describe how and what my deployment is composed of how the different parts of my deployment are exposed, configured, interact etc.. And Odo exposes a command that reads this deployment description(should be very simple compared to what kubernetes/oc already provides) and then creates the required resources in standard/suggested default ways(to avoid elaborate/extensive requirements of configuration)

**Comment by surajnarwade** [comment]
@anmolbabu , can you give an example here ? how this feature/flow should look like

**Comment by cdrage** [comment]
@anmolbabu Can you please explain this more in detail / perhaps we can close this issue (this is from November...) Thanks!

**Comment by girishramnani** [comment]
this issue needs more information and it seems for now we haven't seen any activity hence closing.
