### ISSUE TITLE
`odo catalog list/search` revamp

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#926]
[kind/Feature]

## Which functionality do you think we should add?
We should remove from the `odo catalog list/search xxx` signature the need to specify service or component. We need `odo` to be smart enough and show both, and additionally add to the signature of list a way to filter (narrow down the list of results) based on type and name, while search should search in most/all of the possible metadata.

This issue is linked to:
- [Confusing syntax : odo catalog list components](https://github.com/redhat-developer/odo/issues/692)
- [[RFE] Confusing entity name used to list the images to be used to build/run an application](https://github.com/redhat-developer/odo/issues/838)
- [ocd list should allow to filter components by type](https://github.com/redhat-developer/odo/issues/193)
- [UC 9: As a developer, I want to list all possible configurations of components I can deploy and their meaning](https://github.com/redhat-developer/odo/issues/154)

**Comment by kadel** [comment]
How should `odo catalog list` output look like?
There should still be an option to filter just services/components something like `odo catalog list --services` and `odo catalog list --components` and default would be everything (the same flags for the search)


There might be different columns for each type, so we should probably display them in two separate tables.
Maybe somehting like this?
```
▶ odo catalog list

Components:
NAME                                    PROJECT       TAGS
dotnet                                  openshift     2.0,latest
fis-java-openshift                      openshift     1.0,2.0
fis-karaf-openshift                     openshift     1.0,2.0
httpd                                   openshift     2.4,latest
jboss-decisionserver62-openshift        openshift     1.2
jboss-decisionserver63-openshift        openshift     1.3,1.4

Services:
NAME                                              PLANS
amq62-basic                                       default
amq62-persistent                                  default
mariadb-persistent                                default
mongodb-persistent                                default
mysql-persistent                                  default

```

**Comment by jorgemoralespou** [comment]
Yes, I think that given the different output for every command, we need to show both as separate outputs, like what you get when you do `oc get pods,svc`

Also, I think there should be one option to narrow down results, and then there should be an option to filter the results, by default by name, and additionally by other fields:

Default filter on name:
```
$ odo catalog list --filter java
Components:
NAME                                    PROJECT       TAGS
java                                    openshift     8,latest
fis-java-openshift                      openshift     1.0,2.0
```

Filter on another field. 
```
$ odo catalog list -f plan=production
Services:
NAME                                              PLANS
amq62-basic                                       production
```

**Comment by kadel** [comment]
Would it make sense to have `odo catalog list --search java` instead of `odo catalog list --filter java`?



I also think that we could get rid of `odo catalog search` completely as it would be essentially the same as `odo catalog list --search java`

**Comment by kadel** [comment]
We have the following columns for components:
- name
- project
- tags

 and for services:
- name
- plans


that means that `--filter` could look like this:
 - `project=myprojec` - list only components in given project
 - `tags=v1` - list only components with given tag
 - `name=java` or just `java` - list components and services with given name
- `plans=default` - list only services with given plans


But we should be also able to combine filters like `--filer name=mysql,plans=default`  won't that be too complicated? 

We should also introduce optional `--service` and `--components` flags, to allow list all the services without components.



More and more I think about this I would actually prefer the current approach. It might be more words to type, but I think that it is much cleaner. And all this wouldn't really matter once we have nice interactive mode.

**Comment by jorgemoralespou** [comment]
@kadel, yes to every comment in your previous comments. 

Last comment I could agree with you. Not sure yet if we're getting the right experience on catalog about components and services, and not sure we should even use the catalog for components. I would need also to think it through.

Adding my team. cc/ @gshipley @marekjelen @jankleinert @grahamdumpleton @ryanj @joshix @mhausenblas 
Can you guys provide your thoughts on this issue? If you don't fully grok what's been questioned here, ping me on slack.
