### ISSUE TITLE
New suggestion system  broke path suggestion in bash/zsh

### ISSUE THREAD

**Issue by kadel** [openshift/odo#960]
[kind/bug]

If I run `odo create wildfly --local ./<tab>`  I don't get path suggestions :(

**Comment by mik-dass** [comment]
@kadel Added a quick PR for this. But the PR currently doesn't work for `~` and `../` but it does work for `/` and other normal situations

**Comment by kadel** [comment]
Reopening this, as #962 was supposed to fix this only partially.  But I couldn't every even that :-(

**Comment by mik-dass** [comment]
@kadel @anmolbabu It might be a better idea to fix it upstream. WDYT?

**Comment by anmolbabu** [comment]
Seems to work for me as below:

```
[redhat@localhost odo]$ odo create wildfly --local ./
./                            ./.codecov.yml                ./.git/                       ./glide.yaml                  ./odo                         ./profile.out                 ./.travis.yml
./appveyor.yml                ./coverage.txt                ./.github/                    ./LICENSE                     ./openshift.local.clusterup/  ./README.md                   ./vendor/
./build/                      ./dist/                       ./.gitignore                  ./main.go                     ./pkg/                        ./scripts/                    ./.wwhrd.yml
./cmd/                        ./docs/                       ./glide.lock                  ./Makefile                    ./plugin.yaml                 ./tests/                      
```

**Comment by anmolbabu** [comment]
Ideally, looking at their current code, I doubt posener/complete would work well on windows at the moment :disappointed:

**Comment by mik-dass** [comment]
@anmolbabu I will try to check on windows if I find a suitable machine

**Comment by surajnarwade** [comment]
Closing this as we dont have `--local` flag but we do have `--context` and suggestions are working for it :tada: 

@kadel , reopen if it's not working for you
