### ISSUE TITLE
odo update cmd imporvement adding wait flag

### ISSUE THREAD

**Issue by syamgk** [openshift/odo#994]
[kind/Enhancement]

## What should odo do differently? Which functionality do you think we should change?

`$ odo update`  
can have an option to choose between
-  prevent from following the logs and unblock the shell than waiting for the build to finish
-  blocking the shell and streaming the build logs 
## What are you trying to do?

doing `odo update` and its taking a while(till the build to finish) for releasing the shell

**Comment by kadel** [comment]
not relevant with new workflow implementation
/close
